### ISSUE TITLE
modify_table nemesis: Cannot set default_time_to_live on a table with counters

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla-cluster-tests#1037]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: branch-2019.1
* **scylla**:  2019.1.1-0.20190609.ff2c600c9

### Logs
* test_id: d019fda0-d522-4d5a-bd9c-ea11dabbae4d
* job log: http://jenkins.scylladb.com/job/scylla-staging/job/longevity-encryption-tests/job/longevity-in-memory-test/10/

### Description

Modify_table nemesis chooses first non-system table, and modify efault_time_to_live of it.
But table with counters doesn't support this.

* prepare_write_cmd:
  - ["cassandra-stress write         cl=QUORUM n=21000000     -schema 'replication(factor=3)' -port jmx=6868 -mode cql3 native -rate threads=500 -pop seq=1..21000000 -col 'size=FIXED(200) n=FIXED(5)' -log interval=10", 
  - "cassandra-stress counter_write cl=QUORUM n=12345678     -schema 'replication(factor=3)' -port jmx=6868 -mode cql3 native -rate threads=100 -pop seq=1..12345678"]

```
cqlsh> desc keyspace1;

CREATE KEYSPACE keyspace1 WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '3'}  AND durable_writes = true;

CREATE TABLE keyspace1.counter1 (
    key blob,
    column1 text,
    "C0" counter static,
    "C1" counter static,
    "C2" counter static,
    "C3" counter static,
    "C4" counter static,
    value counter,
    PRIMARY KEY (key, column1)
) WITH COMPACT STORAGE
    AND CLUSTERING ORDER BY (column1 ASC)
    AND bloom_filter_fp_chance = 0.458984320926
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = 'BnAowQgXbslcAGDLeDVkocVG'
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 1024
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 256
    AND read_repair_chance = 0.0
    AND speculative_retry = '813.00ms';

CREATE TABLE keyspace1.standard1 (
    key blob PRIMARY KEY,
    "C0" blob,
    "C1" blob,
    "C2" blob,
    "C3" blob,
    "C4" blob
) WITH COMPACT STORAGE
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = 'test cf'
    AND compaction = {'class': 'InMemoryCompactionStrategy'}
    AND compression = {}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

cqlsh> 
```

### Steps to Reproduce

1. occurs in longevity-in-memory-4days

**Expected behavior:** [What you expected to happen]
ALETER statement executes successfully.

**Actual behavior:** [What actually happened]
```
2019-06-12 14:35:43,845 remote           L0905 DEBUG| Remote [centos@172.30.0.79]: Running 'cqlsh  -e "ALTER TABLE keyspace1.counter1 WITH default_time_to_live = 544659690;" 172.30.0.79'
2019-06-12 14:35:43,846 remote           L0103 INFO | [172.30.0.79] Running '/bin/ssh  -a -x   -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpWJYZry -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l centos -p 22 -i /home/jenkins/.ssh/scylla-qa-ec2 172.30.0.79 "cqlsh  -e \"ALTER TABLE keyspace1.counter1 WITH default_time_to_live = 544659690;\" 172.30.0.79"'
2019-06-12 14:35:44,005 remote           L0203 DEBUG| [172.30.0.241] [stdout] total,    1446219510,   14906,   14906,   14906,     0.7,     0.6,     0.8,     1.0,     5.9,    33.0,97446.0,  0.00051,      0,      0,       0,       0,       0,       0
2019-06-12 14:35:44,005 remote           L0203 DEBUG| [172.30.0.65] [stdout] total,    1371265839,   14186,   14186,   14186,     0.7,     0.7,     0.8,     1.1,     3.1,   203.9,97476.0,  0.00053,      0,      0,       0,       0,       0,       0
2019-06-12 14:35:44,660 remote           L0203 DEBUG| [172.30.0.79] [stderr] <stdin>:1:InvalidRequest: Error from server: code=2200 [Invalid query] message="Cannot set default_time_to_live on a table with counters"
2019-06-12 14:35:44,824 nemesis          L0503 ERROR| sdcm.nemesis.ChaosMonkey: Exception in random_disrupt_method modify_table: Command '/bin/ssh  -a -x   -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpWJYZry -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l centos -p 22 -i /home/jenkins/.ssh/scylla-qa-ec2 172.30.0.79 "cqlsh  -e \"ALTER TABLE keyspace1.counter1 WITH default_time_to_live = 544659690;\" 172.30.0.79"' failed (rc=2)
2019-06-12 14:35:44,825 nemesis          L0891 ERROR| sdcm.nemesis.ChaosMonkey: Unhandled exception in method <function disrupt at 0x7fe22ec88d70>
Traceback (most recent call last):
  File "/sct/sdcm/nemesis.py", line 887, in wrapper
    result = method(*args, **kwargs)
  File "/sct/sdcm/nemesis.py", line 1059, in disrupt
    self.call_random_disrupt_method()
  File "/sct/sdcm/nemesis.py", line 501, in call_random_disrupt_method
    disrupt_method()
  File "/sct/sdcm/nemesis.py", line 735, in disrupt_modify_table
    disrupt_func()
  File "/sct/sdcm/nemesis.py", line 672, in modify_table_default_time_to_live
    self._modify_table_property(name="default_time_to_live", val=random.randint(864000, 630720000))  # max allowed TTL - 20 years (630720000)
  File "/sct/sdcm/nemesis.py", line 583, in _modify_table_property
    self._run_in_cqlsh(cmd)
  File "/sct/sdcm/nemesis.py", line 569, in _run_in_cqlsh
    node.remoter.run('cqlsh {} -e "{}" {}'.format(cql_auth, cmd, node.private_ip_address), verbose=True)
  File "/sct/sdcm/remote.py", line 916, in run
    watch_stdout_pattern=watch_stdout_pattern)
  File "/sct/sdcm/remote.py", line 857, in _run
    watch_stdout_pattern=watch_stdout_pattern)
  File "/sct/sdcm/remote.py", line 814, in ssh_run
    raise process.CmdError(cmd, sp.result)
CmdError: Command '/bin/ssh  -a -x   -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpWJYZry -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l centos -p 22 -i /home/jenkins/.ssh/scylla-qa-ec2 172.30.0.79 "cqlsh  -e \"ALTER TABLE keyspace1.counter1 WITH default_time_to_live = 544659690;\" 172.30.0.79"' failed (rc=2)
```

**Comment by amoskong** [comment]
Test job: http://jenkins.scylladb.com/job/scylla-staging/job/longevity-encryption-tests/job/longevity-in-memory-test/10/

**Comment by amoskong** [comment]
Related Commit f548c6b9 , PR https://github.com/scylladb/scylla-cluster-tests/pull/942

/CC @juliayakovlev

**Comment by juliayakovlev** [comment]
> Related Commit [f548c6b](https://github.com/scylladb/scylla-cluster-tests/commit/f548c6b9c39d446d057605fbef4d8efbdfb07e4e) , PR #942
> 
> /CC @juliayakovlev

Fix in opened PR: https://github.com/scylladb/scylla-cluster-tests/pull/1041
Thanks
