### ISSUE TITLE
AttributeError: No attribute or config key found for 'runners'

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#1046]
### Prerequisites

* [X] Are you rebased to master ?
* [X] Is it reproducible ?
* [X] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: fix_logging
* **scylla**: 3.0.6

### Logs
* test_id: 198079bf-703a-4f62-9b7e-7cb709bac69c
* job log: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/empty/job/longevity/job/longevity-10gb-3h/10/console

### Description

Command running in background thread, might fail with this errors:

```
08:21:26  Exception in thread Thread-8:
08:21:26  Traceback (most recent call last):
08:21:26    File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
08:21:26      self.run()
08:21:26    File "/usr/lib64/python2.7/threading.py", line 765, in run
08:21:26      self.__target(*self.__args, **self.__kwargs)
08:21:26    File "/sct/sdcm/cluster.py", line 768, in backtrace_thread
08:21:26      self.get_backtraces()
08:21:26    File "/sct/sdcm/cluster.py", line 749, in get_backtraces
08:21:26      self.wait_ssh_up(verbose=False)
08:21:26    File "/sct/sdcm/cluster.py", line 888, in wait_ssh_up
08:21:26      self.install_sct_log_formatter()
08:21:26    File "/sct/sdcm/cluster.py", line 572, in install_sct_log_formatter
08:21:26      result = self.remoter.run('test -e /var/tmp/sct_log_formatter', verbose=False, ignore_status=True)
08:21:26    File "/sct/sdcm/remote.py", line 243, in run
08:21:26      watchers=watchers, cmd_timeout=timeout)
08:21:26    File "/sct/sdcm/remote.py", line 59, in run
08:21:26      return super(ConnectionCmdTimeout, self).run(command, **kwargs)
08:21:26    File "<decorator-gen-3>", line 2, in run
08:21:26    File "/usr/lib/python2.7/site-packages/fabric/connection.py", line 30, in opens
08:21:26      return method(self, *args, **kwargs)
08:21:26    File "/usr/lib/python2.7/site-packages/fabric/connection.py", line 702, in run
08:21:26      return self._run(self._remote_runner(), command, **kwargs)
08:21:26    File "/usr/lib/python2.7/site-packages/fabric/connection.py", line 685, in _remote_runner
08:21:26      return self.config.runners.remote(self, inline_env=self.inline_ssh_env)
08:21:26    File "/usr/lib/python2.7/site-packages/invoke/config.py", line 125, in __getattr__
08:21:26      raise AttributeError(err)
08:21:26  AttributeError: No attribute or config key found for 'runners'
08:21:26  
08:21:26  Valid keys: ['run', 'tasks', 'timeouts']
08:21:26  
08:21:26  Valid real attributes: ['clear', 'clone', 'env_prefix', 'file_prefix', 'from_data', 'from_v1', 'global_defaults', 'load_base_conf_files', 'load_collection', 'load_defaults', 'load_overrides', 'load_project', 'load_runtime', 'load_shell_env', 'load_ssh_config', 'load_system', 'load_user', 'merge', 'pop', 'popitem', 'prefix', 'set_project_location', 'set_runtime_path', 'set_runtime_ssh_path', 'setdefault', 'update']
08:21:26  
```

**Comment by fruch** [comment]
@aleksbykov any thoughts what might make this fail on a background thread like that ?

**Comment by aleksbykov** [comment]
@fruch is it always happened?
Looked into invoke and fabric code, the runners attirbute  defined in both as allowed.
