### ISSUE TITLE
Exception in random_disrupt_method modify_table: (1, 'Administratively prohibited')

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla-cluster-tests#1080]
### Prerequisites

* [ ] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: branch-3.1

### Logs
* test_id: dd5f218f-e141-415c-9fea-b2ccd6cde4ca
* test job: http://jenkins.scylladb.com/job/scylla-3.1/job/longevity/job/longevity-50gb-4days/4/

### Description

It seems a SSH connection issue of one random loader node.

### Steps to Reproduce

1. all modify_table nemesis failed for same exception

**Expected behavior:** [What you expected to happen]
Modify_table succeeds.

**Actual behavior:** [What actually happened]

```
2019-06-26 21:25:12,891 nemesis          L0543 INFO | sdcm.nemesis.ChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method modify_table
2019-06-26 21:25:12,892 nemesis          L0296 DEBUG| sdcm.nemesis.ChaosMonkey: Set current_disruption -> ModifyTablePropertiesMaxIndexInterval Node longevity-tls-50gb-4d-3-1-db-node-dd5f218f
-9 [34.254.191.58 | 10.0.154.165] (seed: False)
2019-06-26 21:25:12,892 nemesis          L0298 INFO | sdcm.nemesis.ChaosMonkey: ModifyTablePropertiesMaxIndexInterval Node longevity-tls-50gb-4d-3-1-db-node-dd5f218f-9 [34.254.191.58 | 10.0.1
54.165] (seed: False)
2019-06-26 21:25:12,903 sct_events       L0387 INFO | 2019-06-26 21:25:12.892: (DisruptionEvent Severity.NORMAL): type=start name=ModifyTablePropertiesMaxIndexInterval node=Node longevity-tls
-50gb-4d-3-1-db-node-dd5f218f-9 [34.254.191.58 | 10.0.154.165] (seed: False) duration=None
2019-06-26 21:25:12,908 connectionpool   L0208 DEBUG| Starting new HTTP connection (1): 63.32.61.162
2019-06-26 21:25:12,913 nemesis          L0549 ERROR| sdcm.nemesis.ChaosMonkey: Exception in random_disrupt_method modify_table: (1, 'Administratively prohibited')
2019-06-26 21:25:12,913 nemesis          L0953 ERROR| sdcm.nemesis.ChaosMonkey: Unhandled exception in method <function disrupt at 0x7fbc5e6a1d70>
Traceback (most recent call last):
  File "/sct/sdcm/nemesis.py", line 949, in wrapper
    result = method(*args, **kwargs)
  File "/sct/sdcm/nemesis.py", line 1161, in disrupt
    self.call_random_disrupt_method()
  File "/sct/sdcm/nemesis.py", line 547, in call_random_disrupt_method
    disrupt_method()
  File "/sct/sdcm/nemesis.py", line 782, in disrupt_modify_table
    disrupt_func()
  File "/sct/sdcm/nemesis.py", line 728, in modify_table_max_index_interval
    self._modify_table_property(name="max_index_interval", val=random.choice([1024, 4096, 8192]))
  File "/sct/sdcm/nemesis.py", line 623, in _modify_table_property
    db_node_ip=self.target_node.ip_address)
  File "/sct/sdcm/cluster.py", line 3019, in get_non_system_ks_cf_list
    .format(request_timeout, cmd, db_node_ip), verbose=False)
  File "/sct/sdcm/remote.py", line 247, in run
    watchers=watchers, cmd_timeout=timeout)
  File "/sct/sdcm/remote.py", line 64, in run
    return super(ConnectionCmdTimeout, self).run(command, **kwargs)
  File "<decorator-gen-3>", line 2, in run
  File "/usr/lib/python2.7/site-packages/fabric/connection.py", line 30, in opens
    return method(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/fabric/connection.py", line 702, in run
    return self._run(self._remote_runner(), command, **kwargs)
  File "/usr/lib/python2.7/site-packages/invoke/context.py", line 101, in _run
    return runner.run(command, **kwargs)
  File "/usr/lib/python2.7/site-packages/invoke/runners.py", line 271, in run
    return self._run_body(command, **kwargs)
  File "/usr/lib/python2.7/site-packages/invoke/runners.py", line 285, in _run_body
    self.start(command, shell, env)
  File "/usr/lib/python2.7/site-packages/fabric/runners.py", line 36, in start
    self.channel = self.context.create_session()
  File "<decorator-gen-8>", line 2, in create_session
  File "/usr/lib/python2.7/site-packages/fabric/connection.py", line 30, in opens
    return method(self, *args, **kwargs)
  File "/sct/sdcm/remote.py", line 68, in create_session
    channel = super(ConnectionCmdTimeout, self).create_session()
  File "<decorator-gen-2>", line 2, in create_session
  File "/usr/lib/python2.7/site-packages/fabric/connection.py", line 30, in opens
    return method(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/fabric/connection.py", line 679, in create_session
    channel = self.transport.open_session()
  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 806, in open_session
    timeout=timeout,
  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 944, in open_channel
    raise e
ChannelException: (1, 'Administratively prohibited')
2019-06-26 21:25:12,916 nemesis          L0966 DEBUG| sdcm.nemesis.ChaosMonkey: ModifyTablePropertiesMaxIndexInterval Node longevity-tls-50gb-4d-3-1-db-node-dd5f218f-9 [34.254.191.58 | 10.0.154.165] (seed: False) duration -> 0 s

```

**Comment by amoskong** [comment]
reference: https://unix.stackexchange.com/questions/14160/ssh-tunneling-error-channel-1-open-failed-administratively-prohibited-open

**Comment by amoskong** [comment]
@fruch @bentsi any suggestion?

**Comment by fruch** [comment]
you have a job this is still happening?  does it happen anywhere except modify table nemesis ?

**Comment by amoskong** [comment]
The new longevity-50gb-4days was aborted unexpectedly, and modify_table
Nemesis isn't executed.
It only happened in modify_table nemesis.

**Comment by bentsi** [comment]
we opened too many commands on in parallel, probably we need to alter SSH/D configuration
https://stackoverflow.com/questions/16698814/paramiko-channelexception-administratively-prohibited-encountered-midway-thro

**Comment by fruch** [comment]
https://github.com/scylladb/scylla-cluster-tests/pull/1203 addressed this issue
