### ISSUE TITLE
sdcm.nemesis.ChaosMonkey: Cluster doesn't contain free nonseeds nodes. Test will failed

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-cluster-tests#1093]
### Prerequisites

* [ ] Are you rebased to master ? - Jenkins job
* [ ] ~~Is it reproducible ?~~
* [X] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: [branch or hash tag you are working on] 3.1
* **scylla**: [branch or commit hash]  3.1.0.rc2-0.20190624.433cb93f7

### Logs
* test_id: [look for 'the Test ID' at the end of the log] 1aea54fe-c154-4724-b2a8-0972029f1704 | 
* job log: [e.x. https://cloudius-jenkins-test.s3.amazonaws.com/5a2c3b72-40f8-4992-8b5a-5c4aec8bf0c6/job-2019-05-14T09.59-c85338a.zip] https://jenkins.scylladb.com/view/scylla-3.1/job/scylla-3.1/job/longevity/job/longevity-large-partition-4days/3/console

### Description

Nemesis thread failed and stopped during large partition longevity
Jenkins job: [Large partition job](https://jenkins.scylladb.com/view/scylla-3.1/job/scylla-3.1/job/longevity/job/longevity-large-partition-4days/3/console)

Last cluster status output before crash:
```
2019-06-28 14:09:52,282 nemesis          L0931 INFO | sdcm.nemesis.ChaosMonkey: Status for regular Node longevity-large-partitions-4d-3-1-db-node-1aea54fe-8 [34.244.187.205 | 10.0.138.18] (seed: False): Command exited with status 0.
=== stdout ===
Datacenter: eu-west
===================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address       Load       Tokens       Owns    Host ID                               Rack
UN  10.0.75.2     239.97 GB  256          ?       66f9fb32-4bc2-45de-860d-e9fd51f8094d  1a
UN  10.0.138.18   479.25 GB  256          ?       db7324a8-b846-44b9-adbf-2ad13885d525  1a
UN  10.0.8.199    317.22 GB  256          ?       4fb66155-e4e5-49c6-9ece-9df0ab15c269  1a
UN  10.0.176.141  483.23 GB  256          ?       07cd70c1-542c-4457-8375-db4398d948af  1a

```

Error:
```
2019-06-28 14:39:52,283 nemesis          L0104 DEBUG| sdcm.nemesis.ChaosMonkey: List of NonSeed nodes: []
2019-06-28 14:39:52,283 test             L0142 WARNI| sdcm.nemesis.ChaosMonkey: Cluster doesn't contain free nonseeds nodes. Test will failed
2019-06-28 14:39:52,283 output           L0642 DEBUG| Thread-1361: <Thread(Thread-1361, started daemon 139645970974464)>.__bootstrap(): unhandled exception
2019-06-28 14:39:52,285 output           L0642 DEBUG| Exception in thread Thread-1361:
2019-06-28 14:39:52,285 output           L0642 DEBUG| Traceback (most recent call last):
2019-06-28 14:39:52,286 output           L0642 DEBUG|   File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
2019-06-28 14:39:52,286 output           L0642 DEBUG|     self.run()
2019-06-28 14:39:52,286 output           L0642 DEBUG|   File "/usr/lib64/python2.7/threading.py", line 765, in run
2019-06-28 14:39:52,286 output           L0642 DEBUG|     self.__target(*self.__args, **self.__kwargs)
2019-06-28 14:39:52,286 output           L0642 DEBUG|   File "/sct/sdcm/nemesis.py", line 127, in run
2019-06-28 14:39:52,287 output           L0642 DEBUG|     self.set_target_node(is_running=True)
2019-06-28 14:39:52,287 output           L0642 DEBUG|   File "/sct/sdcm/nemesis.py", line 107, in set_target_node
2019-06-28 14:39:52,287 output           L0642 DEBUG|     self.target_node = random.choice(non_seed_nodes)
2019-06-28 14:39:52,287 output           L0642 DEBUG|   File "/usr/lib64/python2.7/random.py", line 274, in choice
2019-06-28 14:39:52,287 output           L0642 DEBUG|     return seq[int(self.random() * len(seq))]  # raises IndexError if seq is empty
2019-06-28 14:39:52,287 output           L0642 DEBUG| IndexError: list index out of range
```

Nemesis were started before:
```
2019-06-27 09:23:13,296 nemesis          L0551 INFO | sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method stop_start_scylla_server
2019-06-27 09:53:28,747 nemesis          L0551 INFO | sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method nodetool_refresh
2019-06-27 10:24:39,800 nemesis          L0551 INFO | sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method hard_reboot_node
2019-06-27 11:54:26,255 nemesis          L0551 INFO | sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method nodetool_cleanup
2019-06-27 12:35:56,103 nemesis          L0551 INFO | sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method major_compaction
2019-06-27 13:53:42,811 nemesis          L0551 INFO | sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method mgmt_repair_api
2019-06-27 14:31:45,490 nemesis          L0551 INFO | sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method no_corrupt_repair
2019-06-27 15:28:16,059 nemesis          L0551 INFO | sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method nodetool_decommission
2019-06-27 15:59:25,774 nemesis          L0551 INFO | sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method hard_reboot_node
2019-06-27 16:30:44,165 nemesis          L0551 INFO | sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method hard_reboot_node
2019-06-27 17:02:03,950 nemesis          L0551 INFO | sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method nodetool_drain
2019-06-27 19:25:56,077 nemesis          L0551 INFO | sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method restart_then_repair_node
2019-06-27 20:00:12,164 nemesis          L0551 INFO | sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method soft_reboot_node
2019-06-27 21:00:32,823 nemesis          L0551 INFO | sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method nodetool_refresh
2019-06-27 22:00:26,965 nemesis          L0551 INFO | sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method terminate_and_replace_node
2019-06-27 22:36:42,285 nemesis          L0551 INFO | sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method stop_wait_start_scylla_server
2019-06-27 23:09:04,907 nemesis          L0551 INFO | sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method nodetool_enospc
2019-06-28 00:15:26,698 nemesis          L0551 INFO | sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method no_corrupt_repair
2019-06-28 00:47:49,604 nemesis          L0551 INFO | sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method nodetool_enospc
2019-06-28 01:18:18,802 nemesis          L0551 INFO | sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method truncate
2019-06-28 02:24:24,896 nemesis          L0551 INFO | sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method abort_repair
2019-06-28 02:54:39,530 nemesis          L0551 INFO | sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method modify_table
2019-06-28 03:57:41,265 nemesis          L0551 INFO | sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method abort_repair
2019-06-28 04:27:58,454 nemesis          L0551 INFO | sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method snapshot_operations
2019-06-28 05:45:26,119 nemesis          L0551 INFO | sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method restart_then_repair_node
2019-06-28 06:47:59,830 nemesis          L0551 INFO | sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method modify_table
2019-06-28 07:18:17,169 nemesis          L0551 INFO | sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method modify_table
2019-06-28 07:51:41,321 nemesis          L0551 INFO | sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method validate_hh_short_downtime
2019-06-28 09:00:58,479 nemesis          L0551 INFO | sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method nodetool_enospc
2019-06-28 09:34:23,307 nemesis          L0551 INFO | sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method validate_hh_short_downtime
2019-06-28 12:12:30,372 nemesis          L0551 INFO | sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method nodetool_decommission
2019-06-28 12:48:43,424 nemesis          L0551 INFO | sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method stop_wait_start_scylla_server
2019-06-28 14:09:47,684 nemesis          L0551 INFO | sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method terminate_and_replace_node
```

**Comment by aleksbykov** [comment]
@juliayakovlev This happens, because threre is no seeds node left. We have a parameter in config "nemesis_filter_seeds". Try to use it.

**Comment by roydahan** [comment]
This may be a workaround but not a solution.
Seems like new nodes that we are adding are set with a flag to not run a nemesis on that we never remove.

**Comment by juliayakovlev** [comment]
> @juliayakovlev This happens, because threre is no seeds node left. We have a parameter in config "nemesis_filter_seeds". Try to use it.

@aleksbykov  When this error was received, no nemesises were run and were 3 non-seed nodes in the "UP" status that may be used
