### ISSUE TITLE
Cassandra-stress load is stopped on timeout despite the timeout is not reached

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-cluster-tests#1097]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: [branch or hash tag you are working on] juliayakovlev/sla_per_user_next_tests branch
* **scylla**: [branch or commit hash] master

### Description

Cassandra-stress load is stopped unexpectedly on timeout despite the timeout is not reached.

Test starts 2 different c-s commands from 2 loaders (round robin) for 10 minutes.
Load started and ran a few seconds, but reported that timeout of 43800 sec (it's duration of full test, not current c-s command)  was exceeded:

Interrupted load:
```
< t:2019-06-26 05:43:15,102 f:remote.py       l:678  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@3.82.138.141]: total,       2460699,   84664,   84664,   84664,     2.9,     2.9,     4.0,     4.7,     6.9,    11.3,   31.0,  0.03389,      0,      0,       0,       0,       0,       0
< t:2019-06-26 05:43:15,102 f:remote.py       l:678  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@54.83.150.235]: total,       6567958,   88102,   88102,   88102,     2.8,     2.8,     3.8,     4.4,    12.0,    14.4,   60.0,  0.03379,      0,      0,       0,       0,       0,       0
< t:2019-06-26 05:43:15,119 f:remote.py       l:678  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@3.87.200.3]: total,       2785842,   91832,   91832,   91832,     2.7,     2.7,     3.7,     4.4,     9.3,    11.4,   31.0,  0.01442,      0,      0,       0,       0,       0,       0
< t:2019-06-26 05:43:16,038 f:tester.py       l:1585 c:sdcm.tester          p:INFO  > TearDown is starting...
< t:2019-06-26 05:43:16,049 f:sct_events.py   l:387  c:sdcm.sct_events      p:INFO  > 2019-06-26 05:43:16.038: (InfoEvent Severity.NORMAL): message=TEST_END
```

Error:
```
ERROR [1100.865s]: test_two_slas_one_to_five_ratio_mix_load (sla_per_user_system_test.SlaPerUserTest1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/sct/sla_per_user_system_test.py", line 297, in test_two_slas_one_to_five_ratio_mix_load
    self._two_users_load_througput_workload(shares=[190, 950], load=self.MIXED_LOAD)
  File "/sct/sla_per_user_system_test.py", line 301, in _two_users_load_througput_workload
    self.create_test_data()
  File "/sct/sla_per_user_system_test.py", line 73, in create_test_data
    'stats_aggregate_cmds': False})
  File "/sct/sla_per_user_system_test.py", line 188, in run_stress_and_verify_threads
    self.verify_stress_thread(cs_thread_pool=queue)
  File "/sct/sdcm/tester.py", line 1113, in verify_stress_thread
    results, errors = cs_thread_pool.verify_results()
  File "/sct/sdcm/stress_thread.py", line 193, in verify_results
    results.append(future.result())
  File "/usr/lib/python2.7/site-packages/concurrent/futures/_base.py", line 455, in result
    return self.__get_result()
  File "/usr/lib/python2.7/site-packages/concurrent/futures/thread.py", line 63, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/sct/sdcm/stress_thread.py", line 140, in _run_stress
    log_file=log_file_name)
  File "/sct/sdcm/remote.py", line 254, in run
    raise CmdExecTimeoutExceeded(error_msg)
CmdExecTimeoutExceeded: Time of command "echo TAG: loader_idx:1-cpu_idx:0-keyspace_idx:1; cassandra-stress write cl=QUORUM n=200000000 -schema keyspace=keyspace1 'replication(factor=3)' -port jmx=6868 -mode cql3 native user=cassandra password=cassandra -rate threads=250 -node 172.30.0.141" execution exceeded timeout 43800
```

**Expected behavior:**
C-s load should run 10 min and print out the statistics

**Actual behavior:**
C-s load interrupted after a few seconds. No statistics

**Comment by bentsi** [comment]
fixed in #1114
