### ISSUE TITLE
AttributeError: No attribute or config key found for 'cmd_timeout'

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#1105]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master
* **scylla**: 3.1.0.rc2

### Logs
* test_id: f08e57b4-72c3-4c2b-8d65-6df8fc87dca5 

### Description
this failure caused losing the log for an instance

```python
102:Traceback (most recent call last):                                                                                                                                                                                   [0/24978]
103-  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
104-    self.run()
105-  File "/usr/lib64/python2.7/threading.py", line 765, in run
106-    self.__target(*self.__args, **self.__kwargs)
107-  File "/sct/sdcm/cluster.py", line 764, in backtrace_thread
108-    self.get_backtraces()
109-  File "/sct/sdcm/cluster.py", line 749, in get_backtraces
110-    new_n_coredumps = self._get_n_coredumps()
111-  File "/sct/sdcm/cluster.py", line 736, in _get_n_coredumps
112-    result = self.remoter.run(n_backtraces_cmd, verbose=False, ignore_status=True)
113-  File "/sct/sdcm/remote.py", line 243, in run
114-    watchers=watchers, cmd_timeout=timeout)
115-  File "/sct/sdcm/remote.py", line 59, in run
116-    return super(ConnectionCmdTimeout, self).run(command, **kwargs)
117-  File "<decorator-gen-3>", line 2, in run
118-  File "/usr/lib/python2.7/site-packages/fabric/connection.py", line 30, in opens
119-    return method(self, *args, **kwargs)
120-  File "/usr/lib/python2.7/site-packages/fabric/connection.py", line 702, in run
121-    return self._run(self._remote_runner(), command, **kwargs)
122-  File "/usr/lib/python2.7/site-packages/invoke/context.py", line 101, in _run
123-    return runner.run(command, **kwargs)
124-  File "/usr/lib/python2.7/site-packages/invoke/runners.py", line 271, in run
125-    return self._run_body(command, **kwargs)
126-  File "/usr/lib/python2.7/site-packages/invoke/runners.py", line 285, in _run_body
127-    self.start(command, shell, env)
128-  File "/usr/lib/python2.7/site-packages/fabric/runners.py", line 36, in start
129-    self.channel = self.context.create_session()
130-  File "<decorator-gen-8>", line 2, in create_session
131-  File "/usr/lib/python2.7/site-packages/fabric/connection.py", line 30, in opens
132-    return method(self, *args, **kwargs)
133-  File "/sct/sdcm/remote.py", line 64, in create_session
134-    if self.cmd_timeout:
135-  File "/usr/lib/python2.7/site-packages/invoke/config.py", line 125, in __getattr__
136-    raise AttributeError(err)
137-AttributeError: No attribute or config key found for 'cmd_timeout'
138-
139-Valid keys: ['run', 'tasks', 'timeouts']
140-
141-Valid real attributes: ['cd', 'clear', 'client', 'close', 'config', 'connect_kwargs', 'connect_timeout', 'create_session', 'cwd', 'derive_shorthand', 'forward_agent', 'forward_local', 'forward_remote', 'from_data', 'from_v1', 'gateway', 'get', 'get_gateway', 'host', 'is_connected', 'local', 'open', 'open_gateway', 'original_host', 'pop', 'popitem', 'port', 'prefix', 'put', 'resolve_connect_kwargs', 'run', 'setdefault', 'sftp', 'ssh_config', 'sudo', 'transport', 'update', 'user']
```

**Comment by fruch** [comment]
@bentsi, maybe we could try fixing it in #1098 
I think we only need `getatter(self, 'cmd_timeout', None)` there to fix it

**Comment by aleksbykov** [comment]
i saw situation, when such error talk about missing attribute 'run' or 'tasks'.

**Comment by fruch** [comment]
@aleksbykov seems like messing with the fabric internal is causing us too much harm.

hopefully we'll get rid of it soon

**Comment by amoskong** [comment]
I also touched this problem in longevity-3.1-50GB job
- http://jenkins.scylladb.com/job/scylla-3.1/job/longevity/job/longevity-50gb-4days/6/
- test id: 179c22c3-f980-4bc2-a8bb-761e7254b19c
- branch-3.1

```
2019-07-03 07:23:55,785 cluster          L2037 ERROR| Cluster longevity-tls-50gb-4d-3-1-db-cluster-179c22c3 (AMI: ['ami-08f0f9bd6c5f677fb'] Type: i3.4xlarge): Node setup failed: Node longevit
y-tls-50gb-4d-3-1-db-node-179c22c3-10 [52.30.131.26 | 10.0.42.84] (seed: False)
Traceback (most recent call last):
  File "/sct/sdcm/cluster.py", line 2035, in node_setup
    cl_inst.node_setup(node, **setup_kwargs)
  File "/sct/sdcm/cluster_aws.py", line 646, in node_setup
    node.stop_scylla_server(verify_down=False)
  File "/sct/sdcm/cluster.py", line 1730, in stop_scylla_server
    self.remoter.run('sudo systemctl stop scylla-server.service', timeout=timeout, ignore_status=ignore_status)
  File "/sct/sdcm/remote.py", line 247, in run
    watchers=watchers, cmd_timeout=timeout)
  File "/sct/sdcm/remote.py", line 64, in run
    return super(ConnectionCmdTimeout, self).run(command, **kwargs)
  File "<decorator-gen-3>", line 2, in run
  File "/usr/lib/python2.7/site-packages/fabric/connection.py", line 30, in opens
    return method(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/fabric/connection.py", line 702, in run
    return self._run(self._remote_runner(), command, **kwargs)
  File "/usr/lib/python2.7/site-packages/invoke/context.py", line 101, in _run
    return runner.run(command, **kwargs)
  File "/usr/lib/python2.7/site-packages/invoke/runners.py", line 271, in run
    return self._run_body(command, **kwargs)
  File "/usr/lib/python2.7/site-packages/invoke/runners.py", line 285, in _run_body
    self.start(command, shell, env)
  File "/usr/lib/python2.7/site-packages/fabric/runners.py", line 36, in start
    self.channel = self.context.create_session()
  File "<decorator-gen-8>", line 2, in create_session
  File "/usr/lib/python2.7/site-packages/fabric/connection.py", line 30, in opens
    return method(self, *args, **kwargs)
  File "/sct/sdcm/remote.py", line 69, in create_session
    if self.cmd_timeout:
  File "/usr/lib/python2.7/site-packages/invoke/config.py", line 125, in __getattr__
    raise AttributeError(err)
AttributeError: No attribute or config key found for 'cmd_timeout'

Valid keys: ['ServerAliveInterval', 'StrictHostKeyChecking', 'UserKnownHostsFile', 'cmd_timeout', 'connect_kwargs', 'forward_agent', 'gateway', 'inline_ssh_env', 'load_ssh_config', 'load_ssh_configs', 'port', 'run', 'runners', 'ssh_config_path', 'sudo', 'tasks', 'timeouts', 'user']

Valid real attributes: ['cd', 'clear', 'client', 'close', 'config', 'connect_kwargs', 'connect_timeout', 'create_session', 'cwd', 'derive_shorthand', 'forward_agent', 'forward_local', 'forward_remote', 'from_data', 'from_v1', 'gateway', 'get', 'get_gateway', 'host', 'is_connected', 'local', 'open', 'open_gateway', 'original_host', 'pop', 'popitem', 'port', 'prefix', 'put', 'resolve_connect_kwargs', 'run', 'setdefault', 'sftp', 'ssh_config', 'sudo', 'transport', 'update', 'user']
```

**Comment by amoskong** [comment]
I can still see this error in 
- job: https://jenkins.scylladb.com/view/scylla-4.1/job/scylla-4.1/job/longevity/job/longevity-2tb-4days-1Dis-2NonDis-Nemesises/2

```
Command: 'cqlsh --no-color -u cassandra -p cassandra  --request-timeout=120 --connect-timeout=60 --ssl -e "TRUNCATE ks_truncate.standard1" 10.0.202.60 9042'

Exit code: 2

Stdout:



Stderr:

<stdin>:1:NoHostAvailable:
2020-05-26 00:34:36.980: (ThreadFailedEvent Severity.ERROR): message=No attribute or config key found for 'gateway'

Valid keys: []

Valid real attributes: ['clear', 'clone', 'env_prefix', 'file_prefix', 'from_data', 'from_v1', 'global_defaults', 'load_base_conf_files', 'load_collection', 'load_defaults', 'load_overrides', 'load_project', 'load_runtime', 'load_shell_env', 'load_ssh_config', 'load_system', 'load_user', 'merge', 'pop', 'popitem', 'prefix', 'set_project_location', 'set_runtime_path', 'set_runtime_ssh_path', 'setdefault', 'update']
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/invoke/config.py", line 111, in __getattr__
    return self._get(key)
  File "/usr/local/lib/python3.6/site-packages/invoke/config.py", line 176, in _get
    value = self._config[key]
KeyError: 'gateway'

```

**Comment by fruch** [comment]
@amoskong please open a new issue, this thing was caused by specific issue we had, and isn't related to current code we are usung

**Comment by amoskong** [comment]
> @amoskong please open a new issue, this thing was caused by specific issue we had, and isn't related to current code we are usung

Opened a new one:
- No attribute or config key found for 'gateway' #2187
