### ISSUE TITLE
counter_write workload should be in prepare write stage

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla-cluster-tests#1116]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: branch-3.1, master

### Logs
* test_id: 179c22c3-f980-4bc2-a8bb-761e7254b19c
* test job: http://jenkins.scylladb.com/job/scylla-3.1/job/longevity/job/longevity-50gb-4days/6

### Description

Currently we run both counter_write workloads & counter_read workloads in parallel after prepare_write. The counter_read worklaods failed for key missing.

```
counter_read:
2019-07-02 23:04:36,068 remote           L0682 INFO | RemoteCmdRunner [centos@10.0.106.202]: java.io.IOException: Operation x0 on key(s) [39393737304e37353330]: Data returned was not validate
d
2019-07-02 23:04:36,068 remote           L0682 INFO | RemoteCmdRunner [centos@10.0.106.202]: 
2019-07-02 23:04:36,068 remote           L0682 INFO | RemoteCmdRunner [centos@10.0.106.202]:    at org.apache.cassandra.stress.Operation.error(Operation.java:136)
2019-07-02 23:04:36,068 remote           L0682 INFO | RemoteCmdRunner [centos@10.0.106.202]:    at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:114)
2019-07-02 23:04:36,068 remote           L0682 INFO | RemoteCmdRunner [centos@10.0.106.202]:    at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:101)
2019-07-02 23:04:36,068 remote           L0682 INFO | RemoteCmdRunner [centos@10.0.106.202]:    at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:109)
2019-07-02 23:04:36,069 remote           L0682 INFO | RemoteCmdRunner [centos@10.0.106.202]:    at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:264)
2019-07-02 23:04:36,069 remote           L0682 INFO | RemoteCmdRunner [centos@10.0.106.202]:    at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:468)

counter_read:
2019-07-02 23:05:55,173 remote           L0682 INFO | RemoteCmdRunner [centos@10.0.201.180]: java.io.IOException: Operation x0 on key(s) [343437374c3930383131]: Data returned was not validate
d

counter_read:
2019-07-02 23:05:57,226 remote           L0682 INFO | RemoteCmdRunner [centos@10.0.106.206]: java.io.IOException: Operation x0 on key(s) [504f5036503939503631]: Data returned was not validated
```

* prepare_write_cmd:
  - "cassandra-stress write cl=QUORUM n=100000000 -schema 'replication(factor=3) compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native  -rate threads=500 -pop seq=1..100000000"
* stress_cmd: 
  -cassandra-stress mixed cl=QUORUM duration=5760m -schema 'replication(factor=3) compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native  -rate threads=20 -pop seq=1..100000000 -log interval=5",
  - `"cassandra-stress counter_write cl=QUORUM duration=5760m -schema 'replication(factor=3) compaction(strategy=DateTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native -rate threads=1 -pop seq=1..1000000",`
  - "cassandra-stress user profile=/tmp/cs_mv_profile.yaml ops'(insert=3,read1=1,read2=1,read3=1)' cl=QUORUM duration=5760m -port jmx=6868 -mode cql3 native -rate threads=10",
  - "cassandra-stress write cl=QUORUM duration=5760m -schema 'replication(factor=3) compression=LZ4Compressor compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native compression=lz4 -rate threads=50 -pop seq=1..100000000 -log interval=5",
  - "cassandra-stress write cl=QUORUM duration=5760m -schema 'replication(factor=3) compression=SnappyCompressor compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native compression=snappy -rate threads=50 -pop seq=1..100000000 -log interval=5",
  - "cassandra-stress write cl=QUORUM duration=5760m -schema 'replication(factor=3) compression=DeflateCompressor compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native compression=none -rate threads=50 -pop seq=1..100000000 -log interval=5"
* stress_read_cmd:
  - cassandra-stress read cl=QUORUM duration=5760m -port jmx=6868 -mode cql3 native  -rate threads=50 -pop seq=1..100000000 -log interval=5",
  - `"cassandra-stress counter_read cl=QUORUM duration=5760m -port jmx=6868 -mode cql3 native -rate threads=10 -pop seq=1..1000000",`
  - "cassandra-stress read cl=QUORUM duration=5760m -schema 'replication(factor=3) compression=LZ4Compressor compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native compression=lz4 -rate threads=20 -pop seq=1..100000000 -log interval=5",
  - "cassandra-stress read cl=QUORUM duration=5760m -schema 'replication(factor=3) compression=SnappyCompressor compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native compression=snappy -rate threads=20 -pop seq=1..100000000 -log interval=5",
  - "cassandra-stress read cl=QUORUM duration=5760m -schema 'replication(factor=3) compression=DeflateCompressor compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native compression=none -rate threads=20 -pop seq=1..100000000 -log interval=5"

**Expected behavior:**  run counter_write in prepare stage, and start counter_read when counter_write finished.

**Actual behavior:** counter_write & counter_read are started in parallel

**Comment by amoskong** [comment]
It seems we already support to assign workload list for prepare_write parameter in sct 3.1

```
prepare_write_cmd: [
  "cassandra-stress write cl=QUORUM n=100000000 -schema 
           'replication(factor=3) compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868
           -mode cql3 native  -rate threads=500 -pop seq=1..100000000",
  "cassandra-stress counter_write cl=QUORUM n=1000000 -port jmx=6868 -mode cql3 native
           -rate threads=10 -pop seq=1..1000000"]
```

**Comment by amoskong** [comment]
Note:

We have stuck problem in counter_write (duration=...)
But counter_write (n=....) works well, it can return successfully.
