### ISSUE TITLE
GCE: dense ssh connections from different task threads is treated as attack when user isn't added to system

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla-cluster-tests#1121]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: branch-2019.1

### Logs
* test_job: 
- http://jenkins.scylladb.com/job/enterprise-2019.1/job/rolling-upgrade-tests/job/rolling-upgrade-ubuntu-16.04-test/base_version=2.3,label=gce-qavpc,test_sst3=true,version_desc=2019-1/55/

### Description

We have many upgrade tests on different distros, each distro has many kind of src version (2019.1, 2.3, 2018.1 3.1), very few subtests failed in prepare cluster, one node failed for setup timeout.

I checked the test result of yesterday, total 14 subtests, 3 subtests failed for setup timeout.

One solution is increase the timeout to 600, or 700, or 800.

The instances had been removed, I will try to reproduce the issue and check what's happened in the instance from console log.

### Steps to Reproduce

1. start upgrade tests which will create cluster in GCE.

**Expected behavior:** The instances can be ready (ssh is available) in 500 seconds

**Actual behavior:** One of instance took 600 seconds to get network (ssh) ready, the setup failed for timeout.

```
2019-07-03 13:49:13,872 cluster_gce      L0261 INFO | GCE Cluster rolling-upgrade-u16-2019-1-db-cluster-e30ff5c4 | Image: ubuntu-1604-lts | Root Disk: pd-ssd 50 GB | Local SSD: 1 | Type: n1-highmem-8: Created instance <Node: uuid=be80e77bb74c045b99a5392922599f98d58870ac, name=rolling-upgrade-u16-2019-1-db-node-e30ff5c4-0-4, state=RUNNING, public_ips=[u'35.237.249.117'], private_ips=[u'10.142.0.86'], provider=Google Compute Engine ...>

2019-07-03 13:49:20,252 cluster          L0327 DEBUG| Node rolling-upgrade-u16-2019-1-db-node-e30ff5c4-0-4 [35.237.249.117 | 10.142.0.86] (seed: False): SSH access -> 'ssh -i ~/.ssh/scylla-test scylla-test@10.142.0.86'

2019-07-03 14:00:04,709 cluster          L1848 ERROR| GCE Cluster rolling-upgrade-u16-2019-1-db-cluster-e30ff5c4 | Image: ubuntu-1604-lts | Root Disk: pd-ssd 50 GB | Local SSD: 1 | Type: n1-highmem-8: Node setup failed: Node rolling-upgrade-u16-2019-1-db-node-e30ff5c4-0-4 [35.237.249.117 | 10.142.0.86] (seed: False)
Traceback (most recent call last):
  File "/sct/sdcm/cluster.py", line 1846, in node_setup
    cl_inst.node_setup(node, **setup_kwargs)
  File "/sct/sdcm/cluster.py", line 2306, in node_setup
    node.wait_ssh_up(verbose=verbose)
  File "/sct/sdcm/cluster.py", line 854, in wait_ssh_up
    wait.wait_for(func=self.remoter.is_up, step=10, text=text, timeout=timeout, throw_exc=True)
  File "/sct/sdcm/wait.py", line 54, in wait_for
    raise WaitTimeoutExpired(err)
WaitTimeoutExpired: Wait for: None: timeout - 500 seconds - expired
2019-07-03 14:00:04,879 connectionpool   L0396 DEBUG| https://www.googleapis.com:443 "GET /compute/v1/projects/skilled-adapter-452/zones/us-east1-b/instances/rolling-upgrade-u16-2019-1-db-node-e30ff5c4-0-4 HTTP/1.1" 200 None
2019-07-03 14:00:05,133 connectionpool   L0396 DEBUG| https://www.googleapis.com:443 "GET /compute/v1/projects/skilled-adapter-452/aggregated/disks?maxResults=500 HTTP/1.1" 200 None
2019-07-03 14:00:05,310 connectionpool   L0396 DEBUG| https://www.googleapis.com:443 "GET /compute/v1/projects/skilled-adapter-452/zones/us-east1-b/instances/rolling-upgrade-u16-2019-1-db-node-e30ff5c4-0-4 HTTP/1.1" 200 None
2019-07-03 14:00:05,554 connectionpool   L0396 DEBUG| https://www.googleapis.com:443 "GET /compute/v1/projects/skilled-adapter-452/aggregated/disks?maxResults=500 HTTP/1.1" 200 None
2019-07-03 14:00:05,578 tester           L0133 ERROR| Exception in setUp. Will clean resources
Traceback (most recent call last):
  File "/sct/sdcm/tester.py", line 131, in wrapper
    return method(*args, **kwargs)
  File "/sct/sdcm/tester.py", line 221, in setUp
    self.db_cluster.wait_for_init()
  File "/sct/sdcm/cluster.py", line 1869, in wrapper
    raise NodeSetupFailed("{node}:{node_status}".format(**locals()))
NodeSetupFailed: Node rolling-upgrade-u16-2019-1-db-node-e30ff5c4-0-4 [35.237.249.117 | 10.142.0.86] (seed: False):False
```

```
2019-07-03 14:01:16,332 remote           L0716 ERROR| Remote [scylla-test@10.142.0.86]: Error while executing SSH command: Command: /bin/ssh -tt -a -x  -o ControlPath=/var/tmp/ssh-masterUFXGCA/socket -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpdMIWP2 -o BatchMode=yes -o ConnectTimeout=30 -o ServerAliveInterval=300 -l scylla-test -p 22 -i /jenkins/.ssh/scylla-test 10.142.0.86 "true"
Exit status: -15
Duration: 30.0079660416
Stdout:

Stderr:


2019-07-03 14:01:34,050 remote           L0633 DEBUG| Remote [scylla-test@10.142.0.86]: Send files (src) /sct/data_dir/sct_log_formatter -> (dst) /var/tmp
2019-07-03 14:01:34,164 remote           L0905 DEBUG| Remote [scylla-test@10.142.0.86]: Running 'chmod +x /var/tmp/sct_log_formatter'
2019-07-03 14:01:34,165 remote           L0103 INFO | [10.142.0.86] Running '/bin/ssh -tt -a -x  -o ControlPath=/var/tmp/ssh-master6mqYhv/socket -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpdMIWP2 -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l scylla-test -p 22 -i /jenkins/.ssh/scylla-test 10.142.0.86 "chmod +x /var/tmp/sct_log_formatter"'
2019-07-03 14:01:34,199 remote           L0203 DEBUG| [10.142.0.86] [stderr] Shared connection to 10.142.0.86 closed.
2019-07-03 14:01:34,203 remote           L0905 DEBUG| Remote [scylla-test@10.142.0.86]: Running 'cat /etc/redhat-release'
2019-07-03 14:01:34,203 remote           L0103 INFO | [10.142.0.86] Running '/bin/ssh -tt -a -x  -o ControlPath=/var/tmp/ssh-master6mqYhv/socket -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpdMIWP2 -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l scylla-test -p 22 -i /jenkins/.ssh/scylla-test 10.142.0.86 "cat /etc/redhat-release"'
2019-07-03 14:01:34,238 remote           L0203 DEBUG| [10.142.0.86] [stdout] cat: /etc/redhat-release: No such file or directory
2019-07-03 14:01:34,239 remote           L0203 DEBUG| [10.142.0.86] [stderr] Shared connection to 10.142.0.86 closed.
2019-07-03 14:01:34,242 remote           L0905 DEBUG| Remote [scylla-test@10.142.0.86]: Running 'cat /etc/issue'
2019-07-03 14:01:34,242 remote           L0103 INFO | [10.142.0.86] Running '/bin/ssh -tt -a -x  -o ControlPath=/var/tmp/ssh-master6mqYhv/socket -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpdMIWP2 -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l scylla-test -p 22 -i /jenkins/.ssh/scylla-test 10.142.0.86 "cat /etc/issue"'
2019-07-03 14:01:34,277 remote           L0203 DEBUG| [10.142.0.86] [stdout] Ubuntu 16.04.6 LTS \n \l
2019-07-03 14:01:34,277 remote           L0203 DEBUG| [10.142.0.86] [stderr] Shared connection to 10.142.0.86 closed.
2019-07-03 14:01:34,282 remote           L0203 DEBUG| [10.142.0.86] [stdout]
```

**Comment by amoskong** [comment]
I rerun ubuntu-16 upgrade test (2019.1) 3 times * 4 base_version, but the problem didn't occur.

We triggered upgrade test by artifact-test, artifact-tests of different distros might finish in different time, and trigger upgrade-test at different time.

The problem might only occur when many GCE instances are created at same time range.

**Comment by amoskong** [comment]
I can login by public ip from localhost, but builder failed to login the instance with private ip:

![image](https://user-images.githubusercontent.com/309708/60640623-95dc5180-9e5a-11e9-8c5c-fa258326b7c4.png)


```
$ /bin/ssh -vv -tt -a -x  -o ControlPath=/var/tmp/ssh-masterNzcbQe/socket -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpOpK8eL -o BatchMode=yes -o ConnectTimeout=30 -o ServerAliveInterval=300 -l scylla-test -p 22 -i /jenkins/.ssh/scylla-test 10.142.15.233 "true"
OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 51: Applying options for *
debug1: Control socket "/var/tmp/ssh-masterNzcbQe/socket" does not exist
debug2: resolving "10.142.15.233" port 22
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to 10.142.15.233 [10.142.15.233] port 22.
debug2: fd 3 setting O_NONBLOCK
<stuck>
```

**Comment by amoskong** [comment]
It still hang with simple ssh options:
```
[jenkins@public-jenkins-builder1-qavpc scylla-test]$ ssh -vv -l scylla-test -p 22 -i /jenkins/.ssh/scylla-test 10.142.15.233
OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 51: Applying options for *
debug2: resolving "10.142.15.233" port 22
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to 10.142.15.233 [10.142.15.233] port 22.
<stuck>
```

**Comment by amoskong** [comment]
The problem was reproduced in http://jenkins.scylladb.com/job/scylla-staging/job/rolling-upgrade-ubuntu-16.04-test-clone/base_version=2019.1.0,label=gce-qavpc,test_sst3=true,version_desc=2019-1/2/console

The 4th node (node4) failed to setup (timeout), and SCT connected it by private ip from builder after 11 mins 57 seconds (717 seconds).

But I can successfully login the instance by public ip from localhost.

node4: /var/log/auth.log:
```
Jul  4 04:45:54 rolling-upgrade-u16-2019-1-db-node-73ab38b1-0-4 useradd[1209]: new group: name=ubuntu, GID=1000
Jul  4 04:45:54 rolling-upgrade-u16-2019-1-db-node-73ab38b1-0-4 useradd[1209]: new user: name=ubuntu, UID=1000, GID=1000, home=/home/ubuntu, shell=/bin/bash
....
Jul  4 04:46:09 rolling-upgrade-u16-2019-1-db-node-73ab38b1-0-4 gpasswd[2881]: user tgrabiec added by root to group google-sudoers
Jul  4 04:51:02 rolling-upgrade-u16-2019-1-db-node-73ab38b1-0-4 sshd[2953]: Accepted publickey for scylla-test from 113.201.56.61 port 51161 ssh2: RSA SHA256:ORclW5uOPUGIzX/HqWCBo6YH8GIz8D8MPjTEd0njNms
Jul  4 04:51:02 rolling-upgrade-u16-2019-1-db-node-73ab38b1-0-4 sshd[2953]: pam_unix(sshd:session): session opened for user scylla-test by (uid=0)
Jul  4 04:51:02 rolling-upgrade-u16-2019-1-db-node-73ab38b1-0-4 systemd-logind[1275]: New session 1 of user scylla-test.
Jul  4 04:51:02 rolling-upgrade-u16-2019-1-db-node-73ab38b1-0-4 systemd: pam_unix(systemd-user:session): session opened for user scylla-test by (uid=0)
Jul  4 04:51:31 rolling-upgrade-u16-2019-1-db-node-73ab38b1-0-4 sshd[3031]: Received disconnect from 113.201.56.61 port 51161:11: disconnected by user
Jul  4 04:51:31 rolling-upgrade-u16-2019-1-db-node-73ab38b1-0-4 sshd[3031]: Disconnected from 113.201.56.61 port 51161
Jul  4 04:51:31 rolling-upgrade-u16-2019-1-db-node-73ab38b1-0-4 sshd[2953]: pam_unix(sshd:session): session closed for user scylla-test
Jul  4 04:51:31 rolling-upgrade-u16-2019-1-db-node-73ab38b1-0-4 systemd-logind[1275]: Removed session 1.
Jul  4 04:51:31 rolling-upgrade-u16-2019-1-db-node-73ab38b1-0-4 systemd: pam_unix(systemd-user:session): session closed for user scylla-test
Jul  4 04:51:51 rolling-upgrade-u16-2019-1-db-node-73ab38b1-0-4 sshd[3082]: Accepted publickey for scylla-test from 113.201.56.61 port 51170 ssh2: RSA SHA256:ORclW5uOPUGIzX/HqWCBo6YH8GIz8D8MPjTEd0njNms
Jul  4 04:51:51 rolling-upgrade-u16-2019-1-db-node-73ab38b1-0-4 sshd[3082]: pam_unix(sshd:session): session opened for user scylla-test by (uid=0)
Jul  4 04:51:51 rolling-upgrade-u16-2019-1-db-node-73ab38b1-0-4 systemd-logind[1275]: New session 2 of user scylla-test.
Jul  4 04:51:51 rolling-upgrade-u16-2019-1-db-node-73ab38b1-0-4 systemd: pam_unix(systemd-user:session): session opened for user scylla-test by (uid=0)
Jul  4 04:57:30 rolling-upgrade-u16-2019-1-db-node-73ab38b1-0-4 sshd[3191]: Accepted publickey for scylla-test from 113.201.56.61 port 51267 ssh2: RSA SHA256:ORclW5uOPUGIzX/HqWCBo6YH8GIz8D8MPjTEd0njNms
Jul  4 04:57:30 rolling-upgrade-u16-2019-1-db-node-73ab38b1-0-4 sshd[3191]: pam_unix(sshd:session): session opened for user scylla-test by (uid=0)
Jul  4 04:57:30 rolling-upgrade-u16-2019-1-db-node-73ab38b1-0-4 systemd-logind[1275]: New session 3 of user scylla-test.
Jul  4 04:57:47 rolling-upgrade-u16-2019-1-db-node-73ab38b1-0-4 sshd[3119]: Received disconnect from 113.201.56.61 port 51170:11: disconnected by user
Jul  4 04:57:47 rolling-upgrade-u16-2019-1-db-node-73ab38b1-0-4 sshd[3119]: Disconnected from 113.201.56.61 port 51170
Jul  4 04:57:47 rolling-upgrade-u16-2019-1-db-node-73ab38b1-0-4 sshd[3082]: pam_unix(sshd:session): session closed for user scylla-test
Jul  4 04:57:47 rolling-upgrade-u16-2019-1-db-node-73ab38b1-0-4 systemd-logind[1275]: Removed session 2.

>>>>>> private ip works!!!
Jul  4 04:57:50 rolling-upgrade-u16-2019-1-db-node-73ab38b1-0-4 sshd[3248]: Accepted publickey for scylla-test from 10.142.0.9 port 47070 ssh2: RSA SHA256:ORclW5uOPUGIzX/HqWCBo6YH8GIz8D8MPjTEd0njNms
Jul  4 04:57:50 rolling-upgrade-u16-2019-1-db-node-73ab38b1-0-4 sshd[3248]: pam_unix(sshd:session): session opened for user scylla-test by (uid=0)
Jul  4 04:57:50 rolling-upgrade-u16-2019-1-db-node-73ab38b1-0-4 systemd-logind[1275]: New session 4 of user scylla-test.
Jul  4 04:57:50 rolling-upgrade-u16-2019-1-db-node-73ab38b1-0-4 sshd[3281]: Received disconnect from 10.142.0.9 port 47070:11: disconnected by user
Jul  4 04:57:50 rolling-upgrade-u16-2019-1-db-node-73ab38b1-0-4 sshd[3281]: Disconnected from 10.142.0.9 port 47070
Jul  4 04:57:50 rolling-upgrade-u16-2019-1-db-node-73ab38b1-0-4 sshd[3248]: pam_unix(sshd:session): session closed for user scylla-test
Jul  4 04:57:50 rolling-upgrade-u16-2019-1-db-node-73ab38b1-0-4 systemd-logind[1275]: Removed session 4.
```

**Comment by amoskong** [comment]
It seems some packages were installed before private ssh became available (at 09:57:50)  

```
scylla-test@rolling-upgrade-u16-2019-1-db-node-73ab38b1-0-4:/var/log$ cat apt/history.log 

Start-Date: 2019-06-28  09:56:52
Commandline: apt-get -y --no-install-recommends install gce-compute-image-packages google-cloud-sdk ntp python-google-compute-engine sshguard
Install: python-six:amd64 (1.10.0-3, automatic), python3-google-compute-engine:amd64 (20190522-0ubuntu1~16.04.0, automatic), python-boto:amd64 (2.38.0-1ubuntu1, automatic), libcurl3:amd64 (7.47.0-1ubuntu2.13, automatic), python-requests:amd64 (2.9.1-3ubuntu0.1, automatic), python2.7-minimal:amd64 (2.7.12-1ubuntu0~16.04.4, automatic), python2.7:amd64 (2.7.12-1ubuntu0~16.04.4, automatic), python-chardet:amd64 (2.3.0-2, automatic), python:amd64 (2.7.12-1~16.04, automatic), sshguard:amd64 (1.6.0-1), ntp:amd64 (1:4.2.8p4+dfsg-3ubuntu5.9), libpython-stdlib:amd64 (2.7.12-1~16.04, automatic), google-compute-engine-oslogin:amd64 (20190522-0ubuntu1~16.04.0, automatic), python-pkg-resources:amd64 (20.7.0-1, automatic), python-urllib3:amd64 (1.13.1-2ubuntu0.16.04.3, automatic), google-cloud-sdk:amd64 (212.0.0-0ubuntu1~16.04.0), python-google-compute-engine:amd64 (20190522-0ubuntu1~16.04.0), python-crcmod:amd64 (1.7-2build2, automatic), libpython2.7-minimal:amd64 (2.7.12-1ubuntu0~16.04.4, automatic), libopts25:amd64 (1:5.18.7-3, automatic), libpython2.7-stdlib:amd64 (2.7.12-1ubuntu0~16.04.4, automatic), libboost-regex1.58.0:amd64 (1.58.0+dfsg-5ubuntu3.1, automatic), python-minimal:amd64 (2.7.12-1~16.04, automatic), gce-compute-image-packages:amd64 (20190522-0ubuntu1~16.04.0)
End-Date: 2019-06-28  09:57:09

Start-Date: 2019-06-28  09:57:11
Commandline: apt-get -y purge grub-legacy-ec2
Purge: ubuntu-server:amd64 (1.361.3), grub-legacy-ec2:amd64 (19.1-1-gbaa47854-0ubuntu1~16.04.1)
End-Date: 2019-06-28  09:57:11

Start-Date: 2019-06-28  09:57:12
Commandline: apt-get -y purge irqbalance
Purge: irqbalance:amd64 (1.1.0-2ubuntu1)
End-Date: 2019-06-28  09:57:13

Start-Date: 2019-06-28  09:57:14
Commandline: apt-get remove --purge --assume-yes ^linux-.* linux-base+
Purge: linux-headers-generic:amd64 (4.4.0.154.162), linux-headers-4.4.0-154:amd64 (4.4.0-154.181), linux-modules-4.4.0-154-generic:amd64 (4.4.0-154.181), linux-headers-4.4.0-154-generic:amd64 (4.4.0-154.181), linux-virtual:amd64 (4.4.0.154.162), linux-headers-virtual:amd64 (4.4.0.154.162), linux-image-virtual:amd64 (4.4.0.154.162), linux-image-4.4.0-154-generic:amd64 (4.4.0-154.181)
End-Date: 2019-06-28  09:57:16

Start-Date: 2019-06-28  09:57:21
Commandline: apt-get install --assume-yes linux-gcp
Install: linux-modules-4.15.0-1036-gcp:amd64 (4.15.0-1036.38~16.04.1, automatic), linux-gcp-headers-4.15.0-1036:amd64 (4.15.0-1036.38~16.04.1, automatic), linux-headers-gcp:amd64 (4.15.0.1036.50, automatic), linux-gcp:amd64 (4.15.0.1036.50), linux-headers-4.15.0-1036-gcp:amd64 (4.15.0-1036.38~16.04.1, automatic), linux-image-4.15.0-1036-gcp:amd64 (4.15.0-1036.38~16.04.1, automatic), linux-image-gcp:amd64 (4.15.0.1036.50, automatic)
End-Date: 2019-06-28  09:57:32
```

**Comment by amoskong** [comment]
In http://jenkins.scylladb.com/job/scylla-staging/job/rolling-upgrade-ubuntu-16.04-test-clone/2/
 two subtests (2.3, 2018.1) have this problem, and 4th node failed for setup timeout.

I checked old failed jobs,  It seems the problem only occurred on last created db node (4th node).

**Comment by amoskong** [comment]
Finally found the root PROBLEM!!

scylla-test user is added in init stage, sct tried to connect the node before user is created.
sshguard blocked the builder IP for 630 seconds, that's why the ssh with private ip is available finally.

```
Jul  4 04:46:07 rolling-upgrade-u16-2019-1-db-node-73ab38b1-0-4 sshd[2275]: Invalid user scylla-test from 10.142.0.9
Jul  4 04:46:07 rolling-upgrade-u16-2019-1-db-node-73ab38b1-0-4 sshd[2275]: input_userauth_request: invalid user scylla-test [preauth]
Jul  4 04:46:07 rolling-upgrade-u16-2019-1-db-node-73ab38b1-0-4 sshd[2270]: Invalid user scylla-test from 10.142.0.9
Jul  4 04:46:07 rolling-upgrade-u16-2019-1-db-node-73ab38b1-0-4 sshd[2270]: input_userauth_request: invalid user scylla-test [preauth]
Jul  4 04:46:07 rolling-upgrade-u16-2019-1-db-node-73ab38b1-0-4 sshd[2284]: Invalid user scylla-test from 10.142.0.9
Jul  4 04:46:07 rolling-upgrade-u16-2019-1-db-node-73ab38b1-0-4 sshd[2284]: input_userauth_request: invalid user scylla-test [preauth]
Jul  4 04:46:07 rolling-upgrade-u16-2019-1-db-node-73ab38b1-0-4 gpasswd[2301]: user nyh added by root to group google-sudoers
Jul  4 04:46:07 rolling-upgrade-u16-2019-1-db-node-73ab38b1-0-4 sshd[2270]: Connection closed by 10.142.0.9 port 46506 [preauth]
Jul  4 04:46:07 rolling-upgrade-u16-2019-1-db-node-73ab38b1-0-4 sshd[2284]: Connection closed by 10.142.0.9 port 46510 [preauth]
Jul  4 04:46:07 rolling-upgrade-u16-2019-1-db-node-73ab38b1-0-4 sshd[2275]: Connection closed by 10.142.0.9 port 46508 [preauth]
Jul  4 04:46:07 rolling-upgrade-u16-2019-1-db-node-73ab38b1-0-4 useradd[2305]: new group: name=abykov, GID=1020
Jul  4 04:46:07 rolling-upgrade-u16-2019-1-db-node-73ab38b1-0-4 useradd[2305]: new user: name=abykov, UID=1019, GID=1020, home=/home/abykov, shell=/bin/bash
Jul  4 04:46:07 rolling-upgrade-u16-2019-1-db-node-73ab38b1-0-4 sshguard[1547]: Blocking 10.142.0.9:4 for >630secs: 40 danger in 4 attacks over 0 seconds (all: 40d in 1 abuses over 0s).
```

**Comment by amoskong** [comment]
After checked the ssh command timestamp, I found there are two threads tried to connect ssh repeated, the connect time was very very near (0.03 or 0.04 second).

 
```
2019-07-04 04:45:46,959 cluster          L0327 DEBUG| Node rolling-upgrade-u16-2019-1-db-node-5d9ef2dd-0-4 [35.185.31.128 | 10.142.0.188] (seed: False): SSH access -> 'ssh -i ~/.ssh/scylla-test scylla-test@10.142.0.188'

 >>>>>> Thread1
2019-07-04 04:45:47,050 remote           L0716 ERROR| Remote [scylla-test@10.142.0.188]: Error while executing SSH command: Command: /bin/ssh -tt -a -x  -o ControlPath=/var/tmp/ssh-masterfFlUtF/socket -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpVGLnJT -o BatchMode=yes -o ConnectTimeout=30 -o ServerAliveInterval=300 -l scylla-test -p 22 -i /jenkins/.ssh/scylla-test 10.142.0.188 "true"

 >>>>>> Thread2
2019-07-04 04:45:47,054 remote           L0716 ERROR| Remote [scylla-test@10.142.0.188]: Error while executing SSH command: Command: /bin/ssh -tt -a -x  -o ControlPath=/var/tmp/ssh-masterfFlUtF/socket -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpVGLnJT -o BatchMode=yes -o ConnectTimeout=30 -o ServerAliveInterval=300 -l scylla-test -p 22 -i /jenkins/.ssh/scylla-test 10.142.0.188 "true"
2019-07-04 04:46:27,082 remote           L0716 ERROR| Remote [scylla-test@10.142.0.188]: Error while executing SSH command: Command: /bin/ssh -tt -a -x  -o ControlPath=/var/tmp/ssh-mastersC09Rp/socket -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpVGLnJT -o BatchMode=yes -o ConnectTimeout=30 -o ServerAliveInterval=300 -l scylla-test -p 22 -i /jenkins/.ssh/scylla-test 10.142.0.188 "true"
2019-07-04 04:46:27,087 remote           L0716 ERROR| Remote [scylla-test@10.142.0.188]: Error while executing SSH command: Command: /bin/ssh -tt -a -x  -o ControlPath=/var/tmp/ssh-mastersC09Rp/socket -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpVGLnJT -o BatchMode=yes -o ConnectTimeout=30 -o ServerAliveInterval=300 -l scylla-test -p 22 -i /jenkins/.ssh/scylla-test 10.142.0.188 "true"
2019-07-04 04:47:07,110 remote           L0716 ERROR| Remote [scylla-test@10.142.0.188]: Error while executing SSH command: Command: /bin/ssh -tt -a -x  -o ControlPath=/var/tmp/ssh-mastersC09Rp/socket -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpVGLnJT -o BatchMode=yes -o ConnectTimeout=30 -o ServerAliveInterval=300 -l scylla-test -p 22 -i /jenkins/.ssh/scylla-test 10.142.0.188 "true"
2019-07-04 04:47:07,114 remote           L0716 ERROR| Remote [scylla-test@10.142.0.188]: Error while executing SSH command: Command: /bin/ssh -tt -a -x  -o ControlPath=/var/tmp/ssh-mastersC09Rp/socket -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpVGLnJT -o BatchMode=yes -o ConnectTimeout=30 -o ServerAliveInterval=300 -l scylla-test -p 22 -i /jenkins/.ssh/scylla-test 10.142.0.188 "true"
2019-07-04 04:47:47,137 remote           L0716 ERROR| Remote [scylla-test@10.142.0.188]: Error while executing SSH command: Command: /bin/ssh -tt -a -x  -o ControlPath=/var/tmp/ssh-mastersC09Rp/socket -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpVGLnJT -o BatchMode=yes -o ConnectTimeout=30 -o ServerAliveInterval=300 -l scylla-test -p 22 -i /jenkins/.ssh/scylla-test 10.142.0.188 "true"
2019-07-04 04:47:47,142 remote           L0716 ERROR| Remote [scylla-test@10.142.0.188]: Error while executing SSH command: Command: /bin/ssh -tt -a -x  -o ControlPath=/var/tmp/ssh-mastersC09Rp/socket -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpVGLnJT -o BatchMode=yes -o ConnectTimeout=30 -o ServerAliveInterval=300 -l scylla-test -p 22 -i /jenkins/.ssh/scylla-test 10.142.0.188 "true"
```

**Comment by amoskong** [comment]
The problem still exists after backported pr #1107 to branch-2019.1.
http://jenkins.scylladb.com/job/scylla-staging/job/amos/job/rolling-upgrade-ubuntu-16.04-test-clone/3

Expected: 
```
the PR #1107 changed the sleep 30s after get_backtraces() to before
Then journal thread will be started first, and get_backtrace thread will sleep 15 seconds,
then try to connect by ssh.
```

Actual: 
```
The problem still occurred, it seems the first connect when use isn't added will trigger the block (630s).
```

So we need to avoid ssh connection at that stage.

**Comment by amoskong** [comment]
We init the BaseNode when public ip address is available, that means the system `_almost_` get ready.

It's not a best solution by adding sleep/wait insider task threads, we can wait a while before starting all task threads.  

Teset jobs:
- http://jenkins.scylladb.com/job/scylla-staging/job/amos/job/rolling-upgrade-ubuntu-16.04-test-clone/5/
- http://jenkins.scylladb.com/job/scylla-staging/job/amos/job/rolling-upgrade-ubuntu-16.04-test-clone/6/
