### ISSUE TITLE
UnexpectedExit: Encountered a bad command exit code! - bash: -c: line 0: syntax error near unexpected token `seed:'

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylla-cluster-tests#1156]
### Prerequisites

* [ ] Are you rebased to master ?
* [ ] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: [branch or hash tag you are working on] 3.1
* **scylla**: [branch or commit hash] Tomek rpm - scylla-server-3.1.0.rc2-0.20190618.fa53994fb0.el7.x86_64.rpm

### Logs
* test_id: 33eaa49a-1750-44ec-820b-ccf58eb6f0f6
* [job log:](https://cloudius-jenkins-test.s3.amazonaws.com/33eaa49a-1750-44ec-820b-ccf58eb6f0f6/job-2019-07-14T20.35-2b9e14c.zip)
[jenkins job](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/fabio/job/3h_reproducer_malformed_sstables_tomek_version/3/)

### Description

[Description of the bug or feature]

```
2019-07-14 23:27:35,978 nemesis          L0540 ERROR| sdcm.nemesis.ChaosMonkey: Exception in random_disrupt_method show_toppartitions: Encountered a bad command exit code!

Command: 'cqlsh --request-timeout=300 --no-color --execute "SELECT keyspace_name, table_name from system_schema.tables" Node longevity-10gb-3h-jenkins-db-node-33eaa49a-1 [52.23.232.3 | 172.30.0.244] (seed: True)'

Exit code: 1

Stdout:



Stderr:

bash: -c: line 0: syntax error near unexpected token `seed:'
bash: -c: line 0: `cqlsh --request-timeout=300 --no-color --execute "SELECT keyspace_name, table_name from system_schema.tables" Node longevity-10gb-3h-jenkins-db-node-33eaa49a-1 [52.23.232.3 | 172.30.0.244] (seed: True)'


2019-07-14 23:27:35,978 nemesis          L1041 ERROR| sdcm.nemesis.ChaosMonkey: Unhandled exception in method <function disrupt at 0x7fa0bf016140>
Traceback (most recent call last):
  File "/sct/sdcm/nemesis.py", line 1037, in wrapper
    result = method(*args, **kwargs)
  File "/sct/sdcm/nemesis.py", line 1249, in disrupt
    self.call_random_disrupt_method()
  File "/sct/sdcm/nemesis.py", line 538, in call_random_disrupt_method
    disrupt_method()
  File "/sct/sdcm/nemesis.py", line 969, in disrupt_show_toppartitions
    args = generate_random_parameters_values()
  File "/sct/sdcm/nemesis.py", line 954, in generate_random_parameters_values
    ks_cf_list = self.loaders.get_non_system_ks_cf_list(self.loaders.nodes[0], self.cluster.nodes[0])
  File "/sct/sdcm/cluster.py", line 3031, in get_non_system_ks_cf_list
    .format(request_timeout, cmd, db_node_ip), verbose=False)
  File "/sct/sdcm/remote.py", line 230, in run
    watchers=watchers, command_timeout=timeout)
  File "<decorator-gen-3>", line 2, in run
  File "/usr/lib/python2.7/site-packages/fabric/connection.py", line 30, in opens
    return method(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/fabric/connection.py", line 721, in run
    return self._run(self._remote_runner(), command, **kwargs)
  File "/usr/lib/python2.7/site-packages/invoke/context.py", line 101, in _run
    return runner.run(command, **kwargs)
  File "/usr/lib/python2.7/site-packages/invoke/runners.py", line 283, in run
    return self._run_body(command, **kwargs)
  File "/usr/lib/python2.7/site-packages/invoke/runners.py", line 431, in _run_body
    raise UnexpectedExit(result)
UnexpectedExit: Encountered a bad command exit code!

Command: 'cqlsh --request-timeout=300 --no-color --execute "SELECT keyspace_name, table_name from system_schema.tables" Node longevity-10gb-3h-jenkins-db-node-33eaa49a-1 [52.23.232.3 | 172.30.0.244] (seed: True)'

Exit code: 1

Stdout:



Stderr:

bash: -c: line 0: syntax error near unexpected token `seed:'
bash: -c: line 0: `cqlsh --request-timeout=300 --no-color --execute "SELECT keyspace_name, table_name from system_schema.tables" Node longevity-10gb-3h-jenkins-db-node-33eaa49a-1 [52.23.232.3 | 172.30.0.244] (seed: True)'
```

**Comment by bentsi** [comment]
already fixed in master and in 3.1 staging
