### ISSUE TITLE
Filter out critical message during AbortRepair nemesis

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-cluster-tests#1163]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: [branch or hash tag you are working on] juliayakovlev/null_schema_version
* **scylla**: [branch or commit hash] 3.1

### Logs
* test_id: [look for 'the Test ID' at the end of the log] 7466283f-f6a2-4b61-b49a-00a192e66207
* job log: https://jenkins.scylladb.com/job/scylla-staging/job/staging-longevity-50gb-4days/9/console

### Description

During Abort Repair nemesis the repair process is aborted and send error like:
```Got error in row level repair: std::runtime_error (repair id 1 is aborted on shard 1)```

We create critical event about this. But it's expected failure, so we should filter out it and don't show on the dashboard

```
< t:2019-07-16 06:40:49,610 f:nemesis.py      l:808  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Found '1' active repairs
< t:2019-07-16 06:40:50,028 f:nemesis.py      l:818  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Abort repair streaming by storage_service/force_terminate_repair API
< t:2019-07-16 06:40:50,278 f:remote.py       l:217  c:sdcm.remote          p:DEBUG > RemoteCmdRunner [centos@172.30.0.197]: Running command "curl -X POST --header "Content-Type: application/json" --header "Accept: application/json" "http://127.0.0.1:10000/storage_service/force_terminate_repair""...
< t:2019-07-16 06:40:51,355 f:remote.py       l:661  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@172.30.0.197]:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
< t:2019-07-16 06:40:51,736 f:remote.py       l:661  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@172.30.0.197]:                                  Dload  Upload   Total   Spent    Left  Speed
< t:2019-07-16 06:40:51,900 f:remote.py       l:661  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@172.30.0.197]: ^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
< t:2019-07-16 06:40:52,127 f:remote.py       l:115  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@172.30.0.197]: STDERR:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
< t:2019-07-16 06:40:52,127 f:remote.py       l:115  c:sdcm.remote          p:INFO  >                                  Dload  Upload   Total   Spent    Left  Speed
< t:2019-07-16 06:40:52,127 f:remote.py       l:115  c:sdcm.remote          p:INFO  > 
< t:2019-07-16 06:40:52,127 f:remote.py       l:115  c:sdcm.remote          p:INFO  >   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
< t:2019-07-16 06:40:52,127 f:remote.py       l:115  c:sdcm.remote          p:INFO  >   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
< t:2019-07-16 06:40:52,272 f:remote.py       l:661  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@172.30.0.197]: [2019-07-16 06:40:51,964] Repair session 1 failed
< t:2019-07-16 06:40:52,317 f:remote.py       l:117  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@172.30.0.197]: Command "curl -X POST --header "Content-Type: application/json" --header "Accept: application/json" "http://127.0.0.1:10000/storage_service/force_terminate_repair"" finished with status 0
< t:2019-07-16 06:40:52,442 f:remote.py       l:661  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@172.30.0.197]: [2019-07-16 06:40:51,967] Repair session 1 finished
< t:2019-07-16 06:40:52,515 f:remote.py       l:661  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@172.30.0.197]: error: Repair job has failed with the error message: [2019-07-16 06:40:51,964] Repair session 1 failed
< t:2019-07-16 06:40:52,739 f:remote.py       l:661  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@172.30.0.197]: -- StackTrace --
< t:2019-07-16 06:40:52,893 f:remote.py       l:661  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@172.30.0.197]: java.lang.RuntimeException: Repair job has failed with the error message: [2019-07-16 06:40:51,964] Repair session 1 failed
< t:2019-07-16 06:40:53,221 f:remote.py       l:661  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@172.30.0.197]:    at org.apache.cassandra.tools.RepairRunner.progress(RepairRunner.java:124)
< t:2019-07-16 06:40:53,289 f:remote.py       l:661  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@172.30.0.197]:    at org.apache.cassandra.utils.progress.jmx.JMXNotificationProgressListener.handleNotification(JMXNotificationProgressListener.java:77)
< t:2019-07-16 06:40:53,443 f:remote.py       l:661  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@172.30.0.197]:    at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.dispatchNotification(ClientNotifForwarder.java:583)
< t:2019-07-16 06:40:53,660 f:remote.py       l:661  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@172.30.0.197]:    at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.doRun(ClientNotifForwarder.java:533)
< t:2019-07-16 06:40:53,771 f:remote.py       l:661  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@172.30.0.197]:    at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.run(ClientNotifForwarder.java:452)
< t:2019-07-16 06:40:53,874 f:remote.py       l:661  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@172.30.0.197]:    at com.sun.jmx.remote.internal.ClientNotifForwarder$LinearExecutor$1.run(ClientNotifForwarder.java:108)
< t:2019-07-16 06:40:53,949 f:remote.py       l:661  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@172.30.0.197]: 
< t:2019-07-16 06:40:54,059 f:remote.py       l:115  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@172.30.0.197]: STDERR: error: Repair job has failed with the error message: [2019-07-16 06:40:51,964] Repair session 1 failed
< t:2019-07-16 06:40:54,059 f:remote.py       l:115  c:sdcm.remote          p:INFO  > -- StackTrace --
< t:2019-07-16 06:40:54,059 f:remote.py       l:115  c:sdcm.remote          p:INFO  > java.lang.RuntimeException: Repair job has failed with the error message: [2019-07-16 06:40:51,964] Repair session 1 failed
< t:2019-07-16 06:40:54,059 f:remote.py       l:115  c:sdcm.remote          p:INFO  >   at org.apache.cassandra.tools.RepairRunner.progress(RepairRunner.java:124)
< t:2019-07-16 06:40:54,059 f:remote.py       l:115  c:sdcm.remote          p:INFO  >   at org.apache.cassandra.utils.progress.jmx.JMXNotificationProgressListener.handleNotification(JMXNotificationProgressListener.java:77)
< t:2019-07-16 06:40:54,059 f:remote.py       l:115  c:sdcm.remote          p:INFO  >   at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.dispatchNotification(ClientNotifForwarder.java:583)
< t:2019-07-16 06:40:54,059 f:remote.py       l:115  c:sdcm.remote          p:INFO  >   at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.doRun(ClientNotifForwarder.java:533)
< t:2019-07-16 06:40:54,059 f:remote.py       l:115  c:sdcm.remote          p:INFO  >   at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.run(ClientNotifForwarder.java:452)
< t:2019-07-16 06:40:54,059 f:remote.py       l:115  c:sdcm.remote          p:INFO  >   at com.sun.jmx.remote.internal.ClientNotifForwarder$LinearExecutor$1.run(ClientNotifForwarder.java:108)
< t:2019-07-16 06:40:54,059 f:remote.py       l:115  c:sdcm.remote          p:INFO  > 
< t:2019-07-16 06:40:54,112 f:remote.py       l:117  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@172.30.0.197]: Command "nodetool -u cassandra -pw cassandra  repair " finished with status 2
< t:2019-07-16 06:40:54,653 f:nemesis.py      l:825  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Execute a complete repair for target node
< t:2019-07-16 06:40:54,780 f:remote.py       l:217  c:sdcm.remote          p:DEBUG > RemoteCmdRunner [centos@172.30.0.197]: Running command "nodetool -u cassandra -pw cassandra  repair "...
< t:2019-07-16 06:41:06,017 f:remote.py       l:661  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@172.30.0.197]: [2019-07-16 06:41:05,679] Starting repair command #2, repairing 1 ranges for keyspace keyspace_deflate (parallelism=SEQUENTIAL, full=true)
< t:2019-07-16 06:41:31,789 f:cluster_aws.py  l:479  c:sdcm.cluster         p:WARNING > Node longevity-tls-50gb-4d-null-sch-loader-node-7466283f-2 [52.55.244.205 | 172.30.0.172] (seed: False): Error during getting aws termination notification ChannelException(1, 'Administratively prohibited')
< t:2019-07-16 06:41:59,898 f:cluster_aws.py  l:479  c:sdcm.cluster         p:WARNING > Node longevity-tls-50gb-4d-null-sch-loader-node-7466283f-2 [52.55.244.205 | 172.30.0.172] (seed: False): Error during getting aws termination notification ChannelException(1, 'Administratively prohibited')
< t:2019-07-16 06:42:03,461 f:sct_events.py   l:423  c:sdcm.sct_events      p:INFO  > 2019-07-16 06:42:03.098: (DatabaseLogEvent Severity.CRITICAL): type=RUNTIME_ERROR regex=std::runtime_error line_number=29556 node=Node longevity-tls-50gb-4d-null-sch-db-node-7466283f-4 [52.87.171.62 | 172.30.0.197] (seed: False)
< t:2019-07-16 06:42:03,527 f:connectionpool.py l:205  c:urllib3.connectionpool p:DEBUG > Starting new HTTP connection (1): 172.30.0.182:3000
< t:2019-07-16 06:42:03,706 f:connectionpool.py l:393  c:urllib3.connectionpool p:DEBUG > http://172.30.0.182:3000 "POST /api/annotations HTTP/1.1" 200 39
< t:2019-07-16 06:42:03,904 f:sct_events.py   l:480  c:sdcm.sct_events      p:INFO  > {"id":538,"message":"Annotation added"}
< t:2019-07-16 06:42:18,750 f:sct_events.py   l:423  c:sdcm.sct_events      p:INFO  > 2019-07-16 06:42:18.625: (DatabaseLogEvent Severity.CRITICAL): type=RUNTIME_ERROR regex=std::runtime_error line_number=29629 node=Node longevity-tls-50gb-4d-null-sch-db-node-7466283f-4 [52.87.171.62 | 172.30.0.197] (seed: False)
< t:2019-07-16 06:42:18,750 f:sct_events.py   l:423  c:sdcm.sct_events      p:INFO  > air - Got error in row level repair: std::runtime_error (repair id 1 is aborted on shard 1)
< t:2019-07-16 06:42:19,038 f:connectionpool.py l:205  c:urllib3.connectionpool p:DEBUG > Starting new HTTP connection (1): 172.30.0.182:3000
< t:2019-07-16 06:42:19,331 f:connectionpool.py l:393  c:urllib3.connectionpool p:DEBUG > http://172.30.0.182:3000 "POST /api/annotations HTTP/1.1" 200 39
< t:2019-07-16 06:42:19,573 f:sct_events.py   l:480  c:sdcm.sct_events      p:INFO  > {"id":539,"message":"Annotation added"}
< t:2019-07-16 06:42:33,962 f:sct_events.py   l:423  c:sdcm.sct_events      p:INFO  > 2019-07-16 06:42:33.885: (DatabaseLogEvent Severity.CRITICAL): type=RUNTIME_ERROR regex=std::runtime_error line_number=29727 node=Node longevity-tls-50gb-4d-null-sch-db-node-7466283f-4 [52.87.171.62 | 172.30.0.197] (seed: False)
```

**Expected behavior:** Don't show this event on the Graphana Dashboard

**Actual behavior:** The error is present on the Graphana Dashboard

**Comment by juliayakovlev** [comment]
@bentsi  ok, no prob

**Comment by amoskong** [comment]
longevity 3h of 3.1 failed for this issue, we need to fix it.

**Comment by bentsi** [comment]
we have a filter for this, look in the nemesis code:
```
DbEventsFilter(type='RUNTIME_ERROR', line='is aborted', node=self.target_node)
```
@fruch can you check that it is working correctly?

**Comment by fruch** [comment]
@amoskong do you have link for the places you've seen this failing ?

**Comment by amoskong** [comment]
> @amoskong do you have link for the places you've seen this failing ?

http://jenkins.scylladb.com/view/scylla-3.1/job/scylla-3.1/view/scylla-3.1-test/job/longevity/job/longevity-100gb-4h/56/console

**Comment by amoskong** [comment]
I can still see this issue in longevity-4h of 3.1
