### ISSUE TITLE
Reuse cluster doesn't work due to misuse of the objects returned from list_instances_aws

### ISSUE THREAD

**Issue by eliransin** [scylladb/scylla-cluster-tests#1190]
Reuse cluster ends with an exception, this is due to misuse of the list returned from 
list_instances_aws.
```
p:INFO  > 2019-07-23 09:02:45.662: (InfoEvent Severity.NORMAL): message=TEST_START test_id=isolation_test
< t:2019-07-23 09:02:45,926 f:cluster.py      l:2049 c:sdcm.cluster         p:INFO  > Cluster eliransin-isolation--eliransin-db-cluster-isolatio (AMI: ['ami-0ad3df4139aaf5956'] Type: i3.large): Init nodes
< t:2019-07-23 09:02:45,960 f:common.py       l:580  c:utils                p:INFO  > Going to list aws region "us-east-1"
< t:2019-07-23 09:02:47,439 f:common.py       l:589  c:utils                p:INFO  > us-east-1: done [1/1]
< t:2019-07-23 09:02:47,491 f:common.py       l:600  c:utils                p:INFO  > Found total of 3 instances.
< t:2019-07-23 09:02:47,491 f:tester.py       l:127  c:sdcm.tester          p:ERROR > Exception in setUp. Will call tearDown < t:2019-07-23 09:02:47,491 f:tester.py       l:127  c:sdcm.tester          p:ERROR > Exception in setUp. Will call tearDown
< t:2019-07-23 09:02:47,491 f:tester.py       l:127  c:sdcm.tester          p:ERROR > Traceback (most recent call last):
< t:2019-07-23 09:02:47,491 f:tester.py       l:127  c:sdcm.tester          p:ERROR >   File "/sct/sdcm/tester.py", line 125, in wrapper
< t:2019-07-23 09:02:47,491 f:tester.py       l:127  c:sdcm.tester          p:ERROR >     return method(*args, **kwargs)
< t:2019-07-23 09:02:47,491 f:tester.py       l:127  c:sdcm.tester          p:ERROR >   File "/sct/sdcm/utils/common.py", line 243, in inner
< t:2019-07-23 09:02:47,491 f:tester.py       l:127  c:sdcm.tester          p:ERROR >     res = func(*args, **kwargs)
< t:2019-07-23 09:02:47,491 f:tester.py       l:127  c:sdcm.tester          p:ERROR >   File "/sct/sdcm/tester.py", line 218, in setUp
< t:2019-07-23 09:02:47,491 f:tester.py       l:127  c:sdcm.tester          p:ERROR >     self.init_resources()
< t:2019-07-23 09:02:47,491 f:tester.py       l:127  c:sdcm.tester          p:ERROR >   File "/sct/sdcm/tester.py", line 740, in init_resources
< t:2019-07-23 09:02:47,491 f:tester.py       l:127  c:sdcm.tester          p:ERROR >     monitor_info=monitor_info)
< t:2019-07-23 09:02:47,491 f:tester.py       l:127  c:sdcm.tester          p:ERROR >   File "/sct/sdcm/tester.py", line 567, in get_cluster_aws
< t:2019-07-23 09:02:47,491 f:tester.py       l:127  c:sdcm.tester          p:ERROR >     self.db_cluster = create_cluster(db_type)
< t:2019-07-23 09:02:47,491 f:tester.py       l:127  c:sdcm.tester          p:ERROR >   File "/sct/sdcm/tester.py", line 534, in create_cluster
< t:2019-07-23 09:02:47,491 f:tester.py       l:127  c:sdcm.tester          p:ERROR >     **cl_params)
< t:2019-07-23 09:02:47,491 f:tester.py       l:127  c:sdcm.tester          p:ERROR >   File "/sct/sdcm/cluster_aws.py", line 582, in __init__
< t:2019-07-23 09:02:47,491 f:tester.py       l:127  c:sdcm.tester          p:ERROR >     node_type=node_type)
< t:2019-07-23 09:02:47,491 f:tester.py       l:127  c:sdcm.tester          p:ERROR >   File "/sct/sdcm/cluster.py", line 2263, in __init__
< t:2019-07-23 09:02:47,491 f:tester.py       l:127  c:sdcm.tester          p:ERROR >     super(BaseScyllaCluster, self).__init__(*args, **kwargs)
< t:2019-07-23 09:02:47,491 f:tester.py       l:127  c:sdcm.tester          p:ERROR >   File "/sct/sdcm/cluster_aws.py", line 83, in __init__
< t:2019-07-23 09:02:47,491 f:tester.py       l:127  c:sdcm.tester          p:ERROR >     region_names=self.region_names)
< t:2019-07-23 09:02:47,491 f:tester.py       l:127  c:sdcm.tester          p:ERROR >   File "/sct/sdcm/cluster.py", line 2061, in __init__
< t:2019-07-23 09:02:47,491 f:tester.py       l:127  c:sdcm.tester          p:ERROR >     self.add_nodes(num, dc_idx=dc_idx)
< t:2019-07-23 09:02:47,491 f:tester.py       l:127  c:sdcm.tester          p:ERROR >   File "/sct/sdcm/cluster_aws.py", line 605, in add_nodes
< t:2019-07-23 09:02:47,491 f:tester.py       l:127  c:sdcm.tester          p:ERROR >     enable_auto_bootstrap=enable_auto_bootstrap)
< t:2019-07-23 09:02:47,491 f:tester.py       l:127  c:sdcm.tester          p:ERROR >   File "/sct/sdcm/cluster_aws.py", line 279, in add_nodes
< t:2019-07-23 09:02:47,491 f:tester.py       l:127  c:sdcm.tester          p:ERROR >     instances = self._get_instances(dc_idx)
< t:2019-07-23 09:02:47,491 f:tester.py       l:127  c:sdcm.tester          p:ERROR >   File "/sct/sdcm/cluster_aws.py", line 241, in _get_instances
< t:2019-07-23 09:02:47,491 f:tester.py       l:127  c:sdcm.tester          p:ERROR >     instances = results[self.region_names[dc_idx]]
< t:2019-07-23 09:02:47,491 f:tester.py       l:127  c:sdcm.tester          p:ERROR > TypeError: list indices must be integers, not str
```

**Comment by eliransin** [comment]
seams to already have been fixed in d7cc3f1f5b65d95e8c5675f86fc8abf9188dbbeb

**Comment by fruch** [comment]
sorry about this one, we aren't testing the reuse feature enough... 

anyhow thanks for the feedback, keep it coming.

**Comment by eliransin** [comment]
:+1:
