### ISSUE TITLE
GCE setup issues

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla-cluster-tests#1244]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: branch-3.0 / branch-3.1

### Logs
* jobs: http://jenkins.scylladb.com/job/scylla-3.0/job/3.0-test/job/scylla-rolling-upgrade-ubuntu-16.04-test/331/base_version=2.3,label=gce3-qavpc,test_sst3=true,version_desc=3-0/

### Description

There are some problem in node setup of gce backend, which made the upgrade test is very unstable.

### Steps to Reproduce

1. execute upgrade test, that will use gce backend, the errors occur during the cluster init stage.

**Actual behavior:** [What actually happened]

* Failed to report uuid:

```
Error 1:
curl: (6) Could not resolve host: i6a5h9l1kl.execute-api.us-east-1.amazonaws.com; Unknown error


Error 2:
Traceback (most recent call last):
  File "/sct/sdcm/cluster.py", line 1396, in node_setup
    cl_inst.node_setup(node, **setup_kwargs)
  File "/sct/sdcm/cluster.py", line 1865, in node_setup
    node.wait_db_up(timeout=timeout)
  File "/sct/sdcm/cluster.py", line 816, in wait_db_up
    self._report_housekeeping_uuid()
  File "/sct/sdcm/cluster.py", line 807, in _report_housekeeping_uuid
    self.remoter.run(cmd % result.stdout.strip())
  File "/sct/sdcm/remote.py", line 906, in run
    watch_stdout_pattern=watch_stdout_pattern)
  File "/sct/sdcm/remote.py", line 847, in _run
    watch_stdout_pattern=watch_stdout_pattern)
  File "/sct/sdcm/remote.py", line 805, in ssh_run
    raise process.CmdError(cmd, sp.result)
CmdError: Command '/bin/ssh -tt -a -x  -o ControlPath=/var/tmp/ssh-masterGaShRS/socket -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpaCzxfT -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInt
erval=300 -l scylla-test -p 22 -i /root/.ssh/scylla-test 10.142.0.25 "curl \"https://i6a5h9l1kl.execute-api.us-east-1.amazonaws.com/prod/check_version?uu=b8117270-c791-11e9-a825-42010a8e0019&mark=scylla\""' faile
d (rc=6)
2019-08-25 23:44:59,094 connectionpool   L0396 DEBUG| https://www.googleapis.com:443 "GET /compute/v1/projects/skilled-adapter-452/zones/us-east1-b/instances/rolling-upgrade-u16-3-0-db-node-dbfedbca-0-3 HTTP/1.1"
 200 None
2019-08-25 23:44:59,319 connectionpool   L0396 DEBUG| https://www.googleapis.com:443 "GET /compute/v1/projects/skilled-adapter-452/aggregated/disks?maxResults=500 HTTP/1.1" 200 None
2019-08-25 23:44:59,333 remote           L0194 DEBUG| [10.142.0.21] [stderr] Shared connection to 10.142.0.21 closed.
2019-08-25 23:44:59,333 remote           L0178 DEBUG| [10.142.0.21] [stdout] {"version":"3.0.8"}
```

**Comment by amoskong** [comment]
https://ec.haxx.se/usingcurl-returns.html

``
Exit Code 6:

Couldn't resolve host. The given remote host's address was not resolved. The address of the given server could not be resolved. Either the given host name is just wrong, or the DNS server is misbehaving and does not know about this name when it should or perhaps even the system you run curl on is misconfigured so that it does not find/use the correct DNS server.
``

**Comment by amoskong** [comment]
Update:
1. we have an additional fix for GCE setup issues (yum err)
    - PR: Retry to update repo cache after system is up #1251
2. I just touched a yum error in manual testing, google-cloud-sdk was intalled in `yum update`. the next `yum makecache` required to import GPG key, and it failed for `https://packages.cloud.google.com/yum/repos/cloud-sdk-el7-x86_64/repodata/repomd.xml: [Errno -1] repomd.xml signature could not be verified for google-cloud-sdk`.  It might be a real problem of default google-cloud-sdk/signature repo. Or we should import keys before `yum makecache`. However the retry really solved the problem.

```
[scylla-test@amos-centos7-upgrade-test ~]$ sudo yum update
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: repo1.ash.innoscale.net
 * epel: mirror.us.leaseweb.net
 * extras: repo1.ash.innoscale.net
 * updates: repo1.ash.innoscale.net
Resolving Dependencies
--> Running transaction check
---> Package google-cloud-sdk.noarch 0:258.0.0-1.el7 will be updated
---> Package google-cloud-sdk.noarch 0:260.0.0-1.el7 will be an update
--> Finished Dependency Resolution

Dependencies Resolved

====================================================================================================================================================================================================================
 Package                                               Arch                                        Version                                              Repository                                             Size
====================================================================================================================================================================================================================
Updating:
 google-cloud-sdk                                      noarch                                      260.0.0-1.el7                                        google-cloud-sdk                                       34 M

Transaction Summary
====================================================================================================================================================================================================================
Upgrade  1 Package

Total download size: 34 M
Is this ok [y/d/N]: ^Cy
Downloading packages:
Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
[scylla-test@amos-centos7-upgrade-test ~]$ sudo yum makecache
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
epel/x86_64/metalink                                                                                                                                                                         |  17 kB  00:00:00     
 * base: repo1.ash.innoscale.net
 * epel: mirror.us.leaseweb.net
 * extras: repo1.ash.innoscale.net
 * updates: repo1.ash.innoscale.net
base                                                                                                                                                                                         | 3.6 kB  00:00:00     
extras                                                                                                                                                                                       | 3.4 kB  00:00:00     
google-cloud-sdk/signature                                                                                                                                                                   |  454 B  00:00:00     
Retrieving key from https://packages.cloud.google.com/yum/doc/yum-key.gpg
Importing GPG key 0xA7317B0F:
 Userid     : "Google Cloud Packages Automatic Signing Key <gc-team@google.com>"
 Fingerprint: d0bc 747f d8ca f711 7500 d6fa 3746 c208 a731 7b0f
 From       : https://packages.cloud.google.com/yum/doc/yum-key.gpg
Is this ok [y/N]: y
Retrieving key from https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
google-cloud-sdk/signature                                                                                                                                                                   | 1.4 kB  00:00:05 !!! 
https://packages.cloud.google.com/yum/repos/cloud-sdk-el7-x86_64/repodata/repomd.xml: [Errno -1] repomd.xml signature could not be verified for google-cloud-sdk
Trying other mirror.
google-compute-engine/signature                                                                                                                                                              |  454 B  00:00:00     
google-compute-engine/signature                                                                                                                                                              | 1.4 kB  00:00:00 !!! 
updates                                                                                                                                                                                      | 3.4 kB  00:00:00     
(1/14): base/7/x86_64/other_db                                                                                                                                                               | 2.6 MB  00:00:00     
(2/14): base/7/x86_64/filelists_db                                                                                                                                                           | 7.1 MB  00:00:00     
(3/14): epel/x86_64/prestodelta                                                                                                                                                              | 2.2 kB  00:00:00     
(4/14): epel/x86_64/filelists_db                                                                                                                                                             |  12 MB  00:00:00     
(5/14): extras/7/x86_64/filelists_db                                                                                                                                                         | 249 kB  00:00:00     
(6/14): extras/7/x86_64/other_db                                                                                                                                                             | 131 kB  00:00:00     
(7/14): epel/x86_64/other_db                                                                                                                                                                 | 3.3 MB  00:00:00     
(8/14): updates/7/x86_64/filelists_db                                                                                                                                                        | 5.2 MB  00:00:00     
(9/14): extras/7/x86_64/prestodelta                                                                                                                                                          |  73 kB  00:00:00     
(10/14): updates/7/x86_64/prestodelta                                                                                                                                                        | 945 kB  00:00:00     
(11/14): updates/7/x86_64/other_db                                                                                                                                                           | 764 kB  00:00:00     
(12/14): google-compute-engine/filelists                                                                                                                                                     | 3.1 kB  00:00:00     
(13/14): google-compute-engine/other                                                                                                                                                         |  881 B  00:00:00     
(14/14): epel/x86_64/updateinfo_zck                                                                                                                                                          | 1.5 MB  00:00:00     
google-cloud-sdk/filelists                                                                                                                                                                   |  25 MB  00:00:00     
https://packages.cloud.google.com/yum/repos/cloud-sdk-el7-x86_64/repodata/filelists.xml.gz: [Errno -1] Metadata file does not match checksum
Trying other mirror.


 One of the configured repositories failed (Google Cloud SDK),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=google-cloud-sdk ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable google-cloud-sdk
        or
            subscription-manager repos --disable=google-cloud-sdk

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=google-cloud-sdk.skip_if_unavailable=true

failure: repodata/filelists.xml.gz from google-cloud-sdk: [Errno 256] No more mirrors to try.
https://packages.cloud.google.com/yum/repos/cloud-sdk-el7-x86_64/repodata/filelists.xml.gz: [Errno -1] Metadata file does not match checksum
[scylla-test@amos-centos7-upgrade-test ~]$ sudo yum makecache
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
epel/x86_64/metalink                                                                                                                                                                         |  17 kB  00:00:00     
 * base: repo1.ash.innoscale.net
 * epel: mirror.us.leaseweb.net
 * extras: repo1.ash.innoscale.net
 * updates: repo1.ash.innoscale.net
base                                                                                                                                                                                         | 3.6 kB  00:00:00     
extras                                                                                                                                                                                       | 3.4 kB  00:00:00     
google-cloud-sdk/signature                                                                                                                                                                   |  454 B  00:00:00     
google-cloud-sdk/signature                                                                                                                                                                   | 1.4 kB  00:00:00 !!! 
google-compute-engine/signature                                                                                                                                                              |  454 B  00:00:00     
google-compute-engine/signature                                                                                                                                                              | 1.4 kB  00:00:00 !!! 
updates                                                                                                                                                                                      | 3.4 kB  00:00:00     
(1/2): google-cloud-sdk/other                                                                                                                                                                |  37 kB  00:00:00     
(2/2): google-cloud-sdk/filelists                                                                                                                                                            |  25 MB  00:00:01     
google-cloud-sdk                                                                                                                                                                                            864/864
google-cloud-sdk                                                                                                                                                                                            864/864
google-compute-engine                                                                                                                                                                                         11/11
google-compute-engine                                                                                                                                                                                         11/11
Metadata Cache Created
[scylla-test@amos-centos7-upgrade-test ~]$ 
```
