### ISSUE TITLE
upgrade_test will fail for any stall backtrace

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla-cluster-tests#1261]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: branch-3.1

### Logs
* test_id: 85a67219-cf53-48f8-9429-81d7cd0ecbec
* job: http://jenkins.scylladb.com/view/scylla-3.1/job/scylla-3.1/view/scylla-3.1-test/job/rolling-upgrade/job/rolling-upgrade-centos7/85/execution/node/39/log/
* job log: https://cloudius-jenkins-test.s3.amazonaws.com/85a67219-cf53-48f8-9429-81d7cd0ecbec/job_log.zip

### Description

Some 3.1 upgrade_test failed for finding DB errors (backtrace) in log, but it's just one backtrace from stall (500 ms). 

### Steps to Reproduce

1. run 3.1 upgrade test

**Expected behavior:** We should ignore this kind of backtrace, it won't fail the job.

**Actual behavior:** Job failed.

```
< t:2019-08-26 22:46:08,455 f:tester.py       l:1330 c:sdcm.tester          p:ERROR > Errors found on DB node logs:
< t:2019-08-26 22:46:08,455 f:tester.py       l:1331 c:sdcm.tester          p:ERROR > 2019-08-26 20:41:05.846: (DatabaseLogEvent Severity.ERROR): type=BACKTRACE regex=backtrace line_number=10596 node=Node rolling
-upgrade-3-1-centos-db-node-85a67219-0-4 [35.196.160.56 | 10.142.0.110] (seed: False)
< t:2019-08-26 22:46:08,455 f:tester.py       l:1331 c:sdcm.tester          p:ERROR > 2019-08-26T20:40:51+00:00  rolling-upgrade-3-1-centos-db-node-85a67219-0-4 !INFO    | scylla: Backtrace:
< t:2019-08-26 22:46:08,455 f:tester.py       l:1331 c:sdcm.tester          p:ERROR > 
< t:2019-08-26 22:46:08,455 f:tester.py       l:1331 c:sdcm.tester          p:ERROR > 0x00000000006ab5a2
....

< t:2019-08-26 22:46:08,455 f:tester.py       l:1331 c:sdcm.tester          p:ERROR > 2019-08-26 21:32:13.661: (DatabaseLogEvent Severity.ERROR): type=BACKTRACE regex=backtrace line_number=16029 node=Node rolling
-upgrade-3-1-centos-db-node-85a67219-0-4 [35.196.160.56 | 10.142.0.110] (seed: False)
< t:2019-08-26 22:46:08,455 f:tester.py       l:1331 c:sdcm.tester          p:ERROR > 2019-08-26T21:32:01+00:00  rolling-upgrade-3-1-centos-db-node-85a67219-0-4 !INFO    | scylla: Backtrace:
< t:2019-08-26 22:46:08,455 f:tester.py       l:1331 c:sdcm.tester          p:ERROR > 
....
....
< t:2019-08-26 22:46:08,456 f:tester.py       l:1380 c:sdcm.tester          p:ERROR > Exception in finalize_test method Errors found on DB node logs (see test logs) < t:2019-08-26 22:46:08,456 f:tester.py       l:1380 c:sdcm.tester          p:ERROR > Exception in finalize_test method Errors found on DB node logs (see test logs)
< t:2019-08-26 22:46:08,456 f:tester.py       l:1380 c:sdcm.tester          p:ERROR > Traceback (most recent call last):
< t:2019-08-26 22:46:08,456 f:tester.py       l:1380 c:sdcm.tester          p:ERROR >   File "/sct/sdcm/tester.py", line 1378, in tearDown
< t:2019-08-26 22:46:08,456 f:tester.py       l:1380 c:sdcm.tester          p:ERROR >     self.finalize_test()
< t:2019-08-26 22:46:08,456 f:tester.py       l:1380 c:sdcm.tester          p:ERROR >   File "/sct/sdcm/tester.py", line 1287, in finalize_test
< t:2019-08-26 22:46:08,456 f:tester.py       l:1380 c:sdcm.tester          p:ERROR >     self.stop_resources()
< t:2019-08-26 22:46:08,456 f:tester.py       l:1380 c:sdcm.tester          p:ERROR >   File "/sct/sdcm/tester.py", line 1332, in stop_resources
< t:2019-08-26 22:46:08,456 f:tester.py       l:1380 c:sdcm.tester          p:ERROR >     self.fail('Errors found on DB node logs (see test logs)')
< t:2019-08-26 22:46:08,456 f:tester.py       l:1380 c:sdcm.tester          p:ERROR >   File "/usr/lib64/python2.7/unittest/case.py", line 450, in fail
< t:2019-08-26 22:46:08,456 f:tester.py       l:1380 c:sdcm.tester          p:ERROR >     raise self.failureException(msg)
< t:2019-08-26 22:46:08,456 f:tester.py       l:1380 c:sdcm.tester          p:ERROR > AssertionError: Errors found on DB node logs (see test logs)
```

**Comment by fruch** [comment]
I've started working on a fix for this one, didn't had change to finish it:
databaselog1.log is a small sample log of the core issue, and the test wasn't finished

```
diff --cc sdcm/cluster.py
index 19994d1,19994d1..e3c39ef
--- a/sdcm/cluster.py
+++ b/sdcm/cluster.py
@@@ -1237,16 -1237,16 +1237,18 @@@ class BaseNode(object)
                  last_error = filter_backtraces.last_error
                  try:
                      if (last_error and
--                            backtrace['event'].line_number <= filter_backtraces.last_error.line_number + 10
++                            backtrace['event'].line_number <= filter_backtraces.last_error.line_number + 50
                              and not filter_backtraces.last_error.type == 'BACKTRACE'):
                          last_error.add_backtrace_info(raw_backtrace="\n".join(backtrace['backtrace']))
                          return False
                      return True
                  finally:
                      filter_backtraces.last_error = backtrace['event']
--            filter_backtraces.last_error = None
  
--            backtraces = filter(filter_backtraces, backtraces)
++            # support interlaced reactor stalled
++            for i in range(2):
++                filter_backtraces.last_error = None
++                backtraces = filter(filter_backtraces, backtraces)
  
              for backtrace in backtraces:
                  if Setup.BACKTRACE_DECODING:
diff --cc unit_tests/test_cluster.py
index e6b3a04,e6b3a04..2e72dd2
--- a/unit_tests/test_cluster.py
+++ b/unit_tests/test_cluster.py
@@@ -84,3 -84,3 +84,14 @@@ class TestBaseNode(unittest.TestCase)
  
          for line_number, line in errors:
              print line_number, line
++
++    def test_search_database_interlace_reactor_stall(self):
++
++        self.node.database_log = os.path.join(os.path.dirname(__file__), 'test_data', 'databaselog1.log')
++
++        critical_errors = self.node.search_database_log()
++        self.assertEqual(len(critical_errors), 4)
++
++        for line_number, line in critical_errors:
++            print line
++
```

**Comment by fruch** [comment]
same root case as in #1228
