### ISSUE TITLE
"[Errno 104] Connection reset by peer" or "SSHException: Unable to open channel" during `uptime_changed` while calling `AwsNode.reboot()`

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#1278]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: branch-3.1
* **scylla**: branch-3.1.rc4

### Logs
* test_id: e7b34f53-174f-4b68-993b-ed640fa79cea
* job log: https://cloudius-jenkins-test.s3.amazonaws.com/e7b34f53-174f-4b68-993b-ed640fa79cea/job_log.zip

```
(DisruptionEvent Severity.ERROR): type=end name=SoftRebootNode node=Node longevity-200gb-48h-verify-limited--db-node-e7b34f53-3 [18.203.251.65 | 10.0.38.110] (seed: False) duration=74 error=[Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/sct/sdcm/nemesis.py", line 1030, in wrapper
    result = method(*args, **kwargs)
  File "/sct/sdcm/nemesis.py", line 1266, in disrupt
    'disrupt_truncate', 'disrupt_show_toppartitions'])
  File "/sct/sdcm/nemesis.py", line 533, in call_random_disrupt_method
    disrupt_method()
  File "/sct/sdcm/nemesis.py", line 231, in disrupt_soft_reboot_node
    self.target_node.reboot(hard=False)
  File "/sct/sdcm/cluster_aws.py", line 460, in reboot
    wait.wait_for(func=uptime_changed, step=1, timeout=60, throw_exc=True)
  File "/sct/sdcm/wait.py", line 58, in wait_for
    res = r.call(func, **kwargs)
  File "/usr/lib/python2.7/site-packages/tenacity/__init__.py", line 358, in call
    do = self.iter(retry_state=retry_state)
  File "/usr/lib/python2.7/site-packages/tenacity/__init__.py", line 331, in iter
    raise retry_exc.reraise()
  File "/usr/lib/python2.7/site-packages/tenacity/__init__.py", line 167, in reraise
    raise self.last_attempt.result()
  File "/usr/lib/python2.7/site-packages/concurrent/futures/_base.py", line 455, in result
    return self.__get_result()
  File "/usr/lib/python2.7/site-packages/tenacity/__init__.py", line 361, in call
    result = fn(*args, **kwargs)
  File "/sct/sdcm/cluster_aws.py", line 449, in uptime_changed
    result = self.remoter.run('uptime -s', ignore_status=True)
  File "/sct/sdcm/remote.py", line 227, in run
    watchers=watchers, timeout=timeout)
  File "", line 2, in run
  File "/usr/lib/python2.7/site-packages/fabric/connection.py", line 30, in opens
    return method(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/fabric/connection.py", line 721, in run
    return self._run(self._remote_runner(), command, **kwargs)
  File "/usr/lib/python2.7/site-packages/invoke/context.py", line 101, in _run
    return runner.run(command, **kwargs)
  File "/usr/lib/python2.7/site-packages/invoke/runners.py", line 291, in run
    return self._run_body(command, **kwargs)
  File "/usr/lib/python2.7/site-packages/invoke/runners.py", line 315, in _run_body
    self.start(command, shell, env)
  File "/usr/lib/python2.7/site-packages/fabric/runners.py", line 36, in start
    self.channel = self.context.create_session()
  File "", line 2, in create_session
  File "/usr/lib/python2.7/site-packages/fabric/connection.py", line 30, in opens
    return method(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/fabric/connection.py", line 698, in create_session
    channel = self.transport.open_session()
  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 879, in open_session
    timeout=timeout,
  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 1006, in open_channel
    raise e
error: [Errno 104] Connection reset by peer
```

also this:

```
DisruptionEvent Severity.ERROR): type=end name=SoftRebootNode node=Node longevity-200gb-48h-verify-limited--db-node-e7b34f53-9 [34.255.208.194 | 10.0.48.102] (seed: False) duration=65 error=Unable to open channel.
Traceback (most recent call last):
  File "/sct/sdcm/nemesis.py", line 1030, in wrapper
    result = method(*args, **kwargs)
  File "/sct/sdcm/nemesis.py", line 1266, in disrupt
    'disrupt_truncate', 'disrupt_show_toppartitions'])
  File "/sct/sdcm/nemesis.py", line 533, in call_random_disrupt_method
    disrupt_method()
  File "/sct/sdcm/nemesis.py", line 231, in disrupt_soft_reboot_node
    self.target_node.reboot(hard=False)
  File "/sct/sdcm/cluster_aws.py", line 460, in reboot
    wait.wait_for(func=uptime_changed, step=1, timeout=60, throw_exc=True)
  File "/sct/sdcm/wait.py", line 58, in wait_for
    res = r.call(func, **kwargs)
  File "/usr/lib/python2.7/site-packages/tenacity/__init__.py", line 358, in call
    do = self.iter(retry_state=retry_state)
  File "/usr/lib/python2.7/site-packages/tenacity/__init__.py", line 331, in iter
    raise retry_exc.reraise()
  File "/usr/lib/python2.7/site-packages/tenacity/__init__.py", line 167, in reraise
    raise self.last_attempt.result()
  File "/usr/lib/python2.7/site-packages/concurrent/futures/_base.py", line 455, in result
    return self.__get_result()
  File "/usr/lib/python2.7/site-packages/tenacity/__init__.py", line 361, in call
    result = fn(*args, **kwargs)
  File "/sct/sdcm/cluster_aws.py", line 449, in uptime_changed
    result = self.remoter.run('uptime -s', ignore_status=True)
  File "/sct/sdcm/remote.py", line 227, in run
    watchers=watchers, timeout=timeout)
  File "", line 2, in run
  File "/usr/lib/python2.7/site-packages/fabric/connection.py", line 30, in opens
    return method(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/fabric/connection.py", line 721, in run
    return self._run(self._remote_runner(), command, **kwargs)
  File "/usr/lib/python2.7/site-packages/invoke/context.py", line 101, in _run
    return runner.run(command, **kwargs)
  File "/usr/lib/python2.7/site-packages/invoke/runners.py", line 291, in run
    return self._run_body(command, **kwargs)
  File "/usr/lib/python2.7/site-packages/invoke/runners.py", line 315, in _run_body
    self.start(command, shell, env)
  File "/usr/lib/python2.7/site-packages/fabric/runners.py", line 36, in start
    self.channel = self.context.create_session()
  File "", line 2, in create_session
  File "/usr/lib/python2.7/site-packages/fabric/connection.py", line 30, in opens
    return method(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/fabric/connection.py", line 698, in create_session
    channel = self.transport.open_session()
  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 879, in open_session
    timeout=timeout,
  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 1006, in open_channel
    raise e
SSHException: Unable to open channel.
```

**Comment by fruch** [comment]
@amoskong this is around something you recently changed, any thought what might be the cause ?

**Comment by amoskong** [comment]
Oh, `ignore_status=True` can't suppress this kind of exception, so we need a try..except.

I will post a fix now.
