### ISSUE TITLE
abort repair nemesis fails in 'Wait for repair starts'

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#1303]
### Prerequisites

* [x] Are you rebased to master ?
* [ ] Is it reproducible ?
* [ ] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: 3.1
* **scylla**: 3.1 rc5

### Logs
* test_id: 729a1e65-cd23-4d5a-9c20-ba5e441ca028

### Description
```
< t:2019-09-06 04:44:11,740 f:nemesis.py      l:584  c:sdcm.nemesis         p:ERROR > sdcm.nemesis.ChaosMonkey: ('Exception in random_disrupt_method %s: %s', 'abort_repair', RetryError())
< t:2019-09-06 04:44:11,930 f:nemesis.py      l:1082 c:sdcm.nemesis         p:ERROR > sdcm.nemesis.ChaosMonkey: Unhandled exception in method <function disrupt at 0x7fe0477c4b18> < t:2019-09-06 04:44:11,930 f:nemesis.py      l:1082
 c:sdcm.nemesis         p:ERROR > sdcm.nemesis.ChaosMonkey: Unhandled exception in method <function disrupt at 0x7fe0477c4b18>
< t:2019-09-06 04:44:11,930 f:nemesis.py      l:1082 c:sdcm.nemesis         p:ERROR > Traceback (most recent call last):
< t:2019-09-06 04:44:11,930 f:nemesis.py      l:1082 c:sdcm.nemesis         p:ERROR >   File "/sct/sdcm/nemesis.py", line 1078, in wrapper
< t:2019-09-06 04:44:11,930 f:nemesis.py      l:1082 c:sdcm.nemesis         p:ERROR >     result = method(*args, **kwargs)
< t:2019-09-06 04:44:11,930 f:nemesis.py      l:1082 c:sdcm.nemesis         p:ERROR >   File "/sct/sdcm/nemesis.py", line 1287, in disrupt
< t:2019-09-06 04:44:11,930 f:nemesis.py      l:1082 c:sdcm.nemesis         p:ERROR >     self.call_random_disrupt_method()
< t:2019-09-06 04:44:11,930 f:nemesis.py      l:1082 c:sdcm.nemesis         p:ERROR >   File "/sct/sdcm/nemesis.py", line 581, in call_random_disrupt_method
< t:2019-09-06 04:44:11,930 f:nemesis.py      l:1082 c:sdcm.nemesis         p:ERROR >     disrupt_method()
< t:2019-09-06 04:44:11,930 f:nemesis.py      l:1082 c:sdcm.nemesis         p:ERROR >   File "/sct/sdcm/nemesis.py", line 890, in disrupt_abort_repair
< t:2019-09-06 04:44:11,930 f:nemesis.py      l:1082 c:sdcm.nemesis         p:ERROR >     text='Wait for repair starts')
< t:2019-09-06 04:44:11,930 f:nemesis.py      l:1082 c:sdcm.nemesis         p:ERROR >   File "/sct/sdcm/wait.py", line 58, in wait_for
< t:2019-09-06 04:44:11,930 f:nemesis.py      l:1082 c:sdcm.nemesis         p:ERROR >     res = r.call(func, **kwargs)
< t:2019-09-06 04:44:11,930 f:nemesis.py      l:1082 c:sdcm.nemesis         p:ERROR >   File "/usr/lib/python2.7/site-packages/tenacity/__init__.py", line 358, in call
< t:2019-09-06 04:44:11,930 f:nemesis.py      l:1082 c:sdcm.nemesis         p:ERROR >     do = self.iter(retry_state=retry_state)
< t:2019-09-06 04:44:11,930 f:nemesis.py      l:1082 c:sdcm.nemesis         p:ERROR >   File "/usr/lib/python2.7/site-packages/tenacity/__init__.py", line 331, in iter
< t:2019-09-06 04:44:11,930 f:nemesis.py      l:1082 c:sdcm.nemesis         p:ERROR >     raise retry_exc.reraise()
< t:2019-09-06 04:44:11,930 f:nemesis.py      l:1082 c:sdcm.nemesis         p:ERROR >   File "/usr/lib/python2.7/site-packages/tenacity/__init__.py", line 168, in reraise
< t:2019-09-06 04:44:11,930 f:nemesis.py      l:1082 c:sdcm.nemesis         p:ERROR >     raise self
< t:2019-09-06 04:44:11,930 f:nemesis.py      l:1082 c:sdcm.nemesis         p:ERROR > RetryError: RetryError[<Future at 0x7fe008433d90 state=finished returned bool>]
< t:2019-09-06 04:44:11,931 f:nemesis.py      l:1094 c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: AbortRepairMonkey duration -> 302 s
```
[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]
logs:
job:
https://jenkins.scylladb.com/view/scylla-3.1/job/scylla-3.1/view/scylla-3.1-test/job/longevity/job/longevity-50gb-4days/13/

scratch.scylladb.com/issues/sct_ReadFailureException.log.gz
snapshot:
https://snapshot.raintank.io/dashboard/snapshot/VnrVHPU6cMaysa7zMZ5vypgC9hWPwmH3

**Comment by juliayakovlev** [comment]
@bentsi  @fruch 

I received the same problem during MV&SI longevity (with 3.1 rc9)
This error happens when we try to receive active_repair processes. 
```curl -s -X GET --header "Content-Type: application/json" --header "Accept: application/json" "http://127.0.0.1:10000/storage_service/active_repair/"```
Seems it return empty list (I assume). But in the log I see ```repair - Repair``` info in the same time.
I think we need to print out the curl output to see what happens there

**Comment by fgelcer** [comment]
i'm seeing this issue happening:

```
2020-05-12 23:44:59.019: (DisruptionEvent Severity.NORMAL): type=start name=AbortRepairMonkey node=Node alternator-3h-4-0-db-node-4f027403-7 [34.244.16.2 | 10.0.206.14] (seed: False) duration=None
2020-05-12 23:49:59.372: (DisruptionEvent Severity.ERROR): type=end name=AbortRepairMonkey node=Node alternator-3h-4-0-db-node-4f027403-7 [34.244.16.2 | 10.0.206.14] (seed: False) duration=300 error=RetryError[Wait for: Wait for repair starts: timeout - 300 seconds - expired]
Traceback (most recent call last):
  File "/sct/sdcm/wait.py", line 60, in wait_for
    res = retry.call(func, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 358, in call
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 331, in iter
    raise retry_exc.reraise()
  File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 168, in reraise
    raise self
tenacity.RetryError: RetryError[<Future at 0x7f7adc5b8208 state=finished returned bool>]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sct/sdcm/nemesis.py", line 1793, in wrapper
    result = method(*args, **kwargs)
  File "/sct/sdcm/nemesis.py", line 2009, in disrupt
    self.call_random_disrupt_method()
  File "/sct/sdcm/nemesis.py", line 655, in call_random_disrupt_method
    disrupt_method()
  File "/sct/sdcm/nemesis.py", line 1318, in disrupt_abort_repair
    text='Wait for repair starts')
  File "/sct/sdcm/wait.py", line 71, in wait_for
    raise RetryError(err)
tenacity.RetryError: RetryError[Wait for: Wait for repair starts: timeout - 300 seconds - expired]
```

but in the node's log i see that repair was indeed started:
```
2020-05-12T23:45:01+00:00  alternator-3h-4-0-db-node-4f027403-7 !INFO    | scylla: [shard 0] repair - starting user-requested repair for keyspace system_traces, repair id 172, options {{ trace -> false}, { incremental -> false}, { jobThreads -> 1}, { primaryRange -> false}, { parallelism -> parallel}}
2020-05-12T23:45:01+00:00  alternator-3h-4-0-db-node-4f027403-7 !INFO    | scylla: [shard 0] repair - Repair 1 out of 522 ranges, id=172, shard=0, keyspace=system_traces, table={events, sessions, node_slow_log, sessions_time_idx, node_slow_log_time_idx}, range=(-9213606854074140248, -9210968997662535074]
2020-05-12T23:45:01+00:00  alternator-3h-4-0-db-node-4f027403-7 !INFO    | scylla: [shard 0] repair - Repair 2 out of 522 ranges, id=172, shard=0, keyspace=system_traces, table={events, sessions, node_slow_log, sessions_time_idx, node_slow_log_time_idx}, range=(-9210968997662535074, -9202723877980281335]
2020-05-12T23:45:01+00:00  alternator-3h-4-0-db-node-4f027403-7 !INFO    | scylla: [shard 0] repair - Repair 3 out of 522 ranges, id=172, shard=0, keyspace=system_traces, table={events, sessions, node_slow_log, sessions_time_idx, node_slow_log_time_idx}, range=(-9202723877980281335, -9202366883947459168]
2020-05-12T23:45:01+00:00  alternator-3h-4-0-db-node-4f027403-7 !INFO    | scylla: [shard 0] repair - Repair 4 out of 522 ranges, id=172, shard=0, keyspace=system_traces, table={events, sessions, node_slow_log, sessions_time_idx, node_slow_log_time_idx}, range=(-9202366883947459168, -9201344798286790218]
...
```

full logs can be found here:
```
+--------------------------------------------------------------------------------------------------------------------------------------------+
|                                      Collected logs by test-id: 4f027403-5aeb-46f7-bf10-086eafdf4131                                       |
+-------------+------------------------------------------------------------------------------------------------------------------------------+
| Cluster set | Link                                                                                                                         |
+-------------+------------------------------------------------------------------------------------------------------------------------------+
| db-cluster  | https://cloudius-jenkins-test.s3.amazonaws.com/4f027403-5aeb-46f7-bf10-086eafdf4131/20200513_003914/db-cluster-4f027403.zip  |
| monitor-set | https://cloudius-jenkins-test.s3.amazonaws.com/4f027403-5aeb-46f7-bf10-086eafdf4131/20200513_003914/monitor-set-4f027403.zip |
| loader-set  | https://cloudius-jenkins-test.s3.amazonaws.com/4f027403-5aeb-46f7-bf10-086eafdf4131/20200513_003914/loader-set-4f027403.zip  |
| sct-runner  | https://cloudius-jenkins-test.s3.amazonaws.com/4f027403-5aeb-46f7-bf10-086eafdf4131/20200513_003914/sct-runner-4f027403.zip  |
+-------------+------------------------------------------------------------------------------------------------------------------------------+
```

**Comment by roydahan** [comment]
@bentsi, let's disable this nemesis for now and open a task for @amoskong to fix this issue.

**Comment by amoskong** [comment]
> @bentsi, let's disable this nemesis for now and open a task for @amoskong to fix this issue.

We have an old PR (closed without merge): https://github.com/scylladb/scylla-cluster-tests/pull/1029 , which skipped the nemesis if repair streaming doesn't exist.

I will check if 'storage_service/active_repair/' API changed recently.

**Comment by amoskong** [comment]
fix abort repair nemesis:
- destroy data before first repair by self._destroy_data_and_restart_scylla()
- check the repair task by watching the db log

In Scylla 4.0, we don't use latest repair ops for repair, but still use streaming. This might be the reason why we can't find repair task by active_repair API. I will check with @asias

**Comment by amoskong** [comment]
duplicated to https://github.com/scylladb/scylla-cluster-tests/issues/885
