### ISSUE TITLE
fail to copy prometheus.yml.template from monitor: Exit code: None

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla-cluster-tests#1304]
### Prerequisites

* [ ] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: branch-3.1 

### Logs
* Test ID: 43255fcd-2b36-4011-9a0f-8d2016ec6325
* job log: https://cloudius-jenkins-test.s3.amazonaws.com/43255fcd-2b36-4011-9a0f-8d2016ec6325/job_log.zip
* Job link: http://jenkins.scylladb.com/view/scylla-3.1/job/scylla-3.1/view/scylla-3.1-test/job/rolling-upgrade/job/rolling-upgrade-ubuntu16.04/94/execution/node/41/log/

### Description

I saw this error multiple times in upgrade test of 3.1
The monitor is centos7

### Steps to Reproduce

1. run upgrade test of 3.1, it can't be reproduced all the time.

**Expected behavior:**  Monitor setup succeeds.

**Actual behavior:** Monitor setup failed in copying prometheus.yml.template from monitor node to sct builder by scp.

```
ERROR > GCE Cluster rolling-upgrade-upgrade--ubuntu-xen-monitor-set-43255fcd | Image: centos-7 | Root Disk: pd-standard 50 GB | Type: n1-standard-1: Node setup failed: Node rolling-upgrade-upgrade--ubuntu-xen-monitor-node-43255fcd-0-1 [104.196.26.27 | 10.142.0.167] (seed: False) < t:2019-09-10 22:10:27,237 f:cluster.py      l:2353 c:sdcm.cluster         p:ERROR > GCE Cluster rolling-upgrade-upgrade--ubuntu-xen-monitor-set-43255fcd | Image: centos-7 | Root Disk: pd-standard 50 GB | Type: n1-standard-1: Node setup failed: Node rolling-upgrade-upgrade--ubuntu-xen-monitor-node-43255fcd-0-1 [104.196.26.27 | 10.142.0.167] (seed: False)
ERROR > Traceback (most recent call last):
ERROR >   File "/sct/sdcm/cluster.py", line 2351, in node_setup
ERROR >     cl_inst.node_setup(node, **setup_kwargs)
ERROR >   File "/sct/sdcm/cluster.py", line 3332, in node_setup
ERROR >     self.configure_scylla_monitoring(node)
ERROR >   File "/sct/sdcm/cluster.py", line 3452, in configure_scylla_monitoring
ERROR >     dst=local_template_tmp)
ERROR >   File "/sct/sdcm/remote.py", line 313, in receive_files
ERROR >     r = self.connection.local(scp)
ERROR >   File "/usr/lib/python2.7/site-packages/fabric/connection.py", line 748, in local
ERROR >     return super(Connection, self).run(*args, **kwargs)
ERROR >   File "/usr/lib/python2.7/site-packages/invoke/context.py", line 94, in run
ERROR >     return self._run(runner, command, **kwargs)
ERROR >   File "/usr/lib/python2.7/site-packages/invoke/context.py", line 101, in _run
ERROR >     return runner.run(command, **kwargs)
ERROR >   File "/usr/lib/python2.7/site-packages/invoke/runners.py", line 291, in run
ERROR >     return self._run_body(command, **kwargs)
ERROR >   File "/usr/lib/python2.7/site-packages/invoke/runners.py", line 442, in _run_body
ERROR >     raise UnexpectedExit(result)
ERROR > UnexpectedExit: Encountered a bad command exit code!
ERROR > 
ERROR > Command: u'scp -r -o StrictHostKeyChecking=no -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -o UserKnownHostsFile=/tmp/tmpVYoTmr -P 22 -i /jenkins/.ssh/scylla-test scylla-test@10.142.0.167:"/home/scylla-test/scylla-monitoring-branch-2.4/prometheus/prometheus.yml.template" \'/tmp/tmpP9tKxe/prometheus.yml.template.orig\''
ERROR > 
ERROR > Exit code: None
ERROR > 
ERROR > Stdout: already printed
ERROR > 
ERROR > Stderr: already printed
ERROR > 
l p:DEBUG > https://www.googleapis.com:443 "GET /compute/v1/projects/skilled-adapter-452/zones/us-east1-b/instances/rolling-upgrade-upgrade--ubuntu-xen-monitor-node-43255fcd-0-1 HTTP/1.1" 200 None
l p:DEBUG > https://www.googleapis.com:443 "GET /compute/v1/projects/skilled-adapter-452/aggregated/disks?maxResults=500 HTTP/1.1" 200 None
l p:DEBUG > https://www.googleapis.com:443 "GET /compute/v1/projects/skilled-adapter-452/zones/us-east1-b/instances/rolling-upgrade-upgrade--ubuntu-xen-monitor-node-43255fcd-0-1 HTTP/1.1" 200 None
l p:DEBUG > https://www.googleapis.com:443 "GET /compute/v1/projects/skilled-adapter-452/aggregated/disks?maxResults=500 HTTP/1.1" 200 None
ERROR > Exception in setUp. Will call tearDown < t:2019-09-10 22:10:28,154 f:tester.py       l:132  c:sdcm.tester          p:ERROR > Exception in setUp. Will call tearDown
ERROR > Traceback (most recent call last):
ERROR >   File "/sct/sdcm/tester.py", line 130, in wrapper
ERROR >     return method(*args, **kwargs)
ERROR >   File "/sct/sdcm/utils/common.py", line 246, in inner
ERROR >     res = func(*args, **kwargs)
ERROR >   File "/sct/sdcm/tester.py", line 248, in setUp
ERROR >     self.monitors.wait_for_init()
ERROR >   File "/sct/sdcm/cluster.py", line 2374, in wrapper
ERROR >     raise NodeSetupFailed("{node}:{node_status}".format(**locals()))
ERROR > NodeSetupFailed: Node rolling-upgrade-upgrade--ubuntu-xen-monitor-node-43255fcd-0-1 [104.196.26.27 | 10.142.0.167] (seed: False):False
```

**Comment by amoskong** [comment]
Talked with @alexsavilov , we need to backport PR https://github.com/scylladb/scylla-cluster-tests/pull/1224 to solve this issue.
