### ISSUE TITLE
Failure on copying file from one node, failed the job log upload

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#1317]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: [branch or hash tag you are working on]
* **scylla**: [branch or commit hash]

### Logs
* test_id: 71e8ae32-c95f-4f93-9716-940b419169f7
* job log: https://jenkins.scylladb.com/view/scylla-3.1/job/scylla-3.1/view/scylla-3.1-test/job/longevity/job/longevity-multi-keyspaces-60h/17

### Description
Failure on copying file from one node, cause job log not to uploaded

```
======================================================================
ERROR [280562.466s]: test_custom_time (longevity_test.LongevityTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/sct/sdcm/tester.py", line 1380, in tearDown
    self.finalize_test()
  File "/sct/sdcm/tester.py", line 1290, in finalize_test
    self.collect_logs()
  File "/sct/sdcm/tester.py", line 1582, in collect_logs
    db_cluster_log_path = self.db_cluster.collect_logs(storing_dir)
  File "/sct/sdcm/cluster.py", line 2869, in collect_logs
    node.receive_files(src=src_dir, dst=storing_dir)
  File "/sct/sdcm/cluster.py", line 749, in receive_files
    verbose=verbose)
  File "/sct/sdcm/remote.py", line 313, in receive_files
    r = self.connection.local(scp)
  File "/usr/lib/python2.7/site-packages/fabric/connection.py", line 748, in local
    return super(Connection, self).run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/invoke/context.py", line 94, in run
    return self._run(runner, command, **kwargs)
  File "/usr/lib/python2.7/site-packages/invoke/context.py", line 101, in _run
    return runner.run(command, **kwargs)
  File "/usr/lib/python2.7/site-packages/invoke/runners.py", line 291, in run
    return self._run_body(command, **kwargs)
  File "/usr/lib/python2.7/site-packages/invoke/runners.py", line 442, in _run_body
    raise UnexpectedExit(result)
UnexpectedExit: Encountered a bad command exit code!

Command: u'scp -r -o StrictHostKeyChecking=no -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -o UserKnownHostsFile=/tmp/tmpDfGBTe -P 22 -i /home/jenkins/.ssh/scylla-qa-ec2 centos@54.77.253.115:"/tmp/longevity-1000-keyspaces-3-1-db-node-71e8ae32-8" \'/sct/20190910-090830-262666/collected_logs/longevity-1000-keyspaces-3-1-db-cluster-71e8ae32\''

Exit code: 1
```

**Comment by fruch** [comment]
@aleksbykov FYI, a thing to take notice on PR #1150
