### ISSUE TITLE
disrupt_show_toppartitions: nodetool: Found unexpected parameters

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla-cluster-tests#1320]
### Prerequisites

* [ ] Are you rebased to master ?
* [ ] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: branch-2019.1
* scylla version: 2019.1.2-0.20190906.cd45ef55e 

### Logs
* test_id: 2a7fea25-2588-4ef7-8e84-8ae75cf9fc81
* Logs
  - events                : https://cloudius-jenkins-test.s3.amazonaws.com/2a7fea25-2588-4ef7-8e84-8ae75cf9fc81/events_log.zip                                                      
  - grafana               : https://cloudius-jenkins-test.s3.amazonaws.com/2a7fea25-2588-4ef7-8e84-8ae75cf9fc81/grafana-screenshot-overview-metrics-20190915_093122-0.png           
  - grafana               : https://cloudius-jenkins-test.s3.amazonaws.com/2a7fea25-2588-4ef7-8e84-8ae75cf9fc81/grafana-screenshot-per-server-metrics-nemesis-20190915_093009-0.png 
  - job                   : https://cloudius-jenkins-test.s3.amazonaws.com/2a7fea25-2588-4ef7-8e84-8ae75cf9fc81/job_log.zip                                                         
  - db-cluster            : https://cloudius-jenkins-test.s3.amazonaws.com/2a7fea25-2588-4ef7-8e84-8ae75cf9fc81/longevity-encrypt-at-rest-200gb-6h--db-cluster-2a7fea25.zip         
  - loader-set            : https://cloudius-jenkins-test.s3.amazonaws.com/2a7fea25-2588-4ef7-8e84-8ae75cf9fc81/longevity-encrypt-at-rest-200gb-6h--loader-set-2a7fea25.zip         
  - monitor-set           : https://cloudius-jenkins-test.s3.amazonaws.com/2a7fea25-2588-4ef7-8e84-8ae75cf9fc81/longevity-encrypt-at-rest-200gb-6h--monitor-set-2a7fea25.zip        
  - monitoring_data_stack : https://cloudius-jenkins-test.s3.amazonaws.com/2a7fea25-2588-4ef7-8e84-8ae75cf9fc81/monitoring_data_stack_branch-2.4_2019.1.tar.gz    

### Description

nodetool failed for unexpected prameters in disrupt_show_toppartitions nemesis.

### Steps to Reproduce

1. run longevity.

**Expected behavior:** nodetool command succeeds.

**Actual behavior:** 

```
Traceback (most recent call last):
  File "/sct/sdcm/nemesis.py", line 1063, in wrapper
    result = method(*args, **kwargs)
  File "/sct/sdcm/nemesis.py", line 1299, in disrupt
    'disrupt_truncate', 'disrupt_show_toppartitions'])
  File "/sct/sdcm/nemesis.py", line 585, in call_random_disrupt_method
    disrupt_method()
  File "/sct/sdcm/nemesis.py", line 1005, in disrupt_show_toppartitions
    result = self.target_node.run_nodetool(sub_cmd='toppartitions', args=sub_cmd_args)
  File "/sct/sdcm/cluster.py", line 2023, in run_nodetool
    result = self.remoter.run(cmd, ignore_status=ignore_status, verbose=verbose)
  File "/sct/sdcm/remote.py", line 226, in run
    result = _run()
  File "/sct/sdcm/utils/common.py", line 199, in inner
    return func(*args, **kwargs)
  File "/sct/sdcm/remote.py", line 217, in _run
    watchers=watchers, timeout=timeout)
  File "<decorator-gen-3>", line 2, in run
  File "/usr/lib/python2.7/site-packages/fabric/connection.py", line 30, in opens
    return method(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/fabric/connection.py", line 721, in run
    return self._run(self._remote_runner(), command, **kwargs)
  File "/usr/lib/python2.7/site-packages/invoke/context.py", line 101, in _run
    return runner.run(command, **kwargs)
  File "/usr/lib/python2.7/site-packages/invoke/runners.py", line 291, in run
    return self._run_body(command, **kwargs)
  File "/usr/lib/python2.7/site-packages/invoke/runners.py", line 442, in _run_body
    raise UnexpectedExit(result)
UnexpectedExit: Encountered a bad command exit code!

Command: 'nodetool -u cassandra -pw cassandra  toppartitions keyspace1 standard1 6563 -s 560 -k 7 -a writes'

Exit code: 1

Stdout:

nodetool: Found unexpected parameters: [toppartitions, keyspace1, standard1, 6563, -s, 560, -k, 7, -a, writes]
See 'nodetool help' or 'nodetool help <command>'.
```

/cc @alexsavilov

**Comment by juliayakovlev** [comment]
Same failure in 2019.3 (longevity-50gb-4days):

```
< t:2019-10-26 05:56:01,891 f:nemesis.py      l:338  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> ShowTopPartitions
< t:2019-10-26 05:58:19,492 f:nemesis.py      l:588  c:sdcm.nemesis         p:ERROR > sdcm.nemesis.ChaosMonkey: ('Exception in random_disrupt_method %s: %s', 'show_toppartitions', <UnexpectedExit: cmd='nodetool -u cassandra -pw cassandra  toppartitions mview users 3910 -s 504 -k 18 -a writes,reads' exited=1>)
< t:2019-10-26 05:58:19,674 f:nemesis.py      l:1071 c:sdcm.nemesis         p:ERROR > sdcm.nemesis.ChaosMonkey: Unhandled exception in method <function disrupt at 0x7f74234eb500> < t:2019-10-26 05:58:19,674 f:nemesis.py      l:1071 c:sdcm.nemesis         p:ERROR > sdcm.nemesis.ChaosMonkey: Unhandled exception in method <function disrupt at 0x7f74234eb500>
< t:2019-10-26 05:58:19,674 f:nemesis.py      l:1071 c:sdcm.nemesis         p:ERROR > Traceback (most recent call last):
< t:2019-10-26 05:58:19,674 f:nemesis.py      l:1071 c:sdcm.nemesis         p:ERROR >   File "/sct/sdcm/nemesis.py", line 1067, in wrapper
< t:2019-10-26 05:58:19,674 f:nemesis.py      l:1071 c:sdcm.nemesis         p:ERROR >     result = method(*args, **kwargs)
< t:2019-10-26 05:58:19,674 f:nemesis.py      l:1071 c:sdcm.nemesis         p:ERROR >   File "/sct/sdcm/nemesis.py", line 1276, in disrupt
< t:2019-10-26 05:58:19,674 f:nemesis.py      l:1071 c:sdcm.nemesis         p:ERROR >     self.call_random_disrupt_method()
< t:2019-10-26 05:58:19,674 f:nemesis.py      l:1071 c:sdcm.nemesis         p:ERROR >   File "/sct/sdcm/nemesis.py", line 585, in call_random_disrupt_method
< t:2019-10-26 05:58:19,674 f:nemesis.py      l:1071 c:sdcm.nemesis         p:ERROR >     disrupt_method()
< t:2019-10-26 05:58:19,674 f:nemesis.py      l:1071 c:sdcm.nemesis         p:ERROR >   File "/sct/sdcm/nemesis.py", line 1009, in disrupt_show_toppartitions
< t:2019-10-26 05:58:19,674 f:nemesis.py      l:1071 c:sdcm.nemesis         p:ERROR >     result = self.target_node.run_nodetool(sub_cmd='toppartitions', args=sub_cmd_args)
< t:2019-10-26 05:58:19,674 f:nemesis.py      l:1071 c:sdcm.nemesis         p:ERROR >   File "/sct/sdcm/cluster.py", line 2031, in run_nodetool
< t:2019-10-26 05:58:19,674 f:nemesis.py      l:1071 c:sdcm.nemesis         p:ERROR >     result = self.remoter.run(cmd, ignore_status=ignore_status, verbose=verbose)
< t:2019-10-26 05:58:19,674 f:nemesis.py      l:1071 c:sdcm.nemesis         p:ERROR >   File "/sct/sdcm/remote.py", line 226, in run
< t:2019-10-26 05:58:19,674 f:nemesis.py      l:1071 c:sdcm.nemesis         p:ERROR >     result = _run()
< t:2019-10-26 05:58:19,674 f:nemesis.py      l:1071 c:sdcm.nemesis         p:ERROR >   File "/sct/sdcm/utils/common.py", line 87, in inner
< t:2019-10-26 05:58:19,674 f:nemesis.py      l:1071 c:sdcm.nemesis         p:ERROR >     return func(*args, **kwargs)
< t:2019-10-26 05:58:19,674 f:nemesis.py      l:1071 c:sdcm.nemesis         p:ERROR >   File "/sct/sdcm/remote.py", line 217, in _run
< t:2019-10-26 05:58:19,674 f:nemesis.py      l:1071 c:sdcm.nemesis         p:ERROR >     watchers=watchers, timeout=timeout)
< t:2019-10-26 05:58:19,674 f:nemesis.py      l:1071 c:sdcm.nemesis         p:ERROR >   File "<decorator-gen-3>", line 2, in run
< t:2019-10-26 05:58:19,674 f:nemesis.py      l:1071 c:sdcm.nemesis         p:ERROR >   File "/usr/lib/python2.7/site-packages/fabric/connection.py", line 30, in opens
< t:2019-10-26 05:58:19,674 f:nemesis.py      l:1071 c:sdcm.nemesis         p:ERROR >     return method(self, *args, **kwargs)
< t:2019-10-26 05:58:19,674 f:nemesis.py      l:1071 c:sdcm.nemesis         p:ERROR >   File "/usr/lib/python2.7/site-packages/fabric/connection.py", line 721, in run
< t:2019-10-26 05:58:19,674 f:nemesis.py      l:1071 c:sdcm.nemesis         p:ERROR >     return self._run(self._remote_runner(), command, **kwargs)
< t:2019-10-26 05:58:19,674 f:nemesis.py      l:1071 c:sdcm.nemesis         p:ERROR >   File "/usr/lib/python2.7/site-packages/invoke/context.py", line 101, in _run
< t:2019-10-26 05:58:19,674 f:nemesis.py      l:1071 c:sdcm.nemesis         p:ERROR >     return runner.run(command, **kwargs)
< t:2019-10-26 05:58:19,674 f:nemesis.py      l:1071 c:sdcm.nemesis         p:ERROR >   File "/usr/lib/python2.7/site-packages/invoke/runners.py", line 291, in run
< t:2019-10-26 05:58:19,674 f:nemesis.py      l:1071 c:sdcm.nemesis         p:ERROR >     return self._run_body(command, **kwargs)
< t:2019-10-26 05:58:19,674 f:nemesis.py      l:1071 c:sdcm.nemesis         p:ERROR >   File "/usr/lib/python2.7/site-packages/invoke/runners.py", line 442, in _run_body
< t:2019-10-26 05:58:19,674 f:nemesis.py      l:1071 c:sdcm.nemesis         p:ERROR >     raise UnexpectedExit(result)
< t:2019-10-26 05:58:19,674 f:nemesis.py      l:1071 c:sdcm.nemesis         p:ERROR > UnexpectedExit: Encountered a bad command exit code!
< t:2019-10-26 05:58:19,674 f:nemesis.py      l:1071 c:sdcm.nemesis         p:ERROR > 
< t:2019-10-26 05:58:19,674 f:nemesis.py      l:1071 c:sdcm.nemesis         p:ERROR > Command: 'nodetool -u cassandra -pw cassandra  toppartitions mview users 3910 -s 504 -k 18 -a writes,reads'
< t:2019-10-26 05:58:19,674 f:nemesis.py      l:1071 c:sdcm.nemesis         p:ERROR > 
< t:2019-10-26 05:58:19,674 f:nemesis.py      l:1071 c:sdcm.nemesis         p:ERROR > Exit code: 1
< t:2019-10-26 05:58:19,674 f:nemesis.py      l:1071 c:sdcm.nemesis         p:ERROR > 
< t:2019-10-26 05:58:19,674 f:nemesis.py      l:1071 c:sdcm.nemesis         p:ERROR > Stdout:
< t:2019-10-26 05:58:19,674 f:nemesis.py      l:1071 c:sdcm.nemesis         p:ERROR > 
< t:2019-10-26 05:58:19,674 f:nemesis.py      l:1071 c:sdcm.nemesis         p:ERROR > nodetool: Found unexpected parameters: [toppartitions, mview, users, 3910, -s, 504, -k, 18, -a, writes,reads]
< t:2019-10-26 05:58:19,674 f:nemesis.py      l:1071 c:sdcm.nemesis         p:ERROR > See 'nodetool help' or 'nodetool help <command>'.
< t:2019-10-26 05:58:19,674 f:nemesis.py      l:1071 c:sdcm.nemesis         p:ERROR > 
< t:2019-10-26 05:58:19,674 f:nemesis.py      l:1071 c:sdcm.nemesis         p:ERROR > Stderr:
```

**Comment by roydahan** [comment]
The command isn't supported in 2019.1, we need a way to mark such nemesis.

**Comment by fruch** [comment]
I think adding a commit to branch-2019.1 for just skipping it would be enough for now

**Comment by yarongilor** [comment]
i think adding decorators for nemesis functions may be useful and will make it clearer. we can have something like "@MaxVersion == 2018.1"  / "@EnterpriseOnly " and "@OpenSourceOnly" decorators.

**Comment by fruch** [comment]
Implementing this as decorator, might be a bit tricky with current nemesis implementations

**Comment by fruch** [comment]
nemesis was disabled in branch-2019.1 code
