### ISSUE TITLE
CorruptThenRebuild - can't find the path for the table

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla-cluster-tests#1415]
branch-2019.1

## logs
* **job.log**: https://cloudius-jenkins-test.s3.amazonaws.com/4bbdca86-51d2-485e-b7d7-7ccdfb8febc5/job_log.zip
* **Test ID**: 4bbdca86-51d2-485e-b7d7-7ccdfb8febc5
* **jenkins job**  http://jenkins.scylladb.com/view/enterprise-2019.1/job/enterprise-2019.1/job/longevity/job/longevity-10gb-3h/14/

Error:

```
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR > 2019-10-24 12:39:58.932: (DisruptionEvent Severity.ERROR): type=end name=CorruptThenRebuild node=Node longevity-10gb-3h-2019-1-db-node-4bbdca86-4 [3.83.24.105 | 172.30.0.155] (seed: False) duration=79 error=Encountered a bad command exit code!
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR > 
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR > Command: 'sudo find /var/lib/scylla/data/keyspace1/standard1-* -type f'
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR > 
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR > Exit code: 1
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR > 
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR > Stdout:
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR > 
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR > 
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR > 
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR > Stderr:
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR > 
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR > find: ‘/var/lib/scylla/data/keyspace1/standard1-*’: No such file or directory
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR > 
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR > 
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR > Traceback (most recent call last):
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR >   File "/sct/sdcm/nemesis.py", line 1067, in wrapper
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR >     result = method(*args, **kwargs)
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR >   File "/sct/sdcm/nemesis.py", line 1276, in disrupt
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR >     self.call_random_disrupt_method()
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR >   File "/sct/sdcm/nemesis.py", line 585, in call_random_disrupt_method
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR >     disrupt_method()
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR >   File "/sct/sdcm/nemesis.py", line 352, in disrupt_destroy_data_then_rebuild
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR >     self._destroy_data_and_restart_scylla()
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR >   File "/sct/sdcm/nemesis.py", line 313, in _destroy_data_and_restart_scylla
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR >     file_for_destroy = self._choose_file_for_destroy(ks_cfs)
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR >   File "/sct/sdcm/utils/common.py", line 92, in inner
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR >     return func(*args, **kwargs)
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR >   File "/sct/sdcm/nemesis.py", line 276, in _choose_file_for_destroy
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR >     verbose=False)
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR >   File "/sct/sdcm/remote.py", line 226, in run
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR >     result = _run()
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR >   File "/sct/sdcm/utils/common.py", line 87, in inner
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR >     return func(*args, **kwargs)
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR >   File "/sct/sdcm/remote.py", line 217, in _run
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR >     watchers=watchers, timeout=timeout)
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR >   File "<decorator-gen-3>", line 2, in run
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR >   File "/usr/lib/python2.7/site-packages/fabric/connection.py", line 30, in opens
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR >     return method(self, *args, **kwargs)
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR >   File "/usr/lib/python2.7/site-packages/fabric/connection.py", line 721, in run
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR >     return self._run(self._remote_runner(), command, **kwargs)
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR >   File "/usr/lib/python2.7/site-packages/invoke/context.py", line 101, in _run
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR >     return runner.run(command, **kwargs)
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR >   File "/usr/lib/python2.7/site-packages/invoke/runners.py", line 291, in run
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR >     return self._run_body(command, **kwargs)
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR >   File "/usr/lib/python2.7/site-packages/invoke/runners.py", line 442, in _run_body
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR >     raise UnexpectedExit(result)
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR > UnexpectedExit: Encountered a bad command exit code!
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR > 
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR > Command: 'sudo find /var/lib/scylla/data/keyspace1/standard1-* -type f'
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR > 
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR > Exit code: 1
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR > 
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR > Stdout:
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR > 
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR > 
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR > 
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR > Stderr:
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR > 
17:18:40  < t:2019-10-24 14:18:32,618 f:tester.py       l:1353 c:sdcm.tester          p:ERROR > find: ‘/var/lib/scylla/data/keyspace1/standard1-*’: No such file or directory
```

**Comment by fruch** [comment]
@roydahan it's not clear from this snippet, need to dig in to understand

**Comment by fruch** [comment]
seem like it's something that was change in scylla (not clear yet, if intentional or not)
but permission of globing as centos user doesn't work
```
master:
[centos@ip-10-0-58-238 ~]$ sudo ls -all /var/lib/scylla/data/keyspace1/
total 920
drwxr-xr-x.  3 scylla scylla     56 Oct 24 13:17 .
drwxr-xr-x.  8 scylla scylla    169 Oct 24 13:17 ..
drwxr-xr-x. 16 scylla scylla 692224 Oct 24 20:56 standard1-9b1838e0f66011e9b3cd00000000000a

2019.1.3:
[centos@ip-10-0-111-119 ~]$ sudo ls -all /var/lib/scylla/data/keyspace1/
total 900          
drwx------. 4 scylla scylla    117 Oct 24 17:01 .
drwxr-xr-x. 8 scylla scylla    169 Oct 24 16:58 ..
drwx------. 4 scylla scylla  16384 Oct 24 20:55 counter1-e86f2b70f67f11e99d9200000000000a
drwx------. 4 scylla scylla 675840 Oct 24 20:55 standard1-8b1c06a0f67f11e9827c000000000005
```

this might fix this specific issue:
```
sudo sh -c 'find /var/lib/scylla/data/keyspace1/s* -type f'
```

but we'll need to review any place touch the data dir for a proper fix

**Comment by roydahan** [comment]
This is weird, why would it change?
Latest changes should be in master.
Worth checking what is the state in 2019.1

**Comment by fruch** [comment]
@juliayakovlev fixed this
