### ISSUE TITLE
SCT fails to realize a repair has started (abort_repair)

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla-cluster-tests#1445]
### Prerequisites

* [ ] Are you rebased to master ?
* [ ] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: the branch `1tb-longevity-no-nemesis_during_prepare` from my personal fork
* **scylla**: 2019.1.3

### Logs
* test_id: a956e3a8-a4db-4c4f-bf69-86c8a60dfc5b
* job log: scratch.scylladb.com/shlomib/1tb_08_11_job_log.log

![Screenshot from 2019-11-09 00-32-16](https://user-images.githubusercontent.com/40186893/68515179-b98c2a00-0288-11ea-9387-429fa63247e0.png)

### Description

In the 1TB-7days longevity, an abort_repair nemesis has started on node#9. A repair has started on the node, as seen in its log.
However, SCT did not capture that a repair has started, and a timeout has occurred instead:
```
2019-11-01 01:16:14.635 
Traceback (most recent call last):
  File "/sct/sdcm/nemesis.py", line 1067, in wrapper
    result = method(*args, **kwargs)
  File "/sct/sdcm/nemesis.py", line 1276, in disrupt
    self.call_random_disrupt_method()
  File "/sct/sdcm/nemesis.py", line 585, in call_random_disrupt_method
    disrupt_method()
  File "/sct/sdcm/nemesis.py", line 872, in disrupt_abort_repair
    text='Wait for repair starts')
  File "/sct/sdcm/wait.py", line 70, in wait_for
    raise RetryError(err)
RetryError: RetryError[Wait for: Wait for repair starts: timeout - 300 seconds - expired]
sdcm.nemesis.ChaosMonkey: AbortRepairMonkey duration -> 300 s
```
As a result, the nemesis failed while the repair has continued, and when the next nemesis, stop_start_scylla_server, tried to run on the same problematic node, node#9,the log was spammed with events about the railed repairs:
```

2019-11-01 01:50:37.000
(DatabaseLogEvent Severity.CRITICAL): type=RUNTIME_ERROR regex=std::runtime_error line_number=343773 node=Node longevity-tls-1tb-7d-1tb-long-db-node-a956e3a8-9 [54.154.54.186 | 10.0.238.231] (seed: False)
2019-11-01T01:50:37+00:00  ip-10-0-238-231 !INFO    | scylla: [shard 1] repair - repair 21 failed - std::runtime_error (Repair service is being shutdown)
```

**Expected behavior:** sct noticing the repair has started and the nemesis is continued as expected

**Actual behavior:** sct does not realize the repair has started, the nemesis fails while the repair runs

**Comment by ShlomiBalalis** [comment]
This issue is definitely long-irrelavant. Closing.
