### ISSUE TITLE
node_config_setup Failed during restart_with_resharding

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla-cluster-tests#1460]
### Prerequisites

* [x] Are you rebased to master ?
* [ ] Is it reproducible ?
* [ ] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**:branch-3.2
* **scylla**: 3.2

### Logs
* test_id: 0384a9cc-e5d4-4d0a-82e4-0229a27d8fcb
* job log: scratch.scylladb.com/shlomib/21_11_50gb-sct.log

### Description

During restart_with_resharding, the following exception occurred:
```
Traceback (most recent call last):
  File "/sct/sdcm/nemesis.py", line 1193, in wrapper
    result = method(*args, **kwargs)
  File "/sct/sdcm/nemesis.py", line 1408, in disrupt
    self.call_random_disrupt_method()
  File "/sct/sdcm/nemesis.py", line 614, in call_random_disrupt_method
    disrupt_method()
  File "/sct/sdcm/nemesis.py", line 277, in disrupt_restart_with_resharding
    murmur3_partitioner_ignore_msb_bits=murmur3_partitioner_ignore_msb_bits)
  File "/sct/sdcm/cluster.py", line 2105, in restart_node_with_resharding
    node=self, murmur3_partitioner_ignore_msb_bits=murmur3_partitioner_ignore_msb_bits)
  File "/sct/sdcm/cluster_aws.py", line 830, in node_config_setup
    node.config_setup(**setup_params)
  File "/sct/sdcm/cluster.py", line 1513, in config_setup
    self.config_client_encrypt()
  File "/sct/sdcm/cluster.py", line 1594, in config_client_encrypt
    self.remoter.run('bash -cxe "%s"' % setup_script)
  File "/sct/sdcm/remote.py", line 239, in run
    result = _run()
  File "/sct/sdcm/utils/common.py", line 88, in inner
    return func(*args, **kwargs)
  File "/sct/sdcm/remote.py", line 230, in _run
    watchers=watchers, timeout=timeout)
  File "", line 2, in run
  File "/usr/lib/python2.7/site-packages/fabric/connection.py", line 30, in opens
    return method(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/fabric/connection.py", line 721, in run
    return self._run(self._remote_runner(), command, **kwargs)
  File "/usr/lib/python2.7/site-packages/invoke/context.py", line 101, in _run
    return runner.run(command, **kwargs)
  File "/usr/lib/python2.7/site-packages/invoke/runners.py", line 291, in run
    return self._run_body(command, **kwargs)
  File "/usr/lib/python2.7/site-packages/invoke/runners.py", line 442, in _run_body
    raise UnexpectedExit(result)
UnexpectedExit: Encountered a bad command exit code!

Command: 'bash -cxe "\nmkdir -p ~/.cassandra/\ncp /tmp/ssl_conf/client/cqlshrc ~/.cassandra/\nsudo mkdir -p /etc/scylla/\nsudo mv -f /tmp/ssl_conf/ /etc/scylla/\n"'

Exit code: 1

Stdout:



Stderr:

+ mkdir -p /home/centos/.cassandra/
+ cp /tmp/ssl_conf/client/cqlshrc /home/centos/.cassandra/
+ sudo mkdir -p /etc/scylla/
+ sudo mv -f /tmp/ssl_conf/ /etc/scylla/
mv: cannot move ‘/tmp/ssl_conf/’ to ‘/etc/scylla/ssl_conf’: File exists
```

As a result, the node stayed down for the rest of its existence in the run.

**Comment by ShlomiBalalis** [comment]
Seems to be addressed by #1457
