### ISSUE TITLE
row level repair results_analyze fails with: "TypeError: unsupported operand type(s) for +: 'int' and 'list'"

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#1492]
```
 Failed to check regression: unsupported operand type(s) for +: 'int' and 'list' < t:2019-11-26  Failed to check regression: unsupported operand type(s) for +: 'int' and 'list'
 Traceback (most recent call last):
   File "/sct/sdcm/tester.py", line 1656, in check_specified_stats_regression
     perf_analyzer.check_regression(self._test_id, dict_specific_tested_stats=dict_specific_tested_stats, is_gce=is_gce)
   File "/sct/sdcm/results_analyze.py", line 303, in check_regression
     version_avg = sum(list_param_results) / float(len(list_param_results))
 TypeError: unsupported operand type(s) for +: 'int' and 'list'
```

**Comment by yarongilor** [comment]
Not a bug. the elastic search database is corrupted. has a value of list instead of int. it should be deleted.

**Comment by yarongilor** [comment]
the problem is in ES value for 3.0.8 as follows:
```
< t:2019-11-26 10:23:19,865 f:results_analyze.py l:286  c:sdcm.results_analyze p:DEBUG > group_by_version={'2.3.0': {}, '3.0.4': {}, '3.1.0.rc2': {'repair_runtime_large_partitions': [4.94645881652832, 4.557415008544922, 50.87676501274109, 50.969950914382935, 28.92263913154602]}, '3.0.8': {'repair_runtime_large_partitions': [[196.93038606643677, None], 18.907745838165283, 203.330570936203, 195.01774907112122, 196.02140617370605]}, '666.development': {}}
< t:2019-11-26 10:23:19,865 f:results_analyze.py l:299  c:sdcm.results_analyze p:INFO  > Performance result for: repair_runtime_large_partitions is: 50.586652755737305. (average statistics deviation limit is: 33.66557493209839
< t:2019-11-26 10:23:19,866 f:results_analyze.py l:305  c:sdcm.results_analyze p:INFO  > Performance average of 5 results for: repair_runtime_large_partitions on version: 3.1.0.rc2 is: 28.054645776748657
< t:2019-11-26 10:23:19,866 f:tester.py       l:1658 c:sdcm.tester          p:ERROR > Failed to check regression: unsupported operand type(s) for +: 'int' and 'list' < t:2019-11-26 10:23:19,866 f:tester.py       l:1658 c:sdcm.tester          p:ERROR > Failed to check regression: unsupported operand type(s) for +: 'int' and 'list'
< t:2019-11-26 10:23:19,866 f:tester.py       l:1658 c:sdcm.tester          p:ERROR > Traceback (most recent call last):
< t:2019-11-26 10:23:19,866 f:tester.py       l:1658 c:sdcm.tester          p:ERROR >   File "/sct/sdcm/tester.py", line 1656, in check_specified_stats_regression
< t:2019-11-26 10:23:19,866 f:tester.py       l:1658 c:sdcm.tester          p:ERROR >     perf_analyzer.check_regression(self._test_id, dict_specific_tested_stats=dict_specific_tested_stats, is_gce=is_gce)
< t:2019-11-26 10:23:19,866 f:tester.py       l:1658 c:sdcm.tester          p:ERROR >   File "/sct/sdcm/results_analyze.py", line 303, in check_regression
< t:2019-11-26 10:23:19,866 f:tester.py       l:1658 c:sdcm.tester          p:ERROR >     version_avg = sum(list_param_results) / float(len(list_param_results))
< t:2019-11-26 10:23:19,866 f:tester.py       l:1658 c:sdcm.tester          p:ERROR > TypeError: unsupported operand type(s) for +: 'int' and 'list'
```
