### ISSUE TITLE
Nemesis: CorruptThenRepair raise exception during file matching.

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla-cluster-tests#1504]
### Prerequisites

* [x] Are you rebased to master ?
* [ ] Is it reproducible ?
* [ ] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master
* **scylla**: master

### Logs
* test_id: fbc53df6-41c0-4757-85ca-ce23dad38d37
* job log: https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-100gb-4h/50/
* db-nodes: https://cloudius-jenkins-test.s3.amazonaws.com/fbc53df6-41c0-4757-85ca-ce23dad38d37/20191204_020256/sct-runner-fbc53df6.zip
* sct log: https://cloudius-jenkins-test.s3.amazonaws.com/fbc53df6-41c0-4757-85ca-ce23dad38d37/20191204_020256/sct-runner-fbc53df6.zip

### Description

Looks, like wrong filtering of files. We need to update regexp for matching files by
            file_name_template = re.search(r"(.*-\d+)-", file_name).group(1)
            file_for_destroy = one_file.replace(file_name, file_name_template + '-*')
            self.log.debug('Selected files for destroy: {}'.format(file_for_destroy))

logs:
```
< t:2019-12-04 01:31:41,960 f:nemesis.py      l:615  c:sdcm.nemesis         p:ERROR > sdcm.nemesis.ChaosMonkey: ('Exception in random_disrupt_method %s: %s', 'destroy_data_then_repair', AttributeError("'NoneType' object has no attribute 'group'",))
< t:2019-12-04 01:31:41,960 f:nemesis.py      l:1179 c:sdcm.nemesis         p:ERROR > sdcm.nemesis.ChaosMonkey: Unhandled exception in method <function ChaosMonkey.disrupt at 0x7fdb180b3598> < t:2019-12-04 01:31:41,960 f:nemesis.py      l:1179 c:sdcm.nemesis         p:ERROR > sdcm.nemesis.ChaosMonkey: Unhandled exception in method <function ChaosMonkey.disrupt at 0x7fdb180b3598>
< t:2019-12-04 01:31:41,960 f:nemesis.py      l:1179 c:sdcm.nemesis         p:ERROR > Traceback (most recent call last):
< t:2019-12-04 01:31:41,960 f:nemesis.py      l:1179 c:sdcm.nemesis         p:ERROR >   File "/sct/sdcm/nemesis.py", line 1169, in wrapper
< t:2019-12-04 01:31:41,960 f:nemesis.py      l:1179 c:sdcm.nemesis         p:ERROR >     result = method(*args, **kwargs)
< t:2019-12-04 01:31:41,960 f:nemesis.py      l:1179 c:sdcm.nemesis         p:ERROR >   File "/sct/sdcm/nemesis.py", line 1384, in disrupt
< t:2019-12-04 01:31:41,960 f:nemesis.py      l:1179 c:sdcm.nemesis         p:ERROR >     self.call_random_disrupt_method()
< t:2019-12-04 01:31:41,960 f:nemesis.py      l:1179 c:sdcm.nemesis         p:ERROR >   File "/sct/sdcm/nemesis.py", line 612, in call_random_disrupt_method
< t:2019-12-04 01:31:41,960 f:nemesis.py      l:1179 c:sdcm.nemesis         p:ERROR >     disrupt_method()
< t:2019-12-04 01:31:41,960 f:nemesis.py      l:1179 c:sdcm.nemesis         p:ERROR >   File "/sct/sdcm/nemesis.py", line 365, in disrupt_destroy_data_then_repair
< t:2019-12-04 01:31:41,960 f:nemesis.py      l:1179 c:sdcm.nemesis         p:ERROR >     self._destroy_data_and_restart_scylla()
< t:2019-12-04 01:31:41,960 f:nemesis.py      l:1179 c:sdcm.nemesis         p:ERROR >   File "/sct/sdcm/nemesis.py", line 332, in _destroy_data_and_restart_scylla
< t:2019-12-04 01:31:41,960 f:nemesis.py      l:1179 c:sdcm.nemesis         p:ERROR >     file_for_destroy = self._choose_file_for_destroy(ks_cfs)
< t:2019-12-04 01:31:41,960 f:nemesis.py      l:1179 c:sdcm.nemesis         p:ERROR >   File "/sct/sdcm/utils/common.py", line 94, in inner
< t:2019-12-04 01:31:41,960 f:nemesis.py      l:1179 c:sdcm.nemesis         p:ERROR >     return func(*args, **kwargs)
< t:2019-12-04 01:31:41,960 f:nemesis.py      l:1179 c:sdcm.nemesis         p:ERROR >   File "/sct/sdcm/nemesis.py", line 307, in _choose_file_for_destroy
< t:2019-12-04 01:31:41,960 f:nemesis.py      l:1179 c:sdcm.nemesis         p:ERROR >     file_name_template = re.search(r"(.*-\d+)-", file_name).group(1)
< t:2019-12-04 01:31:41,960 f:nemesis.py      l:1179 c:sdcm.nemesis         p:ERROR > AttributeError: 'NoneType' object has no attribute 'group'
< t:2019-12-04 01:31:41,961 f:nemesis.py      l:1191 c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: CorruptThenRepair Node longevity-100gb-4h-master-db-node-fbc53df6-2 [54.175.161.114 | 172.30.0.220] (seed: False) duration -> 79 s
```

**Comment by juliayakovlev** [comment]
PR: https://github.com/scylladb/scylla-cluster-tests/pull/1509
