### ISSUE TITLE
ToggleTableICS nemesis should check first if ICS is available

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#1522]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master
* **scylla**: master

### Logs
* test_id: 8f746fbd-e691-4676-a9d5-2b86d820fda7
* job log: https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-100gb-4h/61/

### Description
ToggleTableICS nemesis should check first if ICS is available, otherwise it is failing like this:

```
2019-12-07 11:56:19.502: (DisruptionEvent Severity.ERROR): type=end name=ToggleTableICS node=Node longevity-100gb-4h-master-db-node-8f746fbd-4 [54.235.224.36 | 172.30.0.237] (seed: False) duration=7 error=Encountered a bad command exit code!
Command: 'cqlsh --no-color   --request-timeout=120 --connect-timeout=5  -e "ALTER TABLE keyspace1.standard1 WITH compaction = {\'class\': \'IncrementalCompactionStrategy\', \'bucket_high\': 1.32, \'bucket_low\': 0.76, \'min_sstable_size\': 170, \'min_threshold\': 9, \'max_threshold\': 49, \'sstable_size_in_mb\': 322};" 172.30.0.237 9042'
Exit code: 2
Stdout:
Stderr:
<stdin>:1:ConfigurationException: Unable to find compaction strategy class 'IncrementalCompactionStrategy'
Traceback (most recent call last):
  File "/sct/sdcm/nemesis.py", line 1203, in wrapper
    result = method(*args, **kwargs)
  File "/sct/sdcm/nemesis.py", line 1418, in disrupt
    self.call_random_disrupt_method()
  File "/sct/sdcm/nemesis.py", line 613, in call_random_disrupt_method
    disrupt_method()
  File "/sct/sdcm/nemesis.py", line 859, in disrupt_toggle_table_ics
    self.toggle_table_ics()
  File "/sct/sdcm/nemesis.py", line 743, in toggle_table_ics
    self.target_node.run_cqlsh(cmd)
  File "/sct/sdcm/cluster.py", line 2284, in run_cqlsh
    verbose=verbose)
  File "/sct/sdcm/remote.py", line 254, in run
    result = _run()
  File "/sct/sdcm/utils/common.py", line 89, in inner
    return func(*args, **kwargs)
  File "/sct/sdcm/remote.py", line 241, in _run
    watchers=watchers, timeout=timeout)
  File "<decorator-gen-3>", line 2, in run
  File "/usr/local/lib/python3.6/site-packages/fabric/connection.py", line 30, in opens
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/fabric/connection.py", line 721, in run
    return self._run(self._remote_runner(), command, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/invoke/context.py", line 101, in _run
    return runner.run(command, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/invoke/runners.py", line 291, in run
    return self._run_body(command, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/invoke/runners.py", line 442, in _run_body
    raise UnexpectedExit(result)
invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!
Command: 'cqlsh --no-color   --request-timeout=120 --connect-timeout=5  -e "ALTER TABLE keyspace1.standard1 WITH compaction = {\'class\': \'IncrementalCompactionStrategy\', \'bucket_high\': 1.32, \'bucket_low\': 0.76, \'min_sstable_size\': 170, \'min_threshold\': 9, \'max_threshold\': 49, \'sstable_size_in_mb\': 322};" 172.30.0.237 9042'
Exit code: 2
Stdout:
Stderr:
<stdin>:1:ConfigurationException: Unable to find compaction strategy class 'IncrementalCompactionStrategy'
```

**Comment by yarongilor** [comment]
fix in:  https://github.com/scylladb/scylla-cluster-tests/pull/1523
