### ISSUE TITLE
Jobs Failed for master branch due to error:  kwargs["auth_token"] 

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla-cluster-tests#1546]
### Prerequisites

* [x] Are you rebased to master ?
* [ ] Is it reproducible ?
* [ ] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master
* **scylla**: master

### Logs
* test_id: 8f57e33b-c6c5-4047-9104-de9996761e0b, a75e6bec-dbe4-4b38-9900-f44cdbe7e35b
* job log: [e.x. https://cloudius-jenkins-test.s3.amazonaws.com/5a2c3b72-40f8-4992-8b5a-5c4aec8bf0c6/job-2019-05-14T09.59-c85338a.zip]
jobs links: https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-10gb-3h/34/consoleFull
https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-100gb-4h/69/consoleFull
### Description

```
172.30.0.193] (seed: False): Detected Linux distribution: CENTOS7
09:51:42  < t:2019-12-12 02:51:42,267 f:cluster.py      l:2515 c:sdcm.cluster         p:ERROR > Cluster longevity-100gb-4h-master-monitor-set-8f57e33b (AMI: ['ami-02eac2c0129f6376b'] Type: t3.large): Node setup failed: Node longevity-100gb-4h-master-monitor-node-8f57e33b-1 [35.174.107.116 | 172.30.0.193] (seed: False) < t:2019-12-12 02:51:42,267 f:cluster.py      l:2515 c:sdcm.cluster         p:ERROR > Cluster longevity-100gb-4h-master-monitor-set-8f57e33b (AMI: ['ami-02eac2c0129f6376b'] Type: t3.large): Node setup failed: Node longevity-100gb-4h-master-monitor-node-8f57e33b-1 [35.174.107.116 | 172.30.0.193] (seed: False)
09:51:42  < t:2019-12-12 02:51:42,267 f:cluster.py      l:2515 c:sdcm.cluster         p:ERROR > Traceback (most recent call last):
09:51:42  < t:2019-12-12 02:51:42,267 f:cluster.py      l:2515 c:sdcm.cluster         p:ERROR >   File "/sct/sdcm/cluster.py", line 2513, in node_setup
09:51:42  < t:2019-12-12 02:51:42,267 f:cluster.py      l:2515 c:sdcm.cluster         p:ERROR >     cl_inst.node_setup(node, **setup_kwargs)
09:51:42  < t:2019-12-12 02:51:42,267 f:cluster.py      l:2515 c:sdcm.cluster         p:ERROR >   File "/sct/sdcm/cluster.py", line 3504, in node_setup
09:51:42  < t:2019-12-12 02:51:42,267 f:cluster.py      l:2515 c:sdcm.cluster         p:ERROR >     self.mgmt_auth_token = kwargs["auth_token"]  # pylint: disable=attribute-defined-outside-init
09:51:42  < t:2019-12-12 02:51:42,267 f:cluster.py      l:2515 c:sdcm.cluster         p:ERROR > KeyError: 'auth_token'
09:52:07  < t:2019-12-12 02:52:05,822 f:tester.py       l:129  c:sdcm.tester          p:ERROR > Exception in setUp. Will call tearDown < t:2019-12-12 02:52:05,822 f:tester.py       l:129  c:sdcm.tester          p:ERROR > Exception in setUp. Will call tearDown
09:52:07  < t:2019-12-12 02:52:05,822 f:tester.py       l:129  c:sdcm.tester          p:ERROR > Traceback (most recent call last):
09:52:07  < t:2019-12-12 02:52:05,822 f:tester.py       l:129  c:sdcm.tester          p:ERROR >   File "/sct/sdcm/tester.py", line 127, in wrapper
09:52:07  < t:2019-12-12 02:52:05,822 f:tester.py       l:129  c:sdcm.tester          p:ERROR >     return method(*args, **kwargs)
09:52:07  < t:2019-12-12 02:52:05,822 f:tester.py       l:129  c:sdcm.tester          p:ERROR >   File "/sct/sdcm/utils/common.py", line 136, in inner
09:52:07  < t:2019-12-12 02:52:05,822 f:tester.py       l:129  c:sdcm.tester          p:ERROR >     res = func(*args, **kwargs)
09:52:07  < t:2019-12-12 02:52:05,822 f:tester.py       l:129  c:sdcm.tester          p:ERROR >   File "/sct/sdcm/tester.py", line 275, in setUp
09:52:07  < t:2019-12-12 02:52:05,822 f:tester.py       l:129  c:sdcm.tester          p:ERROR >     self.monitors.wait_for_init()
09:52:07  < t:2019-12-12 02:52:05,822 f:tester.py       l:129  c:sdcm.tester          p:ERROR >   File "/sct/sdcm/cluster.py", line 2536, in wrapper
09:52:07  < t:2019-12-12 02:52:05,822 f:tester.py       l:129  c:sdcm.tester          p:ERROR >     raise NodeSetupFailed(f"{node}:{node_status}")
09:52:07  < t:2019-12-12 02:52:05,822 f:tester.py       l:129  c:sdcm.tester          p:ERROR > sdcm.cluster.NodeSetupFailed: Node longevity-100gb-4h-master-monitor-node-8f57e33b-1 [35.174.107.116 | 172.30.0.193] (seed: False):False
```
### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by aleksbykov** [comment]
Looks like it is related to this commit 6db74ebc2bf2962021f9a6654e0e13ece21ce669
