### ISSUE TITLE
manager tests are failing (at least 5 jobs) with No db log from node

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylla-cluster-tests#1575]
my jobs are running with multi DC
it is using a spot_low_price

```
16:20:23  ======================================================================
16:20:23  ERROR: test_backup_feature (mgmt_cli_test.MgmtCliTest)
16:20:23  ----------------------------------------------------------------------
16:20:23  Traceback (most recent call last):
16:20:23    File "/sct/sdcm/tester.py", line 127, in wrapper
16:20:23      return method(*args, **kwargs)
16:20:23    File "/sct/sdcm/utils/common.py", line 136, in inner
16:20:23      res = func(*args, **kwargs)
16:20:23    File "/sct/sdcm/tester.py", line 253, in setUp
16:20:23      self.init_nodes(db_cluster=self.db_cluster)
16:20:23    File "/sct/sdcm/tester.py", line 229, in init_nodes
16:20:23      db_cluster.wait_for_init(node_list=db_cluster.non_seed_nodes)
16:20:23    File "/sct/sdcm/cluster.py", line 2555, in wrapper
16:20:23      method(*args, **kwargs)
16:20:23    File "/sct/sdcm/cluster.py", line 3054, in wait_for_init
16:20:23      text="wait for db logs", step=20, timeout=300, throw_exc=True)
16:20:23    File "/sct/sdcm/wait.py", line 60, in wait_for
16:20:23      res = retry.call(func, **kwargs)
16:20:23    File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 358, in call
16:20:23      do = self.iter(retry_state=retry_state)
16:20:23    File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 331, in iter
16:20:23      raise retry_exc.reraise()
16:20:23    File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 167, in reraise
16:20:23      raise self.last_attempt.result()
16:20:23    File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 425, in result
16:20:23      return self.__get_result()
16:20:23    File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 384, in __get_result
16:20:23      raise self._exception
16:20:23    File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 361, in call
16:20:23      result = fn(*args, **kwargs)
16:20:23    File "/sct/sdcm/cluster.py", line 3036, in verify_logging_from_nodes
16:20:23      raise Exception(error_msg)
16:20:23  Exception: No db log from node [Node manager-regression-master-db-node-2933a2b4-2 [52.87.187.119 | 172.30.0.64] (seed: False)] 
```

**Comment by fgelcer** [comment]
at least 5 jobs running in parallel with latest master are failing with the same issue.
when i moved to use on_demand, then it passed this setup phase

**Comment by fgelcer** [comment]
few of the logs:
```
15:57:58  +--------------------------------------------------------------------------------------------------------------------------------------------+
15:57:58  |           Collected logs by test-id: 94d15252-e10f-413c-9d85-63b8094479c2 Directory: /sct/20191217-134305-008866/collected_logs            |
15:57:58  +-------------+------------------------------------------------------------------------------------------------------------------------------+
15:57:58  | Cluster set | Link                                                                                                                         |
15:57:58  +-------------+------------------------------------------------------------------------------------------------------------------------------+
15:57:58  | db-cluster  | https://cloudius-jenkins-test.s3.amazonaws.com/94d15252-e10f-413c-9d85-63b8094479c2/20191217_135523/db-cluster-94d15252.zip  |
15:57:58  | monitor-set | https://cloudius-jenkins-test.s3.amazonaws.com/94d15252-e10f-413c-9d85-63b8094479c2/20191217_135523/monitor-set-94d15252.zip |
15:57:58  | loader-set  | https://cloudius-jenkins-test.s3.amazonaws.com/94d15252-e10f-413c-9d85-63b8094479c2/20191217_135523/loader-set-94d15252.zip  |
15:57:58  | sct-runner  | https://cloudius-jenkins-test.s3.amazonaws.com/94d15252-e10f-413c-9d85-63b8094479c2/20191217_135523/sct-runner-94d15252.zip  |
15:57:58  +-------------+------------------------------------------------------------------------------------------------------------------------------+
```

```
16:24:25  +--------------------------------------------------------------------------------------------------------------------------------------------+
16:24:25  |           Collected logs by test-id: 88d67497-8884-4d13-90ac-77e62adaaaf2 Directory: /sct/20191217-140659-466117/collected_logs            |
16:24:25  +-------------+------------------------------------------------------------------------------------------------------------------------------+
16:24:25  | Cluster set | Link                                                                                                                         |
16:24:25  +-------------+------------------------------------------------------------------------------------------------------------------------------+
16:24:25  | db-cluster  | https://cloudius-jenkins-test.s3.amazonaws.com/88d67497-8884-4d13-90ac-77e62adaaaf2/20191217_142149/db-cluster-88d67497.zip  |
16:24:25  | monitor-set | https://cloudius-jenkins-test.s3.amazonaws.com/88d67497-8884-4d13-90ac-77e62adaaaf2/20191217_142149/monitor-set-88d67497.zip |
16:24:25  | loader-set  | https://cloudius-jenkins-test.s3.amazonaws.com/88d67497-8884-4d13-90ac-77e62adaaaf2/20191217_142149/loader-set-88d67497.zip  |
16:24:25  | sct-runner  | https://cloudius-jenkins-test.s3.amazonaws.com/88d67497-8884-4d13-90ac-77e62adaaaf2/20191217_142149/sct-runner-88d67497.zip  |
16:24:25  +-------------+------------------------------------------------------------------------------------------------------------------------------+
```

**Comment by roydahan** [comment]
Did you have spot termination during the test?

**Comment by fgelcer** [comment]
> Did you have spot termination during the test?

No

**Comment by fgelcer** [comment]
it happens now for me with on_demand instances...
it is blocking me to make further progress with manager 2.0 sanity tests

**Comment by roydahan** [comment]
because it's not related to spot or not.
@bentsi can you please look on this?

**Comment by roydahan** [comment]
@bentsi this issue which seems like happening in the manager tests almost always blocks our sanity from being "Blue".

We need to solve it ASAP + we may want to reduce severity of it.
Can you please look at it?

**Comment by bentsi** [comment]
looking into
