### ISSUE TITLE
botocore.exceptions.NoRegionError: You must specify a region.

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla-cluster-tests#1580]
### Prerequisites

* [ ] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: branch-2019.1

### Logs
* test_jobs:

- https://jenkins.scylladb.com/job/scylla-staging/job/amos/job/rolling-upgrade-2019.1/job/rolling-upgrade-centos7/8/execution/node/34/log/
- https://jenkins.scylladb.com/job/scylla-staging/job/amos/job/rolling-upgrade-2019.1/job/rolling-upgrade-centos7/9/execution/node/34/log/

### Description

The job failed for that the builder doesn't have a ~/.aws/config

### Steps to Reproduce

1. submit a upgrade job on gce builder 2

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

```
11:52:52  Traceback (most recent call last):
11:52:52    File "./sct.py", line 12, in <module>
11:52:52      from sdcm.results_analyze import PerformanceResultsAnalyzer
11:52:52    File "/sct/sdcm/results_analyze.py", line 9, in <module>
11:52:52      from sdcm.db_stats import TestStatsMixin
11:52:52    File "/sct/sdcm/db_stats.py", line 18, in <module>
11:52:52      from sdcm.utils.common import get_job_name, retrying, remove_comments
11:52:52    File "/sct/sdcm/utils/common.py", line 328, in <module>
11:52:52      AWS_REGIONS = all_aws_regions()
11:52:52    File "/sct/sdcm/utils/common.py", line 324, in all_aws_regions
11:52:52      client = boto3.client('ec2')
11:52:52    File "/usr/lib/python2.7/site-packages/boto3/__init__.py", line 91, in client
11:52:52      return _get_default_session().client(*args, **kwargs)
11:52:52    File "/usr/lib/python2.7/site-packages/boto3/session.py", line 263, in client
11:52:52      aws_session_token=aws_session_token, config=config)
11:52:52    File "/usr/lib/python2.7/site-packages/botocore/session.py", line 839, in create_client
11:52:52      client_config=config, api_version=api_version)
11:52:52    File "/usr/lib/python2.7/site-packages/botocore/client.py", line 86, in create_client
11:52:52      verify, credentials, scoped_config, client_config, endpoint_bridge)
11:52:52    File "/usr/lib/python2.7/site-packages/botocore/client.py", line 328, in _get_client_args
11:52:52      verify, credentials, scoped_config, client_config, endpoint_bridge)
11:52:52    File "/usr/lib/python2.7/site-packages/botocore/args.py", line 47, in get_client_args
11:52:52      endpoint_url, is_secure, scoped_config)
11:52:52    File "/usr/lib/python2.7/site-packages/botocore/args.py", line 117, in compute_client_args
11:52:52      service_name, region_name, endpoint_url, is_secure)
11:52:52    File "/usr/lib/python2.7/site-packages/botocore/client.py", line 402, in resolve
11:52:52      service_name, region_name)
11:52:52    File "/usr/lib/python2.7/site-packages/botocore/regions.py", line 122, in construct_endpoint
11:52:52      partition, service_name, region_name)
11:52:52    File "/usr/lib/python2.7/site-packages/botocore/regions.py", line 135, in _endpoint_for_partition
11:52:52      raise NoRegionError()
11:52:52  botocore.exceptions.NoRegionError: You must specify a region.
```

**Comment by amoskong** [comment]
The problem can be fixed by manually adding config file on builder2.
We also need to fix the code to use default region in defaults/test_default.yaml

**Comment by fruch** [comment]
We should do both.

**Comment by bentsi** [comment]
no manual things should be done, we should handle this in the code.
