### ISSUE TITLE
ssh_ping_threadException in thread Thread-42 (most likely raised during interpreter shutdown)

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla-cluster-tests#1605]
### Prerequisites

* [ ] Are you rebased to master ?
* [ ] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**:  branch-2019.1
* **scylla**: 2019.1.4

### Logs
* test_id: 0827b95a-c0f1-41fc-9e5c-de74307aa5db
* SCT log: https://cloudius-jenkins-test.s3.amazonaws.com/0827b95a-c0f1-41fc-9e5c-de74307aa5db/20191219_090706/sct-runner-0827b95a.zip
* test job: https://jenkins.scylladb.com/job/enterprise-2019.1/view/enterprise-2019.1-test/job/SCT_Enterprise_Feature/job/ICS/job/ics-longevity-mv-si-4days-test/1/console

### Description

see ssh_ping_threadException in the end of job. Need to know if it's harmless.

### Steps to Reproduce

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

```
17:16:58  Exception in thread Thread-35 (most likely raised during interpreter shutdown):
17:16:58  Traceback (most recent call last):
17:16:58    File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
17:16:58    File "/usr/lib64/python2.7/threading.py", line 765, in run
17:16:58    File "/sct/sdcm/remote.py", line 278, in ssh_ping_thread
17:16:58    File "/usr/lib64/python2.7/threading.py", line 622, in wait
17:16:58    File "/usr/lib64/python2.7/threading.py", line 354, in wait
17:16:58  <type 'exceptions.TypeError'>: 'NoneType' object is not callable
17:16:58  Exception TypeError: "'NoneType' object is not callable" in <bound method RemoteCmdRunner.__del__ of <sdcm.remote.RemoteCmdRunner object at 0x7f4e4056d410>> ignored
17:16:58  Exception in thread Thread-40 (most likely raised during interpreter shutdown):
17:16:58   Exception in thread Thread-34 (most likely raised during interpreter shutdown):
17:16:58  Traceback (most recent call last):
17:16:58    File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
17:16:58    File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 2135, in run
17:16:58  <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'error'
17:16:58  Traceback (most recent call last):
17:16:58    File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
17:16:58    File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 2135, in run
17:16:58  <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'error'
17:16:58  Exception in thread Thread-23 (most likely raised during interpreter shutdown):
17:16:58  Traceback (most recent call last):
17:16:58   Exception in thread Thread-27 (most likely raised during interpreter shutdown):
17:16:58  Traceback (most recent call last):
17:16:58    File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
17:16:58  
17:16:58   Exception in thread Thread-28 (most likely raised during interpreter shutdown):
17:16:58  Traceback (most recent call last):
17:16:58    File "/usr/lib64/python2.7/threading.py", line 765, in run  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner  File "/usr/lib64/python2.7/threading.py", line 765, in run
17:16:58   Exception in thread Thread-39 (most likely raised during interpreter shutdown):
17:16:58  Traceback (most recent call last):
17:16:58    File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
17:16:58    File "/usr/lib64/python2.7/threading.py", line 765, in run
17:16:58    File "/sct/sdcm/remote.py", line 278, in ssh_ping_thread
17:16:58    File "/usr/lib64/python2.7/threading.py", line 622, in waitException in thread Thread-21 (most likely raised during interpreter shutdown):
17:16:58  
17:16:58  Traceback (most recent call last):  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 2135, in run
17:16:58   Exception in thread Thread-33 (most likely raised during interpreter shutdown):
17:16:58  Traceback (most recent call last):
17:16:58    File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
17:16:58     File "/sct/sdcm/remote.py", line 278, in ssh_ping_thread<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'error'  File "/sct/sdcm/remote.py", line 278, in ssh_ping_threadException in thread Thread-42 (most likely raised during interpreter shutdown):
17:16:58  
17:16:58    File "/usr/lib64/python2.7/threading.py", line 622, in wait
17:16:58    File "/usr/lib64/python2.7/threading.py", line 354, in wait
17:16:58  <type 'exceptions.TypeError'>: 'NoneType' object is not callable
17:16:58  
17:16:58  Exception TypeError: "'NoneType' object is Exception in thread Thread-30 (most likely raised during interpreter shutdown):
17:16:58  
17:16:58  
17:16:58  not callable"  File "/usr/lib64/python2.7/threading.py", line 622, in wait in <bound method RemoteCmdRunner.__del__ of <sdcm.remote.RemoteCmdRunner object at 0x7f4e58e732d0>> ignored
```

**Comment by aleksbykov** [comment]
Will take a look. Seems that Remote object  was removed earlier than thread with ssh_ping die

**Comment by bentsi** [comment]
5d5685ea20e85e0255809c96a10330c369b4c8f5 should improve the situation. Let's close and reopen if it happens again
