### ISSUE TITLE
command returned None, making setup to fail

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylla-cluster-tests#1607]
running sanity of mermaid 2.0 (job number 25).

here is the issue:
```
10:20:39  < t:2019-12-24 08:20:29,213 f:ec2_client.py   l:216  c:sdcm.ec2_client      p:INFO  > Waiting for spot instances...
10:20:39  < t:2019-12-24 08:20:34,291 f:ec2_client.py   l:329  c:sdcm.ec2_client      p:INFO  > Spot instances: ['i-0e95c9582fd54bb20']
10:20:50  < t:2019-12-24 08:20:49,894 f:cluster_aws.py  l:464  c:sdcm.cluster         p:INFO  > Node manager-regression-master-monitor-node-22138b24-1 [18.233.224.59 | 172.30.0.199] (seed: False): Changing hostname to manager-regression-master-monitor-node-22138b24-1
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR > Exception in setUp. Will call tearDown < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR > Exception in setUp. Will call tearDown
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR > Traceback (most recent call last):
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR >   File "/sct/sdcm/tester.py", line 126, in wrapper
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR >     return method(*args, **kwargs)
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR >   File "/sct/sdcm/utils/common.py", line 138, in inner
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR >     res = func(*args, **kwargs)
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR >   File "/sct/sdcm/tester.py", line 250, in setUp
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR >     self.init_resources()
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR >   File "/sct/sdcm/tester.py", line 652, in init_resources
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR >     monitor_info=monitor_info)
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR >   File "/sct/sdcm/tester.py", line 581, in get_cluster_aws
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR >     **common_params)
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR >   File "/sct/sdcm/cluster_aws.py", line 1052, in __init__
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR >     node_type=node_type)
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR >   File "/sct/sdcm/cluster_aws.py", line 95, in __init__
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR >     node_type=node_type,
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR >   File "/sct/sdcm/cluster.py", line 2372, in __init__
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR >     self.add_nodes(n_nodes)
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR >   File "/sct/sdcm/cluster_aws.py", line 384, in add_nodes
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR >     enumerate(instances, start=self._node_index + 1)]
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR >   File "/sct/sdcm/cluster_aws.py", line 383, in <listcomp>
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR >     for node_index, instance in
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR >   File "/sct/sdcm/cluster_aws.py", line 398, in _create_node
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR >     base_logdir=base_logdir, dc_idx=dc_idx, node_type=self.node_type)
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR >   File "/sct/sdcm/cluster_aws.py", line 432, in __init__
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR >     dc_idx=dc_idx)
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR >   File "/sct/sdcm/cluster.py", line 385, in __init__
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR >     start_auto_ssh(Setup.test_id(), self, Setup.RSYSLOG_ADDRESS[1], RSYSLOG_SSH_TUNNEL_LOCAL_PORT)
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR >   File "/sct/sdcm/auto_ssh.py", line 39, in start_auto_ssh
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR >     '''.format(host_name=host_name, user_name=user_name, local_port=local_port, remote_port=remote_port, key_path=key_path, docker_name=docker_name))
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR >   File "/sct/sdcm/remote.py", line 155, in run
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR >     env=os.environ, replace_env=True)
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR >   File "/usr/local/lib/python3.6/site-packages/fabric/connection.py", line 748, in local
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR >     return super(Connection, self).run(*args, **kwargs)
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR >   File "/usr/local/lib/python3.6/site-packages/invoke/context.py", line 94, in run
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR >     return self._run(runner, command, **kwargs)
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR >   File "/usr/local/lib/python3.6/site-packages/invoke/context.py", line 101, in _run
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR >     return runner.run(command, **kwargs)
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR >   File "/usr/local/lib/python3.6/site-packages/invoke/runners.py", line 291, in run
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR >     return self._run_body(command, **kwargs)
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR >   File "/usr/local/lib/python3.6/site-packages/invoke/runners.py", line 442, in _run_body
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR >     raise UnexpectedExit(result)
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR > invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR > 
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR > Command: '\n           docker run -d --network=host            -e SSH_HOSTNAME=18.233.224.59            -e SSH_HOSTUSER=centos            -e SSH_TUNNEL_HOST=127.0.0.1            -e SSH_TUNNEL_LOCAL=33154            -e SSH_TUNNEL_REMOTE=5000            -e AUTOSSH_GATETIME=0            -v ~/.ssh/scylla-qa-ec2:/id_rsa             --restart always            --name 22138b24-3de7-42d2-b454-669f2700801b-18.233.224.59-autossh jnovack/autossh\n       '
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR > 
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR > Exit code: None
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR > 
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR > Stdout:
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR > 
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR > dfb0f0f9301501998159594a51326a726eab6b1c3d5c1837eb74ef70fe321e6a
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR > 
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR > Stderr:
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR > 
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR > 
10:22:07  < t:2019-12-24 08:21:59,035 f:tester.py       l:128  c:sdcm.tester          p:ERROR > 
10:22:07  < t:2019-12-24 08:21:59,040 f:tester.py       l:1331 c:sdcm.tester          p:INFO  > TearDown is starting...
10:22:07  < t:2019-12-24 08:21:59,051 f:sct_events.py   l:508  c:sdcm.sct_events      p:INFO  > 2019-12-24 08:21:59.040: (InfoEvent Severity.NORMAL): message=TEST_END
```

```
+-------------------------------------------------------------------------------------------------------------------------------------------+
|           Collected logs by test-id: 22138b24-3de7-42d2-b454-669f2700801b Directory: /sct/20191224-081628-895109/collected_logs           |
+-------------+-----------------------------------------------------------------------------------------------------------------------------+
| Cluster set | Link                                                                                                                        |
+-------------+-----------------------------------------------------------------------------------------------------------------------------+
| db-cluster  | https://cloudius-jenkins-test.s3.amazonaws.com/22138b24-3de7-42d2-b454-669f2700801b/20191224_082216/db-cluster-22138b24.zip |
| monitor-set | None                                                                                                                        |
| loader-set  | https://cloudius-jenkins-test.s3.amazonaws.com/22138b24-3de7-42d2-b454-669f2700801b/20191224_082216/loader-set-22138b24.zip |
| sct-runner  | https://cloudius-jenkins-test.s3.amazonaws.com/22138b24-3de7-42d2-b454-669f2700801b/20191224_082216/sct-runner-22138b24.zip |
+-------------+-----------------------------------------------------------------------------------------------------------------------------+
```

**Comment by fgelcer** [comment]
running on SCT master
