### ISSUE TITLE
disrupt_mgmt_repair_cli fails with: "IndexError: list index out of range"

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#1609]
### Prerequisites

* [ ] Are you rebased to master ?
* [ ] Is it reproducible ?
* [ ] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: [branch or hash tag you are working on]
* **scylla**: [branch or commit hash]

### Logs
* test_id: [look for 'the Test ID' at the end of the log]
* job log: [e.x. https://cloudius-jenkins-test.s3.amazonaws.com/5a2c3b72-40f8-4992-8b5a-5c4aec8bf0c6/job-2019-05-14T09.59-c85338a.zip]

### Description

```
< t:2019-12-22 20:20:10,353 f:nemesis.py      l:1127 c:sdcm.nemesis         p:ERROR > sdcm.nemesis.ChaosMonkey: Unhandled exception in method <function disrupt at 0x7faf1491c9b0> < t:2019-12-22 20:20:10,353 f:nemesis.py      l:1127
 c:sdcm.nemesis         p:ERROR > sdcm.nemesis.ChaosMonkey: Unhandled exception in method <function disrupt at 0x7faf1491c9b0>
< t:2019-12-22 20:20:10,353 f:nemesis.py      l:1127 c:sdcm.nemesis         p:ERROR > Traceback (most recent call last):
< t:2019-12-22 20:20:10,353 f:nemesis.py      l:1127 c:sdcm.nemesis         p:ERROR >   File "/sct/sdcm/nemesis.py", line 1117, in wrapper
< t:2019-12-22 20:20:10,353 f:nemesis.py      l:1127 c:sdcm.nemesis         p:ERROR >     result = method(*args, **kwargs)
< t:2019-12-22 20:20:10,353 f:nemesis.py      l:1127 c:sdcm.nemesis         p:ERROR >   File "/sct/sdcm/nemesis.py", line 1332, in disrupt
< t:2019-12-22 20:20:10,353 f:nemesis.py      l:1127 c:sdcm.nemesis         p:ERROR >     self.call_random_disrupt_method()
< t:2019-12-22 20:20:10,353 f:nemesis.py      l:1127 c:sdcm.nemesis         p:ERROR >   File "/sct/sdcm/nemesis.py", line 624, in call_random_disrupt_method
< t:2019-12-22 20:20:10,353 f:nemesis.py      l:1127 c:sdcm.nemesis         p:ERROR >     disrupt_method()
< t:2019-12-22 20:20:10,353 f:nemesis.py      l:1127 c:sdcm.nemesis         p:ERROR >   File "/sct/sdcm/nemesis.py", line 900, in disrupt_mgmt_repair_cli
< t:2019-12-22 20:20:10,353 f:nemesis.py      l:1127 c:sdcm.nemesis         p:ERROR >     mgr_cluster = manager_tool.add_cluster(name=cluster_name, host=targets[0], disable_automatic_repair=True)
< t:2019-12-22 20:20:10,353 f:nemesis.py      l:1127 c:sdcm.nemesis         p:ERROR >   File "/sct/sdcm/mgmt.py", line 656, in add_cluster
< t:2019-12-22 20:20:10,353 f:nemesis.py      l:1127 c:sdcm.nemesis         p:ERROR >     manager_cluster.delete_automatic_repair_task()
< t:2019-12-22 20:20:10,353 f:nemesis.py      l:1127 c:sdcm.nemesis         p:ERROR >   File "/sct/sdcm/mgmt.py", line 360, in delete_automatic_repair_task
< t:2019-12-22 20:20:10,353 f:nemesis.py      l:1127 c:sdcm.nemesis         p:ERROR >     repair_task = self.repair_task_list[0]
< t:2019-12-22 20:20:10,353 f:nemesis.py      l:1127 c:sdcm.nemesis         p:ERROR > IndexError: list index out of range
```

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by ShlomiBalalis** [comment]
Solved by #1610
