### ISSUE TITLE
Upgrade pipeline doesn't have email_recipients parameter, but try to use it.

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla-cluster-tests#1634]
### Prerequisites

* [ ] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: branch-2019.1

Related jobs: https://jenkins.scylladb.com/job/enterprise-2019.1/job/rolling-upgrade/job/rolling-upgrade-centos7/build?delay=0sec

### Logs
test_id: da5ad52e-43d0-4b8c-a2d0-59d34957e7b6
job: https://jenkins.scylladb.com/job/scylla-staging/job/amos/job/rolling-upgrade-2019.1/job/rolling-upgrade-debian9/4/console

### Description

Upgrade pipeline doesn't have email_recipients parameter, but try to use it.

### Steps to Reproduce

1. run upgrade test job

**Expected behavior:** [What you expected to happen]
Have a parameter to assign the email address

**Actual behavior:** [What actually happened]

Job pipeline steps are all good, but the  job failed for sending email.

- https://jenkins.scylladb.com/job/scylla-staging/job/amos/job/rolling-upgrade-2019.1/job/rolling-upgrade-debian9/4/flowGraphTable/

```
20:43:37  groovy.lang.MissingPropertyException: No such property: email_recipients for class: rollingUpgradePipeline
20:43:37  	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
20:43:37  	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.getProperty(ScriptBytecodeAdapter.java:458)
20:43:37  	at org.kohsuke.groovy.sandbox.impl.Checker$6.call(Checker.java:293)
20:43:37  	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onGetProperty(GroovyInterceptor.java:68)
20:43:37  	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onGetProperty(SandboxInterceptor.java:354)
20:43:37  	at org.kohsuke.groovy.sandbox.impl.Checker$6.call(Checker.java:291)
20:43:37  	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:295)
20:43:37  	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:271)
20:43:37  	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:271)
20:43:37  	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:271)
20:43:37  	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:271)
20:43:37  	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:271)
20:43:37  	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:271)
20:43:37  	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:271)
20:43:37  	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:271)
20:43:37  	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:271)
20:43:37  	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:271)
20:43:37  	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.getProperty(SandboxInvoker.java:29)
20:43:37  	at com.cloudbees.groovy.cps.impl.PropertyAccessBlock.rawGet(PropertyAccessBlock.java:20)
20:43:37  	at rollingUpgradePipeline.call(rollingUpgradePipeline.groovy:150)
20:43:37  	at ___cps.transform___(Native Method)
20:43:37  	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.get(PropertyishBlock.java:74)
20:43:37  	at com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)
20:43:37  	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.fixName(PropertyishBlock.java:66)
20:43:37  	at sun.reflect.GeneratedMethodAccessor558.invoke(Unknown Source)
20:43:37  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:43:37  	at java.lang.reflect.Method.invoke(Method.java:498)
20:43:37  	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
20:43:37  	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
20:43:37  	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
20:43:37  	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
20:43:37  	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
20:43:37  	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
20:43:37  	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
20:43:37  	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
20:43:37  	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
20:43:37  	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
20:43:37  	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:185)
20:43:37  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:405)
20:43:37  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$400(CpsThreadGroup.java:96)
20:43:37  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:317)
20:43:37  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:281)
20:43:37  	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
20:43:37  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
20:43:37  	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
20:43:37  	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
20:43:37  	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
20:43:37  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
20:43:37  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
20:43:37  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
20:43:37  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
20:43:37  	at java.lang.Thread.run(Thread.java:748)
```

**Comment by aleksbykov** [comment]
@amoskong this PR https://github.com/scylladb/scylla-cluster-tests/pull/1636 should fix the issue. For some reasons the pipeline doesn't have definition of email_recipients parameter. May be during some merges it was lost

**Comment by amoskong** [comment]
Thanks, I will close this issue if it won't happen

**Comment by amoskong** [comment]
This problem also exists with sct branch-3.2
- https://jenkins.scylladb.com/job/scylla-3.2/job/rolling-upgrade/job/rolling-upgrade-centos7/63/
