### ISSUE TITLE
Grafana not installed correctly

### ISSUE THREAD

**Issue by noamha** [scylladb/scylla-cluster-tests#164]
Hi,

2 out of 4 tests I ran were not able to start Grafana correctly.
Prometheus was installed correctly and worked.

Here is the relevant log file:

```
2016-08-08 10:38:21,450 remote           L0832 DEBUG| Remote [centos@54.175.131.251]: Running 'sudo grafana-cli plugins install grafana-piechart-panel'
2016-08-08 10:38:21,450 remote           L0094 INFO | [54.175.131.251] Running '/bin/ssh -a -x  -o ControlPath=/var/tmp/ssh-masterfWVukH/socket -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmp_3gDSy -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l centos -p 22 -i /var/tmp/vagrant-longevity-test-8db5c1d9.pem 54.175.131.251 "sudo grafana-cli plugins install grafana-piechart-panel"'
2016-08-08 10:38:25,400 remote           L0194 DEBUG| [54.175.131.251] [stdout] installing grafana-piechart-panel @ 1.1.1
2016-08-08 10:38:25,401 remote           L0194 DEBUG| [54.175.131.251] [stdout] from url: https://grafana.net/api/plugins/grafana-piechart-panel/versions/1.1.1/download
2016-08-08 10:38:25,401 remote           L0194 DEBUG| [54.175.131.251] [stdout] into: /var/lib/grafana/plugins
2016-08-08 10:38:25,401 remote           L0194 DEBUG| [54.175.131.251] [stdout]
2016-08-08 10:38:28,968 remote           L0194 DEBUG| [54.175.131.251] [stdout]
2016-08-08 10:38:28,968 remote           L0194 DEBUG| [54.175.131.251] [stdout] Error: zip: not a valid zip file
2016-08-08 10:38:28,969 remote           L0194 DEBUG| [54.175.131.251] [stdout]
2016-08-08 10:38:28,969 remote           L0194 DEBUG| [54.175.131.251] [stdout] NAME:
2016-08-08 10:38:28,969 remote           L0194 DEBUG| [54.175.131.251] [stdout]    Grafana cli plugins install - install <plugin id>
2016-08-08 10:38:28,969 remote           L0194 DEBUG| [54.175.131.251] [stdout]
2016-08-08 10:38:28,969 remote           L0194 DEBUG| [54.175.131.251] [stdout] USAGE:
2016-08-08 10:38:28,970 remote           L0194 DEBUG| [54.175.131.251] [stdout]    Grafana cli plugins install [arguments...]
2016-08-08 10:38:29,205 output           L0632 DEBUG| Exception in thread Thread-27:
2016-08-08 10:38:29,205 output           L0632 DEBUG| Traceback (most recent call last):
2016-08-08 10:38:29,205 output           L0632 DEBUG|   File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
2016-08-08 10:38:29,206 output           L0632 DEBUG|     self.run()
2016-08-08 10:38:29,206 output           L0632 DEBUG|   File "/usr/lib64/python2.7/threading.py", line 764, in run
2016-08-08 10:38:29,206 output           L0632 DEBUG|     self.__target(*self.__args, **self.__kwargs)
2016-08-08 10:38:29,206 output           L0632 DEBUG|   File "/home/vagrant/scylla-cluster-tests/sdcm/cluster.py", line 1303, in node_setup
2016-08-08 10:38:29,206 output           L0632 DEBUG|     node.install_grafana()
2016-08-08 10:38:29,207 output           L0632 DEBUG|   File "/home/vagrant/scylla-cluster-tests/sdcm/cluster.py", line 277, in install_grafana
2016-08-08 10:38:29,208 output           L0632 DEBUG|     self.remoter.run('sudo grafana-cli plugins install grafana-piechart-panel')
2016-08-08 10:38:29,209 output           L0632 DEBUG|   File "/home/vagrant/scylla-cluster-tests/sdcm/remote.py", line 843, in run
2016-08-08 10:38:29,209 output           L0632 DEBUG|     watch_stdout_pattern=watch_stdout_pattern)
2016-08-08 10:38:29,210 output           L0632 DEBUG|   File "/home/vagrant/scylla-cluster-tests/sdcm/remote.py", line 808, in _run
2016-08-08 10:38:29,210 output           L0632 DEBUG|     watch_stdout_pattern=watch_stdout_pattern)
2016-08-08 10:38:29,211 output           L0632 DEBUG|   File "/home/vagrant/scylla-cluster-tests/sdcm/remote.py", line 215, in ssh_run
2016-08-08 10:38:29,211 output           L0632 DEBUG|     raise process.CmdError(cmd, sp.result)
2016-08-08 10:38:29,212 output           L0632 DEBUG| CmdError: Command '/bin/ssh -a -x  -o ControlPath=/var/tmp/ssh-masterfWVukH/socket -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmp_3gDSy -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l centos -p 22 -i /var/tmp/vagrant-longevity-test-8db5c1d9.pem 54.175.131.251 "sudo grafana-cli plugins install grafana-piechart-panel"' failed (rc=1)
2016-08-08 10:38:29,245 output           L0632 DEBUG|
2016-08-08 10:42:49,957 remote           L0194 DEBUG| [54.175.131.251] [stderr] time="2016-08-08T10:42:48Z" level=info msg="Checkpointing in-memory metrics and chunks..." source="persistence.go:539"
2016-08-08 10:42:51,900 remote           L0194 DEBUG| [54.175.131.251] [stderr] time="2016-08-08T10:42:50Z" level=info msg="Done checkpointing in-memory metrics and chunks in 1.924280976s." source="persistence.go:563"
2016-08-08 10:47:51,857 remote           L0194 DEBUG| [54.175.131.251] [stderr] time="2016-08-08T10:47:50Z" level=info msg="Checkpointing in-memory metrics and chunks..." source="persistence.go:539"
2016-08-08 10:47:53,285 remote           L0194 DEBUG| [54.175.131.251] [stderr] time="2016-08-08T10:47:51Z" level=info msg="Done checkpointing in-memory metrics and chunks in 1.221837148s." source="persistence.go:563"
```

I used the following commt:

```
commit ceb34c99a0550a9854fdf6005db680a94f6f4e1a
Merge: 0afe46e eafb16f
Author: Lucas Meneghel Rodrigues <lmr@scylladb.com>
Date:   Thu Aug 4 06:34:25 2016 -0300

    Merge pull request #163 from kongove/libvirt_uri

    sdcm: replace fixed Libvirt uri
```

**Comment by lmr** [comment]
That is an issue in Grafana's plugin install mechanism. There's not much we can do to fix this problem per se.

Maybe we can use a previously prepared AMI with grafana, instead of installing grafana on the fly. I'll look into this solution.

**Comment by lmr** [comment]
Since this bug was opened, I updated the grafana version being used by sct (commit 7a693ceb21c1e38e2c47efdcef62a16d4e69d040). Are you still having this problem, @noamha? I'm going to close that issue depending on your answer.

**Comment by kongove** [comment]
Grafana installation is fine currently, close this old issue.
