### ISSUE TITLE
ThreadFailedEvent raised during `get_backtrace()` calls

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#1672]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master
* **scylla**: mastr

### Logs
* test_id: b932e83e-2ac1-4159-9dbc-63e87492723f
* job log: https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-200gb-48h/16/

### Description

During the test there were a few coredumps created, and the background threads failed with those exceptions:

```
2020-01-10 13:28:36.408: (ThreadFailedEvent Severity.ERROR): message=
Traceback (most recent call last):
  File "/sct/sdcm/utils/thread.py", line 18, in wrapper
    result = func(*args, **kwargs)
  File "/sct/sdcm/cluster.py", line 861, in backtrace_thread
    self.get_backtraces()
  File "/sct/sdcm/cluster.py", line 846, in get_backtraces
    new_n_coredumps = self._get_n_coredumps()
  File "/sct/sdcm/utils/common.py", line 97, in inner
    return func(*args, **kwargs)
  File "/sct/sdcm/cluster.py", line 831, in _get_n_coredumps
    result = self.remoter.run('sudo coredumpctl --no-pager --no-legend 2>&1', verbose=False, ignore_status=True)
  File "/sct/sdcm/remote.py", line 259, in run
    result = _run()
  File "/sct/sdcm/utils/common.py", line 92, in inner
    return func(*args, **kwargs)
  File "/sct/sdcm/remote.py", line 246, in _run
    watchers=watchers, timeout=timeout)
  File "<decorator-gen-3>", line 2, in run
  File "/usr/local/lib/python3.6/site-packages/fabric/connection.py", line 30, in opens
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/fabric/connection.py", line 721, in run
    return self._run(self._remote_runner(), command, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/invoke/context.py", line 101, in _run
    return runner.run(command, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/invoke/runners.py", line 291, in run
    return self._run_body(command, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/invoke/runners.py", line 315, in _run_body
    self.start(command, shell, env)
  File "/usr/local/lib/python3.6/site-packages/fabric/runners.py", line 36, in start
    self.channel = self.context.create_session()
  File "<decorator-gen-2>", line 2, in create_session
  File "/usr/local/lib/python3.6/site-packages/fabric/connection.py", line 30, in opens
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/fabric/connection.py", line 698, in create_session
    channel = self.transport.open_session()
  File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 879, in open_session
    timeout=timeout,
  File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 998, in open_channel
    self._send_user_message(m)
  File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 1863, in _send_user_message
    self._send_message(data)
  File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 1839, in _send_message
    self.packetizer.send_message(data)
  File "/usr/local/lib/python3.6/site-packages/paramiko/packet.py", line 431, in send_message
    self.write_all(out)
  File "/usr/local/lib/python3.6/site-packages/paramiko/packet.py", line 367, in write_all
    raise EOFError()
EOFError
```

```
2020-01-11 14:49:10.654: (ThreadFailedEvent Severity.ERROR): message=[Errno 110] Connection timed out
Traceback (most recent call last):
  File "/sct/sdcm/utils/thread.py", line 18, in wrapper
    result = func(*args, **kwargs)
  File "/sct/sdcm/cluster.py", line 861, in backtrace_thread
    self.get_backtraces()
  File "/sct/sdcm/cluster.py", line 846, in get_backtraces
    new_n_coredumps = self._get_n_coredumps()
  File "/sct/sdcm/utils/common.py", line 97, in inner
    return func(*args, **kwargs)
  File "/sct/sdcm/cluster.py", line 831, in _get_n_coredumps
    result = self.remoter.run('sudo coredumpctl --no-pager --no-legend 2>&1', verbose=False, ignore_status=True)
  File "/sct/sdcm/remote.py", line 259, in run
    result = _run()
  File "/sct/sdcm/utils/common.py", line 92, in inner
    return func(*args, **kwargs)
  File "/sct/sdcm/remote.py", line 246, in _run
    watchers=watchers, timeout=timeout)
  File "<decorator-gen-3>", line 2, in run
  File "/usr/local/lib/python3.6/site-packages/fabric/connection.py", line 29, in opens
    self.open()
  File "/usr/local/lib/python3.6/site-packages/fabric/connection.py", line 634, in open
    self.client.connect(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/paramiko/client.py", line 349, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "/usr/local/lib/python3.6/site-packages/paramiko/util.py", line 283, in retry_on_signal
    return function()
  File "/usr/local/lib/python3.6/site-packages/paramiko/client.py", line 349, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
TimeoutError: [Errno 110] Connection timed out
```

**Comment by bentsi** [comment]
fixed in #1740
