### ISSUE TITLE
Longevity failed to send summery mail at the end of the run

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla-cluster-tests#1733]
### Prerequisites

* [x] Are you rebased to master ?
* [ ] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master
* **scylla**: master

### Logs
* test_id: 78ae57a2-6bef-402a-80a1-60c9c5aa0d87
* job log: https://cloudius-jenkins-test.s3.amazonaws.com/78ae57a2-6bef-402a-80a1-60c9c5aa0d87/20200126_045826/sct-runner-78ae57a2.zip
* Job: https://jenkins.scylladb.com/view/master/job/scylla-master/view/master-test/job/longevity/job/longevity-200gb-48h/19/

### Description

At the end of the test, sct failed to send the summery email, with the following error:
```
Traceback (most recent call last):
07:00:58    File "./sct.py", line 494, in <module>
07:00:58      cli()
07:00:58    File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 764, in __call__
07:00:58      return self.main(*args, **kwargs)
07:00:58    File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 717, in main
07:00:58      rv = self.invoke(ctx)
07:00:58    File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 1137, in invoke
07:00:58      return _process_result(sub_ctx.command.invoke(sub_ctx))
07:00:58    File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 956, in invoke
07:00:58      return ctx.invoke(self.callback, **ctx.params)
07:00:58    File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 555, in invoke
07:00:58      return callback(*args, **kwargs)
07:00:58    File "./sct.py", line 485, in send_email
07:00:58      reporter.send_report(test_results)
07:00:58    File "/sct/sdcm/send_email.py", line 169, in send_report
07:00:58      report = self._generate_report(report_data)
07:00:58    File "/sct/sdcm/send_email.py", line 206, in _generate_report
07:00:58      return self.build_report(report_data)
07:00:58    File "/sct/sdcm/send_email.py", line 243, in build_report
07:00:58      return self.render_to_html(report_data, template_str)
07:00:58    File "/sct/sdcm/send_email.py", line 139, in render_to_html
07:00:58      html = template.render(results)
07:00:58    File "/usr/local/lib64/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
07:00:58      return original_render(self, *args, **kwargs)
07:00:58    File "/usr/local/lib64/python3.6/site-packages/jinja2/environment.py", line 1008, in render
07:00:58      return self.environment.handle_exception(exc_info, True)
07:00:58    File "/usr/local/lib64/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
07:00:58      reraise(exc_type, exc_value, tb)
07:00:58    File "/usr/local/lib64/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
07:00:58      raise value.with_traceback(tb)
07:00:58    File "/sct/sdcm/results_longevity.html", line 1, in top-level template code
07:00:58      {% extends 'results_base.html' %}
07:00:58    File "/sct/sdcm/results_base.html", line 138, in top-level template code
07:00:58      {% block body %}
07:00:58    File "/sct/sdcm/results_longevity.html", line 115, in block "body"
07:00:58      {% for k,v in events_summary.items() %}
07:00:58    File "/usr/local/lib64/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
07:00:58      return getattr(obj, attribute)
07:00:58  jinja2.exceptions.UndefinedError: 'events_summary' is undefined
```

(Afterwards there was another error from the send_email.py file, but it doesn't seem too related as it's a traceback from the __del__ function)
```
07:00:58  Exception ignored in: <bound method Email.__del__ of <sdcm.send_email.Email object at 0x7f7a7c5244e0>>
07:00:58  Traceback (most recent call last):
07:00:58    File "/sct/sdcm/send_email.py", line 105, in __del__
07:00:58    File "/usr/lib64/python3.6/smtplib.py", line 984, in quit
07:00:58    File "/usr/lib64/python3.6/smtplib.py", line 420, in docmd
07:00:58    File "/usr/lib64/python3.6/smtplib.py", line 367, in putcmd
07:00:58    File "/usr/lib64/python3.6/smtplib.py", line 357, in send
07:00:58  smtplib.SMTPServerDisconnected: Server not connected
```

**Expected behavior:** The email summery message is sent out, in all cases

**Actual behavior:** The email was not sent

**Comment by ShlomiBalalis** [comment]
It seems to occur in several other jobs:
https://jenkins.scylladb.com/view/master/job/scylla-master/job/longevity/job/longevity-10gb-3h/64/
https://jenkins.scylladb.com/view/master/job/scylla-master/job/longevity/job/longevity-100gb-4h/99/

**Comment by aleksbykov** [comment]
Will take a look

**Comment by aleksbykov** [comment]
should be fixed

**Comment by ShlomiBalalis** [comment]
Seems like it's indeed solved, closing it for now
