### ISSUE TITLE
tester.py update_certificates() Exception: Failed to update certificates by openssl

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#1787]
running SCT branch-3.3 debian-9 rolling upgrade job:
https://jenkins.scylladb.com/job/scylla-3.3/job/rolling-upgrade/job/rolling-upgrade-debian9/11/console

fails with:
```
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR > Exception in setUp. Will call tearDown < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR > Exception in setUp. Will call tearDown
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR > Traceback (most recent call last):
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR >   File "/sct/sdcm/utils/common.py", line 1185, in update_certificates
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR >     localrunner.run('openssl x509 -enddate -noout -in data_dir/ssl_conf/db.crt')
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR >   File "/sct/sdcm/remote.py", line 158, in run
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR >     env=os.environ, replace_env=True)
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR >   File "/usr/local/lib/python3.6/site-packages/fabric/connection.py", line 748, in local
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR >     return super(Connection, self).run(*args, **kwargs)
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR >   File "/usr/local/lib/python3.6/site-packages/invoke/context.py", line 94, in run
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR >     return self._run(runner, command, **kwargs)
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR >   File "/usr/local/lib/python3.6/site-packages/invoke/context.py", line 101, in _run
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR >     return runner.run(command, **kwargs)
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR >   File "/usr/local/lib/python3.6/site-packages/invoke/runners.py", line 291, in run
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR >     return self._run_body(command, **kwargs)
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR >   File "/usr/local/lib/python3.6/site-packages/invoke/runners.py", line 442, in _run_body
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR >     raise UnexpectedExit(result)
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR > invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR > 
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR > Command: 'openssl x509 -enddate -noout -in data_dir/ssl_conf/db.crt'
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR > 
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR > Exit code: None
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR > 
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR > Stdout:
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR > 
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR > notAfter=Feb  6 22:34:00 2021 GMT
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR > 
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR > Stderr:
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR > 
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR > 
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR > 
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR > 
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR > 
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR > During handling of the above exception, another exception occurred:
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR > 
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR > Traceback (most recent call last):
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR >   File "/sct/sdcm/tester.py", line 127, in wrapper
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR >     return method(*args, **kwargs)
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR >   File "/sct/sdcm/utils/common.py", line 142, in inner
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR >     res = func(*args, **kwargs)
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR >   File "/sct/sdcm/tester.py", line 240, in setUp
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR >     update_certificates()
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR >   File "/sct/sdcm/utils/common.py", line 1187, in update_certificates
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR >     raise Exception('Failed to update certificates by openssl: %s' % ex)
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR > Exception: Failed to update certificates by openssl: Encountered a bad command exit code!
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR > 
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR > Command: 'openssl x509 -enddate -noout -in data_dir/ssl_conf/db.crt'
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR > 
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR > Exit code: None
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR > 
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR > Stdout:
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR > 
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR > notAfter=Feb  6 22:34:00 2021 GMT
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR > 
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR > Stderr:
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR > 
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR > 
00:34:00  < t:2020-02-07 22:34:00,252 f:tester.py       l:129  c:sdcm.tester          p:ERROR > 
00:34:00  < t:2020-02-07 22:34:00,262 f:tester.py       l:1342 c:sdcm.tester          p:INFO  > TearDown is starting...
```

**Comment by roydahan** [comment]
@bentsi what is it?
Where does it coming from?

**Comment by bentsi** [comment]
@roydahan we auto-generating certificates for tests running with encryption

**Comment by bentsi** [comment]
I can't reproduce it locally on my laptop. @yarongilor how many times did this happen?

**Comment by yarongilor** [comment]
> I can't reproduce it locally on my laptop. @yarongilor how many times did this happen?

once
