### ISSUE TITLE
add_drop_columns nemesis is breaking cassandra python driver

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#1822]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: [branch or hash tag you are working on]
* **scylla**: [branch or commit hash]

### Logs
* **SCT**: branch-3.3
* **scylla**: branch-3.3
* **test id**: dd68e1c2-45fe-404e-94c3-8c7d1f7e8559
* **job**: https://jenkins.scylladb.com/job/scylla-3.3/job/longevity/job/longevity-1tb-7days/7/

### Description

```
19:40:51  < t:2020-02-13 17:40:43,530 f:asyncorereactor.py l:438  c:cassandra.query      p:WARNING > Failed creating named tuple for results with column names ['first_name', 'username', 'a2071yzcqk', 'abxbo39zk1', 'acd2kt1voy', 'acpjbi6ygx', 'adrc3fxnms', 'aeexjngfd9', 'agco58dagw', 'ahx1uuz1i0', 'aiavtapkap', 'aknkjrowlb', 'al109zgdkf', 'aqrbfqbpjr', 'atoxrr6pwh', 'awe2w3889u', 'aywhkq72jj', 'b20c761z6y', 'b52bdovej0', 'b58ip6uci6', 'bb64blvmu8', 'bbsste8ilp', 'bc7tlnz1j1', 'bf092y9aeo', 'bf0kucngp1', 'bqzu3wlh27', 'c29tv03es0', 'c8t3j2wjb8', 'cavzayi9ue', 'cc81uy3ube', 'cdaudvpngu', 'ch1v57yshd', 'ckvzzc0kpn', 'csoffsg3xs', 'cxtppmmmxc', 'cytg2kom3u', 'd26nezeehk', 'd2xj401wbn', 'd40ee0floc', 'd9hpbsl365', 'db7qdu6vj7', 'de706h3e1y', 'dfftcxzkx5', 'dmmimlwb2i', 'dos6irxqno', 'dsad9oaz45', 'dsjlct2e1v', 'dtdauz0r3n', 'duaqrp8d1x', 'dwthgg42os', 'dymrpqbdal', 'e1jkbvqx8f', 'e6cum0pqnl', 'eb40ui8rwm', 'eba6qebda9', 'ecvlk1offs', 'edc2a5b8jj', 'eey0nkth1p', 'ejbs5e9kpq', 'ekl6j87uvf', 'email', 'excaa7ripf', 'f0l26s8yya', 'f0nca6gsvz', 'f16bha81hs', 'fe0n5vczv9', 'fem7e5s5hz', 'ffk68ilmmy', 'ffobb3eifl', 'fhc9uojo1z', 'fkieuq4axo', 'fwrk0jrofa', 'fy4z5bdaui', 'fzja2mahfz', 'g1noqdhotl', 'g3elf2ymz7', 'g3gf2sghoo', 'g40ldtu57t', 'ga7ior0haq', 'gco7xhrj6s', 'glb402umgu', 'gnuixmqmsi', 'gnxeh12aha', 'gst9klybip', 'gwz4a9a51i', 'gynbqm6los', 'h0qcxxpt5e', 'h11lpa06qa', 'h40d1fmgls', 'h5y2abf0bc', 'h6mw50z5qx', 'ha1eap07fb', 'hcqvuk7on7', 'hd3gpn5ftu', 'hfva3le5xt', 'hfwp3vbgio', 'hmshxe21wh', 'hnrbse6yl8', 'hqyhpz3f4i', 'hu9t4l42bw', 'hui6mjcz1a', 'hvd3woduwg', 'i18pjx747d', 'i1abxbwhd2', 'i2e1fvmnri', 'i2nmjhgfpm', 'i4h7bkxg87', 'i60ue4ufch', 'i9j914an7b', 'ia3o0khr7n', 'ihlm8x54xz', 'irtspeaksy', 'iu5dt5vosb', 'iud2bnn7ya', 'j3e0h9w18t', 'j6svop21sx', 'j87ljmldbq', 'j99hfekx9r', 'jaxlmnb4t6', 'jbuskipndw', 'jcz72k2axb', 'jgptgq6v1h', 'jh8yc10pvc', 'jjopr9i7eb', 'jmrr5h4wxq', 'jo24emhjdl', 'jpdtcyud9q', 'jq59f3pi5r', 'jrjkli4y9q', 'jv1p7wp6c5', 'jva5r7dz01', 'jz3cq8httr', 'jzjd231tz8', 'k2zw39k9s5', 'k8ppj67ctm', 'k9ah6z1tvy', 'kaf72wp084', 'kbbasjrb8l', 'ki9t26alrh', 'kinq8urglh', 'korvcommk1', 'koxpq0gfe3', 'kqaj4co4cb', 'ku4378wyz2', 'kurik2apzt', 'kwopgssrra', 'l704h5vdpk', 'l8wt7j1e74', 'la0tm0sgla', 'laj32sss3o', 'last_access', 'last_name', 'lcqe38oaem', 'lio26igyae', 'lla6p38xh8', 'lpjxzpnwy0', 'lw3rd5qd80', 'lwlwq7tff1', 'lwzjz6vuch', 'lxfr4px0nz', 'lylpr5cu3c', 'm27gw8wkcb', 'mbpghcsrdx', 'mc8hf7297f', 'mvye69jdxj', 'mxelabl8fm', 'mxvd12feti', 'nanj3yi7an', 'netol1mll8', 'nhf1fmsanz', 'nn2v3w4tjo', 'nv4y3s35gt', 'o2daods07z', 'o7u1z82wot', 'o8bhcqck0b', 'oc8g2qlub1', 'ocvmp5wwpx', 'oe5r12tnn0', 'ohyx8sswdk', 'onxvfz80mh', 'oqtq4b2sru', 'os3d97l1pq', 'osju4sxbc8', 'ow61873vui', 'oysm9ghxpm', 'p15bjuq3sk', 'p26zfiv5nf', 'password', 'pdhivqregw', 'phhg6svjim', 'ptf5n6vi5d', 'pue9e1nfv1', 'pwvdiojtbn', 'pyhg0uqhqw', 'q223dly3ec', 'q2p7xc8kpq', 'q4sw4uilz3', 'q632abn1dx', 'q6bw56s4gh', 'q6ycklpmk5', 'q9lpu4n23j', 'qb4f1i3688', 'qfp9k1emha', 'qhml7hoj4a', 'qhqj11zut6', 'qi5j1jbqtt', 'qm19wx6zgf', 'qm6h2l4ska', 'qokb61rvzq', 'qq73qipaqc', 'qqsie7xnq1', 'qqt8ylu54e', 'qr5eu2bpjs', 'qv9l2sj4dd', 'qvx9cvmnh2', 'qvzwf28apc', 'qw9jkyyhwd', 'qwrbqxut3s', 'r0sibseyuv', 'r2depuv4zq', 'r47r8e6n5d', 'r4kh1zk8au', 'r54enhi15u', 'r7ucybkw4q', 'rf3lhsrulj', 'rf92ynjhxu', 'rh96bryp1w', 'rj909jdtck', 'rnt59tjgim', 'ryxe7aljxu', 's1atc9bimp', 'sbak1uca47', 'sdkc1801kp', 'sebepgkwfl', 'seiswiogz0', 'sgmimm954n', 'sgp5grrkxt', 'sn5wi4rzoz', 'soexw3e9zo', 'sok1rhwfet', 'sq0nt4bivj', 'st0iiqgy3z', 'sv2ck36v72', 't0u0d5682n', 't170nre28l', 't26i86h0n4', 't2cuqzaq3i', 'tc2z0rm05g', 'thusf86r3f', 'tn24p0y5ev', 'tnapbdskyl', 'tpejw3m9mc', 'tsbk1sj22l', 'ttt72iioni', 'tw949mm8du', 'tz5zkjnbwc', 'tzdnug9pnz', 'u5hg4tvygg', 'u71myp31lv', 'u7ok9mk417', 'u7r0kk7wko', 'ubewa9icrp', 'ucmywfdmqf', 'ucu85yprip', 'uf02bqugux', 'ug5rsw45y5', 'ugrrpmbk8l', 'uj83jrlx93', 'unie88xfc1', 'uq843bzmfw', 'us28vg591s', 'usc2ek8qg8', 'uwmhp0x2kg', 'uzkwb7t3np', 'v0xd7z2o1s', 'v19z10fl0x', 'v1oi2ytoyt', 'v2wy2opm6j', 'vcyy7xqdrs', 'vdmb4dwzw4', 'vgzp05umfd', 'vhqlcot78i', 'vhuw2607uz', 'vhwzdqn1uk', 'vi4nzhirfq', 'vifren2cl0', 'vqg7tigmal', 'vye13usy2f', 'w2lhle2111', 'w2ykqi3mqg', 'wdvv7fvwq6', 'wk24q4jo99', 'wkvzr8o4ve', 'wnfka9r2g5', 'wpgfuz158e', 'wvjyts1wc8', 'wwcg67de58', 'wy443m45hz', 'wzb9iwtr9k', 'x1i33refaf', 'x2fvyqcrsm', 'x3jb6vd4hx', 'x4hz60kqfp', 'x6o96yq0u2', 'x794cpljxk', 'x92wqvintj', 'xcsg5lr4y7', 'xcwcvnu9j9', 'xe0t11urds', 'xebwpg3cin', 'xet5sf5lza', 'xg69679s09', 'xhqm1h1wxv', 'xhx6ppn4s3', 'xjtgfcqzcx', 'xom4i6vito', 'xp0zpkjt63', 'xqfbyaaova', 'xsffarn836', 'xt32y57ots', 'xvli53m2xj', 'xvrp7orpbr', 'y0p2wvme3c', 'y7pkae7w6g', 'y8jaw8jucl', 'y91jo4c7y8', 'ygf9qhth4g', 'yhoamwnzs9', 'yi10xqjlcv', 'ym0d9ltler', 'ync1bl3t7f', 'yzk071kfw6', 'z1ce4cnjkz', 'z1qwque4pg', 'z5q42up2hg', 'z9vlsjhzzv', 'zeg4u8ipcr', 'zfksduklc8', 'zgwbgzycct', 'zji905v1a2', 'zkekadyt9i', 'zzi8ihtvrm'] (cleaned: ['first_name', 'username', 'a2071yzcqk', 'abxbo39zk1', 'acd2kt1voy', 'acpjbi6ygx', 'adrc3fxnms', 'aeexjngfd9', 'agco58dagw', 'ahx1uuz1i0', 'aiavtapkap', 'aknkjrowlb', 'al109zgdkf', 'aqrbfqbpjr', 'atoxrr6pwh', 'awe2w3889u', 'aywhkq72jj', 'b20c761z6y', 'b52bdovej0', 'b58ip6uci6', 'bb64blvmu8', 'bbsste8ilp', 'bc7tlnz1j1', 'bf092y9aeo', 'bf0kucngp1', 'bqzu3wlh27', 'c29tv03es0', 'c8t3j2wjb8', 'cavzayi9ue', 'cc81uy3ube', 'cdaudvpngu', 'ch1v57yshd', 'ckvzzc0kpn', 'csoffsg3xs', 'cxtppmmmxc', 'cytg2kom3u', 'd26nezeehk', 'd2xj401wbn', 'd40ee0floc', 'd9hpbsl365', 'db7qdu6vj7', 'de706h3e1y', 'dfftcxzkx5', 'dmmimlwb2i', 'dos6irxqno', 'dsad9oaz45', 'dsjlct2e1v', 'dtdauz0r3n', 'duaqrp8d1x', 'dwthgg42os', 'dymrpqbdal', 'e1jkbvqx8f', 'e6cum0pqnl', 'eb40ui8rwm', 'eba6qebda9', 'ecvlk1offs', 'edc2a5b8jj', 'eey0nkth1p', 'ejbs5e9kpq', 'ekl6j87uvf', 'email', 'excaa7ripf', 'f0l26s8yya', 'f0nca6gsvz', 'f16bha81hs', 'fe0n5vczv9', 'fem7e5s5hz', 'ffk68ilmmy', 'ffobb3eifl', 'fhc9uojo1z', 'fkieuq4axo', 'fwrk0jrofa', 'fy4z5bdaui', 'fzja2mahfz', 'g1noqdhotl', 'g3elf2ymz7', 'g3gf2sghoo', 'g40ldtu57t', 'ga7ior0haq', 'gco7xhrj6s', 'glb402umgu', 'gnuixmqmsi', 'gnxeh12aha', 'gst9klybip', 'gwz4a9a51i', 'gynbqm6los', 'h0qcxxpt5e', 'h11lpa06qa', 'h40d1fmgls', 'h5y2abf0bc', 'h6mw50z5qx', 'ha1eap07fb', 'hcqvuk7on7', 'hd3gpn5ftu', 'hfva3le5xt', 'hfwp3vbgio', 'hmshxe21wh', 'hnrbse6yl8', 'hqyhpz3f4i', 'hu9t4l42bw', 'hui6mjcz1a', 'hvd3woduwg', 'i18pjx747d', 'i1abxbwhd2', 'i2e1fvmnri', 'i2nmjhgfpm', 'i4h7bkxg87', 'i60ue4ufch', 'i9j914an7b', 'ia3o0khr7n', 'ihlm8x54xz', 'irtspeaksy', 'iu5dt5vosb', 'iud2bnn7ya', 'j3e0h9w18t', 'j6svop21sx', 'j87ljmldbq', 'j99hfekx9r', 'jaxlmnb4t6', 'jbuskipndw', 'jcz72k2axb', 'jgptgq6v1h', 'jh8yc10pvc', 'jjopr9i7eb', 'jmrr5h4wxq', 'jo24emhjdl', 'jpdtcyud9q', 'jq59f3pi5r', 'jrjkli4y9q', 'jv1p7wp6c5', 'jva5r7dz01', 'jz3cq8httr', 'jzjd231tz8', 'k2zw39k9s5', 'k8ppj67ctm', 'k9ah6z1tvy', 'kaf72wp084', 'kbbasjrb8l', 'ki9t26alrh', 'kinq8urglh', 'korvcommk1', 'koxpq0gfe3', 'kqaj4co4cb', 'ku4378wyz2', 'kurik2apzt', 'kwopgssrra', 'l704h5vdpk', 'l8wt7j1e74', 'la0tm0sgla', 'laj32sss3o', 'last_access', 'last_name', 'lcqe38oaem', 'lio26igyae', 'lla6p38xh8', 'lpjxzpnwy0', 'lw3rd5qd80', 'lwlwq7tff1', 'lwzjz6vuch', 'lxfr4px0nz', 'lylpr5cu3c', 'm27gw8wkcb', 'mbpghcsrdx', 'mc8hf7297f', 'mvye69jdxj', 'mxelabl8fm', 'mxvd12feti', 'nanj3yi7an', 'netol1mll8', 'nhf1fmsanz', 'nn2v3w4tjo', 'nv4y3s35gt', 'o2daods07z', 'o7u1z82wot', 'o8bhcqck0b', 'oc8g2qlub1', 'ocvmp5wwpx', 'oe5r12tnn0', 'ohyx8sswdk', 'onxvfz80mh', 'oqtq4b2sru', 'os3d97l1pq', 'osju4sxbc8', 'ow61873vui', 'oysm9ghxpm', 'p15bjuq3sk', 'p26zfiv5nf', 'password', 'pdhivqregw', 'phhg6svjim', 'ptf5n6vi5d', 'pue9e1nfv1', 'pwvdiojtbn', 'pyhg0uqhqw', 'q223dly3ec', 'q2p7xc8kpq', 'q4sw4uilz3', 'q632abn1dx', 'q6bw56s4gh', 'q6ycklpmk5', 'q9lpu4n23j', 'qb4f1i3688', 'qfp9k1emha', 'qhml7hoj4a', 'qhqj11zut6', 'qi5j1jbqtt', 'qm19wx6zgf', 'qm6h2l4ska', 'qokb61rvzq', 'qq73qipaqc', 'qqsie7xnq1', 'qqt8ylu54e', 'qr5eu2bpjs', 'qv9l2sj4dd', 'qvx9cvmnh2', 'qvzwf28apc', 'qw9jkyyhwd', 'qwrbqxut3s', 'r0sibseyuv', 'r2depuv4zq', 'r47r8e6n5d', 'r4kh1zk8au', 'r54enhi15u', 'r7ucybkw4q', 'rf3lhsrulj', 'rf92ynjhxu', 'rh96bryp1w', 'rj909jdtck', 'rnt59tjgim', 'ryxe7aljxu', 's1atc9bimp', 'sbak1uca47', 'sdkc1801kp', 'sebepgkwfl', 'seiswiogz0', 'sgmimm954n', 'sgp5grrkxt', 'sn5wi4rzoz', 'soexw3e9zo', 'sok1rhwfet', 'sq0nt4bivj', 'st0iiqgy3z', 'sv2ck36v72', 't0u0d5682n', 't170nre28l', 't26i86h0n4', 't2cuqzaq3i', 'tc2z0rm05g', 'thusf86r3f', 'tn24p0y5ev', 'tnapbdskyl', 'tpejw3m9mc', 'tsbk1sj22l', 'ttt72iioni', 'tw949mm8du', 'tz5zkjnbwc', 'tzdnug9pnz', 'u5hg4tvygg', 'u71myp31lv', 'u7ok9mk417', 'u7r0kk7wko', 'ubewa9icrp', 'ucmywfdmqf', 'ucu85yprip', 'uf02bqugux', 'ug5rsw45y5', 'ugrrpmbk8l', 'uj83jrlx93', 'unie88xfc1', 'uq843bzmfw', 'us28vg591s', 'usc2ek8qg8', 'uwmhp0x2kg', 'uzkwb7t3np', 'v0xd7z2o1s', 'v19z10fl0x', 'v1oi2ytoyt', 'v2wy2opm6j', 'vcyy7xqdrs', 'vdmb4dwzw4', 'vgzp05umfd', 'vhqlcot78i', 'vhuw2607uz', 'vhwzdqn1uk', 'vi4nzhirfq', 'vifren2cl0', 'vqg7tigmal', 'vye13usy2f', 'w2lhle2111', 'w2ykqi3mqg', 'wdvv7fvwq6', 'wk24q4jo99', 'wkvzr8o4ve', 'wnfka9r2g5', 'wpgfuz158e', 'wvjyts1wc8', 'wwcg67de58', 'wy443m45hz', 'wzb9iwtr9k', 'x1i33refaf', 'x2fvyqcrsm', 'x3jb6vd4hx', 'x4hz60kqfp', 'x6o96yq0u2', 'x794cpljxk', 'x92wqvintj', 'xcsg5lr4y7', 'xcwcvnu9j9', 'xe0t11urds', 'xebwpg3cin', 'xet5sf5lza', 'xg69679s09', 'xhqm1h1wxv', 'xhx6ppn4s3', 'xjtgfcqzcx', 'xom4i6vito', 'xp0zpkjt63', 'xqfbyaaova', 'xsffarn836', 'xt32y57ots', 'xvli53m2xj', 'xvrp7orpbr', 'y0p2wvme3c', 'y7pkae7w6g', 'y8jaw8jucl', 'y91jo4c7y8', 'ygf9qhth4g', 'yhoamwnzs9', 'yi10xqjlcv', 'ym0d9ltler', 'ync1bl3t7f', 'yzk071kfw6', 'z1ce4cnjkz', 'z1qwque4pg', 'z5q42up2hg', 'z9vlsjhzzv', 'zeg4u8ipcr', 'zfksduklc8', 'zgwbgzycct', 'zji905v1a2', 'zkekadyt9i', 'zzi8ihtvrm']) (see Python 'namedtuple' documentation for details on name rules). Results will be returned with positional names. Avoid this by choosing different names, using SELECT "<col name>" AS aliases, or specifying a different row_factory on your Session
19:40:51  < t:2020-02-13 17:40:43,537 f:asyncorereactor.py l:438  c:cassandra.cluster    p:ERROR > Unexpected exception while handling result in ResponseFuture: < t:2020-02-13 17:40:43,537 f:asyncorereactor.py l:438  c:cassandra.cluster    p:ERROR > Unexpected exception while handling result in ResponseFuture:
19:40:51  < t:2020-02-13 17:40:43,537 f:asyncorereactor.py l:438  c:cassandra.cluster    p:ERROR > Traceback (most recent call last):
19:40:51  < t:2020-02-13 17:40:43,537 f:asyncorereactor.py l:438  c:cassandra.cluster    p:ERROR >   File "cassandra/query.py", line 118, in cassandra.query.named_tuple_factory
19:40:51  < t:2020-02-13 17:40:43,537 f:asyncorereactor.py l:438  c:cassandra.cluster    p:ERROR >   File "/usr/lib64/python3.6/collections/__init__.py", line 429, in namedtuple
19:40:51  < t:2020-02-13 17:40:43,537 f:asyncorereactor.py l:438  c:cassandra.cluster    p:ERROR >     exec(class_definition, namespace)
19:40:51  < t:2020-02-13 17:40:43,537 f:asyncorereactor.py l:438  c:cassandra.cluster    p:ERROR >   File "<string>", line 12
19:40:51  < t:2020-02-13 17:40:43,537 f:asyncorereactor.py l:438  c:cassandra.cluster    p:ERROR > SyntaxError: more than 255 arguments
19:40:51  < t:2020-02-13 17:40:43,537 f:asyncorereactor.py l:438  c:cassandra.cluster    p:ERROR > 
19:40:51  < t:2020-02-13 17:40:43,537 f:asyncorereactor.py l:438  c:cassandra.cluster    p:ERROR > During handling of the above exception, another exception occurred:
19:40:51  < t:2020-02-13 17:40:43,537 f:asyncorereactor.py l:438  c:cassandra.cluster    p:ERROR > 
19:40:51  < t:2020-02-13 17:40:43,537 f:asyncorereactor.py l:438  c:cassandra.cluster    p:ERROR > Traceback (most recent call last):
19:40:51  < t:2020-02-13 17:40:43,537 f:asyncorereactor.py l:438  c:cassandra.cluster    p:ERROR >   File "cassandra/cluster.py", line 3755, in cassandra.cluster.ResponseFuture._set_result
19:40:51  < t:2020-02-13 17:40:43,537 f:asyncorereactor.py l:438  c:cassandra.cluster    p:ERROR >   File "cassandra/query.py", line 127, in cassandra.query.named_tuple_factory
19:40:51  < t:2020-02-13 17:40:43,537 f:asyncorereactor.py l:438  c:cassandra.cluster    p:ERROR >   File "/usr/lib64/python3.6/collections/__init__.py", line 429, in namedtuple
19:40:51  < t:2020-02-13 17:40:43,537 f:asyncorereactor.py l:438  c:cassandra.cluster    p:ERROR >     exec(class_definition, namespace)
19:40:51  < t:2020-02-13 17:40:43,537 f:asyncorereactor.py l:438  c:cassandra.cluster    p:ERROR >   File "<string>", line 12
19:40:51  < t:2020-02-13 17:40:43,537 f:asyncorereactor.py l:438  c:cassandra.cluster    p:ERROR > SyntaxError: more than 255 arguments
```

**Comment by roydahan** [comment]
Is it due to the number of columns?
If so, we can decrease it significantly.

**Comment by fruch** [comment]
Yes it's the number of columns that case the problem. I guess anything under 200 would work

**Comment by dkropachev** [comment]
https://github.com/scylladb/scylla-cluster-tests/pull/1859
