### ISSUE TITLE
How about add an normal event for power off & system reboot

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla-cluster-tests#1905]
### Prerequisites

* [ ] Are you rebased to master ?
* [ ] Is it reproducible ?
* [ ] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: branch-3.3
* **scylla**:  scylla 3.3

### Logs
* test_id: 70101be6-db8d-4819-b66f-250eeebfae6f
* job log: 
  - sct-runner  | https://cloudius-jenkins-test.s3.amazonaws.com/70101be6-db8d-4819-b66f-250eeebfae6f/20200305_223941/sct-runner-70101be6.zip
  - db-cluster  | https://cloudius-jenkins-test.s3.amazonaws.com/70101be6-db8d-4819-b66f-250eeebfae6f/20200305_223941/db-cluster-70101be6.zip

### Description

In one upgrade job, a db node might be terminated, but the last spot termination query failed (exited -1).
In the node log, we see it's powered off.

Can we add an normal event for the power off and reboot?

```
https://jenkins.scylladb.com/job/scylla-3.3/job/rolling-upgrade/job/rolling-upgrade-centos7/41/console

The db-node-70101be6-0-4 was shutdown during the upgrade, this is the root reason why the job failed.
Resubmitted a new job: https://jenkins.scylladb.com/job/scylla-3.3/job/rolling-upgrade/job/rolling-upgrade-centos7/42/



[70101be6-db8d-4819-b66f-250eeebfae6f]$ less sct.log |grep -E 'a Node|ended$|begin$'

< t:2020-03-05 21:31:41,557 f:upgrade_test.py l:417  c:sdcm.tester          p:INFO  > Populate DB with many types of tables and data
< t:2020-03-05 21:33:08,228 f:upgrade_test.py l:419  c:sdcm.tester          p:INFO  > Run some Queries to verify data BEFORE UPGRADE
< t:2020-03-05 21:34:15,847 f:upgrade_test.py l:422  c:sdcm.tester          p:INFO  > Re-Populate DB with many types of tables and data

< t:2020-03-05 21:36:39,139 f:cluster_gce.py  l:133  c:sdcm.cluster         p:WARNING > Node rolling-upgrade-3-3-centos-db-node-70101be6-0-4 [34.74.144.162 | 10.142.0.35] (seed: False): Error during getting spot termination notification Encountered a bad command exit code!

< t:2020-03-05 21:36:39,139 f:cluster_gce.py  l:133  c:sdcm.cluster         p:WARNING > 

< t:2020-03-05 21:36:39,139 f:cluster_gce.py  l:133  c:sdcm.cluster         p:WARNING > Command: 'curl "http://metadata.google.internal/computeMetadata/v1/instance/preempted?wait_for_change=true&timeout_sec=15" -H "Metadata-Flavor: Google"'

< t:2020-03-05 21:36:39,139 f:cluster_gce.py  l:133  c:sdcm.cluster         p:WARNING > 

< t:2020-03-05 21:36:39,139 f:cluster_gce.py  l:133  c:sdcm.cluster         p:WARNING > Exit code: -1

< t:2020-03-05 21:36:39,139 f:cluster_gce.py  l:133  c:sdcm.cluster         p:WARNING > 

< t:2020-03-05 21:36:39,139 f:cluster_gce.py  l:133  c:sdcm.cluster         p:WARNING > Stdout:

< t:2020-03-05 21:36:39,139 f:cluster_gce.py  l:133  c:sdcm.cluster         p:WARNING > 

< t:2020-03-05 21:36:39,139 f:cluster_gce.py  l:133  c:sdcm.cluster         p:WARNING > 

< t:2020-03-05 21:36:39,139 f:cluster_gce.py  l:133  c:sdcm.cluster         p:WARNING > 

< t:2020-03-05 21:36:39,139 f:cluster_gce.py  l:133  c:sdcm.cluster         p:WARNING > Stderr:

< t:2020-03-05 21:36:39,139 f:cluster_gce.py  l:133  c:sdcm.cluster         p:WARNING > 

< t:2020-03-05 21:36:39,139 f:cluster_gce.py  l:133  c:sdcm.cluster         p:WARNING >   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

< t:2020-03-05 21:36:39,139 f:cluster_gce.py  l:133  c:sdcm.cluster         p:WARNING >                                  Dload  Upload   Total   Spent    Left  Speed

< t:2020-03-05 21:36:39,139 f:cluster_gce.py  l:133  c:sdcm.cluster         p:WARNING > 

< t:2020-03-05 21:36:39,139 f:cluster_gce.py  l:133  c:sdcm.cluster         p:WARNING >   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0


2020-03-05T21:36:39+00:00  rolling-upgrade-3-3-centos-db-node-70101be6-0-4 !INFO    | systemd-logind: Power key pressed.
2020-03-05T21:36:39+00:00  rolling-upgrade-3-3-centos-db-node-70101be6-0-4 !INFO    | systemd-logind: Powering Off...
2020-03-05T21:36:39+00:00  rolling-upgrade-3-3-centos-db-node-70101be6-0-4 !NOTICE  | systemd-logind: System is powering down.

< t:2020-03-05 21:38:34,164 f:upgrade_test.py l:488  c:sdcm.tester          p:INFO  > Upgrade Node rolling-upgrade-3-3-centos-db-node-70101be6-0-4 begin


06:39:33  ======================================================================
06:39:33  ERROR: test_rolling_upgrade (upgrade_test.UpgradeTest) [Step1 - Upgrade First Node ]
06:39:33  ----------------------------------------------------------------------
06:39:33  Traceback (most recent call last):
06:39:33    File "/sct/upgrade_test.py", line 489, in test_rolling_upgrade
06:39:33      self.upgrade_node(self.db_cluster.node_to_upgrade)
06:39:33    File "/sct/upgrade_test.py", line 41, in inner
06:39:33      self.cql_truncate_simple_tables(session=session, rows=self.insert_rows)
06:39:33    File "/sct/sdcm/fill_db_data.py", line 2861, in cql_truncate_simple_tables
06:39:33      session.execute(truncate_query % i)
06:39:33    File "cassandra/cluster.py", line 2134, in cassandra.cluster.Session.execute
06:39:33    File "cassandra/cluster.py", line 4026, in cassandra.cluster.ResponseFuture.result
06:39:33  cassandra.Unavailable: Error from server: code=1000 [Unavailable exception] message="Cannot achieve consistency level for cl ALL. Requires 4, alive 3" info={'consistency': 'ALL', 'required_replicas': 4, 'alive_replicas': 3}

< t:2020-03-05 21:41:56,271 f:upgrade_test.py l:515  c:sdcm.tester          p:INFO  > Upgrade Node rolling-upgrade-3-3-centos-db-node-70101be6-0-1 begin
< t:2020-03-05 21:43:38,331 f:upgrade_test.py l:533  c:sdcm.tester          p:INFO  > Rollback Node rolling-upgrade-3-3-centos-db-node-70101be6-0-1 begin
< t:2020-03-05 21:45:20,621 f:upgrade_test.py l:419  c:sdcm.tester          p:INFO  > Run some Queries to verify data after rollback the second node


< t:2020-03-05 21:45:44,491 f:fill_db_data.py l:2960 c:sdcm.fill_db_data    p:ERROR > INSERT INTO ks_no_range_ghost_test.users (KEY, password) VALUES ('user1', 'ch@ngem3a')
< t:2020-03-05 21:45:44,491 f:fill_db_data.py l:2960 c:sdcm.fill_db_data    p:ERROR > Traceback (most recent call last):
< t:2020-03-05 21:45:44,491 f:fill_db_data.py l:2960 c:sdcm.fill_db_data    p:ERROR >   File "/sct/sdcm/fill_db_data.py", line 2957, in run_db_queries
< t:2020-03-05 21:45:44,491 f:fill_db_data.py l:2960 c:sdcm.fill_db_data    p:ERROR >     res = session.execute(item['queries'][i])
< t:2020-03-05 21:45:44,491 f:fill_db_data.py l:2960 c:sdcm.fill_db_data    p:ERROR >   File "cassandra/cluster.py", line 2134, in cassandra.cluster.Session.execute
< t:2020-03-05 21:45:44,491 f:fill_db_data.py l:2960 c:sdcm.fill_db_data    p:ERROR >   File "cassandra/cluster.py", line 4026, in cassandra.cluster.ResponseFuture.result
< t:2020-03-05 21:45:44,491 f:fill_db_data.py l:2960 c:sdcm.fill_db_data    p:ERROR > cassandra.Unavailable: Error from server: code=1000 [Unavailable exception] message="Cannot achieve consistency level for cl QUORUM. Requires 1, alive 0" info={'consistency': 'QUORUM', 'required_replicas': 1, 'alive_replicas': 0}


< t:2020-03-05 21:47:02,761 f:upgrade_test.py l:551  c:sdcm.tester          p:INFO  > Upgrade Node rolling-upgrade-3-3-centos-db-node-70101be6-0-1 begin
```

### Steps to Reproduce

1. shutdown a node during upgrade test

**Expected behavior:** [What you expected to happen]

Expect to get an event for power off

**Actual behavior:** [What actually happened]

No event for power off

/CC @fruch

**Comment by bentsi** [comment]
@amoskong good idea. Please open a task in Trello

**Comment by amoskong** [comment]
> @amoskong good idea. Please open a task in Trello

https://trello.com/c/cjkwg5Xt/1732-add-event-for-poweroff-reboot

**Comment by fruch** [comment]
we can have an even like this, but it would be warning.
since we cant easily tell if it's a poweroff we requested or not
