### ISSUE TITLE
add drop nemesis fails with: ValueError: empty range for randrange() (1,1, 0)

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#1934]
### Prerequisites

* [ ] Are you rebased to master ?
* [ ] Is it reproducible ?
* [ ] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: [branch3.3]
* **scylla**: [branch 3.3]

### Logs
* test_id: [look for 'the Test ID' at the end of the log]
* job log: 
https://jenkins.scylladb.com/job/scylla-3.3/job/longevity/job/longevity-50gb-4days/3/

```
(DisruptionEvent Severity.ERROR): type=end name=ChaosMonkey node=Node longevity-tls-50gb-4d-3-3-db-node-fa96700b-4 [34.245.101.119 | 10.0.88.12] (seed: False) duration=245 error=empty range for randrange() (1,1, 0)
Traceback (most recent call last):
  File "/sct/sdcm/nemesis.py", line 1728, in wrapper
    result = method(*args, **kwargs)
  File "/sct/sdcm/nemesis.py", line 1942, in disrupt
    self.call_random_disrupt_method()
  File "/sct/sdcm/nemesis.py", line 647, in call_random_disrupt_method
    disrupt_method()
  File "/sct/sdcm/nemesis.py", line 1026, in disrupt_add_drop_column
    self._add_drop_column_run_in_cycle()
  File "/sct/sdcm/nemesis.py", line 859, in _add_drop_column_run_in_cycle
    self._add_drop_column()
  File "/sct/sdcm/nemesis.py", line 837, in _add_drop_column
    add = self._add_drop_column_generate_columns_to_add(added_columns_info)
  File "/sct/sdcm/nemesis.py", line 814, in _add_drop_column_generate_columns_to_add
    for num in range(random.randrange(1, upper_limit_columns_to_add)):
  File "/usr/lib64/python3.6/random.py", line 199, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (1,1, 0)
```

**Comment by dkropachev** [comment]
fixed
