### ISSUE TITLE
SCT get failures with ssh timeouts on scale 200 nodes test

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#1966]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: [3.3]
* **scylla**: [3.3]

### Logs
* test_id: 551d9120-92bb-4de5-9346-43a1c91eb894
* job log: https://jenkins.scylladb.com/job/scylla-3.3/job/features-/job/features-scale-180-200-cluster-test/

```
+------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                          Log links for testrun with test id 551d9120-92bb-4de5-9346-43a1c91eb894                                           |
+-----------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
| Date            | Log type   | Link                                                                                                                        |
+-----------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
| 20200323_165936 | db-cluster | https://cloudius-jenkins-test.s3.amazonaws.com/551d9120-92bb-4de5-9346-43a1c91eb894/20200323_165936/db-cluster-551d9120.zip |
| 20200323_165936 | sct-runner | https://cloudius-jenkins-test.s3.amazonaws.com/551d9120-92bb-4de5-9346-43a1c91eb894/20200323_165936/sct-runner-551d9120.zip |
+-----------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
```
### Description
running the scale test of 180 - to - 200 db nodes fails twice on 2 different builders when using sct branch 3.3. the monitor node got timeouts and failed to setup. as well as db nodes that returned many timeouts of ssh connections.
example failures:
```
in this test job: https://jenkins.scylladb.com/job/scylla-3.3/job/features-/job/features-scale-180-200-cluster-test/
it fails with error like: 
https://jenkins.scylladb.com/job/scylla-3.3/job/features-/job/features-scale-180-200-cluster-test/
Traceback (most recent call last):
 File "/sct/sdcm/tester.py", line 127, in wrapper
   return method(*args, **kwargs)
 File "/sct/sdcm/utils/common.py", line 147, in inner
   res = func(*args, **kwargs)
 File "/sct/sdcm/tester.py", line 254, in setUp
   self.init_nodes(db_cluster=self.db_cluster)
 File "/sct/sdcm/tester.py", line 230, in init_nodes
   db_cluster.wait_for_init(node_list=db_cluster.non_seed_nodes)
 File "/sct/sdcm/cluster.py", line 2862, in wrapper
   raise NodeSetupFailed(f"{node}:{node_status}")
sdcm.cluster.NodeSetupFailed: Node cluster-scale-test-3-3-db-node-aab24e22-104 [63.35.202.85 | 10.0.94.97] (seed: False):False
also got errors like:
Traceback (most recent call last):
 File "/sct/sdcm/utils/thread.py", line 18, in wrapper
   result = func(*args, **kwargs)
 File "/sct/sdcm/cluster.py", line 960, in backtrace_thread
   self.get_backtraces()
 File "/sct/sdcm/cluster.py", line 911, in get_backtraces
   self.wait_ssh_up(verbose=False)
 File "/sct/sdcm/cluster.py", line 1131, in wait_ssh_up
   wait.wait_for(func=self.remoter.is_up, step=10, text=text, timeout=timeout, throw_exc=True)
 File "/sct/sdcm/wait.py", line 71, in wait_for
   raise RetryError(err)
tenacity.RetryError: RetryError[Wait for: is_up: timeout - 500 seconds - expired]
```
and the monitor was not installed with scylla since this error:
```
< t:2020-03-24 10:46:58,957 f:cluster.py      l:700  c:sdcm.cluster         p:WARNING > Node cluster-scale-test-3-3-monitor-node-aab24e22-1 [54.229.152.111 | 10.0.71.152] (seed: False): Unable to connect to 'cluster-scale-test-3-3-monitor-node-aab24e22-1'. Probably the node was terminated or is still booting. Error details: 'RetryError[Wait for: is_up: timeout - 500 seconds - expired]'
```

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]
running scylla 3.3 ami with sct 3.2 branch completed and passed without such errors.
**Actual behavior:** [What actually happened]

**Comment by roydahan** [comment]
@bentsi I need someone to look on this.

**Comment by fruch** [comment]
@dkropachev solved this with moving to use libssh2
