### ISSUE TITLE
Nemesis disrupt_rebuild_streaming_err failed with runtime error: operation rebuild is in progress, try again

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-cluster-tests#2004]
### Prerequisites

* [x] Are you rebased to master ?
* [ ] Is it reproducible ?
* [ ] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: juliayakovlev:lwt_longevity_validate_data_2_loaders
* **scylla**: 4.0.rc0-0.20200325.78f5afec30

### Logs
* test_id: 1973df16-d0b8-410e-bb2f-c58568e6bb54
* job log: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/yulia/job/staging-longevity-lwt-2-loaders-3h/1/console

### Description

- destroy data and restart

- run rebuild. rebuild_with_repair was started:
```
< t:2020-04-05 12:34:40,457 f:cluster.py      l:1415 c:sdcm.cluster         p:DEBUG > 4-05T12:34:40+00:00  longevity-lwt-3h-lwt-long-db-node-1973df16-2 !INFO    | scylla: [shard 0] storage_service - rebuild from dc: (any dc)
< t:2020-04-05 12:34:40,458 f:cluster.py      l:1415 c:sdcm.cluster         p:DEBUG > 2020-04-05T12:34:40+00:00  longevity-lwt-3h-lwt-long-db-node-1973df16-2 !INFO    | scylla: [shard 0] repair - rebuild_with_repair: started with keyspaces={cqlstress_lwt_example, system_auth, system_distributed, system_traces}, source_dc=us-east
< t:2020-04-05 12:34:40,458 f:cluster.py      l:1415 c:sdcm.cluster         p:DEBUG > 2020-04-05T12:34:40+00:00  longevity-lwt-3h-lwt-long-db-node-1973df16-2 !INFO    | scylla: [shard 0] repair - rebuild_with_repair: started with keyspace=cqlstress_lwt_example, source_dc=us-east, nr_ranges=758
< t:2020-04-05 12:34:40,458 f:cluster.py      l:1415 c:sdcm.cluster         p:DEBUG > 2020-04-05T12:34:40+00:00  longevity-lwt-3h-lwt-long-db-node-1973df16-2 !INFO    | scylla: [shard 0] repair - repair id 1 to sync data for keyspace=cqlstress_lwt_example, status=started
```

- Interrupt the task by pkill - run command ```sudo pkill -9 -f rebuild```
Rebuild was stopped:
```
< t:2020-04-05 12:40:44,977 f:cluster.py      l:1415 c:sdcm.cluster         p:DEBUG > 2020-04-05T12:40:43+00:00  longevity-lwt-3h-lwt-long-db-node-1973df16-2 !INFO    | scylla: [shard 0] repair - Repair 689 out of 758 ranges, id=1, shard
=0, keyspace=cqlstress_lwt_example, table={blogposts_update_two_columns_lwt_indicator_upd, blogposts_update_two_columns_lwt_indicator, blogposts_update_one_column_lwt_indicator_upd, blogposts_not_updated_lwt_indicator, blogposts, blogpos
ts_update_one_column_lwt_indicator}, range=(8374190472489063327, 8375415926442631377]
< t:2020-04-05 12:40:51,792 f:nemesis.py      l:1780 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: Interrupt the task (rebuild) to trigger streaming error
< t:2020-04-05 12:40:51,792 f:nemesis.py      l:1782 c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Interrupt the task by pkill
< t:2020-04-05 12:40:51,793 f:remote.py       l:305  c:sdcm.remote          p:DEBUG > RemoteCmdRunner [centos@172.30.0.100]: Running command "sudo pkill -9 -f rebuild"...
< t:2020-04-05 12:40:51,888 f:remote.py       l:160  c:sdcm.remote          p:ERROR > RemoteCmdRunner [centos@172.30.0.100]: Error executing command: "nodetool  rebuild "; Exit status: -1
< t:2020-04-05 12:40:51,889 f:cluster.py      l:2420 c:sdcm.cluster_aws     p:CRITICAL > Node longevity-lwt-3h-lwt-long-db-node-1973df16-2 [52.90.189.161 | 172.30.0.100] (seed: False): Command 'nodetool  rebuild ' error: Encountered a bad command exit code!
< t:2020-04-05 12:40:51,889 f:cluster.py      l:2420 c:sdcm.cluster_aws     p:CRITICAL > 
< t:2020-04-05 12:40:51,889 f:cluster.py      l:2420 c:sdcm.cluster_aws     p:CRITICAL > Command: 'nodetool  rebuild '
< t:2020-04-05 12:40:51,889 f:cluster.py      l:2420 c:sdcm.cluster_aws     p:CRITICAL > 
< t:2020-04-05 12:40:51,889 f:cluster.py      l:2420 c:sdcm.cluster_aws     p:CRITICAL > Exit code: -1
< t:2020-04-05 12:40:51,889 f:cluster.py      l:2420 c:sdcm.cluster_aws     p:CRITICAL > 
< t:2020-04-05 12:40:51,889 f:cluster.py      l:2420 c:sdcm.cluster_aws     p:CRITICAL > Stdout:
< t:2020-04-05 12:40:51,889 f:cluster.py      l:2420 c:sdcm.cluster_aws     p:CRITICAL > 
< t:2020-04-05 12:40:51,889 f:cluster.py      l:2420 c:sdcm.cluster_aws     p:CRITICAL > 
< t:2020-04-05 12:40:51,889 f:cluster.py      l:2420 c:sdcm.cluster_aws     p:CRITICAL > 
< t:2020-04-05 12:40:51,889 f:cluster.py      l:2420 c:sdcm.cluster_aws     p:CRITICAL > Stderr:
< t:2020-04-05 12:40:51,889 f:cluster.py      l:2420 c:sdcm.cluster_aws     p:CRITICAL > 
< t:2020-04-05 12:40:51,889 f:cluster.py      l:2420 c:sdcm.cluster_aws     p:CRITICAL > 
< t:2020-04-05 12:40:51,889 f:cluster.py      l:2420 c:sdcm.cluster_aws     p:CRITICAL > 
< t:2020-04-05 12:40:51,889 f:nemesis.py      l:1757 c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: rebuild is stopped
```

By node log repair continue to run.

- Run rebuild again
```
< t:2020-04-05 12:41:13,298 f:nemesis.py      l:1797 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: Recover the target node by a final rebuild
< t:2020-04-05 12:41:13,299 f:remote.py       l:305  c:sdcm.remote          p:DEBUG > RemoteCmdRunner [centos@172.30.0.100]: Running command "nodetool  rebuild "...
.....................
< t:2020-04-05 12:41:15,120 f:cluster.py      l:1415 c:sdcm.cluster         p:DEBUG > 2020-04-05T12:41:14+00:00  longevity-lwt-3h-lwt-long-db-node-1973df16-2 !INFO    | scylla: [shard 0] repair - Repair 736 out of 758 ranges, id=1, shard
=0, keyspace=cqlstress_lwt_example, table={blogposts_update_two_columns_lwt_indicator_upd, blogposts_update_two_columns_lwt_indicator, blogposts_update_one_column_lwt_indicator_upd, blogposts_not_updated_lwt_indicator, blogposts, blogpos
ts_update_one_column_lwt_indicator}, range=(8920050016845192518, 8947197890786007907]
< t:2020-04-05 12:41:15,729 f:remote.py       l:347  c:sdcm.remote          p:DEBUG > RemoteCmdRunner [centos@172.30.0.174]: Error reading SSH protocol banner
< t:2020-04-05 12:41:18,701 f:remote.py       l:732  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@172.30.0.100]: nodetool: Scylla API server HTTP POST to URL '/storage_service/rebuild' failed: std::runtime_error (Operation re
build is in progress, try again)
< t:2020-04-05 12:41:18,701 f:remote.py       l:732  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@172.30.0.100]: See 'nodetool help' or 'nodetool help <command>'.
< t:2020-04-05 12:41:18,720 f:remote.py       l:160  c:sdcm.remote          p:ERROR > RemoteCmdRunner [centos@172.30.0.100]: Error executing command: "nodetool  rebuild "; Exit status: 1
< t:2020-04-05 12:41:18,721 f:remote.py       l:162  c:sdcm.remote          p:DEBUG > RemoteCmdRunner [centos@172.30.0.100]: STDOUT: nodetool: Scylla API server HTTP POST to URL '/storage_service/rebuild' failed: std::runtime_error (Oper
ation rebuild is in progress, try again)
```

Unhandled exception in nemesis:
```
< t:2020-04-05 12:41:18,721 f:nemesis.py      l:655  c:sdcm.nemesis         p:ERROR > sdcm.nemesis.ChaosMonkey: ('Exception in random_disrupt_method %s: %s', 'rebuild_streaming_err', <UnexpectedExit: cmd='nodetool  rebuild ' exited=1>)
< t:2020-04-05 12:41:18,722 f:nemesis.py      l:1889 c:sdcm.nemesis         p:ERROR > sdcm.nemesis.ChaosMonkey: Unhandled exception in method <function ChaosMonkey.disrupt at 0x7f757bf4bea0> < t:2020-04-05 12:41:18,722 f:nemesis.py      
l:1889 c:sdcm.nemesis         p:ERROR > sdcm.nemesis.ChaosMonkey: Unhandled exception in method <function ChaosMonkey.disrupt at 0x7f757bf4bea0>
< t:2020-04-05 12:41:18,722 f:nemesis.py      l:1889 c:sdcm.nemesis         p:ERROR > Traceback (most recent call last):
< t:2020-04-05 12:41:18,722 f:nemesis.py      l:1889 c:sdcm.nemesis         p:ERROR >   File "/sct/sdcm/nemesis.py", line 1879, in wrapper
< t:2020-04-05 12:41:18,722 f:nemesis.py      l:1889 c:sdcm.nemesis         p:ERROR >     result = method(*args, **kwargs)
< t:2020-04-05 12:41:18,722 f:nemesis.py      l:1889 c:sdcm.nemesis         p:ERROR >   File "/sct/sdcm/nemesis.py", line 2100, in disrupt
< t:2020-04-05 12:41:18,722 f:nemesis.py      l:1889 c:sdcm.nemesis         p:ERROR >     self.call_random_disrupt_method()
< t:2020-04-05 12:41:18,722 f:nemesis.py      l:1889 c:sdcm.nemesis         p:ERROR >   File "/sct/sdcm/nemesis.py", line 652, in call_random_disrupt_method
< t:2020-04-05 12:41:18,722 f:nemesis.py      l:1889 c:sdcm.nemesis         p:ERROR >     disrupt_method()
< t:2020-04-05 12:41:18,722 f:nemesis.py      l:1889 c:sdcm.nemesis         p:ERROR >   File "/sct/sdcm/nemesis.py", line 1813, in disrupt_rebuild_streaming_err
< t:2020-04-05 12:41:18,722 f:nemesis.py      l:1889 c:sdcm.nemesis         p:ERROR >     self.break_streaming_task_and_rebuild(task='rebuild')
< t:2020-04-05 12:41:18,722 f:nemesis.py      l:1889 c:sdcm.nemesis         p:ERROR >   File "/sct/sdcm/nemesis.py", line 1798, in break_streaming_task_and_rebuild
< t:2020-04-05 12:41:18,722 f:nemesis.py      l:1889 c:sdcm.nemesis         p:ERROR >     self.repair_nodetool_rebuild()
< t:2020-04-05 12:41:18,722 f:nemesis.py      l:1889 c:sdcm.nemesis         p:ERROR >   File "/sct/sdcm/nemesis.py", line 668, in repair_nodetool_rebuild
< t:2020-04-05 12:41:18,722 f:nemesis.py      l:1889 c:sdcm.nemesis         p:ERROR >     self.target_node.run_nodetool('rebuild')
< t:2020-04-05 12:41:18,722 f:nemesis.py      l:1889 c:sdcm.nemesis         p:ERROR >   File "/sct/sdcm/cluster.py", line 2416, in run_nodetool
< t:2020-04-05 12:41:18,722 f:nemesis.py      l:1889 c:sdcm.nemesis         p:ERROR >     result = self.remoter.run(cmd, timeout=timeout, ignore_status=ignore_status, verbose=verbose)
< t:2020-04-05 12:41:18,722 f:nemesis.py      l:1889 c:sdcm.nemesis         p:ERROR >   File "/sct/sdcm/utils/decorators.py", line 121, in inner
< t:2020-04-05 12:41:18,722 f:nemesis.py      l:1889 c:sdcm.nemesis         p:ERROR >     return func(*args, **kwargs)
< t:2020-04-05 12:41:18,722 f:nemesis.py      l:1889 c:sdcm.nemesis         p:ERROR >   File "/sct/sdcm/remote.py", line 332, in run
< t:2020-04-05 12:41:18,722 f:nemesis.py      l:1889 c:sdcm.nemesis         p:ERROR >     result = _run()
< t:2020-04-05 12:41:18,722 f:nemesis.py      l:1889 c:sdcm.nemesis         p:ERROR >   File "/sct/sdcm/utils/decorators.py", line 116, in inner
< t:2020-04-05 12:41:18,722 f:nemesis.py      l:1889 c:sdcm.nemesis         p:ERROR >     return func(*args, **kwargs)
< t:2020-04-05 12:41:18,722 f:nemesis.py      l:1889 c:sdcm.nemesis         p:ERROR >   File "/sct/sdcm/remote.py", line 317, in _run
< t:2020-04-05 12:41:18,722 f:nemesis.py      l:1889 c:sdcm.nemesis         p:ERROR >     result = self.connection.run(**command_kwargs)
< t:2020-04-05 12:41:18,722 f:nemesis.py      l:1889 c:sdcm.nemesis         p:ERROR >   File "<decorator-gen-3>", line 2, in run
< t:2020-04-05 12:41:18,722 f:nemesis.py      l:1889 c:sdcm.nemesis         p:ERROR >   File "/usr/local/lib/python3.6/site-packages/fabric/connection.py", line 30, in opens
< t:2020-04-05 12:41:18,722 f:nemesis.py      l:1889 c:sdcm.nemesis         p:ERROR >     return method(self, *args, **kwargs)
< t:2020-04-05 12:41:18,722 f:nemesis.py      l:1889 c:sdcm.nemesis         p:ERROR >   File "/usr/local/lib/python3.6/site-packages/fabric/connection.py", line 721, in run
< t:2020-04-05 12:41:18,722 f:nemesis.py      l:1889 c:sdcm.nemesis         p:ERROR >     return self._run(self._remote_runner(), command, **kwargs)
< t:2020-04-05 12:41:18,722 f:nemesis.py      l:1889 c:sdcm.nemesis         p:ERROR >   File "/usr/local/lib/python3.6/site-packages/invoke/context.py", line 101, in _run
< t:2020-04-05 12:41:18,722 f:nemesis.py      l:1889 c:sdcm.nemesis         p:ERROR >     return runner.run(command, **kwargs)
< t:2020-04-05 12:41:18,722 f:nemesis.py      l:1889 c:sdcm.nemesis         p:ERROR >   File "/usr/local/lib/python3.6/site-packages/invoke/runners.py", line 291, in run
< t:2020-04-05 12:41:18,722 f:nemesis.py      l:1889 c:sdcm.nemesis         p:ERROR >     return self._run_body(command, **kwargs)
< t:2020-04-05 12:41:18,722 f:nemesis.py      l:1889 c:sdcm.nemesis         p:ERROR >   File "/usr/local/lib/python3.6/site-packages/invoke/runners.py", line 442, in _run_body
< t:2020-04-05 12:41:18,722 f:nemesis.py      l:1889 c:sdcm.nemesis         p:ERROR >     raise UnexpectedExit(result)
< t:2020-04-05 12:41:18,722 f:nemesis.py      l:1889 c:sdcm.nemesis         p:ERROR > invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!
< t:2020-04-05 12:41:18,722 f:nemesis.py      l:1889 c:sdcm.nemesis         p:ERROR > 
< t:2020-04-05 12:41:18,722 f:nemesis.py      l:1889 c:sdcm.nemesis         p:ERROR > Command: 'nodetool  rebuild '
< t:2020-04-05 12:41:18,722 f:nemesis.py      l:1889 c:sdcm.nemesis         p:ERROR > 
< t:2020-04-05 12:41:18,722 f:nemesis.py      l:1889 c:sdcm.nemesis         p:ERROR > Exit code: 1
< t:2020-04-05 12:41:18,722 f:nemesis.py      l:1889 c:sdcm.nemesis         p:ERROR > 
< t:2020-04-05 12:41:18,722 f:nemesis.py      l:1889 c:sdcm.nemesis         p:ERROR > Stdout:
< t:2020-04-05 12:41:18,722 f:nemesis.py      l:1889 c:sdcm.nemesis         p:ERROR > 
< t:2020-04-05 12:41:18,722 f:nemesis.py      l:1889 c:sdcm.nemesis         p:ERROR > nodetool: Scylla API server HTTP POST to URL '/storage_service/rebuild' failed: std::runtime_error (Operation rebuild is in progress, try again)
< t:2020-04-05 12:41:18,722 f:nemesis.py      l:1889 c:sdcm.nemesis         p:ERROR > See 'nodetool help' or 'nodetool help <command>'.
```

**Comment by amoskong** [comment]
It seems the 'nodetool rebuild' command/process is really killed, but there is a rebuilding task running when the final rebuild is executed.

1. the first rebuild tasking hasn't stopped
2. maybe we need to check the rebuild task status or db log after killed 'nodetool rebuild', make sure it's really stopped, then execute the final rebuild.

**Comment by amoskong** [comment]
After 'nodetool rebuild' is killed, the rebuild task will continue run in background until complete.
We can use abort_repair (http://127.0.0.1:10000/storage_service/force_terminate_repair) to stop the background rebuild task. Then execute a new 'nodetool rebuild'

@fruch

**Comment by juliayakovlev** [comment]
@bentsi  @amoskong 
This issue happened again in the branch-2020.1.
job: https://jenkins.scylladb.com/job/enterprise-2020.1/job/longevity/job/longevity-large-collections-12h/1/

```
2020-07-01 12:33:20.538: (DisruptionEvent Severity.ERROR): type=end name=RebuildStreamingErr node=Node longevity-large-collections-12h-202-db-node-f19e4fc6-4 [54.154.186.244 | 10.0.34.129] (seed: False) duration=504 error=Encountered a bad command exit code!

Command: 'nodetool  rebuild '

Exit code: 1

Stdout:

nodetool: Scylla API server HTTP POST to URL '/storage_service/rebuild' failed: std::runtime_error (Operation rebuild is in progress, try again)
See 'nodetool help' or 'nodetool help <command>'.

Stderr:
```

**Comment by amoskong** [comment]
Fixed by https://github.com/scylladb/scylla-cluster-tests/commit/1914385572d37f5f9b8721eef8cdbca80d6b6376
