### ISSUE TITLE
ValidateHintedHandoffShortDowntime fails with "No results from Prometheus"

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#2123]
## Versions
* **SCT**: master, branch-4.1
* **scylla**: master. branch-4.1

### Description
Recently we start seeing `ValidateHintedHandoffShortDowntime` failing with "No results from Prometheus"

@juliayakovlev noticed the following:

I see that the query didn't failed ( no message "Prometheus query unsuccessful!" in the log),  It means that the result received from Prometheus (result["data"]["result"]) is empty. I think need to checked Prometheus data
```
< t:2020-05-06 21:06:03,091 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  > Traceback (most recent call last):
< t:2020-05-06 21:06:03,091 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  >   File "/sct/sdcm/nemesis.py", line 1973, in wrapper
< t:2020-05-06 21:06:03,091 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  >     result = method(*args, **kwargs)
< t:2020-05-06 21:06:03,091 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  >   File "/sct/sdcm/nemesis.py", line 2197, in disrupt
< t:2020-05-06 21:06:03,091 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  >     self.call_random_disrupt_method()
< t:2020-05-06 21:06:03,091 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  >   File "/sct/sdcm/nemesis.py", line 660, in call_random_disrupt_method
< t:2020-05-06 21:06:03,091 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  >     disrupt_method()
< t:2020-05-06 21:06:03,091 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  >   File "/sct/sdcm/nemesis.py", line 1365, in disrupt_validate_hh_short_downtime
< t:2020-05-06 21:06:03,091 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  >     assert self.tester.hints_sending_in_progress() is False, "Hints are sent too slow"
< t:2020-05-06 21:06:03,091 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  >   File "/sct/sdcm/utils/decorators.py", line 123, in inner
< t:2020-05-06 21:06:03,091 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  >     return func(*args, **kwargs)
< t:2020-05-06 21:06:03,091 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  >   File "/sct/sdcm/tester.py", line 1720, in hints_sending_in_progress
< t:2020-05-06 21:06:03,091 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  >     assert results, "No results from Prometheus"
< t:2020-05-06 21:06:03,091 f:sct_events.py   l:886  c:sdcm.sct_events      p:INFO  > AssertionError: No results from Prometheus
```

### Logs
* test_id: 3b9c67ae-e489-4dcd-ac2a-c1307990b75b
* job log: https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-alternator-3h-test/39/ 
```
hydra investigate show-monitor 3b9c67ae-e489-4dcd-ac2a-c1307990b75b
hydra investigate show-logs 3b9c67ae-e489-4dcd-ac2a-c1307990b75b
```

**Comment by roydahan** [comment]
Are we sure HH enabled?
Didn’t the metrics changed?

**Comment by juliayakovlev** [comment]
HH is not disabled in the longevity-alternator-3h.yaml.

**Comment by fruch** [comment]
I've found the root cause
seem like the `scrape_interval` was set to 20s in:
https://github.com/scylladb/scylla-monitoring/commit/6acafea46909f140cfcb7258a341a15ea13f3717

since our query was with 15s, it returned without data
we should make our range a bit bigger then the step (we are using `scrape_interval` for the step) in the api call
