### ISSUE TITLE
scylla-bench crashing on GCE run

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#2185]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: 4.0.0
* **scylla**: master

### Logs
* test_id: 4a0be1a9-63f8-4fe9-ad53-cecfd472db56
* job log: https://jenkins.scylladb.com/job/sct-github-PRs-scan/job/scylla-cluster-tests/job/PR-2178/16/

### Description

when running the GCE provision test, scylla-bench is crashing on SIGSEGV

```
onfiguration
Mode:                    write
Workload:                sequential
Timeout:                 5s
Consistency level:       quorum
Partition count:         10
Clustering rows:         100
Clustering row size:     Fixed(5120)
Rows per request:        10
Page size:               1000
Concurrency:             7
Connections:             4
Maximum rate:            300 op/s
Client compression:      true

time                operations/s   rows/s   errors  max              99.9th           99th             95th             90th             median           mean             panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x67baf8]

goroutine 137 [running]:
sync.(*Mutex).Lock(...)
        /usr/local/go/src/sync/mutex.go:74
github.com/gocql/gocql.(*Session).routingKeyInfo(0x0, 0x7b11e0, 0xc000088010, 0xc0002f4040, 0x3a, 0x0, 0x0, 0x0)
        /home/scylla-test/go/src/github.com/gocql/gocql/session.go:495 +0x58
github.com/gocql/gocql.(*Batch).GetRoutingKey(0xc0002961c0, 0x7f49f8b9bfff, 0x800, 0x7f49f89be300, 0x20300000000000, 0x7f49f8b9bfff)
        /home/scylla-test/go/src/github.com/gocql/gocql/session.go:1774 +0xcf
github.com/gocql/gocql.(*tokenAwareHostPolicy).Pick(0xc0000c23f0, 0x7b4540, 0xc0002961c0, 0x0)
        /home/scylla-test/go/src/github.com/gocql/gocql/policies.go:575 +0x52
github.com/gocql/gocql.(*queryExecutor).do(0xc00007edc0, 0x7b11e0, 0xc000088010, 0x7b4540, 0xc0002961c0, 0x5b)
        /home/scylla-test/go/src/github.com/gocql/gocql/query_executor.go:87 +0x63
github.com/gocql/gocql.(*queryExecutor).executeQuery(0xc00007edc0, 0x7b4540, 0xc0002961c0, 0x0, 0x0, 0x0)
        /home/scylla-test/go/src/github.com/gocql/gocql/query_executor.go:60 +0x437
github.com/gocql/gocql.(*Session).executeBatch(0xc000077500, 0xc0002961c0, 0x1bd5473be6a)
        /home/scylla-test/go/src/github.com/gocql/gocql/session.go:642 +0xbc
github.com/gocql/gocql.(*Session).ExecuteBatch(0xc000077500, 0xc0002961c0, 0x984f60, 0xc000248920)
        /home/scylla-test/go/src/github.com/gocql/gocql/session.go:653 +0x39
main.DoBatchedWrites.func1(0xc00001d9a0, 0x99ae0100, 0x984f60, 0x97b8e0)
        /home/scylla-test/go/src/github.com/scylladb/scylla-bench/modes.go:453 +0x518
main.RunTest(0xc0001cfa40, 0x7b2480, 0xc00001aba0, 0x7ae940, 0xc0002a4cc0, 0xc000227ea0)
        /home/scylla-test/go/src/github.com/scylladb/scylla-bench/modes.go:268 +0x10c
main.DoBatchedWrites(0xc000077500, 0xc0001cfa40, 0x7b2480, 0xc00001aba0, 0x7ae940, 0xc0002a4cc0)
        /home/scylla-test/go/src/github.com/scylladb/scylla-bench/modes.go:440 +0x179
main.main.func4(0x6, 0xc0001cfa40, 0x7ae940, 0xc0002a4cc0)
        /home/scylla-test/go/src/github.com/scylladb/scylla-bench/main.go:440 +0x145
main.RunConcurrently.func1(0xc0002554f0, 0xc0002a4b40, 0xc0002f6000, 0x7, 0x7, 0xc0002554e8, 0x6)
        /home/scylla-test/go/src/github.com/scylladb/scylla-bench/modes.go:158 +0x73
created by main.RunConcurrently
        /home/scylla-test/go/src/github.com/scylladb/scylla-bench/modes.go:156 +0x203

```

**Comment by fruch** [comment]
Solved in https://github.com/scylladb/scylla-bench/pull/35
