### ISSUE TITLE
Failed to download scylla-manager-agent packages from private repos

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla-cluster-tests#2195]
### Prerequisites

* [ ] Are you rebased to master ?
* [ ] Is it reproducible ?
* [ ] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: branch-4.1
* **scylla**: scylla 4.1.rc1

### Logs
* test_id: a34877ab-c30d-4c73-a671-1c4c0fa93167
* job log: 
- db log: https://cloudius-jenkins-test.s3.amazonaws.com/a34877ab-c30d-4c73-a671-1c4c0fa93167/20200527_103428/db-cluster-a34877ab.zip
- sct log: https://cloudius-jenkins-test.s3.amazonaws.com/a34877ab-c30d-4c73-a671-1c4c0fa93167/20200527_103428/sct-runner-a34877ab.zip

```
Restore Monitor Stack command: $ hydra investigate show-monitor a34877ab-c30d-4c73-a671-1c4c0fa93167
Show all stored logs command: $ hydra investigate show-logs a34877ab-c30d-4c73-a671-1c4c0fa93167
```

### Description

The install fail might be caused by network problem or AWS service problem, we have to workaround it by updating the repo cache before installation, and retry in fail.

```
CRITICAL - [1]
2020-05-27 10:33:04.026: (TestFrameworkEvent Severity.CRITICAL), source=LongevityTest.SetUp() 

exception=Traceback (most recent call last):

  File "/sct/sdcm/tester.py", line 350, in setUp

    self.init_nodes(db_cluster=self.db_cluster)

  File "/sct/sdcm/tester.py", line 325, in init_nodes

    db_cluster.wait_for_init(node_list=db_cluster.non_seed_nodes)

  File "/sct/sdcm/cluster.py", line 2855, in wrapper

    raise NodeSetupFailed(node=node, error_msg=setup_exception[0], traceback_str=setup_exception[1])

sdcm.cluster.NodeSetupFailed: [Node longevity-counters-multidc-4-1-db-node-a34877ab-3 [52.215.255.126 | 10.0.40.233] (seed: False)] NodeSetupFailed: Encountered a bad command exit code!

Command: 'sudo bash -cxe "\nyum install -y scylla-manager-agent\nsed -i \'s/# auth_token:.*$/auth_token: a34877ab-c30d-4c73-a671-1c4c0fa93167/\' /etc/scylla-manager-agent/scylla-manager-agent.yaml\nscyllamgr_ssl_cert_gen\nsed -i \'s/#tls_cert_file/tls_cert_file/\' /etc/scylla-manager-agent/scylla-manager-agent.yaml\nsed -i \'s/#tls_key_file/tls_key_file/\' /etc/scylla-manager-agent/scylla-manager-agent.yaml\nsed -i \'s/#prometheus: .*/prometheus: :5090/\' /etc/scylla-manager-agent/scylla-manager-agent.yaml\nsystemctl restart scylla-manager-agent\nsystemctl enable scylla-manager-agent\n"'

Exit code: 1

Stdout:

Installing:

 scylla-manager-agent x86_64 2.0.2-0.20200401.ab6c6b96 scylla-manager-2.0 6.4 M

Transaction Summary

================================================================================

Install  1 Package

Total download size: 6.4 M

Installed size: 29 M

Downloading packages:

Stderr:

+ yum install -y scylla-manager-agent

https://repositories.scylladb.com/scylla/downloads/scylladb/qa-test/scylla-manager/rpm/centos/scylladb-manager-2.0/7/x86_64/scylla-manager-agent-2.0.2-0.20200401.ab6c6b96.x86_64.rpm: [Errno 14] HTTPS Error 302 - Found

Trying other mirror.

Error downloading packages:

  scylla-manager-agent-2.0.2-0.20200401.ab6c6b96.x86_64: [Errno 256] No more mirrors to try.

Traceback (most recent call last):

  File "/sct/sdcm/cluster.py", line 2834, in node_setup

    cl_inst.node_setup(_node, **setup_kwargs)

  File "/sct/sdcm/cluster.py", line 3348, in node_setup

    node.install_manager_agent(package_path=pkg_path)

  File "/sct/sdcm/cluster.py", line 1808, in install_manager_agent

    self.remoter.run('sudo bash -cxe "%s"' % install_and_config_agent_command)

  File "/sct/sdcm/utils/decorators.py", line 123, in inner

    return func(*args, **kwargs)

  File "/sct/sdcm/remote.py", line 333, in run

    result = _run()

  File "/sct/sdcm/utils/decorators.py", line 118, in inner

    return func(*args, **kwargs)

  File "/sct/sdcm/remote.py", line 318, in _run

    result = self.connection.run(**command_kwargs)

  File "<decorator-gen-3>", line 2, in run

  File "/usr/local/lib/python3.6/site-packages/fabric/connection.py", line 30, in opens

    return method(self, *args, **kwargs)

  File "/usr/local/lib/python3.6/site-packages/fabric/connection.py", line 721, in run

    return self._run(self._remote_runner(), command, **kwargs)

  File "/usr/local/lib/python3.6/site-packages/invoke/context.py", line 101, in _run

    return runner.run(command, **kwargs)

  File "/usr/local/lib/python3.6/site-packages/invoke/runners.py", line 291, in run

    return self._run_body(command, **kwargs)

  File "/usr/local/lib/python3.6/site-packages/invoke/runners.py", line 442, in _run_body

    raise UnexpectedExit(result)

invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!

Command: 'sudo bash -cxe "\nyum install -y scylla-manager-agent\nsed -i \'s/# auth_token:.*$/auth_token: a34877ab-c30d-4c73-a671-1c4c0fa93167/\' /etc/scylla-manager-agent/scylla-manager-agent.yaml\nscyllamgr_ssl_cert_gen\nsed -i \'s/#tls_cert_file/tls_cert_file/\' /etc/scylla-manager-agent/scylla-manager-agent.yaml\nsed -i \'s/#tls_key_file/tls_key_file/\' /etc/scylla-manager-agent/scylla-manager-agent.yaml\nsed -i \'s/#prometheus: .*/prometheus: :5090/\' /etc/scylla-manager-agent/scylla-manager-agent.yaml\nsystemctl restart scylla-manager-agent\nsystemctl enable scylla-manager-agent\n"'

Exit code: 1

Stdout:

Installing:

 scylla-manager-agent x86_64 2.0.2-0.20200401.ab6c6b96 scylla-manager-2.0 6.4 M

Transaction Summary

================================================================================

Install  1 Package

Total download size: 6.4 M

Installed size: 29 M

Downloading packages:

Stderr:

+ yum install -y scylla-manager-agent

https://repositories.scylladb.com/scylla/downloads/scylladb/qa-test/scylla-manager/rpm/centos/scylladb-manager-2.0/7/x86_64/scylla-manager-agent-2.0.2-0.20200401.ab6c6b96.x86_64.rpm: [Errno 14] HTTPS Error 302 - Found

Trying other mirror.

Error downloading packages:

  scylla-manager-agent-2.0.2-0.20200401.ab6c6b96.x86_64: [Errno 256] No more mirrors to try.
```

### Steps to Reproduce

1. We install scylla-manager-agent for each db node

**Expected behavior:** [What you expected to happen]

scylla-manager-agent package can be installed successfully.

**Actual behavior:** [What actually happened]

scylla-manager-agent package failed to be installed for some reason.

Maybe network problem, or aws service problem.

**Comment by roydahan** [comment]
@ShlomiBalalis what is the issue here?
