### ISSUE TITLE
loader/monitor setup failed: HTTPS Error 404 - Not Found from downloads.docker.com

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla-cluster-tests#2202]
### Prerequisites

* [ ] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: branch-perf-v8

### Logs
* test_id: `c05cb6b8-eb36-483c-8888-189e9ea25490`,  `d8d88206-2706-4682-b8ed-1defe213c3b8` and `505b7f16-0e54-4ae1-90c2-fdceddfd2414`

### Description

during the setup stage of scylla-master-perf-regression-aws-test-latency and scylla-master-perf-regression-aws-test-throughput, the setup of the loader and monitor, respectively, failed due to the same error:
```
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR > Traceback (most recent call last):
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR >   File "/sct/sdcm/cluster.py", line 2807, in node_setup
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR >     cl_inst.node_setup(node, **setup_kwargs)
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR >   File "/sct/sdcm/cluster.py", line 3902, in node_setup
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR >     self.install_scylla_monitoring(node)
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR >   File "/sct/sdcm/utils/common.py", line 218, in inner
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR >     res = func(*args, **kwargs)
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR >   File "/sct/sdcm/cluster.py", line 4227, in install_scylla_monitoring
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR >     self.install_scylla_monitoring_prereqs(node)
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR >   File "/sct/sdcm/cluster.py", line 4027, in install_scylla_monitoring_prereqs
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR >     node.remoter.run(cmd="sudo bash -ce '%s'" % prereqs_script)
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR >   File "/sct/sdcm/utils/common.py", line 175, in inner
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR >     return func(*args, **kwargs)
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR >   File "/sct/sdcm/remote.py", line 325, in run
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR >     result = _run()
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR >   File "/sct/sdcm/utils/common.py", line 170, in inner
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR >     return func(*args, **kwargs)
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR >   File "/sct/sdcm/remote.py", line 310, in _run
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR >     result = self.connection.run(**command_kwargs)
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR >   File "<decorator-gen-3>", line 2, in run
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR >   File "/usr/local/lib/python3.6/site-packages/fabric/connection.py", line 30, in opens
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR >     return method(self, *args, **kwargs)
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR >   File "/usr/local/lib/python3.6/site-packages/fabric/connection.py", line 721, in run
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR >     return self._run(self._remote_runner(), command, **kwargs)
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR >   File "/usr/local/lib/python3.6/site-packages/invoke/context.py", line 101, in _run
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR >     return runner.run(command, **kwargs)
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR >   File "/usr/local/lib/python3.6/site-packages/invoke/runners.py", line 291, in run
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR >     return self._run_body(command, **kwargs)
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR >   File "/usr/local/lib/python3.6/site-packages/invoke/runners.py", line 442, in _run_body
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR >     raise UnexpectedExit(result)
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR > invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR > 
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR > Command: "sudo bash -ce '\nyum install -y unzip wget\nyum install -y python36\nyum install -y python36-pip\npython3 -m pip install --upgrade pip\npython3 -m pip install pyyaml\ncurl -fsSL get.docker.com -o get-docker.sh\nsh get-docker.sh\nsystemctl start docker\n'"
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR > 
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR > Exit code: 1
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR > 
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR > Stdout:
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR > 
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR > Loaded plugins: fastestmirror
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR > adding repo from: https://download.docker.com/linux/centos/docker-ce.repo
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR > grabbing file https://download.docker.com/linux/centos/docker-ce.repo to /etc/yum.repos.d/docker-ce.repo
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR > repo saved to /etc/yum.repos.d/docker-ce.repo
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR > Loaded plugins: fastestmirror
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR > Loading mirror speeds from cached hostfile
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR >  * base: d36uatko69830t.cloudfront.net
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR >  * epel: fedora-epel.mirrors.tds.net
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR >  * extras: d36uatko69830t.cloudfront.net
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR >  * updates: d36uatko69830t.cloudfront.net
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR > 
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR > Stderr:
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR > 
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR >      5. Configure the failing repository to be skipped, if it is unavailable.
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR >         Note that yum will try to contact the repo. when it runs most commands,
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR >         so will have to try and fail each time (and thus. yum will be be much
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR >         slower). If it is a very temporary problem though, this is often a nice
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR >         compromise:
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR > 
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR >             yum-config-manager --save --setopt=docker-ce-stable.skip_if_unavailable=true
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR > 
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR > failure: repodata/a4074fad4307c3d0ce7a51628f53e4b227a531f248147406ec055e85e6bd9e82-primary.sqlite.bz2 from docker-ce-stable: [Errno 256] No more mirrors to try.
< t:2020-05-29 03:13:32,847 f:cluster.py      l:2809 c:sdcm.cluster         p:ERROR > https://download.docker.com/linux/centos/7/x86_64/stable/repodata/a4074fad4307c3d0ce7a51628f53e4b227a531f248147406ec055e85e6bd9e82-primary.sqlite.bz2: [Errno 14] HTTPS Error 404 - Not Found
```
It's seem that the required file does not exist anymore in https://download.docker.com/linux/centos/7/x86_64/stable/repodata/
Is there any replacement?

**Comment by fruch** [comment]
this is the formal why of getting docker, I guess it's a temporary issue.

no point of doing anything with it, in less is starts happening too often it

**Comment by roydahan** [comment]
Did they change repo or something?
If it's temporary rare issue, we can ignore if it happens again we can add a retry.

**Comment by ShlomiBalalis** [comment]
@roydahan I've never seen that happen again, and since no one else ever commented about it I assume no one else ever saw it either. I believe we can close it.
