### ISSUE TITLE
Refresh nemesis failing on wrong hash for downloaded file

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#2213]
### Prerequisites

* [x] Are you rebased to master ?
* [ ] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: branch-4.1
* **scylla**: branch-4.1

### Logs
* test_id: 6268fcf8-4171-4c08-8f0f-8b252ffe9c1f
* job log: https://jenkins.scylladb.com/job/scylla-4.1/job/longevity/job/longevity-alternator-3h-test/6/artifact/scylla-cluster-tests/latest/

### Description

Refresh nemesis failing on wrong hash for downloaded file:
```
< t:2020-06-02 22:03:56,775 f:nemesis.py      l:2033 c:sdcm.nemesis         p:ERROR > Traceback (most recent call last):
< t:2020-06-02 22:03:56,775 f:nemesis.py      l:2033 c:sdcm.nemesis         p:ERROR >   File "/sct/sdcm/nemesis.py", line 2023, in wrapper
< t:2020-06-02 22:03:56,775 f:nemesis.py      l:2033 c:sdcm.nemesis         p:ERROR >     result = method(*args, **kwargs)
< t:2020-06-02 22:03:56,775 f:nemesis.py      l:2033 c:sdcm.nemesis         p:ERROR >   File "/sct/sdcm/nemesis.py", line 2255, in disrupt
< t:2020-06-02 22:03:56,775 f:nemesis.py      l:2033 c:sdcm.nemesis         p:ERROR >     self.call_random_disrupt_method()
< t:2020-06-02 22:03:56,775 f:nemesis.py      l:2033 c:sdcm.nemesis         p:ERROR >   File "/sct/sdcm/nemesis.py", line 664, in call_random_disrupt_method
< t:2020-06-02 22:03:56,775 f:nemesis.py      l:2033 c:sdcm.nemesis         p:ERROR >     disrupt_method()
< t:2020-06-02 22:03:56,775 f:nemesis.py      l:2033 c:sdcm.nemesis         p:ERROR >   File "/sct/sdcm/nemesis.py", line 543, in disrupt_nodetool_refresh
< t:2020-06-02 22:03:56,775 f:nemesis.py      l:2033 c:sdcm.nemesis         p:ERROR >     user_agent=creds['user_agent'])
< t:2020-06-02 22:03:56,775 f:nemesis.py      l:2033 c:sdcm.nemesis         p:ERROR >   File "/sct/sdcm/utils/common.py", line 93, in remote_get_file
< t:2020-06-02 22:03:56,775 f:nemesis.py      l:2033 c:sdcm.nemesis         p:ERROR >     assert _remote_get_hash(remoter, dst) == hash_expected
< t:2020-06-02 22:03:56,775 f:nemesis.py      l:2033 c:sdcm.nemesis         p:ERROR > AssertionError
```

**Comment by amoskong** [comment]
It's an env problem (permission denied)
I had fixed the problem.

**Comment by amoskong** [comment]
I added a single policy for new sstable files.
```
        {
            "Sid": "allow-user-agent",
            "Effect": "Allow",
            "Principal": "*",
            "NotAction": "s3:PutObject",
            "Resource": "arn:aws:s3:::scylla-qa-team/refresh_nemesis/*",
            "Condition": {
                "StringEquals": {
                    "aws:UserAgent": "xxxxxxx"
                }
            }
        }
```
