### ISSUE TITLE
Running SCT with non-AWS backend tries to login to AWS

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylla-cluster-tests#2225]
```bash
./sct.py run-test longevity_test.LongevityTest.test_custom_time --backend docker --config cfg.yaml
```

result:
```
Traceback (most recent call last):
  File "./sct.py", line 15, in <module>
    from sdcm.results_analyze import PerformanceResultsAnalyzer
  File "/home/kbraun/dev/scylla-cluster-tests/sdcm/results_analyze/__init__.py", line 15, in <module>
    from sdcm.db_stats import TestStatsMixin
  File "/home/kbraun/dev/scylla-cluster-tests/sdcm/db_stats.py", line 17, in <module>
    from sdcm.utils.common import get_job_name, remove_comments, normalize_ipv6_url
  File "/home/kbraun/dev/scylla-cluster-tests/sdcm/utils/common.py", line 299, in <module>
    AWS_REGIONS = all_aws_regions()
  File "/home/kbraun/dev/scylla-cluster-tests/sdcm/utils/common.py", line 296, in all_aws_regions
    return [region['RegionName'] for region in client.describe_regions()['Regions']]
  File "/home/kbraun/.local/lib/python3.8/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/kbraun/.local/lib/python3.8/site-packages/botocore/client.py", line 621, in _make_api_call
    http, parsed_response = self._make_request(
  File "/home/kbraun/.local/lib/python3.8/site-packages/botocore/client.py", line 641, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/home/kbraun/.local/lib/python3.8/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/kbraun/.local/lib/python3.8/site-packages/botocore/endpoint.py", line 132, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/home/kbraun/.local/lib/python3.8/site-packages/botocore/endpoint.py", line 115, in create_request
    self._event_emitter.emit(event_name, request=request,
  File "/home/kbraun/.local/lib/python3.8/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/kbraun/.local/lib/python3.8/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/home/kbraun/.local/lib/python3.8/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/home/kbraun/.local/lib/python3.8/site-packages/botocore/signers.py", line 90, in handler
    return self.sign(operation_name, request)
  File "/home/kbraun/.local/lib/python3.8/site-packages/botocore/signers.py", line 160, in sign
    auth.add_auth(request)
  File "/home/kbraun/.local/lib/python3.8/site-packages/botocore/auth.py", line 357, in add_auth
    raise NoCredentialsError
botocore.exceptions.NoCredentialsError: Unable to locate credentials
```

Reason: importing `sdcm.utils.common` tries to login to AWS due to the following top-level definition in sdcm/utils/common.py:
```
AWS_REGIONS = all_aws_regions()
```

Importing modules **should not have side-effects**! That's bad programming practice. It should especially not try to establish any network connections.
Some good discussion on this topic: https://news.ycombinator.com/item?id=7536246

**Comment by bentsi** [comment]
I agree that Importing modules shouldn't have side effects but this error is related to misconfigured environment, you need to have the AWS credentials configured as explained in the Readme.

**Comment by kbr-scylla** [comment]
Reopening. Apparently there was a regression and running with docker backend again requires logging in to AWS.

Maybe SCT should have a regression test to prevent this from happening, e.g. a test that runs an empty test with empty cluster on docker backend without any AWS configuration in the environment.
