### ISSUE TITLE
Docker port command fails: client version 1.40 is too new

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla-cluster-tests#2230]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: 51df1d5d782a305680cf288c01154d6e955cf121
* **scylla**: [branch or commit hash]
* **Docker version**:
```
Client:
 Version:           18.09.8
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        0dd43dd87f
 Built:             Wed Jul 17 17:40:31 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.8
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       0dd43dd
  Built:            Wed Jul 17 17:10:42 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

### Logs
* test_id: 04be2f0a-db73-48ef-a719-0bc647d6feaf

### Description

For the last week, perf regression tests that ran on **us-builder-3** failed due an error in the start_rsyslog function:
```
< t:2020-06-05 03:01:22,680 f:remote.py       l:184  c:sdcm.remote          p:DEBUG > LocalCmdRunner [jenkins@aws-us-builder3]: Running command "docker port 2125c1d0088af24a6f52d0bb226c69531deb47feca8615df2f13a600c5c12ce8 514"...
< t:2020-06-05 03:01:22,730 f:remote.py       l:725  c:sdcm.remote          p:INFO  > LocalCmdRunner [jenkins@aws-us-builder3]: Error response from daemon: client version 1.40 is too new. Maximum supported API version is 1.39
< t:2020-06-05 03:01:22,737 f:remote.py       l:156  c:sdcm.remote          p:ERROR > LocalCmdRunner [jenkins@aws-us-builder3]: Error executing command: "docker port 2125c1d0088af24a6f52d0bb226c69531deb47feca8615df2f13a600c5c12ce8 514"; Exit status: 1
< t:2020-06-05 03:01:22,738 f:remote.py       l:160  c:sdcm.remote          p:DEBUG > LocalCmdRunner [jenkins@aws-us-builder3]: STDERR: Error response from daemon: client version 1.40 is too new. Maximum supported API version is 1.39

< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR > Uncaught exception < t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR > Uncaught exception
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR > Traceback (most recent call last):
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "./sct.py", line 490, in <module>
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     cli()
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 764, in __call__
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     return self.main(*args, **kwargs)
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 717, in main
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     rv = self.invoke(ctx)
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 1137, in invoke
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     return _process_result(sub_ctx.command.invoke(sub_ctx))
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 956, in invoke
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     return ctx.invoke(self.callback, **ctx.params)
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 555, in invoke
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     return callback(*args, **kwargs)
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "./sct.py", line 422, in run_test
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     failfast=False, buffer=False, catchbreak=True)
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/usr/lib64/python3.6/unittest/main.py", line 94, in __init__
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     self.parseArgs(argv)
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/usr/lib64/python3.6/unittest/main.py", line 141, in parseArgs
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     self.createTests()
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/usr/lib64/python3.6/unittest/main.py", line 148, in createTests
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     self.module)
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/usr/lib64/python3.6/unittest/loader.py", line 219, in loadTestsFromNames
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     suites = [self.loadTestsFromName(name, module) for name in names]
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/usr/lib64/python3.6/unittest/loader.py", line 219, in <listcomp>
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     suites = [self.loadTestsFromName(name, module) for name in names]
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/usr/lib64/python3.6/unittest/loader.py", line 197, in loadTestsFromName
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     inst = parent(name)
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/sct/sdcm/tester.py", line 196, in __init__
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     cluster.Setup.configure_rsyslog(enable_ngrok=False)
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/sct/sdcm/cluster.py", line 195, in configure_rsyslog
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     port = start_rsyslog(cls.test_id(), cls.logdir())
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/sct/sdcm/rsyslog_daemon.py", line 112, in start_rsyslog
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     res = local_runner.run('docker port {0} 514'.format(RSYSLOG_DOCKER_ID))
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/sct/sdcm/remote.py", line 209, in run
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     result = _run()
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/sct/sdcm/utils/common.py", line 170, in inner
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     return func(*args, **kwargs)
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/sct/sdcm/remote.py", line 199, in _run
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     result = self.connection.local(**command_kwargs)
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/usr/local/lib/python3.6/site-packages/fabric/connection.py", line 748, in local
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     return super(Connection, self).run(*args, **kwargs)
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/usr/local/lib/python3.6/site-packages/invoke/context.py", line 94, in run
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     return self._run(runner, command, **kwargs)
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/usr/local/lib/python3.6/site-packages/invoke/context.py", line 101, in _run
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     return runner.run(command, **kwargs)
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/usr/local/lib/python3.6/site-packages/invoke/runners.py", line 291, in run
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     return self._run_body(command, **kwargs)
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/usr/local/lib/python3.6/site-packages/invoke/runners.py", line 442, in _run_body
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     raise UnexpectedExit(result)
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR > invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR > 
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR > Command: 'docker port 2125c1d0088af24a6f52d0bb226c69531deb47feca8615df2f13a600c5c12ce8 514'
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR > 
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR > Exit code: 1
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR > 
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR > Stdout:
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR > 
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR > 
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR > 
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR > Stderr:
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR > 
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR > Error response from daemon: client version 1.40 is too new. Maximum supported API version is 1.39
< t:2020-06-05 03:01:22,738 f:log.py          l:20   c:sdcm.utils.log       p:ERROR > 
< t:2020-06-05 03:01:22,743 f:config.py       l:273  c:fabric               p:DEBUG > File not found, skipping
< t:2020-06-05 03:01:22,744 f:config.py       l:271  c:fabric               p:DEBUG > Loaded 2 new ssh_config rules from '/etc/ssh/ssh_config'
< t:2020-06-05 03:01:22,745 f:remote.py       l:184  c:sdcm.remote          p:DEBUG > LocalCmdRunner [jenkins@aws-us-builder3]: Running command "docker kill 2125c1d0088af24a6f52d0bb226c69531deb47feca8615df2f13a600c5c12ce8"...
< t:2020-06-05 03:01:22,795 f:remote.py       l:725  c:sdcm.remote          p:INFO  > LocalCmdRunner [jenkins@aws-us-builder3]: Error response from daemon: client version 1.40 is too new. Maximum supported API version is 1.39
```

At which point, the test fails. This happens every time the throughput test ran on builder 3 in the last week.

**Comment by roydahan** [comment]
@bentsi can you please look on this or have someone to look on this?
I think it happens only on older branches like performance, but we must fix it.

**Comment by bentsi** [comment]
it happened since the Hydra docker built with newer version of Docker inside (we install Docker inside Docker) and on the builder, we have old Docker from `Jul 17 17:40:31 2019` installed. Some of the builders have update the Docker version hence this doesn't fail always. I will upgrade all the builders to the newest Docker.
Regarding old perf branches that build Docker image, they will be built with the newest Docker version.

**Comment by bentsi** [comment]
updated Docker on all builders:
```
bentsi@bentsi-G3-3590:~/devel/scylladb$ run_on_builders "docker --version" | grep -v Stderr
[1] 15:43:38 [SUCCESS] jenkins@aws-eu-builder-8
Docker version 19.03.6, build 369ce74a3c
[2] 15:43:38 [SUCCESS] jenkins@aws-eu-builder-2
Docker version 19.03.6, build 369ce74a3c
[3] 15:43:38 [SUCCESS] jenkins@aws-eu-builder-5
Docker version 19.03.2, build 6a30dfc
[4] 15:43:38 [SUCCESS] jenkins@aws-eu-builder-3
Docker version 19.03.11, build 42e35e61f3
[5] 15:43:38 [SUCCESS] jenkins@aws-eu-builder-1
Docker version 19.03.11, build 42e35e61f3
[6] 15:43:38 [SUCCESS] jenkins@aws-eu-builder-7
Docker version 19.03.6, build 369ce74a3c
[7] 15:43:38 [SUCCESS] jenkins@aws-eu-builder-6
Docker version 19.03.2, build 6a30dfc
[8] 15:43:38 [SUCCESS] jenkins@aws-eu-builder-4
Docker version 19.03.6, build 369ce74a3c
[9] 15:43:39 [SUCCESS] scylla-test@gce-builder-4
Docker version 19.03.11, build 42e35e61f3
[10] 15:43:39 [SUCCESS] jenkins@aws-builder-4
Docker version 19.03.11, build 42e35e61f3
[11] 15:43:39 [SUCCESS] scylla-test@gce-builder-1
Docker version 19.03.11, build 42e35e61f3
[12] 15:43:40 [SUCCESS] scylla-test@gce-builder-3
Docker version 19.03.8, build afacb8b
[13] 15:43:40 [SUCCESS] scylla-test@gce-builder-2
Docker version 19.03.11, build 42e35e61f3
[14] 15:43:41 [SUCCESS] jenkins@aws-builder-3
Docker version 19.03.11, build 42e35e61f3
[15] 15:43:41 [SUCCESS] jenkins@aws-builder-1
Docker version 19.03.5, build 633a0ea
[16] 15:43:42 [SUCCESS] jenkins@aws-builder-5
Docker version 19.03.8, build afacb8b
[17] 15:43:42 [SUCCESS] jenkins@aws-builder-2
Docker version 19.03.5, build 633a0ea

```
