### ISSUE TITLE
`TypeError: cql_connection_exclusive() got an unexpected keyword argument 'timeout'`

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylla-cluster-tests#2249]
```
    def cql_connection_patient_exclusive(self, node, keyspace=None,  # pylint: disable=invalid-name,too-many-arguments,unused-argument
                                         user=None, password=None, timeout=30,
                                         compression=True,
                                         protocol_version=None,
                                         port=None, ssl_opts=None, connect_timeout=100, verbose=True):
        """
        Returns a connection after it stops throwing NoHostAvailables.

        If the timeout is exceeded, the exception is raised.
        """
        # pylint: disable=unused-argument
        kwargs = locals()
        del kwargs["self"]
        return self.cql_connection_exclusive(**kwargs)
```

```
    def cql_connection_exclusive(self, node, keyspace=None, user=None,  # pylint: disable=too-many-arguments
                                 password=None, compression=True,
                                 protocol_version=None, port=None,
                                 ssl_opts=None, connect_timeout=100, verbose=True):

        wlrr = WhiteListRoundRobinPolicy([node.external_address])
        return self._create_session(node, keyspace, user, password,
                                    compression, protocol_version, wlrr,
                                    port=port, ssl_opts=ssl_opts, node_ips=[node.external_address],
                                    connect_timeout=connect_timeout, verbose=verbose)
```

result:
```
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kbraun/dev/scylla-cluster-tests/bootstrap.py", line 23, in test_bootstrap
    with self.cql_connection_patient_exclusive(node=self.db_cluster.nodes[0]) as sess:
  File "/home/kbraun/dev/scylla-cluster-tests/sdcm/utils/decorators.py", line 123, in inner
    return func(*args, **kwargs)
  File "/home/kbraun/dev/scylla-cluster-tests/sdcm/tester.py", line 1195, in cql_connection_patient_exclusive
    return self.cql_connection_exclusive(**kwargs)
TypeError: cql_connection_exclusive() got an unexpected keyword argument 'timeout'

----------------------------------------------------------------------
```

Indeed, `cql_connection_exclusive` does not take a `timeout` argument.

Interestingly, there are existing tests which use this function:
```
[kbraun@localhost scylla-cluster-tests]$ git grep "connection.*exclusive"
performance_regression_test.py:        with self.cql_connection_patient_exclusive(self.db_cluster.nodes[0], timeout=60) as session:
performance_regression_test.py:                with self.cql_connection_patient_exclusive(self.db_cluster.nodes[0], timeout=60) as session:
...
snitch_test.py:        with self.cql_connection_patient_exclusive(self.db_cluster.nodes[0], timeout=60) as session:
```
dead code?

**Comment by kbr-** [comment]
also...
```
        kwargs = locals()
        del kwargs["self"]
        return self.cql_connection_exclusive(**kwargs)
```
WHY would anyone create such a monster? Have mercy!
