### ISSUE TITLE
Starting Scylla on newly bootstrapped node fails: "control process exited"

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylla-cluster-tests#2372]
After some recent changes to master, my test (https://github.com/scylladb/scylla-cluster-tests/pull/2283/) fails at this part:
```
        self.log.info('Bootstrapping a new node...')
        new_node = self.db_cluster.add_nodes(count=1, enable_auto_bootstrap=True)[0]
        self.log.info('Waiting for new node to finish initializing...')
        self.db_cluster.wait_for_init(node_list=[new_node])
        self.monitors.reconfigure_scylla_monitoring()
```

Here's some relevant output from the test log:
```
12:49:36  < t:2020-07-13 10:49:36,412 f:tester.py       l:1735 c:CDCReplicationTest   p:INFO  > Resources will continue to run
12:49:36  < t:2020-07-13 10:49:36,411 f:sct_events.py   l:907  c:sdcm.sct_events      p:INFO  > 2020-07-13 10:49:36.397: (TestFrameworkEvent Severity.ERROR), source=CDCReplicationTest.test_replication (cdc_replication_test.CDCReplicationTest)() message=Traceback (most recent call last):
12:49:36  < t:2020-07-13 10:49:36,411 f:sct_events.py   l:907  c:sdcm.sct_events      p:INFO  >   File "/home/jenkins/workspace/sct-pip/scylla-cluster-tests/cdc_replication_test.py", line 160, in test_replication
12:49:36  < t:2020-07-13 10:49:36,411 f:sct_events.py   l:907  c:sdcm.sct_events      p:INFO  >     self.db_cluster.wait_for_init(node_list=[new_node])
12:49:36  < t:2020-07-13 10:49:36,411 f:sct_events.py   l:907  c:sdcm.sct_events      p:INFO  >   File "/home/jenkins/workspace/sct-pip/scylla-cluster-tests/sdcm/cluster.py", line 2980, in wrapper
12:49:36  < t:2020-07-13 10:49:36,411 f:sct_events.py   l:907  c:sdcm.sct_events      p:INFO  >     verify_node_setup(start_time)
12:49:36  < t:2020-07-13 10:49:36,411 f:sct_events.py   l:907  c:sdcm.sct_events      p:INFO  >   File "/home/jenkins/workspace/sct-pip/scylla-cluster-tests/sdcm/cluster.py", line 2956, in verify_node_setup
12:49:36  < t:2020-07-13 10:49:36,411 f:sct_events.py   l:907  c:sdcm.sct_events      p:INFO  >     raise NodeSetupFailed(node=node, error_msg=setup_exception[0], traceback_str=setup_exception[1])
12:49:36  < t:2020-07-13 10:49:36,411 f:sct_events.py   l:907  c:sdcm.sct_events      p:INFO  > sdcm.cluster.NodeSetupFailed: [Node cdc-replication-jenkins-db-node-9270ef10-4 [52.18.136.70 | 10.0.38.183] (seed: False)] NodeSetupFailed: Encountered a bad command exit code!
12:49:36  < t:2020-07-13 10:49:36,411 f:sct_events.py   l:907  c:sdcm.sct_events      p:INFO  > 
12:49:36  < t:2020-07-13 10:49:36,411 f:sct_events.py   l:907  c:sdcm.sct_events      p:INFO  > Command: 'sudo systemctl start scylla-server.service'
12:49:36  < t:2020-07-13 10:49:36,411 f:sct_events.py   l:907  c:sdcm.sct_events      p:INFO  > 
12:49:36  < t:2020-07-13 10:49:36,411 f:sct_events.py   l:907  c:sdcm.sct_events      p:INFO  > Exit code: 1
12:49:36  < t:2020-07-13 10:49:36,411 f:sct_events.py   l:907  c:sdcm.sct_events      p:INFO  > 
12:49:36  < t:2020-07-13 10:49:36,411 f:sct_events.py   l:907  c:sdcm.sct_events      p:INFO  > Stdout:
12:49:36  < t:2020-07-13 10:49:36,411 f:sct_events.py   l:907  c:sdcm.sct_events      p:INFO  > 
12:49:36  < t:2020-07-13 10:49:36,411 f:sct_events.py   l:907  c:sdcm.sct_events      p:INFO  > 
12:49:36  < t:2020-07-13 10:49:36,411 f:sct_events.py   l:907  c:sdcm.sct_events      p:INFO  > 
12:49:36  < t:2020-07-13 10:49:36,411 f:sct_events.py   l:907  c:sdcm.sct_events      p:INFO  > Stderr:
12:49:36  < t:2020-07-13 10:49:36,411 f:sct_events.py   l:907  c:sdcm.sct_events      p:INFO  > 
12:49:36  < t:2020-07-13 10:49:36,411 f:sct_events.py   l:907  c:sdcm.sct_events      p:INFO  > Job for scylla-server.service failed because the control process exited with error code. See "systemctl status scylla-server.service" and "journalctl -xe" for details.
12:49:36  < t:2020-07-13 10:49:36,411 f:sct_events.py   l:907  c:sdcm.sct_events      p:INFO  > 
12:49:36  < t:2020-07-13 10:49:36,411 f:sct_events.py   l:907  c:sdcm.sct_events      p:INFO  > 
12:49:36  < t:2020-07-13 10:49:36,411 f:sct_events.py   l:907  c:sdcm.sct_events      p:INFO  > Traceback (most recent call last):
12:49:36  < t:2020-07-13 10:49:36,411 f:sct_events.py   l:907  c:sdcm.sct_events      p:INFO  >   File "/home/jenkins/workspace/sct-pip/scylla-cluster-tests/sdcm/cluster.py", line 2945, in node_setup
12:49:36  < t:2020-07-13 10:49:36,411 f:sct_events.py   l:907  c:sdcm.sct_events      p:INFO  >     cl_inst.node_setup(_node, **setup_kwargs)
12:49:36  < t:2020-07-13 10:49:36,411 f:sct_events.py   l:907  c:sdcm.sct_events      p:INFO  >   File "/home/jenkins/workspace/sct-pip/scylla-cluster-tests/sdcm/cluster.py", line 3491, in node_setup
12:49:36  < t:2020-07-13 10:49:36,411 f:sct_events.py   l:907  c:sdcm.sct_events      p:INFO  >     node.start_scylla_server(verify_up=False)
12:49:36  < t:2020-07-13 10:49:36,411 f:sct_events.py   l:907  c:sdcm.sct_events      p:INFO  >   File "/home/jenkins/workspace/sct-pip/scylla-cluster-tests/sdcm/cluster.py", line 2332, in start_scylla_server
12:49:36  < t:2020-07-13 10:49:36,411 f:sct_events.py   l:907  c:sdcm.sct_events      p:INFO  >     self.remoter.run('sudo systemctl start scylla-server.service', timeout=timeout)
12:49:36  < t:2020-07-13 10:49:36,411 f:sct_events.py   l:907  c:sdcm.sct_events      p:INFO  >   File "/home/jenkins/workspace/sct-pip/scylla-cluster-tests/sdcm/utils/decorators.py", line 61, in inner
12:49:36  < t:2020-07-13 10:49:36,411 f:sct_events.py   l:907  c:sdcm.sct_events      p:INFO  >     return func(*args, **kwargs)
12:49:36  < t:2020-07-13 10:49:36,411 f:sct_events.py   l:907  c:sdcm.sct_events      p:INFO  >   File "/home/jenkins/workspace/sct-pip/scylla-cluster-tests/sdcm/remote.py", line 373, in run
12:49:36  < t:2020-07-13 10:49:36,411 f:sct_events.py   l:907  c:sdcm.sct_events      p:INFO  >     result = _run()
12:49:36  < t:2020-07-13 10:49:36,411 f:sct_events.py   l:907  c:sdcm.sct_events      p:INFO  >   File "/home/jenkins/workspace/sct-pip/scylla-cluster-tests/sdcm/utils/decorators.py", line 56, in inner
12:49:36  < t:2020-07-13 10:49:36,411 f:sct_events.py   l:907  c:sdcm.sct_events      p:INFO  >     return func(*args, **kwargs)
12:49:36  < t:2020-07-13 10:49:36,411 f:sct_events.py   l:907  c:sdcm.sct_events      p:INFO  >   File "/home/jenkins/workspace/sct-pip/scylla-cluster-tests/sdcm/remote.py", line 358, in _run
12:49:36  < t:2020-07-13 10:49:36,411 f:sct_events.py   l:907  c:sdcm.sct_events      p:INFO  >     result = self.connection.run(**command_kwargs)
12:49:36  < t:2020-07-13 10:49:36,411 f:sct_events.py   l:907  c:sdcm.sct_events      p:INFO  >   File "<decorator-gen-3>", line 2, in run
12:49:36  < t:2020-07-13 10:49:36,411 f:sct_events.py   l:907  c:sdcm.sct_events      p:INFO  >   File "/usr/local/lib/python3.8/site-packages/fabric/connection.py", line 30, in opens
12:49:36  < t:2020-07-13 10:49:36,411 f:sct_events.py   l:907  c:sdcm.sct_events      p:INFO  >     return method(self, *args, **kwargs)
12:49:36  < t:2020-07-13 10:49:36,411 f:sct_events.py   l:907  c:sdcm.sct_events      p:INFO  >   File "/usr/local/lib/python3.8/site-packages/fabric/connection.py", line 721, in run
12:49:36  < t:2020-07-13 10:49:36,411 f:sct_events.py   l:907  c:sdcm.sct_events      p:INFO  >     return self._run(self._remote_runner(), command, **kwargs)
12:49:36  < t:2020-07-13 10:49:36,411 f:sct_events.py   l:907  c:sdcm.sct_events      p:INFO  >   File "/usr/local/lib/python3.8/site-packages/invoke/context.py", line 101, in _run
12:49:36  < t:2020-07-13 10:49:36,411 f:sct_events.py   l:907  c:sdcm.sct_events      p:INFO  >     return runner.run(command, **kwargs)
12:49:36  < t:2020-07-13 10:49:36,411 f:sct_events.py   l:907  c:sdcm.sct_events      p:INFO  >   File "/usr/local/lib/python3.8/site-packages/invoke/runners.py", line 291, in run
12:49:36  < t:2020-07-13 10:49:36,411 f:sct_events.py   l:907  c:sdcm.sct_events      p:INFO  >     return self._run_body(command, **kwargs)
12:49:36  < t:2020-07-13 10:49:36,411 f:sct_events.py   l:907  c:sdcm.sct_events      p:INFO  >   File "/usr/local/lib/python3.8/site-packages/invoke/runners.py", line 442, in _run_body
12:49:36  < t:2020-07-13 10:49:36,411 f:sct_events.py   l:907  c:sdcm.sct_events      p:INFO  >     raise UnexpectedExit(result)
12:49:36  < t:2020-07-13 10:49:36,411 f:sct_events.py   l:907  c:sdcm.sct_events      p:INFO  > invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!
```

I investigated `journalctl -xe` and found this:
```
Jul 13 10:49:26 cdc-replication-jenkins-db-node-9270ef10-4 systemd[1]: Starting Scylla Server...
-- Subject: Unit scylla-server.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit scylla-server.service has begun starting up.
Jul 13 10:49:26 cdc-replication-jenkins-db-node-9270ef10-4 sshd[4882]: pam_unix(sshd:session): session closed for user centos
Jul 13 10:49:26 cdc-replication-jenkins-db-node-9270ef10-4 systemd-logind[542]: Removed session 143.
-- Subject: Session 143 has been terminated
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: http://www.freedesktop.org/wiki/Software/systemd/multiseat
-- 
-- A session with the ID 143 has been terminated.
Jul 13 10:49:26 cdc-replication-jenkins-db-node-9270ef10-4 systemd[1]: scylla-server.service: control process exited, code=exited status=1
Jul 13 10:49:27 cdc-replication-jenkins-db-node-9270ef10-4 systemd[1]: Failed to start Scylla Server.
-- Subject: Unit scylla-server.service has failed
```

When I later login to the node manually and execute `sudo systemctl start scylla-server.service`, Scylla starts without any problems.

**Comment by kbr-** [comment]
Artifacts:
[archive.zip](https://github.com/scylladb/scylla-cluster-tests/files/4911991/archive.zip)

Some relevant parts of sct.log:
```
< t:2020-07-13 10:49:24,800 f:remote.py       l:215  c:sdcm.remote          p:DEBUG > LocalCmdRunner [jenkins@localhost.localdomain]: Running command "rsync -L  --timeout=300 --rsh='/usr/bin/ssh  -a -x  -o StrictHostKeyChecking=no -o UserKnownHostsFile=/tmp/tmpfjs84n_q -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l centos -p 22 -i /home/jenkins/.ssh/scylla-qa-ec2' -az /tmp/scylla-longevitychncfmmq/scylla.yaml centos@[52.18.136.70]:"/tmp/scylla.yaml""...
< t:2020-07-13 10:49:25,749 f:remote.py       l:173  c:sdcm.remote          p:INFO  > LocalCmdRunner [jenkins@localhost.localdomain]: Command "rsync -L  --timeout=300 --rsh='/usr/bin/ssh  -a -x  -o StrictHostKeyChecking=no -o UserKnownHostsFile=/tmp/tmpfjs84n_q -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l centos -p 22 -i /home/jenkins/.ssh/scylla-qa-ec2' -az /tmp/scylla-longevitychncfmmq/scylla.yaml centos@[52.18.136.70]:"/tmp/scylla.yaml"" finished with status 0
< t:2020-07-13 10:49:25,751 f:remote.py       l:346  c:sdcm.remote          p:DEBUG > RemoteCmdRunner [centos@52.18.136.70]: Running command "sudo mv /tmp/scylla.yaml /etc/scylla/scylla.yaml"...
< t:2020-07-13 10:49:25,894 f:remote.py       l:173  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@52.18.136.70]: Command "sudo mv /tmp/scylla.yaml /etc/scylla/scylla.yaml" finished with status 0
< t:2020-07-13 10:49:25,894 f:remote.py       l:346  c:sdcm.remote          p:DEBUG > RemoteCmdRunner [centos@52.18.136.70]: Running command "sudo grep '\--blocked-reactor-notify-ms 500 --abort-on-lsa-bad-alloc 1 --abort-on-seastar-bad-alloc --abort-on-internal-error 1 --abort-on-ebadf 1 --enable-sstable-key-validation 1' /etc/sysconfig/scylla-server"...
< t:2020-07-13 10:49:26,099 f:remote.py       l:346  c:sdcm.remote          p:DEBUG > RemoteCmdRunner [centos@52.18.136.70]: Running command "sudo sed -i -e 's/SCYLLA_ARGS="/SCYLLA_ARGS="--blocked-reactor-notify-ms 500 --abort-on-lsa-bad-alloc 1 --abort-on-seastar-bad-alloc --abort-on-internal-error 1 --abort-on-ebadf 1 --enable-sstable-key-validation 1 /' /etc/sysconfig/scylla-server"...
< t:2020-07-13 10:49:26,278 f:remote.py       l:173  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@52.18.136.70]: Command "sudo sed -i -e 's/SCYLLA_ARGS="/SCYLLA_ARGS="--blocked-reactor-notify-ms 500 --abort-on-lsa-bad-alloc 1 --abort-on-seastar-bad-alloc --abort-on-internal-error 1 --abort-on-ebadf 1 --enable-sstable-key-validation 1 /' /etc/sysconfig/scylla-server" finished with status 0
< t:2020-07-13 10:49:26,279 f:remote.py       l:346  c:sdcm.remote          p:DEBUG > RemoteCmdRunner [centos@52.18.136.70]: Running command "sudo systemctl stop scylla-server.service"...
< t:2020-07-13 10:49:26,510 f:remote.py       l:173  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@52.18.136.70]: Command "sudo systemctl stop scylla-server.service" finished with status 0
< t:2020-07-13 10:49:26,511 f:remote.py       l:346  c:sdcm.remote          p:DEBUG > RemoteCmdRunner [centos@52.18.136.70]: Running command "sudo systemctl start scylla-server.service"...
< t:2020-07-13 10:49:26,760 f:remote.py       l:779  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@52.18.136.70]: Jul 13 10:49:26 cdc-replication-jenkins-db-node-9270ef10-4 systemd[1]: Starting Scylla Server...
< t:2020-07-13 10:49:26,911 f:remote.py       l:779  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@52.18.136.70]: Jul 13 10:49:26 cdc-replication-jenkins-db-node-9270ef10-4 systemd[1]: scylla-server.service: control process exited, code=exited status=1
< t:2020-07-13 10:49:27,036 f:remote.py       l:779  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@52.18.136.70]: Jul 13 10:49:27 cdc-replication-jenkins-db-node-9270ef10-4 systemd[1]: Failed to start Scylla Server.
< t:2020-07-13 10:49:27,036 f:remote.py       l:779  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@52.18.136.70]: Jul 13 10:49:27 cdc-replication-jenkins-db-node-9270ef10-4 systemd[1]: Dependency failed for Scylla JMX.
< t:2020-07-13 10:49:27,037 f:remote.py       l:779  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@52.18.136.70]: Jul 13 10:49:27 cdc-replication-jenkins-db-node-9270ef10-4 systemd[1]: Job scylla-jmx.service/start failed with result 'dependency'.
< t:2020-07-13 10:49:27,039 f:remote.py       l:779  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@52.18.136.70]: Jul 13 10:49:27 cdc-replication-jenkins-db-node-9270ef10-4 systemd[1]: Unit scylla-server.service entered failed state.
< t:2020-07-13 10:49:27,040 f:remote.py       l:779  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@52.18.136.70]: Job for scylla-server.service failed because the control process exited with error code. See "systemctl status scylla-server.service" and "journalctl -xe" for details.
< t:2020-07-13 10:49:27,041 f:remote.py       l:779  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@52.18.136.70]: Jul 13 10:49:27 cdc-replication-jenkins-db-node-9270ef10-4 systemd[1]: scylla-server.service failed.
< t:2020-07-13 10:49:27,046 f:remote.py       l:177  c:sdcm.remote          p:ERROR > RemoteCmdRunner [centos@52.18.136.70]: Error executing command: "sudo systemctl start scylla-server.service"; Exit status: 1
< t:2020-07-13 10:49:27,046 f:remote.py       l:181  c:sdcm.remote          p:DEBUG > RemoteCmdRunner [centos@52.18.136.70]: STDERR: Job for scylla-server.service failed because the control process exited with error code. See "systemctl status scylla-server.service" and "journalctl -xe" for details.

< t:2020-07-13 10:49:27,073 f:sct_events.py   l:907  c:sdcm.sct_events      p:INFO  > 2020-07-13 10:49:27.058: (InfoEvent Severity.NORMAL): message=TEST_END
< t:2020-07-13 10:49:27,074 f:tester.py       l:203  c:silence              p:DEBUG > Finished 'Sending test end event'. No errors were silenced.
< t:2020-07-13 10:49:27,074 f:tester.py       l:1782 c:CDCReplicationTest   p:INFO  > TearDown is starting...
```

**Comment by aleksbykov** [comment]
Fixed by https://github.com/scylladb/scylla-cluster-tests/pull/2382
