### ISSUE TITLE
GCE: network isn't prepared in setting collectd

### ISSUE THREAD

**Issue by kongove** [scylladb/scylla-cluster-tests#240]
```
2017-02-16 18:10:00,012 remote           L0194 DEBUG| [35.185.60.228] [stdout] Feb 16 18:10:00 info   |  [shard 2] compaction - Compacted 4 sstables to [/var/lib/scylla/data/keyspace1/standard1-698f2eb0f46e11e68fcf000000000001/keyspace1-standard1-ka-58-Data.db:level=0, ]. 596289868 bytes to 178508341 (~29% of original) in 27279ms = 6.24065MB/s. ~2122624 total partitions merged to 635261.
2017-02-16 18:10:00,856 cluster          L2370 INFO | GCE Cluster longevity-1-6-gce-scylla-db-cluster-f9485b00 | Image: centos-7 | Root Disk: pd-ssd 50 GB | Local SSD: 1 | Type: n1-highmem-8: added nodes: [<sdcm.cluster.GCENode object at 0x4ef9110>]
2017-02-16 18:10:00,857 remote           L0862 DEBUG| Remote [scylla-test@35.185.37.0]: Running 'sudo yum install -y epel-release'
2017-02-16 18:10:00,858 remote           L0094 INFO | [35.185.37.0] Running '/bin/ssh -tt -a -x  -o ControlPath=/var/tmp/ssh-master9aSJLc/socket -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmppt5hya -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l scylla-test -p 22 -i ~/.ssh/scylla-test 35.185.37.0 "sudo yum install -y epel-release"'
2017-02-16 18:10:07,896 remote           L0194 DEBUG| [35.185.37.0] [stderr] ssh: connect to host 35.185.37.0 port 22: Connection refused
2017-02-16 18:10:07,897 nemesis          L0266 ERROR| sdcm.nemesis.ChaosMonkey: Unhandled exception in method <function disrupt at 0x4bde668>
Traceback (most recent call last):
  File "/jenkins/slave/workspace/scylla-1.6-longevity-gce/label/gce/sdcm/nemesis.py", line 263, in wrapper
    result = method(*args, **kwargs)
  File "/jenkins/slave/workspace/scylla-1.6-longevity-gce/label/gce/sdcm/nemesis.py", line 332, in disrupt
    self.call_random_disrupt_method()
  File "/jenkins/slave/workspace/scylla-1.6-longevity-gce/label/gce/sdcm/nemesis.py", line 240, in call_random_disrupt_method
    disrupt_method()
  File "/jenkins/slave/workspace/scylla-1.6-longevity-gce/label/gce/sdcm/nemesis.py", line 226, in disrupt_nodetool_decommission
    self.cluster.wait_for_init(node_list=new_nodes)
  File "/jenkins/slave/workspace/scylla-1.6-longevity-gce/label/gce/sdcm/cluster.py", line 2804, in wait_for_init
    self.collectd_setup.install(node)
  File "/jenkins/slave/workspace/scylla-1.6-longevity-gce/label/gce/sdcm/collectd.py", line 429, in install
    self.node.remoter.run('sudo yum install -y epel-release')
  File "/jenkins/slave/workspace/scylla-1.6-longevity-gce/label/gce/sdcm/remote.py", line 873, in run
    watch_stdout_pattern=watch_stdout_pattern)
  File "/jenkins/slave/workspace/scylla-1.6-longevity-gce/label/gce/sdcm/remote.py", line 817, in _run
    watch_stdout_pattern=watch_stdout_pattern)
  File "/jenkins/slave/workspace/scylla-1.6-longevity-gce/label/gce/sdcm/remote.py", line 215, in ssh_run
    raise process.CmdError(cmd, sp.result)
CmdError: Command '/bin/ssh -tt -a -x  -o ControlPath=/var/tmp/ssh-master9aSJLc/socket -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmppt5hya -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l scylla-test -p 22 -i ~/.ssh/scylla-test 35.185.37.0 "sudo yum install -y epel-release"' failed (rc=255)
```
We should make sure node ssh is up before collectd_setup
```
2659 class ScyllaGCECluster(GCECluster, BaseScyllaCluster):
.....
2775     def wait_for_init(self, node_list=None, verbose=False):
......
2802         # avoid using node.remoter in thread
2803         for node in node_list:
2804             self.collectd_setup.install(node)
2805 
2806         seed = node_list[0].private_ip_address
2807         for node in node_list:
2808             setup_thread = threading.Thread(target=node_setup,
2809                                             args=(node, seed))
2810             setup_thread.daemon = True
2811             setup_thread.start()
```

**Comment by kongove** [comment]
a fix:
```
diff --git a/sdcm/cluster.py b/sdcm/cluster.py
index 3ba6dff..7446114 100644
--- a/sdcm/cluster.py
+++ b/sdcm/cluster.py
@@ -2801,6 +2801,7 @@ class ScyllaGCECluster(GCECluster, BaseScyllaCluster):
 
         # avoid using node.remoter in thread
         for node in node_list:
+            node.wait_ssh_up(verbose=verbose)
             self.collectd_setup.install(node)
 
         seed = node_list[0].private_ip_address
```
