### ISSUE TITLE
Amazon2 artifact test fails: Waiting for SSH to be up: timeout

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla-cluster-tests#2458]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master
* **scylla**: master

### Logs
* test_id: a8bd83c7-6426-42ba-b34e-48e041884c0e
* job log: https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-amazon2-test/14/

### Description

For twice in a row, the amazon linux 2 job fails on startup because it fails to connect to the db node instance for 500 seconds:
```
< t:2020-08-01 22:53:04,834 f:tester.py       l:152  c:sdcm.tester          p:ERROR > Traceback (most recent call last):
< t:2020-08-01 22:53:04,834 f:tester.py       l:152  c:sdcm.tester          p:ERROR >   File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-amazon2-test@2/scylla-cluster-tests/sdcm/wait.py", line 60, in wait_for
< t:2020-08-01 22:53:04,834 f:tester.py       l:152  c:sdcm.tester          p:ERROR >     res = retry.call(func, **kwargs)
< t:2020-08-01 22:53:04,834 f:tester.py       l:152  c:sdcm.tester          p:ERROR >   File "/usr/local/lib/python3.8/site-packages/tenacity/__init__.py", line 358, in call
< t:2020-08-01 22:53:04,834 f:tester.py       l:152  c:sdcm.tester          p:ERROR >     do = self.iter(retry_state=retry_state)
< t:2020-08-01 22:53:04,834 f:tester.py       l:152  c:sdcm.tester          p:ERROR >   File "/usr/local/lib/python3.8/site-packages/tenacity/__init__.py", line 331, in iter
< t:2020-08-01 22:53:04,834 f:tester.py       l:152  c:sdcm.tester          p:ERROR >     raise retry_exc.reraise()
< t:2020-08-01 22:53:04,834 f:tester.py       l:152  c:sdcm.tester          p:ERROR >   File "/usr/local/lib/python3.8/site-packages/tenacity/__init__.py", line 168, in reraise
< t:2020-08-01 22:53:04,834 f:tester.py       l:152  c:sdcm.tester          p:ERROR >     raise self
< t:2020-08-01 22:53:04,834 f:tester.py       l:152  c:sdcm.tester          p:ERROR > tenacity.RetryError: RetryError[<Future at 0x7f90b4f1bac0 state=finished returned bool>]
< t:2020-08-01 22:53:04,834 f:tester.py       l:152  c:sdcm.tester          p:ERROR > 
< t:2020-08-01 22:53:04,834 f:tester.py       l:152  c:sdcm.tester          p:ERROR > During handling of the above exception, another exception occurred:
< t:2020-08-01 22:53:04,834 f:tester.py       l:152  c:sdcm.tester          p:ERROR > 
< t:2020-08-01 22:53:04,834 f:tester.py       l:152  c:sdcm.tester          p:ERROR > Traceback (most recent call last):
< t:2020-08-01 22:53:04,834 f:tester.py       l:152  c:sdcm.tester          p:ERROR >   File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-amazon2-test@2/scylla-cluster-tests/sdcm/tester.py", line 145, in wrapper
< t:2020-08-01 22:53:04,834 f:tester.py       l:152  c:sdcm.tester          p:ERROR >     return method(*args, **kwargs)
< t:2020-08-01 22:53:04,834 f:tester.py       l:152  c:sdcm.tester          p:ERROR >   File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-amazon2-test@2/scylla-cluster-tests/sdcm/utils/decorators.py", line 109, in inner
< t:2020-08-01 22:53:04,834 f:tester.py       l:152  c:sdcm.tester          p:ERROR >     res = func(*args, **kwargs)
< t:2020-08-01 22:53:04,834 f:tester.py       l:152  c:sdcm.tester          p:ERROR >   File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-amazon2-test@2/scylla-cluster-tests/sdcm/tester.py", line 411, in setUp
< t:2020-08-01 22:53:04,834 f:tester.py       l:152  c:sdcm.tester          p:ERROR >     self.init_resources()
< t:2020-08-01 22:53:04,834 f:tester.py       l:152  c:sdcm.tester          p:ERROR >   File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-amazon2-test@2/scylla-cluster-tests/sdcm/tester.py", line 978, in init_resources
< t:2020-08-01 22:53:04,834 f:tester.py       l:152  c:sdcm.tester          p:ERROR >     self.get_cluster_aws(loader_info=loader_info, db_info=db_info,
< t:2020-08-01 22:53:04,834 f:tester.py       l:152  c:sdcm.tester          p:ERROR >   File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-amazon2-test@2/scylla-cluster-tests/sdcm/tester.py", line 768, in get_cluster_aws
< t:2020-08-01 22:53:04,834 f:tester.py       l:152  c:sdcm.tester          p:ERROR >     self.db_cluster = create_cluster(db_type)
< t:2020-08-01 22:53:04,834 f:tester.py       l:152  c:sdcm.tester          p:ERROR >   File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-amazon2-test@2/scylla-cluster-tests/sdcm/tester.py", line 732, in create_cluster
< t:2020-08-01 22:53:04,834 f:tester.py       l:152  c:sdcm.tester          p:ERROR >     return ScyllaAWSCluster(
< t:2020-08-01 22:53:04,834 f:tester.py       l:152  c:sdcm.tester          p:ERROR >   File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-amazon2-test@2/scylla-cluster-tests/sdcm/cluster_aws.py", line 736, in __init__
< t:2020-08-01 22:53:04,834 f:tester.py       l:152  c:sdcm.tester          p:ERROR >     super(ScyllaAWSCluster, self).__init__(ec2_ami_id=ec2_ami_id,
< t:2020-08-01 22:53:04,834 f:tester.py       l:152  c:sdcm.tester          p:ERROR >   File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-amazon2-test@2/scylla-cluster-tests/sdcm/cluster.py", line 3032, in __init__
< t:2020-08-01 22:53:04,834 f:tester.py       l:152  c:sdcm.tester          p:ERROR >     super(BaseScyllaCluster, self).__init__(*args, **kwargs)
< t:2020-08-01 22:53:04,834 f:tester.py       l:152  c:sdcm.tester          p:ERROR >   File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-amazon2-test@2/scylla-cluster-tests/sdcm/cluster_aws.py", line 83, in __init__
< t:2020-08-01 22:53:04,834 f:tester.py       l:152  c:sdcm.tester          p:ERROR >     super(AWSCluster, self).__init__(cluster_uuid=cluster_uuid,
< t:2020-08-01 22:53:04,834 f:tester.py       l:152  c:sdcm.tester          p:ERROR >   File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-amazon2-test@2/scylla-cluster-tests/sdcm/cluster.py", line 2789, in __init__
< t:2020-08-01 22:53:04,834 f:tester.py       l:152  c:sdcm.tester          p:ERROR >     self.add_nodes(num, dc_idx=dc_idx, enable_auto_bootstrap=Setup.AUTO_BOOTSTRAP)
< t:2020-08-01 22:53:04,834 f:tester.py       l:152  c:sdcm.tester          p:ERROR >   File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-amazon2-test@2/scylla-cluster-tests/sdcm/cluster_aws.py", line 773, in add_nodes
< t:2020-08-01 22:53:04,834 f:tester.py       l:152  c:sdcm.tester          p:ERROR >     added_nodes = super(ScyllaAWSCluster, self).add_nodes(count=count,
< t:2020-08-01 22:53:04,834 f:tester.py       l:152  c:sdcm.tester          p:ERROR >   File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-amazon2-test@2/scylla-cluster-tests/sdcm/cluster_aws.py", line 348, in add_nodes
< t:2020-08-01 22:53:04,834 f:tester.py       l:152  c:sdcm.tester          p:ERROR >     added_nodes = [self._create_node(instance, self._ec2_ami_username,
< t:2020-08-01 22:53:04,834 f:tester.py       l:152  c:sdcm.tester          p:ERROR >   File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-amazon2-test@2/scylla-cluster-tests/sdcm/cluster_aws.py", line 348, in <listcomp>
< t:2020-08-01 22:53:04,834 f:tester.py       l:152  c:sdcm.tester          p:ERROR >     added_nodes = [self._create_node(instance, self._ec2_ami_username,
< t:2020-08-01 22:53:04,834 f:tester.py       l:152  c:sdcm.tester          p:ERROR >   File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-amazon2-test@2/scylla-cluster-tests/sdcm/cluster_aws.py", line 369, in _create_node
< t:2020-08-01 22:53:04,834 f:tester.py       l:152  c:sdcm.tester          p:ERROR >     node.init()
< t:2020-08-01 22:53:04,834 f:tester.py       l:152  c:sdcm.tester          p:ERROR >   File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-amazon2-test@2/scylla-cluster-tests/sdcm/cluster_aws.py", line 412, in init
< t:2020-08-01 22:53:04,834 f:tester.py       l:152  c:sdcm.tester          p:ERROR >     super().init()
< t:2020-08-01 22:53:04,834 f:tester.py       l:152  c:sdcm.tester          p:ERROR >   File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-amazon2-test@2/scylla-cluster-tests/sdcm/cluster.py", line 443, in init
< t:2020-08-01 22:53:04,834 f:tester.py       l:152  c:sdcm.tester          p:ERROR >     self.wait_ssh_up(verbose=True)
< t:2020-08-01 22:53:04,834 f:tester.py       l:152  c:sdcm.tester          p:ERROR >   File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-amazon2-test@2/scylla-cluster-tests/sdcm/cluster.py", line 1220, in wait_ssh_up
< t:2020-08-01 22:53:04,834 f:tester.py       l:152  c:sdcm.tester          p:ERROR >     wait.wait_for(func=self.remoter.is_up, step=10, text=text, timeout=timeout, throw_exc=True)
< t:2020-08-01 22:53:04,834 f:tester.py       l:152  c:sdcm.tester          p:ERROR >   File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-amazon2-test@2/scylla-cluster-tests/sdcm/wait.py", line 71, in wait_for
< t:2020-08-01 22:53:04,834 f:tester.py       l:152  c:sdcm.tester          p:ERROR >     raise RetryError(err)
< t:2020-08-01 22:53:04,834 f:tester.py       l:152  c:sdcm.tester          p:ERROR > tenacity.RetryError: RetryError[Wait for: Node artifacts-amazon2-jenkins-db-node-a8bd83c7-1 [34.241.108.115 | 10.0.2.177] (seed: False): Waiting for SSH to be up: timeout - 500 seconds - expired]
```

logs:
```
+------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                          Log links for testrun with test id a8bd83c7-6426-42ba-b34e-48e041884c0e                                           |
+-----------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
| Date            | Log type   | Link                                                                                                                        |
+-----------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
| 20200801_225319 | db-cluster | https://cloudius-jenkins-test.s3.amazonaws.com/a8bd83c7-6426-42ba-b34e-48e041884c0e/20200801_225319/db-cluster-a8bd83c7.zip |
| 20200801_225319 | sct-runner | https://cloudius-jenkins-test.s3.amazonaws.com/a8bd83c7-6426-42ba-b34e-48e041884c0e/20200801_225319/sct-runner-a8bd83c7.zip |
+------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

**Comment by roydahan** [comment]
@ShlomiBalalis why do you consider it SCT issue?
What does the node do during this time?

**Comment by ShlomiBalalis** [comment]
I have no way of knowing what does the node do in the meantime, since the log that is collected is empty. Ever since the node starts, sct can't communicate with it. I don't think it's some sort of a spot/amazon error, since if it was we would see an error in the creation of of the instance, wouldn't we?

**Comment by roydahan** [comment]
You can alwasy start the AMI manually and check the systemctl status and dmseg.

**Comment by ShlomiBalalis** [comment]
It seems like it won't reoccur again, closing for now.
