### ISSUE TITLE
sdcm.remote.SSHConnectTimeoutError: [...] failed connecting to '172.30.0.160' during 60s

### ISSUE THREAD

**Issue by nizarh11** [scylladb/scylla-cluster-tests#2459]
### Prerequisites

* [ ] Are you rebased to master ?
* [ ] Is it reproducible ?
* [ ] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master
* **scylla**: master:latest

### Description

sdcm.remote.SSHConnectTimeoutError: Unable to run 'cat /etc/os-release': failed connecting to '172.30.0.160' during 60s

### Logs

```
exception=Traceback (most recent call last):
  File "/sct/sdcm/tester.py", line 256, in setUp
    self.init_resources()
  File "/sct/sdcm/tester.py", line 674, in init_resources
    monitor_info=monitor_info)
  File "/sct/sdcm/tester.py", line 572, in get_cluster_aws
    self.db_cluster = create_cluster(db_type)
  File "/sct/sdcm/tester.py", line 538, in create_cluster
    **cl_params)
  File "/sct/sdcm/cluster_aws.py", line 788, in __init__
    extra_network_interface=params.get('extra_network_interface'))
  File "/sct/sdcm/cluster.py", line 2862, in __init__
    super(BaseScyllaCluster, self).__init__(*args, **kwargs)
  File "/sct/sdcm/cluster_aws.py", line 94, in __init__
    extra_network_interface=extra_network_interface
  File "/sct/sdcm/cluster.py", line 2656, in __init__
    self.add_nodes(num, dc_idx=dc_idx)
  File "/sct/sdcm/cluster_aws.py", line 814, in add_nodes
    enable_auto_bootstrap=enable_auto_bootstrap)
  File "/sct/sdcm/cluster_aws.py", line 375, in add_nodes
    enumerate(instances, start=self._node_index + 1)]
  File "/sct/sdcm/cluster_aws.py", line 374, in <listcomp>
    for node_index, instance in
  File "/sct/sdcm/cluster_aws.py", line 391, in _create_node
    base_logdir=base_logdir, dc_idx=dc_idx, node_type=self.node_type)
  File "/sct/sdcm/cluster_aws.py", line 424, in __init__
    dc_idx=dc_idx)
  File "/sct/sdcm/cluster.py", line 402, in __init__
    self.set_hostname()
  File "/sct/sdcm/utils/common.py", line 175, in inner
    return func(*args, **kwargs)
  File "/sct/sdcm/cluster_aws.py", line 460, in set_hostname
    if self.is_debian():
  File "/sct/sdcm/cluster.py", line 557, in is_debian
    return self.distro.is_debian
  File "/sct/sdcm/utils/common.py", line 102, in __get__
    val = self.func(instance)
  File "/sct/sdcm/cluster.py", line 482, in distro
    return Distro.from_os_release(self.remoter.run("cat /etc/os-release", ignore_status=True).stdout)
  File "/sct/sdcm/utils/common.py", line 175, in inner
    return func(*args, **kwargs)
  File "/sct/sdcm/remote.py", line 325, in run
    result = _run()
  File "/sct/sdcm/utils/common.py", line 170, in inner
    return func(*args, **kwargs)
  File "/sct/sdcm/remote.py", line 295, in _run
    raise SSHConnectTimeoutError(err_msg.format(cmd, self.hostname, self.connect_timeout))
sdcm.remote.SSHConnectTimeoutError: Unable to run 'cat /etc/os-release': failed connecting to '172.30.0.160' during 60s
2020-07-31 03:12:20.999: ======================================================================
performance_regression_test.PerformanceRegressionTest.test_mixed

```
* test_id: fde21cec-80f9-4277-aa0e-7d2422f9e2ad 
* job log: https://jenkins.scylladb.com/job/scylla-master/job/scylla-master-perf-regression-aws-test-throughput/30/

```
+------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                          Log links for testrun with test id fde21cec-80f9-4277-aa0e-7d2422f9e2ad                                           |
+-----------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
| Date            | Log type   | Link                                                                                                                        |
+-----------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
| 20200731_031228 | sct-runner | https://cloudius-jenkins-test.s3.amazonaws.com/fde21cec-80f9-4277-aa0e-7d2422f9e2ad/20200731_031228/sct-runner-fde21cec.zip |
+-----------------+------------+-----------------------------------------------------------------------------------------------------------------------------+


```

**Comment by nizarh11** [comment]
@roydahan @bentsi can you please check
