### ISSUE TITLE
Invoke exception UnexpectedExit raised during with libssh2 

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla-cluster-tests#2505]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: branch-4.2/master
* **scylla**: branch-4.2

### Logs
* test_id: 088447af-251d-4222-98f1-3973661f38d8
* job log: https://jenkins.scylladb.com/job/scylla-4.2/job/longevity/job/longevity-10gb-3h-test/42/

### Description

Nemesis ToggleTableIcs raise and error for opensources branch-4.2 instead of skiping nemesis if used libssh2 as remote_cmd_runner.
```
2020-08-13 09:11:42.383: (DisruptionEvent Severity.ERROR): type=end name=ToggleTableICS node=Node longevity-10gb-3h-4-2-db-node-088447af-6 [13.49.70.58 | 10.0.3.139] (seed: False) duration=4 error=Encountered a bad command exit code!
Command: 'cqlsh --no-color   --request-timeout=120 --connect-timeout=60  -e "ALTER TABLE  keyspace1.standard1 WITH compaction = {\'class\': \'IncrementalCompactionStrategy\', \'bucket_high\': 1.65, \'bucket_low\': 0.79, \'min_sstable_size\': 452, \'min_threshold\': 3, \'max_threshold\': 58, \'sstable_size_in_mb\': 1094};" 10.0.3.139 9042'
Exit code: 2
Stdout:
Stderr:
<stdin>:1:ConfigurationException: Unable to find compaction strategy class 'IncrementalCompactionStrategy'
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2116, in wrapper
result = method(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2356, in disrupt
self.call_random_disrupt_method()
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 731, in call_random_disrupt_method
disrupt_method()
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1311, in disrupt_toggle_table_ics
self.toggle_table_ics()
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1187, in toggle_table_ics
self.target_node.run_cqlsh(cmd)
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2710, in run_cqlsh
cqlsh_out = self.remoter.run(cmd, timeout=timeout + 30,  # we give 30 seconds to cqlsh timeout mechanism to work
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 61, in inner
return func(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 590, in run
result = _run()
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 56, in inner
return func(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 582, in _run
return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 536, in _run_execute
result = connection.run(**command_kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 602, in run
return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 636, in _complete_run
raise UnexpectedExit(result)
sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!
Command: 'cqlsh --no-color   --request-timeout=120 --connect-timeout=60  -e "ALTER TABLE  keyspace1.standard1 WITH compaction = {\'class\': \'IncrementalCompactionStrategy\', \'bucket_high\': 1.65, \'bucket_low\': 0.79, \'min_sstable_size\': 452, \'min_threshold\': 3, \'max_threshold\': 58, \'sstable_size_in_mb\': 1094};" 10.0.3.139 9042'
Exit code: 2
Stdout:
Stderr:
<stdin>:1:ConfigurationException: Unable to find compaction strategy class 'IncrementalCompactionStrategy'
```

### Steps to Reproduce

1. Run sct with remote_cmd_runner based on libssh2
2. ToggleTableICS nemesis should be triggered
3. Error detected

**Expected behavior:** [What you expected to happen]
raise UnsupportedNemesis and nemesis skipping
**Actual behavior:** [What actually happened]
reporting an error and nemesis fails

**Comment by nizarh11** [comment]
This also reproduces on Master

```

+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                            Log links for testrun with test id c7605dfa-04bf-4ed8-9e38-d4ac761e0cc8                                                                                            |
+-----------------+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Date            | Log type    | Link                                                                                                                                                                                                                          |
+-----------------+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 20190101_010101 | prometheus  | https://cloudius-jenkins-test.s3.amazonaws.com/c7605dfa-04bf-4ed8-9e38-d4ac761e0cc8/prometheus_snapshot_20200813_033718.tar.gz                                                                                                |
| 20200813_032817 | grafana     | https://cloudius-jenkins-test.s3.amazonaws.com/c7605dfa-04bf-4ed8-9e38-d4ac761e0cc8/20200813_032817/grafana-screenshot-overview-20200813_032817-longevity-10gb-3h-master-monitor-node-c7605dfa-1.png                          |
| 20200813_032817 | grafana     | https://cloudius-jenkins-test.s3.amazonaws.com/c7605dfa-04bf-4ed8-9e38-d4ac761e0cc8/20200813_032817/grafana-screenshot-scylla-per-server-metrics-nemesis-20200813_033157-longevity-10gb-3h-master-monitor-node-c7605dfa-1.png |
| 20200813_033749 | grafana     | https://cloudius-jenkins-test.s3.amazonaws.com/c7605dfa-04bf-4ed8-9e38-d4ac761e0cc8/20200813_033749/grafana-screenshot-overview-20200813_033749-longevity-10gb-3h-master-monitor-node-c7605dfa-1.png                          |
| 20200813_033749 | grafana     | https://cloudius-jenkins-test.s3.amazonaws.com/c7605dfa-04bf-4ed8-9e38-d4ac761e0cc8/20200813_033749/grafana-screenshot-scylla-per-server-metrics-nemesis-20200813_034103-longevity-10gb-3h-master-monitor-node-c7605dfa-1.png |
| 20200813_034723 | db-cluster  | https://cloudius-jenkins-test.s3.amazonaws.com/c7605dfa-04bf-4ed8-9e38-d4ac761e0cc8/20200813_034723/db-cluster-c7605dfa.zip                                                                                                   |
| 20200813_034723 | loader-set  | https://cloudius-jenkins-test.s3.amazonaws.com/c7605dfa-04bf-4ed8-9e38-d4ac761e0cc8/20200813_034723/loader-set-c7605dfa.zip                                                                                                   |
| 20200813_034723 | monitor-set | https://cloudius-jenkins-test.s3.amazonaws.com/c7605dfa-04bf-4ed8-9e38-d4ac761e0cc8/20200813_034723/monitor-set-c7605dfa.zip                                                                                                  |
| 20200813_034723 | sct-runner  | https://cloudius-jenkins-test.s3.amazonaws.com/c7605dfa-04bf-4ed8-9e38-d4ac761e0cc8/20200813_034723/sct-runner-c7605dfa.zip                                                                                                   |
+-----------------+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+


```

Jenknis run: https://jenkins.scylladb.com/view/master/job/scylla-master/job/longevity/job/longevity-10gb-3h-test/164/consoleFull
