### ISSUE TITLE
[SSL: ENCRYPTED_LENGTH_TOO_LONG] encrypted length too long (_ssl.c:1750)

### ISSUE THREAD

**Issue by kongove** [scylladb/scylla-cluster-tests#254]
I didn't change sct code and environment, this ssl error just occurred. Maybe it's a problem of GCE service.

```
2017-03-10 02:55:20,231 stacktrace       L0039 ERROR| Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado-36.3-py2.7.egg/avocado/core/test.py:436
2017-03-10 02:55:20,234 stacktrace       L0042 ERROR| Traceback (most recent call last):
2017-03-10 02:55:20,234 stacktrace       L0042 ERROR|   File "/home/amos/scylla-cluster-tests/sdcm/tester.py", line 129, in wrapper
2017-03-10 02:55:20,234 stacktrace       L0042 ERROR|     return method(*args, **kwargs)
2017-03-10 02:55:20,234 stacktrace       L0042 ERROR|   File "/home/amos/scylla-cluster-tests/sdcm/tester.py", line 161, in setUp
2017-03-10 02:55:20,234 stacktrace       L0042 ERROR|     self.init_resources()
2017-03-10 02:55:20,234 stacktrace       L0042 ERROR|   File "/home/amos/scylla-cluster-tests/sdcm/tester.py", line 129, in wrapper
2017-03-10 02:55:20,234 stacktrace       L0042 ERROR|     return method(*args, **kwargs)
2017-03-10 02:55:20,235 stacktrace       L0042 ERROR|   File "/home/amos/scylla-cluster-tests/sdcm/tester.py", line 524, in init_resources
2017-03-10 02:55:20,235 stacktrace       L0042 ERROR|     monitor_info=monitor_info)
2017-03-10 02:55:20,235 stacktrace       L0042 ERROR|   File "/home/amos/scylla-cluster-tests/sdcm/tester.py", line 305, in get_cluster_gce
2017-03-10 02:55:20,235 stacktrace       L0042 ERROR|     params=self.params)
2017-03-10 02:55:20,235 stacktrace       L0042 ERROR|   File "/home/amos/scylla-cluster-tests/sdcm/cluster.py", line 2744, in __init__
2017-03-10 02:55:20,235 stacktrace       L0042 ERROR|     params=params)
2017-03-10 02:55:20,235 stacktrace       L0042 ERROR|   File "/home/amos/scylla-cluster-tests/sdcm/cluster.py", line 2357, in __init__
2017-03-10 02:55:20,235 stacktrace       L0042 ERROR|     params=params)
2017-03-10 02:55:20,235 stacktrace       L0042 ERROR|   File "/home/amos/scylla-cluster-tests/sdcm/cluster.py", line 1322, in __init__
2017-03-10 02:55:20,235 stacktrace       L0042 ERROR|     self.add_nodes(n_nodes)
2017-03-10 02:55:20,235 stacktrace       L0042 ERROR|   File "/home/amos/scylla-cluster-tests/sdcm/cluster.py", line 2755, in add_nodes
2017-03-10 02:55:20,235 stacktrace       L0042 ERROR|     ec2_user_data=ec2_user_data)
2017-03-10 02:55:20,236 stacktrace       L0042 ERROR|   File "/home/amos/scylla-cluster-tests/sdcm/cluster.py", line 2429, in add_nodes
2017-03-10 02:55:20,236 stacktrace       L0042 ERROR|     base_logdir=self.logdir))
2017-03-10 02:55:20,236 stacktrace       L0042 ERROR|   File "/home/amos/scylla-cluster-tests/sdcm/cluster.py", line 1047, in __init__
2017-03-10 02:55:20,236 stacktrace       L0042 ERROR|     self._gce_service.ex_set_node_tags(self._instance, ['keep-alive'])
2017-03-10 02:55:20,236 stacktrace       L0042 ERROR|   File "/usr/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py", line 5679, in ex_set_node_tags
2017-03-10 02:55:20,236 stacktrace       L0042 ERROR|     self.connection.async_request(request, method='POST', data=tags_data)
2017-03-10 02:55:20,236 stacktrace       L0042 ERROR|   File "/usr/lib/python2.7/site-packages/libcloud/common/base.py", line 1003, in async_request
2017-03-10 02:55:20,236 stacktrace       L0042 ERROR|     response = request(**kwargs)
2017-03-10 02:55:20,236 stacktrace       L0042 ERROR|   File "/usr/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py", line 120, in request
2017-03-10 02:55:20,236 stacktrace       L0042 ERROR|     response = super(GCEConnection, self).request(*args, **kwargs)
2017-03-10 02:55:20,236 stacktrace       L0042 ERROR|   File "/usr/lib/python2.7/site-packages/libcloud/common/google.py", line 812, in request
2017-03-10 02:55:20,236 stacktrace       L0042 ERROR|     raise e
2017-03-10 02:55:20,237 stacktrace       L0042 ERROR| SSLError: [SSL: ENCRYPTED_LENGTH_TOO_LONG] encrypted length too long (_ssl.c:1750)
2017-03-10 02:55:20,237 stacktrace       L0043 ERROR| 
2017-03-10 02:55:20,237 test             L0581 ERROR| ERROR 1-longevity_test.py:LongevityTest.test_custom_time -> TestSetupFail: [SSL: ENCRYPTED_LENGTH_TOO_LONG] encrypted length too long (_ssl.c:1750)
```

**Comment by kongove** [comment]
The above SSL error was touched in adding `keep-alive` tag for node, I also touched another error:

```
Call to method <bound method GCENodeDriver.ex_get_node of <libcloud.compute.drivers.gce.GCENodeDriver object at 0x3cc9bd0>> (retries: 0) failed: [Errno 11] Resource temporarily unavailable
```

Solution: 
Use self._instance_wait_safe() to retry in error case

PR: https://github.com/scylladb/scylla-cluster-tests/pull/251
[PATCH] retry to add keep-alive tag in error case
