### ISSUE TITLE
c-s fails with "Cannot initialize optimized memory deallocator. Some data, both in-memory and on-disk, may live longer due to garbage collection"

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla-cluster-tests#2737]
### Prerequisites

* [x] Are you rebased to master ?
* [ ] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master
* **scylla**: scylla/master

### Logs
* test_id: 094a89c5-de27-4a6d-bab0-c2e52712cfa2
* job log: https://jenkins.scylladb.com/view/master/job/scylla-master/view/master-test/job/longevity/job/longevity-200gb-48h/70

### Description
c-s failing with following error:
```
ERROR 11:13:34,741 FATAL: Cannot initialize optimized memory deallocator. Some data, both in-memory and on-disk, may live longer due to garbage collection.
java.lang.ExceptionInInitializerError
	at org.apache.cassandra.security.SSLFactory.createSSLContext(SSLFactory.java:205)
	at org.apache.cassandra.stress.util.JavaDriverClient.connect(JavaDriverClient.java:142)
	at org.apache.cassandra.stress.settings.StressSettings.getJavaDriverClient(StressSettings.java:211)
	at org.apache.cassandra.stress.settings.SettingsSchema.createKeySpacesNative(SettingsSchema.java:79)
	at org.apache.cassandra.stress.settings.SettingsSchema.createKeySpaces(SettingsSchema.java:69)
	at org.apache.cassandra.stress.settings.StressSettings.maybeCreateKeyspaces(StressSettings.java:228)
	at org.apache.cassandra.stress.StressAction.run(StressAction.java:58)
	at org.apache.cassandra.stress.Stress.run(Stress.java:143)
	at org.apache.cassandra.stress.Stress.main(Stress.java:62)
Caused by: java.lang.RuntimeException: java.lang.IllegalAccessException: access to public member failed: jdk.internal.ref.Cleaner.clean[Ljava.lang.Object;@169bb4dd/invokeVirtual, from org.apache.cassandra.io.util.FileUtils (unnamed module @48fa0f47)
	at org.apache.cassandra.io.util.FileUtils.<clinit>(FileUtils.java:105)
	... 9 more
Caused by: java.lang.IllegalAccessException: access to public member failed: jdk.internal.ref.Cleaner.clean[Ljava.lang.Object;@169bb4dd/invokeVirtual, from org.apache.cassandra.io.util.FileUtils (unnamed module @48fa0f47)
	at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:942)
	at java.base/java.lang.invoke.MethodHandles$Lookup.checkAccess(MethodHandles.java:2206)
	at java.base/java.lang.invoke.MethodHandles$Lookup.checkMethod(MethodHandles.java:2146)
	at java.base/java.lang.invoke.MethodHandles$Lookup.getDirectMethodCommon(MethodHandles.java:2290)
	at java.base/java.lang.invoke.MethodHandles$Lookup.getDirectMethodNoSecurityManager(MethodHandles.java:2283)
	at java.base/java.lang.invoke.MethodHandles$Lookup.unreflect(MethodHandles.java:1747)
	at org.apache.cassandra.io.util.FileUtils.<clinit>(FileUtils.java:96)
	... 9 more
```

### Steps to Reproduce

No steps yet

**Comment by dkropachev** [comment]
This thing is related to java being updated to 11, appears only when c-s is using ssl certificate

**Comment by dkropachev** [comment]
Fixed on current loaders
