### ISSUE TITLE
disrupt_nodetool_refresh fails on k8s-gce-minikube backend

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla-cluster-tests#2743]
### Versions
* **SCT**: master
* **scylla**: [branch or commit hash]

### Logs
* test_id: 9aba5583-c50f-4329-a35b-12adc5fc7c2a
* job log: https://cloudius-jenkins-test.s3.amazonaws.com/9aba5583-c50f-4329-a35b-12adc5fc7c2a/20200927_065641/sct-runner-9aba5583.zip

```
2020-09-27 04:08:22.197: (DisruptionEvent Severity.ERROR): type=end name=Refresh node=Node sct-cluster-gce-minikube-2 [10.109.99.124 | 10.109.99.124] (seed: False) duration=14 error=Resharding wasn't run
Traceback (most recent call last):
File "/jenkins/slave/workspace/scylla-master/longevity/longevity-scylla-operator-3h/scylla-cluster-tests/sdcm/nemesis.py", line 2405, in wrapper
result = method(*args, **kwargs)
File "/jenkins/slave/workspace/scylla-master/longevity/longevity-scylla-operator-3h/scylla-cluster-tests/sdcm/nemesis.py", line 3123, in disrupt
self.call_random_disrupt_method(disrupt_methods=self.disrupt_methods_list)
File "/jenkins/slave/workspace/scylla-master/longevity/longevity-scylla-operator-3h/scylla-cluster-tests/sdcm/nemesis.py", line 803, in call_random_disrupt_method
disrupt_method()
File "/jenkins/slave/workspace/scylla-master/longevity/longevity-scylla-operator-3h/scylla-cluster-tests/sdcm/nemesis.py", line 729, in disrupt_nodetool_refresh
validate_resharding_after_refresh(resharding_done)
File "/jenkins/slave/workspace/scylla-master/longevity/longevity-scylla-operator-3h/scylla-cluster-tests/sdcm/nemesis.py", line 706, in validate_resharding_after_refresh
assert resharding_done, "Resharding wasn't run"

```
### Description

disrupt_nodetool_refresh fails on k8s-gce-minikube backend with "Resharding wasn't run"

**Comment by yarongilor** [comment]
error seems to be reproduced on cloud longevity - 
```
Scylla version (or git commit hash): `2020.1.4-0.20201111.a244dabf89 with build-id 236f4ceab24a5dca73a9d05ab301f9517bbab52d`
Cluster size: 6 nodes (i3.large)
OS (RHEL/CentOS/Ubuntu/AWS AMI): `-` (aws-siren: eu-west-1)


Test: `scylla-cloud-longevity-small-data-set-1h`
Test name: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):
- scylla_cloud_nemesis_small_set.yaml (Siren repo)
- scylla_cloud.yaml (Siren repo)
```
```
2021-01-05 23:46:16.992: (DisruptionEvent Severity.ERROR): type=Refresh subtype=end node=Node longevity-small-set-1h-master-db-node-9a91c500-3 [79.125.59.12 | 172.31.2.11] (seed: True) duration=9 error=Resharding wasn't run
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2810, in wrapper
result = method(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3222, in disrupt
self.call_random_disrupt_method(disrupt_methods=['disrupt_nodetool_cleanup',
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 997, in call_random_disrupt_method
self.execute_disrupt_method(disrupt_method)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1004, in execute_disrupt_method
disrupt_method()
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 922, in disrupt_nodetool_refresh
validate_resharding_after_refresh(resharding_done)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 899, in validate_resharding_after_refresh
assert resharding_done, "Resharding wasn't run"
AssertionError: Resharding wasn't run
```

**Comment by yarongilor** [comment]
@dkropachev, @enaydanov , please see if you have any update on this. it is now reproduced everyday on cloud sanity longevity.

**Comment by fruch** [comment]
resharding is done completely differently now on case of k8s, and it's working on EKS/GKE.
we don't run longevity on local k8s setup anymore.
