### ISSUE TITLE
Elasticsearch errors break whole run

### ISSUE THREAD

**Issue by enaydanov** [scylladb/scylla-cluster-tests#2759]
SCT should be tolerant to Elasticsearch errors. It's better to create an CRITICAL or ERROR event instead of raising exception.

Example:

```python
Exception in setUp. Will call tearDown
Traceback (most recent call last):                                                                                                                                    
  File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 110, in wrapper                                                                                       
    return method(*args, **kwargs)                                                                                                                                    
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 109, in inner                                                                               
    res = func(*args, **kwargs)                                                                                                                                       
  File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 427, in setUp                                                                                         
    self.create_test_stats()                                                                                                                                          
  File "/home/ubuntu/scylla-cluster-tests/sdcm/db_stats.py", line 503, in create_test_stats                                                                           
    self.create()                                                                                                                                                     
  File "/home/ubuntu/scylla-cluster-tests/sdcm/db_stats.py", line 348, in create                                                                                      
    self.elasticsearch.create_doc(index=self._test_index, doc_type=self._es_doc_type,                                                                                 
  File "/home/ubuntu/scylla-cluster-tests/sdcm/es.py", line 40, in create_doc                                                                                         
    self.create(index=index, doc_type=doc_type, id=doc_id, body=body)                                                                                                 
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped                                                                   
    return func(*args, params=params, **kwargs)                                                                                                                       
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/client/__init__.py", line 259, in create                                                                 
    return self.transport.perform_request('PUT', _make_path(index, doc_type,                                                                                          
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/transport.py", line 314, in perform_request                                                              
    status, headers, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)                                    
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 161, in perform_request                                                
    self._raise_error(response.status, raw_data)                                                                                                                      
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error                                                           
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)                                                               
elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Limit of total fields [1000] in index [lwtlongevitytest] has been exceeded')
```

**Comment by fruch** [comment]
I've suggested it before, and I do again, I think we should disable the reporting to ES as default.
and only enable it for the test it's important.

we are collecting there "junk" data, that we are not using now. if we still want to save the SCT information there, we should drop all the nesting as possible, and start a new index for all longevity, and not per scenarios.

**Comment by fruch** [comment]
Also I've wrote a small script that can fix it for specific indexes,
https://github.com/scylladb/scylla-cluster-tests/blob/master/utils/fix_es_mapping.py

but it might not be helpful,

the root-cause is that we are pushing dicts with varying names (i.e. machine names, and such) into the index, and those are automatically indexed. 
this script try to disable most of the automatic indexing, but might not cover all the cases, it was intend as a patch for the indexes we need to their results
