### ISSUE TITLE
Operator test failed on master due "yum search scylla-enterprise" output problem

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-cluster-tests#2776]
### Prerequisites

* [ ] Are you rebased to master ?
* [ ] Is it reproducible ?
* [ ] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master
* **scylla**: 4.1.7

### Logs
* test_id: c9cdbe63-5452-44b8-a7d1-45c31100da61
* job log: https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-scylla-operator-3h/27/
* sct logs:  https://cloudius-jenkins-test.s3.amazonaws.com/c9cdbe63-5452-44b8-a7d1-45c31100da61/20201011_032018/sct-runner-c9cdbe63.zip
* email: FAILED: scylla-master/longevity/longevity-scylla-operator-3h#27: 2020-10-11 03:00:46

### Description

longevity-scylla-operator-3h tes failed on master with error:

```
< t:2020-10-11 03:18:02,513 f:kubernetes_cmd_runner.py l:152  c:KubernetesCmdRunner  p:DEBUG > Running command "yum search scylla-enterprise 2>&1"...
< t:2020-10-11 03:18:02,734 f:base.py         l:220  c:KubernetesCmdRunner  p:DEBUG > Loaded plugins: fastestmirror, ovl
< t:2020-10-11 03:18:02,873 f:base.py         l:220  c:KubernetesCmdRunner  p:DEBUG > Determining fastest mirrors
< t:2020-10-11 03:18:03,917 f:base.py         l:220  c:KubernetesCmdRunner  p:DEBUG >  * base: mirror.teklinks.com
< t:2020-10-11 03:18:03,918 f:base.py         l:220  c:KubernetesCmdRunner  p:DEBUG >  * epel: iad.mirror.rackspace.com
< t:2020-10-11 03:18:03,918 f:base.py         l:220  c:KubernetesCmdRunner  p:DEBUG >  * extras: mirror.cogentco.com
< t:2020-10-11 03:18:03,918 f:base.py         l:220  c:KubernetesCmdRunner  p:DEBUG >  * updates: mirror.mojohost.com
< t:2020-10-11 03:18:04,720 f:base.py         l:220  c:KubernetesCmdRunner  p:DEBUG > https://mirror.umd.edu/fedora/epel/7/x86_64/repodata/26aa3fe31b7a3b4fd3c1865e5a8635f296b1a9c3591a936744c4226a7b170089-updateinfo.xml.bz2: [Errno 14] HTTPS Error 404 - Not Found
< t:2020-10-11 03:18:05,224 f:base.py         l:220  c:KubernetesCmdRunner  p:DEBUG > package scylla-enterprise is not installed
< t:2020-10-11 03:20:02,521 f:sct_events.py   l:964  c:sdcm.sct_events      p:INFO  > 2020-10-11 03:20:02.485: (TestFrameworkEvent Severity.ERROR), source=LongevityTest.SetUp() 
< t:2020-10-11 03:20:02,521 f:sct_events.py   l:964  c:sdcm.sct_events      p:INFO  > exception=[Node sct-cluster-gce-minikube-1 [10.98.147.6 | 10.98.147.6] (seed: False)] NodeSetupFailed: There is no pre-installed ScyllaDB
< t:2020-10-11 03:20:02,521 f:sct_events.py   l:964  c:sdcm.sct_events      p:INFO  > Traceback (most recent call last):
< t:2020-10-11 03:20:02,521 f:sct_events.py   l:964  c:sdcm.sct_events      p:INFO  >   File "/jenkins/slave/workspace/scylla-master/longevity/longevity-scylla-operator-3h/scylla-cluster-tests/sdcm/cluster.py", line 3022, in node_setup
< t:2020-10-11 03:20:02,521 f:sct_events.py   l:964  c:sdcm.sct_events      p:INFO  >     cl_inst.node_setup(_node, **setup_kwargs)
< t:2020-10-11 03:20:02,521 f:sct_events.py   l:964  c:sdcm.sct_events      p:INFO  >   File "/jenkins/slave/workspace/scylla-master/longevity/longevity-scylla-operator-3h/scylla-cluster-tests/sdcm/cluster.py", line 3596, in node_setup
< t:2020-10-11 03:20:02,521 f:sct_events.py   l:964  c:sdcm.sct_events      p:INFO  >     raise Exception("There is no pre-installed ScyllaDB")
< t:2020-10-11 03:20:02,521 f:sct_events.py   l:964  c:sdcm.sct_events      p:INFO  > Exception: There is no pre-installed ScyllaDB
```

It happened because of the yum output was cut and we can't find expected sub-strings.
I faced out with this problem first time

**Comment by bentsi** [comment]
@enaydanov is it an issue of the KubernetesCMD Runner?
