### ISSUE TITLE
Longevity does not fail when C-S process fails

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla-cluster-tests#2820]
### Prerequisites

* [x] Are you rebased to master ?
* [ ] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master
* **scylla**: master

### Logs
* test_id: a9066c3a-7184-4ec6-9afa-68b24025857e
* job log: https://jenkins.scylladb.com/view/master/job/scylla-master/view/master-test/job/longevity/job/longevity-200gb-48h/82/

### Description

During the run, one of the running C-S faileddue to a timeout:
```
Command:
  Type: write
  Count: -1
  Duration: 2,860 MINUTES
  No Warmup: false
  Consistency Level: QUORUM
  Serial Consistency Level: SERIAL
  Target Uncertainty: not applicable
  Key Size (bytes): 10
  Counter Increment Distibution: add=fixed(1)
Rate:
  Auto: false
  Thread Count: 250
  OpsPer Sec: 0
Population:
  Sequence: 400200300..600200300
  Order: ARBITRARY
  Wrap: true
Insert:
  Revisits: Uniform:  min=1,max=1000000
  Visits: Fixed:  key=1
  Row Population Ratio: Ratio: divisor=1.000000;delegate=Fixed:  key=1
  Batch Type: not batching

...

com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
java.io.IOException: Operation x10 on key(s) [4d4d304b383837384f30]: Error executing: (WriteTimeoutException): Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)

        at org.apache.cassandra.stress.Operation.error(Operation.java:141)
        at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:119)
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:101)
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:109)
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:264)
        at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:469)
java.io.IOException: Operation x10 on key(s) [33394c39353738333730]: Error executing: (WriteTimeoutException): Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)

        at org.apache.cassandra.stress.Operation.error(Operation.java:141)
        at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:119)
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:101)
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:109)
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:264)
        at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:469)
11:42:53.325 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Connection - Connection[/10.0.2.73:9042-1, inFlight=0, closed=false] was inactive for 30 seconds, sending heartbeat
11:42:53.326 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Connection - Connection[/10.0.2.73:9042-1, inFlight=0, closed=false] heartbeat query succeeded
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
11:43:05.445 [cluster1-nio-worker-1] DEBUG com.datastax.driver.core.Connection - Connection[/10.0.2.73:9042-5, inFlight=0, closed=false] was inactive for 30 seconds, sending heartbeat
11:43:05.446 [cluster1-nio-worker-1] DEBUG com.datastax.driver.core.Connection - Connection[/10.0.2.73:9042-5, inFlight=0, closed=false] heartbeat query succeeded
11:43:05.512 [cluster1-nio-worker-6] DEBUG com.datastax.driver.core.Connection - Connection[/10.0.2.73:9042-18, inFlight=0, closed=false] was inactive for 30 seconds, sending heartbeat
11:43:05.512 [cluster1-nio-worker-6] DEBUG com.datastax.driver.core.Connection - Connection[/10.0.2.73:9042-18, inFlight=0, closed=false] heartbeat query succeeded
11:43:05.744 [cluster1-nio-worker-5] DEBUG com.datastax.driver.core.Connection - Connection[/10.0.0.50:9042-104, inFlight=0, closed=false] was inactive for 30 seconds, sending heartbeat
11:43:05.745 [cluster1-nio-worker-5] DEBUG com.datastax.driver.core.Connection - Connection[/10.0.0.50:9042-104, inFlight=0, closed=false] heartbeat query succeeded
11:43:05.745 [cluster1-nio-worker-6] DEBUG com.datastax.driver.core.Connection - Connection[/10.0.1.158:9042-36, inFlight=0, closed=false] was inactive for 30 seconds, sending heartbeat
11:43:05.746 [cluster1-nio-worker-6] DEBUG com.datastax.driver.core.Connection - Connection[/10.0.1.158:9042-36, inFlight=0, closed=false] heartbeat query succeeded
11:43:05.747 [cluster1-nio-worker-3] DEBUG com.datastax.driver.core.Connection - Connection[/10.0.1.158:9042-41, inFlight=0, closed=false] was inactive for 30 seconds, sending heartbeat
11:43:05.747 [cluster1-nio-worker-3] DEBUG com.datastax.driver.core.Connection - Connection[/10.0.1.158:9042-41, inFlight=0, closed=false] heartbeat query succeeded
11:43:05.749 [cluster1-nio-worker-7] DEBUG com.datastax.driver.core.Connection - Connection[/10.0.0.50:9042-105, inFlight=0, closed=false] was inactive for 30 seconds, sending heartbeat
11:43:05.749 [cluster1-nio-worker-7] DEBUG com.datastax.driver.core.Connection - Connection[/10.0.2.73:9042-11, inFlight=0, closed=false] was inactive for 30 seconds, sending heartbeat
11:43:05.750 [cluster1-nio-worker-7] DEBUG com.datastax.driver.core.Connection - Connection[/10.0.2.73:9042-11, inFlight=0, closed=false] heartbeat query succeeded
11:43:05.750 [cluster1-nio-worker-7] DEBUG com.datastax.driver.core.Connection - Connection[/10.0.0.50:9042-105, inFlight=0, closed=false] heartbeat query succeeded
11:43:05.919 [cluster1-nio-worker-7] DEBUG com.datastax.driver.core.Connection - Connection[/10.0.2.73:9042-3, inFlight=0, closed=false] was inactive for 30 seconds, sending heartbeat
11:43:05.920 [cluster1-nio-worker-7] DEBUG com.datastax.driver.core.Connection - Connection[/10.0.2.73:9042-3, inFlight=0, closed=false] heartbeat query succeeded
11:43:05.929 [cluster1-nio-worker-1] DEBUG com.datastax.driver.core.Connection - Connection[/10.0.0.50:9042-115, inFlight=0, closed=false] was inactive for 30 seconds, sending heartbeat
11:43:05.930 [cluster1-nio-worker-1] DEBUG com.datastax.driver.core.Connection - Connection[/10.0.0.50:9042-115, inFlight=0, closed=false] heartbeat query succeeded
```

![Screenshot from 2020-11-03 02-43-33](https://user-images.githubusercontent.com/40186893/97934504-97839580-1d7e-11eb-86ca-c42b51cf7188.png)

Afterwards, the load does nothing besides sending heartbeat queries. The longevity, however, continues as without failure until its designated time, even though it should have stopped as soon as the load stopped.

**Expected behavior:** The longevity should stop as soon as the C-S fails.

**Actual behavior:** The longevity continues as with no issue even though the C-S has failed.

**Comment by dkropachev** [comment]
Not sct issue.

Related c-s issue - https://github.com/scylladb/scylla-tools-java/issues/168
