### ISSUE TITLE
In Snapshot disruption SCT supply nodetool with empty table name as parameter

### ISSUE THREAD

**Issue by shoshan** [scylladb/scylla-cluster-tests#2874]
### Prerequisites

* [x] Are you rebased to master ?
* [ ] Is it reproducible ?
* [ ] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: [branch or hash tag you are working on]   sct-branch-4.3
* **scylla**: [branch or commit hash]  scylla 4.3.rc1 

### Logs
https://cloudius-jenkins-test.s3.amazonaws.com/9dcfc92c-8c7f-4527-bd11-3507b351160c/20201113_074626/sct-runner-9dcfc92c.zip

* test_id: [look for 'the Test ID' at the end of the log]  longevity-large-partition-200k-pks-4days-test test_id: 9dcfc92c-8c7f-4527-bd11-3507b351160c
* job log: [e.x. https://cloudius-jenkins-test.s3.amazonaws.com/5a2c3b72-40f8-4992-8b5a-5c4aec8bf0c6/job-2019-05-14T09.59-c85338a.zip]

### Description
When doing Snapshot disruption  SCT supply nodetool with empty table name as parameter. 
command  resulted in an Severity.Error.
`
2020-11-12 18:27:48.785: (DisruptionEvent Severity.ERROR): type=end name=SnapshotOperations node=Node longevity-large-partitions-200k-pks-db-node-9dcfc92c-5 [34.243.203.28 | 10.0.2.242] (seed: False) duration=5 error=Encountered a bad command exit code!
Command: 'nodetool  snapshot system -cf  '
Exit code: 1
Stdout:
Using /etc/scylla/scylla.yaml as the config file
nodetool: Required values for option 'table' not provided
See 'nodetool help' or 'nodetool help <command>'.
Stderr:

Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2454, in wrapper
    result = method(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2724, in disrupt
    self.call_random_disrupt_method()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 817, in call_random_disrupt_method
    self.execute_disrupt_method(disrupt_method)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 824, in execute_disrupt_method
    disrupt_method()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1680, in disrupt_snapshot_operations
    result = self.target_node.run_nodetool(nodetool_cmd)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2407, in run_nodetool
    result = self.remoter.run(cmd, timeout=timeout, ignore_status=ignore_status, verbose=verbose)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 601, in run
    result = _run()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 61, in inner
    return func(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 593, in _run
    return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 536, in _run_execute
    result = connection.run(**command_kwargs)
  File "<decorator-gen-3>", line 2, in run
  File "/usr/local/lib/python3.8/site-packages/fabric/connection.py", line 30, in opens
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/fabric/connection.py", line 721, in run
    return self._run(self._remote_runner(), command, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/invoke/context.py", line 101, in _run
    return runner.run(command, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/invoke/runners.py", line 291, in run
    return self._run_body(command, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/invoke/runners.py", line 442, in _run_body
    raise UnexpectedExit(result)
invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!

Command: 'nodetool  snapshot system -cf  '

Exit code: 1

Stdout:
`

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by shoshan** [comment]
@roydahan @bentsi occured again.
Test-id: 689dfa02-d790-42fc-a3c3-d94f24b6aeb2

`
2020-12-03 18:23:42.765: (DisruptionEvent Severity.ERROR): type=end name=SnapshotOperations node=Node longevity-counters-multidc-4-3-db-node-689dfa02-4 [52.35.234.61 | 10.0.2.95] (seed: False) duration=156 error=Encountered a bad command exit code!
Command: '/usr/bin/nodetool  snapshot system_schema -cf  '
Exit code: 1
Stdout:
Using /etc/scylla/scylla.yaml as the config file
nodetool: Required values for option 'table' not provided
See 'nodetool help' or 'nodetool help <command>'.
Stderr:
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2433, in wrapper
result = method(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2703, in disrupt
self.call_random_disrupt_method()
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 817, in call_random_disrupt_method
self.execute_disrupt_method(disrupt_method)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 824, in execute_disrupt_method
disrupt_method()
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1680, in disrupt_snapshot_operations
result = self.target_node.run_nodetool(nodetool_cmd)
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2491, in run_nodetool
result = self.remoter.run(cmd, timeout=timeout, ignore_status=ignore_status, verbose=verbose)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 601, in run
result = _run()
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 61, in inner
return func(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 593, in _run
return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 536, in _run_execute
result = connection.run(**command_kwargs)
File "<decorator-gen-3>", line 2, in run
File "/usr/local/lib/python3.8/site-packages/fabric/connection.py", line 30, in opens
return method(self, *args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/fabric/connection.py", line 721, in run
return self._run(self._remote_runner(), command, **kwargs)
File "/usr/local/lib/python3.8/site-packages/invoke/context.py", line 101, in _run
return runner.run(command, **kwargs)
File "/usr/local/lib/python3.8/site-packages/invoke/runners.py", line 291, in run
return self._run_body(command, **kwargs)
File "/usr/local/lib/python3.8/site-packages/invoke/runners.py", line 442, in _run_body
raise UnexpectedExit(result)
invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!
Command: '/usr/bin/nodetool  snapshot system_schema -cf  '
Exit code: 1
Stdout:
Using /etc/scylla/scylla.yaml as the config file
nodetool: Required values for option 'table' not provided
See 'nodetool help' or 'nodetool help <command>'.
Stderr:
`
longevity/longevity-counters-multidc-test#4: 2020-12-03.

**Comment by bentsi** [comment]
@shoshan do we have the same issue in master?

**Comment by roydahan** [comment]
We have it in 4.3.
Why wouldn’t we have it on master?
Has this code changed?

@shoshan please try to fix the issue yourself and send PR.

**Comment by bentsi** [comment]
there were changes made in this Nemesis, but now I see that it was backported to 4.3. I will ask @juliayakovlev to check this.
