### ISSUE TITLE
grafana screenshots timing out

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylla-cluster-tests#2882]
### Versions
* **SCT**: branch-4.3
* **scylla**: 4.3.rc1

### Logs
* test_id: 2b3be941-5212-46ad-968d-267607564c47
* job log: https://jenkins.scylladb.com/view/scylla-4.3/job/scylla-4.3/job/longevity/job/longevity-large-partition-4days-test/2/

### Description

i have seen it few times (specially when running from my local pc):
```
< t:2020-11-16 07:13:11,683 f:connectionpool.py l:391  c:urllib3.connectionpool p:DEBUG > http://127.0.0.1:47731 "POST /wd/hub/session/b1f6455ea364d028d1a0204a6698ee8a/url HTTP/1.1" 500 189
< t:2020-11-16 07:13:11,683 f:remote_connection.py l:440  c:selenium.webdriver.remote.remote_connection p:DEBUG > Finished Request
< t:2020-11-16 07:13:11,685 f:logcollector.py l:481  c:sdcm.logcollector    p:ERROR > Error taking monitor screenshot: Message: timeout: Timed out receiving message from renderer: -0.077
< t:2020-11-16 07:13:11,685 f:logcollector.py l:481  c:sdcm.logcollector    p:ERROR >   (Session info: chrome=86.0.4240.75)
< t:2020-11-16 07:13:11,685 f:logcollector.py l:481  c:sdcm.logcollector    p:ERROR > , traceback: Traceback (most recent call last):
< t:2020-11-16 07:13:11,685 f:logcollector.py l:481  c:sdcm.logcollector    p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/logcollector.py", line 473, in get_grafana_screenshot
< t:2020-11-16 07:13:11,685 f:logcollector.py l:481  c:sdcm.logcollector    p:ERROR >     self.remote_browser.get_screenshot(grafana_url, screenshot_path,
< t:2020-11-16 07:13:11,685 f:logcollector.py l:481  c:sdcm.logcollector    p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/remotewebbrowser.py", line 96, in get_screenshot
< t:2020-11-16 07:13:11,685 f:logcollector.py l:481  c:sdcm.logcollector    p:ERROR >     self.browser.get(url)
< t:2020-11-16 07:13:11,685 f:logcollector.py l:481  c:sdcm.logcollector    p:ERROR >   File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
< t:2020-11-16 07:13:11,685 f:logcollector.py l:481  c:sdcm.logcollector    p:ERROR >     self.execute(Command.GET, {'url': url})
< t:2020-11-16 07:13:11,685 f:logcollector.py l:481  c:sdcm.logcollector    p:ERROR >   File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
< t:2020-11-16 07:13:11,685 f:logcollector.py l:481  c:sdcm.logcollector    p:ERROR >     self.error_handler.check_response(response)
< t:2020-11-16 07:13:11,685 f:logcollector.py l:481  c:sdcm.logcollector    p:ERROR >   File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_respons
e
< t:2020-11-16 07:13:11,685 f:logcollector.py l:481  c:sdcm.logcollector    p:ERROR >     raise exception_class(message, screen, stacktrace)
< t:2020-11-16 07:13:11,685 f:logcollector.py l:481  c:sdcm.logcollector    p:ERROR > selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: -0.077
< t:2020-11-16 07:13:11,685 f:logcollector.py l:481  c:sdcm.logcollector    p:ERROR >   (Session info: chrome=86.0.4240.75)
< t:2020-11-16 07:13:11,685 f:logcollector.py l:481  c:sdcm.logcollector    p:ERROR > 
< t:2020-11-16 07:13:11,685 f:logcollector.py l:418  c:sdcm.logcollector    p:INFO  > Grafana - browser quit
< t:2020-11-16 07:13:11,686 f:remote_connection.py l:388  c:selenium.webdriver.remote.remote_connection p:DEBUG > DELETE http://127.0.0.1:47731/wd/hub/session/b1f6455ea364d028d1a0204a6698ee8a {}
```
any ideas if increasing the timeout would solve the issue? does the code retries?

**Comment by fgelcer** [comment]
this happened in the same job, and i'm not sure if this is a result of previous exception (that failed to collect part of the information) or if it is an unrelated issue:

```
< t:2020-11-16 07:18:53,782 f:logcollector.py l:590  c:sdcm.logcollector    p:ERROR > Error taking monitor snapshot: Alert Text: {Alert text : 
< t:2020-11-16 07:18:53,782 f:logcollector.py l:590  c:sdcm.logcollector    p:ERROR > Message: unexpected alert open: {Alert text : }
< t:2020-11-16 07:18:53,782 f:logcollector.py l:590  c:sdcm.logcollector    p:ERROR >   (Session info: chrome=86.0.4240.75)
< t:2020-11-16 07:18:53,782 f:logcollector.py l:590  c:sdcm.logcollector    p:ERROR > , traceback: Traceback (most recent call last):
< t:2020-11-16 07:18:53,782 f:logcollector.py l:590  c:sdcm.logcollector    p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/logcollector.py", line 586, in get_grafana_snapshot
< t:2020-11-16 07:18:53,782 f:logcollector.py l:590  c:sdcm.logcollector    p:ERROR >     snapshots.append(self._get_shared_snapshot_link(self.remote_browser.browser, grafana_url))
< t:2020-11-16 07:18:53,782 f:logcollector.py l:590  c:sdcm.logcollector    p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/logcollector.py", line 542, in _get_shared_snapshot_link
< t:2020-11-16 07:18:53,782 f:logcollector.py l:590  c:sdcm.logcollector    p:ERROR >     self.scrolldown_dashboards_view(remote_browser)
< t:2020-11-16 07:18:53,782 f:logcollector.py l:590  c:sdcm.logcollector    p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/logcollector.py", line 517, in scrolldown_dashboards_view
< t:2020-11-16 07:18:53,782 f:logcollector.py l:590  c:sdcm.logcollector    p:ERROR >     WebDriverWait(remote_browser, 60).until(EC.visibility_of_element_located(self.snapshot_scroll_ready_locator))
< t:2020-11-16 07:18:53,782 f:logcollector.py l:590  c:sdcm.logcollector    p:ERROR >   File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py", line 71, in until
< t:2020-11-16 07:18:53,782 f:logcollector.py l:590  c:sdcm.logcollector    p:ERROR >     value = method(self._driver)
< t:2020-11-16 07:18:53,782 f:logcollector.py l:590  c:sdcm.logcollector    p:ERROR >   File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/support/expected_conditions.py", line 128, in __cal
l__
< t:2020-11-16 07:18:53,782 f:logcollector.py l:590  c:sdcm.logcollector    p:ERROR >     return _element_if_visible(_find_element(driver, self.locator))
< t:2020-11-16 07:18:53,782 f:logcollector.py l:590  c:sdcm.logcollector    p:ERROR >   File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/support/expected_conditions.py", line 415, in _find
_element
< t:2020-11-16 07:18:53,782 f:logcollector.py l:590  c:sdcm.logcollector    p:ERROR >     raise e
< t:2020-11-16 07:18:53,782 f:logcollector.py l:590  c:sdcm.logcollector    p:ERROR >   File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/support/expected_conditions.py", line 411, in _find
_element
< t:2020-11-16 07:18:53,782 f:logcollector.py l:590  c:sdcm.logcollector    p:ERROR >     return driver.find_element(*by)
< t:2020-11-16 07:18:53,782 f:logcollector.py l:590  c:sdcm.logcollector    p:ERROR >   File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
< t:2020-11-16 07:18:53,782 f:logcollector.py l:590  c:sdcm.logcollector    p:ERROR >     return self.execute(Command.FIND_ELEMENT, {
< t:2020-11-16 07:18:53,782 f:logcollector.py l:590  c:sdcm.logcollector    p:ERROR >   File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
< t:2020-11-16 07:18:53,782 f:logcollector.py l:590  c:sdcm.logcollector    p:ERROR >     self.error_handler.check_response(response)
< t:2020-11-16 07:18:53,782 f:logcollector.py l:590  c:sdcm.logcollector    p:ERROR >   File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 241, in check_respons
e
< t:2020-11-16 07:18:53,782 f:logcollector.py l:590  c:sdcm.logcollector    p:ERROR >     raise exception_class(message, screen, stacktrace, alert_text)
< t:2020-11-16 07:18:53,782 f:logcollector.py l:590  c:sdcm.logcollector    p:ERROR > selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: {Alert text : 
< t:2020-11-16 07:18:53,782 f:logcollector.py l:590  c:sdcm.logcollector    p:ERROR > Message: unexpected alert open: {Alert text : }
< t:2020-11-16 07:18:53,782 f:logcollector.py l:590  c:sdcm.logcollector    p:ERROR >   (Session info: chrome=86.0.4240.75)
< t:2020-11-16 07:18:53,782 f:logcollector.py l:590  c:sdcm.logcollector    p:ERROR > 
< t:2020-11-16 07:18:53,782 f:logcollector.py l:418  c:sdcm.logcollector    p:INFO  > Grafana - browser quit
```
