### ISSUE TITLE
disrupt_remove_node_then_add_node step 2 (run full repair) fails but didn't raise an event

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylla-cluster-tests#2884]
### Versions
* **SCT**: branch-4.3
* **scylla**: 4.3.rc1

### Logs
* test_id: 2b3be941-5212-46ad-968d-267607564c47
* job log: https://jenkins.scylladb.com/view/scylla-4.3/job/scylla-4.3/job/longevity/job/longevity-large-partition-4days-test/2/

### Description

i'm not yet sure if this should be an error (fail the nemesis) or expected result.
also, i'm not sure if this is just a bad "timing" issue, or a real Scylla issue.

here is the issue:
```
Error executing command: "nodetool  repair "; Exit status: 2
STDOUT: 11-14 05:30:34,972] Starting repair command #1030, repairing 1 ranges for keyspace scylla_bench (parallelism=SEQUENTIAL, full=true)
[2020-11-14 05:48:36,155] Repair session 1030 failed
[2020-11-14 05:48:36,156] Repair session 1030 finished
STDERR: error: Repair job has failed with the error message: [2020-11-14 05:48:36,155] Repair session 1030 failed
-- StackTrace --
java.lang.RuntimeException: Repair job has failed with the error message: [2020-11-14 05:48:36,155] Repair session 1030 failed
  at org.apache.cassandra.tools.RepairRunner.progress(RepairRunner.java:124)
  at org.apache.cassandra.utils.progress.jmx.JMXNotificationProgressListener.handleNotification(JMXNotificationProgressListener.java:77)
  at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.dispatchNotification(ClientNotifForwarder.java:583)
  at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.doRun(ClientNotifForwarder.java:533)
  at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.run(ClientNotifForwarder.java:452)
  at com.sun.jmx.remote.internal.ClientNotifForwarder$LinearExecutor$1.run(ClientNotifForwarder.java:108)

Node longevity-large-partitions-4d-4-3-db-node-2b3be941-1 [34.254.243.108 | 10.0.0.168] (seed: False): Command 'nodetool  repair ' error: Encountered a bad command exit code!

Command: 'nodetool  repair '

Exit code: 2

Stdout:

Using /etc/scylla/scylla.yaml as the config file
[2020-11-14 05:30:34,972] Starting repair command #1030, repairing 1 ranges for keyspace scylla_bench (parallelism=SEQUENTIAL, full=true)
[2020-11-14 05:48:36,155] Repair session 1030 failed
[2020-11-14 05:48:36,156] Repair session 1030 finished

Stderr:

error: Repair job has failed with the error message: [2020-11-14 05:48:36,155] Repair session 1030 failed
-- StackTrace --
java.lang.RuntimeException: Repair job has failed with the error message: [2020-11-14 05:48:36,155] Repair session 1030 failed
       at org.apache.cassandra.tools.RepairRunner.progress(RepairRunner.java:124)
       at org.apache.cassandra.utils.progress.jmx.JMXNotificationProgressListener.handleNotification(JMXNotificationProgressListener.java:77)
       at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.dispatchNotification(ClientNotifForwarder.java:583)
       at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.doRun(ClientNotifForwarder.java:533)
       at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.run(ClientNotifForwarder.java:452)
       at com.sun.jmx.remote.internal.ClientNotifForwarder$LinearExecutor$1.run(ClientNotifForwarder.java:108)
```

from the code:
```
        for node in up_normal_nodes:
            if node is not node_to_remove:
                try:
                    self.repair_nodetool_repair(node=node)
                except Exception as details:  # pylint: disable=broad-except
                    self.log.error(f"failed to execute repair command "
                                   f"on node {node} due to the following error: {str(details)}")
```
is this supposed to raise an exception and fail the nemesis?
is it an exception with the repair command? or just a bad timing, as we just run:
```
self.cluster.terminate_node(node)
self.monitoring_set.reconfigure_scylla_monitoring()
```

**Comment by roydahan** [comment]
It is by design.
When adding this nemesis we followed the procedure but the repair failed and we weren’t sure if it should fail or shouldn’t.

Leave this issue open so we can change it back when we get answer how to make the repair passing

**Comment by fgelcer** [comment]
how does work the mechanism for a node to re-balance the vnodes after we remove a node?
maybe we need to wait for something before we are able to run repair on all nodes?
@asias , could you help us identify what we are missing?

**Comment by fruch** [comment]
This is the procedure that talks about nodetool removenode

https://docs.scylladb.com/operating-scylla/procedures/cluster-management/remove_node/

I still don't understand why do we try to repair before calling `nodetool removenode`

**Comment by fgelcer** [comment]
> This is the procedure that talks about nodetool removenode
> 
> https://docs.scylladb.com/operating-scylla/procedures/cluster-management/remove_node/
> 
> I still don't understand why do we try to repair before calling `nodetool removenode`

so, following this procedure we need to invert the order of the steps, and call `nodetool removenode <node>` before we run full repair...
@roydahan , should we try it?

**Comment by roydahan** [comment]
No, we need and we do both.
Before and after.

We need before because this is what is written in the procedure:

NOTE

Attention When using nodetool removenode, the data in the node is not streamed. For this reason, in order to be able to keep quorum consistencies it is extremely advisable to run a full cluster repair before nodetool removenode so all existing replicas have the most up to date data.


We do it to avoid data loss

**Comment by roydahan** [comment]
Not an issue.
