### ISSUE TITLE
collect logs for <test> box logs for jenkins pipeline has an exception and show an empty logs table, although they were collected

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylla-cluster-tests#2919]
### Versions
* **SCT**: ef35de973f418c5da934005664e2d58260536384

### Logs
* test_id: d8d14ce1-b384-4aa0-b80e-35c54607b7e4
* job log: https://jenkins.scylladb.com/job/scylla-staging/job/fabio/job/latency_automatic_calculation_regressions/job/perf-throughput-regression/

i have seen this before, but opening this task to track it, as it is failing for a while now.
in a Jenkins pipeline job, in the box called "Collect logs for test_write" (in my example the test name is <test_write>) it has an exception, and the logs table is empty:
```
ct-runner-d8d14ce1.zip
01:30:54  
01:30:54  +--------------------------------------------------------------------------------------------------------------------------------------------+
01:30:54  |                                      Collected logs by test-id: d8d14ce1-b384-4aa0-b80e-35c54607b7e4                                       |
01:30:54  +-------------+------------------------------------------------------------------------------------------------------------------------------+
01:30:54  | Cluster set | Link                                                                                                                         |
01:30:54  +-------------+------------------------------------------------------------------------------------------------------------------------------+
01:30:54  | db-cluster  | https://cloudius-jenkins-test.s3.amazonaws.com/d8d14ce1-b384-4aa0-b80e-35c54607b7e4/20201124_232141/db-cluster-d8d14ce1.zip  |
01:30:54  | monitor-set | https://cloudius-jenkins-test.s3.amazonaws.com/d8d14ce1-b384-4aa0-b80e-35c54607b7e4/20201124_232141/monitor-set-d8d14ce1.zip |
01:30:54  | loader-set  | https://cloudius-jenkins-test.s3.amazonaws.com/d8d14ce1-b384-4aa0-b80e-35c54607b7e4/20201124_232141/loader-set-d8d14ce1.zip  |
01:30:54  | sct-runner  | https://cloudius-jenkins-test.s3.amazonaws.com/d8d14ce1-b384-4aa0-b80e-35c54607b7e4/20201124_232141/sct-runner-d8d14ce1.zip  |
01:30:54  +-------------+------------------------------------------------------------------------------------------------------------------------------+
01:34:02  <sdcm.utils.remotewebbrowser.RemoteBrowser object at 0x7f193c8580d0>: some exception raised during container `web_driver' destroying
01:34:02  Traceback (most recent call last):
01:34:02    File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 384, in _make_request
01:34:02      six.raise_from(e, None)
01:34:02    File "<string>", line 2, in raise_from
01:34:02    File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 380, in _make_request
01:34:02      httplib_response = conn.getresponse()
01:34:02    File "/usr/local/lib/python3.8/http/client.py", line 1347, in getresponse
01:34:02      response.begin()
01:34:02    File "/usr/local/lib/python3.8/http/client.py", line 307, in begin
01:34:02      version, status, reason = self._read_status()
01:34:02    File "/usr/local/lib/python3.8/http/client.py", line 268, in _read_status
01:34:02      line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
01:34:02    File "/usr/local/lib/python3.8/site-packages/paramiko/file.py", line 291, in readline
01:34:02      new_data = self._read(n)
01:34:02    File "/usr/local/lib/python3.8/site-packages/paramiko/channel.py", line 1361, in _read
01:34:02      return self.channel.recv(size)
01:34:02    File "/usr/local/lib/python3.8/site-packages/paramiko/channel.py", line 701, in recv
01:34:02      raise socket.timeout()
01:34:02  socket.timeout
01:34:02  
01:34:02  During handling of the above exception, another exception occurred:
01:34:02  
01:34:02  Traceback (most recent call last):
01:34:02    File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
01:34:02      resp = conn.urlopen(
01:34:02    File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 637, in urlopen
01:34:02      retries = retries.increment(method, url, error=e, _pool=self,
01:34:02    File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 368, in increment
01:34:02      raise six.reraise(type(error), error, _stacktrace)
01:34:02    File "/usr/local/lib/python3.8/site-packages/urllib3/packages/six.py", line 686, in reraise
01:34:02      raise value
01:34:02    File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 597, in urlopen
01:34:02      httplib_response = self._make_request(conn, method, url,
01:34:02    File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 386, in _make_request
01:34:02      self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
01:34:02    File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
01:34:02      raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
01:34:02  urllib3.exceptions.ReadTimeoutError: SSHConnectionPool(host='localhost', port=None): Read timed out. (read timeout=180)
01:34:02  
01:34:02  During handling of the above exception, another exception occurred:
01:34:02  
01:34:02  Traceback (most recent call last):
01:34:02    File "/home/jenkins/slave/workspace/scylla-staging/fabio/latency_automatic_calculation_regressions/perf-throughput-regression@2/scylla-cluster-tests/sdcm/utils/remotewebbrowser.py", line 116, in destroy_container
01:34:02      if ContainerManager.get_container(self.node, name, raise_not_found_exc=False) is not None:
01:34:02    File "/home/jenkins/slave/workspace/scylla-staging/fabio/latency_automatic_calculation_regressions/perf-throughput-regression@2/scylla-cluster-tests/sdcm/utils/docker_utils.py", line 181, in get_container
01:34:02      container.reload()
01:34:02    File "/usr/local/lib/python3.8/site-packages/docker/models/resource.py", line 48, in reload
01:34:02      new_model = self.collection.get(self.id)
01:34:02    File "/usr/local/lib/python3.8/site-packages/docker/models/containers.py", line 880, in get
01:34:02      resp = self.client.api.inspect_container(container_id)
01:34:02    File "/usr/local/lib/python3.8/site-packages/docker/utils/decorators.py", line 19, in wrapped
01:34:02      return f(self, resource_id, *args, **kwargs)
01:34:02    File "/usr/local/lib/python3.8/site-packages/docker/api/container.py", line 758, in inspect_container
01:34:02      self._get(self._url("/containers/{0}/json", container)), True
01:34:02    File "/usr/local/lib/python3.8/site-packages/docker/utils/decorators.py", line 46, in inner
01:34:02      return f(self, *args, **kwargs)
01:34:02    File "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 230, in _get
01:34:02      return self.get(url, **self._set_request_timeout(kwargs))
01:34:02    File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 537, in get
01:34:02      return self.request('GET', url, **kwargs)
01:34:02    File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 524, in request
01:34:02      resp = self.send(prep, **send_kwargs)
01:34:02    File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 637, in send
01:34:02      r = adapter.send(request, **kwargs)
01:34:02    File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 529, in send
01:34:02      raise ReadTimeout(e, request=request)
01:34:02  requests.exceptions.ReadTimeout: SSHConnectionPool(host='localhost', port=None): Read timed out. (read timeout=180)
01:34:02  Exception ignored in: <function GrafanaSnapshot.__del__ at 0x7f193dd0a550>
01:34:02  Traceback (most recent call last):
01:34:02    File "/home/jenkins/slave/workspace/scylla-staging/fabio/latency_automatic_calculation_regressions/perf-throughput-regression@2/scylla-cluster-tests/sdcm/logcollector.py", line 607, in __del__
01:34:02    File "/home/jenkins/slave/workspace/scylla-staging/fabio/latency_automatic_calculation_regressions/perf-throughput-regression@2/scylla-cluster-tests/sdcm/logcollector.py", line 423, in destory_webdriver_container
01:34:02    File "/home/jenkins/slave/workspace/scylla-staging/fabio/latency_automatic_calculation_regressions/perf-throughput-regression@2/scylla-cluster-tests/sdcm/utils/remotewebbrowser.py", line 112, in destroy_containers
01:34:02    File "/home/jenkins/slave/workspace/scylla-staging/fabio/latency_automatic_calculation_regressions/perf-throughput-regression@2/scylla-cluster-tests/sdcm/utils/remotewebbrowser.py", line 121, in destroy_container
01:34:02    File "/usr/local/lib/python3.8/logging/__init__.py", line 1463, in error
01:34:02    File "/usr/local/lib/python3.8/logging/__init__.py", line 1577, in _log
01:34:02    File "/usr/local/lib/python3.8/logging/__init__.py", line 1587, in handle
01:34:02    File "/usr/local/lib/python3.8/logging/__init__.py", line 1649, in callHandlers
01:34:02    File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
01:34:02    File "/usr/local/lib/python3.8/logging/__init__.py", line 1182, in emit
01:34:02    File "/usr/local/lib/python3.8/logging/__init__.py", line 1172, in _open
01:34:02  NameError: name 'open' is not defined
01:34:02  + echo 'end collect logs'
01:34:02  end collect logs
```

**Comment by fgelcer** [comment]
here we can see the exception too:
https://jenkins.scylladb.com/job/scylla-staging/job/fabio/job/latency_automatic_calculation_regressions/job/perf-throughput-regression/4/execution/node/107/log/

**Comment by fruch** [comment]
can you explain what is empty exactly ?

**Comment by fruch** [comment]
> can you explain what is empty exactly ?

i.e. in what you attached here the table looks o.k.

**Comment by fruch** [comment]
you are talking about this ?
![image](https://user-images.githubusercontent.com/340979/100251504-85dd7a00-2f47-11eb-9438-10e985e2d30d.png)

**Comment by fruch** [comment]
it's a bug in jenkins CSS, it show the links in white, i.e. the text is there, and you can copy it.

the exceptions are not related to it, and they are probably issue with the snapshot of grafana, do you need it ? (the snapshot not the screenshots)
