### ISSUE TITLE
Exception: No db log from node

### ISSUE THREAD

**Issue by sitano** [scylladb/scylla-cluster-tests#2926]
Started seeing those:

```
08:47:11  2020-11-27 06:46:44.000: (InfoEvent Severity.NORMAL): message=TEST_END================================================================================
08:47:11  FAILED :(
08:47:11  
08:47:11  ======================================================================
08:47:11  ERROR: test_custom_time (longevity_test.LongevityTest)
08:47:11  Run cassandra-stress with params defined in data_dir/scylla.yaml
08:47:11  ----------------------------------------------------------------------
08:47:11  Traceback (most recent call last):
08:47:11    File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 111, in wrapper
08:47:11      return method(*args, **kwargs)
08:47:11    File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 109, in inner
08:47:11      res = func(*args, **kwargs)
08:47:11    File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 414, in setUp
08:47:11      self.legacy_init_nodes(db_cluster=self.db_cluster)
08:47:11    File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 353, in legacy_init_nodes
08:47:11      db_cluster.wait_for_init(node_list=db_cluster.seed_nodes)
08:47:11    File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3092, in wrapper
08:47:11      method(*args, **kwargs)
08:47:11    File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3731, in wait_for_init
08:47:11      wait.wait_for(self.verify_logging_from_nodes, nodes_list=node_list,
08:47:11    File "/home/ubuntu/scylla-cluster-tests/sdcm/wait.py", line 60, in wait_for
08:47:11      res = retry.call(func, **kwargs)
08:47:11    File "/usr/local/lib/python3.8/site-packages/tenacity/__init__.py", line 358, in call
08:47:11      do = self.iter(retry_state=retry_state)
08:47:11    File "/usr/local/lib/python3.8/site-packages/tenacity/__init__.py", line 331, in iter
08:47:11      raise retry_exc.reraise()
08:47:11    File "/usr/local/lib/python3.8/site-packages/tenacity/__init__.py", line 167, in reraise
08:47:11      raise self.last_attempt.result()
08:47:11    File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 432, in result
08:47:11      return self.__get_result()
08:47:11    File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
08:47:11      raise self._exception
08:47:11    File "/usr/local/lib/python3.8/site-packages/tenacity/__init__.py", line 361, in call
08:47:11      result = fn(*args, **kwargs)
08:47:11    File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3713, in verify_logging_from_nodes
08:47:11      raise Exception(error_msg)
08:47:11  Exception: No db log from node [Node longevity-ycsb-a-100M-master-db-node-75459fff-1 [13.48.1.237 | 10.0.0.185] (seed: True)] 
08:47:11  
08:47:11  ----------------------------------------------------------------------
```

Before this branch worked well. Failed 3 times conseq.

**Comment by fruch** [comment]
@sitano Can you share the link ? 

is this multi-dc ? or have you were running this locally ?

I'm guessing it might be this one #2921

**Comment by sitano** [comment]
@fruch yes, https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/ivan/job/ivan-byo-longevity/33/console. Also 31, 32, 33. It's single DC, single AZ.

**Comment by fruch** [comment]
@sitano 
any reason you are passing in the pipeline params ? 
```
ip_ssh_connections: public
```
I think that would trigger the usage of autossh too and you'll need #2921

**Comment by sitano** [comment]
@fruch no, I did not pay attention to it. I thought this setting means that the SCT will use public IP addresses for accessing cluster nodes. Is that correct? To enable 2921 I just need to rebase my branches?

**Comment by fruch** [comment]
Yes, and you can also try it with that setting private

**Comment by fruch** [comment]
I.e. you can still access those node from public ips, but the test itself would access them from private address

**Comment by fruch** [comment]
This setting is from when you aren't running the test from the same network as the nodes.

For debugging or for when we are running multi DC (or multi AZ, for that matter)

**Comment by sitano** [comment]
@fruch thank you! I will try rebase and private.

**Comment by sitano** [comment]
@fruch Thank you! everything works after rebase. With `private` I guess can't login into the nodes via SSH.
