### ISSUE TITLE
Error during GrowCluster nemesis

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla-cluster-tests#2991]
Master SCT (ef927cf7).

Every time GrowShrinkCluster nemesis runs, we get the following traceback.
(I used nemesis_add_node_cnt: 3, if it matters)

2020-12-09 23:58:23.172: (DisruptionEvent Severity.ERROR): type=GrowCluster subtype=end node=Node longevity-100gb-4h-test-asy-db-node-e6a19134-2 [54.246.69.67 | 10.0.0.76] (seed: True) duration=341 error='NoneType' object has no attribute 'running_nemesis'
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2678, in wrapper
result = method(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2743, in disrupt
self.disrupt_grow_shrink_cluster()
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2431, in disrupt_grow_shrink_cluster
self._disrupt_grow_shrink_cluster(rack=0)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2449, in _disrupt_grow_shrink_cluster
added_node.running_nemesis = None
AttributeError: 'NoneType' object has no attribute 'running_nemesis'

**Comment by roydahan** [comment]
Assigned to @fgelcer as the last one who touched this area.
Please check it.

**Comment by dkropachev** [comment]
https://github.com/scylladb/scylla-cluster-tests/pull/2992

**Comment by dkropachev** [comment]
fixed
