### ISSUE TITLE
c-s load called during nemesis (to create test bed) are failing - making nemesis to fail as tables are not being created

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylla-cluster-tests#3028]
### Versions
* **SCT**: branch-4.3
* **scylla**: 4.3.rc2-0.20201210.2148a194c21 with build-id e5eb54096ba980c90c06c4741b0356dea02dc4fa (ami-08aaddc100281dc7d on eu-north-1)

### Logs
* test_id: 8f3c83be-138b-4af3-a3c7-dc872c1c1f5b
* job log: https://jenkins.scylladb.com/job/scylla-4.3/job/Reproducers/job/scylla-jmx-crash-longevity-5000-tables/4/

### Description

for example, during `Refresh`:
```
2020-12-18 09:58:09.279: (DisruptionEvent Severity.NORMAL): type=Refresh subtype=start node=Node longevity-5000-tables-5k-table-db-node-8f3c83be-4 [13.49.23.191 | 10.0.1.242] (seed: False) duration=None
2020-12-18 10:03:26.547: (CassandraStressEvent Severity.NORMAL): type=start node=Node longevity-5000-tables-5k-table-loader-node-8f3c83be-4 [13.53.123.198 | 10.0.2.15] (seed: False)
stress_cmd=cassandra-stress write n=400000 cl=QUORUM -port jmx=6868 -mode native cql3 -schema keyspace=keyspace1 'replication(factor=1)' -log interval=5 -node 10.0.3.110
2020-12-18 10:03:26.692: (CassandraStressEvent Severity.ERROR): type=error node=Node longevity-5000-tables-5k-table-loader-node-8f3c83be-4 [13.53.123.198 | 10.0.2.15] (seed: False)
Stress command completed with bad status 1: /etc/profile.d/lang.sh: line 20: warning: setlocale: LC_COLLATE: cannot change locale (en_US.UTF-8)
...
2020-12-18 10:05:30.622: (DisruptionEvent Severity.ERROR): type=Refresh subtype=end node=Node longevity-5000-tables-5k-table-db-node-8f3c83be-4 [13.49.23.191 | 10.0.1.242] (seed: False) duration=441 error=Encountered a bad command exit code!

Command: 'cqlsh --no-color   --request-timeout=120 --connect-timeout=60  -e "SELECT * FROM keyspace1.standard1 LIMIT 1" 10.0.1.242 9042'

Exit code: 2

Stdout:



Stderr:

<stdin>:1:InvalidRequest: Error from server: code=2200 [Invalid query] message="Keyspace keyspace1 does not exist"


Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2692, in wrapper
    result = method(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2971, in disrupt
    self.call_random_disrupt_method()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 900, in call_random_disrupt_method
    self.execute_disrupt_method(disrupt_method)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 907, in execute_disrupt_method
    disrupt_method()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 714, in disrupt_nodetool_refresh
    result = self.target_node.run_cqlsh(query_cmd)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2718, in run_cqlsh
    cqlsh_out = self.remoter.run(cmd, timeout=timeout + 30,  # we give 30 seconds to cqlsh timeout mechanism to work
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in run
    result = _run()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 61, in inner
    return func(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 596, in _run
    return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
    result = connection.run(**command_kwargs)
  File "<decorator-gen-3>", line 2, in run
  File "/usr/local/lib/python3.9/site-packages/fabric/connection.py", line 30, in opens
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/fabric/connection.py", line 721, in run
    return self._run(self._remote_runner(), command, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/invoke/context.py", line 101, in _run
    return runner.run(command, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/invoke/runners.py", line 291, in run
    return self._run_body(command, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/invoke/runners.py", line 442, in _run_body
    raise UnexpectedExit(result)
invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!

Command: 'cqlsh --no-color   --request-timeout=120 --connect-timeout=60  -e "SELECT * FROM keyspace1.standard1 LIMIT 1" 10.0.1.242 9042'

Exit code: 2

Stdout:



Stderr:

<stdin>:1:InvalidRequest: Error from server: code=2200 [Invalid query] message="Keyspace keyspace1 does not exist"
```

here is a list of the errors:
```
< t:2020-12-17 17:50:52,479 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > Stress command completed with bad status 1: /etc/profile.d/lang.sh: line 20: warning: setlocale: LC_COLLATE: cannot change locale (en_US.UTF-8)
< t:2020-12-17 17:51:42,845 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > Stress command completed with bad status 1: /etc/profile.d/lang.sh: line 20: warning: setlocale: LC_COLLATE: cannot change locale (en_US.UTF-8)
< t:2020-12-17 17:52:33,824 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > Stress command completed with bad status 1: /etc/profile.d/lang.sh: line 20: warning: setlocale: LC_COLLATE: cannot change locale (en_US.UTF-8)
< t:2020-12-17 17:53:24,338 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > Stress command completed with bad status 1: /etc/profile.d/lang.sh: line 20: warning: setlocale: LC_COLLATE: cannot change locale (en_US.UTF-8)
< t:2020-12-17 17:54:14,826 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > Stress command completed with bad status 1: /etc/profile.d/lang.sh: line 20: warning: setlocale: LC_COLLATE: cannot change locale (en_US.UTF-8)
< t:2020-12-17 17:55:05,431 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > Stress command completed with bad status 1: /etc/profile.d/lang.sh: line 20: warning: setlocale: LC_COLLATE: cannot change locale (en_US.UTF-8)
< t:2020-12-17 17:55:55,929 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > Stress command completed with bad status 1: /etc/profile.d/lang.sh: line 20: warning: setlocale: LC_COLLATE: cannot change locale (en_US.UTF-8)
< t:2020-12-17 17:56:46,780 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > Stress command completed with bad status 1: /etc/profile.d/lang.sh: line 20: warning: setlocale: LC_COLLATE: cannot change locale (en_US.UTF-8)
< t:2020-12-17 17:57:37,542 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > Stress command completed with bad status 1: /etc/profile.d/lang.sh: line 20: warning: setlocale: LC_COLLATE: cannot change locale (en_US.UTF-8)
< t:2020-12-18 02:35:44,830 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > Stress command completed with bad status 1: /etc/profile.d/lang.sh: line 20: warning: setlocale: LC_COLLATE: cannot change locale (en_US.UTF-8)
< t:2020-12-18 02:42:26,310 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > Stress command completed with bad status 1: /etc/profile.d/lang.sh: line 20: warning: setlocale: LC_COLLATE: cannot change locale (en_US.UTF-8)
< t:2020-12-18 02:49:11,954 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > Stress command completed with bad status 1: /etc/profile.d/lang.sh: line 20: warning: setlocale: LC_COLLATE: cannot change locale (en_US.UTF-8)
< t:2020-12-18 02:55:51,484 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > Stress command completed with bad status 1: /etc/profile.d/lang.sh: line 20: warning: setlocale: LC_COLLATE: cannot change locale (en_US.UTF-8)
< t:2020-12-18 03:02:32,721 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > Stress command completed with bad status 1: /etc/profile.d/lang.sh: line 20: warning: setlocale: LC_COLLATE: cannot change locale (en_US.UTF-8)
< t:2020-12-18 03:09:14,543 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > Stress command completed with bad status 1: /etc/profile.d/lang.sh: line 20: warning: setlocale: LC_COLLATE: cannot change locale (en_US.UTF-8)
< t:2020-12-18 03:15:59,840 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > Stress command completed with bad status 1: /etc/profile.d/lang.sh: line 20: warning: setlocale: LC_COLLATE: cannot change locale (en_US.UTF-8)
< t:2020-12-18 03:22:45,461 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > Stress command completed with bad status 1: /etc/profile.d/lang.sh: line 20: warning: setlocale: LC_COLLATE: cannot change locale (en_US.UTF-8)
< t:2020-12-18 03:29:28,921 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > Stress command completed with bad status 1: /etc/profile.d/lang.sh: line 20: warning: setlocale: LC_COLLATE: cannot change locale (en_US.UTF-8)
< t:2020-12-18 03:36:17,099 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > Stress command completed with bad status 1: /etc/profile.d/lang.sh: line 20: warning: setlocale: LC_COLLATE: cannot change locale (en_US.UTF-8)
< t:2020-12-18 10:03:26,694 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > Stress command completed with bad status 1: /etc/profile.d/lang.sh: line 20: warning: setlocale: LC_COLLATE: cannot change locale (en_US.UTF-8)
< t:2020-12-19 06:59:10,891 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > Stress command completed with bad status 1: /etc/profile.d/lang.sh: line 20: warning: setlocale: LC_COLLATE: cannot change locale (en_US.UTF-8)
< t:2020-12-19 10:40:09,147 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > Stress command completed with bad status 1: /etc/profile.d/lang.sh: line 20: warning: setlocale: LC_COLLATE: cannot change locale (en_US.UTF-8)
```

**Comment by roydahan** [comment]
@fgelcer please fix it.

**Comment by fgelcer** [comment]
#3062
