### ISSUE TITLE
Rolling upgrade failed with 're.error: nothing to repeat at position 0'

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla-cluster-tests#3097]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Logs
* test_id: b4d869ee-b2ee-49af-971a-acfd32971d4c
* Job url: https://jenkins.scylladb.com/view/master/job/scylla-master/view/master-test/job/rolling-upgrade/job/rolling-upgrade-alternator-test/8/consoleFull
* job log: https://cloudius-jenkins-test.s3.amazonaws.com/b4d869ee-b2ee-49af-971a-acfd32971d4c/20210101_054519/db-cluster-b4d869ee.zip
* job log: https://cloudius-jenkins-test.s3.amazonaws.com/b4d869ee-b2ee-49af-971a-acfd32971d4c/20210101_054519/sct-runner-b4d869ee.zip

Error:
```
12:09:30  Exception in thread Thread-2:
12:09:30  Traceback (most recent call last):
12:09:30    File "/usr/local/lib/python3.9/threading.py", line 954, in _bootstrap_inner
12:09:30      self.run()
12:09:30    File "/jenkins/slave/workspace/scylla-master/rolling-upgrade/rolling-upgrade-alternator-test/scylla-cluster-tests/sdcm/sct_events/grafana.py", line 44, in run
12:09:30      for event_tuple in self.inbound_events():  # pylint: disable=no-member; pylint doesn't understand generics
12:09:30    File "/jenkins/slave/workspace/scylla-master/rolling-upgrade/rolling-upgrade-alternator-test/scylla-cluster-tests/sdcm/sct_events/events_processes.py", line 81, in inbound_events
12:09:30      yield from cast(OutboundEventsProtocol[T_inbound_event],
12:09:30    File "/jenkins/slave/workspace/scylla-master/rolling-upgrade/rolling-upgrade-alternator-test/scylla-cluster-tests/sdcm/sct_events/events_device.py", line 160, in outbound_events
12:09:30      obj_filtered = any([f.eval_filter(obj) for f in filters.values()])
12:09:30    File "/jenkins/slave/workspace/scylla-master/rolling-upgrade/rolling-upgrade-alternator-test/scylla-cluster-tests/sdcm/sct_events/events_device.py", line 160, in <listcomp>
12:09:30      obj_filtered = any([f.eval_filter(obj) for f in filters.values()])
12:09:30    File "/jenkins/slave/workspace/scylla-master/rolling-upgrade/rolling-upgrade-alternator-test/scylla-cluster-tests/sdcm/sct_events/filters.py", line 88, in eval_filter
12:09:30      if self._regex:
12:09:30    File "/usr/local/lib/python3.9/functools.py", line 969, in __get__
12:09:30  Process EventsFileLogger-2:
12:09:30      val = self.func(instance)
12:09:30    File "/jenkins/slave/workspace/scylla-master/rolling-upgrade/rolling-upgrade-alternator-test/scylla-cluster-tests/sdcm/sct_events/filters.py", line 78, in _regex
12:09:30      return self.regex and re.compile(self.regex, self.regex_flags)
12:09:30    File "/usr/local/lib/python3.9/re.py", line 252, in compile
12:09:30      return _compile(pattern, flags)
12:09:30    File "/usr/local/lib/python3.9/re.py", line 304, in _compile
12:09:30      p = sre_compile.compile(pattern, flags)
12:09:30    File "/usr/local/lib/python3.9/sre_compile.py", line 764, in compile
12:09:30      p = sre_parse.parse(p, flags)
12:09:30    File "/usr/local/lib/python3.9/sre_parse.py", line 948, in parse
12:09:30      p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
12:09:30    File "/usr/local/lib/python3.9/sre_parse.py", line 443, in _parse_sub
12:09:30      itemsappend(_parse(source, state, verbose, nested + 1,
12:09:30    File "/usr/local/lib/python3.9/sre_parse.py", line 668, in _parse
12:09:30  Exception in thread Thread-5:
12:09:30  Traceback (most recent call last):
12:09:30    File "/usr/local/lib/python3.9/threading.py", line 954, in _bootstrap_inner
12:09:30      self.run()
12:09:30    File "/jenkins/slave/workspace/scylla-master/rolling-upgrade/rolling-upgrade-alternator-test/scylla-cluster-tests/sdcm/sct_events/events_analyzer.py", line 39, in run
12:09:30      for event_tuple in self.inbound_events():
12:09:30    File "/jenkins/slave/workspace/scylla-master/rolling-upgrade/rolling-upgrade-alternator-test/scylla-cluster-tests/sdcm/sct_events/events_processes.py", line 81, in inbound_events
12:09:30      yield from cast(OutboundEventsProtocol[T_inbound_event],
12:09:30    File "/jenkins/slave/workspace/scylla-master/rolling-upgrade/rolling-upgrade-alternator-test/scylla-cluster-tests/sdcm/sct_events/events_device.py", line 160, in outbound_events
12:09:30      obj_filtered = any([f.eval_filter(obj) for f in filters.values()])
12:09:30    File "/jenkins/slave/workspace/scylla-master/rolling-upgrade/rolling-upgrade-alternator-test/scylla-cluster-tests/sdcm/sct_events/events_device.py", line 160, in <listcomp>
12:09:30      obj_filtered = any([f.eval_filter(obj) for f in filters.values()])
12:09:30    File "/jenkins/slave/workspace/scylla-master/rolling-upgrade/rolling-upgrade-alternator-test/scylla-cluster-tests/sdcm/sct_events/filters.py", line 88, in eval_filter
12:09:30      if self._regex:
12:09:30    File "/usr/local/lib/python3.9/functools.py", line 969, in __get__
12:09:30      val = self.func(instance)
12:09:30    File "/jenkins/slave/workspace/scylla-master/rolling-upgrade/rolling-upgrade-alternator-test/scylla-cluster-tests/sdcm/sct_events/filters.py", line 78, in _regex
12:09:30      return self.regex and re.compile(self.regex, self.regex_flags)
12:09:30    File "/usr/local/lib/python3.9/re.py", line 252, in compile
12:09:30      return _compile(pattern, flags)
12:09:30    File "/usr/local/lib/python3.9/re.py", line 304, in _compile
12:09:30      p = sre_compile.compile(pattern, flags)
12:09:30    File "/usr/local/lib/python3.9/sre_compile.py", line 764, in compile
12:09:30      p = sre_parse.parse(p, flags)
12:09:30    File "/usr/local/lib/python3.9/sre_parse.py", line 948, in parse
12:09:30      p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
12:09:30    File "/usr/local/lib/python3.9/sre_parse.py", line 443, in _parse_sub
12:09:30      itemsappend(_parse(source, state, verbose, nested + 1,
12:09:30    File "/usr/local/lib/python3.9/sre_parse.py", line 668, in _parse
12:09:30      raise source.error("nothing to repeat",
12:09:30  re.error: nothing to repeat at position 0
12:09:30      raise source.error("nothing to repeat",
12:09:30  re.error: nothing to repeat at position 0
12:09:30  Traceback (most recent call last):
12:09:30    File "/usr/local/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
12:09:30      self.run()
12:09:30    File "/jenkins/slave/workspace/scylla-master/rolling-upgrade/rolling-upgrade-alternator-test/scylla-cluster-tests/sdcm/sct_events/file_logger.py", line 69, in run
12:09:30      for event_tuple in self.inbound_events():
12:09:30    File "/jenkins/slave/workspace/scylla-master/rolling-upgrade/rolling-upgrade-alternator-test/scylla-cluster-tests/sdcm/sct_events/events_processes.py", line 81, in inbound_events
12:09:30      yield from cast(OutboundEventsProtocol[T_inbound_event],
12:09:30    File "/jenkins/slave/workspace/scylla-master/rolling-upgrade/rolling-upgrade-alternator-test/scylla-cluster-tests/sdcm/sct_events/events_device.py", line 160, in outbound_events
12:09:30      obj_filtered = any([f.eval_filter(obj) for f in filters.values()])
12:09:30    File "/jenkins/slave/workspace/scylla-master/rolling-upgrade/rolling-upgrade-alternator-test/scylla-cluster-tests/sdcm/sct_events/events_device.py", line 160, in <listcomp>
12:09:30      obj_filtered = any([f.eval_filter(obj) for f in filters.values()])
12:09:30    File "/jenkins/slave/workspace/scylla-master/rolling-upgrade/rolling-upgrade-alternator-test/scylla-cluster-tests/sdcm/sct_events/filters.py", line 88, in eval_filter
12:09:30      if self._regex:
12:09:30    File "/usr/local/lib/python3.9/functools.py", line 969, in __get__
12:09:30      val = self.func(instance)
12:09:30    File "/jenkins/slave/workspace/scylla-master/rolling-upgrade/rolling-upgrade-alternator-test/scylla-cluster-tests/sdcm/sct_events/filters.py", line 78, in _regex
12:09:30      return self.regex and re.compile(self.regex, self.regex_flags)
12:09:30    File "/usr/local/lib/python3.9/re.py", line 252, in compile
12:09:30      return _compile(pattern, flags)
12:09:30    File "/usr/local/lib/python3.9/re.py", line 304, in _compile
12:09:30      p = sre_compile.compile(pattern, flags)
12:09:30    File "/usr/local/lib/python3.9/sre_compile.py", line 764, in compile
12:09:30      p = sre_parse.parse(p, flags)
12:09:30    File "/usr/local/lib/python3.9/sre_parse.py", line 948, in parse
12:09:30      p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
12:09:30    File "/usr/local/lib/python3.9/sre_parse.py", line 443, in _parse_sub
12:09:30      itemsappend(_parse(source, state, verbose, nested + 1,
12:09:30    File "/usr/local/lib/python3.9/sre_parse.py", line 668, in _parse
12:09:30      raise source.error("nothing to repeat",
12:09:30  re.error: nothing to repeat at position 0
```

**Comment by fruch** [comment]
@Orenef11, can you take a quick look at that one ?

**Comment by Orenef11** [comment]
There is a open bug for that:
https://github.com/scylladb/scylla/issues/7819

The upgrade is failed.

**Comment by dkropachev** [comment]
Hello,

Issue fixed in here https://github.com/scylladb/scylla-cluster-tests/pull/3118

Thanks.
