### ISSUE TITLE
Issue with perf-regression-latency-250gb-with-nemesis test

### ISSUE THREAD

**Issue by asias** [scylladb/scylla-cluster-tests#3135]
I tried to run fabio's perf test and got some errors. I used the SCT stable branch below:

SCT commit: 8031577bedf8ea8ee051d84c09d7fdbfb0e62958 (perf-test-v10, origin/branch-perf-v10)

I added the following to test-cases/performance/perf-regression-latency-250gb-with-nemesis.yaml
```
region_name: 'us-east-1'
# Official 4.2.2
ami_id_db_scylla: 'ami-00c58bef44e987fb5'
update_db_packages: '/home/ubuntu/rpms/new_sched/x86_64'
```
Then, I ran the following command to start the tests inside a aws instance. I tried both centos and ubuntu as the host.

ubuntu@ip-172-31-4-101:~/scylla-cluster-tests$ hydra "run-test performance_regression_test.PerformanceRegressionTest --backend aws --config test-cases/performance/perf-regression-latency-250gb-with-nemesis.yaml"

I saw the following errors:
```
376 < t:2021-01-06 02:21:10,735 f:cluster.py      l:273  c:sdcm.cluster         p:INFO  > rsyslog listen on port 49154 (config: /tmp/sct-rsyslogpl7qe4xa.conf)
377 < t:2021-01-06 02:21:10,736 f:log.py          l:20   c:sdcm.utils.log       p:ERROR > Uncaught exception < t:2021-01-06 02:21:10,736 f:log.py          l:20   c:sdcm.utils.log       p:ERROR > Uncaught exception
378 < t:2021-01-06 02:21:10,736 f:log.py          l:20   c:sdcm.utils.log       p:ERROR > Traceback (most recent call last):
379 < t:2021-01-06 02:21:10,736 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "./sct.py", line 856, in <module>
380 < t:2021-01-06 02:21:10,736 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     cli()
381 < t:2021-01-06 02:21:10,736 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 764, in __call__
382 < t:2021-01-06 02:21:10,736 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     return self.main(*args, **kwargs)
383 < t:2021-01-06 02:21:10,736 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 717, in main
384 < t:2021-01-06 02:21:10,736 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     rv = self.invoke(ctx)
385 < t:2021-01-06 02:21:10,736 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
386 < t:2021-01-06 02:21:10,736 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     return _process_result(sub_ctx.command.invoke(sub_ctx))
387 < t:2021-01-06 02:21:10,736 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 956, in invoke
388 < t:2021-01-06 02:21:10,736 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     return ctx.invoke(self.callback, **ctx.params)
389 < t:2021-01-06 02:21:10,736 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 555, in invoke
390 < t:2021-01-06 02:21:10,736 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     return callback(*args, **kwargs)
391 < t:2021-01-06 02:21:10,736 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "./sct.py", line 618, in run_test
392 < t:2021-01-06 02:21:10,736 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     unittest.main(module=None, argv=['python -m unittest', argv],
393 < t:2021-01-06 02:21:10,736 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/usr/local/lib/python3.8/unittest/main.py", line 100, in __init__
394 < t:2021-01-06 02:21:10,736 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     self.parseArgs(argv)
395 < t:2021-01-06 02:21:10,736 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/usr/local/lib/python3.8/unittest/main.py", line 147, in parseArgs
396 < t:2021-01-06 02:21:10,736 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     self.createTests()
397 < t:2021-01-06 02:21:10,736 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/usr/local/lib/python3.8/unittest/main.py", line 158, in createTests
398 < t:2021-01-06 02:21:10,736 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     self.test = self.testLoader.loadTestsFromNames(self.testNames,
399 < t:2021-01-06 02:21:10,736 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/usr/local/lib/python3.8/unittest/loader.py", line 220, in loadTestsFromNames
400 < t:2021-01-06 02:21:10,736 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     suites = [self.loadTestsFromName(name, module) for name in names]
401 < t:2021-01-06 02:21:10,736 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/usr/local/lib/python3.8/unittest/loader.py", line 220, in <listcomp>
402 < t:2021-01-06 02:21:10,736 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     suites = [self.loadTestsFromName(name, module) for name in names]
403 < t:2021-01-06 02:21:10,736 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/usr/local/lib/python3.8/unittest/loader.py", line 193, in loadTestsFromName
404 < t:2021-01-06 02:21:10,736 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     return self.loadTestsFromTestCase(obj)
405 < t:2021-01-06 02:21:10,736 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/usr/local/lib/python3.8/unittest/loader.py", line 93, in loadTestsFromTestCase
406 < t:2021-01-06 02:21:10,736 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     loaded_suite = self.suiteClass(map(testCaseClass, testCaseNames))
407 < t:2021-01-06 02:21:10,736 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/usr/local/lib/python3.8/unittest/suite.py", line 24, in __init__
408 < t:2021-01-06 02:21:10,736 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     self.addTests(tests)
409 < t:2021-01-06 02:21:10,736 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/usr/local/lib/python3.8/unittest/suite.py", line 57, in addTests
410 < t:2021-01-06 02:21:10,736 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     for test in tests:
411 < t:2021-01-06 02:21:10,736 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 302, in __init__
412 < t:2021-01-06 02:21:10,736 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     start_events_device(log_dir=self.logdir, _registry=self.events_processes_registry)
413 < t:2021-01-06 02:21:10,736 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/sct_events/setup.py", line 45, in start_events_device
414 < t:2021-01-06 02:21:10,736 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     _registry = create_default_events_process_registry(log_dir=log_dir)
415 < t:2021-01-06 02:21:10,736 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/sct_events/events_processes.py", line 162, in create_default_events_process_registry
416 < t:2021-01-06 02:21:10,736 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     raise RuntimeError("Try to create default EventsProcessRegistry second time")
417 < t:2021-01-06 02:21:10,736 f:log.py          l:20   c:sdcm.utils.log       p:ERROR > RuntimeError: Try to create default EventsProcessRegistry second time
```

Full logs attached. 

[sct.log2.txt](https://github.com/scylladb/scylla-cluster-tests/files/5814084/sct.log2.txt)

**Comment by fruch** [comment]
@enaydanov @fgelcer, can you look into what's the issue here ?

**Comment by fgelcer** [comment]
@fruch , Asias said you were able to reproduce this issue on SCT master... do you have an issue number, or more details about it?

**Comment by fgelcer** [comment]
with the help of @enaydanov we were able to find the issue, and right now @asias is running a test, hence closing this issue
