### ISSUE TITLE
centos-7 rolling upgrade fails with: "Unable to curl repository file https://download.docker.com/linux/centos/docker-ce.repo"

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#3158]
ERROR:
```
2021-01-19 09:09:10.180: (TestFrameworkEvent Severity.ERROR), source=UpgradeTest.SetUp()
exception=[Node rolling-upgrade-master-centos-loader-node-e8b8b2e4-0-1 [35.237.226.154 | 10.142.15.216] (seed: False)] NodeSetupFailed: Encountered a bad command exit code!
Command: 'sudo bash -cxe "\ncurl -fsSL get.docker.com -o get-docker.sh\nsh get-docker.sh\nsystemctl enable docker\nsystemctl start docker\n"'
Exit code: 1
Stdout:
# Executing docker install script, commit: 3d8fe77c2c46c5b7571f94b42793905e5b3e42e4
Error: Unable to curl repository file https://download.docker.com/linux/centos/docker-ce.repo, is it valid?
Stderr:
+ curl -fsSL get.docker.com -o get-docker.sh
+ sh get-docker.sh
Traceback (most recent call last):
File "/jenkins/slave/workspace/scylla-master/rolling-upgrade/rolling-upgrade-centos7-test/scylla-cluster-tests/sdcm/cluster.py", line 3268, in node_setup
cl_inst.node_setup(_node, **setup_kwargs)
File "/jenkins/slave/workspace/scylla-master/rolling-upgrade/rolling-upgrade-centos7-test/scylla-cluster-tests/sdcm/cluster.py", line 4267, in node_setup
node.remoter.run('sudo bash -cxe "%s"' % docker_install)
File "/jenkins/slave/workspace/scylla-master/rolling-upgrade/rolling-upgrade-centos7-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in run
result = _run()
File "/jenkins/slave/workspace/scylla-master/rolling-upgrade/rolling-upgrade-centos7-test/scylla-cluster-tests/sdcm/utils/decorators.py", line 61, in inner
return func(*args, **kwargs)
File "/jenkins/slave/workspace/scylla-master/rolling-upgrade/rolling-upgrade-centos7-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 596, in _run
return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
File "/jenkins/slave/workspace/scylla-master/rolling-upgrade/rolling-upgrade-centos7-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
result = connection.run(**command_kwargs)
File "<decorator-gen-3>", line 2, in run
File "/usr/local/lib/python3.9/site-packages/fabric/connection.py", line 30, in opens
return method(self, *args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/fabric/connection.py", line 721, in run
return self._run(self._remote_runner(), command, **kwargs)
File "/usr/local/lib/python3.9/site-packages/invoke/context.py", line 101, in _run
return runner.run(command, **kwargs)
File "/usr/local/lib/python3.9/site-packages/invoke/runners.py", line 291, in run
return self._run_body(command, **kwargs)
File "/usr/local/lib/python3.9/site-packages/invoke/runners.py", line 442, in _run_body
raise UnexpectedExit(result)
invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!
Command: 'sudo bash -cxe "\ncurl -fsSL get.docker.com -o get-docker.sh\nsh get-docker.sh\nsystemctl enable docker\nsystemctl start docker\n"'
Exit code: 1
Stdout:
# Executing docker install script, commit: 3d8fe77c2c46c5b7571f94b42793905e5b3e42e4
Error: Unable to curl repository file https://download.docker.com/linux/centos/docker-ce.repo, is it valid?
Stderr:
+ curl -fsSL get.docker.com -o get-docker.sh
+ sh get-docker.sh
```

Test details
Test: upgrade_test.UpgradeTest.test_rolling_upgrade
Build number: 138
Backend: gce: us-east1
Test-id: e8b8b2e4-339b-46d9-a6b4-2c10504ed312
Start time: 2021-01-19 08:33:03
End time: 2021-01-19 09:09:18
Started by user: yarongilor
Test result
FAILED
System under test
ScyllaDB version: 4.3.0-0.20210110.000585522 with build-id 7fab6c35a5d403f3416292b37c9a9aa94fe4db1f (-)
Target ScyllaDB repo: https://s3.amazonaws.com/downloads.scylladb.com/rpm/unstable/centos/master/latest/scylla.repo
Instance type: i3.2xlarge
Number of ScyllaDB nodes: 4

Hydra commands:
Restore Monitor Stack command: $ hydra investigate show-monitor e8b8b2e4-339b-46d9-a6b4-2c10504ed312
Show all stored logs command: $ hydra investigate show-logs e8b8b2e4-339b-46d9-a6b4-2c10504ed312
Logs:
db-cluster - https://cloudius-jenkins-test.s3.amazonaws.com/e8b8b2e4-339b-46d9-a6b4-2c10504ed312/20210119_090946/db-cluster-e8b8b2e4.zip
loader-set - https://cloudius-jenkins-test.s3.amazonaws.com/e8b8b2e4-339b-46d9-a6b4-2c10504ed312/20210119_090946/loader-set-e8b8b2e4.zip
monitor-set - https://cloudius-jenkins-test.s3.amazonaws.com/e8b8b2e4-339b-46d9-a6b4-2c10504ed312/20210119_090946/monitor-set-e8b8b2e4.zip
sct-runner - https://cloudius-jenkins-test.s3.amazonaws.com/e8b8b2e4-339b-46d9-a6b4-2c10504ed312/20210119_090946/sct-runner-e8b8b2e4.zip

**Comment by fruch** [comment]
@yarongilor how many time this happens ? seem like a temporary network issue, case that URL is available (at least from my laptop)

**Comment by roydahan** [comment]
This repository doesn't accept issues like this.
If you know what is the issue, send PR.
If not, drill down into it and specify which part of SCT is broken.
