### ISSUE TITLE
Enterprise: Unified-deb artifact tests fail

### ISSUE THREAD

**Issue by hagitsegev** [scylladb/scylla-cluster-tests#3189]
On enterprise:
Unified-deb artifact tests (16.04, 18.04, deb9, deb10): 
https://jenkins.scylladb.com/view/nexts/job/scylla-enterprise/job/artifacts/job/artifacts-debian10-test/82/parameters/ scylla_repo is http://downloads.scylladb.com/unstable/scylla-enterprise/enterprise/deb/unified/2021-01-27T17:19:16Z/scylladb-enterprise/scylla.list which is OK.
In [log](https://jenkins.scylladb.com/view/nexts/job/scylla-enterprise/job/artifacts/job/artifacts-debian10-test/82/consoleText): 
```
[2021-01-29T02:53:25.638Z] < t:2021-01-29 02:53:20,692 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > subprocess.CalledProcessError: Command 'systemctl  cat scylla-node-exporter' returned non-zero exit status 1.
[2021-01-29T02:53:25.638Z] < t:2021-01-29 02:53:20,692 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > 
[2021-01-29T02:53:25.638Z] < t:2021-01-29 02:53:20,692 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > During handling of the above exception, another exception occurred:
[2021-01-29T02:53:25.638Z] < t:2021-01-29 02:53:20,692 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > 
[2021-01-29T02:53:25.638Z] < t:2021-01-29 02:53:20,692 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > Traceback (most recent call last):
[2021-01-29T02:53:25.638Z] < t:2021-01-29 02:53:20,692 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >   File "/opt/scylladb/scripts/libexec/scylla_setup", line 507, in <module>
[2021-01-29T02:53:25.638Z] < t:2021-01-29 02:53:20,692 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >     node_exporter_unit = systemd_unit('scylla-node-exporter')
[2021-01-29T02:53:25.638Z] < t:2021-01-29 02:53:20,692 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >   File "/opt/scylladb/scripts/scylla_util.py", line 759, in __init__
[2021-01-29T02:53:25.638Z] < t:2021-01-29 02:53:20,692 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >     raise SystemdException('unit {} is not found or invalid'.format(unit))
[2021-01-29T02:53:25.638Z] < t:2021-01-29 02:53:20,692 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > scylla_util.SystemdException: unit scylla-node-exporter is not found or invalid
[2021-01-29T02:53:25.638Z] < t:2021-01-29 02:53:20,692 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > 
[2021-01-29T02:53:25.638Z] < t:2021-01-29 02:53:20,692 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > 
[2021-01-29T02:53:25.638Z] < t:2021-01-29 02:53:20,692 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > Traceback (most recent call last):
[2021-01-29T02:53:25.638Z] < t:2021-01-29 02:53:20,692 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >   File "/jenkins/slave/workspace/scylla-enterprise/artifacts/artifacts-debian10-test/scylla-cluster-tests/sdcm/cluster.py", line 3273, in node_setup
[2021-01-29T02:53:25.638Z] < t:2021-01-29 02:53:20,692 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >     cl_inst.node_setup(_node, **setup_kwargs)
[2021-01-29T02:53:25.638Z] < t:2021-01-29 02:53:20,692 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >   File "/jenkins/slave/workspace/scylla-enterprise/artifacts/artifacts-debian10-test/scylla-cluster-tests/sdcm/cluster.py", line 3915, in node_setup
[2021-01-29T02:53:25.638Z] < t:2021-01-29 02:53:20,692 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >     self._scylla_post_install(node, install_scylla, devname)
[2021-01-29T02:53:25.638Z] < t:2021-01-29 02:53:20,692 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >   File "/jenkins/slave/workspace/scylla-enterprise/artifacts/artifacts-debian10-test/scylla-cluster-tests/sdcm/cluster.py", line 3983, in _scylla_post_install
[2021-01-29T02:53:25.638Z] < t:2021-01-29 02:53:20,692 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >     node.scylla_setup(disks, devname)
[2021-01-29T02:53:25.638Z] < t:2021-01-29 02:53:20,692 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >   File "/jenkins/slave/workspace/scylla-enterprise/artifacts/artifacts-debian10-test/scylla-cluster-tests/sdcm/utils/decorators.py", line 110, in inner
[2021-01-29T02:53:25.638Z] < t:2021-01-29 02:53:20,692 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >     res = func(*args, **kwargs)
[2021-01-29T02:53:25.638Z] < t:2021-01-29 02:53:20,692 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >   File "/jenkins/slave/workspace/scylla-enterprise/artifacts/artifacts-debian10-test/scylla-cluster-tests/sdcm/cluster.py", line 2184, in scylla_setup
[2021-01-29T02:53:25.638Z] < t:2021-01-29 02:53:20,692 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >     self.remoter.run('sudo /usr/lib/scylla/scylla_setup --nic {} --disks {} --setup-nic-and-disks {}'
[2021-01-29T02:53:25.638Z] < t:2021-01-29 02:53:20,692 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >   File "/jenkins/slave/workspace/scylla-enterprise/artifacts/artifacts-debian10-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in run
[2021-01-29T02:53:25.638Z] < t:2021-01-29 02:53:20,692 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >     result = _run()
[2021-01-29T02:53:25.638Z] < t:2021-01-29 02:53:20,692 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >   File "/jenkins/slave/workspace/scylla-enterprise/artifacts/artifacts-debian10-test/scylla-cluster-tests/sdcm/utils/decorators.py", line 61, in inner
[2021-01-29T02:53:25.639Z] < t:2021-01-29 02:53:20,692 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >     return func(*args, **kwargs)
[2021-01-29T02:53:25.639Z] < t:2021-01-29 02:53:20,692 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >   File "/jenkins/slave/workspace/scylla-enterprise/artifacts/artifacts-debian10-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 596, in _run
[2021-01-29T02:53:25.639Z] < t:2021-01-29 02:53:20,692 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >     return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
[2021-01-29T02:53:25.639Z] < t:2021-01-29 02:53:20,692 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >   File "/jenkins/slave/workspace/scylla-enterprise/artifacts/artifacts-debian10-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
[2021-01-29T02:53:25.639Z] < t:2021-01-29 02:53:20,692 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >     result = connection.run(**command_kwargs)
[2021-01-29T02:53:25.639Z] < t:2021-01-29 02:53:20,692 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >   File "<decorator-gen-3>", line 2, in run
[2021-01-29T02:53:25.639Z] < t:2021-01-29 02:53:20,692 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >   File "/usr/local/lib/python3.9/site-packages/fabric/connection.py", line 30, in opens
[2021-01-29T02:53:25.639Z] < t:2021-01-29 02:53:20,692 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >     return method(self, *args, **kwargs)
[2021-01-29T02:53:25.639Z] < t:2021-01-29 02:53:20,692 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >   File "/usr/local/lib/python3.9/site-packages/fabric/connection.py", line 721, in run
[2021-01-29T02:53:25.639Z] < t:2021-01-29 02:53:20,692 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >     return self._run(self._remote_runner(), command, **kwargs)
[2021-01-29T02:53:25.639Z] < t:2021-01-29 02:53:20,692 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >   File "/usr/local/lib/python3.9/site-packages/invoke/context.py", line 101, in _run
[2021-01-29T02:53:25.639Z] < t:2021-01-29 02:53:20,692 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >     return runner.run(command, **kwargs)
[2021-01-29T02:53:25.639Z] < t:2021-01-29 02:53:20,692 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >   File "/usr/local/lib/python3.9/site-packages/invoke/runners.py", line 291, in run
[2021-01-29T02:53:25.639Z] < t:2021-01-29 02:53:20,692 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >     return self._run_body(command, **kwargs)
[2021-01-29T02:53:25.639Z] < t:2021-01-29 02:53:20,692 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >   File "/usr/local/lib/python3.9/site-packages/invoke/runners.py", line 442, in _run_body
[2021-01-29T02:53:25.639Z] < t:2021-01-29 02:53:20,692 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >     raise UnexpectedExit(result)
[2021-01-29T02:53:25.639Z] < t:2021-01-29 02:53:20,692 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!
[2021-01-29T02:53:25.639Z] < t:2021-01-29 02:53:20,692 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > 
[2021-01-29T02:53:25.639Z] < t:2021-01-29 02:53:20,692 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > Command: 'sudo /usr/lib/scylla/scylla_setup --nic ens5 --disks /dev/nvme0n1 --setup-nic-and-disks  --swap-directory / '
```
Similar errors on:
https://jenkins.scylladb.com/view/nexts/job/scylla-enterprise/job/artifacts/job/artifacts-debian9-test/83/consoleFull
https://jenkins.scylladb.com/view/nexts/job/scylla-enterprise/job/artifacts/job/artifacts-ubuntu1604-test/83/consoleFull
https://jenkins.scylladb.com/view/nexts/job/scylla-enterprise/job/artifacts/job/artifacts-ubuntu1804-test/82/consoleFull

**Comment by dkropachev** [comment]
Problem is not reproducing lately
