### ISSUE TITLE
during get_node_info_list, 'nodetool status' fails and expansion not catched. decommission not completed

### ISSUE THREAD

**Issue by harelassayag** [scylladb/scylla-cluster-tests#326]
during get_node_info_list, 'nodetool status' fails and expansion not catched . as result, decommission not completed.
### relevent code lines:
https://github.com/scylladb/scylla-cluster-tests/blob/master/sdcm/nemesis.py#L220
https://github.com/scylladb/scylla-cluster-tests/blob/master/sdcm/cluster.py#L1589-L1613
### log:
```
2017-07-20 17:41:43,052 remote           L0197 DEBUG| [10.240.0.89] [stdout] Jul 20 17:41:43 info   |  [shard 0] storage_service - DECOMMISSIONING: done
2017-07-20 17:41:43,066 remote           L0197 DEBUG| [10.240.0.89] [stderr] Connection to 10.240.0.89 closed.
2017-07-20 17:41:43,067 nemesis          L0113 DEBUG| sdcm.nemesis.ChaosMonkey: Command '/bin/ssh -tt -a -x   -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpft6vnJ -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l scylla-test -p 22 -i /jenkins/.ssh/scylla-test 10.240.0.89 "nodetool --host localhost decommission"' duration -> 2667.3868649 s
2017-07-20 17:41:43,067 remote           L0894 DEBUG| Remote [scylla-test@10.240.0.83]: Running 'nodetool status'
2017-07-20 17:41:43,068 remote           L0097 INFO | [10.240.0.83] Running '/bin/ssh -tt -a -x   -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpRhXPIY -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l scylla-test -p 22 -i /jenkins/.ssh/scylla-test 10.240.0.83 "nodetool status"'
2017-07-20 17:41:43,609 remote           L0197 DEBUG| [10.240.0.83] [stdout] Cassandra 3.0 and later require Java 8u40 or later.
2017-07-20 17:41:43,612 remote           L0197 DEBUG| [10.240.0.83] [stderr] Connection to 10.240.0.83 closed.
2017-07-20 17:41:43,613 nemesis          L0368 ERROR| sdcm.nemesis.ChaosMonkey: Unhandled exception in method <function disrupt at 0x49736e0>
Traceback (most recent call last):
  File "/jenkins/slave/workspace/scylla-2.0-longevity-1TB-gce/label/gce/sdcm/nemesis.py", line 365, in wrapper
    result = method(*args, **kwargs)
  File "/jenkins/slave/workspace/scylla-2.0-longevity-1TB-gce/label/gce/sdcm/nemesis.py", line 481, in disrupt
    self.call_random_disrupt_method()
  File "/jenkins/slave/workspace/scylla-2.0-longevity-1TB-gce/label/gce/sdcm/nemesis.py", line 327, in call_random_disrupt_method
    disrupt_method()
  File "/jenkins/slave/workspace/scylla-2.0-longevity-1TB-gce/label/gce/sdcm/nemesis.py", line 220, in disrupt_nodetool_decommission
    node_info_list = self.cluster.get_node_info_list(verification_node)
  File "/jenkins/slave/workspace/scylla-2.0-longevity-1TB-gce/label/gce/sdcm/cluster.py", line 1591, in get_node_info_list
    cmd_result = verification_node.remoter.run('nodetool status')
  File "/jenkins/slave/workspace/scylla-2.0-longevity-1TB-gce/label/gce/sdcm/remote.py", line 905, in run
    watch_stdout_pattern=watch_stdout_pattern)
  File "/jenkins/slave/workspace/scylla-2.0-longevity-1TB-gce/label/gce/sdcm/remote.py", line 849, in _run
    watch_stdout_pattern=watch_stdout_pattern)
  File "/jenkins/slave/workspace/scylla-2.0-longevity-1TB-gce/label/gce/sdcm/remote.py", line 228, in ssh_run
    raise process.CmdError(cmd, sp.result)
CmdError: Command '/bin/ssh -tt -a -x   -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpRhXPIY -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l scylla-test -p 22 -i /jenkins/.ssh/scylla-test 10.240.0.83 "nodetool status"' failed (rc=1)
2017-07-20 17:41:43,615 nemesis          L0376 DEBUG| sdcm.nemesis.ChaosMonkey: Decommission Node terabyte-longevity-scylla-2-0-scylla-db-node-33cebc9d-3 [35.190.162.239 | 10.240.0.89] (seed: False) duration -> 2668 s
2017-07-20 17:41:43,615 remote           L0894 DEBUG| Remote [scylla-test@10.240.0.75]: Running 'nodetool status'
2017-07-20 17:41:43,615 remote           L0097 INFO | [10.240.0.75] Running '/bin/ssh -tt -a -x   -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpJYq7V6 -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l scylla-test -p 22 -i /jenkins/.ssh/scylla-test 10.240.0.75 "nodetool status"'
2017-07-20 17:41:44,181 remote           L0197 DEBUG| [10.240.0.75] [stdout] Cassandra 3.0 and later require Java 8u40 or later.
2017-07-20 17:41:44,182 remote           L0197 DEBUG| [10.240.0.75] [stderr] Connection to 10.240.0.75 closed.
2017-07-20 17:41:45,072 nemesis          L0119 ERROR| sdcm.nemesis.ChaosMonkey: nodetool command 'nodetool status' failed on node Node terabyte-longevity-scylla-2-0-scylla-db-node-33cebc9d-3 [35.190.162.239 | 10.240.0.89] (seed: False): Command: /bin/ssh -tt -a -x   -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpJYq7V6 -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l scylla-test -p 22 -i /jenkins/.ssh/scylla-test 10.240.0.75 "nodetool status"
Exit status: 1
Duration: 0.557344913483
```

**Comment by amoskong** [comment]
Fixed by 14a11b12
