### ISSUE TITLE
gemini-1tb-10h fails to report email on master

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#3283]
seem like this job is failing like this for months now since this change:
https://github.com/scylladb/scylla-cluster-tests/commit/038b183ccc313891f096929b55d15a5592f3f9dc

```
22:01:53  2021-03-02 20:01:47.175: (TestFrameworkEvent Severity.ERROR), source=GeminiTest.save_email_data() message=save_email_data (silenced) failed with:
22:01:53  exception='cmd'
22:01:53  Traceback (most recent call last):
22:01:53  File "/home/ubuntu/scylla-cluster-tests/./sct.py", line 904, in <module>
22:01:53  cli()
22:01:53  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 764, in __call__
22:01:53  return self.main(*args, **kwargs)
22:01:53  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 717, in main
22:01:53  rv = self.invoke(ctx)
22:01:53  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1137, in invoke
22:01:53  return _process_result(sub_ctx.command.invoke(sub_ctx))
22:01:53  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 956, in invoke
22:01:53  return ctx.invoke(self.callback, **ctx.params)
22:01:53  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 555, in invoke
22:01:53  return callback(*args, **kwargs)
22:01:53  File "/home/ubuntu/scylla-cluster-tests/./sct.py", line 656, in run_test
22:01:53  unittest.main(module=None, argv=['python -m unittest', argv],
22:01:53  File "/usr/local/lib/python3.9/unittest/main.py", line 101, in __init__
22:01:53  self.runTests()
22:01:53  File "/usr/local/lib/python3.9/unittest/main.py", line 271, in runTests
22:01:53  self.result = testRunner.run(self.test)
22:01:53  File "/usr/local/lib/python3.9/unittest/runner.py", line 176, in run
22:01:53  test(result)
22:01:53  File "/usr/local/lib/python3.9/unittest/suite.py", line 84, in __call__
22:01:53  return self.run(*args, **kwds)
22:01:53  File "/usr/local/lib/python3.9/unittest/suite.py", line 122, in run
22:01:53  test(result)
22:01:53  File "/usr/local/lib/python3.9/unittest/suite.py", line 84, in __call__
22:01:53  return self.run(*args, **kwds)
22:01:53  File "/usr/local/lib/python3.9/unittest/suite.py", line 122, in run
22:01:53  test(result)
22:01:53  File "/usr/local/lib/python3.9/unittest/case.py", line 653, in __call__
22:01:53  return self.run(*args, **kwds)
22:01:53  File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 356, in run
22:01:53  result = super(ClusterTester, self).run(self.result)
22:01:53  File "/usr/local/lib/python3.9/unittest/case.py", line 596, in run
22:01:53  self._callTearDown()
22:01:53  File "/usr/local/lib/python3.9/unittest/case.py", line 553, in _callTearDown
22:01:53  self.tearDown()
22:01:53  File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 2054, in tearDown
22:01:53  self.save_email_data()
22:01:53  File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 177, in decor
22:01:53  self._store_test_result(args[0], exc, exc.__traceback__, name)
```

**Comment by aleksbykov** [comment]
PR: https://github.com/scylladb/scylla-cluster-tests/pull/3208 should fix the issue
