### ISSUE TITLE
An error occurred (InvalidAllocationID.NotFound) when calling the AssociateAddress operation

### ISSUE THREAD

**Issue by avelanarius** [scylladb/scylla-cluster-tests#3327]
### Prerequisites

* *Are you rebased to master?* **No, I was told that branch-4.4 is most stable.**
* *Is it reproducible?* **No, the next time it worked correctly.**
* *Did you perform a cursory search if this issue isn't opened?* **Yes.**

### Versions
* **SCT**: branch-4.4
* **scylla**: branch-4.4:latest (but the test did not go that far)

### Logs
* test_id: a618e574-fdf3-40ee-b4d8-79880c987848
* job log: https://cloudius-jenkins-test.s3.amazonaws.com/a618e574-fdf3-40ee-b4d8-79880c987848/20210318_151559/sct-runner-a618e574.zip

### Description

The Jenkins job failed with the following exception:
```
16:15:38  ======================================================================
16:15:38  ERROR: test_replication_longevity (cdc_replication_test.CDCReplicationTest)
16:15:38  ----------------------------------------------------------------------
16:15:38  Traceback (most recent call last):
16:15:38    File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 121, in wrapper
16:15:38      return method(*args, **kwargs)
16:15:38    File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 110, in inner
16:15:38      res = func(*args, **kwargs)
16:15:38    File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 447, in setUp
16:15:38      self.init_resources()
16:15:38    File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 1075, in init_resources
16:15:38      self.get_cluster_aws(loader_info=loader_info, db_info=db_info,
16:15:38    File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 826, in get_cluster_aws
16:15:38      self.db_cluster = create_cluster('scylla')
16:15:38    File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 785, in create_cluster
16:15:38      return ScyllaAWSCluster(
16:15:38    File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster_aws.py", line 850, in __init__
16:15:38      super(ScyllaAWSCluster, self).__init__(ec2_ami_id=ec2_ami_id,
16:15:38    File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3377, in __init__
16:15:38      super(BaseScyllaCluster, self).__init__(*args, **kwargs)
16:15:38    File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster_aws.py", line 101, in __init__
16:15:38      super(AWSCluster, self).__init__(cluster_uuid=cluster_uuid,
16:15:38    File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2934, in __init__
16:15:38      self.add_nodes(num, dc_idx=dc_idx, enable_auto_bootstrap=Setup.AUTO_BOOTSTRAP)
16:15:38    File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster_aws.py", line 887, in add_nodes
16:15:38      added_nodes = super(ScyllaAWSCluster, self).add_nodes(count=count,
16:15:38    File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster_aws.py", line 438, in add_nodes
16:15:38      added_nodes = [self._create_node(instance, self._ec2_ami_username,
16:15:38    File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster_aws.py", line 438, in <listcomp>
16:15:38      added_nodes = [self._create_node(instance, self._ec2_ami_username,
16:15:38    File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster_aws.py", line 459, in _create_node
16:15:38      node.init()
16:15:38    File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster_aws.py", line 496, in init
16:15:38      self.allocate_and_attach_elastic_ip(self.parent_cluster, self.dc_idx)
16:15:38    File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster_aws.py", line 602, in allocate_and_attach_elastic_ip
16:15:38      client.associate_address(
16:15:38    File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 357, in _api_call
16:15:38      return self._make_api_call(operation_name, kwargs)
16:15:38    File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 676, in _make_api_call
16:15:38      raise error_class(parsed_response, operation_name)
16:15:38  botocore.exceptions.ClientError: An error occurred (InvalidAllocationID.NotFound) when calling the AssociateAddress operation: The allocation ID 'eipalloc-0c7cfb407bfaabf99' does not exist
``` 

It seems like some race condition when interacting with AWS API (associating Elastic IP Address).

Next time running (rebuild), this issue was not present. 

### Steps to Reproduce

Could not reproduce.

**Expected behavior:** Jenkins job with SCT running without crashing.

**Actual behavior:** Jenkins job with SCT crashed.

**Comment by kbr-** [comment]
Just hit the same issue:
https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/KamilBraun/job/cdc-replication-longevity/9/consoleText
```
[2021-04-01T14:03:13.225Z] < t:2021-04-01 14:03:08,887 f:nemesis.py      l:1085 c:sdcm.nemesis         p:ERROR > sdcm.nemesis.CategoricalMonkey: ('Exception in random_disrupt_method %s: %s', 'nodetool_decommission', ClientError("An error occurred (InvalidAllocationID.NotFound) when calling the ReleaseAddress operation: The allocation ID 'eipalloc-0e436efa0716cc0ad' does not exist"))
[2021-04-01T14:03:13.225Z] < t:2021-04-01 14:03:08,888 f:nemesis.py      l:2907 c:sdcm.nemesis         p:ERROR > sdcm.nemesis.CategoricalMonkey: Unhandled exception in method <function CategoricalMonkey.disrupt at 0x7f817e2a1790> < t:2021-04-01 14:03:08,888 f:nemesis.py      l:2907 c:sdcm.nemesis         p:ERROR > sdcm.nemesis.CategoricalMonkey: Unhandled exception in method <function CategoricalMonkey.disrupt at 0x7f817e2a1790>
[2021-04-01T14:03:13.225Z] < t:2021-04-01 14:03:08,888 f:nemesis.py      l:2907 c:sdcm.nemesis         p:ERROR > Traceback (most recent call last):
[2021-04-01T14:03:13.226Z] < t:2021-04-01 14:03:08,888 f:nemesis.py      l:2907 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2897, in wrapper
[2021-04-01T14:03:13.226Z] < t:2021-04-01 14:03:08,888 f:nemesis.py      l:2907 c:sdcm.nemesis         p:ERROR >     result = method(*args, **kwargs)
[2021-04-01T14:03:13.226Z] < t:2021-04-01 14:03:08,888 f:nemesis.py      l:2907 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3270, in disrupt
[2021-04-01T14:03:13.226Z] < t:2021-04-01 14:03:08,888 f:nemesis.py      l:2907 c:sdcm.nemesis         p:ERROR >     self._random_disrupt()
[2021-04-01T14:03:13.226Z] < t:2021-04-01 14:03:08,888 f:nemesis.py      l:2907 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3278, in _random_disrupt
[2021-04-01T14:03:13.226Z] < t:2021-04-01 14:03:08,888 f:nemesis.py      l:2907 c:sdcm.nemesis         p:ERROR >     self.execute_disrupt_method(bound_method)
[2021-04-01T14:03:13.226Z] < t:2021-04-01 14:03:08,888 f:nemesis.py      l:2907 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1082, in execute_disrupt_method
[2021-04-01T14:03:13.226Z] < t:2021-04-01 14:03:08,888 f:nemesis.py      l:2907 c:sdcm.nemesis         p:ERROR >     disrupt_method()
[2021-04-01T14:03:13.226Z] < t:2021-04-01 14:03:08,888 f:nemesis.py      l:2907 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 708, in disrupt_nodetool_decommission
[2021-04-01T14:03:13.226Z] < t:2021-04-01 14:03:08,888 f:nemesis.py      l:2907 c:sdcm.nemesis         p:ERROR >     self.cluster.decommission(self.target_node)
[2021-04-01T14:03:13.226Z] < t:2021-04-01 14:03:08,888 f:nemesis.py      l:2907 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 4160, in decommission
[2021-04-01T14:03:13.226Z] < t:2021-04-01 14:03:08,888 f:nemesis.py      l:2907 c:sdcm.nemesis         p:ERROR >     self.terminate_node(node)  # pylint: disable=no-member
[2021-04-01T14:03:13.226Z] < t:2021-04-01 14:03:08,888 f:nemesis.py      l:2907 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3044, in terminate_node
[2021-04-01T14:03:13.226Z] < t:2021-04-01 14:03:08,888 f:nemesis.py      l:2907 c:sdcm.nemesis         p:ERROR >     node.destroy()
[2021-04-01T14:03:13.226Z] < t:2021-04-01 14:03:08,888 f:nemesis.py      l:2907 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster_aws.py", line 759, in destroy
[2021-04-01T14:03:13.226Z] < t:2021-04-01 14:03:08,888 f:nemesis.py      l:2907 c:sdcm.nemesis         p:ERROR >     self.release_address()
[2021-04-01T14:03:13.226Z] < t:2021-04-01 14:03:08,888 f:nemesis.py      l:2907 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster_aws.py", line 752, in release_address
[2021-04-01T14:03:13.226Z] < t:2021-04-01 14:03:08,888 f:nemesis.py      l:2907 c:sdcm.nemesis         p:ERROR >     client.release_address(AllocationId=self.eip_allocation_id)
[2021-04-01T14:03:13.226Z] < t:2021-04-01 14:03:08,888 f:nemesis.py      l:2907 c:sdcm.nemesis         p:ERROR >   File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 357, in _api_call
[2021-04-01T14:03:13.226Z] < t:2021-04-01 14:03:08,888 f:nemesis.py      l:2907 c:sdcm.nemesis         p:ERROR >     return self._make_api_call(operation_name, kwargs)
[2021-04-01T14:03:13.226Z] < t:2021-04-01 14:03:08,888 f:nemesis.py      l:2907 c:sdcm.nemesis         p:ERROR >   File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 676, in _make_api_call
[2021-04-01T14:03:13.226Z] < t:2021-04-01 14:03:08,888 f:nemesis.py      l:2907 c:sdcm.nemesis         p:ERROR >     raise error_class(parsed_response, operation_name)
[2021-04-01T14:03:13.226Z] < t:2021-04-01 14:03:08,888 f:nemesis.py      l:2907 c:sdcm.nemesis         p:ERROR > botocore.exceptions.ClientError: An error occurred (InvalidAllocationID.NotFound) when calling the ReleaseAddress operation: The allocation ID 'eipalloc-0e436efa0716cc0ad' does not exist
```

the decommission disruption nemesis crashed and did not bootstrap a node to replace the decommissioned node, leaving the test with 2 nodes instead of 3.
```
[2021-04-01T14:03:18.775Z] < t:2021-04-01 14:03:18,637 f:nemesis.py      l:2931 c:sdcm.nemesis         p:ERROR > sdcm.nemesis.CategoricalMonkey: num nodes before 3 and nodes after 2 does not match
```
