### ISSUE TITLE
artifacts-centos8-nonroot-test fails with - tee: /etc/scylla/scylla.yaml: No such file or directory

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#3395]
Test details
Test: artifacts_test.ArtifactsTest.test_scylla_service
Build number: 123
Backend: gce: us-east1
Kernel version: 4.18.0-240.15.1.el8_3.x86_64
Test-id: a8244784-e4ee-4185-be03-6f89de0bb58c
Start time: 2021-04-12 12:51:53
End time: 2021-04-12 12:53:53
Started by user: yarongilor
Private repo: https://s3.amazonaws.com/downloads.scylladb.com/rpm/centos/scylla-3.3.repo
Test result
FAILED
System under test
ScyllaDB version:
ScyllaDB repo: https://s3.amazonaws.com/downloads.scylladb.com/rpm/centos/scylla-3.3.repo
Actual gce image used: centos-8-v20210316
AWS region: us-east1
Instance type: n1-standard-2
Scylla packages installed:
No scylla packages are installed. Please check log files.

error log:
```
2021-04-12 12:53:35.008: (TestFrameworkEvent Severity.ERROR), source=ArtifactsTest.SetUp()
exception=[Node artifacts-centos8-jenkins-db-node-a8244784-0-1 [35.229.68.71 | 10.142.0.28] (seed: True)] NodeSetupFailed: Encountered a bad command exit code!
Command: 'bash -cxe "\nsudo yum install -y cyrus-sasl\nsudo systemctl enable saslauthd\necho \'MECH=ldap\' | sudo tee -a /etc/sysconfig/saslauthd\nsudo touch /etc/saslauthd.conf\necho \'saslauthd_socket_path: /run/saslauthd/mux\' | sudo tee -a /etc/scylla/scylla.yaml\n"'
Exit code: 1
Stdout:
Installing       : cyrus-sasl-2.1.27-5.el8.x86_64                         1/1
Running scriptlet: cyrus-sasl-2.1.27-5.el8.x86_64                         1/1
Verifying        : cyrus-sasl-2.1.27-5.el8.x86_64                         1/1
Installed:
cyrus-sasl-2.1.27-5.el8.x86_64
Complete!
MECH=ldap
saslauthd_socket_path: /run/saslauthd/mux
Stderr:
+ sudo yum install -y cyrus-sasl
+ sudo systemctl enable saslauthd
Created symlink /etc/systemd/system/multi-user.target.wants/saslauthd.service → /usr/lib/systemd/system/saslauthd.service.
+ sudo tee -a /etc/sysconfig/saslauthd
+ echo MECH=ldap
+ sudo touch /etc/saslauthd.conf
+ echo 'saslauthd_socket_path: /run/saslauthd/mux'
+ sudo tee -a /etc/scylla/scylla.yaml
tee: /etc/scylla/scylla.yaml: No such file or directory
Traceback (most recent call last):
File "/jenkins/slave/workspace/scylla-master/artifacts-offline-install/artifacts-centos8-nonroot-test@2/scylla-cluster-tests/sdcm/cluster.py", line 3457, in node_setup
cl_inst.node_setup(_node, **setup_kwargs)
File "/jenkins/slave/workspace/scylla-master/artifacts-offline-install/artifacts-centos8-nonroot-test@2/scylla-cluster-tests/sdcm/cluster.py", line 4082, in node_setup
node.remoter.run('bash -cxe "%s"' % setup_script)
File "/jenkins/slave/workspace/scylla-master/artifacts-offline-install/artifacts-centos8-nonroot-test@2/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in run
result = _run()
File "/jenkins/slave/workspace/scylla-master/artifacts-offline-install/artifacts-centos8-nonroot-test@2/scylla-cluster-tests/sdcm/utils/decorators.py", line 61, in inner
return func(*args, **kwargs)
File "/jenkins/slave/workspace/scylla-master/artifacts-offline-install/artifacts-centos8-nonroot-test@2/scylla-cluster-tests/sdcm/remote/remote_base.py", line 596, in _run
return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
File "/jenkins/slave/workspace/scylla-master/artifacts-offline-install/artifacts-centos8-nonroot-test@2/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
result = connection.run(**command_kwargs)
File "<decorator-gen-3>", line 2, in run
File "/usr/local/lib/python3.9/site-packages/fabric/connection.py", line 30, in opens
return method(self, *args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/fabric/connection.py", line 721, in run
return self._run(self._remote_runner(), command, **kwargs)
File "/usr/local/lib/python3.9/site-packages/invoke/context.py", line 101, in _run
return runner.run(command, **kwargs)
File "/usr/local/lib/python3.9/site-packages/invoke/runners.py", line 291, in run
return self._run_body(command, **kwargs)
File "/usr/local/lib/python3.9/site-packages/invoke/runners.py", line 442, in _run_body
raise UnexpectedExit(result)
invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!
Command: 'bash -cxe "\nsudo yum install -y cyrus-sasl\nsudo systemctl enable saslauthd\necho \'MECH=ldap\' | sudo tee -a /etc/sysconfig/saslauthd\nsudo touch /etc/saslauthd.conf\necho \'saslauthd_socket_path: /run/saslauthd/mux\' | sudo tee -a /etc/scylla/scylla.yaml\n"'
Exit code: 1
Stdout:
Installing       : cyrus-sasl-2.1.27-5.el8.x86_64                         1/1
Running scriptlet: cyrus-sasl-2.1.27-5.el8.x86_64                         1/1
Verifying        : cyrus-sasl-2.1.27-5.el8.x86_64                         1/1
Installed:
cyrus-sasl-2.1.27-5.el8.x86_64
Complete!
MECH=ldap
saslauthd_socket_path: /run/saslauthd/mux
Stderr:
+ sudo yum install -y cyrus-sasl
+ sudo systemctl enable saslauthd
Created symlink /etc/systemd/system/multi-user.target.wants/saslauthd.service → /usr/lib/systemd/system/saslauthd.service.
+ sudo tee -a /etc/sysconfig/saslauthd
+ echo MECH=ldap
+ sudo touch /etc/saslauthd.conf
+ echo 'saslauthd_socket_path: /run/saslauthd/mux'
+ sudo tee -a /etc/scylla/scylla.yaml
tee: /etc/scylla/scylla.yaml: No such file or directory
```

Hydra commands:
Restore Monitor Stack command: $ hydra investigate show-monitor a8244784-e4ee-4185-be03-6f89de0bb58c
Show all stored logs command: $ hydra investigate show-logs a8244784-e4ee-4185-be03-6f89de0bb58c
Logs:
db-cluster - https://cloudius-jenkins-test.s3.amazonaws.com/a8244784-e4ee-4185-be03-6f89de0bb58c/20210412_125418/db-cluster-a8244784.zip
sct-runner - https://cloudius-jenkins-test.s3.amazonaws.com/a8244784-e4ee-4185-be03-6f89de0bb58c/20210412_125418/sct-runner-a8244784.zip

**Comment by amoskong** [comment]
Fixed by #3399
