### ISSUE TITLE
config_client_encrypt fails with - mkdir: cannot create directory ‘/home/scyllaadm/.cassandra/’: Permission denied

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#3397]
Setup for both 50GB and 200GB master longevities failed with below error.
error log:
```
2021-04-09 03:12:16.834: (TestFrameworkEvent Severity.ERROR), source=LongevityTest.SetUp()
exception=[Node longevity-200gb-48h-verify-limited--db-node-a1630d2d-1 [13.53.115.146 | 10.0.0.138] (seed: True)] NodeSetupFailed: Encountered a bad command exit code!
Command: 'bash -cxe "\nmkdir -p ~/.cassandra/\ncp /tmp/ssl_conf/client/cqlshrc ~/.cassandra/\nsudo mkdir -p /etc/scylla/\nsudo rm -rf /etc/scylla/ssl_conf/\nsudo mv -f /tmp/ssl_conf/ /etc/scylla/\n"'
Exit code: 1
Stdout:
Stderr:
+ '[' -z '' ']'
+ return
+ case $- in
+ return
+ mkdir -p /home/scyllaadm/.cassandra/
mkdir: cannot create directory ‘/home/scyllaadm/.cassandra/’: Permission denied
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3426, in node_setup
cl_inst.node_setup(_node, **setup_kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 4079, in node_setup
self.node_config_setup(node, ','.join(self.seed_nodes_ips), self.get_endpoint_snitch())
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster_aws.py", line 923, in node_config_setup
node.config_setup(**setup_params)
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 1809, in config_setup
self.config_client_encrypt()
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 1899, in config_client_encrypt
self.remoter.run('bash -cxe "%s"' % setup_script)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in run
result = _run()
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 61, in inner
return func(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 596, in _run
return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
result = connection.run(**command_kwargs)
File "<decorator-gen-3>", line 2, in run
File "/usr/local/lib/python3.9/site-packages/fabric/connection.py", line 30, in opens
return method(self, *args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/fabric/connection.py", line 721, in run
return self._run(self._remote_runner(), command, **kwargs)
File "/usr/local/lib/python3.9/site-packages/invoke/context.py", line 101, in _run
return runner.run(command, **kwargs)
File "/usr/local/lib/python3.9/site-packages/invoke/runners.py", line 291, in run
return self._run_body(command, **kwargs)
File "/usr/local/lib/python3.9/site-packages/invoke/runners.py", line 442, in _run_body
raise UnexpectedExit(result)
invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!
Command: 'bash -cxe "\nmkdir -p ~/.cassandra/\ncp /tmp/ssl_conf/client/cqlshrc ~/.cassandra/\nsudo mkdir -p /etc/scylla/\nsudo rm -rf /etc/scylla/ssl_conf/\nsudo mv -f /tmp/ssl_conf/ /etc/scylla/\n"'
Exit code: 1
Stdout:
Stderr:
+ '[' -z '' ']'
+ return
+ case $- in
+ return
+ mkdir -p /home/scyllaadm/.cassandra/
mkdir: cannot create directory ‘/home/scyllaadm/.cassandra/’: Permission denied
```

**Comment by ShlomiBalalis** [comment]
Reoccurred In master's rolling-upgrade-ami-test: 

```
2021-06-04 03:10:09.703: (TestFrameworkEvent Severity.ERROR), source=UpgradeTest.SetUp()
exception=[Node rolling-upgrade-master-centos-db-node-0ea1571c-1 [34.240.7.194 | 10.0.3.186] (seed: True)] NodeSetupFailed: Encountered a bad command exit code!
Command: 'bash -cxe "\nmkdir -p ~/.cassandra/\ncp /tmp/ssl_conf/client/cqlshrc ~/.cassandra/\nsudo mkdir -p /etc/scylla/\nsudo rm -rf /etc/scylla/ssl_conf/\nsudo mv -f /tmp/ssl_conf/ /etc/scylla/\n"'
Exit code: 1
Stdout:
Stderr:
+ '[' -z '' ']'
+ return
+ case $- in
+ return
+ mkdir -p /home/scyllaadm/.cassandra/
mkdir: cannot create directory ‘/home/scyllaadm/.cassandra/’: Permission denied
Traceback (most recent call last):
File "/home/jenkins/slave/workspace/scylla-master/rolling-upgrade/rolling-upgrade-ami-test@2/scylla-cluster-tests/sdcm/cluster.py", line 3600, in node_setup
cl_inst.node_setup(_node, **setup_kwargs)
File "/home/jenkins/slave/workspace/scylla-master/rolling-upgrade/rolling-upgrade-ami-test@2/scylla-cluster-tests/sdcm/cluster.py", line 4261, in node_setup
self.node_config_setup(node, ','.join(self.seed_nodes_ips), self.get_endpoint_snitch())
File "/home/jenkins/slave/workspace/scylla-master/rolling-upgrade/rolling-upgrade-ami-test@2/scylla-cluster-tests/sdcm/cluster_aws.py", line 936, in node_config_setup
node.config_setup(**setup_params)
File "/home/jenkins/slave/workspace/scylla-master/rolling-upgrade/rolling-upgrade-ami-test@2/scylla-cluster-tests/sdcm/cluster.py", line 1911, in config_setup
self.config_client_encrypt()
File "/home/jenkins/slave/workspace/scylla-master/rolling-upgrade/rolling-upgrade-ami-test@2/scylla-cluster-tests/sdcm/cluster.py", line 2003, in config_client_encrypt
self.remoter.run('bash -cxe "%s"' % setup_script)
File "/home/jenkins/slave/workspace/scylla-master/rolling-upgrade/rolling-upgrade-ami-test@2/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in run
result = _run()
File "/home/jenkins/slave/workspace/scylla-master/rolling-upgrade/rolling-upgrade-ami-test@2/scylla-cluster-tests/sdcm/utils/decorators.py", line 61, in inner
return func(*args, **kwargs)
File "/home/jenkins/slave/workspace/scylla-master/rolling-upgrade/rolling-upgrade-ami-test@2/scylla-cluster-tests/sdcm/remote/remote_base.py", line 596, in _run
return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
File "/home/jenkins/slave/workspace/scylla-master/rolling-upgrade/rolling-upgrade-ami-test@2/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
result = connection.run(**command_kwargs)
File "<decorator-gen-3>", line 2, in run
File "/usr/local/lib/python3.9/site-packages/fabric/connection.py", line 30, in opens
return method(self, *args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/fabric/connection.py", line 721, in run
return self._run(self._remote_runner(), command, **kwargs)
File "/usr/local/lib/python3.9/site-packages/invoke/context.py", line 101, in _run
return runner.run(command, **kwargs)
File "/usr/local/lib/python3.9/site-packages/invoke/runners.py", line 291, in run
return self._run_body(command, **kwargs)
File "/usr/local/lib/python3.9/site-packages/invoke/runners.py", line 442, in _run_body
raise UnexpectedExit(result)
invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!
Command: 'bash -cxe "\nmkdir -p ~/.cassandra/\ncp /tmp/ssl_conf/client/cqlshrc ~/.cassandra/\nsudo mkdir -p /etc/scylla/\nsudo rm -rf /etc/scylla/ssl_conf/\nsudo mv -f /tmp/ssl_conf/ /etc/scylla/\n"'
Exit code: 1
Stdout:
Stderr:
+ '[' -z '' ']'
+ return
+ case $- in
+ return
+ mkdir -p /home/scyllaadm/.cassandra/
mkdir: cannot create directory ‘/home/scyllaadm/.cassandra/’: Permission denied
```

Testid: 0ea1571c-a3cf-4d10-a70c-7af7458959db

@yarongilor How was this solved?
