### ISSUE TITLE
longevity-large-partition-asymmetric-cluster fails: apt-get install -y scylla-manager-agent: Could not get lock /var/lib/dpkg/lock-frontend

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#3398]
scylla-master/longevity/longevity-large-partition-asymmetric-cluster-3h failed installing the scylla manager agent.

error log:
```
2021-04-12 06:54:32.890: (TestFrameworkEvent Severity.ERROR), source=LargePartitionLongevityTest.SetUp()
exception=[Node longevity-large-partitions-3h-maste-db-node-4ea94ed9-4 [13.53.207.1 | 10.0.3.16] (seed: False)] NodeSetupFailed: Encountered a bad command exit code!
Command: 'sudo bash -cxe "\napt-get install -y scylla-manager-agent\nsed -i \'s/# auth_token:.*$/auth_token: 4ea94ed9-708e-4317-8789-01306a70a611/\' /etc/scylla-manager-agent/scylla-manager-agent.yaml\nscyllamgr_ssl_cert_gen\nsed -i \'s/#tls_cert_file/tls_cert_file/\' /etc/scylla-manager-agent/scylla-manager-agent.yaml\nsed -i \'s/#tls_key_file/tls_key_file/\' /etc/scylla-manager-agent/scylla-manager-agent.yaml\nsed -i \'s/#prometheus: .*/prometheus: :5090/\' /etc/scylla-manager-agent/scylla-manager-agent.yaml\nsystemctl restart scylla-manager-agent\nsystemctl enable scylla-manager-agent\n"'
Exit code: 100
Stdout:
Stderr:
+ apt-get install -y scylla-manager-agent
E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 14408 (unattended-upgr)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3426, in node_setup
cl_inst.node_setup(_node, **setup_kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 4099, in node_setup
self.install_scylla_manager(node)
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 4116, in install_scylla_manager
node.install_manager_agent(package_path=pkg_path)
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 1950, in install_manager_agent
self.remoter.run('sudo bash -cxe "%s"' % install_and_config_agent_command)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in run
result = _run()
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 61, in inner
return func(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 596, in _run
return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
result = connection.run(**command_kwargs)
File "<decorator-gen-3>", line 2, in run
File "/usr/local/lib/python3.9/site-packages/fabric/connection.py", line 30, in opens
return method(self, *args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/fabric/connection.py", line 721, in run
return self._run(self._remote_runner(), command, **kwargs)
File "/usr/local/lib/python3.9/site-packages/invoke/context.py", line 101, in _run
return runner.run(command, **kwargs)
File "/usr/local/lib/python3.9/site-packages/invoke/runners.py", line 291, in run
return self._run_body(command, **kwargs)
File "/usr/local/lib/python3.9/site-packages/invoke/runners.py", line 442, in _run_body
raise UnexpectedExit(result)
invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!
Command: 'sudo bash -cxe "\napt-get install -y scylla-manager-agent\nsed -i \'s/# auth_token:.*$/auth_token: 4ea94ed9-708e-4317-8789-01306a70a611/\' /etc/scylla-manager-agent/scylla-manager-agent.yaml\nscyllamgr_ssl_cert_gen\nsed -i \'s/#tls_cert_file/tls_cert_file/\' /etc/scylla-manager-agent/scylla-manager-agent.yaml\nsed -i \'s/#tls_key_file/tls_key_file/\' /etc/scylla-manager-agent/scylla-manager-agent.yaml\nsed -i \'s/#prometheus: .*/prometheus: :5090/\' /etc/scylla-manager-agent/scylla-manager-agent.yaml\nsystemctl restart scylla-manager-agent\nsystemctl enable scylla-manager-agent\n"'
Exit code: 100
Stdout:
Stderr:
+ apt-get install -y scylla-manager-agent
E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 14408 (unattended-upgr)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
```
Test details
Test: longevity_large_partition_test.LargePartitionLongevityTest.test_large_partition_longevity
Build number: 3
Backend: aws: eu-north-1
Kernel version: 5.4.0-1035-aws
Test-id: 4ea94ed9-708e-4317-8789-01306a70a611
Start time: 2021-04-12 06:44:42
End time: 2021-04-12 06:55:02
Started by user: yarongilor
Test result
FAILED
System under test
Scylla version: 4.6.dev-0.20210409.305372820 (ami-0de4afff7dcfcf4bd)
Instance type: i3.2xlarge
Number of scylladb nodes: 5

**Comment by amoskong** [comment]
In 2021.1 job, I can still see this problem, it finally failed after 10 times retry.

/Cc @bentsi @roydahan @fgelcer 

job: https://jenkins.scylladb.com/job/enterprise-2021.1/job/SCT_Enterprise_Features/job/EncryptionAtRest/job/EaR-longevity-local-200gb-6h-test/5/console
test_id: 802bfc65-20ef-48a7-b60e-d94704a72728


```
11:19:10  < t:2021-05-10 03:19:09,350 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > 2021-05-10T03:19:00+00:00  longevity-encrypt-at-rest-200gb-6h--db-node-802bfc65-2 !INFO    | systemd[1]: Starting Scylla Server...
11:19:16  < t:2021-05-10 03:19:16,218 f:base.py         l:144  c:RemoteCmdRunner      p:ERROR > Error executing command: "sudo apt-get install -y scylla-manager-agent"; Exit status: 100
11:19:22  < t:2021-05-10 03:19:21,284 f:base.py         l:144  c:RemoteCmdRunner      p:ERROR > Error executing command: "sudo apt-get install -y scylla-manager-agent"; Exit status: 100
11:19:26  < t:2021-05-10 03:19:26,352 f:base.py         l:144  c:RemoteCmdRunner      p:ERROR > Error executing command: "sudo apt-get install -y scylla-manager-agent"; Exit status: 100
11:19:32  < t:2021-05-10 03:19:31,420 f:base.py         l:144  c:RemoteCmdRunner      p:ERROR > Error executing command: "sudo apt-get install -y scylla-manager-agent"; Exit status: 100
11:19:36  < t:2021-05-10 03:19:36,493 f:base.py         l:144  c:RemoteCmdRunner      p:ERROR > Error executing command: "sudo apt-get install -y scylla-manager-agent"; Exit status: 100
11:19:42  < t:2021-05-10 03:19:41,561 f:base.py         l:144  c:RemoteCmdRunner      p:ERROR > Error executing command: "sudo apt-get install -y scylla-manager-agent"; Exit status: 100
11:19:47  < t:2021-05-10 03:19:46,649 f:base.py         l:144  c:RemoteCmdRunner      p:ERROR > Error executing command: "sudo apt-get install -y scylla-manager-agent"; Exit status: 100
11:19:51  < t:2021-05-10 03:19:51,718 f:base.py         l:144  c:RemoteCmdRunner      p:ERROR > Error executing command: "sudo apt-get install -y scylla-manager-agent"; Exit status: 100
11:19:57  < t:2021-05-10 03:19:56,783 f:base.py         l:144  c:RemoteCmdRunner      p:ERROR > Error executing command: "sudo apt-get install -y scylla-manager-agent"; Exit status: 100
11:20:02  < t:2021-05-10 03:20:01,851 f:base.py         l:144  c:RemoteCmdRunner      p:ERROR > Error executing command: "sudo apt-get install -y scylla-manager-agent"; Exit status: 100
11:20:07  < t:2021-05-10 03:20:06,857 f:decorators.py   l:66   c:sdcm.utils.decorators p:ERROR > 'install_package': Number of retries exceeded!
11:20:07  < t:2021-05-10 03:20:06,861 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > 2021-05-10 03:20:06.859: (TestFrameworkEvent Severity.ERROR), source=LongevityTest.SetUp()
```

**Comment by fgelcer** [comment]
@amoskong  if it was not a transient failure (while we research a better way to wait), you can in the meantime increase the retries, and the sleep time between retries..
