### ISSUE TITLE
exception while nodetool refresh when trying to run cqlsh

### ISSUE THREAD

**Issue by harelassayag** [scylladb/scylla-cluster-tests#348]
need to handle the exception:

> sdcm.nemesis.ChaosMonkey: Unhandled exception in method <function disrupt at 0x58e56e0>

in the nodetool refresh when trying to run cqlsh

```
2017-08-09 16:48:43,540 remote           L0197 DEBUG| [10.240.0.95] [stdout] Aug 09 16:48:43 info   |  [shard 12] storage_service - Done loading new SSTables for keyspace1.standard1 for all shards
2017-08-09 16:48:43,543 remote           L0197 DEBUG| [10.240.0.95] [stderr] Connection to 10.240.0.95 closed.
2017-08-09 16:48:43,544 nemesis          L0107 DEBUG| sdcm.nemesis.ChaosMonkey: Command '/bin/ssh -tt -a -x   -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpI1YdUa -o BatchMode=yes -o ConnectTimeo
ut=300 -o ServerAliveInterval=300 -l scylla-test -p 22 -i /jenkins/.ssh/scylla-test 10.240.0.95 "nodetool --host localhost refresh -- keyspace1 standard1"' duration -> 0.978437185287 s
2017-08-09 16:48:43,820 remote           L0894 DEBUG| Remote [scylla-test@10.240.0.95]: Running 'cqlsh -e "select * from keyspace1.standard1 where key=0x314e344b4d504d4b4b30" 10.240.0.95'
2017-08-09 16:48:43,821 remote           L0097 INFO | [10.240.0.95] Running '/bin/ssh -tt -a -x   -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpI1YdUa -o BatchMode=yes -o ConnectTimeout=300 -o Se
rverAliveInterval=300 -l scylla-test -p 22 -i /jenkins/.ssh/scylla-test 10.240.0.95 "cqlsh -e \"select * from keyspace1.standard1 where key=0x314e344b4d504d4b4b30\" 10.240.0.95"'
2017-08-09 16:48:44,255 remote           L0197 DEBUG| [10.240.0.95] [stdout] Connection error: ('Unable to connect to any servers', {'10.240.0.95': error(111, "Tried connecting to [('10.240.0.95', 9042)]. Last e
rror: Connection refused")})
2017-08-09 16:48:44,265 remote           L0197 DEBUG| [10.240.0.95] [stderr] Connection to 10.240.0.95 closed.
2017-08-09 16:48:44,266 nemesis          L0399 ERROR| sdcm.nemesis.ChaosMonkey: Unhandled exception in method <function disrupt at 0x58e56e0>
Traceback (most recent call last):
  File "/jenkins/slave/workspace/scylla-2.0-longevity-gce/label/gce/sdcm/nemesis.py", line 396, in wrapper
  File "/jenkins/slave/workspace/scylla-2.0-longevity-gce/label/gce/sdcm/nemesis.py", line 519, in disrupt
  File "/jenkins/slave/workspace/scylla-2.0-longevity-gce/label/gce/sdcm/nemesis.py", line 352, in call_random_disrupt_method
  File "/jenkins/slave/workspace/scylla-2.0-longevity-gce/label/gce/sdcm/nemesis.py", line 279, in disrupt_nodetool_refresh
  File "/jenkins/slave/workspace/scylla-2.0-longevity-gce/label/gce/sdcm/remote.py", line 905, in run
  File "/jenkins/slave/workspace/scylla-2.0-longevity-gce/label/gce/sdcm/remote.py", line 849, in _run
  File "/jenkins/slave/workspace/scylla-2.0-longevity-gce/label/gce/sdcm/remote.py", line 228, in ssh_run
CmdError: Command '/bin/ssh -tt -a -x   -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpI1YdUa -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l scylla-test -p 22 -i /jenkins/.ss
h/scylla-test 10.240.0.95 "cqlsh -e \"select * from keyspace1.standard1 where key=0x314e344b4d504d4b4b30\" 10.240.0.95"' failed (rc=1)
2017-08-09 16:48:44,267 nemesis          L0407 DEBUG| sdcm.nemesis.ChaosMonkey: Refresh keyspace1.standard1 on longevity-scylla-2-0-scylla-db-node-7b8f147e-0-2 duration -> 3 s
```

**Comment by roydahan** [comment]
@amoskong please take a look and try to fix.
In any case, we shouldn't exit like that, we should try catching everything.

**Comment by amoskong** [comment]
We have 4 place to execute cqlsh command by remoter.run().

```
$ git grep cqlsh
refresh_test.py:            node.remoter.run('cqlsh -e "{}" {}'.format(cmd, node.private_ip_address), verbose=True)
sdcm/nemesis.py:            node.remoter.run('cqlsh -e "{}" {}'.format(cmd, node.private_ip_address), verbose=True)
sdcm/nemesis.py:        self.target_node.remoter.run('cqlsh -e "{}" {}'.format(cmd, self.target_node.private_ip_address), verbose=True)
sdcm/nemesis.py:        self.target_node.remoter.run('cqlsh -e "{}" {}'.format(cmd, self.target_node.private_ip_address), verbose=True)
```
