### ISSUE TITLE
oel81 node cannot be pinged (through curl) using public IP address, only private

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla-cluster-tests#3502]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master
* **scylla**: master
Using artifacts-oel81-test

### Logs
* test_id: eecc26d4-c3ec-4031-b6ad-6bddd6a3dc74
* job log: https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-oel81-test/33/

### Description

For some reason, when using oel-81, the run fails on manager installation, specifically when sct tries to ping the agent to see if it's alive: https://github.com/scylladb/scylla-cluster-tests/blob/master/sdcm/cluster.py#L1356, it receives a timeout, even though the agent is up and running. Upon further inspection, it does not seem to be an agent issue, but rather some sort of firewall issue.
First, it became clear that the timeout only occurs when trying to ping the agent from the public IP:
```
[ec2-user@artifacts-oel81-jenkins-db-node-eecc26d4-1 ~]$ curl https://34.244.80.147:10001/ping -sv
*   Trying 34.244.80.147...
* TCP_NODELAY set
```
While pinging from the private IP is a non-issue:
```
[ec2-user@artifacts-oel81-jenkins-db-node-eecc26d4-1 ~]$ curl https://10.0.1.15:10001/ping -sv
*   Trying 10.0.1.15...
* TCP_NODELAY set
* Connected to 10.0.1.15 (10.0.1.15) port 10001 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: self signed certificate
* Closing connection 0
```
The same applies when I tried to curl through scylla port:
```
[ec2-user@artifacts-oel81-jenkins-db-node-eecc26d4-1 ~]$ curl https://34.244.80.147:9042 -sv
* Rebuilt URL to: https://34.244.80.147:9042/
*   Trying 34.244.80.147...
* TCP_NODELAY set
{TIMESOUT}
```
```
[ec2-user@artifacts-oel81-jenkins-db-node-eecc26d4-1 ~]$ curl https://10.0.1.15:9042 -sv
* Rebuilt URL to: https://10.0.1.15:9042/
*   Trying 10.0.1.15...
* TCP_NODELAY set
* Connected to 10.0.1.15 (10.0.1.15) port 9042 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* error:1408F10B:SSL routines:ssl3_get_record:wrong version number
* Closing connection 0
```

I tried and compared to a different, random node (specifically from 200gb 2021) and did not run into the issue:
```
scyllaadm@longevity-200gb-48h-verify-limited--db-node-1d474a76-1:~$ curl https://3.250.3.150:10001/ping -sv
*   Trying 3.250.3.150:10001...
* TCP_NODELAY set
* Connected to 3.250.3.150 (3.250.3.150) port 10001 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: self signed certificate
* Closing connection 0
```
```
scyllaadm@longevity-200gb-48h-verify-limited--db-node-1d474a76-1:~$ curl https://3.250.3.150:9042 -sv
*   Trying 3.250.3.150:9042...
* TCP_NODELAY set
* Connected to 3.250.3.150 (3.250.3.150) port 9042 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: self signed certificate
* Closing connection 0
```

As such, it seems there is some sort of port blockage issue with oel81 servers.

### Steps to Reproduce

1. start oel81 artifact run
2. wai for the manager agent to be installed
3. try to ping it, both through public and private IPs

**Expected behavior:** The agent (or any other port, for that matter) can be pinged from public IP

**Actual behavior:** when pinging from public IPs, we receive a timeout

~~Kept the node live, for now, at 34.244.80.147 (ec2-user, at Ireland)~~

Edit:
My attempt to ping through python requests from my private machine, same as sct attempts to do:
```
>>> r = requests.get(f"https://34.244.80.147:10001/ping", verify=False)
Traceback (most recent call last):
  File "/home/shlomib/.local/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/shlomib/.local/lib/python3.6/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/home/shlomib/.local/lib/python3.6/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shlomib/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/shlomib/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/home/shlomib/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/home/shlomib/.local/lib/python3.6/site-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/home/shlomib/.local/lib/python3.6/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7fc513aefba8>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/shlomib/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/shlomib/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='34.244.80.147', port=10001): Max retries exceeded with url: /ping (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fc513aefba8>: Failed to establish a new connection: [Errno 110] Connection timed out',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='34.244.80.147', port=10001): Max retries exceeded with url: /ping (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fc513aefba8>: Failed to establish a new connection: [Errno 110] Connection timed out',))
```

**Comment by amoskong** [comment]
The problem doesn't exist with recent Oel76 and other distros, it might be caused by the firewall/selinux/etc in Oel8.
It should be a general network config issue, not just for scylla-manager.

**Comment by amoskong** [comment]
### Selinux is enabled

```
[ec2-user@artifacts-oel81-jenkins-db-node-041264c3-1 ~]$ sestatus 
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   permissive
Mode from config file:          error (Success)
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Memory protection checking:     actual (secure)
Max kernel policy version:      31

[ec2-user@artifacts-oel81-jenkins-db-node-041264c3-1 ~]$ getenforce 
Permissive

[ec2-user@artifacts-oel81-jenkins-db-node-041264c3-1 ~]$ selinuxenabled; echo $?
0

```

```
[ec2-user@artifacts-oel81-jenkins-db-node-041264c3-1 ~]$ sudo iptables -L
Chain INPUT (policy DROP)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere            
DROP       all  --  127.0.0.0/8          anywhere            
ACCEPT     tcp  --  anywhere             anywhere             state ESTABLISHED
ACCEPT     udp  --  anywhere             anywhere             state ESTABLISHED
ACCEPT     icmp --  anywhere             anywhere             state ESTABLISHED
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:ssh state NEW
ACCEPT     udp  --  anywhere             anywhere             udp dpt:bootpc state NEW
ACCEPT     udp  --  anywhere             anywhere             udp dpt:ntp state NEW
ACCEPT     udp  --  anywhere             anywhere             udp dpt:323 state NEW

Chain FORWARD (policy DROP)
target     prot opt source               destination         

Chain OUTPUT (policy DROP)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     tcp  --  anywhere             anywhere             state NEW,ESTABLISHED
ACCEPT     udp  --  anywhere             anywhere             state NEW,ESTABLISHED
ACCEPT     icmp --  anywhere             anywhere             state NEW,ESTABLISHED
```

```
[ec2-user@artifacts-oel81-jenkins-db-node-041264c3-1 ~]$ cat /etc/selinux/config 

# This file controls the state of SELinux on the system.
# SELINUX= can take one of these three values:
#     enforcing - SELinux security policy is enforced.
#     permissive - SELinux prints warnings instead of enforcing.
#     disabled - No SELinux policy is loaded.
SELINUX="disabled"
# SELINUXTYPE= can take one of these three values:
#     targeted - Targeted processes are protected,
#     minimum - Modification of targeted policy. Only selected processes are protected. 
#     mls - Multi Level Security protection.
SELINUXTYPE=targeted
```

### No special difference between OEL76 and OEL81 artifact tests.
```
[amos@fedora scylla-cluster-tests]$ diff test-cases/artifacts/oel76.yaml test-cases/artifacts/oel81.yaml 
1,2c1,2
< ami_db_scylla_user: 'clckwrk'
< ami_id_db_scylla: 'ami-0d6a24fe35fdf5dc4'
---
> ami_db_scylla_user: 'ec2-user'
> ami_id_db_scylla: 'ami-0e883e67243efea62'
19c19
< user_prefix: 'artifacts-oel76'
---
> user_prefix: 'artifacts-oel81'
[amos@fedora scylla-cluster-tests]$ diff jenkins-pipelines/artifacts-oel76.jenkinsfile jenkins-pipelines/artifacts-oel81.jenkinsfile 
7c7
<     test_config: 'test-cases/artifacts/oel76.yaml',
---
>     test_config: 'test-cases/artifacts/oel81.yaml',
```

**Comment by amoskong** [comment]
#### SElinux config of httpd

```
[ec2-user@artifacts-oel81-jenkins-db-node-041264c3-1 ~]$ getsebool  -a|grep http
httpd_anon_write --> off
httpd_builtin_scripting --> on
httpd_can_check_spam --> off
httpd_can_connect_ftp --> off
httpd_can_connect_ldap --> off
httpd_can_connect_mythtv --> off
httpd_can_connect_zabbix --> off
httpd_can_network_connect --> off
httpd_can_network_connect_cobbler --> off
httpd_can_network_connect_db --> off
httpd_can_network_memcache --> off
httpd_can_network_relay --> off
httpd_can_sendmail --> off
httpd_dbus_avahi --> off
httpd_dbus_sssd --> off
httpd_dontaudit_search_dirs --> off
httpd_enable_cgi --> on
httpd_enable_ftp_server --> off
httpd_enable_homedirs --> off
httpd_execmem --> off
httpd_graceful_shutdown --> off
httpd_manage_ipa --> off
httpd_mod_auth_ntlm_winbind --> off
httpd_mod_auth_pam --> off
httpd_read_user_content --> off
httpd_run_ipa --> off
httpd_run_preupgrade --> off
httpd_run_stickshift --> off
httpd_serve_cobbler_files --> off
httpd_setrlimit --> off
httpd_ssi_exec --> off
httpd_sys_script_anon_write --> off
httpd_tmp_exec --> off
httpd_tty_comm --> off
httpd_unified --> off
httpd_use_cifs --> off
httpd_use_fusefs --> off
httpd_use_gpg --> off
httpd_use_nfs --> off
httpd_use_openstack --> off
httpd_use_sasl --> off
httpd_verify_dns --> off
mysql_connect_http --> off
named_tcp_bind_http_port --> off
prosody_bind_http_port --> off
```

**Comment by amoskong** [comment]
Tried to ping from an external instance. The package can be monitored by tcpdump.
So the firewall of ec2 is fine.

```
[amos@amos-centos7 ~]$ curl  https://54.77.115.85:10001/ping -sv
* About to connect() to 54.77.115.85 port 10001 (#0)
*   Trying 54.77.115.85...

[ec2-user@artifacts-oel81-jenkins-db-node-041264c3-1 ~]$ sudo tcpdump -i ens3 port 10001
dropped privs to tcpdump
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on ens3, link-type EN10MB (Ethernet), capture size 262144 bytes
02:46:00.965816 IP 128.201.187.35.bc.googleusercontent.com.54500 > artifacts-oel81-jenkins-db-node-041264c3-1.scp-config: Flags [S], seq 3790535942, win 28400, options [mss 1420,sackOK,TS val 260081065 ecr 0,nop,wscale 7], length 0
02:46:01.968222 IP 128.201.187.35.bc.googleusercontent.com.54500 > artifacts-oel81-jenkins-db-node-041264c3-1.scp-config: Flags [S], seq 3790535942, win 28400, options [mss 1420,sackOK,TS val 260082068 ecr 0,nop,wscale 7], length 0
```

### Correct Selinux config

There is a typo in selinux config (/etc/selinux/config). But the problem still exists after really disabled selinux

```
$ diff -urp selinux.old selinux.new
--- selinux.old	2021-05-24 11:20:01.208726844 +0800
+++ selinux.new	2021-05-24 11:19:51.968654072 +0800
@@ -3,7 +3,7 @@
 #     enforcing - SELinux security policy is enforced.
 #     permissive - SELinux prints warnings instead of enforcing.
 #     disabled - No SELinux policy is loaded.
-SELINUX="disabled"
+SELINUX=disabled
 # SELINUXTYPE= can take one of these three values:
 #     targeted - Targeted processes are protected,
 #     minimum - Modification of targeted policy. Only selected processes are protected. 

[ec2-user@artifacts-oel81-jenkins-db-node-041264c3-1 ~]$ sestatus 
SELinux status:                 disabled

```

### Problem is solved after stop iptables service.

```
[ec2-user@artifacts-oel81-jenkins-db-node-041264c3-1 ~]$ sudo systemctl status iptables
● iptables.service - IPv4 firewall with iptables
   Loaded: loaded (/usr/lib/systemd/system/iptables.service; enabled; vendor preset: disabled)
   Active: active (exited) since Mon 2021-05-24 03:17:43 UTC; 9s ago
  Process: 1796 ExecStop=/usr/libexec/iptables/iptables.init stop (code=exited, status=0/SUCCESS)
  Process: 1833 ExecStart=/usr/libexec/iptables/iptables.init start (code=exited, status=0/SUCCESS)
 Main PID: 1833 (code=exited, status=0/SUCCESS)

May 24 03:17:43 artifacts-oel81-jenkins-db-node-041264c3-1 systemd[1]: Starting IPv4 firewall with iptabl>
May 24 03:17:43 artifacts-oel81-jenkins-db-node-041264c3-1 iptables.init[1833]: iptables: Applying firewa>
May 24 03:17:43 artifacts-oel81-jenkins-db-node-041264c3-1 systemd[1]: Started IPv4 firewall with iptable>
[ec2-user@artifacts-oel81-jenkins-db-node-041264c3-1 ~]$ curl  https://54.77.115.85:10001/ping -sv
*   Trying 54.77.115.85...
* TCP_NODELAY set
* connect to 54.77.115.85 port 10001 failed: Connection timed out
* Failed to connect to 54.77.115.85 port 10001: Connection timed out
* Closing connection 0
[ec2-user@artifacts-oel81-jenkins-db-node-041264c3-1 ~]$ sudo systemctl stop iptables
[ec2-user@artifacts-oel81-jenkins-db-node-041264c3-1 ~]$ curl  https://54.77.115.85:10001/ping -sv
*   Trying 54.77.115.85...
* TCP_NODELAY set
* Connected to 54.77.115.85 (54.77.115.85) port 10001 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: self signed certificate
* Closing connection 0
[ec2-user@artifacts-oel81-jenkins-db-node-041264c3-1 ~]$ 
```

**Comment by roydahan** [comment]
@amoskong did you  send a PR to fix it?

**Comment by amoskong** [comment]
> @amoskong did you send a PR to fix it?

Thanks for the reminder, I forgot to send it out.
Just sent it out and run a byo test.

**Comment by amoskong** [comment]
There are also some todo items in future (not urgent)

1. bash error:  /etc/bashrc

```
/etc/bashrc: line 99: TMOUT: readonly variable
/etc/bashrc: line 100: TMOUT: readonly variable
```

2. permission to read housekeeping.uuid (add sudo)

$ cat /var/lib/scylla-housekeeping/housekeeping.uuid
cat: /var/lib/scylla-housekeeping/housekeeping.uuid: Permission denied

3. fix selinux conf (not urgent)
