### ISSUE TITLE
[master] The manager installation failed because "scyllamgr_ssl_cert_gen: command not found"

### ISSUE THREAD

**Issue by Orenef11** [scylladb/scylla-cluster-tests#3509]
test-id: `5363a1fc-1046-477e-8b04-0cd1b8edc609`

```
09:40:39  + sed -i 's/# auth_token:.*$/auth_token: 5363a1fc-1046-477e-8b04-0cd1b8edc609/' /etc/scylla-manager-agent/scylla-manager-agent.yaml
09:40:39  + scyllamgr_ssl_cert_gen
09:40:39  bash: line 2: scyllamgr_ssl_cert_gen: command not found
09:40:39  
09:40:39  
09:40:39  Traceback (most recent call last):
09:40:39    File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3535, in node_setup
09:40:39      cl_inst.node_setup(_node, **setup_kwargs)
09:40:39    File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 4216, in node_setup
09:40:39      self.install_scylla_manager(node)
09:40:39    File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 4233, in install_scylla_manager
09:40:39      node.install_manager_agent(package_path=pkg_path)
09:40:39    File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2017, in install_manager_agent
09:40:39      self.remoter.run('sudo bash -cxe "%s"' % install_and_config_agent_command)
09:40:39    File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in run
09:40:39      result = _run()
09:40:39    File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 61, in inner
09:40:39      return func(*args, **kwargs)
09:40:39    File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 596, in _run
09:40:39      return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
09:40:39    File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
09:40:39      result = connection.run(**command_kwargs)
09:40:39    File "<decorator-gen-3>", line 2, in run
09:40:39    File "/usr/local/lib/python3.9/site-packages/fabric/connection.py", line 30, in opens
09:40:39      return method(self, *args, **kwargs)
09:40:39    File "/usr/local/lib/python3.9/site-packages/fabric/connection.py", line 721, in run
09:40:39      return self._run(self._remote_runner(), command, **kwargs)
09:40:39    File "/usr/local/lib/python3.9/site-packages/invoke/context.py", line 101, in _run
09:40:39      return runner.run(command, **kwargs)
09:40:39    File "/usr/local/lib/python3.9/site-packages/invoke/runners.py", line 291, in run
09:40:39      return self._run_body(command, **kwargs)
09:40:39    File "/usr/local/lib/python3.9/site-packages/invoke/runners.py", line 442, in _run_body
09:40:39      raise UnexpectedExit(result)
09:40:39  invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!
09:40:39  
09:40:39  Command: 'sudo bash -cxe "\nsed -i \'s/# auth_token:.*$/auth_token: 5363a1fc-1046-477e-8b04-0cd1b8edc609/\' /etc/scylla-manager-agent/scylla-manager-agent.yaml\nscyllamgr_ssl_cert_gen\nsed -i \'s/#tls_cert_file/tls_cert_file/\' /etc/scylla-manager-agent/scylla-manager-agent.yaml\nsed -i \'s/#tls_key_file/tls_key_file/\' /etc/scylla-manager-agent/scylla-manager-agent.yaml\nsed -i \'s/#prometheus: .*/prometheus: :5090/\' /etc/scylla-manager-agent/scylla-manager-agent.yaml\nsystemctl restart scylla-manager-agent\nsystemctl enable scylla-manager-agent\n"'
09:40:39  
09:40:39  Exit code: 127
09:40:39  
09:40:39  Stdout:
09:40:39  
09:40:39  
09:40:39  
09:40:39  Stderr:
09:40:39  
09:40:39  + sed -i 's/# auth_token:.*$/auth_token: 5363a1fc-1046-477e-8b04-0cd1b8edc609/' /etc/scylla-manager-agent/scylla-manager-agent.yaml
09:40:39  + scyllamgr_ssl_cert_gen
09:40:39  bash: line 2: scyllamgr_ssl_cert_gen: command not found
```

[JOB RUN](https://jenkins.scylladb.com/view/master/job/scylla-master/view/master-test/job/longevity/job/longevity-200gb-48h/116/execution/node/117/log/)

**Comment by fgelcer** [comment]
relates to https://github.com/scylladb/scylla-manager/commit/29a519747f208f0ca8dafd4962688affaecfd63a

**Comment by roydahan** [comment]
https://github.com/scylladb/scylla-manager/issues/2617

**Comment by mmatczuk** [comment]
You should not run the script, before the patch the script was invoked in post install action. Now it's not needed at all as the certificate is generated in memory on server start.

**Comment by fgelcer** [comment]
> You should not run the script, before the patch the script was invoked in post install action. Now it's not needed at all as the certificate is generated in memory on server start.

@mmatczuk , so i just need to drop the call to this script at all?

**Comment by mmatczuk** [comment]
Correct.

**Comment by fgelcer** [comment]
> Correct.

fix here --> https://github.com/scylladb/scylla-cluster-tests/pull/3536/commits/bcfaf2585d24752ad6499fb08a91b1cc5c744bab
@ShlomiBalalis , FYI
