### ISSUE TITLE
[2021.1.rc2] The command "cqlsh --no-color   --request-timeout=120 --connect-timeout=60 --ssl -e "TRUNCATE ks_truncate_large_partition.test_table"" is failed

### ISSUE THREAD

**Issue by Orenef11** [scylladb/scylla-cluster-tests#3510]
```
(DisruptionEvent Severity.ERROR): type=TruncateMonkeyLargePartition subtype=end node=Node lwt-longevity-multi-dc-24h-2021-1-db-node-b2b540b6-9 [3.239.32.32 | 10.0.2.175] (seed: False) duration=504 error=Encountered a bad command exit code!

Command: 'cqlsh --no-color   --request-timeout=120 --connect-timeout=60 --ssl -e "TRUNCATE ks_truncate_large_partition.test_table" 3.239.32.32 9042'

Exit code: 2

Stdout:



Stderr:

:1:InvalidRequest: Error from server: code=2200 [Invalid query] message="Keyspace ks_truncate_large_partition does not exist"


Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2955, in wrapper
    result = method(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3250, in disrupt
    self.call_random_disrupt_method()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1121, in call_random_disrupt_method
    self.execute_disrupt_method(disrupt_method)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1128, in execute_disrupt_method
    disrupt_method()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1228, in disrupt_truncate_large_partition
    self.target_node.run_cqlsh(cmd='TRUNCATE {}.{}'.format(ks_name, table), timeout=120)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2862, in run_cqlsh
    cqlsh_out = self.remoter.run(cmd, timeout=timeout + 30,  # we give 30 seconds to cqlsh timeout mechanism to work
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in run
    result = _run()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 61, in inner
    return func(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 596, in _run
    return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
    result = connection.run(**command_kwargs)
  File "", line 2, in run
  File "/usr/local/lib/python3.9/site-packages/fabric/connection.py", line 30, in opens
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/fabric/connection.py", line 721, in run
    return self._run(self._remote_runner(), command, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/invoke/context.py", line 101, in _run
    return runner.run(command, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/invoke/runners.py", line 291, in run
    return self._run_body(command, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/invoke/runners.py", line 442, in _run_body
    raise UnexpectedExit(result)
invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!

Command: 'cqlsh --no-color   --request-timeout=120 --connect-timeout=60 --ssl -e "TRUNCATE ks_truncate_large_partition.test_table" 3.239.32.32 9042'

Exit code: 2

Stdout:



Stderr:

:1:InvalidRequest: Error from server: code=2200 [Invalid query] message="Keyspace ks_truncate_large_partition does not exist"
```

test-id: `b2b540b6-2689-4f5c-a81f-43f248e49108`
nemesis: `TruncateMonkeyLargePartition`
monitor: http://34.241.224.63:3000/d/95EX8WjMz/longevity-lwt-24h-multidc-test-scylla-per-server-metrics-nemesis-master?orgId=1&from=1620323959186&to=1620324475709

**Comment by Orenef11** [comment]
Also, at `2021-05-06 18:24:38.168` there is another issue:
```
(DisruptionEvent Severity.ERROR): type=MemoryStress subtype=end node=Node lwt-longevity-multi-dc-24h-2021-1-db-node-b2b540b6-5 [35.167.170.190 | 10.0.2.137] (seed: False) duration=326 error=Encountered a bad command exit code!

Command: 'sudo apt install -y stress-ng'

Exit code: 100

Stdout:

Reading package lists...
Building dependency tree...
Reading state information...

No apt package "stress-ng", but there is a snap with that name.
Try "snap install stress-ng"


Stderr:


WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

E: Unable to locate package stress-ng


Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2955, in wrapper
    result = method(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3250, in disrupt
    self.call_random_disrupt_method()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1121, in call_random_disrupt_method
    self.execute_disrupt_method(disrupt_method)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1128, in execute_disrupt_method
    disrupt_method()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2799, in disrupt_memory_stress
    self.target_node.remoter.sudo('apt install -y stress-ng')
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/base.py", line 121, in sudo
    return self.run(cmd=cmd,
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in run
    result = _run()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 61, in inner
    return func(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 596, in _run
    return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
    result = connection.run(**command_kwargs)
  File "", line 2, in run
  File "/usr/local/lib/python3.9/site-packages/fabric/connection.py", line 30, in opens
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/fabric/connection.py", line 721, in run
    return self._run(self._remote_runner(), command, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/invoke/context.py", line 101, in _run
    return runner.run(command, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/invoke/runners.py", line 291, in run
    return self._run_body(command, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/invoke/runners.py", line 442, in _run_body
    raise UnexpectedExit(result)
invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!

Command: 'sudo apt install -y stress-ng'

Exit code: 100

Stdout:

Reading package lists...
Building dependency tree...
Reading state information...

No apt package "stress-ng", but there is a snap with that name.
Try "snap install stress-ng"


Stderr:


WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

E: Unable to locate package stress-ng
```

**Comment by roydahan** [comment]
Known Scylla issue

**Comment by roydahan** [comment]
Stress-ng is a different issue due to Ubuntu AMI.
Open a new one assign to Amos.
