### ISSUE TITLE
Clean resources fails when a test runs with "reuse_cluster"

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-cluster-tests#3691]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: [branch or hash tag you are working on] my private branch rebased with master
* **scylla**: [branch or commit hash]

### Logs
* test_id: [look for 'the Test ID' at the end of the log] 6273a07e-7767-49f5-a081-287261d79b58
* job log: sct-runner - https://cloudius-jenkins-test.s3.amazonaws.com/6273a07e-7767-49f5-a081-287261d79b58/20210621_135547/sct-runner-6273a07e.zip

[Jenkins job](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/yulia/job/staging-10gb-3h/190/console)

`sdcm.utils.common.clean_resources_according_post_behavior` fails to clean resources when a test runs with "reuse_cluster" 
```
21:09:28  Traceback (most recent call last):
21:09:28    File "/home/ubuntu/scylla-cluster-tests/./sct.py", line 1072, in <module>
21:09:28      cli()
21:09:28    File "/usr/local/lib/python3.9/site-packages/click/core.py", line 764, in __call__
21:09:28      return self.main(*args, **kwargs)
21:09:28    File "/usr/local/lib/python3.9/site-packages/click/core.py", line 717, in main
21:09:28      rv = self.invoke(ctx)
21:09:28    File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1137, in invoke
21:09:28      return _process_result(sub_ctx.command.invoke(sub_ctx))
21:09:28    File "/usr/local/lib/python3.9/site-packages/click/core.py", line 956, in invoke
21:09:28      return ctx.invoke(self.callback, **ctx.params)
21:09:28    File "/usr/local/lib/python3.9/site-packages/click/core.py", line 555, in invoke
21:09:28      return callback(*args, **kwargs)
21:09:28    File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 17, in new_func
21:09:28      return f(get_current_context(), *args, **kwargs)
21:09:28    File "/home/ubuntu/scylla-cluster-tests/./sct.py", line 192, in clean_resources
21:09:28      clean_func(param, dry_run=dry_run)
21:09:28    File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 1826, in clean_resources_according_post_behavior
21:09:28      os.environ['KUBECONFIG'] = str(Path(testrun_dir) / ".kube/config")
21:09:28    File "/usr/local/lib/python3.9/pathlib.py", line 1071, in __new__
21:09:28      self = cls._from_parts(args, init=False)
21:09:28    File "/usr/local/lib/python3.9/pathlib.py", line 696, in _from_parts
21:09:28      drv, root, parts = self._parse_args(args)
21:09:28    File "/usr/local/lib/python3.9/pathlib.py", line 680, in _parse_args
21:09:28      a = os.fspath(a)
21:09:28  TypeError: expected str, bytes or os.PathLike object, not NoneType
```
 When test runs with reuse cluster, SCT runner is created with test_id, different from cluster test_id. `TestId` param is set to runner test_id. So path to the folder with runner test_id can't be found

For example:
- cluster.test_id in the failed job is `6273a07e-7767-49f5-a081-287261d79b58`
- runner.test_id -  `c79b4f11-c99f-41e0-9ce7-a82bffeb4ac1`

From job output we see that `clean_resources_according_post_behavior` search test directory by runner. test_id:

```
    success = get_testrun_status(params.get('TestId'), logdir, only_critical=True)
    actions_per_type = get_post_behavior_actions(config)
    LOGGER.debug(actions_per_type)

    # Define 'KUBECONFIG' env var that is needed in some cases on K8S backends
    testrun_dir = get_testrun_dir(test_id=params.get('TestId'), base_dir=logdir)
    os.environ['KUBECONFIG'] = str(Path(testrun_dir) / ".kube/config")
```

and fails

```
21:09:28  Search dir with logs locally for test id: c79b4f11-c99f-41e0-9ce7-a82bffeb4ac1
21:09:28  Search result Command exited with status 123.
21:09:28  (no stdout)
21:09:28  (no stderr)
21:09:28  No any dirs found locally for current test id
21:09:28  Search dir with logs locally for test id: c79b4f11-c99f-41e0-9ce7-a82bffeb4ac1
21:09:28  Search result Command exited with status 123.
21:09:28  (no stdout)
21:09:28  (no stderr)
21:09:28  No any dirs found locally for current test id
```

**Comment by dkropachev** [comment]
@juliayakovlev , how did this job was started ? how did clean resources was triggered ?

**Comment by bentsi** [comment]
we don't use REUSE_CLUSTER as part of our YAML configuration for running tests, let's not fix this since in any case we will need to think about this when refactoring provision/install logic
