### ISSUE TITLE
Time to time we hit elasticsearch ceiling on request size

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla-cluster-tests#3728]
Time to time we hit elasticsearch ceiling on request size.
When it is happening we see this exception:

```
< t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > 2021-06-20 18:58:38.967: (ThreadFailedEvent Severity.ERROR) period_type=not-set event_id=09f8434b-8696-47a7-8ab9-dad05141899f: message=TransportError(429, 'circuit_breaking_exception', '[parent] Data too large, data for [<http_request>] would be [1067233530/1017.7mb], which is larger than the limit of [1020054732/972.7mb], real usage: [1067232576/1017.7mb], new bytes reserved: [954/954b], usages [request=51888128/49.4mb, fielddata=4202/4.1kb, in_flight_requests=207550474/197.9mb, model_inference=0/0b, accounting=56641464/54mb]')
< t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > Traceback (most recent call last):
< t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/sct_events/decorators.py", line 26, in wrapper
< t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >     return func(*args, **kwargs)
< t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 272, in run
< t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >     self.disrupt()
< t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2999, in wrapper
< t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >     args[0].update_stats(disrupt, status, log_info)
< t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 192, in update_stats
< t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >     self.es_publisher.publish(disrupt_name=disrupt, status=status, data=data)
< t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis_publisher.py", line 90, in publish
< t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >     res = self.es.index(index=self.index_name, doc_type='nemesis', body=new_nemesis_data)
< t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >   File "/usr/local/lib/python3.9/site-packages/elasticsearch/client/utils.py", line 153, in _wrapped
< t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >     return func(*args, params=params, headers=headers, **kwargs)
< t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >   File "/usr/local/lib/python3.9/site-packages/elasticsearch/client/__init__.py", line 398, in index
< t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >     return self.transport.perform_request(
< t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >   File "/usr/local/lib/python3.9/site-packages/elasticsearch/transport.py", line 415, in perform_request
< t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >     raise e
< t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >   File "/usr/local/lib/python3.9/site-packages/elasticsearch/transport.py", line 381, in perform_request
< t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >     status, headers_response, data = connection.perform_request(
< t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >   File "/usr/local/lib/python3.9/site-packages/elasticsearch/connection/http_urllib3.py", line 275, in perform_request
< t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >     self._raise_error(response.status, raw_data)
< t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >   File "/usr/local/lib/python3.9/site-packages/elasticsearch/connection/base.py", line 322, in _raise_error
< t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  >     raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
< t:2021-06-20 18:58:38,969 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > elasticsearch.exceptions.TransportError: TransportError(429, 'circuit_breaking_exception', '[parent] Data too large, data for [<http_request>] would be [1067233530/1017.7mb], which is larger than the limit of [1020054732/972.7mb], real usage: [1067232576/1017.7mb], new bytes reserved: [954/954b], usages [request=51888128/49.4mb, fielddata=4202/4.1kb, in_flight_requests=207550474/197.9mb, model_inference=0/0b, accounting=56641464/54mb]')
```

**Comment by dkropachev** [comment]
@vponomaryov , I know you are working on it, could you please take care of the issue

**Comment by fgelcer** [comment]
thank you @dkropachev

**Comment by vponomaryov** [comment]
Yesterday was merged workaround for that problem: https://github.com/scylladb/scylla-cluster-tests/commit/ff689f55
@dkropachev , @fgelcer - Cherry-pick it where you need it.

**Comment by dkropachev** [comment]
thanks @vponomaryov closing it
