### ISSUE TITLE
Unhandled exception, Permission denied (publickey,gssapi-keyex,gssapi-with-mic).

### ISSUE THREAD

**Issue by harelassayag** [scylladb/scylla-cluster-tests#377]
Unhandled exception, Permission denied. Happens only on some of the nemsis
```
2017-09-12 19:03:03,335 nemesis          L0170 DEBUG| sdcm.nemesis.ChaosMonkey: Set current_disruption -> ModifyTableProperties Node longevity-50gb-4d-enterprise-db-node-f9eb33f8-0-16 [104.196.117.12 | 10.240.0.
20] (seed: False)
2017-09-12 19:03:03,335 nemesis          L0172 INFO | sdcm.nemesis.ChaosMonkey: ModifyTableProperties Node longevity-50gb-4d-enterprise-db-node-f9eb33f8-0-16 [104.196.117.12 | 10.240.0.20] (seed: False)
2017-09-12 19:03:03,511 remote           L0197 DEBUG| [10.240.0.26] [stdout] total,    14935999470,   74346,   74346,   74346,    13.4,    11.5,    32.5,    47.2,    70.4,   135.7,204230.6,  0.00015,      0,    
  0,       0,       0,       0,       0
2017-09-12 19:03:03,716 remote           L0894 DEBUG| Remote [scylla-test@10.240.0.20]: Running 'cqlsh -e "ALTER TABLE keyspace1.standard1 with comment = 'zqhPmZRgObelPyqUEBjqwPPs';" 10.240.0.20'
2017-09-12 19:03:03,716 remote           L0097 INFO | [10.240.0.20] Running '/bin/ssh -tt -a -x   -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpty4hkm -o BatchMode=yes -o ConnectTimeout=300 -o Se
rverAliveInterval=300 -l scylla-test -p 22 -i /jenkins/.ssh/scylla-test 10.240.0.20 "cqlsh -e \"ALTER TABLE keyspace1.standard1 with comment = 'zqhPmZRgObelPyqUEBjqwPPs';\" 10.240.0.20"'
2017-09-12 19:03:03,746 remote           L0197 DEBUG| [10.240.0.20] [stderr] Warning: Identity file /jenkins/.ssh/scylla-test not accessible: No such file or directory.
2017-09-12 19:03:03,849 remote           L0197 DEBUG| [10.240.0.20] [stderr] Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
2017-09-12 19:03:03,850 nemesis          L0418 ERROR| sdcm.nemesis.ChaosMonkey: Unhandled exception in method <function disrupt at 0x5299b18>
Traceback (most recent call last):
  File "/jenkins/slave/workspace/scylla-enterprise-2017.1-longevity-gce/label/gce/sdcm/nemesis.py", line 415, in wrapper
    result = method(*args, **kwargs)
  File "/jenkins/slave/workspace/scylla-enterprise-2017.1-longevity-gce/label/gce/sdcm/nemesis.py", line 538, in disrupt
    self.call_random_disrupt_method()
  File "/jenkins/slave/workspace/scylla-enterprise-2017.1-longevity-gce/label/gce/sdcm/nemesis.py", line 358, in call_random_disrupt_method
    disrupt_method()
  File "/jenkins/slave/workspace/scylla-enterprise-2017.1-longevity-gce/label/gce/sdcm/nemesis.py", line 378, in disrupt_modify_table_comment
    self.target_node.remoter.run('cqlsh -e "{}" {}'.format(cmd, self.target_node.private_ip_address), verbose=True)
  File "/jenkins/slave/workspace/scylla-enterprise-2017.1-longevity-gce/label/gce/sdcm/remote.py", line 905, in run
    watch_stdout_pattern=watch_stdout_pattern)
  File "/jenkins/slave/workspace/scylla-enterprise-2017.1-longevity-gce/label/gce/sdcm/remote.py", line 849, in _run
    watch_stdout_pattern=watch_stdout_pattern)
  File "/jenkins/slave/workspace/scylla-enterprise-2017.1-longevity-gce/label/gce/sdcm/remote.py", line 228, in ssh_run
    raise process.CmdError(cmd, sp.result)
CmdError: Command '/bin/ssh -tt -a -x   -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpty4hkm -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l scylla-test -p 22 -i /jenkins/.ss
h/scylla-test 10.240.0.20 "cqlsh -e \"ALTER TABLE keyspace1.standard1 with comment = 'zqhPmZRgObelPyqUEBjqwPPs';\" 10.240.0.20"' failed (rc=255)
2017-09-12 19:03:03,866 nemesis          L0426 DEBUG| sdcm.nemesis.ChaosMonkey: ModifyTableProperties Node longevity-50gb-4d-enterprise-db-node-f9eb33f8-0-16 [104.196.117.12 | 10.240.0.20] (seed: False) duration
 -> 1 s
2017-09-12 19:03:03,866 remote           L0894 DEBUG| Remote [scylla-test@10.240.0.5]: Running 'nodetool status'
2017-09-12 19:03:03,867 remote           L0097 INFO | [10.240.0.5] Running '/bin/ssh -tt -a -x   -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpyLH8uD -o BatchMode=yes -o ConnectTimeout=300 -o Ser
verAliveInterval=300 -l scylla-test -p 22 -i /jenkins/.ssh/scylla-test 10.240.0.5 "nodetool status"'
2017-09-12 19:03:03,901 remote           L0197 DEBUG| [10.240.0.5] [stderr] Warning: Identity file /jenkins/.ssh/scylla-test not accessible: No such file or directory.
2017-09-12 19:03:04,017 remote           L0197 DEBUG| [10.240.0.5] [stderr] Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
2017-09-12 19:03:04,572 nemesis          L0114 ERROR| sdcm.nemesis.ChaosMonkey: nodetool command 'nodetool status' failed on node Node longevity-50gb-4d-enterprise-db-node-f9eb33f8-0-16 [104.196.117.12 | 10.240.0.20] (seed: False): Command: /bin/ssh -tt -a -x   -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpyLH8uD -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l scylla-test -p 22 -i /jenkins/.ssh/scylla-test 10.240.0.5 "nodetool status"
Exit status: 255
Duration: 0.123158931732
Stdout:

Stderr:
Warning: Identity file /jenkins/.ssh/scylla-test not accessible: No such file or directory.
Permission denied (publickey,gssapi-keyex,gssapi-with-mic).

```

**Comment by amoskong** [comment]
The problem is that the private key doesn't exist.

2017-09-12 19:03:03,901 remote           L0197 DEBUG| [10.240.0.5] [stderr] Warning: Identity file /jenkins/.ssh/scylla-test not accessible: No such file or directory.

It might be a environment issue, we prepared the private key in Jenkins.

**Comment by amoskong** [comment]
env issue, closed.

**Comment by bismaya123** [comment]
Hello I'm getting below error in jenkin build log though i have added the ssh public key to git server.

Fetching changes from the remote Git repository
 > C:\Program Files\Git\bin\git config remote.origin.url git@git.sami.int.thomsonreuters.com:TRDA-Development/database.git # timeout=10
Fetching upstream changes from git@git.sami.int.thomsonreuters.com:TRDA-Development/database.git
 > C:\Program Files\Git\bin\git --version # timeout=10
 > C:\Program Files\Git\bin\git fetch --tags --progress git@git.sami.int.thomsonreuters.com:TRDA-Development/database.git +refs/heads/*:refs/remotes/origin/*
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from git@git.sami.int.thomsonreuters.com:TRDA-Development/database.git
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:888)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1155)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1186)
	at org.jenkinsci.plugins.multiplescms.MultiSCM.checkout(MultiSCM.java:129)
	at hudson.scm.SCM.checkout(SCM.java:485)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1269)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:607)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
	at hudson.model.Run.execute(Run.java:1738)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Caused by: hudson.plugins.git.GitException: Command "C:\Program Files\Git\bin\git fetch --tags --progress git@git.sami.int.thomsonreuters.com:TRDA-Development/database.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: ***************************************************************************
* This computer system is the property of Thomson Reuters and may be      *
* accessed only by authorized users. Unauthorized use of this system is   *
* strictly prohibited and may be subject to criminal prosecution.  Your   *
* use of Thomson Reuters systems and networks is permitted only in        *
* accordance with Thomson Reuters policies, including the Code of         *
* Business Conduct and Ethics.  Where permitted by applicable law, we     *
* reserve the right to monitor your use of these systems and networks and *
* review any communications made through them.  By accessing the Thomson  *
* Reuters system, you consent to such monitoring and to the retrieval of  *
* information required for law enforcement or for the purpose of          *
* protecting Thomson Reuters intellectual property and the                *
* confidentiality of our corporate, client, and personnel data.           *
*                                                                         *
* For support on SAMI Git please visit:                                   *
*         https://thehub.thomsonreuters.com/groups/sami                   *
***************************************************************************
Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by bentsi** [comment]
@bismaya123 how is this related to Scylla Cluster Tests?

**Comment by bismaya123** [comment]
no this is not related to Scylla Cluster Tests but i have pretty same error in my project so thought i could get some help here.
