### ISSUE TITLE
log collector fails collecting cloud manager logs: KeyError: 'cloud_manager_id'

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#3816]
```
01:46:55  Found latest test_id: 8f04069f-c6ad-443f-8a99-42d98e7be19e
01:46:55  Collect logs for test-run with test-id: 8f04069f-c6ad-443f-8a99-42d98e7be19e
01:46:59  Traceback (most recent call last):
01:46:59    File "/home/ubuntu/scylla-cluster-tests/./sct.py", line 1109, in <module>
01:46:59      cli()
01:46:59    File "/usr/local/lib/python3.9/site-packages/click/core.py", line 764, in __call__
01:46:59      return self.main(*args, **kwargs)
01:46:59    File "/usr/local/lib/python3.9/site-packages/click/core.py", line 717, in main
01:46:59      rv = self.invoke(ctx)
01:46:59    File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1137, in invoke
01:46:59      return _process_result(sub_ctx.command.invoke(sub_ctx))
01:46:59    File "/usr/local/lib/python3.9/site-packages/click/core.py", line 956, in invoke
01:46:59      return ctx.invoke(self.callback, **ctx.params)
01:46:59    File "/usr/local/lib/python3.9/site-packages/click/core.py", line 555, in invoke
01:46:59      return callback(*args, **kwargs)
01:46:59    File "/home/ubuntu/scylla-cluster-tests/./sct.py", line 828, in collect_logs
01:46:59      collected_logs = collector.run()
01:46:59    File "/home/ubuntu/scylla-cluster-tests/sdcm/logcollector.py", line 1251, in run
01:46:59      self.get_running_cluster_sets(self.backend)
01:46:59    File "/home/ubuntu/scylla-cluster-tests/sdcm/logcollector.py", line 1232, in get_running_cluster_sets
01:46:59      self.get_aws_instances_by_testid()
01:46:59    File "/home/ubuntu/scylla-cluster-tests/sdcm/logcollector.py", line 1130, in get_aws_instances_by_testid
01:46:59      manager_id=self.params["cloud_manager_id"])
01:46:59  KeyError: 'cloud_manager_id'
```

**Comment by Orenef11** [comment]
I know, there are 2 PRs that fix it:
 https://github.com/scylladb/scylla-cluster-tests/pull/3815
https://github.com/scylladb/siren-tests/pull/639

**Comment by Orenef11** [comment]
The PRs were merged
