### ISSUE TITLE
successful cloud manager backup command fails for needless stderr output check

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#3818]
When running sdcm.nemesis.MgmtBackup with cloud manager it doesn't have the awkward meaningless stderr as in original manager (https://github.com/scylladb/scylla-cluster-tests/blob/fc6c562639d3abf843972347c45c89f70430d01f/sdcm/mgmt/cli.py#L443)

so the although the cloud manager command finish successfully, it raises exception for this.
(i think it is needless to check and raise for this if stdout returns the expected value - that's just manager design.)
```
< t:2021-07-26 12:43:24,460 f:base.py         l:142  c:RemoteCmdRunner      p:DEBUG > Command "/opt/scylla/scylla-cloud -c /opt/scylla/scylla-dbaas.yml cluster manager sctool --cluster-id 10998 --  backup  --location AWS_US_EAST_1:s3:scylla-cloud-backup-10998-11166-533aqn " finished with status 0
< t:2021-07-26 12:43:24,460 f:cli.py          l:1015 c:sdcm.mgmt.cli        p:DEBUG > sctool output: backup/fc271f0c-610c-434e-b26a-af8f2c6a7783

< t:2021-07-26 12:43:24,460 f:cli.py          l:1031 c:sdcm.mgmt.cli        p:DEBUG > sctool res after parsing: Command exited with status 0.
< t:2021-07-26 12:43:24,460 f:cli.py          l:1031 c:sdcm.mgmt.cli        p:DEBUG > === stdout ===
< t:2021-07-26 12:43:24,460 f:cli.py          l:1031 c:sdcm.mgmt.cli        p:DEBUG > backup/fc271f0c-610c-434e-b26a-af8f2c6a7783
< t:2021-07-26 12:43:24,460 f:cli.py          l:1031 c:sdcm.mgmt.cli        p:DEBUG > 
< t:2021-07-26 12:43:24,460 f:cli.py          l:1031 c:sdcm.mgmt.cli        p:DEBUG > === stderr ===
< t:2021-07-26 12:43:24,460 f:cli.py          l:1031 c:sdcm.mgmt.cli        p:DEBUG > {"level":"debug","ts":1627303403.744257,"caller":"track/track.go:78","msg":"Action Start","Action":"MANAGER_COMMAND","TrackID":436212}
< t:2021-07-26 12:43:24,461 f:cli.py          l:448  c:sdcm.mgmt.cli        p:DEBUG > Encountered an error on 'backup -c CLOUD_CLUSTER_ID --location AWS_US_EAST_1:s3:scylla-cloud-backup-10998-11166-533aqn ' command response
< t:2021-07-26 12:43:24,462 f:nemesis.py      l:2988 c:sdcm.nemesis         p:ERROR > sdcm.nemesis.MgmtBackup: Unhandled exception in method <function Nemesis.disrupt_mgmt_backup at 0x7f990f860160> < t:2021-07-26 12:43:24,462 f:nemesis.py      l:2988 c:sdcm.nemesis         p:ERROR > sdcm.nemesis.MgmtBackup: Unhandled exception in method <function Nemesis.disrupt_mgmt_backup at 0x7f990f860160>
< t:2021-07-26 12:43:24,462 f:nemesis.py      l:2988 c:sdcm.nemesis         p:ERROR > Traceback (most recent call last):
< t:2021-07-26 12:43:24,462 f:nemesis.py      l:2988 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2977, in wrapper
< t:2021-07-26 12:43:24,462 f:nemesis.py      l:2988 c:sdcm.nemesis         p:ERROR >     result = method(*args, **kwargs)
< t:2021-07-26 12:43:24,462 f:nemesis.py      l:2988 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1760, in disrupt_mgmt_backup
< t:2021-07-26 12:43:24,462 f:nemesis.py      l:2988 c:sdcm.nemesis         p:ERROR >     self._mgmt_backup(backup_specific_tables=False)
< t:2021-07-26 12:43:24,462 f:nemesis.py      l:2988 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1785, in _mgmt_backup
< t:2021-07-26 12:43:24,462 f:nemesis.py      l:2988 c:sdcm.nemesis         p:ERROR >     mgr_task = mgr_cluster.create_backup_task(location_list=[location, ])
< t:2021-07-26 12:43:24,462 f:nemesis.py      l:2988 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/mgmt/cli.py", line 449, in create_backup_task
< t:2021-07-26 12:43:24,462 f:nemesis.py      l:2988 c:sdcm.nemesis         p:ERROR >     raise ScyllaManagerError(res.stderr)
< t:2021-07-26 12:43:24,462 f:nemesis.py      l:2988 c:sdcm.nemesis         p:ERROR > sdcm.mgmt.common.ScyllaManagerError: {"level":"debug","ts":1627303403.744257,"caller":"track/track.go:78","msg":"Action Start","Action":"MANAGER_COMMAND","TrackID":436212}
< t:2021-07-26 12:43:24,463 f:nemesis.py      l:3001 c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.MgmtBackup: MgmtBackup Node cloud_nemesis_debug-cloud-ne-db-node-030dea91-3 [54.204.25.144 | 172.31.2.11] (seed: True) duration -> 9 s
```

**Comment by yarongilor** [comment]
Fixed in https://github.com/scylladb/scylla-cluster-tests/pull/3819
