### ISSUE TITLE
scylla-master-perf-regression-aws-test-throughput-disk-cache failed with docker toomanyrequests error

### ISSUE THREAD

**Issue by enaydanov** [scylladb/scylla-cluster-tests#3850]
[Build #12](https://jenkins.scylladb.com/view/Performance/job/scylla-master/job/scylla-master-perf-regression-aws-test-throughput-disk-cache/12) of scylla-master/scylla-master-perf-regression-aws-test-throughput-disk-cache job failed because of Docker error:

```
 < t:2021-07-30 03:25:30,603 f:tester.py       l:131  c:sdcm.tester          p:ERROR > Traceback (most recent call last):
 < t:2021-07-30 03:25:30,603 f:tester.py       l:131  c:sdcm.tester          p:ERROR >   File "/home/jenkins/slave/workspace/scylla-master/scylla-master-perf-regression-aws-test-throughput-disk-cache@4/scylla-cluster-tests/sdcm/cluster.py", line 3549, in node_setup
 < t:2021-07-30 03:25:30,603 f:tester.py       l:131  c:sdcm.tester          p:ERROR >     cl_inst.node_setup(_node, **setup_kwargs)
 < t:2021-07-30 03:25:30,603 f:tester.py       l:131  c:sdcm.tester          p:ERROR >   File "/home/jenkins/slave/workspace/scylla-master/scylla-master-perf-regression-aws-test-throughput-disk-cache@4/scylla-cluster-tests/sdcm/cluster.py", line 4898, in node_setup
 < t:2021-07-30 03:25:30,603 f:tester.py       l:131  c:sdcm.tester          p:ERROR >     self.configure_scylla_monitoring(node)
 < t:2021-07-30 03:25:30,603 f:tester.py       l:131  c:sdcm.tester          p:ERROR >   File "/home/jenkins/slave/workspace/scylla-master/scylla-master-perf-regression-aws-test-throughput-disk-cache@4/scylla-cluster-tests/sdcm/cluster.py", line 5086, in configure_scylla_monitoring
 < t:2021-07-30 03:25:30,603 f:tester.py       l:131  c:sdcm.tester          p:ERROR >     self.reconfigure_scylla_monitoring()
 < t:2021-07-30 03:25:30,603 f:tester.py       l:131  c:sdcm.tester          p:ERROR >   File "/home/jenkins/slave/workspace/scylla-master/scylla-master-perf-regression-aws-test-throughput-disk-cache@4/scylla-cluster-tests/sdcm/utils/decorators.py", line 61, in inner
 < t:2021-07-30 03:25:30,603 f:tester.py       l:131  c:sdcm.tester          p:ERROR >     return func(*args, **kwargs)
 < t:2021-07-30 03:25:30,603 f:tester.py       l:131  c:sdcm.tester          p:ERROR >   File "/home/jenkins/slave/workspace/scylla-master/scylla-master-perf-regression-aws-test-throughput-disk-cache@4/scylla-cluster-tests/sdcm/cluster.py", line 5161, in reconfigure_scylla_monitoring
 < t:2021-07-30 03:25:30,603 f:tester.py       l:131  c:sdcm.tester          p:ERROR >     node.remoter.sudo(f"docker run --rm -v {self.monitoring_conf_dir}:/workdir"
 < t:2021-07-30 03:25:30,603 f:tester.py       l:131  c:sdcm.tester          p:ERROR >   File "/home/jenkins/slave/workspace/scylla-master/scylla-master-perf-regression-aws-test-throughput-disk-cache@4/scylla-cluster-tests/sdcm/remote/base.py", line 121, in sudo
 < t:2021-07-30 03:25:30,603 f:tester.py       l:131  c:sdcm.tester          p:ERROR >     return self.run(cmd=cmd,
 < t:2021-07-30 03:25:30,603 f:tester.py       l:131  c:sdcm.tester          p:ERROR >   File "/home/jenkins/slave/workspace/scylla-master/scylla-master-perf-regression-aws-test-throughput-disk-cache@4/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in run
 < t:2021-07-30 03:25:30,603 f:tester.py       l:131  c:sdcm.tester          p:ERROR >     result = _run()
 < t:2021-07-30 03:25:30,603 f:tester.py       l:131  c:sdcm.tester          p:ERROR >   File "/home/jenkins/slave/workspace/scylla-master/scylla-master-perf-regression-aws-test-throughput-disk-cache@4/scylla-cluster-tests/sdcm/utils/decorators.py", line 61, in inner
 < t:2021-07-30 03:25:30,603 f:tester.py       l:131  c:sdcm.tester          p:ERROR >     return func(*args, **kwargs)
 < t:2021-07-30 03:25:30,603 f:tester.py       l:131  c:sdcm.tester          p:ERROR >   File "/home/jenkins/slave/workspace/scylla-master/scylla-master-perf-regression-aws-test-throughput-disk-cache@4/scylla-cluster-tests/sdcm/remote/remote_base.py", line 596, in _run
 < t:2021-07-30 03:25:30,603 f:tester.py       l:131  c:sdcm.tester          p:ERROR >     return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
 < t:2021-07-30 03:25:30,603 f:tester.py       l:131  c:sdcm.tester          p:ERROR >   File "/home/jenkins/slave/workspace/scylla-master/scylla-master-perf-regression-aws-test-throughput-disk-cache@4/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
 < t:2021-07-30 03:25:30,603 f:tester.py       l:131  c:sdcm.tester          p:ERROR >     result = connection.run(**command_kwargs)
 < t:2021-07-30 03:25:30,603 f:tester.py       l:131  c:sdcm.tester          p:ERROR >   File "<decorator-gen-3>", line 2, in run
 < t:2021-07-30 03:25:30,603 f:tester.py       l:131  c:sdcm.tester          p:ERROR >   File "/usr/local/lib/python3.9/site-packages/fabric/connection.py", line 30, in opens
 < t:2021-07-30 03:25:30,603 f:tester.py       l:131  c:sdcm.tester          p:ERROR >     return method(self, *args, **kwargs)
 < t:2021-07-30 03:25:30,603 f:tester.py       l:131  c:sdcm.tester          p:ERROR >   File "/usr/local/lib/python3.9/site-packages/fabric/connection.py", line 721, in run
 < t:2021-07-30 03:25:30,603 f:tester.py       l:131  c:sdcm.tester          p:ERROR >     return self._run(self._remote_runner(), command, **kwargs)
 < t:2021-07-30 03:25:30,603 f:tester.py       l:131  c:sdcm.tester          p:ERROR >   File "/usr/local/lib/python3.9/site-packages/invoke/context.py", line 101, in _run
 < t:2021-07-30 03:25:30,603 f:tester.py       l:131  c:sdcm.tester          p:ERROR >     return runner.run(command, **kwargs)
 < t:2021-07-30 03:25:30,603 f:tester.py       l:131  c:sdcm.tester          p:ERROR >   File "/usr/local/lib/python3.9/site-packages/invoke/runners.py", line 291, in run
 < t:2021-07-30 03:25:30,603 f:tester.py       l:131  c:sdcm.tester          p:ERROR >     return self._run_body(command, **kwargs)
 < t:2021-07-30 03:25:30,603 f:tester.py       l:131  c:sdcm.tester          p:ERROR >   File "/usr/local/lib/python3.9/site-packages/invoke/runners.py", line 442, in _run_body
 < t:2021-07-30 03:25:30,603 f:tester.py       l:131  c:sdcm.tester          p:ERROR >     raise UnexpectedExit(result)
 < t:2021-07-30 03:25:30,603 f:tester.py       l:131  c:sdcm.tester          p:ERROR > invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!
 < t:2021-07-30 03:25:30,603 f:tester.py       l:131  c:sdcm.tester          p:ERROR > 
 < t:2021-07-30 03:25:30,603 f:tester.py       l:131  c:sdcm.tester          p:ERROR > Command: "sudo docker run --rm -v /home/centos/sct-monitoring/scylla-monitoring-src/config:/workdir mikefarah/yq:3 yq w -i node_exporter_servers.yml '[0].targets[+]' ''[10.0.0.116]:9100''"
 < t:2021-07-30 03:25:30,603 f:tester.py       l:131  c:sdcm.tester          p:ERROR > 
 < t:2021-07-30 03:25:30,603 f:tester.py       l:131  c:sdcm.tester          p:ERROR > Exit code: 125
 < t:2021-07-30 03:25:30,603 f:tester.py       l:131  c:sdcm.tester          p:ERROR > 
 < t:2021-07-30 03:25:30,603 f:tester.py       l:131  c:sdcm.tester          p:ERROR > Stdout:
 < t:2021-07-30 03:25:30,603 f:tester.py       l:131  c:sdcm.tester          p:ERROR > 
 < t:2021-07-30 03:25:30,603 f:tester.py       l:131  c:sdcm.tester          p:ERROR > 
 < t:2021-07-30 03:25:30,603 f:tester.py       l:131  c:sdcm.tester          p:ERROR > 
 < t:2021-07-30 03:25:30,603 f:tester.py       l:131  c:sdcm.tester          p:ERROR > Stderr:
 < t:2021-07-30 03:25:30,603 f:tester.py       l:131  c:sdcm.tester          p:ERROR > 
 < t:2021-07-30 03:25:30,603 f:tester.py       l:131  c:sdcm.tester          p:ERROR > Unable to find image 'mikefarah/yq:3' locally
 < t:2021-07-30 03:25:30,603 f:tester.py       l:131  c:sdcm.tester          p:ERROR > docker: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit.
 < t:2021-07-30 03:25:30,603 f:tester.py       l:131  c:sdcm.tester          p:ERROR > See 'docker run --help'.
 < t:2021-07-30 03:25:30,603 f:tester.py       l:131  c:sdcm.tester          p:ERROR > 
 < t:2021-07-30 03:25:30,603 f:tester.py       l:131  c:sdcm.tester          p:ERROR > 
 < t:2021-07-30 03:25:30,607 f:tester.py       l:2213 c:PerformanceRegressionTest p:INFO  > TearDown is starting...
```

TestID: 5c4699f6-456b-4b8f-b4cd-356155e23f98

**Comment by roydahan** [comment]
Are we doing it with a specific user?
Don't we have some users that are not limited using the license we have?
@bentsi ?

**Comment by dkropachev** [comment]
We are doing it with no authorization, so the limit to 100 pulls per 6
hours per ip.
If we turn on authorization we will get 5000 per 24 hours, but it is not
clear whether requests are going to be bound by ip or by account.

**Comment by enaydanov** [comment]
Looks like we're unlimited: https://www.docker.com/blog/expanded-support-for-open-source-software-projects/

Just need to authorize.

**Comment by enaydanov** [comment]
Also, I tried to understand the limit of my account:

```$ ./jwt decode $TOKEN                                                                                                                                                                         
                                                                                                                                                                                                                     
Token header                                                                                                                                                                                                         
------------                                                                                                                                                                                                         
{                                                                                                                                                                                                                    
  "typ": "JWT",                                                                                                                                                                                                      
  "alg": "RS256"                                                                                                                                                                                                     
}                                                                                                                                                                                                                    
                                                                                                                                                                                                                     
Token claims                                                                                                                                                                                                         
------------                                                                                                                                                                                                         
{
  "access": [
    {
      "actions": [
        "pull"
      ],
      "name": "mikefarah/yq",
      "type": "repository"
    }
  ],
...
}
```

I.e., no limit.
