### ISSUE TITLE
Operator upgrade somehow trigger kubernetes API to respond 500 when node is added after the upgrade

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla-cluster-tests#3858]
Testid: 49d5c327-e249-4dbd-8793-5afd0706549a   
Job link: https://jenkins.scylladb.com/view/scylla-operator/job/scylla-operator/job/operator-1.4/job/upgrade/job/upgrade-operator-k8s-eks/6/

```
12:32:48  2021-08-06 09:28:28.637: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=32dda88e-05cb-43ff-a78e-c8e0731929c2, source=UpgradeTest.test_kubernetes_operator_upgrade (upgrade_test.UpgradeTest)() message=Traceback (most recent call last):
12:32:48  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 596, in _run
12:32:48  return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
12:32:48  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/kubernetes_cmd_runner.py", line 154, in _run_execute
12:32:48  return super()._run_execute(cmd, timeout=timeout, ignore_status=ignore_status, verbose=verbose,
12:32:48  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 530, in _run_execute
12:32:48  result = connection.run(**command_kwargs)
12:32:48  File "/usr/local/lib/python3.9/site-packages/invoke/runners.py", line 291, in run
12:32:48  return self._run_body(command, **kwargs)
12:32:48  File "/usr/local/lib/python3.9/site-packages/invoke/runners.py", line 315, in _run_body
12:32:48  self.start(command, shell, env)
12:32:48  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/kubernetes_cmd_runner.py", line 78, in start
12:32:48  raise ConnectionError(str(exc)) from None
12:32:48  ConnectionError: (0)
12:32:48  Reason: Handshake status 500 Internal Server Error
12:32:48  During handling of the above exception, another exception occurred:
12:32:48  Traceback (most recent call last):
12:32:48  File "/home/ubuntu/scylla-cluster-tests/upgrade_test.py", line 966, in test_kubernetes_operator_upgrade
12:32:48  new_nodes = self.db_cluster.add_nodes(
12:32:48  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster_k8s/eks.py", line 507, in add_nodes
12:32:48  new_nodes = super().add_nodes(count=count,
12:32:48  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster_k8s/__init__.py", line 2113, in add_nodes
12:32:48  return super().add_nodes(count=count,
12:32:48  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster_k8s/__init__.py", line 1795, in add_nodes
12:32:48  node = self._create_node(len(self.nodes), pod.metadata.name, dc_idx, rack)
12:32:48  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster_k8s/__init__.py", line 1767, in _create_node
12:32:48  node.init()
12:32:48  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster_k8s/__init__.py", line 1617, in init
12:32:48  self.remoter.sudo('yum install --downloadonly iproute', retry=5)
12:32:48  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/base.py", line 121, in sudo
12:32:48  return self.run(cmd=cmd,
12:32:48  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in run
12:32:48  result = _run()
12:32:48  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 61, in inner
12:32:48  return func(*args, **kwargs)
12:32:48  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 598, in _run
12:32:48  if self._run_on_retryable_exception(exc, new_session):
12:32:48  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/kubernetes_cmd_runner.py", line 174, in _run_on_retryable_exception
12:32:48  raise RetryableNetworkException(str(exc), original=exc)
12:32:48  sdcm.remote.base.RetryableNetworkException: (0)
12:32:48  Reason: Handshake status 500 Internal Server Error
```

### Versions
sct: operator-1.4
operator: v1.4.0-rc.0-0-g910a3e0
k8s: v1.20.4-eks-6b7464

### Logs
db-cluster  | https://cloudius-jenkins-test.s3.amazonaws.com/49d5c327-e249-4dbd-8793-5afd0706549a/20210806_093309/db-cluster-49d5c327.tar.gz  |
monitor-set | https://cloudius-jenkins-test.s3.amazonaws.com/49d5c327-e249-4dbd-8793-5afd0706549a/20210806_093309/monitor-set-49d5c327.tar.gz |
loader-set  | https://cloudius-jenkins-test.s3.amazonaws.com/49d5c327-e249-4dbd-8793-5afd0706549a/20210806_093309/loader-set-49d5c327.tar.gz  |
sct-runner  | https://cloudius-jenkins-test.s3.amazonaws.com/49d5c327-e249-4dbd-8793-5afd0706549a/20210806_093309/sct-runner-49d5c327.tar.gz  |
kubernetes  | https://cloudius-jenkins-test.s3.amazonaws.com/49d5c327-e249-4dbd-8793-5afd0706549a/20210806_093309/kubernetes-49d5c327.tar.gz 

### Steps to Reproduce

1. Run upgrade_test.UpgradeTest.test_kubernetes_operator_upgrade

**Comment by dkropachev** [comment]
Pod that was added stopped on iotune:

```
I0806 09:28:18.183377       1 operator/sidecar.go:149] sidecar version v1.4.0-rc.0-0-g910a3e0
I0806 09:28:18.183455       1 operator/sidecar.go:150] loglevel is set to "2"
I0806 09:28:18.207491       1 config/config.go:64] Setting up scylla.yaml
I0806 09:28:18.209387       1 config/config.go:68] Setting up cassandra-rackdc.properties
I0806 09:28:18.209425       1 config/config.go:157] "unable to read properties" file="/mnt/scylla-config/cassandra-rackdc.properties"
I0806 09:28:18.209529       1 config/config.go:72] Setting up entrypoint script
I0806 09:28:18.233479       1 config/config.go:290] "suboptimal shard and cpuset config, shard count (config: 'CPU') and cpuset size should match for optimal performance" shards=15 cpuset="0-15"
I0806 09:28:18.233524       1 config/config.go:251] "Scylla version detected" version={version:{Major:4 Minor:4 Patch:4 Pre:[] Build:[]} unknown:false}
I0806 09:28:18.233600       1 config/config.go:279] "Scylla entrypoint" Command="/docker-entrypoint.py --broadcast-rpc-address=172.20.213.177 --seeds=172.20.160.199 --developer-mode=0 --overprovisioned=1 --smp=15 --cpuset=0-15 --listen-address=0.0.0.0 --broadcast-address=172.20.213.177"
I0806 09:28:18.234564       1 sidecar/controller.go:171] "Starting controller" Controller="SidecarController"
I0806 09:28:18.234591       1 cache/shared_informer.go:240] Waiting for caches to sync for SidecarController
I0806 09:28:18.234589       1 cache/shared_informer.go:240] Waiting for caches to sync for Prober
I0806 09:28:18.234633       1 cache/reflector.go:219] Starting reflector *v1.Secret (12h0m0s) from k8s.io/client-go@v0.21.1/tools/cache/reflector.go:167
I0806 09:28:18.234651       1 cache/reflector.go:219] Starting reflector *v1.Service (12h0m0s) from k8s.io/client-go@v0.21.1/tools/cache/reflector.go:167
I0806 09:28:18.335058       1 cache/shared_informer.go:247] Caches are synced for Prober 
I0806 09:28:18.335096       1 operator/sidecar.go:270] "Starting Prober server"
running: (['/opt/scylladb/scripts/scylla_dev_mode_setup', '--developer-mode', '0'],)
I0806 09:28:18.734988       1 cache/shared_informer.go:247] Caches are synced for SidecarController 
running: (['/opt/scylladb/scripts/scylla_cpuset_setup', '--cpuset', '0-15'],)
running: (['/opt/scylladb/scripts/scylla_io_setup'],)
INFO  2021-08-06 09:28:19,520 [shard 0] iotune - /var/lib/scylla/saved_caches passed sanity checks
WARN  2021-08-06 09:28:19,521 [shard 0] iotune - nomerges for /sys/devices/pci0000:00/0000:00:1d.0/nvme/nvme0/nvme0n1/queue/nomerges set to 0. It is recommend to set it to 2 before evaluation so that merges are disabled. Results can be skewed otherwise.
WARN  2021-08-06 09:28:19,521 [shard 0] iotune - nomerges for /sys/devices/pci0000:00/0000:00:1e.0/nvme/nvme1/nvme1n1/queue/nomerges set to 0. It is recommend to set it to 2 before evaluation so that merges are disabled. Results can be skewed otherwise.
INFO  2021-08-06 09:28:19,521 [shard 0] iotune - Disk parameters: max_iodepth=2046 disks_per_array=2 minimum_io_size=512
Starting Evaluation. This may take a while...
E0806 09:28:24.039813       1 sidecar/probes.go:172] "healthz probe: can't connect to JMX" err="dial tcp 10.0.1.250:10001: connect: connection refused" Service="scylla/sct-cluster-us-east1-b-us-east1-3"
E0806 09:28:34.039979       1 sidecar/probes.go:172] "healthz probe: can't connect to JMX" err="dial tcp 10.0.1.250:10001: connect: connection refused" Service="scylla/sct-cluster-us-east1-b-us-east1-3"
E0806 09:28:44.039817       1 sidecar/probes.go:172] "healthz probe: can't connect to JMX" err="dial tcp 10.0.1.250:10001: connect: connection refused" Service="scylla/sct-cluster-us-east1-b-us-east1-3"
E0806 09:28:54.039801       1 sidecar/probes.go:172] "healthz probe: can't connect to JMX" err="dial tcp 10.0.1.250:10001: connect: connection refused" Service="scylla/sct-cluster-us-east1-b-us-east1-3"
```

**Comment by dkropachev** [comment]
Node info:

```
Name:               ip-10-0-1-250.eu-north-1.compute.internal
Roles:              <none>
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=i3.4xlarge
                    beta.kubernetes.io/os=linux
                    eks.amazonaws.com/capacityType=ON_DEMAND
                    eks.amazonaws.com/nodegroup=scylla-pool
                    eks.amazonaws.com/nodegroup-image=ami-0e84d3087df4f5ff4
                    failure-domain.beta.kubernetes.io/region=eu-north-1
                    failure-domain.beta.kubernetes.io/zone=eu-north-1a
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=ip-10-0-1-250.eu-north-1.compute.internal
                    kubernetes.io/os=linux
                    node.kubernetes.io/instance-type=i3.4xlarge
                    topology.kubernetes.io/region=eu-north-1
                    topology.kubernetes.io/zone=eu-north-1a
Annotations:        node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Fri, 06 Aug 2021 08:26:16 +0000
Taints:             <none>
Unschedulable:      false
Lease:
  HolderIdentity:  ip-10-0-1-250.eu-north-1.compute.internal
  AcquireTime:     <unset>
  RenewTime:       Fri, 06 Aug 2021 09:28:41 +0000
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  MemoryPressure   False   Fri, 06 Aug 2021 09:28:21 +0000   Fri, 06 Aug 2021 08:26:16 +0000   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Fri, 06 Aug 2021 09:28:21 +0000   Fri, 06 Aug 2021 08:26:16 +0000   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False   Fri, 06 Aug 2021 09:28:21 +0000   Fri, 06 Aug 2021 08:26:16 +0000   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            True    Fri, 06 Aug 2021 09:28:21 +0000   Fri, 06 Aug 2021 08:26:36 +0000   KubeletReady                 kubelet is posting ready status
Addresses:
  InternalIP:   10.0.1.250
  ExternalIP:   13.51.234.100
  Hostname:     ip-10-0-1-250.eu-north-1.compute.internal
  InternalDNS:  ip-10-0-1-250.eu-north-1.compute.internal
Capacity:
  attachable-volumes-aws-ebs:  39
  cpu:                         16
  ephemeral-storage:           31444972Ki
  hugepages-1Gi:               0
  hugepages-2Mi:               0
  memory:                      125709124Ki
  pods:                        234
Allocatable:
  attachable-volumes-aws-ebs:  39
  cpu:                         15890m
  ephemeral-storage:           27905944324
  hugepages-1Gi:               0
  hugepages-2Mi:               0
  memory:                      122709828Ki
  pods:                        234
System Info:
  Machine ID:                 622e40502253422bb5f4b9758a31590c
  System UUID:                ec2ae4f4-cd58-fd38-f89b-eeba68f3543f
  Boot ID:                    a7ccc85a-836f-4936-a2c4-86f2ab45750a
  Kernel Version:             5.4.129-63.229.amzn2.x86_64
  OS Image:                   Amazon Linux 2
  Operating System:           linux
  Architecture:               amd64
  Container Runtime Version:  docker://19.3.13
  Kubelet Version:            v1.20.4-eks-6b7464
  Kube-Proxy Version:         v1.20.4-eks-6b7464
ProviderID:                   aws:///eu-north-1a/i-03d205d98b0ac6a6c
Non-terminated Pods:          (5 in total)
  Namespace                   Name                                 CPU Requests  CPU Limits  Memory Requests     Memory Limits  Age
  ---------                   ----                                 ------------  ----------  ---------------     -------------  ---
  default                     local-volume-provisioner-k5wpd       0 (0%)        0 (0%)      0 (0%)              0 (0%)         59m
  default                     node-setup-g9dhj                     0 (0%)        0 (0%)      0 (0%)              0 (0%)         59m
  kube-system                 aws-node-t4djl                       10m (0%)      0 (0%)      0 (0%)              0 (0%)         62m
  kube-system                 kube-proxy-hlcsn                     100m (0%)     0 (0%)      0 (0%)              0 (0%)         62m
  scylla                      sct-cluster-us-east1-b-us-east1-3    15050m (94%)  15 (94%)    124564051584 (99%)  116Gi (99%)    38s
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource                    Requests            Limits
  --------                    --------            ------
  cpu                         15160m (95%)        15 (94%)
  memory                      124564051584 (99%)  116Gi (99%)
  ephemeral-storage           0 (0%)              0 (0%)
  hugepages-1Gi               0 (0%)              0 (0%)
  hugepages-2Mi               0 (0%)              0 (0%)
  attachable-volumes-aws-ebs  0                   0
Events:                       <none>

```

**Comment by dkropachev** [comment]
Loos like there is some issue on EKS API side, not enouth information to investigate it, we need to get API logs off the EKS on the tearDown
