### ISSUE TITLE
Loader setup in GCP fails with: 'sudo yum install -y scylla-tools' No package scylla-tools available.

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#3878]
error:

```
2021-08-11 13:34:00.811: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=ade602b1-c72d-42ee-8e1f-2120d4ba6339, source=LongevityTest.SetUp()
exception=[Node longevity-small-set-1h-gcp-open-loader-node-4d586840-0-1 [35.196.119.240 | 10.142.0.29] (seed: False)] NodeSetupFailed: Encountered a bad command exit code!
Command: 'sudo yum install -y scylla-tools'
Exit code: 1
Stdout:
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
* base: mirror.centos.iad1.serverforge.org
* epel: mirror.vcu.edu
* extras: mirror.ash.fastserv.com
* updates: mirror.nodespace.net
No package scylla-tools available.
Stderr:
Error: Nothing to do
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3460, in node_setup
cl_inst.node_setup(_node, **setup_kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 4534, in node_setup
node.remoter.run('sudo yum install -y {}-tools'.format(node.scylla_pkg()))
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run
result = _run()
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 62, in inner
return func(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run
return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
result = connection.run(**command_kwargs)
File "<decorator-gen-3>", line 2, in run
File "/usr/local/lib/python3.9/site-packages/fabric/connection.py", line 30, in opens
return method(self, *args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/fabric/connection.py", line 721, in run
return self._run(self._remote_runner(), command, **kwargs)
File "/usr/local/lib/python3.9/site-packages/invoke/context.py", line 101, in _run
return runner.run(command, **kwargs)
File "/usr/local/lib/python3.9/site-packages/invoke/runners.py", line 291, in run
return self._run_body(command, **kwargs)
File "/usr/local/lib/python3.9/site-packages/invoke/runners.py", line 442, in _run_body
raise UnexpectedExit(result)
invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!
Command: 'sudo yum install -y scylla-tools'
Exit code: 1
Stdout:
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
* base: mirror.centos.iad1.serverforge.org
* epel: mirror.vcu.edu
* extras: mirror.ash.fastserv.com
* updates: mirror.nodespace.net
No package scylla-tools available.
Stderr:
Error: Nothing to do
```

*Installation details*
Kernel version: `5.8.0-1038-gcp`
Scylla version (or git commit hash): `2021.1.4-0.20210721.6cb3fc153 with build-id fca16a2479fa0f0e8e49791757da28fcb79d5dfa`
Cluster size: 3 nodes (n1-highmem-8)
Scylla running with shards number (live nodes):
   longevity-small-set-1h-gcp-open-db-node-4d586840-1 (35.227.39.17 | 172.31.0.4): 4 shards
   longevity-small-set-1h-gcp-open-db-node-4d586840-2 (35.231.229.123 | 172.31.0.5): 4 shards
   longevity-small-set-1h-gcp-open-db-node-4d586840-3 (34.139.146.154 | 172.31.0.3): 4 shards
OS (RHEL/CentOS/Ubuntu/AWS AMI): `-` (gce-siren: us-east1)

Test: `cloud-longevity-small-data-set-1h-gcp_dbg`
Test name: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):
- scylla_cloud_nemesis_small_set.yaml (Siren repo)
- scylla_cloud.yaml (Siren repo)

**Issue description**

====================================

PUT ISSUE DESCRIPTION HERE

====================================

Restore Monitor Stack command: `$ hydra investigate show-monitor 4d586840-267c-4aab-a03a-b3e0881603da`
Show all stored logs command: `$ hydra investigate show-logs 4d586840-267c-4aab-a03a-b3e0881603da`

Test id: `4d586840-267c-4aab-a03a-b3e0881603da`

Logs:
db-cluster - [https://cloudius-jenkins-test.s3.amazonaws.com/4d586840-267c-4aab-a03a-b3e0881603da/20210811_133518/db-cluster-4d586840.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4d586840-267c-4aab-a03a-b3e0881603da/20210811_133518/db-cluster-4d586840.tar.gz)
loader-set - [https://cloudius-jenkins-test.s3.amazonaws.com/4d586840-267c-4aab-a03a-b3e0881603da/20210811_133518/loader-set-4d586840.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4d586840-267c-4aab-a03a-b3e0881603da/20210811_133518/loader-set-4d586840.tar.gz)
monitor-set - [https://cloudius-jenkins-test.s3.amazonaws.com/4d586840-267c-4aab-a03a-b3e0881603da/20210811_133518/monitor-set-4d586840.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4d586840-267c-4aab-a03a-b3e0881603da/20210811_133518/monitor-set-4d586840.tar.gz)
sct-runner - [https://cloudius-jenkins-test.s3.amazonaws.com/4d586840-267c-4aab-a03a-b3e0881603da/20210811_133518/sct-runner-4d586840.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4d586840-267c-4aab-a03a-b3e0881603da/20210811_133518/sct-runner-4d586840.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/siren-tests/job/longevity-tests/job/cloud-longevity-small-data-set-1h-gcp_dbg/3/)

**Comment by yarongilor** [comment]
logs shows: scylla_repo_loader: ''
should probably be something like: 
scylla_repo_loader: https://s3.amazonaws.com/downloads.scylladb.com/rpm/centos/scylla-4.2.repo

**Comment by yarongilor** [comment]
should be resolved by https://github.com/scylladb/siren-tests/pull/687
