### ISSUE TITLE
siren backend config fails with a non-siren check: '...scylla-manager/noarch/repodata/repomd.xml' is incorrect'

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#3919]
In case of siren backend, SCT currently incorrectly validates scylla manager repos and fails like -
error log:
```
< t:2021-08-26 21:00:05,428 f:decorators.py   l:64   c:sdcm.utils.decorators p:DEBUG > 'get_url_content': failed with 'ValueError("The following repository URL 'http://downloads.scylladb.com/manager/rpm/unstable/centos/master/2021-08-26T17:22:14Z/scylla-manager/noarch/repodata/repomd.xml' is incorrect")', retrying [#9]
< t:2021-08-26 21:00:05,528 f:decorators.py   l:67   c:sdcm.utils.decorators p:ERROR > 'get_url_content': Number of retries exceeded!
< t:2021-08-26 21:00:05,530 f:log.py          l:20   c:sdcm.utils.log       p:ERROR > Uncaught exception < t:2021-08-26 21:00:05,530 f:log.py          l:20   c:sdcm.utils.log       p:ERROR > Uncaught exception
< t:2021-08-26 21:00:05,530 f:log.py          l:20   c:sdcm.utils.log       p:ERROR > Traceback (most recent call last):
< t:2021-08-26 21:00:05,530 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/./sct.py", line 1113, in <module>
< t:2021-08-26 21:00:05,530 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     cli()
< t:2021-08-26 21:00:05,530 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 764, in __call__
< t:2021-08-26 21:00:05,530 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     return self.main(*args, **kwargs)
< t:2021-08-26 21:00:05,530 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 717, in main
< t:2021-08-26 21:00:05,530 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     rv = self.invoke(ctx)
< t:2021-08-26 21:00:05,530 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1137, in invoke
< t:2021-08-26 21:00:05,530 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     return _process_result(sub_ctx.command.invoke(sub_ctx))
< t:2021-08-26 21:00:05,530 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 956, in invoke
< t:2021-08-26 21:00:05,530 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     return ctx.invoke(self.callback, **ctx.params)
< t:2021-08-26 21:00:05,530 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 555, in invoke
< t:2021-08-26 21:00:05,530 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     return callback(*args, **kwargs)
< t:2021-08-26 21:00:05,530 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/./sct.py", line 756, in run_test
< t:2021-08-26 21:00:05,530 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     unittest.main(module=None, argv=['python -m unittest', argv],
< t:2021-08-26 21:00:05,530 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/usr/local/lib/python3.9/unittest/main.py", line 100, in __init__
< t:2021-08-26 21:00:05,530 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     self.parseArgs(argv)
< t:2021-08-26 21:00:05,530 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/usr/local/lib/python3.9/unittest/main.py", line 147, in parseArgs
< t:2021-08-26 21:00:05,530 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     self.createTests()
< t:2021-08-26 21:00:05,530 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/usr/local/lib/python3.9/unittest/main.py", line 158, in createTests
< t:2021-08-26 21:00:05,530 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     self.test = self.testLoader.loadTestsFromNames(self.testNames,
< t:2021-08-26 21:00:05,530 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/usr/local/lib/python3.9/unittest/loader.py", line 220, in loadTestsFromNames
< t:2021-08-26 21:00:05,530 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     suites = [self.loadTestsFromName(name, module) for name in names]
< t:2021-08-26 21:00:05,530 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/usr/local/lib/python3.9/unittest/loader.py", line 220, in <listcomp>
< t:2021-08-26 21:00:05,530 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     suites = [self.loadTestsFromName(name, module) for name in names]
< t:2021-08-26 21:00:05,530 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/usr/local/lib/python3.9/unittest/loader.py", line 198, in loadTestsFromName
< t:2021-08-26 21:00:05,530 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     inst = parent(name)
< t:2021-08-26 21:00:05,530 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 246, in __init__
< t:2021-08-26 21:00:05,530 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     self._init_params()
< t:2021-08-26 21:00:05,530 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 412, in _init_params
< t:2021-08-26 21:00:05,530 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     self.params = init_and_verify_sct_config()
< t:2021-08-26 21:00:05,530 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/sct_config.py", line 1797, in init_and_verify_sct_config
< t:2021-08-26 21:00:05,530 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     sct_config.verify_configuration_urls_validity()
< t:2021-08-26 21:00:05,530 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/sct_config.py", line 1717, in verify_configuration_urls_validity
< t:2021-08-26 21:00:05,530 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     get_branch_version_for_multiple_repositories(urls=(self.get(url) for url in [
< t:2021-08-26 21:00:05,530 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/version_utils.py", line 196, in get_branch_version_for_multiple_repositories
< t:2021-08-26 21:00:05,530 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     threads = ParallelObject(objects=urls, timeout=SCYLLA_URL_RESPONSE_TIMEOUT).run(func=get_branch_version)
< t:2021-08-26 21:00:05,530 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 443, in run
< t:2021-08-26 21:00:05,530 f:log.py          l:20   c:sdcm.utils.log       p:ERROR >     raise ParallelObjectException(results=results)
< t:2021-08-26 21:00:05,530 f:log.py          l:20   c:sdcm.utils.log       p:ERROR > sdcm.utils.common.ParallelObjectException: http://downloads.scylladb.com.s3.amazonaws.com/manager/rpm/unstable/centos/master/latest/scylla-manager.repo: http://downloads.scylladb.com/manager/rpm/unstable/centos/master/2021-08-26T17:22:14Z/scylla-manager/noarch/repodata/repomd.xml: The following repository URL 'http://downloads.scylladb.com/manager/rpm/unstable/centos/master/2021-08-26T17:22:14Z/scylla-manager/noarch/repodata/repomd.xml' is incorrect
```
build url: https://jenkins.scylladb.com/job/siren-tests/job/longevity-tests/job/scylla-cloud-longevity-small-data-set-1h-aws/252/
[sct.log](https://github.com/scylladb/scylla-cluster-tests/files/7072780/sct.log)

**Comment by vponomaryov** [comment]
This bug has been fixed by the following PR: https://github.com/scylladb/scylla-cluster-tests/pull/3916
