### ISSUE TITLE
4.3: GCE artifact test failed to start scylla service 

### ISSUE THREAD

**Issue by yaronkaikov** [scylladb/scylla-cluster-tests#3992]
job https://jenkins.scylladb.com/view/scylla-4.3/job/scylla-4.3/job/artifacts/job/artifacts-gce-image-test/111/console failed to start Scylla (it's the same for couple of last runs) 
```
11:14:45  < t:2021-09-29 08:14:44,702 f:sct_events.py   l:976  c:sdcm.sct_events      p:INFO  > A dependency job for scylla-server.service failed. See 'journalctl -xe' for details.
11:14:46  < t:2021-09-29 08:14:44,702 f:tester.py       l:119  c:sdcm.tester          p:ERROR > Exception in setUp. Will call tearDown < t:2021-09-29 08:14:44,702 f:tester.py       l:119  c:sdcm.tester          p:ERROR > Exception in setUp. Will call tearDown
11:14:46  < t:2021-09-29 08:14:44,702 f:tester.py       l:119  c:sdcm.tester          p:ERROR > Traceback (most recent call last):
11:14:46  < t:2021-09-29 08:14:44,702 f:tester.py       l:119  c:sdcm.tester          p:ERROR >   File "/jenkins/slave/workspace/scylla-4.3/artifacts/artifacts-gce-image-test@2/scylla-cluster-tests/sdcm/tester.py", line 112, in wrapper
11:14:46  < t:2021-09-29 08:14:44,702 f:tester.py       l:119  c:sdcm.tester          p:ERROR >     return method(*args, **kwargs)
11:14:46  < t:2021-09-29 08:14:44,702 f:tester.py       l:119  c:sdcm.tester          p:ERROR >   File "/jenkins/slave/workspace/scylla-4.3/artifacts/artifacts-gce-image-test@2/scylla-cluster-tests/sdcm/utils/decorators.py", line 109, in inner
11:14:46  < t:2021-09-29 08:14:44,702 f:tester.py       l:119  c:sdcm.tester          p:ERROR >     res = func(*args, **kwargs)
11:14:46  < t:2021-09-29 08:14:44,702 f:tester.py       l:119  c:sdcm.tester          p:ERROR >   File "/jenkins/slave/workspace/scylla-4.3/artifacts/artifacts-gce-image-test@2/scylla-cluster-tests/sdcm/tester.py", line 415, in setUp
11:14:46  < t:2021-09-29 08:14:44,702 f:tester.py       l:119  c:sdcm.tester          p:ERROR >     self.init_nodes(db_cluster=self.db_cluster)
11:14:46  < t:2021-09-29 08:14:44,702 f:tester.py       l:119  c:sdcm.tester          p:ERROR >   File "/jenkins/slave/workspace/scylla-4.3/artifacts/artifacts-gce-image-test@2/scylla-cluster-tests/sdcm/tester.py", line 361, in init_nodes
11:14:46  < t:2021-09-29 08:14:44,702 f:tester.py       l:119  c:sdcm.tester          p:ERROR >     db_cluster.wait_for_init(node_list=db_cluster.nodes)
11:14:46  < t:2021-09-29 08:14:44,702 f:tester.py       l:119  c:sdcm.tester          p:ERROR >   File "/jenkins/slave/workspace/scylla-4.3/artifacts/artifacts-gce-image-test@2/scylla-cluster-tests/sdcm/cluster.py", line 3184, in wrapper
11:14:46  < t:2021-09-29 08:14:44,702 f:tester.py       l:119  c:sdcm.tester          p:ERROR >     verify_node_setup(start_time)
11:14:46  < t:2021-09-29 08:14:44,702 f:tester.py       l:119  c:sdcm.tester          p:ERROR >   File "/jenkins/slave/workspace/scylla-4.3/artifacts/artifacts-gce-image-test@2/scylla-cluster-tests/sdcm/cluster.py", line 3163, in verify_node_setup
11:14:46  < t:2021-09-29 08:14:44,702 f:tester.py       l:119  c:sdcm.tester          p:ERROR >     raise NodeSetupFailed(node=node, error_msg=setup_exception[0], traceback_str=setup_exception[1])
11:14:46  < t:2021-09-29 08:14:44,702 f:tester.py       l:119  c:sdcm.tester          p:ERROR > sdcm.cluster.NodeSetupFailed: [Node artifacts-gce-image-jenkins-db-node-ca4eb393-0-1 [34.139.222.190 | 10.142.0.130] (seed: True)] NodeSetupFailed: Encountered a bad command exit code!
11:14:46  < t:2021-09-29 08:14:44,702 f:tester.py       l:119  c:sdcm.tester          p:ERROR > 
11:14:46  < t:2021-09-29 08:14:44,702 f:tester.py       l:119  c:sdcm.tester          p:ERROR > Command: 'sudo systemctl start scylla-server.service'
```

This is blocking us from starting 4.3 release as next-machine-image can't pass

**Comment by yaronkaikov** [comment]
I have created instance with the same type as the artifct test from same image source and Scylla is up and running

**Comment by yaronkaikov** [comment]
```
[yaronkaikov@artifacts-gce-image-jenkins-db-node-61d40c44-0-1 ~]$ sudo systemctl status scylla-image-setup
● scylla-image-setup.service - Scylla Cloud Image Setup service
   Loaded: loaded (/usr/lib/systemd/system/scylla-image-setup.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2021-10-06 05:47:58 UTC; 3min 19s ago
  Process: 6907 ExecStart=/opt/scylladb/scylla-machine-image/scylla_image_setup (code=exited, status=1/FAILURE)
 Main PID: 6907 (code=exited, status=1/FAILURE)

Oct 06 05:47:58 artifacts-gce-image-jenkins-db-node-61d40c44-0-1 scylla_image_setup[6907]:   File "/opt/scylladb/scylla-machine-image/libexec/scylla_image_setup", line 27, in <module>
Oct 06 05:47:58 artifacts-gce-image-jenkins-db-node-61d40c44-0-1 scylla_image_setup[6907]:     run('/opt/scylladb/scripts/scylla_sysconfig_setup --nic eth0 --setup-nic --ami')
Oct 06 05:47:58 artifacts-gce-image-jenkins-db-node-61d40c44-0-1 scylla_image_setup[6907]:   File "/opt/scylladb/scripts/scylla_util.py", line 513, in run
Oct 06 05:47:58 artifacts-gce-image-jenkins-db-node-61d40c44-0-1 scylla_image_setup[6907]:     return subprocess.run(cmd, stdout=stdout, stderr=stderr, shell=shell, check=exception, env=scylla_env).returnco>
Oct 06 05:47:58 artifacts-gce-image-jenkins-db-node-61d40c44-0-1 scylla_image_setup[6907]:   File "/opt/scylladb/python3/lib64/python3.8/subprocess.py", line 512, in run
Oct 06 05:47:58 artifacts-gce-image-jenkins-db-node-61d40c44-0-1 scylla_image_setup[6907]:     raise CalledProcessError(retcode, process.args,
Oct 06 05:47:58 artifacts-gce-image-jenkins-db-node-61d40c44-0-1 scylla_image_setup[6907]: subprocess.CalledProcessError: Command '['/opt/scylladb/scripts/scylla_sysconfig_setup', '--nic', 'eth0', '--setup->
Oct 06 05:47:58 artifacts-gce-image-jenkins-db-node-61d40c44-0-1 systemd[1]: scylla-image-setup.service: Main process exited, code=exited, status=1/FAILURE
Oct 06 05:47:58 artifacts-gce-image-jenkins-db-node-61d40c44-0-1 systemd[1]: scylla-image-setup.service: Failed with result 'exit-code'.
Oct 06 05:47:58 artifacts-gce-image-jenkins-db-node-61d40c44-0-1 systemd[1]: Failed to start Scylla Cloud Image Setup service.```

@syuu1228 Can you please assist?

**Comment by syuu1228** [comment]
How do I able to reproduce the error locally?

I tried to run target image (scylla-4-3-7-build-2021-09-29t07-51-10 on scylla-images) but my account does not have permission to run it:
```
Required 'compute.images.useReadOnly' permission for 'projects/scylla-images/global/images/scylla-4-3-7-build-2021-09-29t07-51-10'
```

So I generated GCE image with same unstable rpm repo, but generated GCE image able to start scylla finely, no error occurred.

**Comment by yaronkaikov** [comment]
@syuu1228 You can log into google cloud web console and then under scylla project look for `artifacts-gce-image-jenkins-db-node-61d40c44-0-1` instance (it;s up and running) and you can ssh from there
