### ISSUE TITLE
rolling upgrade tests are failing with "No results from Prometheus"

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla-cluster-tests#4068]
Trace:

```
14:09:08  2021-10-10 11:04:58.325: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=872d3bf0-8f2f-4b23-8393-a8164971d18a, source=UpgradeTest.test_rolling_upgrade (upgrade_test.UpgradeTest)() message=Traceback (most recent call last):
14:09:08  File "/home/ubuntu/scylla-cluster-tests/upgrade_test.py", line 502, in test_rolling_upgrade
14:09:08  self.metric_has_data(
14:09:08  File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 2674, in metric_has_data
14:09:08  is_metric_has_data()
14:09:08  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 62, in inner
14:09:08  return func(*args, **kwargs)
14:09:08  File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 2670, in is_metric_has_data
14:09:08  assert results, "No results from Prometheus"
14:09:08  AssertionError: No results from Prometheus
```

### Logs
* test_id: cae5cc83-4d10-499a-8210-f84ddc6c6d60 
* run: https://jenkins.scylladb.com/view/master/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-ubuntu16.04-test/139
* job log: https://cloudius-jenkins-test.s3.amazonaws.com/cae5cc83-4d10-499a-8210-f84ddc6c6d60/20211010_110937/sct-runner-cae5cc83.tar.gz

**Comment by roydahan** [comment]
@dkropachev what's the root cause of it?
Did it happen on this week runs as well?

**Comment by fgelcer** [comment]
on this run where you reported this issue i see:
```
11:54:41  < t:2021-10-10 09:54:40,306 f:base.py         l:202  c:sdcm.sct_events.base p:ERROR > Traceback (most recent call last):
11:54:41  < t:2021-10-10 09:54:40,306 f:base.py         l:202  c:sdcm.sct_events.base p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/sct_events/base.py", line 200, in publish_or_dump
11:54:41  < t:2021-10-10 09:54:40,306 f:base.py         l:202  c:sdcm.sct_events.base p:ERROR >     proc = get_events_main_device(_registry=self._events_processes_registry)
11:54:41  < t:2021-10-10 09:54:40,306 f:base.py         l:202  c:sdcm.sct_events.base p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/sct_events/events_processes.py", line 182, in get_events_process
11:54:41  < t:2021-10-10 09:54:40,306 f:base.py         l:202  c:sdcm.sct_events.base p:ERROR >     return get_default_events_process_registry(_registry=_registry).get_events_process(name=name)
11:54:41  < t:2021-10-10 09:54:40,306 f:base.py         l:202  c:sdcm.sct_events.base p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/sct_events/events_processes.py", line 173, in get_default_events_process_registry
11:54:41  < t:2021-10-10 09:54:40,306 f:base.py         l:202  c:sdcm.sct_events.base p:ERROR >     raise RuntimeError("You should create default EventsProcessRegistry first")
11:54:41  < t:2021-10-10 09:54:40,306 f:base.py         l:202  c:sdcm.sct_events.base p:ERROR > RuntimeError: You should create default EventsProcessRegistry first
11:54:41  < t:2021-10-10 09:54:40,307 f:base.py         l:211  c:sdcm.utils.version_utils p:ERROR > (ScyllaRepoEvent Severity.WARNING) period_type=one-time event_id=34cbb357-cb37-4d85-b623-20e6b64953e3: url=http://downloads.scylladb.com.s3.amazonaws.com/unstable/scylla/master/deb/unified/latest/scylladb-master/scylla.list error=There is no a sibling directory which contains same repo file (ETag="33a84793c13bb4aeb80be4f4d8e86fe3")
11:54:41  < t:2021-10-10 09:54:40,308 f:version_utils.py l:316  c:sdcm.utils.version_utils p:INFO  > There is no a sibling directory which contains same repo file, use URL http://downloads.scylladb.com.s3.amazonaws.com/unstable/scylla/master/deb/unified/latest/scylladb-master/scylla.list as is
```

and then:
```
13:04:59  < t:2021-10-10 11:04:49,758 f:base.py         l:146  c:RemoteCmdRunner      p:ERROR > Error executing command: "echo TAG: loader_idx:0-cpu_idx:0-keyspace_idx:1; STRESS_TEST_MARKER=PLFPELTA9A00DF9Y1SV8; cassandra-stress write no-warmup cl=QUORUM n=20100200 -schema 'keyspace=keyspace_entire_test replication(factor=3) compression=LZ4Compressor compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native compression=lz4  user=cassandra password=cassandra -rate threads=100 -pop seq=1..20100200 -log interval=5 -node 10.142.0.244 -errors skip-unsupported-columns"; Exit status: -1
13:04:59  < t:2021-10-10 11:04:49,761 f:file_logger.py  l:83   c:sdcm.sct_events.file_logger p:INFO  > 2021-10-10 11:04:49.759: (CassandraStressEvent Severity.CRITICAL) period_type=end event_id=35188b03-a11a-41f1-af3b-291a1b52224c duration=9m59s: node=Node rolling-upgrade-master-ubuntu-xenia-loader-node-cae5cc83-0-1 [34.138.243.213 | 10.142.1.25] (seed: False)
13:04:59  < t:2021-10-10 11:04:49,761 f:file_logger.py  l:83   c:sdcm.sct_events.file_logger p:INFO  > stress_cmd=cassandra-stress write no-warmup cl=QUORUM n=20100200 -schema 'keyspace=keyspace_entire_test replication(factor=3) compression=LZ4Compressor compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native compression=lz4 -rate threads=100 -pop seq=1..20100200 -log interval=5
13:04:59  < t:2021-10-10 11:04:49,761 f:file_logger.py  l:83   c:sdcm.sct_events.file_logger p:INFO  > errors:
13:04:59  < t:2021-10-10 11:04:49,761 f:file_logger.py  l:83   c:sdcm.sct_events.file_logger p:INFO  > 
13:04:59  < t:2021-10-10 11:04:49,761 f:file_logger.py  l:83   c:sdcm.sct_events.file_logger p:INFO  > Stress command completed with bad status -1: Failed to connect over JMX; not collecting these stats
```
so the error `No results from Prometheus` could be a real error in SCT, but it doesn't seem to fail the test (i saw it happening in the past already)

**Comment by roydahan** [comment]
@dkropachev did you  get to the  bottom of this one?
the rolling upgrades are still failing.

**Comment by dkropachev** [comment]
No information yet, it is definitely SCT issue, but I could not find source of it right away.
Do I need to raise priority for the issue ?

**Comment by roydahan** [comment]
Please do.

**Comment by dkropachev** [comment]
Fixed at https://github.com/scylladb/scylla-cluster-tests/issues/4068

**Comment by dkropachev** [comment]
Fixed at https://github.com/scylladb/scylla-cluster-tests/pull/4115
