### ISSUE TITLE
install_awscli_dependencies is not suited for ubuntu distro

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla-cluster-tests#4096]
As result manager test can fail with :

```
02:21:28  ----- LAST ERROR EVENT -------------------------------------------------------
02:21:28  2021-11-05 23:21:20.068: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=87bf083f-1778-4895-9bd5-d249413f5734, source=MgmtCliTest.test_manager_sanity (mgmt_cli_test.MgmtCliTest) [Basic Backup Test]() message=Traceback (most recent call last):
02:21:28  File "/home/ubuntu/scylla-cluster-tests/mgmt_cli_test.py", line 352, in test_manager_sanity
02:21:28  self.test_basic_backup()
02:21:28  File "/home/ubuntu/scylla-cluster-tests/mgmt_cli_test.py", line 478, in test_basic_backup
02:21:28  self.verify_backup_success(mgr_cluster=mgr_cluster, backup_task=backup_task)
02:21:28  File "/home/ubuntu/scylla-cluster-tests/mgmt_cli_test.py", line 164, in verify_backup_success
02:21:28  self.restore_backup_from_backup_task(mgr_cluster=mgr_cluster, backup_task=backup_task,
02:21:28  File "/home/ubuntu/scylla-cluster-tests/mgmt_cli_test.py", line 151, in restore_backup_from_backup_task
02:21:28  self.restore_backup(mgr_cluster=mgr_cluster, snapshot_tag=snapshot_tag,
02:21:28  File "/home/ubuntu/scylla-cluster-tests/mgmt_cli_test.py", line 145, in restore_backup
02:21:28  download(node=node, source=file_path, destination=table_upload_path)
02:21:28  File "/home/ubuntu/scylla-cluster-tests/mgmt_cli_test.py", line 91, in download_from_s3
02:21:28  node.remoter.sudo(f"aws s3 cp '{source}' '{destination}'")
02:21:28  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/base.py", line 123, in sudo
02:21:28  return self.run(cmd=cmd,
02:21:28  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run
02:21:28  result = _run()
02:21:28  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 64, in inner
02:21:28  return func(*args, **kwargs)
02:21:28  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run
02:21:28  return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
02:21:28  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
02:21:28  result = connection.run(**command_kwargs)
02:21:28  File "<decorator-gen-3>", line 2, in run
02:21:28  File "/usr/local/lib/python3.10/site-packages/fabric/connection.py", line 30, in opens
02:21:28  return method(self, *args, **kwargs)
02:21:28  File "/usr/local/lib/python3.10/site-packages/fabric/connection.py", line 723, in run
02:21:28  return self._run(self._remote_runner(), command, **kwargs)
02:21:28  File "/usr/local/lib/python3.10/site-packages/invoke/context.py", line 102, in _run
02:21:28  return runner.run(command, **kwargs)
02:21:28  File "/usr/local/lib/python3.10/site-packages/invoke/runners.py", line 380, in run
02:21:28  return self._run_body(command, **kwargs)
02:21:28  File "/usr/local/lib/python3.10/site-packages/invoke/runners.py", line 442, in _run_body
02:21:28  return self.make_promise() if self._asynchronous else self._finish()
02:21:28  File "/usr/local/lib/python3.10/site-packages/invoke/runners.py", line 509, in _finish
02:21:28  raise UnexpectedExit(result)
02:21:28  invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!
02:21:28  Command: "sudo aws s3 cp 's3://manager-backup-tests-us-east-1/backup/sst/cluster/db8cbf90-81fb-4d66-b054-e4c71f116095/dc/us-eastscylla_node_east/node/00114660-be6c-4c19-b0ba-70b4cee4f2b7/keyspace/keyspace1/table/standard1/a49439803e8611ec8442288ae797970f/md-6-big-CRC.db' '/var/lib/scylla/data/keyspace1/standard1-a49439803e8611ec8442288ae797970f/upload'"
02:21:28  Exit code: 1
02:21:28  Stdout:
02:21:28  Stderr:
02:21:28  sudo: aws: command not found
```

**Comment by dkropachev** [comment]
fixed in #4097
