### ISSUE TITLE
Failure saving logs to argus running with K8S backends

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-cluster-tests#4111]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: [branch or hash tag you are working on]
* **scylla**: [branch or commit hash]

### Logs
* test_id: 3910ec25-6a17-4f55-88aa-58c6c9a69637
* job log: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/valerii/job/vp-functional-k8s-local-kind-aws/83

### Description

Running SCT with latest master I get following error on the "collect logs" stage:

```
Initializing TestRun table...                                                                       
Downgrading core protocol version from 66 to 65 for 13.49.166.9:9042. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
Downgrading core protocol version from 65 to 4 for 13.49.166.9:9042. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
New Cassandra host <Host: 10.0.1.247:9042 eu-north> discovered                                         
New Cassandra host <Host: 10.0.2.153:9042 eu-north> discovered                                         
Cassandra host 13.51.52.79:9042 removed                                                                
Cassandra host 13.53.252.230:9042 removed                                                              
Dumping full schema...                                                                                 
Error saving logs to argus                                                                             
Traceback (most recent call last):                                                                     
  File "/home/ubuntu/scylla-cluster-tests/./sct.py", line 989, in store_logs_in_argus                  
    test_run = ArgusTestRun.get(test_id=test_id)                                                       
  File "/home/ubuntu/scylla-cluster-tests/sdcm/argus_test_run.py", line 247, in get                    
    cls.TESTRUN_INSTANCE = TestRunWithHeartbeat.from_id(test_id, config=cls.CONFIG)                    
  File "/home/ubuntu/scylla-cluster-tests/src/argus/argus/db/testrun.py", line 399, in from_id         
    return cls.from_db_row(row)                                                                        
  File "/home/ubuntu/scylla-cluster-tests/src/argus/argus/db/testrun.py", line 385, in from_db_row  
    nested_fields[field.name] = field.type.from_db_row(row)                                            
  File "/home/ubuntu/scylla-cluster-tests/src/argus/argus/db/testrun.py", line 174, in from_db_row  
    raise NotImplementedError()                                                                        
NotImplementedError
```

It makes job run be marked as "FAILED" which is false negative.

### Steps to Reproduce

1. Run any job with K8S backend
2. Wait till the "collect logs" step is reached
3. See error

**Expected behavior:** If Argus doesn't support saving logs on some backend it must not fail the stage, it must write warning and finish execution.

**Actual behavior:** Argus's exception fails the "collect logs" stage

**Comment by vponomaryov** [comment]
Was fixed here: https://github.com/bentsi/argus/commit/86d87c09
