### ISSUE TITLE
[artifacts-docker-test] failed with error about wrong mediaType on manifest file

### ISSUE THREAD

**Issue by benipeled** [scylladb/scylla-cluster-tests#4181]
The `artifacts-docker-test` on 4.6 failed with the error below. The job run from `branch-4.6`
I'm not sure if it's a wrong image passed to this job or some other wrong param.

```
21:57:06  < t:2021-11-30 19:57:05,565 f:cluster.py      l:3166 c:sdcm.cluster         p:INFO  > <sdcm.cluster_docker.ScyllaDockerCluster object at 0x7f429622b1c0>: Init nodes
21:57:06  < t:2021-11-30 19:57:05,575 f:docker_utils.py l:348  c:sdcm.utils.docker_utils p:INFO  > Build Docker image `scylla-sct:scylla-db-66e6222c'
21:57:07  < t:2021-11-30 19:57:06,919 f:docker_utils.py l:365  c:sdcm.utils.docker_utils p:CRITICAL > Build log:
21:57:07  < t:2021-11-30 19:57:06,919 f:docker_utils.py l:365  c:sdcm.utils.docker_utils p:CRITICAL > Step 1/12 : ARG SOURCE_IMAGE
21:57:07  < t:2021-11-30 19:57:06,919 f:docker_utils.py l:365  c:sdcm.utils.docker_utils p:CRITICAL > 
21:57:07  < t:2021-11-30 19:57:06,919 f:docker_utils.py l:365  c:sdcm.utils.docker_utils p:CRITICAL > 
21:57:07  < t:2021-11-30 19:57:06,919 f:docker_utils.py l:365  c:sdcm.utils.docker_utils p:CRITICAL > Step 2/12 : FROM ${SOURCE_IMAGE}
21:57:07  < t:2021-11-30 19:57:06,919 f:docker_utils.py l:365  c:sdcm.utils.docker_utils p:CRITICAL > 
21:57:07  < t:2021-11-30 19:57:06,922 f:file_logger.py  l:85   c:sdcm.sct_events.file_logger p:INFO  > 2021-11-30 19:57:06.920: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=30d13063-4318-4f43-8a28-c52344cf2dc2, source=ArtifactsTest.SetUp()
21:57:07  < t:2021-11-30 19:57:06,922 f:file_logger.py  l:85   c:sdcm.sct_events.file_logger p:INFO  > exception=mediaType in manifest should be 'application/vnd.docker.distribution.manifest.v2+json' not ''
21:57:07  < t:2021-11-30 19:57:06,920 f:tester.py       l:139  c:sdcm.tester          p:ERROR > Exception in setUp. Will call tearDown < t:2021-11-30 19:57:06,920 f:tester.py       l:139  c:sdcm.tester          p:ERROR > Exception in setUp. Will call tearDown
21:57:07  < t:2021-11-30 19:57:06,920 f:tester.py       l:139  c:sdcm.tester          p:ERROR > Traceback (most recent call last):
21:57:07  < t:2021-11-30 19:57:06,920 f:tester.py       l:139  c:sdcm.tester          p:ERROR >   File "/home/jenkins/slave/workspace/scylla-4.6/artifacts/artifacts-docker-test/scylla-cluster-tests/sdcm/tester.py", line 132, in wrapper
21:57:07  < t:2021-11-30 19:57:06,920 f:tester.py       l:139  c:sdcm.tester          p:ERROR >     return method(*args, **kwargs)
21:57:07  < t:2021-11-30 19:57:06,920 f:tester.py       l:139  c:sdcm.tester          p:ERROR >   File "/home/jenkins/slave/workspace/scylla-4.6/artifacts/artifacts-docker-test/scylla-cluster-tests/sdcm/utils/decorators.py", line 113, in inner
21:57:07  < t:2021-11-30 19:57:06,920 f:tester.py       l:139  c:sdcm.tester          p:ERROR >     res = func(*args, **kwargs)
21:57:07  < t:2021-11-30 19:57:06,920 f:tester.py       l:139  c:sdcm.tester          p:ERROR >   File "/home/jenkins/slave/workspace/scylla-4.6/artifacts/artifacts-docker-test/scylla-cluster-tests/sdcm/tester.py", line 606, in setUp
21:57:07  < t:2021-11-30 19:57:06,920 f:tester.py       l:139  c:sdcm.tester          p:ERROR >     self.init_resources()
21:57:07  < t:2021-11-30 19:57:06,920 f:tester.py       l:139  c:sdcm.tester          p:ERROR >   File "/home/jenkins/slave/workspace/scylla-4.6/artifacts/artifacts-docker-test/scylla-cluster-tests/sdcm/tester.py", line 1340, in init_resources
21:57:07  < t:2021-11-30 19:57:06,920 f:tester.py       l:139  c:sdcm.tester          p:ERROR >     self.get_cluster_docker()
21:57:07  < t:2021-11-30 19:57:06,920 f:tester.py       l:139  c:sdcm.tester          p:ERROR >   File "/home/jenkins/slave/workspace/scylla-4.6/artifacts/artifacts-docker-test/scylla-cluster-tests/sdcm/tester.py", line 975, in get_cluster_docker
21:57:07  < t:2021-11-30 19:57:06,920 f:tester.py       l:139  c:sdcm.tester          p:ERROR >     self.db_cluster = cluster_docker.ScyllaDockerCluster(n_nodes=[self.params.get("n_db_nodes"), ],
21:57:07  < t:2021-11-30 19:57:06,920 f:tester.py       l:139  c:sdcm.tester          p:ERROR >   File "/home/jenkins/slave/workspace/scylla-4.6/artifacts/artifacts-docker-test/scylla-cluster-tests/sdcm/cluster_docker.py", line 255, in __init__
21:57:07  < t:2021-11-30 19:57:06,920 f:tester.py       l:139  c:sdcm.tester          p:ERROR >     super().__init__(docker_image=docker_image,
21:57:07  < t:2021-11-30 19:57:06,920 f:tester.py       l:139  c:sdcm.tester          p:ERROR >   File "/home/jenkins/slave/workspace/scylla-4.6/artifacts/artifacts-docker-test/scylla-cluster-tests/sdcm/cluster.py", line 3667, in __init__
21:57:07  < t:2021-11-30 19:57:06,920 f:tester.py       l:139  c:sdcm.tester          p:ERROR >     super().__init__(*args, **kwargs)
21:57:07  < t:2021-11-30 19:57:06,920 f:tester.py       l:139  c:sdcm.tester          p:ERROR >   File "/home/jenkins/slave/workspace/scylla-4.6/artifacts/artifacts-docker-test/scylla-cluster-tests/sdcm/cluster_docker.py", line 187, in __init__
21:57:07  < t:2021-11-30 19:57:06,920 f:tester.py       l:139  c:sdcm.tester          p:ERROR >     super().__init__(cluster_prefix=cluster_prefix,
21:57:07  < t:2021-11-30 19:57:06,920 f:tester.py       l:139  c:sdcm.tester          p:ERROR >   File "/home/jenkins/slave/workspace/scylla-4.6/artifacts/artifacts-docker-test/scylla-cluster-tests/sdcm/cluster.py", line 3184, in __init__
21:57:07  < t:2021-11-30 19:57:06,920 f:tester.py       l:139  c:sdcm.tester          p:ERROR >     self.add_nodes(num, dc_idx=dc_idx, enable_auto_bootstrap=self.auto_bootstrap)
21:57:07  < t:2021-11-30 19:57:06,920 f:tester.py       l:139  c:sdcm.tester          p:ERROR >   File "/home/jenkins/slave/workspace/scylla-4.6/artifacts/artifacts-docker-test/scylla-cluster-tests/sdcm/cluster_docker.py", line 242, in add_nodes
21:57:07  < t:2021-11-30 19:57:06,920 f:tester.py       l:139  c:sdcm.tester          p:ERROR >     return self._get_nodes() if self.test_config.REUSE_CLUSTER else self._create_nodes(count, enable_auto_bootstrap)
21:57:07  < t:2021-11-30 19:57:06,920 f:tester.py       l:139  c:sdcm.tester          p:ERROR >   File "/home/jenkins/slave/workspace/scylla-4.6/artifacts/artifacts-docker-test/scylla-cluster-tests/sdcm/cluster_docker.py", line 227, in _create_nodes
21:57:07  < t:2021-11-30 19:57:06,920 f:tester.py       l:139  c:sdcm.tester          p:ERROR >     node = self._create_node(node_index)
21:57:07  < t:2021-11-30 19:57:06,920 f:tester.py       l:139  c:sdcm.tester          p:ERROR >   File "/home/jenkins/slave/workspace/scylla-4.6/artifacts/artifacts-docker-test/scylla-cluster-tests/sdcm/cluster_docker.py", line 209, in _create_node
21:57:07  < t:2021-11-30 19:57:06,920 f:tester.py       l:139  c:sdcm.tester          p:ERROR >     ContainerManager.build_container_image(node, "node")
21:57:07  < t:2021-11-30 19:57:06,920 f:tester.py       l:139  c:sdcm.tester          p:ERROR >   File "/home/jenkins/slave/workspace/scylla-4.6/artifacts/artifacts-docker-test/scylla-cluster-tests/sdcm/utils/docker_utils.py", line 363, in build_container_image
21:57:07  < t:2021-11-30 19:57:06,920 f:tester.py       l:139  c:sdcm.tester          p:ERROR >     image, logs = docker_client.images.build(tag=image_tag, **dockerfile_args, **build_args)
21:57:07  < t:2021-11-30 19:57:06,920 f:tester.py       l:139  c:sdcm.tester          p:ERROR >   File "/usr/local/lib/python3.10/site-packages/docker/models/images.py", line 287, in build
21:57:07  < t:2021-11-30 19:57:06,920 f:tester.py       l:139  c:sdcm.tester          p:ERROR >     raise BuildError(chunk['error'], result_stream)
21:57:07  < t:2021-11-30 19:57:06,920 f:tester.py       l:139  c:sdcm.tester          p:ERROR > docker.errors.BuildError: mediaType in manifest should be 'application/vnd.docker.distribution.manifest.v2+json' not ''
21:57:07  E
21:57:07  ======================================================================
21:57:07  ERROR: test_scylla_service (artifacts_test.ArtifactsTest)
21:57:07  ----------------------------------------------------------------------
```

**Comment by roydahan** [comment]
@benipeled It looks like the problem is with the  docker itself, isn't it?

**Comment by roydahan** [comment]
@bentsi do you know what is the issue here?

**Comment by benipeled** [comment]
It might be caused by an empty/wrong `SOURCE_IMAGE` variable required at the beginning of the build `scylla-sct:scylla-db-0f473d18` stage - WDYT?


```
10:33:48  < t:2021-12-01 08:33:48,770 f:docker_utils.py l:348  c:sdcm.utils.docker_utils p:INFO  > Build Docker image `scylla-sct:scylla-db-0f473d18'
10:33:51  < t:2021-12-01 08:33:50,188 f:docker_utils.py l:365  c:sdcm.utils.docker_utils p:CRITICAL > Build log:
10:33:51  < t:2021-12-01 08:33:50,188 f:docker_utils.py l:365  c:sdcm.utils.docker_utils p:CRITICAL > Step 1/12 : ARG SOURCE_IMAGE
10:33:51  < t:2021-12-01 08:33:50,188 f:docker_utils.py l:365  c:sdcm.utils.docker_utils p:CRITICAL > 
10:33:51  < t:2021-12-01 08:33:50,188 f:docker_utils.py l:365  c:sdcm.utils.docker_utils p:CRITICAL > 
10:33:51  < t:2021-12-01 08:33:50,188 f:docker_utils.py l:365  c:sdcm.utils.docker_utils p:CRITICAL > Step 2/12 : FROM ${SOURCE_IMAGE}
10:33:51  < t:2021-12-01 08:33:50,188 f:docker_utils.py l:365  c:sdcm.utils.docker_utils p:CRITICAL > 
10:33:51  < t:2021-12-01 08:33:50,190 f:file_logger.py  l:85   c:sdcm.sct_events.file_logger p:INFO  > 2021-12-01 08:33:50.189: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=bc37f7df-9e91-4072-a43d-a36a14f31f6d, source=ArtifactsTest.SetUp()
10:33:51  < t:2021-12-01 08:33:50,190 f:file_logger.py  l:85   c:sdcm.sct_events.file_logger p:INFO  > exception=mediaType in manifest should be 'application/vnd.docker.distribution.manifest.v2+json' not ''
10:33:51  < t:2021-12-01 08:33:50,189 f:tester.py       l:139  c:sdcm.tester          p:ERROR > Exception in setUp. Will call tearDown < t:2021-12-01 08:33:50,189 f:tester.py       l:139  c:sdcm.tester          p:ERROR > Exception in setUp. Will call tearDown
```

**Comment by fruch** [comment]
those are caused cause of an old docker runtime being used.
I think we've updated all the builder already
