### ISSUE TITLE
scylla-driver in branch manager-2.6 seem to be out of date

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla-cluster-tests#4189]
on 01/12 the following error appeared in 4 different manager jobs:
```
2021-12-01 13:28:06.209: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=902ae960-d439-480c-b581-fe4ce6ffccbc, source=ManagerUpgradeTest.test_upgrade (mgmt_upgrade_test.ManagerUpgradeTest) [Restoring an older version backup task with newer version manager]() message=Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/mgmt_upgrade_test.py", line 139, in test_upgrade
    self.verify_backup_success(mgr_cluster=mgr_cluster, backup_task=backup_task)
  File "/home/ubuntu/scylla-cluster-tests/mgmt_cli_test.py", line 178, in verify_backup_success
    self.restore_backup_from_backup_task(mgr_cluster=mgr_cluster, backup_task=backup_task,
  File "/home/ubuntu/scylla-cluster-tests/mgmt_cli_test.py", line 165, in restore_backup_from_backup_task
    self.restore_backup(mgr_cluster=mgr_cluster, snapshot_tag=snapshot_tag,
  File "/home/ubuntu/scylla-cluster-tests/mgmt_cli_test.py", line 156, in restore_backup
    table_id = self.get_table_id(node=node, table_name=table, keyspace_name=keyspace)
  File "/home/ubuntu/scylla-cluster-tests/mgmt_cli_test.py", line 128, in get_table_id
    results = session.execute(query)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 1238, in __exit__
    self.cluster.shutdown()
  File "cassandra/cluster.py", line 1768, in cassandra.cluster.Cluster.shutdown
  File "cassandra/cluster.py", line 3156, in cassandra.cluster.Session.shutdown
  File "cassandra/pool.py", line 546, in cassandra.pool.HostConnection.shutdown
RuntimeError: dictionary changed size during iteration
```
https://jenkins.scylladb.com/view/scylla-manager/job/manager-2.6/job/debian9-upgrade-test/8/
https://jenkins.scylladb.com/view/scylla-manager/job/manager-2.6/job/ubuntu16-upgrade-test/9/
https://jenkins.scylladb.com/view/scylla-manager/job/manager-2.6/job/ubuntu18-upgrade-test/9/
https://jenkins.scylladb.com/view/scylla-manager/job/manager-2.6/job/ubuntu20-upgrade-test/4/

@dkropachev suggested that bug is caused by an outdated scylla drvier, and that it was already fixed in a newer one.

**Comment by ShlomiBalalis** [comment]
@dkropachev it still occurres in the tests, any news about it?

**Comment by dkropachev** [comment]
@ShlomiBalalis , all crucial patches to the driver where made and now we are working on publishing new version, when it is done we will switch it to 3.24.8
