### ISSUE TITLE
User data for AWS VMs are provided in wrong format and cause incorrect setup of scylla cluster members

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-cluster-tests#4197]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master
* **scylla**: 4.7.dev-0.20211126.44f4ea38c with build-id a88083cca1208179dd36a3847af403f77ad794f0

### Logs
* test_id: e165522a-c0f3-4abe-bb0a-c8234070c5d1
* job log: [[Failed CI job logs]](https://jenkins.scylladb.com/view/master/job/scylla-master/job/gemini-/job/gemini-1tb-10h/132)

### Description

Running Scylla on AWS it fails to apply provided user data because it is base64-encoded. But `scylla-machine-image` tools expect only fileds with scripts to be encoded as base64 string such as "post_configuration_script".

Here is key messages from the DB node 1:
```
2021-12-07T01:30:54+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !    INFO | Scylla version 4.7.dev-0.20211126.44f4ea38c with build-id a88083cca1208179dd36a3847af403f77ad794f0 starting ...
2021-12-07T01:30:54+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !    INFO | command used: "/usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --io-properties-file=/etc/scylla.d/io_properties.yaml --cpuset 1-7,9-15 --lock-memory=1"
...
2021-12-07T01:30:56+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !    INFO |  [shard 0] init - Scylla version 4.7.dev-0.20211126.44f4ea38c with build-id a88083cca1208179dd36a3847af403f77ad794f0 starting ...
...
2021-12-07T01:30:57+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !    INFO | Started Scylla Server.
2021-12-07T01:30:57+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !    INFO | Started Run Scylla Housekeeping daily mode.
2021-12-07T01:30:57+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !    INFO | Started Run Scylla Housekeeping restart mode.
2021-12-07T01:30:57+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !    INFO | Reached target Multi-User System.
2021-12-07T01:30:57+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !    INFO | Reached target Graphical Interface.
2021-12-07T01:30:57+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !    INFO | Reached target Timers.
2021-12-07T01:30:57+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !    INFO | Starting Execute cloud user/final scripts...
2021-12-07T01:30:57+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !    INFO | Starting Scylla cloud image post start service...
2021-12-07T01:30:57+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !    INFO | Started Scylla JMX.
...
2021-12-07T01:31:00+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !    INFO | Started Scylla Housekeeping restart mode.
...
2021-12-07T01:31:02+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !    INFO | Starting the JMX server
2021-12-07T01:31:02+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !    INFO | scylla-housekeeping-restart.service: Succeeded.
...
2021-12-07T01:31:10+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !    INFO |  [shard 0] storage_service - NORMAL: node is now in normal status
...
2021-12-07T01:31:23+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !    INFO |  [shard 0] init - Scylla version 4.7.dev-0.20211126.44f4ea38c initialization completed.
...
2021-12-07T01:31:27+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !    INFO | 2021-12-07 01:31:27,736 - [scylla_post_start] - INFO - Got user-data: eyJjbHVzdGVyX25hbWUiOiAiZ2VtaW5pLTF0Yi0xMGgtbWFzdGVyLWRiLWNsdXN0ZXItZTE2NTUyMmEiLCAiZGF0YV9kZXZpY2UiOiAiaW5zdGFuY2Vfc3RvcmUiLCAicG9zdF9jb25maWd1cmF0aW9uX3NjcmlwdCI6ICJJeUV2WW1sdUwySmhjMmdLQ25ObFpDQXRhU0F0WlNBbmN5OWVYQ3BiV3pwaWJHRnVhenBkWFNwemIyWjBXMXM2WW14aGJtczZYVjBxYm5CeWIyTmJXenBpYkdGdWF6cGRYU28wTURrMkx5b0pDWE52Wm5RSmJuQnliMk1KQ1hWdWJHbHRhWFJsWkM4bklDQWdJQ0FnSUNBZ0wyVjBZeTl6WldOMWNtbDBlUzlzYVcxcGRITXVaQzh5TUMxdWNISnZZeTVqYjI1bUNtVmphRzhnTFdVZ0p5b0pDV2hoY21RSmJuQnliMk1KQ1hWdWJHbHRhWFJsWkNjZ1BqNGdMMlYwWXk5elpXTjFjbWwwZVM5c2FXMXBkSE11WkM4eU1DMXVjSEp2WXk1amIyNW1DZ3B6WldRZ0xXa2dKM012STAxaGVGTmxjM05wYjI1eklGd29MaXBjS1NRdlRXRjRVMlZ6YzJsdmJuTWdNVEF3TUM4bklDOWxkR012YzNOb0wzTnphR1JmWTI5dVptbG5Dbk5sWkNBdGFTQW5jeThqVFdGNFUzUmhjblIxY0hNZ1hDZ3VLbHdwSkM5TllYaFRkR0Z5ZEhWd2N5QTJNQzhuSUM5bGRHTXZjM05vTDNOemFHUmZZMjl1Wm1sbkNuTmxaQ0F0YVNBbmN5OGpURzluYVc1SGNtRmpaVlJwYldVZ1hDZ3VLbHdwSkM5TWIyZHBia2R5WVdObFZHbHRaU0F4TlhNdkp5QXZaWFJqTDNOemFDOXpjMmhrWDJOdmJtWnBad3B6ZVhOMFpXMWpkR3dnY21WemRHRnlkQ0J6YzJoa0NnPT0iLCAic2N5bGxhX3lhbWwiOiB7ImNsdXN0ZXJfbmFtZSI6ICJnZW1pbmktMXRiLTEwaC1tYXN0ZXItZGItY2x1c3Rlci1lMTY1NTIyYSJ9LCAic3RhcnRfc2N5bGxhX29uX2ZpcnN0X2Jvb3QiOiBmYWxzZX0=
2021-12-07T01:31:27+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !    INFO | Got user-data: eyJjbHVzdGVyX25hbWUiOiAiZ2VtaW5pLTF0Yi0xMGgtbWFzdGVyLWRiLWNsdXN0ZXItZTE2NTUyMmEiLCAiZGF0YV9kZXZpY2UiOiAiaW5zdGFuY2Vfc3RvcmUiLCAicG9zdF9jb25maWd1cmF0aW9uX3NjcmlwdCI6ICJJeUV2WW1sdUwySmhjMmdLQ25ObFpDQXRhU0F0WlNBbmN5OWVYQ3BiV3pwaWJHRnVhenBkWFNwemIyWjBXMXM2WW14aGJtczZYVjBxYm5CeWIyTmJXenBpYkdGdWF6cGRYU28wTURrMkx5b0pDWE52Wm5RSmJuQnliMk1KQ1hWdWJHbHRhWFJsWkM4bklDQWdJQ0FnSUNBZ0wyVjBZeTl6WldOMWNtbDBlUzlzYVcxcGRITXVaQzh5TUMxdWNISnZZeTVqYjI1bUNtVmphRzhnTFdVZ0p5b0pDV2hoY21RSmJuQnliMk1KQ1hWdWJHbHRhWFJsWkNjZ1BqNGdMMlYwWXk5elpXTjFjbWwwZVM5c2FXMXBkSE11WkM4eU1DMXVjSEp2WXk1amIyNW1DZ3B6WldRZ0xXa2dKM012STAxaGVGTmxjM05wYjI1eklGd29MaXBjS1NRdlRXRjRVMlZ6YzJsdmJuTWdNVEF3TUM4bklDOWxkR012YzNOb0wzTnphR1JmWTI5dVptbG5Dbk5sWkNBdGFTQW5jeThqVFdGNFUzUmhjblIxY0hNZ1hDZ3VLbHdwSkM5TllYaFRkR0Z5ZEhWd2N5QTJNQzhuSUM5bGRHTXZjM05vTDNOemFHUmZZMjl1Wm1sbkNuTmxaQ0F0YVNBbmN5OGpURzluYVc1SGNtRmpaVlJwYldVZ1hDZ3VLbHdwSkM5TWIyZHBia2R5WVdObFZHbHRaU0F4TlhNdkp5QXZaWFJqTDNOemFDOXpjMmhrWDJOdmJtWnBad3B6ZVhOMFpXMWpkR3dnY21WemRHRnlkQ0J6YzJoa0NnPT0iLCAic2N5bGxhX3lhbWwiOiB7ImNsdXN0ZXJfbmFtZSI6ICJnZW1pbmktMXRiLTEwaC1tYXN0ZXItZGItY2x1c3Rlci1lMTY1NTIyYSJ9LCAic3RhcnRfc2N5bGxhX29uX2ZpcnN0X2Jvb3QiOiBmYWxzZX0=
2021-12-07T01:31:27+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !    INFO | 2021-12-07 01:31:27,736 - [scylla_post_start] - WARNING - Error getting user data: Expecting value: line 1 column 1 (char 0)
2021-12-07T01:31:27+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !    INFO | Error getting user data: Expecting value: line 1 column 1 (char 0)
2021-12-07T01:31:27+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !    INFO | Traceback (most recent call last):
2021-12-07T01:31:27+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !    INFO |   File "/opt/scylladb/scylla-machine-image/libexec/scylla_post_start.py", line 71, in <module>
2021-12-07T01:31:27+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !    INFO |     if init.run_post_start_script():
2021-12-07T01:31:27+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !    INFO |   File "/opt/scylladb/scylla-machine-image/libexec/scylla_post_start.py", line 57, in run_post_start_script
2021-12-07T01:31:27+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !    INFO |     post_start_script = self.instance_user_data.get("post_start_script")
2021-12-07T01:31:27+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !    INFO | AttributeError: 'NoneType' object has no attribute 'get'
2021-12-07T01:31:27+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !  NOTICE | scylla-image-post-start.service: Main process exited, code=exited, status=1/FAILURE
2021-12-07T01:31:27+00:00 gemini-1tb-10h-master-db-node-e165522a-1 ! WARNING | scylla-image-post-start.service: Failed with result 'exit-code'.
2021-12-07T01:31:27+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !     ERR | Failed to start Scylla cloud image post start service.
2021-12-07T01:31:27+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !    INFO | Startup finished in 2.884s (kernel) + 2min 56.502s (userspace) = 2min 59.386s.
...
2021-12-07T01:33:45+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !    INFO | scylla-housekeeping-daily.timer: Succeeded.
2021-12-07T01:33:45+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !    INFO | Stopped Run Scylla Housekeeping daily mode.
2021-12-07T01:33:45+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !    INFO | scylla-housekeeping-restart.timer: Succeeded.
2021-12-07T01:33:45+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !    INFO | Stopped Run Scylla Housekeeping restart mode.
2021-12-07T01:33:45+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !    INFO | Stopping Scylla JMX...
2021-12-07T01:33:45+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !  NOTICE | scylla-jmx.service: Main process exited, code=exited, status=143/n/a
2021-12-07T01:33:45+00:00 gemini-1tb-10h-master-db-node-e165522a-1 ! WARNING | scylla-jmx.service: Failed with result 'exit-code'.
2021-12-07T01:33:45+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !    INFO | Stopped Scylla JMX.
2021-12-07T01:33:45+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !    INFO |  [shard 0] compaction_manager - Asked to stop
2021-12-07T01:33:45+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !    INFO |  [shard 0] compaction_manager - Stopping 0 ongoing compactions due to shutdown
2021-12-07T01:33:45+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !    INFO | Stopping Scylla Server...
...

2021-12-07T01:33:48+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !    INFO |  [shard 0] init - Scylla version 4.7.dev-0.20211126.44f4ea38c shutdown complete.
...
2021-12-07T01:34:47+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !  NOTICE | scyllaadm : TTY=unknown ; PWD=/home/scyllaadm ; USER=root ; COMMAND=/usr/bin/systemctl start scylla-server.service
2021-12-07T01:34:47+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !    INFO | pam_unix(sudo:session): session opened for user root by (uid=0)
2021-12-07T01:34:47+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !    INFO | Starting Scylla Server...
...
2021-12-07T01:34:48+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !    INFO | Scylla version 4.7.dev-0.20211126.44f4ea38c with build-id a88083cca1208179dd36a3847af403f77ad794f0 starting ...
2021-12-07T01:34:48+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !    INFO | command used: "/usr/bin/scylla --blocked-reactor-notify-ms 100 --abort-on-lsa-bad-alloc 1 --abort-on-seastar-bad-alloc --abort-on-internal-error 1 --abort-on-ebadf 1 --enable-sstable-key-validation 1 --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --io-properties-file=/etc/scylla.d/io_properties.yaml --cpuset 1-7,9-15 --lock-memory=1"
...
2021-12-07T01:34:50+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !    INFO | Started Scylla Server.
2021-12-07T01:34:50+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !    INFO | Started Run Scylla Housekeeping daily mode.
2021-12-07T01:34:50+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !    INFO | Started Run Scylla Housekeeping restart mode.
2021-12-07T01:34:50+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !    INFO |  [shard 0] init - starting sstables loader
2021-12-07T01:34:50+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !    INFO | Starting Scylla cloud image post start service...
2021-12-07T01:34:50+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !    INFO | pam_unix(sudo:session): session closed for user root
2021-12-07T01:34:50+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !    INFO | Started Scylla JMX.
```

As a result, none of user data changes get applied including `"start_scylla_on_first_boot": false`, by default it is set to be `True`.
So, it makes scylla try to start by default, it fails and starts successfully only from second attempt.
That first failed attempt makes SCT generate following error events that is enough to mark whole test run as "Failed":
```
2021-12-07 01:33:46.255: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=09003ef8-eeae-4f4d-8413-ba9b73f25e2c, source=ScyllaServerStatusEvent message=Did not find any events of type <class 'sdcm.sct_events.database.ScyllaServerStatusEvent'> with period type begin, event data: {}
2021-12-07 01:37:25.845: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=533ecb5a-ea68-4e15-be91-68e46530d7a2, source=JMXServiceEvent message=Did not find any events of type <class 'sdcm.sct_events.database.JMXServiceEvent'> with period type begin, event data: {}
2021-12-07 01:37:26.148: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=796803df-9295-46a7-b18d-19011eb41c00, source=ScyllaServerStatusEvent message=Did not find any events of type <class 'sdcm.sct_events.database.ScyllaServerStatusEvent'> with period type begin, event data: {}
2021-12-07 01:42:00.857: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=e355555c-52a1-4a67-a0d2-727c50f596e0, source=JMXServiceEvent message=Did not find any events of type <class 'sdcm.sct_events.database.JMXServiceEvent'> with period type begin, event data: {}
2021-12-07 01:42:00.859: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=b1d81ad1-703d-4de7-8ebb-bf8dc486f0cc, source=ScyllaServerStatusEvent message=Did not find any events of type <class 'sdcm.sct_events.database.ScyllaServerStatusEvent'> with period type begin, event data: {}
```

`Begin` is considered absent, because `Starting Scylla Server` does not match following real messages in such a case:
```
2021-12-07T01:30:56+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !    INFO |  [shard 0] init - Scylla version 4.7.dev-0.20211126.44f4ea38c with build-id a88083cca1208179dd36a3847af403f77ad794f0 starting ...
...
2021-12-07T01:30:57+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !    INFO | Started Scylla Server.
```

### Steps to Reproduce

1. Run Scylla on AWS
2. Look at DB nodes logs
3. See error

**Expected behavior:** User data should be applied successfully.
Expected user data:
```
{"cluster_name": "gemini-1tb-10h-master-db-cluster-e165522a", "data_device": "instance_store", "post_configuration_script": "IyEvYmluL2Jhc2gKCnNlZCAtaSAtZSAncy9eXCpbWzpibGFuazpdXSpzb2Z0W1s6Ymxhbms6XV0qbnByb2NbWzpibGFuazpdXSo0MDk2LyoJCXNvZnQJbnByb2MJCXVubGltaXRlZC8nICAgICAgICAgL2V0Yy9zZWN1cml0eS9saW1pdHMuZC8yMC1ucHJvYy5jb25mCmVjaG8gLWUgJyoJCWhhcmQJbnByb2MJCXVubGltaXRlZCcgPj4gL2V0Yy9zZWN1cml0eS9saW1pdHMuZC8yMC1ucHJvYy5jb25mCgpzZWQgLWkgJ3MvI01heFNlc3Npb25zIFwoLipcKSQvTWF4U2Vzc2lvbnMgMTAwMC8nIC9ldGMvc3NoL3NzaGRfY29uZmlnCnNlZCAtaSAncy8jTWF4U3RhcnR1cHMgXCguKlwpJC9NYXhTdGFydHVwcyA2MC8nIC9ldGMvc3NoL3NzaGRfY29uZmlnCnNlZCAtaSAncy8jTG9naW5HcmFjZVRpbWUgXCguKlwpJC9Mb2dpbkdyYWNlVGltZSAxNXMvJyAvZXRjL3NzaC9zc2hkX2NvbmZpZwpzeXN0ZW1jdGwgcmVzdGFydCBzc2hkCg==", "scylla_yaml": {"cluster_name": "gemini-1tb-10h-master-db-cluster-e165522a"}, "start_scylla_on_first_boot": false}
```

**Actual behavior:** scylla-machine-image tools fail to parse provided user data. All of it.
Actual user data (base64-encoded):
```
eyJjbHVzdGVyX25hbWUiOiAiZ2VtaW5pLTF0Yi0xMGgtbWFzdGVyLWRiLWNsdXN0ZXItZTE2NTUyMmEiLCAiZGF0YV9kZXZpY2UiOiAiaW5zdGFuY2Vfc3RvcmUiLCAicG9zdF9jb25maWd1cmF0aW9uX3NjcmlwdCI6ICJJeUV2WW1sdUwySmhjMmdLQ25ObFpDQXRhU0F0WlNBbmN5OWVYQ3BiV3pwaWJHRnVhenBkWFNwemIyWjBXMXM2WW14aGJtczZYVjBxYm5CeWIyTmJXenBpYkdGdWF6cGRYU28wTURrMkx5b0pDWE52Wm5RSmJuQnliMk1KQ1hWdWJHbHRhWFJsWkM4bklDQWdJQ0FnSUNBZ0wyVjBZeTl6WldOMWNtbDBlUzlzYVcxcGRITXVaQzh5TUMxdWNISnZZeTVqYjI1bUNtVmphRzhnTFdVZ0p5b0pDV2hoY21RSmJuQnliMk1KQ1hWdWJHbHRhWFJsWkNjZ1BqNGdMMlYwWXk5elpXTjFjbWwwZVM5c2FXMXBkSE11WkM4eU1DMXVjSEp2WXk1amIyNW1DZ3B6WldRZ0xXa2dKM012STAxaGVGTmxjM05wYjI1eklGd29MaXBjS1NRdlRXRjRVMlZ6YzJsdmJuTWdNVEF3TUM4bklDOWxkR012YzNOb0wzTnphR1JmWTI5dVptbG5Dbk5sWkNBdGFTQW5jeThqVFdGNFUzUmhjblIxY0hNZ1hDZ3VLbHdwSkM5TllYaFRkR0Z5ZEhWd2N5QTJNQzhuSUM5bGRHTXZjM05vTDNOemFHUmZZMjl1Wm1sbkNuTmxaQ0F0YVNBbmN5OGpURzluYVc1SGNtRmpaVlJwYldVZ1hDZ3VLbHdwSkM5TWIyZHBia2R5WVdObFZHbHRaU0F4TlhNdkp5QXZaWFJqTDNOemFDOXpjMmhrWDJOdmJtWnBad3B6ZVhOMFpXMWpkR3dnY21WemRHRnlkQ0J6YzJoa0NnPT0iLCAic2N5bGxhX3lhbWwiOiB7ImNsdXN0ZXJfbmFtZSI6ICJnZW1pbmktMXRiLTEwaC1tYXN0ZXItZGItY2x1c3Rlci1lMTY1NTIyYSJ9LCAic3RhcnRfc2N5bGxhX29uX2ZpcnN0X2Jvb3QiOiBmYWxzZX0
```

**Comment by dkropachev** [comment]
It was temporary issue on AWS, if you look at the provision step you will see that we submitted followin user-data:

```
eyJjbHVzdGVyX25hbWUiOiAiZ2VtaW5pLTF0Yi0xMGgtbWFzdGVyLWRiLWNsdXN0ZXItZTE2NTUyMmEiLCAiZGF0YV9kZXZpY2UiOiAiaW5zdGFuY2Vfc3RvcmUiLCAicG9zdF9jb25maWd1cmF0aW9uX3NjcmlwdCI6ICJJeUV2WW1sdUwySmhjMmdLQ25ObFpDQXRhU0F0WlNBbmN5OWVYQ3BiV3pwaWJHRnVhenBkWFNwemIyWjBXMXM2WW14aGJtczZYVjBxYm5CeWIyTmJXenBpYkdGdWF6cGRYU28wTURrMkx5b0pDWE52Wm5RSmJuQnliMk1KQ1hWdWJHbHRhWFJsWkM4bklDQWdJQ0FnSUNBZ0wyVjBZeTl6WldOMWNtbDBlUzlzYVcxcGRITXVaQzh5TUMxdWNISnZZeTVqYjI1bUNtVmphRzhnTFdVZ0p5b0pDV2hoY21RSmJuQnliMk1KQ1hWdWJHbHRhWFJsWkNjZ1BqNGdMMlYwWXk5elpXTjFjbWwwZVM5c2FXMXBkSE11WkM4eU1DMXVjSEp2WXk1amIyNW1DZ3B6WldRZ0xXa2dKM012STAxaGVGTmxjM05wYjI1eklGd29MaXBjS1NRdlRXRjRVMlZ6YzJsdmJuTWdNVEF3TUM4bklDOWxkR012YzNOb0wzTnphR1JmWTI5dVptbG5Dbk5sWkNBdGFTQW5jeThqVFdGNFUzUmhjblIxY0hNZ1hDZ3VLbHdwSkM5TllYaFRkR0Z5ZEhWd2N5QTJNQzhuSUM5bGRHTXZjM05vTDNOemFHUmZZMjl1Wm1sbkNuTmxaQ0F0YVNBbmN5OGpURzluYVc1SGNtRmpaVlJwYldVZ1hDZ3VLbHdwSkM5TWIyZHBia2R5WVdObFZHbHRaU0F4TlhNdkp5QXZaWFJqTDNOemFDOXpjMmhrWDJOdmJtWnBad3B6ZVhOMFpXMWpkR3dnY21WemRHRnlkQ0J6YzJoa0NnPT0iLCAic2N5bGxhX3lhbWwiOiB7ImNsdXN0ZXJfbmFtZSI6ICJnZW1pbmktMXRiLTEwaC1tYXN0ZXItZGItY2x1c3Rlci1lMTY1NTIyYSJ9LCAic3RhcnRfc2N5bGxhX29uX2ZpcnN0X2Jvb3QiOiBmYWxzZX0=
``` 

Same user-data is reported in the logs:

```
2021-12-07T01:31:27+00:00 gemini-1tb-10h-master-db-node-e165522a-1 !    INFO | 2021-12-07 01:31:27,736 - [scylla_post_start] - INFO - Got user-data: eyJjbHVzdGVyX25hbWUiOiAiZ2VtaW5pLTF0Yi0xMGgtbWFzdGVyLWRiLWNsdXN0ZXItZTE2NTUyMmEiLCAiZGF0YV9kZXZpY2UiOiAiaW5zdGFuY2Vfc3RvcmUiLCAicG9zdF9jb25maWd1cmF0aW9uX3NjcmlwdCI6ICJJeUV2WW1sdUwySmhjMmdLQ25ObFpDQXRhU0F0WlNBbmN5OWVYQ3BiV3pwaWJHRnVhenBkWFNwemIyWjBXMXM2WW14aGJtczZYVjBxYm5CeWIyTmJXenBpYkdGdWF6cGRYU28wTURrMkx5b0pDWE52Wm5RSmJuQnliMk1KQ1hWdWJHbHRhWFJsWkM4bklDQWdJQ0FnSUNBZ0wyVjBZeTl6WldOMWNtbDBlUzlzYVcxcGRITXVaQzh5TUMxdWNISnZZeTVqYjI1bUNtVmphRzhnTFdVZ0p5b0pDV2hoY21RSmJuQnliMk1KQ1hWdWJHbHRhWFJsWkNjZ1BqNGdMMlYwWXk5elpXTjFjbWwwZVM5c2FXMXBkSE11WkM4eU1DMXVjSEp2WXk1amIyNW1DZ3B6WldRZ0xXa2dKM012STAxaGVGTmxjM05wYjI1eklGd29MaXBjS1NRdlRXRjRVMlZ6YzJsdmJuTWdNVEF3TUM4bklDOWxkR012YzNOb0wzTnphR1JmWTI5dVptbG5Dbk5sWkNBdGFTQW5jeThqVFdGNFUzUmhjblIxY0hNZ1hDZ3VLbHdwSkM5TllYaFRkR0Z5ZEhWd2N5QTJNQzhuSUM5bGRHTXZjM05vTDNOemFHUmZZMjl1Wm1sbkNuTmxaQ0F0YVNBbmN5OGpURzluYVc1SGNtRmpaVlJwYldVZ1hDZ3VLbHdwSkM5TWIyZHBia2R5WVdObFZHbHRaU0F4TlhNdkp5QXZaWFJqTDNOemFDOXpjMmhrWDJOdmJtWnBad3B6ZVhOMFpXMWpkR3dnY21WemRHRnlkQ0J6YzJoa0NnPT0iLCAic2N5bGxhX3lhbWwiOiB7ImNsdXN0ZXJfbmFtZSI6ICJnZW1pbmktMXRiLTEwaC1tYXN0ZXItZGItY2x1c3Rlci1lMTY1NTIyYSJ9LCAic3RhcnRfc2N5bGxhX29uX2ZpcnN0X2Jvb3QiOiBmYWxzZX0=
```

While usually we are getting it decoded on scylla_image side.
I have also re-run the test and checked results there - user_data was decoded propery and script was executed.

So, most likely it was temporary issue on aws side.
