### ISSUE TITLE
Running post configuration script fails on Scylla nodes added with grow_shrink_cluster nemesis

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-cluster-tests#4205]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master / 2c05a22
* **scylla**: `4.7.dev-0.20211126.44f4ea38c` with build-id `a88083cca1208179dd36a3847af403f77ad794f0`

### Logs
* test_id: c9a476f5-ee4a-4392-920a-3b6d9694a0c3
* job log: https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-100gb-4h-ebs-gp3-test/23

### Description

If we run "grow_shrink_cluster" nemesis that creates a new Scylla node then "post configuration script" fails there with the following error:
```
Dec 09 12:06:00 ip-10-0-1-254 scylla_image_setup[857]: 2021-12-09 12:06:00,946 - [scylla_configure] - INFO - Running post configuration script:
Dec 09 12:06:00 ip-10-0-1-254 scylla_image_setup[857]: b'#!/bin/bash\n\nsed -i -e \'s/^\\*[[:blank:]]*soft[[:blank:]]*nproc[[:blank:]]*4096/*\t\tsoft\tnproc\t\tunlimited/\'         /etc/security/limits.d/20-nproc.conf\necho -e \'*\t\thard\tnproc\t\tunlimited\' >> /etc/security/limits.d/20-nproc.conf\n\nsed -i \'s/#MaxSessions \\(.*\\)$/MaxSessions 1000/\' /etc/ssh/sshd_config\nsed -i \'s/#MaxStartups \\(.*\\)$/MaxStartups 60/\' /etc/ssh/sshd_config\nsed -i \'s/#LoginGraceTime \\(.*\\)$/LoginGraceTime 15s/\' /etc/ssh/sshd_config\nsystemctl restart sshd\nif yum --help 2>/dev/null 1>&2 ; then\n    if ! rpm -q syslog-ng ; then\n        yum install -y syslog-ng\n    fi\n    rpm -q syslog-ng\nelif apt-get --help 2>/dev/null 1>&2 ; then\n    if ! dpkg-query --show syslog-ng ; then\n        while ! find /proc/*/fd -lname /var/lib/dpkg/lock-frontend -exec false {} + -quit ; do\n            sleep 60\n        done\n        apt-get -qq update\n        apt-get -qq install syslog-ng\n    fi\n    dpkg-query --show syslog-ng\nelse\n    echo "Unsupported distro"\n    false\nfi\n\nif [ $? -ne 0 ]; then\n\ngrep imjournalRatelimitInterval /etc/rsyslog.conf | cat <<EOF >> /etc/rsyslog.conf\n#\n# The following configuration was added by SCT.\n#\n\\$ModLoad imjournal\n\\$imjournalRatelimitInterval 60\n\\$imjournalRatelimitBurst 50000\nEOF\necho "action(type=\\"omfwd\\" Target=\\"10.0.3.28\\" Port=\\"49153\\" Protocol=\\"tcp\\")" >> /etc/rsyslog.conf\nsystemctl restart rsyslog\n\nelse\n\nsource_name=`cat /etc/syslog-ng/syslog-ng.conf | tr -d "\\n" | tr -d "\\r" | sed -r "s/\\};/\\};\\n/g;         s/source /\\nsource /g" | grep -P "^source.*system\\(\\)" | cut -d" " -f2`\ndisk_buffer_option=""\nif syslog-ng -V | grep disk; then\n    disk_buffer_option="disk-buffer(\n            mem-buf-size(100000)\n            disk-buf-size(2000000)\n            reliable(yes)\n            dir(\\"/tmp\\")\n        )"\nfi\n\nif grep -P "keep-timestamp\\([^)]+\\)" /etc/syslog-ng/syslog-ng.conf; then\n    sed -i -r "s/keep-timestamp([ ]*yes[ ]*)/keep-timestamp(no)/g" /etc/syslog-ng/syslog-ng.conf\nelse\n    sed -i -r "s/([ \t]*options[ \t]*\\\\{)/\\\\1\\n  keep-timestamp(no);\\n/g" /etc/syslog-ng/syslog-ng.conf\nfi\n\ngrep "destination remote_sct" /etc/syslog-ng/syslog-ng.conf || cat <<EOF >>/etc/syslog-ng/syslog-ng.conf\ndestination remote_sct {\n    network(\n        "10.0.3.28"\n        transport("tcp")\n        port(49153)\n        throttle(10000)\n        $disk_buffer_option\n    );\n};\n\ndestination d_system { file("/var/log/system.log"); };\nlog { source($source_name); destination(d_system); };\n\nEOF\n\nif ! grep -P "log {.*destination\\\\(remote_sct\\\\)" /etc/syslog-ng/syslog-ng.conf; then\n    echo "log { source($source_name); destination(remote_sct); };" >> /etc/syslog-ng/syslog-ng.conf\nfi\n\nif [ ! -z "" ]; then\n    if grep "rewrite r_host" /etc/syslog-ng/syslog-ng.conf; then\n        sed -i -r "s/rewrite r_host \\{ set\\(\\"[^\\"]+\\"/rewrite r_host { set(\\"\\"/" /etc/syslog-ng/syslog-ng.conf\n    else\n        echo "rewrite r_host { set(\\"\\", value(\\"HOST\\")); };" >>  /etc/syslog-ng/syslog-ng.conf\n        sed -i -r "s/destination\\(remote_sct\\);[ \\t]*\\};/destination\\(remote_sct\\); rewrite\\(r_host\\); \\};/" /etc/syslog-ng/syslog-ng.conf\n    fi\nfi\nsystemctl restart syslog-ng\n\nfi\n'
Dec 09 12:06:00 ip-10-0-1-254 scylla_image_setup[857]: Running post configuration script:
Dec 09 12:06:00 ip-10-0-1-254 scylla_image_setup[857]: b'#!/bin/bash\n\nsed -i -e \'s/^\\*[[:blank:]]*soft[[:blank:]]*nproc[[:blank:]]*4096/*\t\tsoft\tnproc\t\tunlimited/\'         /etc/security/limits.d/20-nproc.conf\necho -e \'*\t\thard\tnproc\t\tunlimited\' >> /etc/security/limits.d/20-nproc.conf\n\nsed -i \'s/#MaxSessions \\(.*\\)$/MaxSessions 1000/\' /etc/ssh/sshd_config\nsed -i \'s/#MaxStartups \\(.*\\)$/MaxStartups 60/\' /etc/ssh/sshd_config\nsed -i \'s/#LoginGraceTime \\(.*\\)$/LoginGraceTime 15s/\' /etc/ssh/sshd_config\nsystemctl restart sshd\nif yum --help 2>/dev/null 1>&2 ; then\n    if ! rpm -q syslog-ng ; then\n        yum install -y syslog-ng\n    fi\n    rpm -q syslog-ng\nelif apt-get --help 2>/dev/null 1>&2 ; then\n    if ! dpkg-query --show syslog-ng ; then\n        while ! find /proc/*/fd -lname /var/lib/dpkg/lock-frontend -exec false {} + -quit ; do\n            sleep 60\n        done\n        apt-get -qq update\n        apt-get -qq install syslog-ng\n    fi\n    dpkg-query --show syslog-ng\nelse\n    echo "Unsupported distro"\n    false\nfi\n\nif [ $? -ne 0 ]; then\n\ngrep imjournalRatelimitInterval /etc/rsyslog.conf | cat <<EOF >> /etc/rsyslog.conf\n#\n# The following configuration was added by SCT.\n#\n\\$ModLoad imjournal\n\\$imjournalRatelimitInterval 60\n\\$imjournalRatelimitBurst 50000\nEOF\necho "action(type=\\"omfwd\\" Target=\\"10.0.3.28\\" Port=\\"49153\\" Protocol=\\"tcp\\")" >> /etc/rsyslog.conf\nsystemctl restart rsyslog\n\nelse\n\nsource_name=`cat /etc/syslog-ng/syslog-ng.conf | tr -d "\\n" | tr -d "\\r" | sed -r "s/\\};/\\};\\n/g;         s/source /\\nsource /g" | grep -P "^source.*system\\(\\)" | cut -d" " -f2`\ndisk_buffer_option=""\nif syslog-ng -V | grep disk; then\n    disk_buffer_option="disk-buffer(\n            mem-buf-size(100000)\n            disk-buf-size(2000000)\n            reliable(yes)\n            dir(\\"/tmp\\")\n        )"\nfi\n\nif grep -P "keep-timestamp\\([^)]+\\)" /etc/syslog-ng/syslog-ng.conf; then\n    sed -i -r "s/keep-timestamp([ ]*yes[ ]*)/keep-timestamp(no)/g" /etc/syslog-ng/syslog-ng.conf\nelse\n    sed -i -r "s/([ \t]*options[ \t]*\\\\{)/\\\\1\\n  keep-timestamp(no);\\n/g" /etc/syslog-ng/syslog-ng.conf\nfi\n\ngrep "destination remote_sct" /etc/syslog-ng/syslog-ng.conf || cat <<EOF >>/etc/syslog-ng/syslog-ng.conf\ndestination remote_sct {\n    network(\n        "10.0.3.28"\n        transport("tcp")\n        port(49153)\n        throttle(10000)\n        $disk_buffer_option\n    );\n};\n\ndestination d_system { file("/var/log/system.log"); };\nlog { source($source_name); destination(d_system); };\n\nEOF\n\nif ! grep -P "log {.*destination\\\\(remote_sct\\\\)" /etc/syslog-ng/syslog-ng.conf; then\n    echo "log { source($source_name); destination(remote_sct); };" >> /etc/syslog-ng/syslog-ng.conf\nfi\n\nif [ ! -z "" ]; then\n    if grep "rewrite r_host" /etc/syslog-ng/syslog-ng.conf; then\n        sed -i -r "s/rewrite r_host \\{ set\\(\\"[^\\"]+\\"/rewrite r_host { set(\\"\\"/" /etc/syslog-ng/syslog-ng.conf\n    else\n        echo "rewrite r_host { set(\\"\\", value(\\"HOST\\")); };" >>  /etc/syslog-ng/syslog-ng.conf\n        sed -i -r "s/destination\\(remote_sct\\);[ \\t]*\\};/destination\\(remote_sct\\); rewrite\\(r_host\\); \\};/" /etc/syslog-ng/syslog-ng.conf\n    fi\nfi\nsystemctl restart syslog-ng\n\nfi\n'
Dec 09 12:06:00 ip-10-0-1-254 scylla_image_setup[873]: sed: can't read /etc/security/limits.d/20-nproc.conf: No such file or directory
Dec 09 12:06:01 ip-10-0-1-254 scylla_image_setup[904]: dpkg-query: no packages found matching syslog-ng
Dec 09 12:06:07 longevity-100gb-4h-master-db-node-c9a476f5-7 scylla_image_setup[2040]: E: Unable to locate package syslog-ng
Dec 09 12:06:07 longevity-100gb-4h-master-db-node-c9a476f5-7 scylla_image_setup[2074]: dpkg-query: no packages found matching syslog-ng
```

In the referenced run were added 3 nodes and each of those had this problem.

Also, there is missing "messages.log" file and raised exception with it:
```
Wait for: wait for db logs: timeout - 300 seconds - expired                                            
last error: Exception('No db log from the following nodes:\nlongevity-100gb-4h-master-db-node-c9a476f5-8\nfiles expected to be find:\n/home/ubuntu/sct-results/20211209-110802-568969/hosts/longevity-100gb-4h-master-db-node-c9a476f5-8/messages.log')
sdcm.nemesis.ChaosMonkey: Unhandled exception in method <function Nemesis.disrupt_grow_shrink_cluster at 0x7fdaec554a60> < t:2021-12-09 12:45:39,057 f:nemesis.py      l:3025 c:sdcm.nemesis         p:ERROR > sdcm.nemesis.ChaosMonkey: Unhandled exception in method <function Nemesis.disrupt_grow_shrink_cluster at 0x7fdaec554a60>
Traceback (most recent call last):                                                                     
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3015, in wrapper                      
    result = method(*args, **kwargs)                                                                   
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2628, in disrupt_grow_shrink_cluster
    self._grow_cluster(rack=0)                                                                         
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2648, in _grow_cluster                
    added_node = self.add_new_node(rack=rack)                                                          
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 166, in wrapped              
    res = func(*args, **kwargs)                                                                        
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2604, in add_new_node                 
    return self._add_and_init_new_cluster_node(rack=rack)                                              
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 64, in inner                 
    return func(*args, **kwargs)                                                                       
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 839, in _add_and_init_new_cluster_node
    self.cluster.wait_for_init(node_list=[new_node], timeout=timeout, check_node_health=False)         
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3474, in wrapper                      
    method(*args, **kwargs)                                                                            
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 4227, in wait_for_init                
    wait.wait_for(                                                                                     
  File "/home/ubuntu/scylla-cluster-tests/sdcm/wait.py", line 61, in wait_for                          
    res = retry(func, **kwargs)                                                                        
  File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 404, in __call__           
    do = self.iter(retry_state=retry_state)                                                            
  File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 360, in iter               
    raise retry_exc.reraise()                                                                          
  File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 193, in reraise            
    raise self.last_attempt.result()                                                                   
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 438, in result                    
    return self.__get_result()                                                                         
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 390, in __get_result              
    raise self._exception                                                                              
  File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 407, in __call__           
    result = fn(*args, **kwargs)                                                                       
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 4217, in verify_logging_from_nodes 
    raise Exception(                                                                                   
Exception: No db log from the following nodes:                                                         
longevity-100gb-4h-master-db-node-c9a476f5-8                                                           
files expected to be find:                                                                             
/home/ubuntu/sct-results/20211209-110802-568969/hosts/longevity-100gb-4h-master-db-node-c9a476f5-8/messages.log
```

Note that nodes 7 and 8 were added by the same nemesis, 8th was added because 7th failed to get network connectivity and timed out due to it. So, need to look at the nodes 8 and 9 in such a case.

Severity of it is high, because we do not have logs of some nodes which are needed for debugging of the DB issues.

### Steps to Reproduce

1. Deploy Scylla cluster
2. Run "grow_shrink_cluster" nemesis
3. Look at the "system.log" file and see the mentioned error.

**Expected behavior:** script must pass successfully.

**Actual behavior:** script fails as described.

**Comment by dkropachev** [comment]
Fixed at https://github.com/scylladb/scylla-cluster-tests/pull/4281
