### ISSUE TITLE
delete_automatic_repair_task is failing with `get resource: load task "00000000-0000-0000-0000-000000000000": not found`

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla-cluster-tests#4252]
```
[2021-12-21T18:06:56.999Z] 2021-12-21 18:02:48.647: (DisruptionEvent Severity.ERROR) period_type=end event_id=f0450a46-83b4-4a10-bb11-cd5fbda57ebd duration=22s: nemesis_name=MgmtBackup target_node=Node PR-provision-test-jenkins-db-node-1444a9d5-2 [3.250.75.210 | 10.0.0.8] (seed: False) errors=Encountered an error on sctool command: -c ac07b90c-a3ff-463a-96b2-8f783bdb496f task delete repair/all-weekly: Encountered a bad command exit code!
[2021-12-21T18:06:56.999Z] Command: 'sudo sctool -c ac07b90c-a3ff-463a-96b2-8f783bdb496f task delete repair/all-weekly'
[2021-12-21T18:06:56.999Z] Exit code: 1
[2021-12-21T18:06:56.999Z] Stdout:
[2021-12-21T18:06:56.999Z] Stderr:
[2021-12-21T18:06:56.999Z] Command "delete" is deprecated, use sctool stop --delete instead
[2021-12-21T18:06:56.999Z] Error: get resource: load task "00000000-0000-0000-0000-000000000000": not found
[2021-12-21T18:06:56.999Z] Trace ID: oZbOyVAdSVu_RcHheIwd4w (grep in scylla-manager logs)
[2021-12-21T18:06:56.999Z] Traceback (most recent call last):
[2021-12-21T18:06:56.999Z] File "/home/jenkins/slave/workspace/can_scylla-cluster-tests_PR-4245/scylla-cluster-tests/sdcm/mgmt/cli.py", line 1004, in run
[2021-12-21T18:06:56.999Z] res = self.manager_node.remoter.sudo(f"sctool {cmd}")
[2021-12-21T18:06:56.999Z] File "/home/jenkins/slave/workspace/can_scylla-cluster-tests_PR-4245/scylla-cluster-tests/sdcm/remote/base.py", line 123, in sudo
[2021-12-21T18:06:56.999Z] return self.run(cmd=cmd,
[2021-12-21T18:06:56.999Z] File "/home/jenkins/slave/workspace/can_scylla-cluster-tests_PR-4245/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run
[2021-12-21T18:06:56.999Z] result = _run()
[2021-12-21T18:06:57.000Z] File "/home/jenkins/slave/workspace/can_scylla-cluster-tests_PR-4245/scylla-cluster-tests/sdcm/utils/decorators.py", line 64, in inner
[2021-12-21T18:06:57.000Z] return func(*args, **kwargs)
[2021-12-21T18:06:57.000Z] File "/home/jenkins/slave/workspace/can_scylla-cluster-tests_PR-4245/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run
[2021-12-21T18:06:57.000Z] return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
[2021-12-21T18:06:57.000Z] File "/home/jenkins/slave/workspace/can_scylla-cluster-tests_PR-4245/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
[2021-12-21T18:06:57.000Z] result = connection.run(**command_kwargs)
[2021-12-21T18:06:57.000Z] File "<decorator-gen-3>", line 2, in run
[2021-12-21T18:06:57.000Z] File "/usr/local/lib/python3.10/site-packages/fabric/connection.py", line 30, in opens
[2021-12-21T18:06:57.000Z] return method(self, *args, **kwargs)
[2021-12-21T18:06:57.000Z] File "/usr/local/lib/python3.10/site-packages/fabric/connection.py", line 723, in run
[2021-12-21T18:06:57.000Z] return self._run(self._remote_runner(), command, **kwargs)
[2021-12-21T18:06:57.000Z] File "/usr/local/lib/python3.10/site-packages/invoke/context.py", line 102, in _run
[2021-12-21T18:06:57.000Z] return runner.run(command, **kwargs)
[2021-12-21T18:06:57.000Z] File "/usr/local/lib/python3.10/site-packages/invoke/runners.py", line 380, in run
[2021-12-21T18:06:57.000Z] return self._run_body(command, **kwargs)
[2021-12-21T18:06:57.000Z] File "/usr/local/lib/python3.10/site-packages/invoke/runners.py", line 442, in _run_body
[2021-12-21T18:06:57.000Z] return self.make_promise() if self._asynchronous else self._finish()
[2021-12-21T18:06:57.000Z] File "/usr/local/lib/python3.10/site-packages/invoke/runners.py", line 509, in _finish
[2021-12-21T18:06:57.000Z] raise UnexpectedExit(result)
[2021-12-21T18:06:57.000Z] invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!
[2021-12-21T18:06:57.000Z] Command: 'sudo sctool -c ac07b90c-a3ff-463a-96b2-8f783bdb496f task delete repair/all-weekly'
[2021-12-21T18:06:57.000Z] Exit code: 1
[2021-12-21T18:06:57.000Z] Stdout:
[2021-12-21T18:06:57.000Z] Stderr:
[2021-12-21T18:06:57.000Z] Command "delete" is deprecated, use sctool stop --delete instead
[2021-12-21T18:06:57.000Z] Error: get resource: load task "00000000-0000-0000-0000-000000000000": not found
[2021-12-21T18:06:57.000Z] Trace ID: oZbOyVAdSVu_RcHheIwd4w (grep in scylla-manager logs)
[2021-12-21T18:06:57.000Z] The above exception was the direct cause of the following exception:
[2021-12-21T18:06:57.000Z] Traceback (most recent call last):
[2021-12-21T18:06:57.000Z] File "/home/jenkins/slave/workspace/can_scylla-cluster-tests_PR-4245/scylla-cluster-tests/sdcm/nemesis.py", line 3075, in wrapper
[2021-12-21T18:06:57.000Z] result = method(*args, **kwargs)
[2021-12-21T18:06:57.000Z] File "/home/jenkins/slave/workspace/can_scylla-cluster-tests_PR-4245/scylla-cluster-tests/sdcm/nemesis.py", line 1861, in disrupt_mgmt_backup
[2021-12-21T18:06:57.000Z] self._mgmt_backup(backup_specific_tables=False)
[2021-12-21T18:06:57.000Z] File "/home/jenkins/slave/workspace/can_scylla-cluster-tests_PR-4245/scylla-cluster-tests/sdcm/nemesis.py", line 1866, in _mgmt_backup
[2021-12-21T18:06:57.000Z] mgr_cluster = self.cluster.get_cluster_manager()
[2021-12-21T18:06:57.000Z] File "/home/jenkins/slave/workspace/can_scylla-cluster-tests_PR-4245/scylla-cluster-tests/sdcm/cluster.py", line 4372, in get_cluster_manager
[2021-12-21T18:06:57.000Z] return self.create_cluster_manager(cluster_name, manager_tool=manager_tool)
[2021-12-21T18:06:57.000Z] File "/home/jenkins/slave/workspace/can_scylla-cluster-tests_PR-4245/scylla-cluster-tests/sdcm/cluster.py", line 4380, in create_cluster_manager
[2021-12-21T18:06:57.000Z] return manager_tool.add_cluster(name=cluster_name, host=host_ip, auth_token=self.scylla_manager_auth_token)
[2021-12-21T18:06:57.000Z] File "/home/jenkins/slave/workspace/can_scylla-cluster-tests_PR-4245/scylla-cluster-tests/sdcm/mgmt/cli.py", line 903, in add_cluster
[2021-12-21T18:06:57.000Z] manager_cluster.delete_automatic_repair_task()
[2021-12-21T18:06:57.000Z] File "/home/jenkins/slave/workspace/can_scylla-cluster-tests_PR-4245/scylla-cluster-tests/sdcm/mgmt/cli.py", line 565, in delete_automatic_repair_task
[2021-12-21T18:06:57.000Z] self.delete_task(automatic_repair_task.id)
[2021-12-21T18:06:57.000Z] File "/home/jenkins/slave/workspace/can_scylla-cluster-tests_PR-4245/scylla-cluster-tests/sdcm/mgmt/cli.py", line 558, in delete_task
[2021-12-21T18:06:57.000Z] self.sctool.run(cmd=cmd, parse_table_res=False)
[2021-12-21T18:06:57.000Z] File "/home/jenkins/slave/workspace/can_scylla-cluster-tests_PR-4245/scylla-cluster-tests/sdcm/mgmt/cli.py", line 1007, in run
[2021-12-21T18:06:57.000Z] raise ScyllaManagerError(f"Encountered an error on sctool command: {cmd}: {ex}") from ex
[2021-12-21T18:06:57.000Z] sdcm.mgmt.common.ScyllaManagerError: Encountered an error on sctool command: -c ac07b90c-a3ff-463a-96b2-8f783bdb496f task delete repair/all-weekly: Encountered a bad command exit code!
[2021-12-21T18:06:57.000Z] Command: 'sudo sctool -c ac07b90c-a3ff-463a-96b2-8f783bdb496f task delete repair/all-weekly'
[2021-12-21T18:06:57.000Z] Exit code: 1
[2021-12-21T18:06:57.000Z] Stdout:
[2021-12-21T18:06:57.000Z] Stderr:
[2021-12-21T18:06:57.000Z] Command "delete" is deprecated, use sctool stop --delete instead
[2021-12-21T18:06:57.000Z] Error: get resource: load task "00000000-0000-0000-0000-000000000000": not found
[2021-12-21T18:06:57.000Z] Trace ID: oZbOyVAdSVu_RcHheIwd4w (grep in scylla-manager logs)
```

**Comment by roydahan** [comment]
@ShlomiBalalis is it something new in manager?

@dkropachev which job  is it?

**Comment by roydahan** [comment]
I'm going to change SCT master tests to use the latest released manager version, this issue is relevant to manager master which will be tested only in manager master branch.

**Comment by dkropachev** [comment]
Test-id: 1463ea98-e1db-4167-b8fd-7824f63a2be4

db-cluster - https://cloudius-jenkins-test.s3.amazonaws.com/1463ea98-e1db-4167-b8fd-7824f63a2be4/20211221_134147/db-cluster-1463ea98.tar.gz
loader-set - https://cloudius-jenkins-test.s3.amazonaws.com/1463ea98-e1db-4167-b8fd-7824f63a2be4/20211221_134147/loader-set-1463ea98.tar.gz
monitor-set - https://cloudius-jenkins-test.s3.amazonaws.com/1463ea98-e1db-4167-b8fd-7824f63a2be4/20211221_134147/monitor-set-1463ea98.tar.gz
sct-runner - https://cloudius-jenkins-test.s3.amazonaws.com/1463ea98-e1db-4167-b8fd-7824f63a2be4/20211221_134147/sct-runner-1463ea98.tar.gz

**Comment by Orenef11** [comment]
happened again
I think the command was changed from `delete` to ` stop --delete`
https://github.com/scylladb/scylla-cluster-tests/pull/4268

Restore Monitor Stack command: `$ hydra investigate show-monitor 21bf62d0-29de-4108-a20c-9c0aeabfd17a`
Show all stored logs command: `$ hydra investigate show-logs 21bf62d0-29de-4108-a20c-9c0aeabfd17a`

Test id: `21bf62d0-29de-4108-a20c-9c0aeabfd17a`


Logs:
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/21bf62d0-29de-4108-a20c-9c0aeabfd17a/20211226_082027/grafana-screenshot-longevity-10gb-3h-test-scylla-per-server-metrics-nemesis-20211226_082248-longevity-10gb-3h-master-monitor-node-21bf62d0-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/21bf62d0-29de-4108-a20c-9c0aeabfd17a/20211226_082027/grafana-screenshot-longevity-10gb-3h-test-scylla-per-server-metrics-nemesis-20211226_082248-longevity-10gb-3h-master-monitor-node-21bf62d0-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/21bf62d0-29de-4108-a20c-9c0aeabfd17a/20211226_082027/grafana-screenshot-overview-20211226_082027-longevity-10gb-3h-master-monitor-node-21bf62d0-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/21bf62d0-29de-4108-a20c-9c0aeabfd17a/20211226_082027/grafana-screenshot-overview-20211226_082027-longevity-10gb-3h-master-monitor-node-21bf62d0-1.png)
db-cluster - [https://cloudius-jenkins-test.s3.amazonaws.com/21bf62d0-29de-4108-a20c-9c0aeabfd17a/20211226_083120/db-cluster-21bf62d0.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/21bf62d0-29de-4108-a20c-9c0aeabfd17a/20211226_083120/db-cluster-21bf62d0.tar.gz)
loader-set - [https://cloudius-jenkins-test.s3.amazonaws.com/21bf62d0-29de-4108-a20c-9c0aeabfd17a/20211226_083120/loader-set-21bf62d0.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/21bf62d0-29de-4108-a20c-9c0aeabfd17a/20211226_083120/loader-set-21bf62d0.tar.gz)
monitor-set - [https://cloudius-jenkins-test.s3.amazonaws.com/21bf62d0-29de-4108-a20c-9c0aeabfd17a/20211226_083120/monitor-set-21bf62d0.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/21bf62d0-29de-4108-a20c-9c0aeabfd17a/20211226_083120/monitor-set-21bf62d0.tar.gz)
sct - [https://cloudius-jenkins-test.s3.amazonaws.com/21bf62d0-29de-4108-a20c-9c0aeabfd17a/20211226_083120/sct-runner-21bf62d0.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/21bf62d0-29de-4108-a20c-9c0aeabfd17a/20211226_083120/sct-runner-21bf62d0.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-10gb-3h-test/408/)

**Comment by rayakurl** [comment]
Closing this issue as it was fixed a while ago when SCT manager was adjuster to manager 3.0 new CLI
