### ISSUE TITLE
AddRemoveDC nemesis (new nemesis) - Failed with traceback - couldn't find db log of node

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla-cluster-tests#4262]
During job scylla-master/longevity/longevity-alternator-3h-test#327: 2021-12-22 09:46:33.

```
2021-12-22 13:07:59.178: (DisruptionEvent Severity.ERROR) period_type=end event_id=354bf243-1777-48de-a57a-12e7647a4913 duration=11m13s: nemesis_name=AddRemoveDc target_node=Node alternator-3h-master-db-node-1f2279f2-3 [13.49.23.236 | 10.0.0.241] (seed: False) errors=No db log from the following nodes:
alternator-3h-master-db-node-1f2279f2-9
files expected to be find:
/home/ubuntu/sct-results/20211222-091011-703895/hosts/alternator-3h-master-db-node-1f2279f2-9/messages.log
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3075, in wrapper
result = method(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2971, in disrupt_add_remove_dc
new_node = self._add_new_node_in_new_dc()
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2942, in _add_new_node_in_new_dc
self.cluster.wait_for_init(node_list=[new_node], timeout=900,
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3479, in wrapper
method(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 4232, in wait_for_init
wait.wait_for(
File "/home/ubuntu/scylla-cluster-tests/sdcm/wait.py", line 61, in wait_for
res = retry(func, **kwargs)
File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 404, in __call__
do = self.iter(retry_state=retry_state)
File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 360, in iter
raise retry_exc.reraise()
File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 193, in reraise
raise self.last_attempt.result()
File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 438, in result
return self.__get_result()
File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 390, in __get_result
raise self._exception
File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 407, in __call__
result = fn(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 4222, in verify_logging_from_nodes
raise Exception(
Exception: No db log from the following nodes:
alternator-3h-master-db-node-1f2279f2-9
files expected to be find:
/home/ubuntu/sct-results/20211222-091011-703895/hosts/alternator-3h-master-db-node-1f2279f2-9/messages.log
```

**Comment by roydahan** [comment]
Since it's a new nemesis without proven record of runs, I assign to its author automatically - @soyacz .

**Comment by soyacz** [comment]
@dkropachev isn't it related to syslog-ng? Can you check if it works properly when new node in new dc is created?

**Comment by Orenef11** [comment]
@roydahan
happen for  `DecommissionStreamingErr` nemesis
```
10:27:16  2021-12-26 08:07:33.793: (DisruptionEvent Severity.ERROR) period_type=end event_id=90227217-83fc-4a1b-9352-62b528f40743 duration=11m3s: nemesis_name=AddRemoveDc target_node=Node alternator-3h-master-db-node-6b6e1fda-6 [34.241.226.37 | 10.0.1.86] (seed: False) errors=No db log from the following nodes:
10:27:16  alternator-3h-master-db-node-6b6e1fda-9
10:27:16  files expected to be find:
10:27:16  /home/ubuntu/sct-results/20211226-040756-930810/hosts/alternator-3h-master-db-node-6b6e1fda-9/messages.log
10:27:16  Traceback (most recent call last):
10:27:16  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3080, in wrapper
10:27:16  result = method(*args, **kwargs)
10:27:16  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2976, in disrupt_add_remove_dc
10:27:16  new_node = self._add_new_node_in_new_dc()
10:27:16  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2947, in _add_new_node_in_new_dc
10:27:16  self.cluster.wait_for_init(node_list=[new_node], timeout=900,
10:27:16  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3479, in wrapper
10:27:16  method(*args, **kwargs)
10:27:16  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 4232, in wait_for_init
10:27:16  wait.wait_for(
10:27:16  File "/home/ubuntu/scylla-cluster-tests/sdcm/wait.py", line 61, in wait_for
10:27:16  res = retry(func, **kwargs)
10:27:16  File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 404, in __call__
10:27:16  do = self.iter(retry_state=retry_state)
10:27:16  File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 360, in iter
10:27:16  raise retry_exc.reraise()
10:27:16  File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 193, in reraise
10:27:16  raise self.last_attempt.result()
10:27:16  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 438, in result
10:27:16  return self.__get_result()
10:27:16  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 390, in __get_result
10:27:16  raise self._exception
10:27:16  File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 407, in __call__
10:27:16  result = fn(*args, **kwargs)
10:27:16  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 4222, in verify_logging_from_nodes
10:27:16  raise Exception(
10:27:16  Exception: No db log from the following nodes:
10:27:16  alternator-3h-master-db-node-6b6e1fda-9
10:27:16  files expected to be find:
10:27:16  /home/ubuntu/sct-results/20211226-040756-930810/hosts/alternator-3h-master-db-node-6b6e1fda-9/messages.log
```

test-id: `6b6e1fda-a66d-452a-a460-2ed2e8033ccf`

**Comment by yarongilor** [comment]
May also reproduced in 200k-pk-4d longevity 4.6.rc2 running test:
```
2022-01-10 20:49:38.450: (DisruptionEvent Severity.ERROR) period_type=end event_id=5d9a814d-96eb-4371-a40d-a390680621d9 duration=17m15s: nemesis_name=GrowShrinkCluster target_node=Node longevity-large-partitions-200k-pks-db-node-267923ae-7 [52.211.43.33 | 10.0.3.97] (seed: False) errors=No db log from the following nodes:
longevity-large-partitions-200k-pks-db-node-267923ae-8
files expected to be find:
/home/ubuntu/sct-results/20220109-170120-867578/hosts/longevity-large-partitions-200k-pks-db-node-267923ae-8/messages.log
Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3080, in wrapper
    result = method(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2693, in disrupt_grow_shrink_cluster
    self._grow_cluster(rack=0)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2713, in _grow_cluster
    added_node = self.add_new_node(rack=rack)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 166, in wrapped
    res = func(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2669, in add_new_node
    return self._add_and_init_new_cluster_node(rack=rack)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 64, in inner
    return func(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 877, in _add_and_init_new_cluster_node
    self.cluster.wait_for_init(node_list=[new_node], timeout=timeout, check_node_health=False)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3470, in wrapper
    method(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 4223, in wait_for_init
    wait.wait_for(
  File "/home/ubuntu/scylla-cluster-tests/sdcm/wait.py", line 61, in wait_for
    res = retry(func, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 360, in iter
    raise retry_exc.reraise()
  File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 193, in reraise
    raise self.last_attempt.result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 4213, in verify_logging_from_nodes
    raise Exception(
Exception: No db log from the following nodes:
longevity-large-partitions-200k-pks-db-node-267923ae-8
```
running in: https://jenkins.scylladb.com/view/scylla-4.6/job/scylla-4.6/job/longevity/view/Long%20Longevities/job/longevity-large-partition-200k-pks-4days-test/5/
