### ISSUE TITLE
Nodetool decommission fails with no explanation 4 seconds after executions

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla-cluster-tests#4301]
### Prerequisites

* [x] Are you rebased to master ?
* [ ] Is it reproducible ?
* [ ] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master
* **scylla**: master

### Logs
* test_id: 179db65e-1f8e-4725-b90c-0fd4151a88bc
```
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                 Log links for testrun with test id 179db65e-1f8e-4725-b90c-0fd4151a88bc                                                                                  |
+-----------------+-------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Date            | Log type    | Link                                                                                                                                                                                                     |
+-----------------+-------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 20211231_163005 | grafana     | https://cloudius-jenkins-test.s3.amazonaws.com/179db65e-1f8e-4725-b90c-0fd4151a88bc/20211231_163005/grafana-screenshot-overview-20211231_163005-longevity-tls-50gb-3d-master-monitor-node-179db65e-1.png |
| 20211231_170102 | db-cluster  | https://cloudius-jenkins-test.s3.amazonaws.com/179db65e-1f8e-4725-b90c-0fd4151a88bc/20211231_170102/db-cluster-179db65e.tar.gz                                                                           |
| 20211231_170102 | loader-set  | https://cloudius-jenkins-test.s3.amazonaws.com/179db65e-1f8e-4725-b90c-0fd4151a88bc/20211231_170102/loader-set-179db65e.tar.gz                                                                           |
| 20211231_170102 | monitor-set | https://cloudius-jenkins-test.s3.amazonaws.com/179db65e-1f8e-4725-b90c-0fd4151a88bc/20211231_170102/monitor-set-179db65e.tar.gz                                                                          |
| 20211231_170102 | sct         | https://cloudius-jenkins-test.s3.amazonaws.com/179db65e-1f8e-4725-b90c-0fd4151a88bc/20211231_170102/sct-runner-179db65e.tar.gz                                                                           |
+-----------------+-------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```
https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-50gb-3days/117/

### Description

At `2021-12-31 16:03:50.816` a GrowShrinkCluster has started. The nemesis initiates a new node and adds it to the cluster, and then decommissions a random node.
At `2021-12-31 16:21:38,347`, the decommission command with node No. 13 (54.195.173.85 | 10.0.3.203) as the target node.
However, 4 seconds after the decommission has started, it failed with no stdout or stderr (seemingly, out of connection error?):
```
2021-12-31 16:21:42.624: (NodetoolEvent Severity.ERROR) period_type=end event_id=fc495d89-04c9-426b-a1c7-0b8d66066ea2 duration=4s: nodetool_command=decommission node=longevity-tls-50gb-3d-master-db-node-179db65e-13 errors=['Encountered a bad command exit code!\n\nCommand: "/usr/bin/nodetool -u cassandra -pw \'cassandra\'  decommission "\n\nExit code: -1\n\nStdout:\n\n\n\nStderr:\n\n\n\n', 'Traceback (most recent call last):\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2564, in run_nodetool\n    result = self.remoter.run(cmd, timeout=timeout, ignore_status=ignore_status, verbose=verbose)\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run\n    result = _run()\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 64, in inner\n    return func(*args, **kwargs)\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run\n    return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute\n    result = connection.run(**command_kwargs)\n  File "<decorator-gen-3>", line 2, in run\n  File "/usr/local/lib/python3.10/site-packages/fabric/connection.py", line 30, in opens\n    return method(self, *args, **kwargs)\n  File "/usr/local/lib/python3.10/site-packages/fabric/connection.py", line 723, in run\n    return self._run(self._remote_runner(), command, **kwargs)\n  File "/usr/local/lib/python3.10/site-packages/invoke/context.py", line 102, in _run\n    return runner.run(command, **kwargs)\n  File "/usr/local/lib/python3.10/site-packages/invoke/runners.py", line 380, in run\n    return self._run_body(command, **kwargs)\n  File "/usr/local/lib/python3.10/site-packages/invoke/runners.py", line 442, in _run_body\n    return self.make_promise() if self._asynchronous else self._finish()\n  File "/usr/local/lib/python3.10/site-packages/invoke/runners.py", line 509, in _finish\n    raise UnexpectedExit(result)\ninvoke.exceptions.UnexpectedExit: Encountered a bad command exit code!\n\nCommand: "/usr/bin/nodetool -u cassandra -pw \'cassandra\'  decommission "\n\nExit code: -1\n\nStdout:\n\n\n\nStderr:\n\n\n\n\n']
Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2564, in run_nodetool
    result = self.remoter.run(cmd, timeout=timeout, ignore_status=ignore_status, verbose=verbose)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run
    result = _run()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 64, in inner
    return func(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run
    return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
    result = connection.run(**command_kwargs)
  File "<decorator-gen-3>", line 2, in run
  File "/usr/local/lib/python3.10/site-packages/fabric/connection.py", line 30, in opens
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/fabric/connection.py", line 723, in run
    return self._run(self._remote_runner(), command, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/invoke/context.py", line 102, in _run
    return runner.run(command, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/invoke/runners.py", line 380, in run
    return self._run_body(command, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/invoke/runners.py", line 442, in _run_body
    return self.make_promise() if self._asynchronous else self._finish()
  File "/usr/local/lib/python3.10/site-packages/invoke/runners.py", line 509, in _finish
    raise UnexpectedExit(result)
invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!

Command: "/usr/bin/nodetool -u cassandra -pw 'cassandra'  decommission "

Exit code: -1

Stdout:



Stderr:



```
Since the decommission process in the target node has continued with no issue, the entire longevity failed cmopletely after the nemesis has ended since the target node has remained in `UL` state:
```
2021-12-31 16:23:41.511: (ClusterHealthValidatorEvent Severity.CRITICAL) period_type=one-time event_id=b64b4d85-9fbe-4877-ac3c-5b74a3053454: type=NodeStatus node=longevity-tls-50gb-3d-master-db-node-179db65e-1 error=Current node 10.0.3.97. Node with 10.0.3.203 (GrowShrinkCluster Node longevity-tls-50gb-3d-master-db-node-179db65e-7 [54.247.43.129 | 10.0.0.64] (seed: False) nemesis target node) status is UL
2021-12-31 16:25:37.407: (ClusterHealthValidatorEvent Severity.CRITICAL) period_type=one-time event_id=b91526ac-5d26-4398-b84a-d19d720416a9: type=NodeStatus node=longevity-tls-50gb-3d-master-db-node-179db65e-7 error=Current node 10.0.0.64. Node with 10.0.3.203 (GrowShrinkCluster Node longevity-tls-50gb-3d-master-db-node-179db65e-7 [54.247.43.129 | 10.0.0.64] (seed: False) nemesis target node) status is UL
```

**Comment by fgelcer** [comment]
was there any message in the target node? maybe it crashed?

**Comment by ShlomiBalalis** [comment]
> was there any message in the target node? maybe it crashed?

Nope. From the node's POV, the decommission process continued naturally, which what led me to believe the issue is on sct's side.

**Comment by fgelcer** [comment]
> > was there any message in the target node? maybe it crashed?
> 
> Nope. From the node's POV, the decommission process continued naturally, which what led me to believe the issue is on sct's side.

AFAICT `Exit code = -1` means the running command finished unexpectedly (crashed or was killed)

**Comment by ShlomiBalalis** [comment]
I'm pretty sure it means ssh connection failure?

**Comment by roydahan** [comment]
It's something related to SSH connection failure, but we need to understand where the failure is coming from.
It can be related to fabric or it can be related to kernel issue on the db node side.

**Comment by roydahan** [comment]
I opened related issue in scylla - https://github.com/scylladb/scylla/issues/9901

**Comment by bentsi** [comment]
looks like SSH issue:
```
Bad packet length 3617507228
ssh_dispatch_run_fatal: Connection from user scyllaadm 10.0.1.213 port 46920: message authentication code incorrect
pam_unix(sshd:session): session closed for user scyllaadm
```

not sure  how (maybe it's related) 
there were reactor stalls and empty  "kernel stack messages"

```
Dec 31 16:21:42 longevity-tls-50gb-3d-master-db-node-179db65e-13 scylla[50830]: Reactor stalled for 148 ms on shard 0. Backtrace: 0x40709f2 0x406f6a0 0x4070900 0x7fb6ae5efa1f 0x2c12db3 0x2bc2fa1 0x2b82da7 0x30e7b45 0x30e996a 0x31119a6 0x310eee3 0x42f15a1
...
2021-12-31T16:21:42+00:00 longevity-tls-50gb-3d-master-db-node-179db65e-13 !    INFO | kernel callstack:
2021-12-31T16:21:42+00:00 longevity-tls-50gb-3d-master-db-node-179db65e-13 !    INFO | kernel callstack:
2021-12-31T16:21:42+00:00 longevity-tls-50gb-3d-master-db-node-179db65e-13 !    INFO | kernel callstack:
2021-12-31T16:21:42+00:00 longevity-tls-50gb-3d-master-db-node-179db65e-13 !    INFO |  [shard 0] range_streamer - Unbootstrap starts, nr_ranges_remaining=5823
2021-12-31T16:21:42+00:00 longevity-tls-50gb-3d-master-db-node-179db65e-13 !    INFO |  [shard 0] range_streamer - Unbootstrap with [10.0.1.155, 10.0.3.97, 10.0.0.64, 10.0.2.167, 10.0.3.113, 10.0.3.224] for keyspace=keyspace1 started, nodes_to_stream=6
2021-12-31T16:21:42+00:00 longevity-tls-50gb-3d-master-db-node-179db65e-13 !    INFO |  [shard 0] range_streamer - Unbootstrap with 10.0.1.155 for keyspace=keyspace1, streaming [0, 11) out of 119 ranges
2021-12-31T16:21:42+00:00 longevity-tls-50gb-3d-master-db-node-179db65e-13 !    INFO |  [shard 0] range_streamer - Unbootstrap with 10.0.3.97 for keyspace=keyspace1, streaming [0, 14) out of 147 ranges
2021-12-31T16:21:42+00:00 longevity-tls-50gb-3d-master-db-node-179db65e-13 !    INFO |  [shard 0] range_streamer - Unbootstrap with 10.0.0.64 for keyspace=keyspace1, streaming [0, 11) out of 112 ranges
2021-12-31T16:21:42+00:00 longevity-tls-50gb-3d-master-db-node-179db65e-13 !    INFO |  [shard 0] range_streamer - Unbootstrap with 10.0.2.167 for keyspace=keyspace1, streaming [0, 11) out of 116 ranges
2021-12-31T16:21:42+00:00 longevity-tls-50gb-3d-master-db-node-179db65e-13 !    INFO |  [shard 0] range_streamer - Unbootstrap with 10.0.3.113 for keyspace=keyspace1, streaming [0, 12) out of 126 ranges
2021-12-31T16:21:42+00:00 longevity-tls-50gb-3d-master-db-node-179db65e-13 !    INFO |  [shard 0] range_streamer - Unbootstrap with 10.0.3.224 for keyspace=keyspace1, streaming [0, 13) out of 132 ranges
2021-12-31T16:21:42+00:00 longevity-tls-50gb-3d-master-db-node-179db65e-13 !    INFO | Bad packet length 3617507228.
2021-12-31T16:21:42+00:00 longevity-tls-50gb-3d-master-db-node-179db65e-13 !    INFO | ssh_dispatch_run_fatal: Connection from user scyllaadm 10.0.1.213 port 46920: message authentication code incorrect
2021-12-31T16:21:42+00:00 longevity-tls-50gb-3d-master-db-node-179db65e-13 !    INFO | pam_unix(sshd:session): session closed for user scyllaadm
2021-12-31T16:21:42+00:00 longevity-tls-50gb-3d-master-db-node-179db65e-13 !    INFO | Session 3 logged out. Waiting for processes to exit.
2021-12-31T16:21:43+00:00 longevity-tls-50gb-3d-master-db-node-179db65e-13 !    INFO | {"L":"INFO","T":"2021-12-31T16:21:43.030Z","N":"http","M":"GET /storage_service/host_id","from":"10.0.1.47:53824","status":200,"bytes":496,"duration":"11ms"}
2021-12-31T16:21:43+00:00 longevity-tls-50gb-3d-master-db-node-179db65e-13 !    INFO | {"L":"INFO","T":"2021-12-31T16:21:43.044Z","N":"http","M":"GET /storage_service/nodes/joining","from":"10.0.1.47:53824","status":200,"bytes":2,"duration":"9ms"}
2021-12-31T16:21:46+00:00 longevity-tls-50gb-3d-master-db-node-179db65e-13 !    INFO | Accepted publickey for scyllaadm from 10.0.1.213 port 43448 ssh2: RSA SHA256:1YmYWh7roz4Y3FSY7N8CetmQNlK/K5FeBPITC8KF0u8
2021-12-31T16:21:46+00:00 longevity-tls-50gb-3d-master-db-node-179db65e-13 !    INFO | pam_unix(sshd:session): session opened for user scyllaadm by (uid=0)
2021-12-31T16:21:46+00:00 longevity-tls-50gb-3d-master-db-node-179db65e-13 !    INFO | New session 2096 of user scyllaadm.
2021-12-31T16:21:46+00:00 longevity-tls-50gb-3d-master-db-node-179db65e-13 !    INFO | Started Session 2096 of user scyllaadm.
2021-12-31T16:21:50+00:00 longevity-tls-50gb-3d-master-db-node-179db65e-13 !    INFO | pam_unix(sshd:session): session closed for user scyllaadm
2021-12-31T16:21:50+00:00 longevity-tls-50gb-3d-master-db-node-179db65e-13 !    INFO | session-2096.scope: Succeeded.
2021-12-31T16:21:50+00:00 longevity-tls-50gb-3d-master-db-node-179db65e-13 !    INFO | Session 2096 logged out. Waiting for processes to exit.
2021-12-31T16:21:50+00:00 longevity-tls-50gb-3d-master-db-node-179db65e-13 !    INFO | Removed session 2096.
...
Dec 31 16:21:53 longevity-tls-50gb-3d-master-db-node-179db65e-13 scylla[50830]:  [shard 1] reader_concurrency_semaphore - (rate limiting dropped 29 similar messages) Semaphore _system_read_concurrency_sem with 91/100 count and 16608/171001774 memory resources: timed out, du
mping permit diagnostics:
                                                                                permits        count        memory        table/description/state
                                                                                1        1        16K        system_auth.roles/data-query/active/used
                                                                                15        0        0B        system_distributed.service_levels/shard-reader/waiting
                                                                                178        0        0B        system_auth.roles/data-query/waiting
                                                                                1        0        0B        *.*/view_builder/active/unused
                                                                                
                                                                                195        1        16K        total
                                                                                
                                                                                Total: 195 permits with 1 count and 16K memory resources
Dec 31 16:22:05 longevity-tls-50gb-3d-master-db-node-179db65e-13 scylla[50830]:  [shard 7] compaction - [Compact keyspace1.standard1 cadf29b0-6a55-11ec-ac6c-b547e7802a56] Compacting [/var/lib/scylla/data/keyspace1/standard1-d1528ba069f311ecbc23c585caa62888/md-11459-big-Data

```

**Comment by fgelcer** [comment]
> @fgelcer where do you have more cases of it?

i saw it on `test_id: 0cc17cf2-52e9-4433-ace9-178a589ef120` for `nodetool drain`

**Comment by roydahan** [comment]
I see that others suffer from it: https://github.com/aws/amazon-ssm-agent/issues/274

**Comment by roydahan** [comment]
@fruch I need your skills here.
I think that the issue started around October, but we seeing it a lot lately in many longevities (see also the scylla issue).

**Comment by fruch** [comment]
@bentsi, seem like it's happening only when fabric is used... is there a specific reason why we didn't moved everything to work with libssh2 ?

**Comment by roydahan** [comment]
Are there cases we use fabric and cases we use libssh2?

**Comment by fruch** [comment]
> Are there cases we use fabric and cases we use libssh2?

Yes, fabric is the default. and only a handful of yamls are using libssh2

The -1 in here is coming from fabric code, in case there wasn't able to get return code, mostly when connection disconnects.

**Comment by roydahan** [comment]
Let's change remote commands (at least nodetool) to use libssh2.
I want a limited fix, not a full refactor so we can backport safely.

**Comment by fruch** [comment]
> Let's change remote commands (at least nodetool) to use libssh2. I want a limited fix, not a full refactor so we can backport safely.

I don't think it would be a refactor, changing the default `ssh_transport`.
Changing only nodetool to a different remote, is a bigger change.

**Comment by roydahan** [comment]
ok, send a PR and we will get @bentsi and others to comment why wasn't it changed till now.
