### ISSUE TITLE
sed: can't read /etc/syslog-ng/syslog-ng.conf: No such file or directory

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylla-cluster-tests#4308]
test is [rolling upgrade](https://jenkins.scylladb.com/view/scylla-4.6/job/scylla-4.6/job/rolling-upgrade/view/test/job/rolling-upgrade-ubuntu18.04-test/11/)

the failure is:
```
14:43:51  Command: 'sudo bash -cxe \'\nsource_name=`cat /etc/syslog-ng/syslog-ng.conf | tr -d "\\n" | tr -d "\\r" | sed -r "s/\\};/\\};\\n/g;         s/source /\\nsource /g" | grep -P "^source.*system\\(\\)" | cut -d" " -f2`\ndisk_buffer_option=""\nif syslog-ng -V | grep disk; then\n    disk_buffer_option="disk-buffer(\n            mem-buf-size(100000)\n            disk-buf-size(2000000)\n            reliable(yes)\n            dir(\\"/tmp\\")\n        )"\nfi\n\nif grep -P "keep-timestamp\\([^)]+\\)" /etc/syslog-ng/syslog-ng.conf; then\n    sed -i -r "s/keep-timestamp([ ]*yes[ ]*)/keep-timestamp(no)/g" /etc/syslog-ng/syslog-ng.conf\nelse\n    sed -i -r "s/([ \t]*options[ \t]*\\\\{)/\\\\1\\n  keep-timestamp(no);\\n/g" /etc/syslog-ng/syslog-ng.conf\nfi\n\ngrep "destination remote_sct" /etc/syslog-ng/syslog-ng.conf || cat <<EOF >>/etc/syslog-ng/syslog-ng.conf\ndestination remote_sct {\n    network(\n        "10.142.0.44"\n        transport("tcp")\n        port(49153)\n        throttle(10000)\n        $disk_buffer_option\n    );\n};\n\ndestination d_system { file("/var/log/system.log"); };\nlog { source($source_name); destination(d_system); };\n\nEOF\n\nif ! grep -P "log {.*destination\\\\(remote_sct\\\\)" /etc/syslog-ng/syslog-ng.conf; then\n    echo "log { source($source_name); destination(remote_sct); };" >> /etc/syslog-ng/syslog-ng.conf\nfi\n\nif [ ! -z "rolling-upgrade-4-6-ubuntu-bionic-db-node-ee8fa9fb-0-4" ]; then\n    if grep "rewrite r_host" /etc/syslog-ng/syslog-ng.conf; then\n        sed -i -r "s/rewrite r_host \\{ set\\(\\"[^\\"]+\\"/rewrite r_host { set(\\"rolling-upgrade-4-6-ubuntu-bionic-db-node-ee8fa9fb-0-4\\"/" /etc/syslog-ng/syslog-ng.conf\n    else\n        echo "rewrite r_host { set(\\"rolling-upgrade-4-6-ubuntu-bionic-db-node-ee8fa9fb-0-4\\", value(\\"HOST\\")); };" >>  /etc/syslog-ng/syslog-ng.conf\n        sed -i -r "s/destination\\(remote_sct\\);[ \\t]*\\};/destination\\(remote_sct\\); rewrite\\(r_host\\); \\};/" /etc/syslog-ng/syslog-ng.conf\n    fi\nfi\nsystemctl restart syslog-ng\n\''
14:43:51  
14:43:51  Exit code: 2
14:43:51  
14:43:51  Stdout:
14:43:51  
14:43:51  Available-Modules: xml,affile,map-value-pairs,afstomp,cryptofuncs,date,kvformat,graphite,appmodel,afuser,tags-parser,syslogformat,afamqp,dbparser,basicfuncs,system-source,tfgetent,afsql,confgen,cef,add-contextual-data,riemann,csvparser,mod-python,disk-buffer,pseudofile,afprog,afsmtp,stardate,linux-kmsg-format,afmongodb,snmptrapd-parser,sdjournal,json-plugin,afsocket,redis,geoip-plugin
14:43:51  
14:43:51  Stderr:
14:43:51  
14:43:51  + disk_buffer_option='disk-buffer(
14:43:51              mem-buf-size(100000)
14:43:51              disk-buf-size(2000000)
14:43:51              reliable(yes)
14:43:51              dir("/tmp")
14:43:51          )'
14:43:51  + grep -P 'keep-timestamp\([^)]+\)' /etc/syslog-ng/syslog-ng.conf
14:43:51  grep: /etc/syslog-ng/syslog-ng.conf: No such file or directory
14:43:51  + sed -i -r 's/([ 	]*options[ 	]*\{)/\1\n  keep-timestamp(no);\n/g' /etc/syslog-ng/syslog-ng.conf
14:43:51  sed: can't read /etc/syslog-ng/syslog-ng.conf: No such file or directory
14:43:51  
14:43:51  
14:43:51  
14:43:51  The above exception was the direct cause of the following exception:
14:43:51  
14:43:51  Traceback (most recent call last):
14:43:51    File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 130, in wrapper
14:43:51      return method(*args, **kwargs)
14:43:51    File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 113, in inner
14:43:51      res = func(*args, **kwargs)
14:43:51    File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 604, in setUp
14:43:51      self.init_resources()
14:43:51    File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 1335, in init_resources
14:43:51      self.get_cluster_gce(loader_info=loader_info, db_info=db_info,
14:43:51    File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 799, in get_cluster_gce
14:43:51      self.db_cluster = ScyllaGCECluster(gce_image=gce_image_db,
14:43:51    File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster_gce.py", line 482, in __init__
14:43:51      super().__init__(
14:43:51    File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3487, in __init__
14:43:51      super().__init__(*args, **kwargs)
14:43:51    File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster_gce.py", line 227, in __init__
14:43:51      super().__init__(cluster_uuid=cluster_uuid,
14:43:51    File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3004, in __init__
14:43:51      self.add_nodes(num, dc_idx=dc_idx, enable_auto_bootstrap=self.auto_bootstrap)
14:43:51    File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster_gce.py", line 461, in add_nodes
14:43:51      node = self._create_node(instance, node_index, dc_idx)
14:43:51    File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster_gce.py", line 442, in _create_node
14:43:51      raise CreateGCENodeError('Failed to create node: %s' % ex) from ex
14:43:51  sdcm.cluster_gce.CreateGCENodeError: Failed to create node: Encountered a bad command exit code!
14:43:51  
14:43:51  Command: 'sudo bash -cxe \'\nsource_name=`cat /etc/syslog-ng/syslog-ng.conf | tr -d "\\n" | tr -d "\\r" | sed -r "s/\\};/\\};\\n/g;         s/source /\\nsource /g" | grep -P "^source.*system\\(\\)" | cut -d" " -f2`\ndisk_buffer_option=""\nif syslog-ng -V | grep disk; then\n    disk_buffer_option="disk-buffer(\n            mem-buf-size(100000)\n            disk-buf-size(2000000)\n            reliable(yes)\n            dir(\\"/tmp\\")\n        )"\nfi\n\nif grep -P "keep-timestamp\\([^)]+\\)" /etc/syslog-ng/syslog-ng.conf; then\n    sed -i -r "s/keep-timestamp([ ]*yes[ ]*)/keep-timestamp(no)/g" /etc/syslog-ng/syslog-ng.conf\nelse\n    sed -i -r "s/([ \t]*options[ \t]*\\\\{)/\\\\1\\n  keep-timestamp(no);\\n/g" /etc/syslog-ng/syslog-ng.conf\nfi\n\ngrep "destination remote_sct" /etc/syslog-ng/syslog-ng.conf || cat <<EOF >>/etc/syslog-ng/syslog-ng.conf\ndestination remote_sct {\n    network(\n        "10.142.0.44"\n        transport("tcp")\n        port(49153)\n        throttle(10000)\n        $disk_buffer_option\n    );\n};\n\ndestination d_system { file("/var/log/system.log"); };\nlog { source($source_name); destination(d_system); };\n\nEOF\n\nif ! grep -P "log {.*destination\\\\(remote_sct\\\\)" /etc/syslog-ng/syslog-ng.conf; then\n    echo "log { source($source_name); destination(remote_sct); };" >> /etc/syslog-ng/syslog-ng.conf\nfi\n\nif [ ! -z "rolling-upgrade-4-6-ubuntu-bionic-db-node-ee8fa9fb-0-4" ]; then\n    if grep "rewrite r_host" /etc/syslog-ng/syslog-ng.conf; then\n        sed -i -r "s/rewrite r_host \\{ set\\(\\"[^\\"]+\\"/rewrite r_host { set(\\"rolling-upgrade-4-6-ubuntu-bionic-db-node-ee8fa9fb-0-4\\"/" /etc/syslog-ng/syslog-ng.conf\n    else\n        echo "rewrite r_host { set(\\"rolling-upgrade-4-6-ubuntu-bionic-db-node-ee8fa9fb-0-4\\", value(\\"HOST\\")); };" >>  /etc/syslog-ng/syslog-ng.conf\n        sed -i -r "s/destination\\(remote_sct\\);[ \\t]*\\};/destination\\(remote_sct\\); rewrite\\(r_host\\); \\};/" /etc/syslog-ng/syslog-ng.conf\n    fi\nfi\nsystemctl restart syslog-ng\n\''
14:43:51  
14:43:51  Exit code: 2
14:43:51  
14:43:51  Stdout:
14:43:51  
14:43:51  Available-Modules: xml,affile,map-value-pairs,afstomp,cryptofuncs,date,kvformat,graphite,appmodel,afuser,tags-parser,syslogformat,afamqp,dbparser,basicfuncs,system-source,tfgetent,afsql,confgen,cef,add-contextual-data,riemann,csvparser,mod-python,disk-buffer,pseudofile,afprog,afsmtp,stardate,linux-kmsg-format,afmongodb,snmptrapd-parser,sdjournal,json-plugin,afsocket,redis,geoip-plugin
14:43:51  
14:43:51  Stderr:
14:43:51  
14:43:51  + disk_buffer_option='disk-buffer(
14:43:51              mem-buf-size(100000)
14:43:51              disk-buf-size(2000000)
14:43:51              reliable(yes)
14:43:51              dir("/tmp")
14:43:51          )'
14:43:51  + grep -P 'keep-timestamp\([^)]+\)' /etc/syslog-ng/syslog-ng.conf
14:43:51  grep: /etc/syslog-ng/syslog-ng.conf: No such file or directory
14:43:51  + sed -i -r 's/([ 	]*options[ 	]*\{)/\1\n  keep-timestamp(no);\n/g' /etc/syslog-ng/syslog-ng.conf
14:43:51  sed: can't read /etc/syslog-ng/syslog-ng.conf: No such file or directory
14:43:51  
14:43:51  
14:43:51  
14:43:51  ----------------------------------------------------------------------
14:43:51  Ran 1 test in 199.677s
14:43:51  
14:43:51  FAILED (errors=2)
14:43:51  Cleaning SSH agent
14:43:52  Agent pid 26303 killed
```

**Comment by dkropachev** [comment]
Fixed by https://github.com/scylladb/scylla-cluster-tests/pull/4281
