### ISSUE TITLE
The nemesis of delete-range-in-few-partitions fails: "object index out of range"

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#4320]
error:
```
(DisruptionEvent Severity.ERROR) period_type=end event_id=667528ea-d2aa-4222-8d1d-5f005b245cdd duration=13s: nemesis_name=DeleteByRowsRange target_node=Node longevity-large-partitions-200k-pks-db-node-267923ae-3 [3.251.86.162 | 10.0.0.33] (seed: False) errors=range object index out of range
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3080, in wrapper
result = method(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1644, in disrupt_delete_by_rows_range
self.delete_range_in_few_partitions(ks_cf, partitions_for_exclude)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1609, in delete_range_in_few_partitions
queries.append(f"delete from {ks_cf} where pk = {pkey} and ck >= {clustering_keys[0]} "
IndexError: range object index out of range
```

it might be related to merged reversed-queries PR and may be changed by the mergin of open PR: https://github.com/scylladb/scylla-cluster-tests/pull/4274

Test is running in:
https://jenkins.scylladb.com/view/scylla-4.6/job/scylla-4.6/job/longevity/view/Long%20Longevities/job/longevity-large-partition-200k-pks-4days-test/5/

**Comment by fgelcer** [comment]
why would `clustering_keys` be an empty string?
