### ISSUE TITLE
SisyphusMonkey failing in long run - `IndexError: pop from empty list`

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylla-cluster-tests#4333]
*Installation details*
Kernel version: `5.4.0-1035-aws`
Scylla version (or git commit hash): `4.6.rc2-0.20220102.e8a1cfb6f with build-id 5d7b96e39c909424e8224207a162fc2c82b67214`
Cluster size: 6 nodes (i3.2xlarge)
Scylla running with shards number (live nodes):
   longevity-200gb-48h-network-4-6-db-node-2a9bb634-1 (63.35.146.122 | 10.0.3.69): 8 shards
   longevity-200gb-48h-network-4-6-db-node-2a9bb634-2 (18.203.86.153 | 10.0.3.235): 8 shards
   longevity-200gb-48h-network-4-6-db-node-2a9bb634-3 (52.51.152.223 | 10.0.1.158): 8 shards
   longevity-200gb-48h-network-4-6-db-node-2a9bb634-4 (52.208.176.176 | 10.0.0.55): 8 shards
   longevity-200gb-48h-network-4-6-db-node-2a9bb634-5 (63.35.77.2 | 10.0.2.121): 8 shards
   longevity-200gb-48h-network-4-6-db-node-2a9bb634-6 (18.200.192.236 | 10.0.1.129): 8 shards
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-07d92096e7ab05aae` (aws: eu-west-1)

Test: `longevity-200gb-48h-network-monkey-test`
Test name: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):
- [longevity-200GB-48h-network-monkey.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/2c3e4506cee8b75c0f4e89b0aefb9f335c52d6dd/test-cases/longevity/longevity-200GB-48h-network-monkey.yaml)

**Issue description**

during the test, we had an exception for the nemesis:
```
2022-01-14 01:07:34.170: (ThreadFailedEvent Severity.ERROR) period_type=one-time event_id=64d95a9b-bf68-486e-ade1-e16a1e9288b4: message=pop from empty list
Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/sct_events/decorators.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 307, in run
    self.disrupt()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4031, in disrupt
    self.call_next_nemesis()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1256, in call_next_nemesis
    self.execute_disrupt_method(disrupt_method=self.disruptions_list.pop())
IndexError: pop from empty list
```

this is the full list of nemesis:
```
2022-01-13 16:24:07.030: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=6424c5c4-c1d7-45dc-b878-70e021c77300: nemesis_name=NetworkRejectThrift target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-2 [18.203.86.153 | 10.0.3.235] (seed: False)
2022-01-13 16:26:07.755: (DisruptionEvent Severity.NORMAL) period_type=end event_id=6424c5c4-c1d7-45dc-b878-70e021c77300 duration=2m0s: nemesis_name=NetworkRejectThrift target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-2 [18.203.86.153 | 10.0.3.235] (seed: F
alse)
2022-01-13 16:43:43.403: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=4885d70d-11b1-4551-9e84-968bd74d678b: nemesis_name=NetworkRandomInterruptions target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-6 [18.200.192.236 | 10.0.1.129] (seed: False
)
2022-01-13 16:47:25.859: (DisruptionEvent Severity.NORMAL) period_type=end event_id=4885d70d-11b1-4551-9e84-968bd74d678b duration=3m42s: nemesis_name=NetworkRandomInterruptions target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-6 [18.200.192.236 | 10.0.1.129]
 (seed: False)
2022-01-13 17:02:51.909: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=3535f448-785f-4801-b0c1-578bfb2f0815: nemesis_name=NetworkRejectThrift target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-3 [52.51.152.223 | 10.0.1.158] (seed: False)
2022-01-13 17:04:52.532: (DisruptionEvent Severity.NORMAL) period_type=end event_id=3535f448-785f-4801-b0c1-578bfb2f0815 duration=2m0s: nemesis_name=NetworkRejectThrift target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-3 [52.51.152.223 | 10.0.1.158] (seed: F
alse)
2022-01-13 17:19:12.360: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=6c5b3f56-32be-49af-b68f-586363c7e58d: nemesis_name=NetworkRandomInterruptions target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-5 [63.35.77.2 | 10.0.2.121] (seed: False)
2022-01-13 17:25:36.171: (DisruptionEvent Severity.NORMAL) period_type=end event_id=6c5b3f56-32be-49af-b68f-586363c7e58d duration=6m23s: nemesis_name=NetworkRandomInterruptions target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-5 [63.35.77.2 | 10.0.2.121] (se
ed: False)
2022-01-13 17:39:17.764: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=8bbf6643-f335-4c5a-b427-f6b67434eb58: nemesis_name=NetworkStartStopInterface target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-3 [52.51.152.223 | 10.0.1.158] (seed: False)
2022-01-13 17:42:16.540: (DisruptionEvent Severity.NORMAL) period_type=end event_id=8bbf6643-f335-4c5a-b427-f6b67434eb58 duration=2m58s: nemesis_name=NetworkStartStopInterface target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-3 [52.51.152.223 | 10.0.1.158] (seed: False)
2022-01-13 17:56:05.807: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=0ab67b3f-cc28-419f-aa38-a9f988b8ec0f: nemesis_name=NetworkBlock target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-2 [18.203.86.153 | 10.0.3.235] (seed: False)
2022-01-13 17:58:50.451: (DisruptionEvent Severity.NORMAL) period_type=end event_id=0ab67b3f-cc28-419f-aa38-a9f988b8ec0f duration=2m44s: nemesis_name=NetworkBlock target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-2 [18.203.86.153 | 10.0.3.235] (seed: False)
2022-01-13 18:12:24.321: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=84512fe9-027a-4c41-9549-20cd6ef8ca98: nemesis_name=NetworkStartStopInterface target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-6 [18.200.192.236 | 10.0.1.129] (seed: False)
2022-01-13 18:13:52.956: (DisruptionEvent Severity.NORMAL) period_type=end event_id=84512fe9-027a-4c41-9549-20cd6ef8ca98 duration=1m28s: nemesis_name=NetworkStartStopInterface target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-6 [18.200.192.236 | 10.0.1.129] (seed: False)
2022-01-13 18:27:20.077: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=dc73bbfb-cd34-442a-98c5-dd6a7b41b066: nemesis_name=NetworkRejectNodeExporter target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-5 [63.35.77.2 | 10.0.2.121] (seed: False)
2022-01-13 18:35:40.529: (DisruptionEvent Severity.NORMAL) period_type=end event_id=dc73bbfb-cd34-442a-98c5-dd6a7b41b066 duration=8m20s: nemesis_name=NetworkRejectNodeExporter target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-5 [63.35.77.2 | 10.0.2.121] (seed: False)
2022-01-13 18:49:26.388: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=b9063f09-7fb1-45fa-8781-582d62b922e4: nemesis_name=NetworkRandomInterruptions target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-3 [52.51.152.223 | 10.0.1.158] (seed: False)
2022-01-13 18:52:51.121: (DisruptionEvent Severity.NORMAL) period_type=end event_id=b9063f09-7fb1-45fa-8781-582d62b922e4 duration=3m24s: nemesis_name=NetworkRandomInterruptions target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-3 [52.51.152.223 | 10.0.1.158] (seed: False)
2022-01-13 19:06:35.562: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=2586eabc-1857-4989-a4df-253c158e9838: nemesis_name=NetworkRejectNodeExporter target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-5 [63.35.77.2 | 10.0.2.121] (seed: False)
2022-01-13 19:07:35.943: (DisruptionEvent Severity.NORMAL) period_type=end event_id=2586eabc-1857-4989-a4df-253c158e9838 duration=1m0s: nemesis_name=NetworkRejectNodeExporter target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-5 [63.35.77.2 | 10.0.2.121] (seed: False)
2022-01-13 19:21:05.626: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=cb2cb37e-4a92-4559-a86c-788605d3aab6: nemesis_name=NetworkStartStopInterface target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-5 [63.35.77.2 | 10.0.2.121] (seed: False)
2022-01-13 19:27:21.174: (DisruptionEvent Severity.NORMAL) period_type=end event_id=cb2cb37e-4a92-4559-a86c-788605d3aab6 duration=6m15s: nemesis_name=NetworkStartStopInterface target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-5 [63.35.77.2 | 10.0.2.121] (seed: False)
2022-01-13 19:40:54.249: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=b9910b50-bd8f-4bdd-b3fa-b40dfd5b0e54: nemesis_name=NetworkBlock target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-4 [52.208.176.176 | 10.0.0.55] (seed: False)
2022-01-13 19:42:57.349: (DisruptionEvent Severity.NORMAL) period_type=end event_id=b9910b50-bd8f-4bdd-b3fa-b40dfd5b0e54 duration=2m3s: nemesis_name=NetworkBlock target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-4 [52.208.176.176 | 10.0.0.55] (seed: False)
2022-01-13 19:56:40.644: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=3ac1c91f-1a2c-4b0d-9395-b7cd4709b289: nemesis_name=NetworkRejectNodeExporter target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-4 [52.208.176.176 | 10.0.0.55] (seed: False)
2022-01-13 19:56:51.052: (DisruptionEvent Severity.NORMAL) period_type=end event_id=3ac1c91f-1a2c-4b0d-9395-b7cd4709b289 duration=10s: nemesis_name=NetworkRejectNodeExporter target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-4 [52.208.176.176 | 10.0.0.55] (seed: False)
2022-01-13 20:10:30.430: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=116024d9-adf0-4fac-830c-0198e2874734: nemesis_name=NetworkRandomInterruptions target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-6 [18.200.192.236 | 10.0.1.129] (seed: False)
2022-01-13 20:20:11.653: (DisruptionEvent Severity.NORMAL) period_type=end event_id=116024d9-adf0-4fac-830c-0198e2874734 duration=9m41s: nemesis_name=NetworkRandomInterruptions target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-6 [18.200.192.236 | 10.0.1.129] (seed: False)
2022-01-13 20:33:59.584: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=8fc7b236-46f4-4f8e-b76d-df388a9e613b: nemesis_name=NetworkStartStopInterface target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-5 [63.35.77.2 | 10.0.2.121] (seed: False)
2022-01-13 20:37:55.618: (DisruptionEvent Severity.NORMAL) period_type=end event_id=8fc7b236-46f4-4f8e-b76d-df388a9e613b duration=3m56s: nemesis_name=NetworkStartStopInterface target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-5 [63.35.77.2 | 10.0.2.121] (seed: False)
2022-01-13 20:51:28.814: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=cd103ce0-32b4-4356-a740-3fcb8e16f091: nemesis_name=NetworkBlock target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-5 [63.35.77.2 | 10.0.2.121] (seed: False)
2022-01-13 20:55:27.428: (DisruptionEvent Severity.NORMAL) period_type=end event_id=cd103ce0-32b4-4356-a740-3fcb8e16f091 duration=3m58s: nemesis_name=NetworkBlock target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-5 [63.35.77.2 | 10.0.2.121] (seed: False)
2022-01-13 21:08:59.944: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=b88c031b-a1b3-4c77-b8e6-7d0d7dff7a02: nemesis_name=NetworkRandomInterruptions target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-5 [63.35.77.2 | 10.0.2.121] (seed: False)
2022-01-13 21:18:46.232: (DisruptionEvent Severity.NORMAL) period_type=end event_id=b88c031b-a1b3-4c77-b8e6-7d0d7dff7a02 duration=9m46s: nemesis_name=NetworkRandomInterruptions target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-5 [63.35.77.2 | 10.0.2.121] (seed: False)
2022-01-13 21:32:19.252: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=556c104d-edf9-4791-ac3b-a10276c59957: nemesis_name=NetworkRejectNodeExporter target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-6 [18.200.192.236 | 10.0.1.129] (seed: False)
2022-01-13 21:33:19.857: (DisruptionEvent Severity.NORMAL) period_type=end event_id=556c104d-edf9-4791-ac3b-a10276c59957 duration=1m0s: nemesis_name=NetworkRejectNodeExporter target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-6 [18.200.192.236 | 10.0.1.129] (seed: False)
2022-01-13 21:46:41.892: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=2d995db9-0a89-4616-a476-90e6260929da: nemesis_name=NetworkRejectThrift target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-2 [18.203.86.153 | 10.0.3.235] (seed: False)
2022-01-13 21:46:52.206: (DisruptionEvent Severity.NORMAL) period_type=end event_id=2d995db9-0a89-4616-a476-90e6260929da duration=10s: nemesis_name=NetworkRejectThrift target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-2 [18.203.86.153 | 10.0.3.235] (seed: False)
2022-01-13 22:00:13.802: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=ff0446cd-7e9e-4185-9700-8a46c975355c: nemesis_name=NetworkRejectNodeExporter target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-3 [52.51.152.223 | 10.0.1.158] (seed: False)
2022-01-13 22:01:14.130: (DisruptionEvent Severity.NORMAL) period_type=end event_id=ff0446cd-7e9e-4185-9700-8a46c975355c duration=1m0s: nemesis_name=NetworkRejectNodeExporter target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-3 [52.51.152.223 | 10.0.1.158] (seed: False)
2022-01-13 22:14:35.008: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=1fad4e1f-c3b1-4146-9844-dfd1bc7ee167: nemesis_name=NetworkRejectThrift target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-3 [52.51.152.223 | 10.0.1.158] (seed: False)
2022-01-13 22:16:35.420: (DisruptionEvent Severity.NORMAL) period_type=end event_id=1fad4e1f-c3b1-4146-9844-dfd1bc7ee167 duration=2m0s: nemesis_name=NetworkRejectThrift target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-3 [52.51.152.223 | 10.0.1.158] (seed: False)
2022-01-13 22:29:57.675: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=cb11ce86-5aa0-4add-bcf1-20843ecc88cd: nemesis_name=NetworkRejectNodeExporter target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-5 [63.35.77.2 | 10.0.2.121] (seed: False)
2022-01-13 22:30:07.991: (DisruptionEvent Severity.NORMAL) period_type=end event_id=cb11ce86-5aa0-4add-bcf1-20843ecc88cd duration=10s: nemesis_name=NetworkRejectNodeExporter target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-5 [63.35.77.2 | 10.0.2.121] (seed: False)
2022-01-13 22:43:37.204: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=d1a05c77-90d6-42aa-9f3f-1f0636ceade3: nemesis_name=NetworkStartStopInterface target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-6 [18.200.192.236 | 10.0.1.129] (seed: False)
2022-01-13 22:47:32.956: (DisruptionEvent Severity.NORMAL) period_type=end event_id=d1a05c77-90d6-42aa-9f3f-1f0636ceade3 duration=3m55s: nemesis_name=NetworkStartStopInterface target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-6 [18.200.192.236 | 10.0.1.129] (seed: False)
2022-01-13 23:01:12.516: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=a1fcfa64-e45f-4520-afa4-f01d25c5766e: nemesis_name=NetworkBlock target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-5 [63.35.77.2 | 10.0.2.121] (seed: False)
2022-01-13 23:02:38.951: (DisruptionEvent Severity.NORMAL) period_type=end event_id=a1fcfa64-e45f-4520-afa4-f01d25c5766e duration=1m26s: nemesis_name=NetworkBlock target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-5 [63.35.77.2 | 10.0.2.121] (seed: False)
2022-01-13 23:16:11.375: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=0d1c85d2-ba4b-4daa-b0a4-67d70ecfadcf: nemesis_name=NetworkBlock target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-4 [52.208.176.176 | 10.0.0.55] (seed: False)
2022-01-13 23:17:47.617: (DisruptionEvent Severity.NORMAL) period_type=end event_id=0d1c85d2-ba4b-4daa-b0a4-67d70ecfadcf duration=1m36s: nemesis_name=NetworkBlock target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-4 [52.208.176.176 | 10.0.0.55] (seed: False)
2022-01-13 23:31:14.461: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=d5b0cc4f-3f20-46c1-bd1f-38eb22488225: nemesis_name=NetworkRandomInterruptions target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-4 [52.208.176.176 | 10.0.0.55] (seed: False)
2022-01-13 23:34:17.759: (DisruptionEvent Severity.NORMAL) period_type=end event_id=d5b0cc4f-3f20-46c1-bd1f-38eb22488225 duration=3m3s: nemesis_name=NetworkRandomInterruptions target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-4 [52.208.176.176 | 10.0.0.55] (seed: False)
2022-01-13 23:47:51.923: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=7305872a-6b24-40e5-8a6d-6c5d75b37827: nemesis_name=NetworkStartStopInterface target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-2 [18.203.86.153 | 10.0.3.235] (seed: False)
2022-01-13 23:54:03.217: (DisruptionEvent Severity.NORMAL) period_type=end event_id=7305872a-6b24-40e5-8a6d-6c5d75b37827 duration=6m11s: nemesis_name=NetworkStartStopInterface target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-2 [18.203.86.153 | 10.0.3.235] (seed: False)
2022-01-14 00:07:27.504: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=62c407f9-6022-452c-89fc-c0eddf8735b1: nemesis_name=NetworkRejectThrift target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-6 [18.200.192.236 | 10.0.1.129] (seed: False)
2022-01-14 00:12:27.905: (DisruptionEvent Severity.NORMAL) period_type=end event_id=62c407f9-6022-452c-89fc-c0eddf8735b1 duration=5m0s: nemesis_name=NetworkRejectThrift target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-6 [18.200.192.236 | 10.0.1.129] (seed: False)
2022-01-14 00:25:52.242: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=b77511f2-e09f-431b-bcc8-924c33717eac: nemesis_name=NetworkBlock target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-2 [18.203.86.153 | 10.0.3.235] (seed: False)
2022-01-14 00:27:30.137: (DisruptionEvent Severity.NORMAL) period_type=end event_id=b77511f2-e09f-431b-bcc8-924c33717eac duration=1m37s: nemesis_name=NetworkBlock target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-2 [18.203.86.153 | 10.0.3.235] (seed: False)
2022-01-14 00:40:55.808: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=74f2a63a-155b-4b87-9e4c-b94ab0f9d0d9: nemesis_name=NetworkRejectThrift target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-3 [52.51.152.223 | 10.0.1.158] (seed: False)
2022-01-14 00:45:56.163: (DisruptionEvent Severity.NORMAL) period_type=end event_id=74f2a63a-155b-4b87-9e4c-b94ab0f9d0d9 duration=5m0s: nemesis_name=NetworkRejectThrift target_node=Node longevity-200gb-48h-network-4-6-db-node-2a9bb634-3 [52.51.152.223 | 10.0.1.158] (seed: False)
```

and since that failure, no more nemesis ran..
test ended several hours after that, but load continued without nemesis:
```
2022-01-15 14:36:29.479: (CassandraStressEvent Severity.NORMAL) period_type=end event_id=20f983f6-da45-46ab-be1f-0b811714d56f duration=1d22h20m22s: node=Node longevity-200gb-48h-network-4-6-loader-node-2a9bb634-1 [54.155.48.191 | 10.0.3.232] (seed: False)
2022-01-15 14:39:49.721: (CassandraStressEvent Severity.NORMAL) period_type=end event_id=3943e250-f6ce-42ae-8293-ab3d9265b37b duration=1d22h20m14s: node=Node longevity-200gb-48h-network-4-6-loader-node-2a9bb634-1 [54.155.48.191 | 10.0.3.232] (seed: False)
2022-01-15 14:39:49.805: (InfoEvent Severity.NORMAL) period_type=not-set event_id=06a20e24-9cd1-408b-85f7-ed8ab853ce96: message=TEST_END
```

Restore Monitor Stack command: `$ hydra investigate show-monitor 2a9bb634-ee64-41dc-a9fb-0d3b4e942466`
Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=2a9bb634-ee64-41dc-a9fb-0d3b4e942466)
Show all stored logs command: `$ hydra investigate show-logs 2a9bb634-ee64-41dc-a9fb-0d3b4e942466`

Test id: `2a9bb634-ee64-41dc-a9fb-0d3b4e942466`

Logs:
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/2a9bb634-ee64-41dc-a9fb-0d3b4e942466/20220115_144009/grafana-screenshot-longevity-200gb-48h-network-monkey-test-scylla-per-server-metrics-nemesis-20220115_144240-longevity-200gb-48h-network-4-6-monitor-node-2a9bb634-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/2a9bb634-ee64-41dc-a9fb-0d3b4e942466/20220115_144009/grafana-screenshot-longevity-200gb-48h-network-monkey-test-scylla-per-server-metrics-nemesis-20220115_144240-longevity-200gb-48h-network-4-6-monitor-node-2a9bb634-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/2a9bb634-ee64-41dc-a9fb-0d3b4e942466/20220115_144009/grafana-screenshot-overview-20220115_144009-longevity-200gb-48h-network-4-6-monitor-node-2a9bb634-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/2a9bb634-ee64-41dc-a9fb-0d3b4e942466/20220115_144009/grafana-screenshot-overview-20220115_144009-longevity-200gb-48h-network-4-6-monitor-node-2a9bb634-1.png)
db-cluster - [https://cloudius-jenkins-test.s3.amazonaws.com/2a9bb634-ee64-41dc-a9fb-0d3b4e942466/20220115_155445/db-cluster-2a9bb634.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2a9bb634-ee64-41dc-a9fb-0d3b4e942466/20220115_155445/db-cluster-2a9bb634.tar.gz)
loader-set - [https://cloudius-jenkins-test.s3.amazonaws.com/2a9bb634-ee64-41dc-a9fb-0d3b4e942466/20220115_155445/loader-set-2a9bb634.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2a9bb634-ee64-41dc-a9fb-0d3b4e942466/20220115_155445/loader-set-2a9bb634.tar.gz)
monitor-set - [https://cloudius-jenkins-test.s3.amazonaws.com/2a9bb634-ee64-41dc-a9fb-0d3b4e942466/20220115_155445/monitor-set-2a9bb634.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2a9bb634-ee64-41dc-a9fb-0d3b4e942466/20220115_155445/monitor-set-2a9bb634.tar.gz)
sct - [https://cloudius-jenkins-test.s3.amazonaws.com/2a9bb634-ee64-41dc-a9fb-0d3b4e942466/20220115_155445/sct-runner-2a9bb634.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2a9bb634-ee64-41dc-a9fb-0d3b4e942466/20220115_155445/sct-runner-2a9bb634.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-4.6/job/longevity/job/longevity-200gb-48h-network-monkey-test/3/)

**Comment by fruch** [comment]
`disruptions_list` should be a cycle 
```python
disruptions_list = itertools.cycle(disruptions_list)
...
self.execute_disrupt_method(disrupt_method=next(self.disruptions_list)) # instead of pop
```

**Comment by roydahan** [comment]
Did the stack of nemesis really was empty?
Need to check the log.

**Comment by fgelcer** [comment]
> Did the stack of nemesis really was empty? Need to check the log.

it is a job that is filtering nemesis with `nemesis_include_filter: ['networking']`, so probably it did multiple cycles (it is supposed to be a 48h job)...
logs are attached

**Comment by fruch** [comment]
`is not None` doesn't cover empty lists, i.e. the logic here should be `if self.disruptions_list`

```python 
        if self.disruptions_list is not None:
            self.execute_disrupt_method(disrupt_method=self.disruptions_list.pop())
            self.log.info(f'Remaining nemesis to execute {self.disruptions_list}')
        else:
            self.log.info('Nemesis stack is empty - setting termination_event')
            self.termination_event.set()
````

**Comment by roydahan** [comment]
We probably also need to add here a higher multiply factor.

**Comment by roydahan** [comment]
> `is not None` doesn't cover empty lists, i.e. the logic here should be `if self.disruptions_list`
> 
> ```python
>         if self.disruptions_list is not None:
>             self.execute_disrupt_method(disrupt_method=self.disruptions_list.pop())
>             self.log.info(f'Remaining nemesis to execute {self.disruptions_list}')
>         else:
>             self.log.info('Nemesis stack is empty - setting termination_event')
>             self.termination_event.set()
> ```

Yes, already saw it.
