### ISSUE TITLE
Jepsen run on master ends up with 'Repository content has invalid line'

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla-cluster-tests#4362]
https://jenkins.scylladb.com/view/master/job/scylla-master/job/jepsen/job/jepsen-test-all/85/execution/node/110/log/

```
13:11:56  Traceback (most recent call last):
13:11:56  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3424, in node_setup
13:11:56  cl_inst.node_setup(_node, **setup_kwargs)
13:11:56  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 4528, in node_setup
13:11:56  node.download_scylla_repo(scylla_repo_loader)
13:11:56  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 64, in inner
13:11:56  return func(*args, **kwargs)
13:11:56  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 1727, in download_scylla_repo
13:11:56  verify_scylla_repo_file(result.stdout, is_rhel_like=False)
13:11:56  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 168, in verify_scylla_repo_file
13:11:56  assert valid_prefix, 'Repository content has invalid line: {}'.format(line)
13:11:56  AssertionError: Repository content has invalid line: [scylladb-4.6]
```

**Comment by roydahan** [comment]
Isn't it a releng issue?

**Comment by bentsi** [comment]
not sure, it happens when setting up loader node. Evgeniy will check it
