### ISSUE TITLE
scylla-bench installation fails on K8S: unzip: command not found

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-cluster-tests#4374]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master
* **scylla**: any

### Logs
* test_id: 194782b7-912f-49e2-aebd-ab026ccb4fb0
* job log: https://jenkins.scylladb.com/view/scylla-operator/job/scylla-operator/job/operator-1.7/job/eks/job/longevity-scylla-operator-twcs-48h/2

### Description

If we runt any CI job on K8S that is configured to use "scylla-bench" kind of a loader then we get following error:

```
> Error executing command: "bash -cxe "rm -rf /usr/local/go || true                                 
> rm -rf /tmp/sb_install || true                                                                    
> mkdir /tmp/sb_install                                                                             
> cd /tmp/sb_install                                                                                
> curl -Lo go.tar.gz https://storage.googleapis.com/golang/go1.17.4.linux-amd64.tar.gz              
> tar -C /usr/local -xvzf go.tar.gz                                                                 
> echo 'export GOPATH=$HOME/go' >> $HOME/.bash_profile                                              
> echo 'export PATH=$PATH:/usr/local/go/bin' >> $HOME/.bash_profile                                 
> source $HOME/.bash_profile                                                                        
> curl -Lo sb.zip https://github.com/scylladb/scylla-bench/archive/refs/tags/v0.1.6.zip             
> unzip sb.zip                                                                                      
> cd ./scylla-bench-*                                                                               
> GO111MODULE=on go install .                                                                       
> ""; Exit status: 127                                                                              
                                                                                                    
<lots of the same attempts>                                                                         
                                                                                                    
> Error executing command: "bash -cxe "rm -rf /usr/local/go || true                                 
> rm -rf /tmp/sb_install || true                                                                    
> mkdir /tmp/sb_install                                                                             
> cd /tmp/sb_install                                                                                   
> curl -Lo go.tar.gz https://storage.googleapis.com/golang/go1.17.4.linux-amd64.tar.gz                 
> tar -C /usr/local -xvzf go.tar.gz                                                                    
> echo 'export GOPATH=$HOME/go' >> $HOME/.bash_profile                                                 
> echo 'export PATH=$PATH:/usr/local/go/bin' >> $HOME/.bash_profile                                    
> source $HOME/.bash_profile                                                                           
> curl -Lo sb.zip https://github.com/scylladb/scylla-bench/archive/refs/tags/v0.1.6.zip                
> unzip sb.zip                                                                                         
> cd ./scylla-bench-*                                                                                  
> GO111MODULE=on go install .                                                                          
> ""; Exit status: 127                                                                                 
 > 'install_scylla_bench': Number of retries exceeded!                                                 
> Exception in setUp. Will call tearDown < t:2022-01-24 13:24:22,543 f:tester.py       l:137  c:sdcm.tester          p:ERROR > Exception in setUp. Will call tearDown
> Traceback (most recent call last):                                                                   
>   File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 130, in wrapper                      
>     return method(*args, **kwargs)                                                                   
>   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 113, in inner              
>     res = func(*args, **kwargs)                                                                      
>   File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 629, in setUp                        
>     self.loaders.wait_for_init(db_node_address=db_node_address)                                      
>   File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3472, in wrapper                    
>     verify_node_setup(start_time)                                                                    
>   File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3435, in verify_node_setup          
>     raise NodeSetupFailed(node=node, error_msg=setup_exception[0], traceback_str=setup_exception[1])
> sdcm.cluster.NodeSetupFailed: [Node sct-loaders-2 [10.0.2.63 | 10.0.2.63] (seed: False)] NodeSetupFailed: Encountered a bad command exit code!
>                                                                                                      
> Command: 'bash -cxe "rm -rf /usr/local/go || true\nrm -rf /tmp/sb_install || true\nmkdir /tmp/sb_install\ncd /tmp/sb_install\ncurl -Lo go.tar.gz https://storage.googleapis.com/golang/go1.17.4.linux-amd64.tar.gz\ntar -C /usr/local -xvzf go.tar.gz\necho \'export GOPATH=$HOME/go\' >> $HOME/.bash_profile\necho \'export PATH=$PATH:/usr/local/go/bin\' >> $HOME/.bash_profile\nsource $HOME/.bash_profile\ncurl -Lo sb.zip https://github.com/scylladb/scylla-bench/archive/refs/tags/v0.1.6.zip\nunzip sb.zip\ncd ./scylla-bench-*\nGO111MODULE=on go install .\n"'
>                                                                                                      
> Exit code: 127                                                                                       
>                                                                                                      
> Stdout:                                                                                              
>                                                                                                      
> go/test/interface/private.go                                                                         
> go/test/interface/receiver.go                                                                        
> go/test/interface/receiver1.go                                                                       
> go/test/interface/recursive.go                                                                    
> go/test/interface/recursive1.dir/                                                                 
> go/test/interface/recursive1.dir/recursive1.go                                                    
> go/test/interface/recursive1.dir/recursive2.go                                                    
> go/test/interface/recursive1.go                                                                   
> go/test/interface/returntype.go                                                                   
> go/test/interface/struct.go                                                                       
>                                                                                                   
> Stderr:                                                                                           
>                                                                                                   
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current                   
>                                  Dload  Upload   Total   Spent    Left  Speed                     
>                                                                                                   
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0                    
> 100   136  100   136    0     0    661      0 --:--:-- --:--:-- --:--:--   663                    
>                                                                                                   
>  44 31987   44 14212    0     0  35611      0 --:--:-- --:--:-- --:--:-- 35611                    
> 100 31987  100 31987    0     0  80087      0 --:--:-- --:--:-- --:--:-- 16.9M                    
> + unzip sb.zip                                                                                    
> bash: line 10: unzip: command not found
```

### Steps to Reproduce

1. Try to run any test using "scylla-bench" loader on K8S
2. See error

**Expected behavior:** Scylla-bench installation should not fail

**Actual behavior:** "unzip" package not found.

**Comment by vponomaryov** [comment]
After installation of the missing package, it fails with the following error:

```
2022-01-25 14:54:38.476: (ScyllaBenchEvent Severity.CRITICAL) period_type=end event_id=d87843af-98c4-4c53-9bee-fc021e8406e3 duration=5s: node=Node sct-loaders-0 [10.0.1.60 | 10.0.1.60] (seed: False)
stress_cmd=scylla-bench -workload=timeseries -mode=write -replication-factor=3 -partition-count=400 -clustering-row-count=10000000 -clustering-row-size=200 -concurrency=100 -rows-per-request=100 -start-timestamp=SET_WRITE_TIMESTAMP -connection-count 100 -max-rate 50000 --timeout 120s -duration=2880m -error-at-row-limit 1000
errors:
Stress command completed with bad status 137:
```

CI job link: https://jenkins.scylladb.com/view/scylla-operator/job/scylla-operator/job/operator-1.7/job/eks/job/longevity-scylla-operator-twcs-48h/3

**Comment by dkropachev** [comment]
Fixed at https://github.com/scylladb/scylla-cluster-tests/pull/4379
