### ISSUE TITLE
nemesis stuck due to issue in session.execute_async

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla-cluster-tests#4417]
### Prerequisites

* [x] Are you rebased to master ?
* [ ] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: branch-4.6/master
* **scylla**: 4.6.rc4

### Logs
* test_id: [look for 'the Test ID' at the end of the log]
* job log: https://cloudius-jenkins-test.s3.amazonaws.com/68d5f270-2035-45a2-8583-209c433eb8ca/20220204_172639/sct-runner-68d5f270.tar.gz 

### Description
During mentioned job, SnapshotOperation nemesis was started. In step def _few_tables(), after log.info was printed, next methods was executed:
cluster.get_non_system_ks_cf_list -> get_non_system_ks_cf_list -> get_any_ks_cf_list.

```
            session.default_fetch_size = 1000
            session.default_consistency_level = ConsistencyLevel.ONE
            execute_result = session.execute_async(cmd)
            fetcher = PageFetcher(execute_result).request_all()
            current_rows = fetcher.all_data()
```
code try to get list of tables in async mode. But during jobs some issue happened in async call:
```
< t:2022-02-02 10:26:16,997 f:asyncorereactor.py l:375  c:cassandra.io.asyncorereactor p:DEBUG > Closing connection (139853616974000) to 10.0.0.39:9042
< t:2022-02-02 10:26:16,997 f:asyncorereactor.py l:382  c:cassandra.io.asyncorereactor p:DEBUG > Closed socket to 10.0.0.39:9042
< t:2022-02-02 10:26:16,997 f:cluster.py      l:3206 c:cassandra.cluster    p:WARNING > [control connection] Error connecting to 10.0.0.39:9042: < t:2022-02-02 10:26:16,997 f:cluster.py      l:3206 c:cassandra.cluster    p:WARNING > [control connection] Error connecting to 10.0.0.39:9042:
< t:2022-02-02 10:26:16,997 f:cluster.py      l:3206 c:cassandra.cluster    p:WARNING > Traceback (most recent call last):
< t:2022-02-02 10:26:16,997 f:cluster.py      l:3206 c:cassandra.cluster    p:WARNING >   File "cassandra/cluster.py", line 3531, in cassandra.cluster.ControlConnection._reconnect_internal
< t:2022-02-02 10:26:16,997 f:cluster.py      l:3206 c:cassandra.cluster    p:WARNING >   File "cassandra/cluster.py", line 3600, in cassandra.cluster.ControlConnection._try_connect
< t:2022-02-02 10:26:16,997 f:cluster.py      l:3206 c:cassandra.cluster    p:WARNING >   File "cassandra/cluster.py", line 3592, in cassandra.cluster.ControlConnection._try_connect
< t:2022-02-02 10:26:16,997 f:cluster.py      l:3206 c:cassandra.cluster    p:WARNING >   File "cassandra/connection.py", line 963, in cassandra.connection.Connection.wait_for_response
< t:2022-02-02 10:26:16,997 f:cluster.py      l:3206 c:cassandra.cluster    p:WARNING >   File "cassandra/connection.py", line 1007, in cassandra.connection.Connection.wait_for_responses
< t:2022-02-02 10:26:16,997 f:cluster.py      l:3206 c:cassandra.cluster    p:WARNING >   File "cassandra/connection.py", line 1005, in cassandra.connection.Connection.wait_for_responses
< t:2022-02-02 10:26:16,997 f:cluster.py      l:3206 c:cassandra.cluster    p:WARNING >   File "cassandra/connection.py", line 1469, in cassandra.connection.ResponseWaiter.deliver
< t:2022-02-02 10:26:16,997 f:cluster.py      l:3206 c:cassandra.cluster    p:WARNING > cassandra.OperationTimedOut: errors=None, last_host=None

```

and this error was not process in async call. Error could happened, because waiting result is too short only 30 seconds:

Session.execute_async
Example of usage:
```
       See :meth:`Session.execute` for parameter definitions.

        Example usage::

            >>> session = cluster.connect()
            >>> future = session.execute_async("SELECT * FROM mycf")

            >>> def log_results(results):
            ...     for row in results:
            ...         log.info("Results: %s", row)

            >>> def log_error(exc):
            >>>     log.error("Operation failed: %s", exc)

            >>> future.add_callbacks(log_results, log_error)

        Async execution with blocking wait for results::

            >>> future = session.execute_async("SELECT * FROM mycf")
            >>> # do other stuff...

            >>> try:
            ...     results = future.result()
            ... except Exception:
            ...     log.exception("Operation failed:")
```

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by aleksbykov** [comment]
Issue didn't reproduced anymore in any job.
