### ISSUE TITLE
Throuput and Latency performance tests wrongly using an ARM AMI and fails: "The i3.2xlarge instance type does not support an AMI with a boot mode of UEFI"

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#4436]
ami_id_db_scylla: ami-099a011bd5f16a168 (or  ami-06b9b5d3a9e579eb5) 

Log url:
https://jenkins.scylladb.com/job/scylla-master/view/master-weekly-performance-tests/job/scylla-master-perf-regression-aws-test-throughput/223/execution/node/68/log/

Log error:
```
06:04:39  < t:2022-02-06 04:04:38,864 f:sct_config.py   l:1025 c:sdcm.sct_config      p:INFO  > test_id: f13be8fa-b01a-4cf5-bdf3-529655066ba5
06:04:39  < t:2022-02-06 04:04:38,864 f:sct_config.py   l:1025 c:sdcm.sct_config      p:INFO  > use_legacy_cluster_init: false
06:04:39  < t:2022-02-06 04:04:38,864 f:sct_config.py   l:1025 c:sdcm.sct_config      p:INFO  > user_credentials_path: ~/.ssh/scylla-qa-ec2
06:04:39  < t:2022-02-06 04:04:38,864 f:sct_config.py   l:1025 c:sdcm.sct_config      p:INFO  > user_prefix: perf-regression-perf-v8
06:04:40  < t:2022-02-06 04:04:39,760 f:rsyslog_daemon.py l:108  c:sdcm.rsyslog_daemon  p:INFO  > Rsyslog started. Container id: 3a1a56e5a6b3d01c00129898996e276ca092d042b21b97486cbcc9e1d124ca95
06:04:40  /usr/local/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py:111: UserWarning: Connecting to 746f0ad652a3447d83b1572f657c67cb.us-east-1.aws.found.io using SSL with verify_certs=False is insecure.
06:04:40    'Connecting to %s using SSL with verify_certs=False is insecure.' % host)
06:04:40  < t:2022-02-06 04:04:39,819 f:sct_events.py   l:63   c:sdcm.sct_events      p:INFO  > EventsDevice listen on pub_port=42956, sub_port=46599
06:04:40  < t:2022-02-06 04:04:39,822 f:sct_events.py   l:110  c:sdcm.sct_events      p:INFO  > subscribe to server with port 46599
06:04:40  < t:2022-02-06 04:04:39,822 f:sct_events.py   l:762  c:sdcm.sct_events      p:INFO  > writing to /sct/20220206-040435-805428/events_log/events.log
06:04:40  < t:2022-02-06 04:04:39,825 f:sct_events.py   l:110  c:sdcm.sct_events      p:INFO  > subscribe to server with port 46599
06:04:42  < t:2022-02-06 04:04:40,590 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  > 2022-02-06 04:04:40.578: (InfoEvent Severity.NORMAL): message=TEST_START test_id=f13be8fa-b01a-4cf5-bdf3-529655066ba5
06:04:42  < t:2022-02-06 04:04:41,273 f:cluster.py      l:2730 c:sdcm.cluster         p:INFO  > Cluster perf-regression-perf-v8-db-cluster-f13be8fa (AMI: ['ami-06b9b5d3a9e579eb5'] Type: i3.2xlarge): Init nodes
06:04:42  < t:2022-02-06 04:04:41,580 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  > 2022-02-06 04:04:41.568: (TestFrameworkEvent Severity.CRITICAL), source=PerformanceRegressionTest.SetUp()message=None
06:04:42  < t:2022-02-06 04:04:41,580 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  > exception=Traceback (most recent call last):
06:04:42  < t:2022-02-06 04:04:41,580 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  >   File "/sct/sdcm/tester.py", line 271, in setUp
06:04:42  < t:2022-02-06 04:04:41,580 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  >     self.init_resources()
06:04:42  < t:2022-02-06 04:04:41,580 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  >   File "/sct/sdcm/tester.py", line 719, in init_resources
06:04:42  < t:2022-02-06 04:04:41,580 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  >     monitor_info=monitor_info)
06:04:42  < t:2022-02-06 04:04:41,580 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  >   File "/sct/sdcm/tester.py", line 617, in get_cluster_aws
06:04:42  < t:2022-02-06 04:04:41,580 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  >     self.db_cluster = create_cluster(db_type)
06:04:42  < t:2022-02-06 04:04:41,580 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  >   File "/sct/sdcm/tester.py", line 583, in create_cluster
06:04:42  < t:2022-02-06 04:04:41,580 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  >     **cl_params)
06:04:42  < t:2022-02-06 04:04:41,580 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  >   File "/sct/sdcm/cluster_aws.py", line 787, in __init__
06:04:42  < t:2022-02-06 04:04:41,580 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  >     extra_network_interface=params.get('extra_network_interface'))
06:04:42  < t:2022-02-06 04:04:41,580 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  >   File "/sct/sdcm/cluster.py", line 2966, in __init__
06:04:42  < t:2022-02-06 04:04:41,580 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  >     super(BaseScyllaCluster, self).__init__(*args, **kwargs)
06:04:42  < t:2022-02-06 04:04:41,580 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  >   File "/sct/sdcm/cluster_aws.py", line 93, in __init__
06:04:42  < t:2022-02-06 04:04:41,580 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  >     extra_network_interface=extra_network_interface
06:04:42  < t:2022-02-06 04:04:41,580 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  >   File "/sct/sdcm/cluster.py", line 2743, in __init__
06:04:42  < t:2022-02-06 04:04:41,580 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  >     self.add_nodes(num, dc_idx=dc_idx, enable_auto_bootstrap=Setup.AUTO_BOOTSTRAP)
06:04:42  < t:2022-02-06 04:04:41,580 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  >   File "/sct/sdcm/cluster_aws.py", line 813, in add_nodes
06:04:42  < t:2022-02-06 04:04:41,580 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  >     enable_auto_bootstrap=enable_auto_bootstrap)
06:04:42  < t:2022-02-06 04:04:41,580 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  >   File "/sct/sdcm/cluster_aws.py", line 368, in add_nodes
06:04:42  < t:2022-02-06 04:04:41,580 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  >     instances = self._create_instances(count, ec2_user_data, dc_idx)
06:04:42  < t:2022-02-06 04:04:41,580 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  >   File "/sct/sdcm/cluster_aws.py", line 204, in _create_instances
06:04:42  < t:2022-02-06 04:04:41,580 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  >     instances = self._create_on_demand_instances(count, interfaces, ec2_user_data, dc_idx, tags_list=tags_list)
06:04:42  < t:2022-02-06 04:04:41,580 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  >   File "/sct/sdcm/cluster_aws.py", line 122, in _create_on_demand_instances
06:04:42  < t:2022-02-06 04:04:41,580 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  >     instances = self._ec2_services[dc_idx].create_instances(**params)
06:04:42  < t:2022-02-06 04:04:41,580 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  >   File "/usr/local/lib/python3.6/site-packages/boto3/resources/factory.py", line 520, in do_action
06:04:42  < t:2022-02-06 04:04:41,580 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  >     response = action(self, *args, **kwargs)
06:04:42  < t:2022-02-06 04:04:41,580 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  >   File "/usr/local/lib/python3.6/site-packages/boto3/resources/action.py", line 83, in __call__
06:04:42  < t:2022-02-06 04:04:41,580 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  >     response = getattr(parent.meta.client, operation_name)(**params)
06:04:42  < t:2022-02-06 04:04:41,580 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  >   File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 357, in _api_call
06:04:42  < t:2022-02-06 04:04:41,580 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  >     return self._make_api_call(operation_name, kwargs)
06:04:42  < t:2022-02-06 04:04:41,580 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  >   File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 661, in _make_api_call
06:04:42  < t:2022-02-06 04:04:41,580 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  >     raise error_class(parsed_response, operation_name)
06:04:42  < t:2022-02-06 04:04:41,580 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  > botocore.exceptions.ClientError: An error occurred (InvalidParameterValue) when calling the RunInstances operation: The i3.2xlarge instance type does not support an AMI with a boot mode of UEFI. Only instance types built on the Nitro System support UEFI. Specify an instance type that supports UEFI, and try again.
```

**Comment by fruch** [comment]
Look like I've missed the fixed for that for branch-perf-v8,
Now I've backported it, should be working:
https://github.com/scylladb/scylla-cluster-tests/commit/306f236e7c8c28590fc2dfcda9d0902170581c29
