### ISSUE TITLE
Jenkins script error - exit with exit code 137

### ISSUE THREAD

**Issue by KnifeyMoloko** [scylladb/scylla-cluster-tests#4514]
### Prerequisites

* [x] Are you rebased to master ?
* [ ] Is it reproducible ? --> First occurance
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master
* **scylla**: 5.1.dev-20220304.eff5076dd5d9

### Logs
* test_id: 6069c32d-cee4-4694-a2ce-851a16c19936
* jenkins job: https://jenkins.scylladb.com/job/scylla-master/job/scylla-master-perf-regression-aws-test-latency/173
* db logs: https://cloudius-jenkins-test.s3.amazonaws.com/6069c32d-cee4-4694-a2ce-851a16c19936/20220306_071804/db-cluster-6069c32d.zip
* sct_runner logs: https://cloudius-jenkins-test.s3.amazonaws.com/6069c32d-cee4-4694-a2ce-851a16c19936/20220306_071804/sct-runner-6069c32d.zip
* loader logs: https://cloudius-jenkins-test.s3.amazonaws.com/6069c32d-cee4-4694-a2ce-851a16c19936/20220306_071804/loader-set-6069c32d.zip
* monitor logs: https://cloudius-jenkins-test.s3.amazonaws.com/6069c32d-cee4-4694-a2ce-851a16c19936/20220306_071804/monitor-set-6069c32d.zip

### Description

When running the `test-latency` job, write and read workloads passed, but when running the mixed workload after 30 minutes the Jenkins script failed with code 137

sct.log

```
07:48:20  < t:2022-03-06 06:48:20,410 f:es.py           l:46   c:sdcm.es              p:INFO  > Update doc 6069c32d-cee4-4694-a2ce-851a16c19936_20220306_064820_178067 with info {'test_details': {'sct_git_commit': b'911515140d749e19692c701b197c1a56de0eb05f', 'job_name': 'scylla-master/scylla-master-perf-regression-aws-test-latency', 'job_url': 'https://jenkins.scylladb.com/job/scylla-master/job/scylla-master-perf-regression-aws-test-latency/173/', 'start_host': 'aws-us-builder3', 'test_duration': 300, 'start_time': 1646549300.386505, 'grafana_snapshots': [], 'grafana_screenshots': [], 'grafana_annotations': [], 'prometheus_data': '', 'test_id': '6069c32d-cee4-4694-a2ce-851a16c19936', 'log_files': {}, 'sub_type': 'mixed', 'test_name': 'performance_regression_test.PerformanceRegressionTest.test_latency_mixed', 'cassandra-stress': {'raw_cmd': "cassandra-stress mixed no-warmup cl=QUORUM duration=30m -schema 'replication(factor=3)' -port jmx=6868 -mode cql3 native -rate 'threads=100 throttle=9000/s'  -col 'size=FIXED(1024) n=FIXED(1)' -pop 'dist=gauss(1..500000000,250000000,25000000)' ", 'command': 'mixed', 'no-warmup': True, 'cl': 'QUORUM', 'duration': '30m', 'n': 'FIXED', 'schema': 'replication(factor=3)', 'port': 'jmx=6868', 'mode': 'cql3 native', 'col': 'size=FIXED(1024) n=FIXED(1)', 'pop': 'dist=gauss(1..500000000,250000000,25000000)', 'rate threads': '100', 'throttle threads': '9000'}}}
07:48:20  < t:2022-03-06 06:48:20,419 f:base.py         l:83   c:elasticsearch        p:INFO  > POST https://746f0ad652a3447d83b1572f657c67cb.us-east-1.aws.found.io:9243/performanceregressiontest/test_stats/6069c32d-cee4-4694-a2ce-851a16c19936_20220306_064820_178067/_update[](https://jenkins.scylladb.com/job/scylla-master/job/scylla-master-perf-regression-aws-test-latency/173/consoleFull#)[](https://jenkins.scylladb.com/job/scylla-master/job/scylla-master-perf-regression-aws-test-latency/173/consoleFull#)[](https://jenkins.scylladb.com/job/scylla-master/job/scylla-master-perf-regression-aws-test-latency/173/consoleFull#)[](https://jenkins.scylladb.com/job/scylla-master/job/scylla-master-perf-regression-aws-test-latency/173/consoleFull#)[](https://jenkins.scylladb.com/job/scylla-master/job/scylla-master-perf-regression-aws-test-latency/173/consoleFull#)[](https://jenkins.scylladb.com/job/scylla-master/job/scylla-master-perf-regression-aws-test-latency/173/consoleFull#) [status:200 request:0.009s]
07:48:20  < t:2022-03-06 06:48:20,435 f:stress_thread.py l:134  c:sdcm.stress_thread   p:INFO  > Stress command:
07:48:20  < t:2022-03-06 06:48:20,435 f:stress_thread.py l:134  c:sdcm.stress_thread   p:INFO  > cassandra-stress mixed no-warmup cl=QUORUM duration=30m -schema keyspace=keyspace1 'replication(factor=3)' -port jmx=6868 -mode cql3 native -rate 'threads=100 throttle=9000/s'  -col 'size=FIXED(1024) n=FIXED(1)' -pop 'dist=gauss(1..500000000,250000000,25000000)'  -node 172.30.0.102
07:48:20  < t:2022-03-06 06:48:20,447 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  > 2022-03-06 06:48:20.435: (CassandraStressEvent Severity.NORMAL): type=start node=Node perf-regression-latency-perf-v8-loader-node-6069c32d-1 [3.88.210.3 | 172.30.0.139] (seed: False)
07:48:20  < t:2022-03-06 06:48:20,447 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  > stress_cmd=cassandra-stress mixed no-warmup cl=QUORUM duration=30m -schema keyspace=keyspace1 'replication(factor=3)' -port jmx=6868 -mode cql3 native -rate 'threads=100 throttle=9000/s'  -col 'size=FIXED(1024) n=FIXED(1)' -pop 'dist=gauss(1..500000000,250000000,25000000)'  -node 172.30.0.102
07:48:52  < t:2022-03-06 06:48:50,463 f:stress_thread.py l:134  c:sdcm.stress_thread   p:INFO  > Stress command:
07:48:52  < t:2022-03-06 06:48:50,463 f:stress_thread.py l:134  c:sdcm.stress_thread   p:INFO  > cassandra-stress mixed no-warmup cl=QUORUM duration=30m -schema keyspace=keyspace1 'replication(factor=3)' -port jmx=6868 -mode cql3 native -rate 'threads=100 throttle=9000/s'  -col 'size=FIXED(1024) n=FIXED(1)' -pop 'dist=gauss(1..500000000,250000000,25000000)'  -node 172.30.0.102
07:48:52  < t:2022-03-06 06:48:50,466 f:stress_thread.py l:134  c:sdcm.stress_thread   p:INFO  > Stress command:
07:48:52  < t:2022-03-06 06:48:50,466 f:stress_thread.py l:134  c:sdcm.stress_thread   p:INFO  > cassandra-stress mixed no-warmup cl=QUORUM duration=30m -schema keyspace=keyspace1 'replication(factor=3)' -port jmx=6868 -mode cql3 native -rate 'threads=100 throttle=9000/s'  -col 'size=FIXED(1024) n=FIXED(1)' -pop 'dist=gauss(1..500000000,250000000,25000000)'  -node 172.30.0.102
07:48:52  < t:2022-03-06 06:48:50,466 f:stress_thread.py l:134  c:sdcm.stress_thread   p:INFO  > Stress command:
07:48:52  < t:2022-03-06 06:48:50,466 f:stress_thread.py l:134  c:sdcm.stress_thread   p:INFO  > cassandra-stress mixed no-warmup cl=QUORUM duration=30m -schema keyspace=keyspace1 'replication(factor=3)' -port jmx=6868 -mode cql3 native -rate 'threads=100 throttle=9000/s'  -col 'size=FIXED(1024) n=FIXED(1)' -pop 'dist=gauss(1..500000000,250000000,25000000)'  -node 172.30.0.102
07:48:52  < t:2022-03-06 06:48:50,476 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  > 2022-03-06 06:48:50.464: (CassandraStressEvent Severity.NORMAL): type=start node=Node perf-regression-latency-perf-v8-loader-node-6069c32d-2 [3.87.186.124 | 172.30.0.105] (seed: False)
07:48:52  < t:2022-03-06 06:48:50,476 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  > stress_cmd=cassandra-stress mixed no-warmup cl=QUORUM duration=30m -schema keyspace=keyspace1 'replication(factor=3)' -port jmx=6868 -mode cql3 native -rate 'threads=100 throttle=9000/s'  -col 'size=FIXED(1024) n=FIXED(1)' -pop 'dist=gauss(1..500000000,250000000,25000000)'  -node 172.30.0.102
07:48:52  < t:2022-03-06 06:48:50,480 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  > 2022-03-06 06:48:50.467: (CassandraStressEvent Severity.NORMAL): type=start node=Node perf-regression-latency-perf-v8-loader-node-6069c32d-4 [3.87.71.32 | 172.30.0.60] (seed: False)
07:48:52  < t:2022-03-06 06:48:50,480 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  > stress_cmd=cassandra-stress mixed no-warmup cl=QUORUM duration=30m -schema keyspace=keyspace1 'replication(factor=3)' -port jmx=6868 -mode cql3 native -rate 'threads=100 throttle=9000/s'  -col 'size=FIXED(1024) n=FIXED(1)' -pop 'dist=gauss(1..500000000,250000000,25000000)'  -node 172.30.0.102
07:48:52  < t:2022-03-06 06:48:50,480 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  > 2022-03-06 06:48:50.468: (CassandraStressEvent Severity.NORMAL): type=start node=Node perf-regression-latency-perf-v8-loader-node-6069c32d-3 [54.173.21.168 | 172.30.0.18] (seed: False)
07:48:52  < t:2022-03-06 06:48:50,480 f:sct_events.py   l:780  c:sdcm.sct_events      p:INFO  > stress_cmd=cassandra-stress mixed no-warmup cl=QUORUM duration=30m -schema keyspace=keyspace1 'replication(factor=3)' -port jmx=6868 -mode cql3 native -rate 'threads=100 throttle=9000/s'  -col 'size=FIXED(1024) n=FIXED(1)' -pop 'dist=gauss(1..500000000,250000000,25000000)'  -node 172.30.0.102
08:17:33  [Pipeline] }
08:17:40  [Pipeline] // dir
08:17:41  [Pipeline] }
08:17:43  [Pipeline] // wrap
08:17:43  [Pipeline] }
08:17:44  ERROR: script returned exit code 137
08:17:46  [Pipeline] // catchError
08:17:46  [Pipeline] }
08:17:48  [Pipeline] // stage
08:17:49  [Pipeline] stage
08:17:49  [Pipeline] { (Collect logs for test_latency)
08:17:52  [Pipeline] catchError
08:17:52  [Pipeline] {
08:17:54  [Pipeline] wrap
08:17:55  [Pipeline] {
08:17:57  [Pipeline] dir
```

**Comment by ShlomiBalalis** [comment]
Several 2022.1 jobs failed with the same exit code:
## Installation details

Kernel Version: 5.15.0-1015-aws
Scylla version (or git commit hash): `2022.1.1-20220807.e1e2c3d21` with build-id `c3ec7353aee613ea535370e90c7c1d7ddcdf3209`
Cluster size: 1 nodes (i3.metal)

Scylla Nodes used in this run:
- artifacts-ami-jenkins-db-node-e9061d94-1 (44.196.48.11 | 10.0.2.168) (shards: 70)


OS / Image: `ami-01670e0a2b0d4d19b` (aws: us-east-1)

Test: `artifacts-ami-test`
Test id: `e9061d94-5fd4-4ede-a22e-40745e867d65`
Test name: `enterprise-2022.1/artifacts/artifacts-ami-test`
Test config file(s):

- [ami.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/2a9676fe346183a0861b9b7df3d0d4511650e5b5/test-cases/artifacts/ami.yaml)

## Issue description

In this run, the job failed after the actual test has already passed:
```
10:02:38  < t:2022-08-08 07:02:36,923 f:health_checker.py l:41   c:sdcm.utils.health_checker p:INFO  > Status for regular node artifacts-ami-jenkins-db-node-e9061d94-1
10:02:38  < t:2022-08-08 07:02:36,925 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2022-08-08 07:02:36.923: (NodetoolEvent Severity.NORMAL) period_type=begin event_id=3d828c74-3047-4abf-9bde-9834b54184e0: nodetool_command=status node=artifacts-ami-jenkins-db-node-e9061d94-1
10:02:38  < t:2022-08-08 07:02:38,353 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2022-08-08 07:02:38.351: (NodetoolEvent Severity.NORMAL) period_type=end event_id=3d828c74-3047-4abf-9bde-9834b54184e0 duration=1s: nodetool_command=status node=artifacts-ami-jenkins-db-node-e9061d94-1
10:07:37  < t:2022-08-08 07:03:58,741 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2022-08-08 07:03:58.241: (JMXServiceEvent Severity.NORMAL) period_type=end event_id=c4977b81-6dca-4b34-8b91-2c16050db872 duration=5m11s node=artifacts-ami-jenkins-db-node-e9061d94-1
10:07:37  < t:2022-08-08 07:04:00,048 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2022-08-08 07:03:58.635: (ScyllaServerStatusEvent Severity.NORMAL) period_type=end event_id=95f6b0e7-ddfa-42a9-9a02-a3b95a503e8c duration=5m26s node=artifacts-ami-jenkins-db-node-e9061d94-1
10:07:37  < t:2022-08-08 07:05:38,126 f:threading.py    l:1009 c:cassandra.connection p:WARNING > Heartbeat failed for connection (140385275400720) to 13.49.166.9:9042
10:07:37  /bin/bash: line 1:    11 Killed                  ./sct.py run-test artifacts_test --backend aws --logdir /home/jenkins/slave/workspace/enterprise-2022.1/artifacts/artifacts-ami-test@10/scylla-cluster-tests
10:07:38  < t:2022-08-08 07:03:58,741 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2022-08-08 07:03:58.241: (JMXServiceEvent Severity.NORMAL) period_type=end event_id=c4977b81-6dca-4b34-8b91-2c16050db872 duration=5m11s node=artifacts-ami-jenkins-db-node-e9061d94-1
10:07:38  < t:2022-08-08 07:04:00,048 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2022-08-08 07:03:58.635: (ScyllaServerStatusEvent Severity.NORMAL) period_type=end event_id=95f6b0e7-ddfa-42a9-9a02-a3b95a503e8c duration=5m26s node=artifacts-ami-jenkins-db-node-e9061d94-1
10:07:38  < t:2022-08-08 07:05:38,126 f:threading.py    l:1009 c:cassandra.connection p:WARNING > Heartbeat failed for connection (140385275400720) to 13.49.166.9:9042
10:07:38  /bin/bash: line 1:    11 Killed                  ./sct.py run-test artifacts_test --backend aws --logdir /home/jenkins/slave/workspace/enterprise-2022.1/artifacts/artifacts-ami-test@10/scylla-cluster-tests
10:07:39  [Pipeline] }
10:07:39  [Pipeline] // dir
10:07:39  [Pipeline] }
10:07:39  [Pipeline] // wrap
10:07:39  [Pipeline] }
10:07:39  ERROR: script returned exit code 137
10:07:39  [Pipeline] // catchError
10:07:39  [Pipeline] }
10:07:39  [Pipeline] // timeout
10:07:39  [Pipeline] }
10:07:39  [Pipeline] // stage
10:07:39  [Pipeline] stage
10:07:39  [Pipeline] { (Collect log data (i3.metal))
10:07:39  [Pipeline] catchError
10:07:39  [Pipeline] {
10:07:39  [Pipeline] wrap
10:07:39  [Pipeline] {
10:07:39  [Pipeline] dir
```

- Restore Monitor Stack command: `$ hydra investigate show-monitor e9061d94-5fd4-4ede-a22e-40745e867d65`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=e9061d94-5fd4-4ede-a22e-40745e867d65)
- Show all stored logs command: `$ hydra investigate show-logs e9061d94-5fd4-4ede-a22e-40745e867d65`

## Logs:
- **db-cluster-e9061d94.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e9061d94-5fd4-4ede-a22e-40745e867d65/20220808_070846/db-cluster-e9061d94.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e9061d94-5fd4-4ede-a22e-40745e867d65/20220808_070846/db-cluster-e9061d94.tar.gz)
- **sct-runner-e9061d94.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e9061d94-5fd4-4ede-a22e-40745e867d65/20220808_070846/sct-runner-e9061d94.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e9061d94-5fd4-4ede-a22e-40745e867d65/20220808_070846/sct-runner-e9061d94.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2022.1/job/artifacts/job/artifacts-ami-test/153/)

And:


## Installation details



Cluster size: 1 nodes (im4gn.4xlarge)

Scylla Nodes used in this run:
- artifacts-ami-jenkins-db-node-aa6d8b0b-1 (3.84.118.122 | 10.0.10.70) (shards: -1)


OS / Image: `ami-0626cc8a62beeab72` (aws: us-east-1)

Test: `artifacts-ami-test-arm`
Test id: `aa6d8b0b-3eb9-4c23-baeb-2b948ea0cbba`
Test name: `enterprise-2022.1/artifacts/artifacts-ami-test-arm`
Test config file(s):

- [ami.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/2a9676fe346183a0861b9b7df3d0d4511650e5b5/test-cases/artifacts/ami.yaml)

## Issue description

In this run, however, the job failed during the test run.
```
09:58:48  < t:2022-08-08 06:58:48,438 f:cluster.py      l:4220 c:sdcm.cluster         p:INFO  > Cluster artifacts-ami-jenkins-db-cluster-aa6d8b0b (AMI: ['ami-0626cc8a62beeab72'] Type: im4gn.4xlarge): io.conf right after reboot: SEASTAR_IO="--io-properties-file=/etc/scylla.d/io_properties.yaml"
09:58:48  
09:58:59  < t:2022-08-08 06:58:57,930 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2022-08-08 06:58:57.927: (JMXServiceEvent Severity.NORMAL) period_type=begin event_id=343dba25-5177-4814-8dd5-eb34669ad0c2 node=artifacts-ami-jenkins-db-node-aa6d8b0b-1
09:59:30  Cannot contact aws-us-east-1-qa-builder-1: java.lang.InterruptedException
10:02:06  < t:2022-08-08 06:59:57,245 f:cluster.py      l:1808 c:sdcm.cluster_aws     p:INFO  > Node artifacts-ami-jenkins-db-node-aa6d8b0b-1 [3.84.118.122 | 10.0.10.70] (seed: True): node artifacts-ami-jenkins-db-node-aa6d8b0b-1 has scylla-manager-agent version 3.0.0-0.20220523.5501e5d7f53
10:02:06  
10:02:06  < t:2022-08-08 07:02:04,344 f:threading.py    l:1009 c:cassandra.connection p:WARNING > Heartbeat failed for connection (139860140321248) to 13.51.52.79:9042
10:02:06  Exception in thread TestRunWithHeartbeat-aa6d8b0b-3eb9-4c23-baeb-2b948ea0cbba-heartbeat:
10:02:06  Traceback (most recent call last):
10:02:06    File "/usr/local/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
10:02:06      self.run()
10:02:06    File "/usr/local/lib/python3.10/threading.py", line 946, in run
10:02:06      self._target(*self._args, **self._kwargs)
10:02:06    File "/usr/local/lib/python3.10/site-packages/argus/db/testrun.py", line 723, in _heartbeat_entry
10:02:06      self.argus.session.execute(bound_statement)
10:02:06    File "cassandra/cluster.py", line 2668, in cassandra.cluster.Session.execute
10:02:06    File "cassandra/cluster.py", line 4953, in cassandra.cluster.ResponseFuture.result
10:02:06  cassandra.OperationTimedOut: errors={'13.51.52.79:9042': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=13.51.52.79:9042
10:02:18  /bin/bash: line 1:    11 Killed                  ./sct.py run-test artifacts_test --backend aws --logdir /home/jenkins/slave/workspace/enterprise-2022.1/artifacts/artifacts-ami-test-arm/scylla-cluster-tests
10:02:19  [Pipeline] }
10:02:19  [Pipeline] // dir
10:02:19  [Pipeline] }
10:02:19  [Pipeline] // wrap
10:02:19  [Pipeline] }
10:02:19  ERROR: script returned exit code 137
```

- Restore Monitor Stack command: `$ hydra investigate show-monitor aa6d8b0b-3eb9-4c23-baeb-2b948ea0cbba`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=aa6d8b0b-3eb9-4c23-baeb-2b948ea0cbba)
- Show all stored logs command: `$ hydra investigate show-logs aa6d8b0b-3eb9-4c23-baeb-2b948ea0cbba`

## Logs:
- **db-cluster-aa6d8b0b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/aa6d8b0b-3eb9-4c23-baeb-2b948ea0cbba/20220808_070320/db-cluster-aa6d8b0b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/aa6d8b0b-3eb9-4c23-baeb-2b948ea0cbba/20220808_070320/db-cluster-aa6d8b0b.tar.gz)
- **sct-runner-aa6d8b0b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/aa6d8b0b-3eb9-4c23-baeb-2b948ea0cbba/20220808_070320/sct-runner-aa6d8b0b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/aa6d8b0b-3eb9-4c23-baeb-2b948ea0cbba/20220808_070320/sct-runner-aa6d8b0b.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2022.1/job/artifacts/job/artifacts-ami-test-arm/85/)

**Comment by fruch** [comment]
I would look at system log on the builder running the tests.

Or someone manually kill docker instances, 
Or it might have running out of disk/memory, and we need to beef those builders with one of the two.

**Comment by KnifeyMoloko** [comment]
We don't see this crop up again, and it does look like it was an issue with the Jenkins machine rather than something in our code. Closing this issue.
