### ISSUE TITLE
hydra clean-resources --user is breaking on clean_instances_azure 

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#4546]
Today I was trying to clean my resources, like that:
```
./sct.py clean-resources --user fruch
```
and when it got to scanning azure, it failed like the following:
```
Traceback (most recent call last):
  File "/home/fruch/Projects/scylla-cluster-tests/./sct.py", line 1400, in <module>
    cli()
  File "/home/fruch/.pyenv/versions/3.10.0/envs/sct310-3.10.0/lib/python3.10/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/fruch/.pyenv/versions/3.10.0/envs/sct310-3.10.0/lib/python3.10/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/fruch/.pyenv/versions/3.10.0/envs/sct310-3.10.0/lib/python3.10/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/fruch/.pyenv/versions/3.10.0/envs/sct310-3.10.0/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/fruch/.pyenv/versions/3.10.0/envs/sct310-3.10.0/lib/python3.10/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/fruch/.pyenv/versions/3.10.0/envs/sct310-3.10.0/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/fruch/Projects/scylla-cluster-tests/./sct.py", line 299, in clean_resources
    clean_func(param, dry_run=dry_run)
  File "/home/fruch/Projects/scylla-cluster-tests/sdcm/utils/common.py", line 514, in clean_cloud_resources
    clean_instances_azure(tags_dict, dry_run=dry_run)
  File "/home/fruch/Projects/scylla-cluster-tests/sdcm/utils/common.py", line 1065, in clean_instances_azure
    test_id = tags_dict.pop("TestId")
KeyError: 'TestId'
```

**Comment by fruch** [comment]
also `list-resources` doesn't seem to be scanning azure, it would be nice once people start working with it.
