### ISSUE TITLE
[rolling upgrade]  Found error in truncate table: ConnectionException('Host has been marked down or removed')

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#4562]
Test failed with the following error:
```
< t:2022-03-29 00:46:37,236 f:fill_db_data.py l:3255 c:sdcm.fill_db_data    p:ERROR > SELECT total FROM counters_test WHERE userid = 1 AND url = 'http://foo.com' < t:2022-03-29 00:46:37,236 f:fill_db_data.py l:3255 c:sdcm.fill_db_data    p:ERROR > SELECT total FROM counters_test WHERE userid = 1 AND url = 'http://foo.com'
< t:2022-03-29 00:46:37,236 f:fill_db_data.py l:3255 c:sdcm.fill_db_data    p:ERROR > Traceback (most recent call last):
< t:2022-03-29 00:46:37,236 f:fill_db_data.py l:3255 c:sdcm.fill_db_data    p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/fill_db_data.py", line 3253, in _run_db_queries
< t:2022-03-29 00:46:37,236 f:fill_db_data.py l:3255 c:sdcm.fill_db_data    p:ERROR >     self.assertEqual([list(row) for row in res], item['results'][i])
< t:2022-03-29 00:46:37,236 f:fill_db_data.py l:3255 c:sdcm.fill_db_data    p:ERROR >   File "/usr/local/lib/python3.10/unittest/case.py", line 837, in assertEqual
< t:2022-03-29 00:46:37,236 f:fill_db_data.py l:3255 c:sdcm.fill_db_data    p:ERROR >     assertion_func(first, second, msg=msg)
< t:2022-03-29 00:46:37,236 f:fill_db_data.py l:3255 c:sdcm.fill_db_data    p:ERROR >   File "/usr/local/lib/python3.10/unittest/case.py", line 1043, in assertListEqual
< t:2022-03-29 00:46:37,236 f:fill_db_data.py l:3255 c:sdcm.fill_db_data    p:ERROR >     self.assertSequenceEqual(list1, list2, msg, seq_type=list)
< t:2022-03-29 00:46:37,236 f:fill_db_data.py l:3255 c:sdcm.fill_db_data    p:ERROR >   File "/usr/local/lib/python3.10/unittest/case.py", line 1025, in assertSequenceEqual
< t:2022-03-29 00:46:37,236 f:fill_db_data.py l:3255 c:sdcm.fill_db_data    p:ERROR >     self.fail(msg)
< t:2022-03-29 00:46:37,236 f:fill_db_data.py l:3255 c:sdcm.fill_db_data    p:ERROR >   File "/usr/local/lib/python3.10/unittest/case.py", line 667, in fail
< t:2022-03-29 00:46:37,236 f:fill_db_data.py l:3255 c:sdcm.fill_db_data    p:ERROR >     raise self.failureException(msg)
< t:2022-03-29 00:46:37,236 f:fill_db_data.py l:3255 c:sdcm.fill_db_data    p:ERROR > AssertionError: Lists differ: [[-3]] != [[1]]
< t:2022-03-29 00:46:37,236 f:fill_db_data.py l:3255 c:sdcm.fill_db_data    p:ERROR >
< t:2022-03-29 00:46:37,236 f:fill_db_data.py l:3255 c:sdcm.fill_db_data    p:ERROR > First differing element 0:
< t:2022-03-29 00:46:37,236 f:fill_db_data.py l:3255 c:sdcm.fill_db_data    p:ERROR > [-3]
< t:2022-03-29 00:46:37,236 f:fill_db_data.py l:3255 c:sdcm.fill_db_data    p:ERROR > [1]
< t:2022-03-29 00:46:37,236 f:fill_db_data.py l:3255 c:sdcm.fill_db_data    p:ERROR >
< t:2022-03-29 00:46:37,236 f:fill_db_data.py l:3255 c:sdcm.fill_db_data    p:ERROR > - [[-3]]
< t:2022-03-29 00:46:37,236 f:fill_db_data.py l:3255 c:sdcm.fill_db_data    p:ERROR > + [[1]]
```

seem like it was failing since the truncate phase failed:
```
< t:2022-03-28 23:49:24,949 f:fill_db_data.py l:3331 c:sdcm.fill_db_data    p:DEBUG > Found error in truncate tables: 'errors={<Host: 10.0.1.90:9042 eu-west>: ConnectionException('Host has been marked down or removed')}, last_host=10.0.1.171:9042'
```
it's not clear what cause the host to be removed ? or it was before it was added ?

## Logs:
[grafana - https://cloudius-jenkins-test.s3.amazonaws.com/4d3e4d6c-2db2-474d-b890-6ff441b1b02a/20220329_004647/grafana-screenshot-overview-20220329_004647-rolling-upgrade-4-6-centos-monitor-node-4d3e4d6c-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/4d3e4d6c-2db2-474d-b890-6ff441b1b02a/20220329_004647/grafana-screenshot-overview-20220329_004647-rolling-upgrade-4-6-centos-monitor-node-4d3e4d6c-1.png)
[grafana - https://cloudius-jenkins-test.s3.amazonaws.com/4d3e4d6c-2db2-474d-b890-6ff441b1b02a/20220329_004647/grafana-screenshot-rolling-upgrade-ami-test-scylla-per-server-metrics-nemesis-20220329_004844-rolling-upgrade-4-6-centos-monitor-node-4d3e4d6c-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/4d3e4d6c-2db2-474d-b890-6ff441b1b02a/20220329_004647/grafana-screenshot-rolling-upgrade-ami-test-scylla-per-server-metrics-nemesis-20220329_004844-rolling-upgrade-4-6-centos-monitor-node-4d3e4d6c-1.png)
[db-cluster - https://cloudius-jenkins-test.s3.amazonaws.com/4d3e4d6c-2db2-474d-b890-6ff441b1b02a/20220329_005908/db-cluster-4d3e4d6c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4d3e4d6c-2db2-474d-b890-6ff441b1b02a/20220329_005908/db-cluster-4d3e4d6c.tar.gz)
[loader-set - https://cloudius-jenkins-test.s3.amazonaws.com/4d3e4d6c-2db2-474d-b890-6ff441b1b02a/20220329_005908/loader-set-4d3e4d6c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4d3e4d6c-2db2-474d-b890-6ff441b1b02a/20220329_005908/loader-set-4d3e4d6c.tar.gz)
[monitor-set - https://cloudius-jenkins-test.s3.amazonaws.com/4d3e4d6c-2db2-474d-b890-6ff441b1b02a/20220329_005908/monitor-set-4d3e4d6c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4d3e4d6c-2db2-474d-b890-6ff441b1b02a/20220329_005908/monitor-set-4d3e4d6c.tar.gz)
[sct - https://cloudius-jenkins-test.s3.amazonaws.com/4d3e4d6c-2db2-474d-b890-6ff441b1b02a/20220329_005908/sct-runner-4d3e4d6c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4d3e4d6c-2db2-474d-b890-6ff441b1b02a/20220329_005908/sct-runner-4d3e4d6c.tar.gz)

## Links:

[Build URL](https://jenkins.scylladb.com/job/scylla-4.6/job/rolling-upgrade/job/rolling-upgrade-ami-test/23/)

**Comment by fruch** [comment]
maybe we should do by default
```python
cluster.connect(wait_all_pools=True)
```
