### ISSUE TITLE
Longevity startup fails: No db log from 2 nodes

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla-cluster-tests#4563]
### Prerequisites

* [x] Are you rebased to master ?
* [ ] Is it reproducible ?
* [ ] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master
* **scylla**: master (5.1.dev-0.20220317.c45050895403 with build-id 076f513b6143670def988c7626389b270411f8f7)

### Logs
* test_id: 9b851a59-848f-4d0d-8f78-cf6619767872
* job: https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-200gb-48h/171/ 

### Description

At the startup of the 200gb longevity job the init_nodes function failed because it couldn't access the logs of two of the db nodes:
```
< t:2022-03-25 03:29:22,667 f:tester.py       l:140  c:sdcm.tester          p:ERROR > Traceback (most recent call last):
< t:2022-03-25 03:29:22,667 f:tester.py       l:140  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 133, in wrapper
< t:2022-03-25 03:29:22,667 f:tester.py       l:140  c:sdcm.tester          p:ERROR >     return method(*args, **kwargs)
< t:2022-03-25 03:29:22,667 f:tester.py       l:140  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 113, in inner
< t:2022-03-25 03:29:22,667 f:tester.py       l:140  c:sdcm.tester          p:ERROR >     res = func(*args, **kwargs)
< t:2022-03-25 03:29:22,667 f:tester.py       l:140  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 622, in setUp
< t:2022-03-25 03:29:22,667 f:tester.py       l:140  c:sdcm.tester          p:ERROR >     self.init_nodes(db_cluster=self.db_cluster)
< t:2022-03-25 03:29:22,667 f:tester.py       l:140  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 558, in init_nodes
< t:2022-03-25 03:29:22,667 f:tester.py       l:140  c:sdcm.tester          p:ERROR >     db_cluster.wait_for_init(node_list=db_cluster.nodes)
< t:2022-03-25 03:29:22,667 f:tester.py       l:140  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3546, in wrapper
< t:2022-03-25 03:29:22,667 f:tester.py       l:140  c:sdcm.tester          p:ERROR >     method(*args, **kwargs)
< t:2022-03-25 03:29:22,667 f:tester.py       l:140  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 4309, in wait_for_init
< t:2022-03-25 03:29:22,667 f:tester.py       l:140  c:sdcm.tester          p:ERROR >     wait.wait_for(
< t:2022-03-25 03:29:22,667 f:tester.py       l:140  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/wait.py", line 61, in wait_for
< t:2022-03-25 03:29:22,667 f:tester.py       l:140  c:sdcm.tester          p:ERROR >     res = retry(func, **kwargs)
< t:2022-03-25 03:29:22,667 f:tester.py       l:140  c:sdcm.tester          p:ERROR >   File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 404, in __call__
< t:2022-03-25 03:29:22,667 f:tester.py       l:140  c:sdcm.tester          p:ERROR >     do = self.iter(retry_state=retry_state)
< t:2022-03-25 03:29:22,667 f:tester.py       l:140  c:sdcm.tester          p:ERROR >   File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 360, in iter
< t:2022-03-25 03:29:22,667 f:tester.py       l:140  c:sdcm.tester          p:ERROR >     raise retry_exc.reraise()
< t:2022-03-25 03:29:22,667 f:tester.py       l:140  c:sdcm.tester          p:ERROR >   File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 193, in reraise
< t:2022-03-25 03:29:22,667 f:tester.py       l:140  c:sdcm.tester          p:ERROR >     raise self.last_attempt.result()
< t:2022-03-25 03:29:22,667 f:tester.py       l:140  c:sdcm.tester          p:ERROR >   File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 438, in result
< t:2022-03-25 03:29:22,667 f:tester.py       l:140  c:sdcm.tester          p:ERROR >     return self.__get_result()
< t:2022-03-25 03:29:22,667 f:tester.py       l:140  c:sdcm.tester          p:ERROR >   File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 390, in __get_result
< t:2022-03-25 03:29:22,667 f:tester.py       l:140  c:sdcm.tester          p:ERROR >     raise self._exception
< t:2022-03-25 03:29:22,667 f:tester.py       l:140  c:sdcm.tester          p:ERROR >   File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 407, in __call__
< t:2022-03-25 03:29:22,667 f:tester.py       l:140  c:sdcm.tester          p:ERROR >     result = fn(*args, **kwargs)
< t:2022-03-25 03:29:22,667 f:tester.py       l:140  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 4299, in verify_logging_from_nodes
< t:2022-03-25 03:29:22,667 f:tester.py       l:140  c:sdcm.tester          p:ERROR >     raise Exception(
< t:2022-03-25 03:29:22,667 f:tester.py       l:140  c:sdcm.tester          p:ERROR > Exception: No db log from the following nodes:
< t:2022-03-25 03:29:22,667 f:tester.py       l:140  c:sdcm.tester          p:ERROR > longevity-200gb-48h-verify-limited--db-node-9b851a59-3
< t:2022-03-25 03:29:22,667 f:tester.py       l:140  c:sdcm.tester          p:ERROR > longevity-200gb-48h-verify-limited--db-node-9b851a59-4
< t:2022-03-25 03:29:22,667 f:tester.py       l:140  c:sdcm.tester          p:ERROR > files expected to be find:
< t:2022-03-25 03:29:22,667 f:tester.py       l:140  c:sdcm.tester          p:ERROR > /home/ubuntu/sct-results/20220325-030616-820481/hosts/longevity-200gb-48h-verify-limited--db-node-9b851a59-3/messages.log
< t:2022-03-25 03:29:22,667 f:tester.py       l:140  c:sdcm.tester          p:ERROR > /home/ubuntu/sct-results/20220325-030616-820481/hosts/longevity-200gb-48h-verify-limited--db-node-9b851a59-4/messages.log
```
Which, obviously, caused the job to fail before it even started.

**Expected behavior:** The job starts normally and is able to collect the logs of the nodes

**Actual behavior:** SCT failed to connect to the nodes and stream the logs

**Comment by fruch** [comment]
Found the root cause, all the nodes mistakenly configured syslog-ng, and not rsyslog as the SCT configuration suggest.
the first two failed to installed syslog-ng, hence fallback to using rsyslog.

In the two places `AWSConfigurationScriptBuilder` being initialized it's without `log_transport` and the default is syslog-ng.
