### ISSUE TITLE
SCT test fails due benchmarking tools installation failure

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#4586]
When running basic longevity: `test-cases/longevity/longevity-10gb-3h.yaml` error happened during setup:
```
< t:2022-04-06 14:33:25,724 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > E: Package 'make' has no installation candidate
< t:2022-04-06 14:33:25,724 f:base.py         l:146  c:RemoteLibSSH2CmdRunner p:ERROR > Error executing command: "sudo apt-get install -y make"; Exit status: 100
```
and later:
```
< t:2022-04-06 14:38:59,909 f:tester.py       l:140  c:sdcm.tester          p:ERROR > Exception in setUp. Will call tearDown < t:2022-04-06 14:38:59,909 f:tester.py       l:140  c:sdcm.tester          p:ERROR > Exception in setUp. Will call tearDown
< t:2022-04-06 14:38:59,909 f:tester.py       l:140  c:sdcm.tester          p:ERROR > Traceback (most recent call last):
< t:2022-04-06 14:38:59,909 f:tester.py       l:140  c:sdcm.tester          p:ERROR >   File "/home/ls/repos/sct/loader-with-ics-v18/sdcm/tester.py", line 133, in wrapper
< t:2022-04-06 14:38:59,909 f:tester.py       l:140  c:sdcm.tester          p:ERROR >     return method(*args, **kwargs)
< t:2022-04-06 14:38:59,909 f:tester.py       l:140  c:sdcm.tester          p:ERROR >   File "/home/ls/repos/sct/loader-with-ics-v18/sdcm/utils/decorators.py", line 113, in inner
< t:2022-04-06 14:38:59,909 f:tester.py       l:140  c:sdcm.tester          p:ERROR >     res = func(*args, **kwargs)
< t:2022-04-06 14:38:59,909 f:tester.py       l:140  c:sdcm.tester          p:ERROR >   File "/home/ls/repos/sct/loader-with-ics-v18/sdcm/tester.py", line 616, in setUp
< t:2022-04-06 14:38:59,909 f:tester.py       l:140  c:sdcm.tester          p:ERROR >     self.init_resources()
< t:2022-04-06 14:38:59,909 f:tester.py       l:140  c:sdcm.tester          p:ERROR >   File "/home/ls/repos/sct/loader-with-ics-v18/sdcm/tester.py", line 1410, in init_resources
< t:2022-04-06 14:38:59,909 f:tester.py       l:140  c:sdcm.tester          p:ERROR >     self.get_cluster_aws(loader_info=loader_info, db_info=db_info,
< t:2022-04-06 14:38:59,909 f:tester.py       l:140  c:sdcm.tester          p:ERROR >   File "/home/ls/repos/sct/loader-with-ics-v18/sdcm/tester.py", line 1006, in get_cluster_aws
< t:2022-04-06 14:38:59,909 f:tester.py       l:140  c:sdcm.tester          p:ERROR >     self.db_cluster = create_cluster(db_type)
< t:2022-04-06 14:38:59,909 f:tester.py       l:140  c:sdcm.tester          p:ERROR >   File "/home/ls/repos/sct/loader-with-ics-v18/sdcm/tester.py", line 969, in create_cluster
< t:2022-04-06 14:38:59,909 f:tester.py       l:140  c:sdcm.tester          p:ERROR >     return ScyllaAWSCluster(
< t:2022-04-06 14:38:59,909 f:tester.py       l:140  c:sdcm.tester          p:ERROR >   File "/home/ls/repos/sct/loader-with-ics-v18/sdcm/cluster_aws.py", line 803, in __init__
< t:2022-04-06 14:38:59,909 f:tester.py       l:140  c:sdcm.tester          p:ERROR >     super().__init__(
< t:2022-04-06 14:38:59,909 f:tester.py       l:140  c:sdcm.tester          p:ERROR >   File "/home/ls/repos/sct/loader-with-ics-v18/sdcm/cluster.py", line 3580, in __init__
< t:2022-04-06 14:38:59,909 f:tester.py       l:140  c:sdcm.tester          p:ERROR >     super().__init__(*args, **kwargs)
< t:2022-04-06 14:38:59,909 f:tester.py       l:140  c:sdcm.tester          p:ERROR >   File "/home/ls/repos/sct/loader-with-ics-v18/sdcm/cluster_aws.py", line 100, in __init__
< t:2022-04-06 14:38:59,909 f:tester.py       l:140  c:sdcm.tester          p:ERROR >     super().__init__(cluster_uuid=cluster_uuid,
< t:2022-04-06 14:38:59,909 f:tester.py       l:140  c:sdcm.tester          p:ERROR >   File "/home/ls/repos/sct/loader-with-ics-v18/sdcm/cluster.py", line 3079, in __init__
< t:2022-04-06 14:38:59,909 f:tester.py       l:140  c:sdcm.tester          p:ERROR >     self.run_node_benchmarks()
< t:2022-04-06 14:38:59,909 f:tester.py       l:140  c:sdcm.tester          p:ERROR >   File "/home/ls/repos/sct/loader-with-ics-v18/sdcm/cluster.py", line 3448, in run_node_benchmarks
< t:2022-04-06 14:38:59,909 f:tester.py       l:140  c:sdcm.tester          p:ERROR >     self.node_benchmark_manager.run_benchmarks()
< t:2022-04-06 14:38:59,909 f:tester.py       l:140  c:sdcm.tester          p:ERROR >   File "/home/ls/repos/sct/loader-with-ics-v18/sdcm/utils/benchmarks.py", line 125, in run_benchmarks
< t:2022-04-06 14:38:59,909 f:tester.py       l:140  c:sdcm.tester          p:ERROR >     self._compare_results()
< t:2022-04-06 14:38:59,909 f:tester.py       l:140  c:sdcm.tester          p:ERROR >   File "/home/ls/repos/sct/loader-with-ics-v18/sdcm/utils/benchmarks.py", line 158, in _compare_results
< t:2022-04-06 14:38:59,909 f:tester.py       l:140  c:sdcm.tester          p:ERROR >     averages = self._get_average_results(es_docs=self._get_all_benchmark_results(),
< t:2022-04-06 14:38:59,909 f:tester.py       l:140  c:sdcm.tester          p:ERROR >   File "/home/ls/repos/sct/loader-with-ics-v18/sdcm/utils/benchmarks.py", line 195, in _get_average_results
< t:2022-04-06 14:38:59,909 f:tester.py       l:140  c:sdcm.tester          p:ERROR >     cassandra_fio_read_bw=item["cassandra_fio_lcs_64k_read"]["read"]["bw"],
< t:2022-04-06 14:38:59,909 f:tester.py       l:140  c:sdcm.tester          p:ERROR > KeyError: 'cassandra_fio_lcs_64k_read'
```

I've logged into failing node and I could install `make` package after issuing `sudo apt update`.
Do we miss this step when installing benchmarking tools?

**Comment by soyacz** [comment]
[logs.tar.gz](https://github.com/scylladb/scylla-cluster-tests/files/8427209/logs.tar.gz)
