### ISSUE TITLE
clean_instances_azure failed: KeyError: 'TestId'

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-cluster-tests#4609]
I ran:
`hydra clean-resources --user julia.yakovlev`

There was docker only in my resources.

the command failed with:
```
Traceback (most recent call last):
  File "/home/juliayakovlev/scylla_repo/scylla-cluster-tests/./sct.py", line 1402, in <module>
    cli()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/juliayakovlev/scylla_repo/scylla-cluster-tests/./sct.py", line 299, in clean_resources
    clean_func(param, dry_run=dry_run)
  File "/home/juliayakovlev/scylla_repo/scylla-cluster-tests/sdcm/utils/common.py", line 514, in clean_cloud_resources
    clean_instances_azure(tags_dict, dry_run=dry_run)
  File "/home/juliayakovlev/scylla_repo/scylla-cluster-tests/sdcm/utils/common.py", line 1065, in clean_instances_azure
    test_id = tags_dict.pop("TestId")
KeyError: 'TestId'
```

**Comment by fgelcer** [comment]
same as #4546

**Comment by soyacz** [comment]
@juliayakovlev it should be fixed with https://github.com/scylladb/scylla-cluster-tests/pull/4554
