### ISSUE TITLE
Subtest got error after the test was finished despite the subtest was completed

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-cluster-tests#4628]
## Installation details

Kernel Version: 3.10.0-957.27.2.el7.x86_64
Scylla version (or git commit hash): `5.1.dev-20220421.cc40685c288f` with build-id `fde9a351743afef6ce27c7787712211d9ee8f41f`
Cluster size: 1 nodes (docker)

Scylla Nodes used in this run:
**No resources left at the end of the run**

OS / Image: `scylladb/scylla-nightly` (docker: undefined_region)

Test: `artifacts-docker-test`
Test id: `bd2c219d-8e4a-453b-ab28-f309810256b0`
Test name: `scylla-master/artifacts/artifacts-docker-test`
Test config file(s):

- [docker.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/49f587f9438801523500dc03d8de8eca9fbe53fb/test-cases/artifacts/docker.yaml)

## Issue description

`TestFrameworkEvent` error happened after `TEST_END`.
```
< t:2022-04-21 10:18:56,974 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2022-04-21 10:18:56.972: (InfoEvent Severity.NORMAL) period_type=not-set event_id=706a642d-0208-4a98-b812-ee2da70654b6
: message=TEST_END
```

`subTest("check Scylla server after stop/start")` failed:
```
< t:2022-04-21 10:19:00,131 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2022-04-21 10:19:00.129: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=ec8dd357-fd64-4021-bfa2-3a6
c42a78bfc, source=ArtifactsTest.test_scylla_service (artifacts_test.ArtifactsTest) [check Scylla server after stop/start]() message=Traceback (most recent call last):
< t:2022-04-21 10:19:00,131 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
< t:2022-04-21 10:19:00,131 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     conn = connection.create_connection(
< t:2022-04-21 10:19:00,131 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
< t:2022-04-21 10:19:00,131 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     raise err
< t:2022-04-21 10:19:00,131 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
< t:2022-04-21 10:19:00,131 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     sock.connect(sa)
< t:2022-04-21 10:19:00,131 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > TimeoutError: timed out
< t:2022-04-21 10:19:00,131 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 
< t:2022-04-21 10:19:00,131 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > During handling of the above exception, another exception occurred:
< t:2022-04-21 10:19:00,131 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 
< t:2022-04-21 10:19:00,131 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > Traceback (most recent call last):
< t:2022-04-21 10:19:00,131 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
< t:2022-04-21 10:19:00,131 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     httplib_response = self._make_request(
< t:2022-04-21 10:19:00,131 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
< t:2022-04-21 10:19:00,131 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     self._validate_conn(conn)
< t:2022-04-21 10:19:00,131 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
< t:2022-04-21 10:19:00,131 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     conn.connect()
< t:2022-04-21 10:19:00,131 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
< t:2022-04-21 10:19:00,131 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     self.sock = conn = self._new_conn()
< t:2022-04-21 10:19:00,131 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 179, in _new_conn
< t:2022-04-21 10:19:00,131 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     raise ConnectTimeoutError(
< t:2022-04-21 10:19:00,131 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7fdc442174c0>, 'Connection to api4.my-ip.io timed out. (connect timeout=10)')

< t:2022-04-21 10:19:00,131 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > Traceback (most recent call last):
< t:2022-04-21 10:19:00,131 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-docker-test/scylla-cluster-tests/artifacts_test.py", line 340, in test_scylla_service
< t:2022-04-21 10:19:00,131 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     version_id_after_stop = self.check_scylla_version_in_housekeepingdb(
< t:2022-04-21 10:19:00,131 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-docker-test/scylla-cluster-tests/artifacts_test.py", line 64, in check_scylla_version_in_housekeepingdb
< t:2022-04-21 10:19:00,131 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     public_ip_address = self.node.host_public_ip_address if backend == 'docker' else self.node.public_ip_address
< t:2022-04-21 10:19:00,131 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/usr/local/lib/python3.10/functools.py", line 970, in __get__
< t:2022-04-21 10:19:00,131 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     val = self.func(instance)
< t:2022-04-21 10:19:00,131 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-docker-test/scylla-cluster-tests/sdcm/cluster_docker.py", line 97, in host_public_ip_address
< t:2022-04-21 10:19:00,131 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     return get_my_public_ip()
< t:2022-04-21 10:19:00,131 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-docker-test/scylla-cluster-tests/sdcm/utils/net.py", line 28, in get_my_public_ip
< t:2022-04-21 10:19:00,131 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     result = requests.get(hostname, timeout=10)
< t:2022-04-21 10:19:00,131 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 75, in get
< t:2022-04-21 10:19:00,131 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     return request('get', url, params=params, **kwargs)
< t:2022-04-21 10:19:00,131 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 61, in request
< t:2022-04-21 10:19:00,131 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     return session.request(method=method, url=url, **kwargs)
< t:2022-04-21 10:19:00,131 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 542, in request
< t:2022-04-21 10:19:00,131 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     resp = self.send(prep, **send_kwargs)
< t:2022-04-21 10:19:00,131 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 655, in send
< t:2022-04-21 10:19:00,131 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     r = adapter.send(request, **kwargs)
< t:2022-04-21 10:19:00,131 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 504, in send
< t:2022-04-21 10:19:00,131 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     raise ConnectTimeout(e, request=request)
< t:2022-04-21 10:19:00,131 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api4.my-ip.io', port=443): Max retries exceeded with url: /ip (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fdc442174c0>, 'Connection to api4.my-ip.io timed out. (connect timeout=10)'))
```

But by all events list looks like all steps were performed successfully. So it's not clear why the subtest tread failed.

- Restore Monitor Stack command: `$ hydra investigate show-monitor bd2c219d-8e4a-453b-ab28-f309810256b0`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=bd2c219d-8e4a-453b-ab28-f309810256b0)
- Show all stored logs command: `$ hydra investigate show-logs bd2c219d-8e4a-453b-ab28-f309810256b0`

## Logs:
- **db-cluster-bd2c219d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/bd2c219d-8e4a-453b-ab28-f309810256b0/20220421_101945/db-cluster-bd2c219d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/bd2c219d-8e4a-453b-ab28-f309810256b0/20220421_101945/db-cluster-bd2c219d.tar.gz)
- **monitor-set-bd2c219d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/bd2c219d-8e4a-453b-ab28-f309810256b0/20220421_101945/monitor-set-bd2c219d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/bd2c219d-8e4a-453b-ab28-f309810256b0/20220421_101945/monitor-set-bd2c219d.tar.gz)
- **sct-runner-bd2c219d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/bd2c219d-8e4a-453b-ab28-f309810256b0/20220421_101945/sct-runner-bd2c219d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/bd2c219d-8e4a-453b-ab28-f309810256b0/20220421_101945/sct-runner-bd2c219d.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-docker-test/439/)

**Comment by fruch** [comment]
@juliayakovlev see the implementation in https://github.com/scylladb/siren-tests/blob/master/common.py#L882
the one in SCT doesn't continure to the next service on case of failures to connect, since the try/expect clause if different then in siren, and don't cover the actual GET call
