### ISSUE TITLE
Add-Remove-DC nemesis failed with a connection timeout

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#4629]
## Installation details

Kernel Version: 5.13.0-1021-aws
Scylla version (or git commit hash): `2022.1~rc3-20220406.5cc3b678c` with build-id `48dfae0735cd8efc4ae2f5c777beaee2a1e89f4a`
Cluster size: 5 nodes (i3.2xlarge)

Scylla Nodes used in this run:
- longevity-large-partitions-8h-2022--db-node-d764b84e-6 (16.171.64.162 | 10.0.2.204) (shards: 8)
- longevity-large-partitions-8h-2022--db-node-d764b84e-5 (13.49.0.224 | 10.0.0.215) (shards: 8)
- longevity-large-partitions-8h-2022--db-node-d764b84e-4 (16.16.68.73 | 10.0.1.99) (shards: 8)
- longevity-large-partitions-8h-2022--db-node-d764b84e-3 (13.51.156.251 | 10.0.3.103) (shards: 8)
- longevity-large-partitions-8h-2022--db-node-d764b84e-2 (13.48.24.141 | 10.0.3.97) (shards: 8)
- longevity-large-partitions-8h-2022--db-node-d764b84e-1 (16.16.56.100 | 10.0.0.125) (shards: 8)

OS / Image: `ami-001615890d21c8784` (aws: eu-north-1)

Test: `longevity-large-partition-8h-test`
Test id: `d764b84e-69c3-4e38-b5d1-4e9398c56890`
Test name: `enterprise-2022.1/longevity/longevity-large-partition-8h-test`
Test config file(s):

- [longevity-large-partition-8h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/7f5f150f522fd17c764c1b64e1a8f750c7a8cf18/test-cases/longevity/longevity-large-partition-8h.yaml)

## Issue description

**>>>>>>>**
Add-Remove-DC nemesis failed with a connection timeout
```
Nemesis Information
Class: Sisyphus
Name: disrupt_add_remove_dc
Status: Failed
Duration: 24 minutes, 14 seconds
Failure reason

                                            Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 515, in connect
    self._connect()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 531, in _connect
    self._init_ssh()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 332, in _init_ssh
    self.session.handshake(self.sock)
  File "ssh2/session.pyx", line 138, in ssh2.session.Session.handshake
  File "ssh2/utils.pyx", line 214, in ssh2.utils.handle_error_codes
ssh2.exceptions.SocketRecvError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 588, in run
    self.connect()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 524, in connect
    raise ConnectTimeout(ex_msg) from exc
sdcm.remote.libssh2_client.exceptions.ConnectTimeout: Failed to connect in 60 seconds, last error: (SocketRecvError)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run
    return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
    result = connection.run(**command_kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 591, in run
    return self._complete_run(
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 649, in _complete_run
    raise exception
sdcm.remote.libssh2_client.exceptions.FailedToRunCommand: Failed to run a command due to exception!

Command: 'cp /etc/scylla/cassandra/logback-tools.xml .'

Stdout:



Stderr:



Exception:  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 588, in run
    self.connect()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 524, in connect
    raise ConnectTimeout(ex_msg) from exc

Failed to connect in 60 seconds, last error: (SocketRecvError)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3307, in wrapper
    result = method(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3214, in disrupt_add_remove_dc
    self._write_read_data_to_multi_dc_keyspace(datacenters)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3159, in _write_read_data_to_multi_dc_keyspace
    self.tester.verify_stress_thread(cs_thread_pool=write_thread)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 1679, in verify_stress_thread
    results, errors = cs_thread_pool.verify_results()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/stress_thread.py", line 276, in verify_results
    results.append(future.result())
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/stress_thread.py", line 189, in _run_stress
    node.remoter.run("cp /etc/scylla/cassandra/logback-tools.xml .", ignore_status=True)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run
    result = _run()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 64, in inner
    return func(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 606, in _run
    if self._run_on_retryable_exception(exc, new_session):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_libssh_cmd_runner.py", line 78, in _run_on_retryable_exception
    raise RetryableNetworkException(str(exc), original=exc)
sdcm.remote.base.RetryableNetworkException: Failed to run a command due to exception!

Command: 'cp /etc/scylla/cassandra/logback-tools.xml .'

Stdout:



Stderr:



Exception:  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 588, in run
    self.connect()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 524, in connect
    raise ConnectTimeout(ex_msg) from exc

Failed to connect in 60 seconds, last error: (SocketRecvError)
```
**<<<<<<<**

- Restore Monitor Stack command: `$ hydra investigate show-monitor d764b84e-69c3-4e38-b5d1-4e9398c56890`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=d764b84e-69c3-4e38-b5d1-4e9398c56890)
- Show all stored logs command: `$ hydra investigate show-logs d764b84e-69c3-4e38-b5d1-4e9398c56890`

## Logs:
- **db-cluster-d764b84e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d764b84e-69c3-4e38-b5d1-4e9398c56890/20220413_182036/db-cluster-d764b84e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d764b84e-69c3-4e38-b5d1-4e9398c56890/20220413_182036/db-cluster-d764b84e.tar.gz)
- **monitor-set-d764b84e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d764b84e-69c3-4e38-b5d1-4e9398c56890/20220413_182036/monitor-set-d764b84e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d764b84e-69c3-4e38-b5d1-4e9398c56890/20220413_182036/monitor-set-d764b84e.tar.gz)
- **loader-set-d764b84e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d764b84e-69c3-4e38-b5d1-4e9398c56890/20220413_182036/loader-set-d764b84e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d764b84e-69c3-4e38-b5d1-4e9398c56890/20220413_182036/loader-set-d764b84e.tar.gz)
- **sct-runner-d764b84e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d764b84e-69c3-4e38-b5d1-4e9398c56890/20220413_182036/sct-runner-d764b84e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d764b84e-69c3-4e38-b5d1-4e9398c56890/20220413_182036/sct-runner-d764b84e.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2022.1/job/longevity/job/longevity-large-partition-8h-test/2/)

**Comment by yarongilor** [comment]
@soyacz , please advise if this failure is familiar. If not, i can investigate logs further more.

**Comment by soyacz** [comment]
@yarongilor this looks like some issue with loader - from these logs I see sct couldn't perform some file copy on loader within given timeout. I made a fix to reduce number of loader that take part in this test: https://github.com/scylladb/scylla-cluster-tests/pull/4744 hopefully it will help for this too.

Anyway, fix rather should go to ssh client we use (or prolong timeout).

I propose to close it and reopen when issue persists.

**Comment by yarongilor** [comment]
not reproduced.
