### ISSUE TITLE
RemoveNodeThenAddNode failure on removing node

### ISSUE THREAD

**Issue by KnifeyMoloko** [scylladb/scylla-cluster-tests#4667]
## Installation details

Kernel Version: 5.13.0-1022-aws
Scylla version (or git commit hash): `5.1.dev-20220421.cc40685c288f` with build-id `fde9a351743afef6ce27c7787712211d9ee8f41f`
Cluster size: 4 nodes (i3en.2xlarge)

Scylla Nodes used in this run:
- longevity-twcs-48h-master-db-node-acecfe6e-9 (54.194.242.138 | 10.0.1.123) (shards: 8)
- longevity-twcs-48h-master-db-node-acecfe6e-8 (34.243.183.187 | 10.0.0.144) (shards: 8)
- longevity-twcs-48h-master-db-node-acecfe6e-7 (34.240.111.77 | 10.0.3.13) (shards: 8)
- longevity-twcs-48h-master-db-node-acecfe6e-6 (18.202.225.136 | 10.0.0.71) (shards: 8)
- longevity-twcs-48h-master-db-node-acecfe6e-5 (52.215.235.205 | 10.0.2.81) (shards: 8)
- longevity-twcs-48h-master-db-node-acecfe6e-4 (34.244.12.198 | 10.0.1.34) (shards: 8)
- longevity-twcs-48h-master-db-node-acecfe6e-3 (34.242.229.178 | 10.0.0.33) (shards: 8)
- longevity-twcs-48h-master-db-node-acecfe6e-2 (52.208.144.39 | 10.0.3.200) (shards: 8)
- longevity-twcs-48h-master-db-node-acecfe6e-1 (34.243.226.229 | 10.0.3.228) (shards: 8)

OS / Image: `ami-07d353a9e8649b3a1` (aws: eu-west-1)

Test: `longevity-twcs-48h-test`
Test id: `acecfe6e-3e7b-436a-9f53-023a9d25b9ee`
Test name: `scylla-master/longevity/longevity-twcs-48h-test`
Test config file(s):

- [longevity-twcs-48h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/f485155a9f8b359c8e8da8d07cd3d4396aa5ca27/test-cases/longevity/longevity-twcs-48h.yaml)

## Issue description

**>>>>>>>**
During RemoveNodeThenAddNode nemesis removing one of the nodes did not finish in time:
```
  Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3309, in wrapper
    result = method(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2532, in disrupt_remove_node_then_add_node
    assert removed_node_status is None,\
AssertionError: Node was not removed properly (Node status:{'state': 'DN', 'load': '25.3GB', 'tokens': '256', 'owns': '?', 'host_id': 'f2d01a78-fbf2-4bfe-9b16-2bb4016e3eab', 'rack': '1a'})
```

`sct.log` around the time of the failure:
```
< t:2022-04-24 02:11:42,642 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 022-04-24T02:11:42+00:00 longevity-twcs-48h-master-db-node-acecfe6e-1 ! WARNING |  [shard 6] large_data - Writing large partition scylla_bench/test: 352187318272 (3955395 bytes) to me-47966-big-Data.db
< t:2022-04-24 02:11:42,642 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-04-24T02:11:42+00:00 longevity-twcs-48h-master-db-node-acecfe6e-1 ! WARNING |  [shard 0] large_data - Writing large partition scylla_bench/test: 841813590016 (8412666 bytes) to me-47952-big-Data.db
< t:2022-04-24 02:11:42,643 f:events_processes.py l:146  c:sdcm.sct_events.events_processes p:DEBUG > Get process `MainDevice' from EventsProcessesRegistry[lod_dir=/home/ubuntu/sct-results/20220422-030637-445971,id=0x7f12ad0d49a0,default=True]
< t:2022-04-24 02:11:42,643 f:events_processes.py l:146  c:sdcm.sct_events.events_processes p:DEBUG > Get process `MainDevice' from EventsProcessesRegistry[lod_dir=/home/ubuntu/sct-results/20220422-030637-445971,id=0x7f12ad0d49a0,default=True]
< t:2022-04-24 02:11:42,644 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2022-04-24 02:11:42.642 <22-04-24 02:11:42.000>: (DatabaseLogEvent Severity.WARNING) period_type=one-time event_id=083c0584-fbd7-4b29-98b1-8f274b74cd41: type=WARNING regex=!\s*?WARNING  line_number=342048 node=longevity-twcs-48h-master-db-node-acecfe6e-1
< t:2022-04-24 02:11:42,644 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 022-04-24T02:11:42+00:00 longevity-twcs-48h-master-db-node-acecfe6e-1 ! WARNING |  [shard 6] large_data - Writing large partition scylla_bench/test: 352187318272 (3955395 bytes) to me-47966-big-Data.db
< t:2022-04-24 02:11:42,645 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2022-04-24 02:11:42.642 <2022-04-24 02:11:42.000>: (DatabaseLogEvent Severity.WARNING) period_type=one-time event_id=083c0584-fbd7-4b29-98b1-8f274b74cd41: type=WARNING regex=!\s*?WARNING  line_number=342049 node=longevity-twcs-48h-master-db-node-acecfe6e-1
< t:2022-04-24 02:11:42,645 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2022-04-24T02:11:42+00:00 longevity-twcs-48h-master-db-node-acecfe6e-1 ! WARNING |  [shard 0] large_data - Writing large partition scylla_bench/test: 841813590016 (8412666 bytes) to me-47952-big-Data.db
< t:2022-04-24 02:11:42,860 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 2022/04/24 02:06:00 Cannot achieve consistency level for cl QUORUM. Requires 2, alive 1
< t:2022-04-24 02:11:42,910 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 2022/04/24 02:05:57 Cannot achieve consistency level for cl QUORUM. Requires 2, alive 1
< t:2022-04-24 02:11:42,928 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 2022/04/24 02:07:33 Cannot achieve consistency level for cl QUORUM. Requires 2, alive 1
< t:2022-04-24 02:11:43,010 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 022-04-24T02:11:42+00:00 longevity-twcs-48h-master-db-node-acecfe6e-9 !     ERR |  [shard 0] rpc - client 10.0.0.33:7000: fail to connect: No route to host
< t:2022-04-24 02:11:43,046 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 022-04-24T02:11:42+00:00 longevity-twcs-48h-master-db-node-acecfe6e-7 ! WARNING |  [shard 1] large_data - Writing large partition scylla_bench/test: 618475290624 (83372794 bytes) to me-3513-big-Data.db
< t:2022-04-24 02:11:43,046 f:events_processes.py l:146  c:sdcm.sct_events.events_processes p:DEBUG > Get process `MainDevice' from EventsProcessesRegistry[lod_dir=/home/ubuntu/sct-results/20220422-030637-445971,id=0x7f12ad0d49a0,default=True]
< t:2022-04-24 02:11:43,047 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2022-04-24 02:11:43.046 <22-04-24 02:11:42.000>: (DatabaseLogEvent Severity.WARNING) period_type=one-time event_id=083c0584-fbd7-4b29-98b1-8f274b74cd41: type=WARNING regex=!\s*?WARNING  line_number=349979 node=longevity-twcs-48h-master-db-node-acecfe6e-7
< t:2022-04-24 02:11:43,047 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 022-04-24T02:11:42+00:00 longevity-twcs-48h-master-db-node-acecfe6e-7 ! WARNING |  [shard 1] large_data - Writing large partition scylla_bench/test: 618475290624 (83372794 bytes) to me-3513-big-Data.db
< t:2022-04-24 02:11:43,055 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 2022/04/24 02:05:56 Cannot achieve consistency level for cl QUORUM. Requires 2, alive 1
< t:2022-04-24 02:11:43,057 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 2022/04/24 02:05:58 Cannot achieve consistency level for cl QUORUM. Requires 2, alive 1
< t:2022-04-24 02:11:43,059 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 2022/04/24 02:05:56 Cannot achieve consistency level for cl QUORUM. Requires 2, alive 1
< t:2022-04-24 02:11:43,073 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 2022/04/24 02:05:56 Cannot achieve consistency level for cl QUORUM. Requires 2, alive 1
< t:2022-04-24 02:11:43,096 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 2022/04/24 02:07:34 Cannot achieve consistency level for cl QUORUM. Requires 2, alive 1
< t:2022-04-24 02:11:43,124 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 2022/04/24 02:07:36 Cannot achieve consistency level for cl QUORUM. Requires 2, alive 1
< t:2022-04-24 02:11:43,361 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 2022/04/24 02:06:00 Cannot achieve consistency level for cl QUORUM. Requires 2, alive 1
< t:2022-04-24 02:11:43,410 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 2022/04/24 02:05:57 Cannot achieve consistency level for cl QUORUM. Requires 2, alive 1
< t:2022-04-24 02:11:43,428 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 2022/04/24 02:07:33 Cannot achieve consistency level for cl QUORUM. Requires 2, alive 1
< t:2022-04-24 02:11:43,555 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 2022/04/24 02:05:56 Cannot achieve consistency level for cl QUORUM. Requires 2, alive 1
< t:2022-04-24 02:11:43,557 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 2022/04/24 02:05:58 Cannot achieve consistency level for cl QUORUM. Requires 2, alive 1
< t:2022-04-24 02:11:43,559 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 2022/04/24 02:05:56 Cannot achieve consistency level for cl QUORUM. Requires 2, alive 1
< t:2022-04-24 02:11:43,573 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 2022/04/24 02:05:56 Cannot achieve consistency level for cl QUORUM. Requires 2, alive 1
< t:2022-04-24 02:11:43,596 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 2022/04/24 02:07:34 Cannot achieve consistency level for cl QUORUM. Requires 2, alive 1
< t:2022-04-24 02:11:43,624 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 2022/04/24 02:07:36 Cannot achieve consistency level for cl QUORUM. Requires 2, alive 1
...
...
...
< t:2022-04-24 02:11:45,614 f:cluster.py      l:2760 c:sdcm.cluster         p:DEBUG >   X1:ALTERNATOR_STREAMS,ALTERNATOR_TTL,CDC,CDC_GENERATIONS_V2,COMPUTED_COLUMNS,CORRECT_COUNTER_ORDER,CORRECT_IDX_TOKEN_IN_SECONDARY_INDEX,CORRECT_NON_COMPOUND_RANGE_TOMBSTONES,CORRECT_STATIC_COMPACT_IN_MC,COUNTERS,DIGEST_FOR_NULL_VALUES,DIGEST_INSENSITIVE_TO_EXPIRY,DIGEST_MULTIPARTITION_READ,HINTED_HANDOFF_SEPARATE_CONNECTION,INDEXES,KEYSPACE_STORAGE_OPTIONS,LARGE_PARTITIONS,LA_SSTABLE_FORMAT,LWT,MATERIALIZED_VIEWS,MC_SSTABLE_FORMAT,MD_SSTABLE_FORMAT,ME_SSTABLE_FORMAT,NONFROZEN_UDTS,PARALLELIZED_AGGREGATION,PER_TABLE_CACHING,PER_TABLE_PARTITIONERS,RANGE_SCAN_DATA_VARIANT,RANGE_TOMBSTONES,ROLES,ROW_LEVEL_REPAIR,SCHEMA_TABLES_V3,SEPARATE_PAGE_SIZE_AND_SAFETY_LIMIT,STREAM_WITH_RPC_STREAM,TOMBSTONE_GC_OPTIONS,TRUNCATION_TABLE,UDA,UNBOUNDED_RANGE_TOMBSTONES,VIEW_VIRTUAL_COLUMNS,WRITE_FAILURE_REPLY,XXHASH
< t:2022-04-24 02:11:45,614 f:cluster.py      l:2760 c:sdcm.cluster         p:DEBUG >   X3:3
< t:2022-04-24 02:11:45,614 f:cluster.py      l:2760 c:sdcm.cluster         p:DEBUG >   DC:eu-west
< t:2022-04-24 02:11:45,614 f:cluster.py      l:2760 c:sdcm.cluster         p:DEBUG >   X8:v2;1650613877168;3f869334-1cb7-473b-a677-7cc2f2dbe68b
< t:2022-04-24 02:11:45,614 f:cluster.py      l:2760 c:sdcm.cluster         p:DEBUG >   RACK:1a
< t:2022-04-24 02:11:45,614 f:cluster.py      l:2760 c:sdcm.cluster         p:DEBUG >   HOST_ID:2f80916e-12aa-40c3-bbaf-a3d2c2949d44
< t:2022-04-24 02:11:45,614 f:cluster.py      l:2760 c:sdcm.cluster         p:DEBUG >   X2:system_distributed.cdc_streams_descriptions_v2:0.000000;system_auth.role_members:0.000000;system_auth.roles:1.000000;system_traces.node_slow_log:0.000000;system_traces.sessions:0.000000;system_distributed.cdc_generation_timestamps:0.004550;scylla_bench.test:0.986957;system_distributed.view_build_status:0.000000;system_distributed_everywhere.cdc_generation_descriptions_v2:0.000000;system_distributed.service_levels:1.000000;ks_truncate_large_partition.test_counters:0.000000;system_auth.role_attributes:0.000000;ks_truncate_large_partition.test_table:0.000000;system_traces.sessions_time_idx:0.000000;system_traces.node_slow_log_time_idx:0.000000;scylla_bench.test_counters:0.000000;system_traces.events:0.000000;
< t:2022-04-24 02:11:45,614 f:cluster.py      l:2760 c:sdcm.cluster         p:DEBUG >   X7:12   
< t:2022-04-24 02:11:45,614 f:cluster.py      l:2760 c:sdcm.cluster         p:DEBUG >   X4:1
< t:2022-04-24 02:11:45,614 f:cluster.py      l:2760 c:sdcm.cluster         p:DEBUG >   SCHEMA:4ba369a1-6a9b-3f33-8028-f08f1cbb059e
< t:2022-04-24 02:11:45,614 f:cluster.py      l:2760 c:sdcm.cluster         p:DEBUG >   RELEASE_VERSION:3.0.8
< t:2022-04-24 02:11:45,614 f:cluster.py      l:2760 c:sdcm.cluster         p:DEBUG >   X9:org.apache.cassandra.locator.Ec2Snitch
< t:2022-04-24 02:11:45,614 f:cluster.py      l:2760 c:sdcm.cluster         p:DEBUG > 
< t:2022-04-24 02:11:45,614 f:cluster.py      l:2760 c:sdcm.cluster         p:DEBUG > (no stderr) 
< t:2022-04-24 02:11:45,614 f:cluster.py      l:2777 c:sdcm.cluster         p:DEBUG > Get gossip info. Node with IP 10.0.1.34 is not found in the cluster. Node status is: LEFT
< t:2022-04-24 02:11:45,614 f:cluster.py      l:2777 c:sdcm.cluster         p:DEBUG > Get gossip info. Node with IP 10.0.2.81 is not found in the cluster. Node status is: LEFT
< t:2022-04-24 02:11:45,614 f:cluster.py      l:2777 c:sdcm.cluster         p:DEBUG > Get gossip info. Node with IP 10.0.0.144 is not found in the cluster. Node status is: LEFT
< t:2022-04-24 02:11:45,614 f:cluster.py      l:2777 c:sdcm.cluster         p:DEBUG > Get gossip info. Node with IP 10.0.0.33 is not found in the cluster. Node status is: shutdown
< t:2022-04-24 02:11:45,614 f:cluster.py      l:2777 c:sdcm.cluster         p:DEBUG > Get gossip info. Node with IP 10.0.3.200 is not found in the cluster. Node status is: LEFT
< t:2022-04-24 02:11:45,614 f:health_checker.py l:41   c:sdcm.utils.health_checker p:INFO  > Status for regular node longevity-twcs-48h-master-db-node-acecfe6e-9
< t:2022-04-24 02:11:45,614 f:cluster.py      l:2685 c:sdcm.cluster         p:DEBUG > Node `longevity-twcs-48h-master-db-node-acecfe6e-9' is healthy 
< t:2022-04-24 02:11:45,615 f:events_processes.py l:146  c:sdcm.sct_events.events_processes p:DEBUG > Get process `MainDevice' from EventsProcessesRegistry[lod_dir=/home/ubuntu/sct-results/20220422-030637-445971,id=0x7f12ad0d49a0,default=True]
< t:2022-04-24 02:11:45,615 f:nemesis.py      l:3351 c:sdcm.nemesis         p:ERROR > sdcm.nemesis.SisyphusMonkey: num nodes before 4 and nodes after 3 does not match
< t:2022-04-24 02:11:45,616 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2022-04-24 02:11:45.615: (ClusterHealthValidatorEvent Severity.NORMAL) period_type=end event_id=a3c77093-6bf2-4f28-95b3-5a825e1e0f1b duration=3m41s message=Cluster health check finished
```
**<<<<<<<**

- Restore Monitor Stack command: `$ hydra investigate show-monitor acecfe6e-3e7b-436a-9f53-023a9d25b9ee`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=acecfe6e-3e7b-436a-9f53-023a9d25b9ee)
- Show all stored logs command: `$ hydra investigate show-logs acecfe6e-3e7b-436a-9f53-023a9d25b9ee`

## Logs:
- **db-cluster-acecfe6e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/db-cluster-acecfe6e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/db-cluster-acecfe6e.tar.gz)
- **monitor-set-acecfe6e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/monitor-set-acecfe6e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/monitor-set-acecfe6e.tar.gz)
- **loader-set-acecfe6e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/loader-set-acecfe6e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/loader-set-acecfe6e.tar.gz)
- **normal-acecfe6e.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/normal-acecfe6e.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/normal-acecfe6e.log.tar.gz)
- **summary-acecfe6e.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/summary-acecfe6e.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/summary-acecfe6e.log.tar.gz)
- **events-acecfe6e.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/events-acecfe6e.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/events-acecfe6e.log.tar.gz)
- **output-acecfe6e.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/output-acecfe6e.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/output-acecfe6e.log.tar.gz)
- **debug-acecfe6e.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/debug-acecfe6e.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/debug-acecfe6e.log.tar.gz)
- **sct-acecfe6e.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/sct-acecfe6e.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/sct-acecfe6e.log.tar.gz)
- **error-acecfe6e.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/error-acecfe6e.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/error-acecfe6e.log.tar.gz)
- **critical-acecfe6e.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/critical-acecfe6e.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/critical-acecfe6e.log.tar.gz)
- **raw_events-acecfe6e.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/raw_events-acecfe6e.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/raw_events-acecfe6e.log.tar.gz)
- **warning-acecfe6e.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/warning-acecfe6e.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/warning-acecfe6e.log.tar.gz)
- **email_data-acecfe6e.json.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/email_data-acecfe6e.json.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/email_data-acecfe6e.json.tar.gz)
- **argus-acecfe6e.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/argus-acecfe6e.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/argus-acecfe6e.log.tar.gz)
- **left_processes-acecfe6e.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/left_processes-acecfe6e.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/left_processes-acecfe6e.log.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-twcs-48h-test/29/)

**Comment by KnifeyMoloko** [comment]
Closing as duplicate to https://github.com/scylladb/scylladb/issues/10460
