### ISSUE TITLE
disruption_start_stop_compaction failed by timeout because stop_major_compaction method was not executed

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla-cluster-tests#4687]
### Prerequisites

* [ ] Are you rebased to master ?
* [x] Is it reproducible ? Periodically
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: branch-2022.1
* **scylla**: 2022.1.rc3
* ** other versions: master, branch-5.0

### Logs
* test_id: 87d4d86d-7e51-4072-a066-cd2cf4633f8a
* job log: https://cloudius-jenkins-test.s3.amazonaws.com/87d4d86d-7e51-4072-a066-cd2cf4633f8a/20220429_203259/sct-87d4d86d.log.tar.gz

### Description
During job  longevity-cdc-3d-400gb-test on version 2022.1([job link](https://jenkins.scylladb.com/job/enterprise-2022.1/job/longevity/job/longevity-cdc-3d-400gb-test/2/)) Nemesis start_stop_major_compaction was failed by timeout
```

                                            Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3310, in wrapper
    result = method(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 513, in disrupt_start_stop_major_compaction
    ParallelObject(objects=[trigger_func, watch_func], timeout=timeout).call_objects()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 460, in call_objects
    return self.run(lambda x: x())
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 436, in run
    raise FuturesTimeoutError("when running on: %s" % [r.obj for r in results])
concurrent.futures._base.TimeoutError: when running on: [functools.partial(<bound method CompactionOps.trigger_major_compaction of <sdcm.utils.compaction_ops.CompactionOps object at 0x7f688272dc30>>), functools.partial(<function CompactionOps.stop_on_user_compaction_logged at 0x7f694c183130>, node=<sdcm.cluster_aws.AWSNode object at 0x7f6944529210>, mark=1, watch_for='User initiated compaction started on behalf of', timeout=360, stop_func=<bound method CompactionOps.stop_major_compaction of <sdcm.utils.compaction_ops.CompactionOps object at 0x7f688272dc30>>)]
                                       
```

After greping sct.log, it was found that required node log record was found:
```
 ~/tmp/87d4d86d-7e51-4072-a066-cd2cf4633f8a $ grep -e "User initiated compaction started on behalf of\|topping major compaction with <nodetool stop>\|Stopping compaction with nodetool\|Command '.*nodetool stop .*' duration -> " sct-87d4d86d.log
< t:2022-04-29 17:34:30,445 f:common.py       l:405  c:utils                p:DEBUG > Executing in parallel: '<lambda>' on [functools.partial(<bound method CompactionOps.trigger_major_compaction of <sdcm.utils.compaction_ops.CompactionOps object at 0x7f688272dc30>>), functools.partial(<function CompactionOps.stop_on_user_compaction_logged at 0x7f694c183130>, node=<sdcm.cluster_aws.AWSNode object at 0x7f6944529210>, mark=1, watch_for='User initiated compaction started on behalf of', timeout=360, stop_func=<bound method CompactionOps.stop_major_compaction of <sdcm.utils.compaction_ops.CompactionOps object at 0x7f688272dc30>>)]
< t:2022-04-29 17:34:30,446 f:common.py       l:392  c:utils                p:DEBUG > [ThreadPoolExecutor-61_1] <lambda>((functools.partial(<function CompactionOps.stop_on_user_compaction_logged at 0x7f694c183130>, node=<sdcm.cluster_aws.AWSNode object at 0x7f6944529210>, mark=1, watch_for='User initiated compaction started on behalf of', timeout=360, stop_func=<bound method CompactionOps.stop_major_compaction of <sdcm.utils.compaction_ops.CompactionOps object at 0x7f688272dc30>>),), {})
< t:2022-04-29 17:34:35,577 f:compaction_ops.py l:62   c:root                 p:INFO  > Stopping major compaction with <nodetool stop>
< t:2022-04-29 17:34:35,577 f:compaction_ops.py l:85   c:root                 p:INFO  > Stopping compaction with nodetool stop COMPACTION
< t:2022-04-29 17:34:35,615 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 022-04-29T17:34:35+00:00 longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-6 !    INFO |  [shard 0] compaction_manager - User initiated compaction started on behalf of keyspace1.standard1
< t:2022-04-29 17:35:01,067 f:compaction_ops.py l:102  c:root                 p:INFO  > Grepped expression found: User initiated compaction started on behalf of in log line 2022-04-29T17:34:35+00:00 longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-6 !    INFO |  [shard 0] compaction_manager - User initiated compaction started on behalf of keyspace1.standard1
< t:2022-04-29 17:40:30,447 f:nemesis.py      l:3320 c:sdcm.nemesis         p:ERROR > concurrent.futures._base.TimeoutError: when running on: [functools.partial(<bound method CompactionOps.trigger_major_compaction of <sdcm.utils.compaction_ops.CompactionOps object at 0x7f688272dc30>>), functools.partial(<function CompactionOps.stop_on_user_compaction_logged at 0x7f694c183130>, node=<sdcm.cluster_aws.AWSNode object at 0x7f6944529210>, mark=1, watch_for='User initiated compaction started on behalf of', timeout=360, stop_func=<bound method CompactionOps.stop_major_compaction of <sdcm.utils.compaction_ops.CompactionOps object at 0x7f688272dc30>>)]
```

But nodetool command with compaction stopping was not trigered or not logged:
```
~/tmp/87d4d86d-7e51-4072-a066-cd2cf4633f8a $ grep -e "nodetool stop" sct-87d4d86d.log
< t:2022-04-29 17:34:35,577 f:compaction_ops.py l:62   c:root                 p:INFO  > Stopping major compaction with <nodetool stop>
< t:2022-04-29 17:34:35,577 f:compaction_ops.py l:85   c:root                 p:INFO  > Stopping compaction with nodetool stop COMPACTION

```

it seems that thread with running nodetool stop compaction stucked or failed, and it is the reason why thread with stopping compaction exceeded timeout

**Comment by fruch** [comment]
> But nodetool command with compaction stopping was not trigered or not logged:
> 
> ```
> ~/tmp/87d4d86d-7e51-4072-a066-cd2cf4633f8a $ grep -e "nodetool stop" sct-87d4d86d.log
> < t:2022-04-29 17:34:35,577 f:compaction_ops.py l:62   c:root                 p:INFO  > Stopping major compaction with <nodetool stop>
> < t:2022-04-29 17:34:35,577 f:compaction_ops.py l:85   c:root                 p:INFO  > Stopping compaction with nodetool stop COMPACTION
> ```
> 
> it seems that thread with running nodetool stop compaction stucked or failed, and it is the reason why thread with stopping compaction exceeded timeout

@aleksbykov you are not grepping correctly:
```python 
f"{self.add_install_prefix('/usr/bin/nodetool')} {options} {sub_cmd} {args}"```

the options come between the nodetool and the `sub_cmd`, I'll guess the other thread is getting stuck, or takes more then 5min, the `trigger_major_compaction` call

**Comment by aleksbykov** [comment]
@fruch , nodetool compact was started. but nodetool stop compact  was not started or stucked.
i try different combinations but didn't find command nodetool stop - command which should stop the compaction

**Comment by fruch** [comment]
the stop happened just fine:
```
22647917:< t:2022-04-29 17:34:35,577 f:compaction_ops.py l:85   c:root                 p:INFO  > Stopping compaction with nodetool stop COMPACTION
22647919:< t:2022-04-29 17:34:35,578 f:remote_base.py  l:520  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "/usr/bin/nodetool  stop COMPACTION "...
22649882:< t:2022-04-29 17:35:01,067 f:base.py         l:142  c:RemoteLibSSH2CmdRunner p:DEBUG > Command "/usr/bin/nodetool  stop COMPACTION " finished with status 0
22649883:< t:2022-04-29 17:35:01,067 f:cluster.py      l:2628 c:sdcm.cluster_aws     p:DEBUG > Node longevity-cdc-3d-400gb-2022-1-db-node-87d4d86d-6 [54.171.197.212 | 10.0.0.183] (seed: False): Command '/usr/bin/nodetool  stop COMPACTION ' duration -> 25.488694713043515 s
```

the compaction is what took long, and timeouted, question is why it didn't stopped:
```
22647536:< t:2022-04-29 17:34:30,446 f:remote_base.py  l:520  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "curl -v -X POST "http://localhost:10000/storage_service/keyspace_compaction/keyspace1?cf=standard1""...
22824633:< t:2022-04-29 18:06:55,193 f:base.py         l:142  c:RemoteLibSSH2CmdRunner p:DEBUG > Command "curl -v -X POST "http://localhost:10000/storage_service/keyspace_compaction/keyspace1?cf=standard1"" finished with status 0
```

or the stop was too soon, before the compaction really started, or it's a scylla bug.

**Comment by aleksbykov** [comment]
Thanks @fruch . WIll check. The issue could be closed i think

**Comment by fruch** [comment]
If the stop was too soon, we need to handle it better, and somehow delay enough the stop command.

If it's proven to be a scylla issue, we can close this one

**Comment by KnifeyMoloko** [comment]
@aleksbykov From a brief look it seems to me that:

1. Major compaction was triggered.
2. The `nodetool STOP` command was triggered when it observed the compaction running via watching the logs (as expected).
3. Nemesis failed, because it didn't find the log line saying that the compaction was stopped in the timeout window, which might mean a couple of things. 
I'l take a look at the job logs, it might be as simple as the log line for the stopped compaction changed or maybe something else.

**Comment by aleksbykov** [comment]
@KnifeyMoloko @fruch thanks for help. 
it seems as scylla issue. i found in node log that compaction started by user request. next i see that compaction manager initiate stopping compactions. so here a question should nodetool wait while all compaction will be stopped? 
Next according to log, the compaction_manager stopping compaction for all tables and keyspace( here is another question,
should command nodetool stop compaction stop only user  initiated compaction or all running? and another question request to API for compaction should wait while compaction finished?

test have 8 tables in cdc_test keyspace and it looks like nodetool stop compaction attemp to stop all running compactions.

so i think the stucked process was not  related to stop compactions ( Thanks to Israel which help to find) while it is related to curl request scylla API for compactions

**Comment by KnifeyMoloko** [comment]
@aleksbykov 
> next i see that compaction manager initiate stopping compactions. so here a question should nodetool wait while all compaction will be stopped?

The issue here was actually not about `nodetool` waiting. It was actually about the REST API returning a response only after 30  minutes (!). See here:
```
< t:2022-04-29 18:06:55,193 f:base.py         l:140  c:RemoteLibSSH2CmdRunner p:DEBUG > STDERR:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
< t:2022-04-29 18:06:55,193 f:base.py         l:140  c:RemoteLibSSH2CmdRunner p:DEBUG >                                  Dload  Upload   Total   Spent    Left  Speed
< t:2022-04-29 18:06:55,193 f:base.py         l:140  c:RemoteLibSSH2CmdRunner p:DEBUG >
< t:2022-04-29 18:06:55,193 f:base.py         l:140  c:RemoteLibSSH2CmdRunner p:DEBUG >   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 127.0.0.1:10000...
< t:2022-04-29 18:06:55,193 f:base.py         l:140  c:RemoteLibSSH2CmdRunner p:DEBUG > * TCP_NODELAY set
< t:2022-04-29 18:06:55,193 f:base.py         l:140  c:RemoteLibSSH2CmdRunner p:DEBUG > * Connected to localhost (127.0.0.1) port 10000 (#0)
< t:2022-04-29 18:06:55,193 f:base.py         l:140  c:RemoteLibSSH2CmdRunner p:DEBUG > > POST /storage_service/keyspace_compaction/keyspace1?cf=standard1 HTTP/1.1
< t:2022-04-29 18:06:55,193 f:base.py         l:140  c:RemoteLibSSH2CmdRunner p:DEBUG > > Host: localhost:10000
< t:2022-04-29 18:06:55,193 f:base.py         l:140  c:RemoteLibSSH2CmdRunner p:DEBUG > > User-Agent: curl/7.68.0
< t:2022-04-29 18:06:55,193 f:base.py         l:140  c:RemoteLibSSH2CmdRunner p:DEBUG > > Accept: */*
< t:2022-04-29 18:06:55,193 f:base.py         l:140  c:RemoteLibSSH2CmdRunner p:DEBUG > >
< t:2022-04-29 18:06:55,193 f:base.py         l:142  c:RemoteLibSSH2CmdRunner p:DEBUG > Command "curl -v -X POST "http://localhost:10000/storage_service/keyspace_compaction/keyspace1?cf=standard1"" finished with status 0
< t:2022-04-29 18:06:55,193 f:common.py       l:397  c:utils                p:DEBUG > [ThreadPoolExecutor-61_0] Done.
```

^ this is actually the REST API call that triggered the major compaction in the first place.

**Comment by KnifeyMoloko** [comment]
> should command nodetool stop compaction stop only user initiated compaction or all running?

AFAIK it should only stop a certain type of compaction. In this case, it should only be major compactions, i.e. the ones triggered by the admin user. If it stops also the minor ones, I think that's a Scylla issue.

**Comment by aleksbykov** [comment]
Agree, but also it is interesting, if compaction was stopped, why the curl command was waiting so long.
I will open a scylla issue, and then close the sct issue.

Thanks for you help.

**Comment by aleksbykov** [comment]
I opened scylla issue https://github.com/scylladb/scylla/issues/10485
