### ISSUE TITLE
Data validation failed in gemini-with-nemesis test

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#4694]
## Installation details

Kernel Version: 5.13.0-1019-aws

Scylla version (or git commit hash): `5.1.dev-20220331.0c3d4091a4e8` with build-id `eb5de93b8ef258ca44d4a246138896090ae47534`

Cluster size: 3 nodes (i3.large)

Scylla Nodes used in this run:
- gemini-with-nemesis-3h-normal-maste-oracle-db-node-967abb63-1 (3.239.186.171 | 10.0.2.88) (shards: 2)
- gemini-with-nemesis-3h-normal-maste-db-node-967abb63-4 (3.91.19.88 | 10.0.1.63) (shards: 2)
- gemini-with-nemesis-3h-normal-maste-db-node-967abb63-3 (44.200.210.91 | 10.0.2.2) (shards: 2)
- gemini-with-nemesis-3h-normal-maste-db-node-967abb63-2 (3.223.136.201 | 10.0.1.155) (shards: 2)
- gemini-with-nemesis-3h-normal-maste-db-node-967abb63-1 (3.231.164.97 | 10.0.2.132) (shards: 2)

OS / Image: `ami-0e8b22c6e1c8e7c69` (aws: us-east-1)

Test: `gemini-3h-with-nemesis-test`

Test id: `967abb63-38fe-4009-a612-adcb84c511da`

Test name: `gemini/gemini-3h-with-nemesis-test`

Test config file(s):

- [gemini-3h-with-nemesis.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/aed2807e52b56f6774156d9a030be4d0fb24e302/test-cases/gemini/gemini-3h-with-nemesis.yaml)

## Issue description

>>>>>>>

Gemini test with nemesis shows some data validation errors (rows differ was cut due to large amount of text):
```
2022-04-03 05:13:18.296: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=40d47059-fb72-41d9-a06f-5d256a8c2670, source=GeminiTest.test_load_random_with_nemesis (gemini_test.GeminiTest)() message=Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/gemini_test.py", line 68, in test_load_random_with_nemesis
self.verify_results()
File "/home/ubuntu/scylla-cluster-tests/gemini_test.py", line 127, in verify_results
self.fail(self.gemini_results['results'])
AssertionError: [{'write_ops': 2515555, 'write_errors': 0, 'read_ops': 100592, 'read_errors': 1, 'errors': [{'timestamp': '2022-04-03T05:10:14.585778693Z', 'message': 'Validation failed: rows differ (-map[ck0:6354053194158753163 [...],\n  \t... // 36 identical entries\n  }\n', 'query': 'SELECT * FROM ks1.table1 WHERE pk0=1703095777 AND pk1=1358311377598850686 AND pk2=1397030731685468543 AND pk3=1978088718 '}]}]
```

I cannot find anything related in logs. 
There was one nemesis executed in this run: `disrupt_remove_node_then_add_node`
In previous runs, issues with data validation was connected to semaphore_timeouts (https://github.com/scylladb/scylla/issues/8426) - but I cannot see it here.

<<<<<<<

- Restore Monitor Stack command: `$ hydra investigate show-monitor 967abb63-38fe-4009-a612-adcb84c511da`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=967abb63-38fe-4009-a612-adcb84c511da)
- Show all stored logs command: `$ hydra investigate show-logs 967abb63-38fe-4009-a612-adcb84c511da`

## Logs:
- **db-cluster-967abb63.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/967abb63-38fe-4009-a612-adcb84c511da/20220403_052322/db-cluster-967abb63.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/967abb63-38fe-4009-a612-adcb84c511da/20220403_052322/db-cluster-967abb63.tar.gz)
- **monitor-set-967abb63.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/967abb63-38fe-4009-a612-adcb84c511da/20220403_052322/monitor-set-967abb63.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/967abb63-38fe-4009-a612-adcb84c511da/20220403_052322/monitor-set-967abb63.tar.gz)
- **loader-set-967abb63.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/967abb63-38fe-4009-a612-adcb84c511da/20220403_052322/loader-set-967abb63.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/967abb63-38fe-4009-a612-adcb84c511da/20220403_052322/loader-set-967abb63.tar.gz)
- **sct-runner-967abb63.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/967abb63-38fe-4009-a612-adcb84c511da/20220403_052322/sct-runner-967abb63.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/967abb63-38fe-4009-a612-adcb84c511da/20220403_052322/sct-runner-967abb63.tar.gz)
- **parallel-timelines-report-967abb63.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/967abb63-38fe-4009-a612-adcb84c511da/20220403_052322/parallel-timelines-report-967abb63.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/967abb63-38fe-4009-a612-adcb84c511da/20220403_052322/parallel-timelines-report-967abb63.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/gemini-/job/gemini-3h-with-nemesis-test/313/)

**Comment by roydahan** [comment]
Same comment as in: https://github.com/scylladb/scylla-cluster-tests/issues/4692#issuecomment-1117188238

**Comment by soyacz** [comment]
@roydahan @aleksbykov did you have session about it? Some outcomes?

**Comment by aleksbykov** [comment]
@soyacz , yes i will prepare session.

**Comment by roydahan** [comment]
No-one should use this as an issue.

**Comment by roydahan** [comment]
First, the metrics to see if the disk is bottelneck we should see looks on disk writes/reads and see the throughput we got during this time and compare it to the prospect of these disks.

Second, regarding the timeouts, IIRC an actual timeout is an Error in Gemini, maybe those that you see as DEBUG have a retry.

Regarding your suggestions:

> 1. like in rolling-upgrade tests, fix the seed with less stressing load
That's defeat the purpose of Gemini as a tool.
The whole idea behind this tool is to generate random loads that we don't test.

> 2. modify gemini code to not ignore timeouts (we can verify this theory by running Gemini with debug log level) - but looks it was deliberately ignored - so maybe there's some reason for that and this is not a solution.
This need to be looks at, we shouldn't ignore failed writes if that's the claim here.

> 3. Fix gemini load generator to not create such big payloads.
We can start by re-running the exact same workload with the same seed and see if we're hitting the same issue.
Then, looking at the monitor and try to see where is the bottleneck.
After we have a clear reproducer with a monitor, we can try use stronger instances and see if it solves the issue.

**Comment by soyacz** [comment]
I did some more tests and found the problem of wrong error message. More details here: https://github.com/scylladb/gemini/pull/269
I was able to reproduce this error on my local computer, and after this fix, instead of missing rows, gemini responds with error:
```
      "errors": [
             {
                 "timestamp": "2022-06-09T11:14:46.332248664+02:00",
                 "message": "Validation failed: unable to load check data from the test store: system failed: Operation failed for ks1.table1 - received 0 responses and 1 failures from 1 CL=QUORUM.",
                 "query": "SELECT * FROM ks1.table1 WHERE pk0=8222467953303024468 AND pk1=1311377606 AND ck0='XHaZWzA27MgF' AND ck1>3 AND ck1<19 "
             }
         ]

```

I did some retesting with problematic seed, and cluster was definitely overloaded (100% cpu load), thus I think mentioned fix will not solve the problem of failing Gemini test. For certain seeds cluster gets overloaded leading to this kind of errors.

**Comment by soyacz** [comment]
@roydahan @aleksbykov ^^
