### ISSUE TITLE
MultipleHardRebootNode incorrectly fails with: "Could not update CDC description table with generation"

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#4710]
## Installation details

Kernel Version: 5.13.0-1021-aws
Scylla version (or git commit hash): `5.0~rc3-20220406.f92622e0d` with build-id `2b79c4744216b294fdbd2f277940044c899156ea`
Cluster size: 5 nodes (i3.2xlarge)

Scylla Nodes used in this run:
- longevity-large-partitions-8h-5-0-db-node-a47961e7-7 (34.200.240.191 | 10.0.2.50) (shards: 8)
- longevity-large-partitions-8h-5-0-db-node-a47961e7-6 (44.204.114.148 | 10.0.0.147) (shards: 8)
- longevity-large-partitions-8h-5-0-db-node-a47961e7-5 (34.206.53.114 | 10.0.1.35) (shards: 8)
- longevity-large-partitions-8h-5-0-db-node-a47961e7-4 (35.172.235.25 | 10.0.1.164) (shards: 8)
- longevity-large-partitions-8h-5-0-db-node-a47961e7-3 (3.83.4.109 | 10.0.0.197) (shards: 8)
- longevity-large-partitions-8h-5-0-db-node-a47961e7-2 (44.204.212.120 | 10.0.1.206) (shards: 8)
- longevity-large-partitions-8h-5-0-db-node-a47961e7-1 (35.153.103.191 | 10.0.0.52) (shards: 8)

OS / Image: `ami-04ab7c26398ec6944` (aws: us-east-1)

Test: `longevity-large-partition-8h-test`
Test id: `a47961e7-57b7-4096-81d5-557ae1a34219`
Test name: `scylla-5.0/longevity/longevity-large-partition-8h-test`
Test config file(s):

- [longevity-large-partition-8h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/1cdf92e8270cc05282286e2df33d21e59bc3b712/test-cases/longevity/longevity-large-partition-8h.yaml)

## Issue description

**>>>>>>>**
scenario:
1. MultipleHardRebootNode for node 5 passed ok once.
2. then in the second time - after reboot completed, it failed with a CDC-update related error, since not success message found in log:
3. 

```
2022-05-02 22:20:02.268: (DisruptionEvent Severity.ERROR) period_type=end event_id=8d784e80-8af6-4e49-8a4b-f399e6c8e552 duration=7m14s: nemesis_name=MultipleHardRebootNode target_node=Node longevity-large-partitions-8h-5-0-db-node-a47961e7-5 [34.206.53.114 | 10.0.1.35] (seed: False) errors=After '2022-05-02T22:19:15+00:00 longevity-large-partitions-8h-5-0-db-node-a47961e7-5 ! WARNING |  [shard 0] cdc - Could not update CDC description table with generation (2022/05/02 18:15:36, 6355e121-7183-400e-9857-bc017ea4acfd): exceptions::unavailable_exception (Cannot achieve consistency level for cl QUORUM. Requires 2, alive 1). Will retry in the background.
', messages '' were not found
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3336, in wrapper
result = method(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 633, in disrupt_multiple_hard_reboot_node
raise CdcStreamsWasNotUpdated(
sdcm.nemesis.CdcStreamsWasNotUpdated: After '2022-05-02T22:19:15+00:00 longevity-large-partitions-8h-5-0-db-node-a47961e7-5 ! WARNING |  [shard 0] cdc - Could not update CDC description table with generation (2022/05/02 18:15:36, 6355e121-7183-400e-9857-bc017ea4acfd): exceptions::unavailable_exception (Cannot achieve consistency level for cl QUORUM. Requires 2, alive 1). Will retry in the background.
', messages '' were not found
```

BUT, if it is not a scylla too-big-delay or something, it looks like an SCT Stream-follow-system-log issue.
That's because the CDC success message after the second reboot was indeed found a bit later on on node-5.
So it might be a matter of too short log interval that didn't catch this late log print:

The full scenario log (and error at 22:20:02):
```
yarongilor@yaron-pc:~/Downloads/logs/sct-runner-a47961e7$ grep '< t:2022-05-02 22:' sct.log | egrep -i "Rebooting |>>>>>>>>|services to start after node reboot|Waiting for DB services to be up|Waiting for nodes to join the cluster|init - Scylla version| description table "
< t:2022-05-02 22:12:30,081 f:nemesis.py      l:1367 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.SisyphusMonkey: >>>>>>>>>>>>>Started random_disrupt_method multiple_hard_reboot_node
< t:2022-05-02 22:12:47,946 f:nemesis.py      l:615  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.SisyphusMonkey: Rebooting 1 out of 10 times
< t:2022-05-02 22:12:47,952 f:cluster.py      l:1041 c:sdcm.cluster_aws     p:DEBUG > Node longevity-large-partitions-8h-5-0-db-node-a47961e7-5 [34.206.53.114 | 10.0.1.35] (seed: False): Hardly rebooting node
< t:2022-05-02 22:14:43,383 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-05-02T22:13:03+00:00 longevity-large-partitions-8h-5-0-db-node-a47961e7-5 !    INFO |  [shard 0] init - Scylla version 5.0.rc3-0.20220406.f92622e0d shutdown complete.
< t:2022-05-02 22:14:58,644 f:nemesis.py      l:623  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.SisyphusMonkey: Waiting JMX services to start after node reboot
< t:2022-05-02 22:15:13,248 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-05-02T22:14:45+00:00 longevity-large-partitions-8h-5-0-db-node-a47961e7-5 !    INFO |  [shard 0] init - Scylla version 5.0.rc3-0.20220406.f92622e0d with build-id 2b79c4744216b294fdbd2f277940044c899156ea starting ...
< t:2022-05-02 22:15:13,309 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-05-02T22:15:02+00:00 longevity-large-partitions-8h-5-0-db-node-a47961e7-5 !    INFO |  [shard 0] cdc - Generation (2022/05/02 18:15:36, 6355e121-7183-400e-9857-bc017ea4acfd): streams description table already updated.
< t:2022-05-02 22:15:15,620 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 022-05-02T22:15:15+00:00 longevity-large-partitions-8h-5-0-db-node-a47961e7-5 !    INFO |  [shard 0] init - Scylla version 5.0.rc3-0.20220406.f92622e0d initialization completed.
< t:2022-05-02 22:17:03,005 f:nemesis.py      l:615  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.SisyphusMonkey: Rebooting 2 out of 10 times
< t:2022-05-02 22:17:03,510 f:cluster.py      l:1041 c:sdcm.cluster_aws     p:DEBUG > Node longevity-large-partitions-8h-5-0-db-node-a47961e7-5 [34.206.53.114 | 10.0.1.35] (seed: False): Hardly rebooting node
< t:2022-05-02 22:18:54,848 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-05-02T22:17:15+00:00 longevity-large-partitions-8h-5-0-db-node-a47961e7-5 !    INFO |  [shard 0] init - Scylla version 5.0.rc3-0.20220406.f92622e0d shutdown complete.
< t:2022-05-02 22:18:57,970 f:nemesis.py      l:620  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.SisyphusMonkey: Waiting scylla services to start after node reboot
< t:2022-05-02 22:18:58,559 f:wait.py         l:46   c:sdcm.wait            p:DEBUG > wait_for: Retrying Node longevity-large-partitions-8h-5-0-db-node-a47961e7-5 [34.206.53.114 | 10.0.1.35] (seed: False): Waiting for DB services to be up: attempt 1 ended with: False
< t:2022-05-02 22:19:25,687 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-05-02T22:18:56+00:00 longevity-large-partitions-8h-5-0-db-node-a47961e7-5 !    INFO |  [shard 0] init - Scylla version 5.0.rc3-0.20220406.f92622e0d with build-id 2b79c4744216b294fdbd2f277940044c899156ea starting ...
< t:2022-05-02 22:19:25,752 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-05-02T22:19:15+00:00 longevity-large-partitions-8h-5-0-db-node-a47961e7-5 ! WARNING |  [shard 0] cdc - Could not update CDC description table with generation (2022/05/02 18:15:36, 6355e121-7183-400e-9857-bc017ea4acfd): exceptions::unavailable_exception (Cannot achieve consistency level for cl QUORUM. Requires 2, alive 1). Will retry in the background.
< t:2022-05-02 22:19:25,758 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2022-05-02T22:19:15+00:00 longevity-large-partitions-8h-5-0-db-node-a47961e7-5 ! WARNING |  [shard 0] cdc - Could not update CDC description table with generation (2022/05/02 18:15:36, 6355e121-7183-400e-9857-bc017ea4acfd): exceptions::unavailable_exception (Cannot achieve consistency level for cl QUORUM. Requires 2, alive 1). Will retry in the background.
< t:2022-05-02 22:19:27,962 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-05-02T22:19:27+00:00 longevity-large-partitions-8h-5-0-db-node-a47961e7-5 !    INFO |  [shard 0] init - Scylla version 5.0.rc3-0.20220406.f92622e0d initialization completed.
< t:2022-05-02 22:20:02,268 f:nemesis.py      l:3346 c:sdcm.nemesis         p:ERROR > sdcm.nemesis.CdcStreamsWasNotUpdated: After '2022-05-02T22:19:15+00:00 longevity-large-partitions-8h-5-0-db-node-a47961e7-5 ! WARNING |  [shard 0] cdc - Could not update CDC description table with generation (2022/05/02 18:15:36, 6355e121-7183-400e-9857-bc017ea4acfd): exceptions::unavailable_exception (Cannot achieve consistency level for cl QUORUM. Requires 2, alive 1). Will retry in the background.
< t:2022-05-02 22:20:02,269 f:nemesis.py      l:241  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.SisyphusMonkey: Update nemesis info with: {'start': 1651529567, 'end': 1651530002, 'duration': 434, 'node': 'Node longevity-large-partitions-8h-5-0-db-node-a47961e7-5 [34.206.53.114 | 10.0.1.35] (seed: False)', 'subtype': 'end', 'error': "After '2022-05-02T22:19:15+00:00 longevity-large-partitions-8h-5-0-db-node-a47961e7-5 ! WARNING |  [shard 0] cdc - Could not update CDC description table with generation (2022/05/02 18:15:36, 6355e121-7183-400e-9857-bc017ea4acfd): exceptions::unavailable_exception (Cannot achieve consistency level for cl QUORUM. Requires 2, alive 1). Will retry in the background.\n', messages '' were not found", 'full_traceback': 'Traceback (most recent call last):\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3336, in wrapper\n    result = method(*args, **kwargs)\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 633, in disrupt_multiple_hard_reboot_node\n    raise CdcStreamsWasNotUpdated(\nsdcm.nemesis.CdcStreamsWasNotUpdated: After \'2022-05-02T22:19:15+00:00 longevity-large-partitions-8h-5-0-db-node-a47961e7-5 ! WARNING |  [shard 0] cdc - Could not update CDC description table with generation (2022/05/02 18:15:36, 6355e121-7183-400e-9857-bc017ea4acfd): exceptions::unavailable_exception (Cannot achieve consistency level for cl QUORUM. Requires 2, alive 1). Will retry in the background.\n\', messages \'\' were not found\n'}
< t:2022-05-02 22:20:02,270 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2022-05-02 22:20:02.268: (DisruptionEvent Severity.ERROR) period_type=end event_id=8d784e80-8af6-4e49-8a4b-f399e6c8e552 duration=7m14s: nemesis_name=MultipleHardRebootNode target_node=Node longevity-large-partitions-8h-5-0-db-node-a47961e7-5 [34.206.53.114 | 10.0.1.35] (seed: False) errors=After '2022-05-02T22:19:15+00:00 longevity-large-partitions-8h-5-0-db-node-a47961e7-5 ! WARNING |  [shard 0] cdc - Could not update CDC description table with generation (2022/05/02 18:15:36, 6355e121-7183-400e-9857-bc017ea4acfd): exceptions::unavailable_exception (Cannot achieve consistency level for cl QUORUM. Requires 2, alive 1). Will retry in the background.
< t:2022-05-02 22:20:02,270 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > sdcm.nemesis.CdcStreamsWasNotUpdated: After '2022-05-02T22:19:15+00:00 longevity-large-partitions-8h-5-0-db-node-a47961e7-5 ! WARNING |  [shard 0] cdc - Could not update CDC description table with generation (2022/05/02 18:15:36, 6355e121-7183-400e-9857-bc017ea4acfd): exceptions::unavailable_exception (Cannot achieve consistency level for cl QUORUM. Requires 2, alive 1). Will retry in the background.
< t:2022-05-02 22:20:02,301 f:base.py         l:277  c:elasticsearch        p:DEBUG > > {"test_id":"a47961e7-57b7-4096-81d5-557ae1a34219","job_name":"scylla-5.0/longevity/longevity-large-partition-8h-test","test_name":"longevity_large_partition_test.LargePartitionLongevityTest.test_large_partition_longevity","scylla_version":"5.0~rc3","scylla_git_sha":"f92622e0d","nemesis_name":"MultipleHardRebootNode","nemesis_duration":434,"start_time":"2022-05-02T22:12:47","end_time":"2022-05-02T22:20:02","target_node":"Node longevity-large-partitions-8h-5-0-db-node-a47961e7-5 [34.206.53.114 | 10.0.1.35] (seed: False)","outcome":"failure","failure_message":"After '2022-05-02T22:19:15+00:00 longevity-large-partitions-8h-5-0-db-node-a47961e7-5 ! WARNING |  [shard 0] cdc - Could not update CDC description table with generation (2022/05/02 18:15:36, 6355e121-7183-400e-9857-bc017ea4acfd): exceptions::unavailable_exception (Cannot achieve consistency level for cl QUORUM. Requires 2, alive 1). Will retry in the background.\n', messages '' were not found"}
< t:2022-05-02 22:20:02,302 f:nemesis.py      l:3373 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.SisyphusMonkey: log_info: {'start': 1651529567, 'end': 1651530002, 'duration': 434, 'node': 'Node longevity-large-partitions-8h-5-0-db-node-a47961e7-5 [34.206.53.114 | 10.0.1.35] (seed: False)', 'subtype': 'end', 'error': "After '2022-05-02T22:19:15+00:00 longevity-large-partitions-8h-5-0-db-node-a47961e7-5 ! WARNING |  [shard 0] cdc - Could not update CDC description table with generation (2022/05/02 18:15:36, 6355e121-7183-400e-9857-bc017ea4acfd): exceptions::unavailable_exception (Cannot achieve consistency level for cl QUORUM. Requires 2, alive 1). Will retry in the background.\n', messages '' were not found", 'full_traceback': 'Traceback (most recent call last):\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3336, in wrapper\n    result = method(*args, **kwargs)\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 633, in disrupt_multiple_hard_reboot_node\n    raise CdcStreamsWasNotUpdated(\nsdcm.nemesis.CdcStreamsWasNotUpdated: After \'2022-05-02T22:19:15+00:00 longevity-large-partitions-8h-5-0-db-node-a47961e7-5 ! WARNING |  [shard 0] cdc - Could not update CDC description table with generation (2022/05/02 18:15:36, 6355e121-7183-400e-9857-bc017ea4acfd): exceptions::unavailable_exception (Cannot achieve consistency level for cl QUORUM. Requires 2, alive 1). Will retry in the background.\n\', messages \'\' were not found\n'}
< t:2022-05-02 22:20:15,858 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 022-05-02T22:20:15+00:00 longevity-large-partitions-8h-5-0-db-node-a47961e7-5 !    INFO |  [shard 0] cdc - Generation (2022/05/02 18:15:36, 6355e121-7183-400e-9857-bc017ea4acfd): streams description table already updated.
```
The CDC successfull update (at 22:20:15):
```
< t:2022-05-02 22:20:15,858 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 022-05-02T22:20:15+00:00 longevity-large-partitions-8h-5-0-db-node-a47961e7-5 !    INFO |  [shard 0] cdc - Generation (2022/05/02 18:15:36, 6355e121-7183-400e-9857-bc017ea4acfd): streams description table already updated.
```
**<<<<<<<**

- Restore Monitor Stack command: `$ hydra investigate show-monitor a47961e7-57b7-4096-81d5-557ae1a34219`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=a47961e7-57b7-4096-81d5-557ae1a34219)
- Show all stored logs command: `$ hydra investigate show-logs a47961e7-57b7-4096-81d5-557ae1a34219`

## Logs:
- **db-cluster-a47961e7.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a47961e7-57b7-4096-81d5-557ae1a34219/20220503_040651/db-cluster-a47961e7.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a47961e7-57b7-4096-81d5-557ae1a34219/20220503_040651/db-cluster-a47961e7.tar.gz)
- **monitor-set-a47961e7.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a47961e7-57b7-4096-81d5-557ae1a34219/20220503_040651/monitor-set-a47961e7.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a47961e7-57b7-4096-81d5-557ae1a34219/20220503_040651/monitor-set-a47961e7.tar.gz)
- **loader-set-a47961e7.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a47961e7-57b7-4096-81d5-557ae1a34219/20220503_040651/loader-set-a47961e7.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a47961e7-57b7-4096-81d5-557ae1a34219/20220503_040651/loader-set-a47961e7.tar.gz)
- **sct-runner-a47961e7.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a47961e7-57b7-4096-81d5-557ae1a34219/20220503_040651/sct-runner-a47961e7.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a47961e7-57b7-4096-81d5-557ae1a34219/20220503_040651/sct-runner-a47961e7.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-5.0/job/longevity/job/longevity-large-partition-8h-test/3/)

**Comment by yarongilor** [comment]
@aleksbykov , @enaydanov , can you please advise? could it be an issue with logs sync and reading?
