### ISSUE TITLE
RepairStreamingErr fails to stop repair operation and times out

### ISSUE THREAD

**Issue by KnifeyMoloko** [scylladb/scylla-cluster-tests#4759]
## Installation details

Kernel Version: 5.13.0-1022-aws
Scylla version (or git commit hash): `5.1.dev-20220513.8e8dc2c930f5` with build-id `db03bd099e34fdbcc0ab957324be67cc42850a83`
Cluster size: 3 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- gemini-1tb-10h-master-oracle-db-node-cbe00a9c-1 (34.247.191.129 | 10.0.2.97) (shards: 14)
- gemini-1tb-10h-master-db-node-cbe00a9c-6 (34.244.94.2 | 10.0.1.139) (shards: 14)
- gemini-1tb-10h-master-db-node-cbe00a9c-5 (54.75.90.170 | 10.0.0.154) (shards: 14)
- gemini-1tb-10h-master-db-node-cbe00a9c-4 (3.250.167.154 | 10.0.1.55) (shards: 14)
- gemini-1tb-10h-master-db-node-cbe00a9c-3 (52.215.220.56 | 10.0.0.53) (shards: 14)
- gemini-1tb-10h-master-db-node-cbe00a9c-2 (34.247.86.38 | 10.0.3.47) (shards: 14)
- gemini-1tb-10h-master-db-node-cbe00a9c-1 (54.75.60.187 | 10.0.2.38) (shards: 14)

OS / Image: `ami-0d71c53b714b555e3` (aws: eu-west-1)

Test: `gemini-1tb-10h`
Test id: `cbe00a9c-be8c-409c-aeb3-aba4195f25d8`
Test name: `scylla-master/gemini-/gemini-1tb-10h`
Test config file(s):

- [gemini-1tb-10h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/ec8c055433d0d9024cd7f70ef63964013b230687/test-cases/gemini/gemini-1tb-10h.yaml)

## Issue description

**>>>>>>>**
`RepairStreamingErr` nemesis fails with timeouts.

```
2022-05-15 15:17:32.161: (DisruptionEvent Severity.ERROR) period_type=end event_id=a47773a7-1d2b-4f1d-83e9-d13553ecb5b9 duration=10m0s: nemesis_name=RepairStreamingErr target_node=Node gemini-1tb-10h-master-db-node-cbe00a9c-4 [3.250.167.154 | 10.0.1.55] (seed: False) errors=RetryError[Wait for: Wait for streaming starts: timeout - 600 seconds - expired]
Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/wait.py", line 64, in wait_for
    res = retry(func, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 360, in iter
    raise retry_exc.reraise()
  File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 194, in reraise
    raise self
tenacity.RetryError: RetryError[<Future at 0x7fb8786e1e40 state=finished returned bool>]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3378, in wrapper
    result = method(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2914, in disrupt_repair_streaming_err
    self.break_streaming_task_and_rebuild(task='repair')
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2844, in break_streaming_task_and_rebuild
    wait.wait_for(func=is_streaming_started, timeout=600, step=1,
  File "/home/ubuntu/scylla-cluster-tests/sdcm/wait.py", line 75, in wait_for
    raise tenacity.RetryError(err) from ex
tenacity.RetryError: RetryError[Wait for: Wait for streaming starts: timeout - 600 seconds - expired]

```

The nemesis started with destroying data and restarting the target node:

grepped sct.log:
```
2022-05-15 15:07:44.876: (ScyllaServerStatusEvent Severity.NORMAL) period_type=end event_id=15fea534-b090-4a20-9517-c231f786bd16 duration=1h20m59s node=gemini-1tb-10h-master-db-node-cbe00a9c-4
2022-05-15 15:09:55.509: (ScyllaServerStatusEvent Severity.NORMAL) period_type=begin event_id=04aa1b3b-84d1-4084-873b-699931c30fcf node=gemini-1tb-10h-master-db-node-cbe00a9c-4
```

After which we run `'nodetool repair' on the target node. In this case the repair took 33m38s:

grepped `sct.log`:
```
2022-05-15 15:12:00.708: (NodetoolEvent Severity.NORMAL) period_type=begin event_id=b46edb56-5268-45d2-b5ee-859c715d085e: nodetool_command=repair node=gemini-1tb-10h-master-db-node-cbe00a9c-4
2022-05-15 15:45:39.660: (NodetoolEvent Severity.NORMAL) period_type=end event_id=b46edb56-5268-45d2-b5ee-859c715d085e duration=33m38s: nodetool_command=repair node=gemini-1tb-10h-master-db-node-cbe00a9c-4
```

The nemesis should have stopped this repair operation, but it failed to detect it. Likely because of a regex pattern mismatch in https://github.com/scylladb/scylla-cluster-tests/blob/e68bd7101149ac27e24d3232434269cfe930f1b6/sdcm/nemesis.py#L2826

`**<<<<<<<**

- Restore Monitor Stack command: `$ hydra investigate show-monitor cbe00a9c-be8c-409c-aeb3-aba4195f25d8`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=cbe00a9c-be8c-409c-aeb3-aba4195f25d8)
- Show all stored logs command: `$ hydra investigate show-logs cbe00a9c-be8c-409c-aeb3-aba4195f25d8`

## Logs:
- **db-cluster-cbe00a9c.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/cbe00a9c-be8c-409c-aeb3-aba4195f25d8/20220515_224305/db-cluster-cbe00a9c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cbe00a9c-be8c-409c-aeb3-aba4195f25d8/20220515_224305/db-cluster-cbe00a9c.tar.gz)
- **monitor-set-cbe00a9c.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/cbe00a9c-be8c-409c-aeb3-aba4195f25d8/20220515_224305/monitor-set-cbe00a9c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cbe00a9c-be8c-409c-aeb3-aba4195f25d8/20220515_224305/monitor-set-cbe00a9c.tar.gz)
- **loader-set-cbe00a9c.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/cbe00a9c-be8c-409c-aeb3-aba4195f25d8/20220515_224305/loader-set-cbe00a9c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cbe00a9c-be8c-409c-aeb3-aba4195f25d8/20220515_224305/loader-set-cbe00a9c.tar.gz)
- **sct-runner-cbe00a9c.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/cbe00a9c-be8c-409c-aeb3-aba4195f25d8/20220515_224305/sct-runner-cbe00a9c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cbe00a9c-be8c-409c-aeb3-aba4195f25d8/20220515_224305/sct-runner-cbe00a9c.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/gemini-/job/gemini-1tb-10h/157/)

**Comment by fruch** [comment]
> This should be fixed with #4757

Can you explain a bit what is the suggested fix ? why removing the rebuild ? And what the problem is exactly, is the repair stopped or not according to the node log ?
