### ISSUE TITLE
Remote ScyllaYaml receives none

### ISSUE THREAD

**Issue by igorsimb** [scylladb/scylla-cluster-tests#4778]
### Prerequisites

* [ ] Are you rebased to master ? 
* [X] Is it reproducible ?
* [X] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: branch-2022.1
* **scylla**: 2022.1.rc5

### Logs
* test_id: c5c77456-fb66-4743-86c4-c296a4699aab
* job: https://jenkins.scylladb.com/job/enterprise-2022.1/job/features-/job/features-dns-cluster-5min-test/

### Description
It seems to fail at the start of the test. The test seems to use DNS names instead of IP (that's why the IP address shows as None). If that's the case, the remote yaml should support host names as well.
```
2022-05-23 09:45:35.221: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=8d17bc03-0859-4c2b-a19f-1e3eb8f1ac10, source=BuildClusterTest.test_use_public_dns_names (build_cluster_test.BuildClusterTest)() message=Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/build_cluster_test.py", line 91, in test_use_public_dns_names
    self.verify_stress_thread(cs_thread_pool=cs_thread_pool)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 1716, in verify_stress_thread
    results, errors = cs_thread_pool.verify_results()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/stress_thread.py", line 276, in verify_results
    results.append(future.result())
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/stress_thread.py", line 157, in _run_stress
    stress_cmd = self.create_stress_cmd(node, loader_idx, keyspace_idx)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/stress_thread.py", line 125, in create_stress_cmd
    stress_cmd += " -node {}".format(first_node.cql_ip_address)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 858, in cql_ip_address
    with self.remote_scylla_yaml() as scylla_yaml:
  File "/usr/local/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 1567, in remote_scylla_yaml
    new_scylla_yaml = ScyllaYaml(**scylla_yaml)
  File "/usr/local/lib/python3.10/site-packages/pydantic/main.py", line 406, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 2 validation errors for ScyllaYaml
listen_address
  none is not an allowed value (type=type_error.none.not_allowed)
rpc_address
  none is not an allowed value (type=type_error.none.not_allowed)
```

### Steps to Reproduce

Run the jenkins job mentioned above (https://jenkins.scylladb.com/job/enterprise-2022.1/job/features-/job/features-dns-cluster-5min-test/)

**Expected behavior:**

Function works (provided the DNS scenario mentioned above is true)

**Actual behavior:**

It looks for an IP address and finds nothing

**Comment by fruch** [comment]
Seems like the test itself is breaking the scylla.yaml:
my guess that the `addresses` dict isn't exactly as this part of the code expect, hence clearing 
every place the private address is mentioned

```python
        for node in self.db_cluster.nodes:
            node.remoter.run('sudo sed -i.bak s/{0}/{1}/g /etc/scylla/scylla.yaml'.format(node.private_ip_address,
                                                                                          addresses.get(
                                                                                              node.private_ip_address,
                                                                                              "")))
            for seed in seeds:
                node.remoter.run(
                    'sudo sed -i.bak2 s/{0}/{1}/g /etc/scylla/scylla.yaml'.format(seed, addresses.get(seed, "")))
```

**Comment by roydahan** [comment]
@rayakurl FYI
