### ISSUE TITLE
gemini-3h-ics-nondisruptive-nemesis-test CI job uses wrong Scylla type for oracle cluster

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-cluster-tests#4787]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: branch-2022.1
* **scylla**: any

### Logs
* test_id: a90859e6-3329-4ac9-a992-2bc187dfc6aa
* job log: https://jenkins.scylladb.com/job/enterprise-2022.1/job/SCT_Enterprise_Features/job/ICS/job/gemini-3h-ics-nondisruptive-nemesis-test/3

### Description

CI job called `gemini-3h-ics-nondisruptive-nemesis-test` is broken in the following way:
Oracle cluster is OS Scylla `4.4.7` and the test cluster is enterprise `2022.1.rc5`
Configuration for the test run tries to apply `IncrementalCompactionStrategy` compaction strategy which is available only in Enterprise Scylla version. So, the oracle cluster gets following failure visible in the `sct.log`:

```
< t:2022-05-23 10:00:28,511 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2022-05-23 10:00:28.509: (GeminiStressEvent Severity.NORMAL) period_type=begin event_id=c540e747-7b7f-44e4-835a-7d2fae5aeb15: node=Node ics-gemini-nemesis-3h-2022-1-loader-node-a90859e6-1 [3.250.33.163 | 10.0.2.164] (seed: False) gemini_cmd=/$HOME/gemini -d --duration 10800s --warmup 1800s -c 50 -m mixed -f --non-interactive --cql-features normal --table-options "compaction={'class': 'IncrementalCompactionStrategy'}" --max-mutation-retries 5 --max-mutation-retries-backoff 500ms --async-objects-stabilization-attempts 5 --async-objects-stabilization-backoff 500ms --test-cluster=10.0.2.86,10.0.1.68,10.0.0.232 --outfile /home/centos/gemini_result_6eed0325-f1a7-4834-bfcf-630c8d05f69d.log --seed 39 --oracle-cluster=10.0.3.176

...

< t:2022-05-23 10:00:51,535 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > {
	"L":"INFO",
	"T":"2022-05-23T10:00:51.524Z",
	"N":"delegating_store",
	"M":"oracle failed mutation, transition to next state impossible so continuing with next mutation",
	"error":"unable to apply mutations to the oracle store: [
		cluster = oracle, 
		query = 'CREATE TABLE IF NOT EXISTS ks1.table1 (pk0 int,pk1 int,pk2 tinyint,ck0 double,ck1 decimal,ck2 uuid,col0 smallint,col1 frozen<map<inet,varchar>>,col2 blob,col3 tinyint,col4 bigint,col5 uuid,col6 decimal,col7 inet,col8 smallint,col9 timeuuid,col10 frozen<udt_2298261596>,col11 list<smallint>,col12 varint,col13 varchar, PRIMARY KEY ((pk0,pk1,pk2), ck0,ck1,ck2)) WITH compaction = {'class':'IncrementalCompactionStrategy'};'
	]: Unable to find compaction strategy class 'IncrementalCompactionStrategy'",
	"errorVerbose":"Unable to find compaction strategy class 'IncrementalCompactionStrategy'
	[cluster = oracle, query = 'CREATE TABLE IF NOT EXISTS ks1.table1 (pk0 int,pk1 int,pk2 tinyint,ck0 double,ck1 decimal,ck2 uuid,col0 smallint,col1 frozen<map<inet,varchar>>,col2 blob,col3 tinyint,col4 bigint,col5 uuid,col6 decimal,col7 inet,col8 smallint,col9 timeuuid,col10 frozen<udt_2298261596>,col11 list<smallint>,col12 varint,col13 varchar, PRIMARY KEY ((pk0,pk1,pk2), ck0,ck1,ck2)) WITH compaction = {'class':'IncrementalCompactionStrategy'};']\ngithub.com/scylladb/gemini/store.(*cqlStore).doMutate\n\t/home/penberg/go/src/github.com/scylladb/gemini/store/cqlstore.go:98\ngithub.com/scylladb/gemini/store.(*cqlStore).mutate\n\t/home/penberg/go/src/github.com/scylladb/gemini/store/cqlstore.go:50\ngithub.com/scylladb/gemini/store.mutate\n\t/home/penberg/go/src/github.com/scylladb/gemini/store/store.go:165\ngithub.com/scylladb/gemini/store.delegatingStore.Mutate\n\t/home/penberg/go/src/github.com/scylladb/gemini/store/store.go:156\nmain.run\n\t/home/penberg/go/src/github.com/scylladb/gemini/cmd/gemini/root.go:248\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/penberg/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/penberg/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/penberg/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800\nmain.main\n\t/home/penberg/go/src/github.com/scylladb/gemini/cmd/gemini/main.go:29\nruntime.main\n\t/usr/lib/golang/src/runtime/proc.go:204\nruntime.goexit\n\t/usr/lib/golang/src/runtime/asm_amd64.s:1374\nunable to apply mutations to the oracle store\ngithub.com/scylladb/gemini/store.mutate\n\t/home/penberg/go/src/github.com/scylladb/gemini/store/store.go:166\ngithub.com/scylladb/gemini/store.delegatingStore.Mutate\n\t/home/penberg/go/src/github.com/scylladb/gemini/store/store.go:156\nmain.run\n\t/home/penberg/go/src/github.com/scylladb/gemini/cmd/gemini/root.go:248\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/penberg/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/penberg/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/penberg/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800\nmain.main\n\t/home/penberg/go/src/github.com/scylladb/gemini/cmd/gemini/main.go:29\nruntime.main\n\t/usr/lib/golang/src/runtime/proc.go:204\nruntime.goexit\n\t/usr/lib/golang/src/runtime/asm_amd64.s:1374"}
```

If we run nemesis which are not keyspace specific then we do not get problems because of it.
But, if we do run such nemesis like `mgmt_backup_specific_keyspaces` then we get error like following not finding the expectation keyspace which was not created due to above error:

```
> sdcm.nemesis.GeminiNonDisruptiveChaosMonkey: Unhandled exception in method <function Nemesis.disrupt_mgmt_backup_specific_keyspaces at 0x7fcb2fa9aef0> < t:2022-05-23 10:50:59,611 f:nemesis.py      l:3346 c:sdcm.nemesis         p:ERROR > sdcm.nemesis.GeminiNonDisruptiveChaosMonkey: Unhandled exception in method <function Nemesis.disrupt_mgmt_backup_specific_keyspaces at 0x7fcb2fa9aef0>
> Traceback (most recent call last):                                                                   
>   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3336, in wrapper                    
>     result = method(*args, **kwargs)                                                                 
>   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2057, in disrupt_mgmt_backup_specific_keyspaces
>     self._mgmt_backup(backup_specific_tables=True)                                                   
>   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2083, in _mgmt_backup               
>     mgr_task = mgr_cluster.create_backup_task(location_list=[location, ], keyspace_list=non_test_keyspaces)
>   File "/home/ubuntu/scylla-cluster-tests/sdcm/mgmt/cli.py", line 521, in create_backup_task         
>     res = self.sctool.run(cmd=cmd, parse_table_res=False)                                            
>   File "/home/ubuntu/scylla-cluster-tests/sdcm/mgmt/cli.py", line 1041, in run                       
>     res = self.manager_node.remoter.sudo(f"sctool {cmd}")                                            
>   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/base.py", line 123, in sudo                    
>     return self.run(cmd=cmd,                                                                         
>   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run              
>     result = _run()                                                                                  
>   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 64, in inner               
>     return func(*args, **kwargs)                                                                     
>   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run             
>     return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)            
>   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute  
>     result = connection.run(**command_kwargs)                                                        
>   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run 
>     return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
>   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 654, in _complete_run
>     raise UnexpectedExit(result)                                                                     
> sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!           
>                                                                                                      
> Command: 'sudo sctool backup -c dfd7658b-e503-4daa-8edf-469e16d55d62 --keyspace ks1  --location s3:manager-backup-tests-us-east-1 '
>                                                                                                      
> Exit code: 1                                                                                         
>                                                                                                      
> Stdout:                                                                                              
>                                                                                                      
>                                                                                                      
>                                                                                                      
> Stderr:                                                                                              
>                                                                                                      
> Error: create backup target: no keyspace matched criteria [ks1.*] - available keyspaces are: []   
> Trace ID: P6eW1eqVQfO3eJl8fqxbRg (grep in scylla-manager logs)
```

### Steps to Reproduce

1. Run `gemini-3h-ics-nondisruptive-nemesis-test`
2. Try to use `ks1` keyspace
3. See error

**Expected behavior:** We should use Enterprise oracle Scylla only when we use enterprise-only features on Oracle cluster.

**Actual behavior:** We mistakenly try to apply nonexistent compaction strategy.

**Comment by fruch** [comment]
Closed by #4788
