### ISSUE TITLE
Scylla does not start on GCE due io_setup error in 1TB test

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#4814]
Test details:

## Installation details

Cluster size: 4 nodes (n1-highmem-16)

Scylla Nodes used in this run:
- longevity-tls-1tb-7d-5-0-db-node-88f84d54-0-4 (34.138.28.89 | 10.142.0.152) (shards: -1)
- longevity-tls-1tb-7d-5-0-db-node-88f84d54-0-3 (34.139.186.45 | 10.142.0.150) (shards: -1)
- longevity-tls-1tb-7d-5-0-db-node-88f84d54-0-2 (35.237.185.125 | 10.142.0.148) (shards: -1)
- longevity-tls-1tb-7d-5-0-db-node-88f84d54-0-1 (34.138.75.240 | 10.142.0.145) (shards: -1)

OS / Image: `https://www.googleapis.com/compute/v1/projects/scylla-images/global/images/scylla-5-0-rc5` (gce: us-east1)

Test: `longevity-1tb-7days-gce-test`
Test id: `88f84d54-f5c0-4c13-8d02-f245375b5589`
Test name: `scylla-5.0/longevity/longevity-1tb-7days-gce-test`
Test config file(s):

- [longevity-1TB-5days-authorization-and-tls-ssl.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/33426dd39d0c9cefdc80d5e6283ca28a24af1d02/test-cases/longevity/longevity-1TB-5days-authorization-and-tls-ssl.yaml)

- Restore Monitor Stack command: `$ hydra investigate show-monitor 88f84d54-f5c0-4c13-8d02-f245375b5589`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=88f84d54-f5c0-4c13-8d02-f245375b5589)
- Show all stored logs command: `$ hydra investigate show-logs 88f84d54-f5c0-4c13-8d02-f245375b5589`

## Issue description
On GCE, 1TB test with many disks, scylla-server does not start due io_setup error. Logs show:
```
2022-05-23T08:54:59+00:00 longevity-tls-1tb-7d-5-0-db-node-88f84d54-0-1 !    INFO | Devices: ['/dev/nvme0n16', '/dev/nvme0n15', '/dev/nvme0n14', '/dev/nvme0n13', '/dev/nvme0n12', '/dev/nvme0n11', '/dev/nvme0n10', '/dev/nvme0n9', '/dev/nvme0n8', '/dev/nvme0n7', '/dev/nvme0n6', '/dev/nvme0n5', '/dev/nvme0n4', '/dev/nvme0n3', '/dev/nvme0n2', '/dev/nvme0n1']
2022-05-23T08:54:59+00:00 longevity-tls-1tb-7d-5-0-db-node-88f84d54-0-1 !    INFO | /var/lib/scylla is already mounted. Will not run 'scylla_raid_setup'!
2022-05-23T08:55:02+00:00 longevity-tls-1tb-7d-5-0-db-node-88f84d54-0-1 !    INFO | WARNING:root:This machine doesn't have enough CPUs for allocated number of NVMEs (at least 32 cpus for >=16 disks). Performance will suffer.
2022-05-23T08:55:02+00:00 longevity-tls-1tb-7d-5-0-db-node-88f84d54-0-1 !    INFO | ERROR:root:This is not a recommended Google Cloud instance setup for auto local disk tuning.
2022-05-23T08:55:02+00:00 longevity-tls-1tb-7d-5-0-db-node-88f84d54-0-1 !    INFO | Traceback (most recent call last):
2022-05-23T08:55:02+00:00 longevity-tls-1tb-7d-5-0-db-node-88f84d54-0-1 !    INFO |   File "/opt/scylladb/scylla-machine-image/libexec/scylla_image_setup", line 40, in <module>
2022-05-23T08:55:02+00:00 longevity-tls-1tb-7d-5-0-db-node-88f84d54-0-1 !    INFO |     cloud_instance.io_setup()
2022-05-23T08:55:02+00:00 longevity-tls-1tb-7d-5-0-db-node-88f84d54-0-1 !    INFO |   File "/opt/scylladb/scylla-machine-image/lib/scylla_cloud.py", line 301, in io_setup
2022-05-23T08:55:02+00:00 longevity-tls-1tb-7d-5-0-db-node-88f84d54-0-1 !    INFO |     return run('/opt/scylladb/scylla-machine-image/scylla_cloud_io_setup', shell=True, check=True)
2022-05-23T08:55:02+00:00 longevity-tls-1tb-7d-5-0-db-node-88f84d54-0-1 !    INFO |   File "/opt/scylladb/python3/lib64/python3.9/subprocess.py", line 528, in run
2022-05-23T08:55:02+00:00 longevity-tls-1tb-7d-5-0-db-node-88f84d54-0-1 !    INFO |     raise CalledProcessError(retcode, process.args,
2022-05-23T08:55:02+00:00 longevity-tls-1tb-7d-5-0-db-node-88f84d54-0-1 !    INFO | subprocess.CalledProcessError: Command '/opt/scylladb/scylla-machine-image/scylla_cloud_io_setup' returned non-zero exit status 1.
2022-05-23T08:55:02+00:00 longevity-tls-1tb-7d-5-0-db-node-88f84d54-0-1 !  NOTICE | scylla-image-setup.service: Main process exited, code=exited, status=1/FAILURE
2022-05-23T08:55:02+00:00 longevity-tls-1tb-7d-5-0-db-node-88f84d54-0-1 ! WARNING | scylla-image-setup.service: Failed with result 'exit-code'.
2022-05-23T08:55:02+00:00 longevity-tls-1tb-7d-5-0-db-node-88f84d54-0-1 !     ERR | Failed to start Scylla Cloud Image Setup service.
```

Warning about not enough cpu's and error about not recommended GC instance setup was also present for 4.6 release, but in that case test anyway progressed. For 5.0 `scylla-machine-setup` now fails (exit 1 from io_setup script) and prevents from running Scylla.

Question is, shall we change GC instance setup (e.g. add more cpu's) or switch back to previous behavior of `scylla-machine-setup`?

## Logs:
- **db-cluster-88f84d54.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/88f84d54-f5c0-4c13-8d02-f245375b5589/20220523_090047/db-cluster-88f84d54.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/88f84d54-f5c0-4c13-8d02-f245375b5589/20220523_090047/db-cluster-88f84d54.tar.gz)
- **monitor-set-88f84d54.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/88f84d54-f5c0-4c13-8d02-f245375b5589/20220523_090047/monitor-set-88f84d54.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/88f84d54-f5c0-4c13-8d02-f245375b5589/20220523_090047/monitor-set-88f84d54.tar.gz)
- **loader-set-88f84d54.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/88f84d54-f5c0-4c13-8d02-f245375b5589/20220523_090047/loader-set-88f84d54.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/88f84d54-f5c0-4c13-8d02-f245375b5589/20220523_090047/loader-set-88f84d54.tar.gz)
- **sct-runner-88f84d54.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/88f84d54-f5c0-4c13-8d02-f245375b5589/20220523_090047/sct-runner-88f84d54.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/88f84d54-f5c0-4c13-8d02-f245375b5589/20220523_090047/sct-runner-88f84d54.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-5.0/job/longevity/job/longevity-1tb-7days-gce-test/3/)

**Comment by soyacz** [comment]
@syuu1228 I moved https://github.com/scylladb/scylla-pkg/issues/2900 here  ^^.

**Comment by fruch** [comment]
It can be both, opening an issue for scylla machine image, about the regression (if that was intended or not)
And pick larger resources, so we test the recommend setup

**Comment by soyacz** [comment]
There may be even more problems - see the recent comments in https://github.com/scylladb/scylla-pkg/issues/2900
