### ISSUE TITLE
disrupt_decommission_streaming_err timeout cause of the nodetool decomission coammnd doesn't return

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#4935]
## Installation details

Kernel Version: 5.13.0-1033-gcp
Scylla version (or git commit hash): `5.1.dev-20220621.f15a6ce41a07` with build-id `8d5dee8623f8cc364e2934f932c8b45cd34ac93f`
Cluster size: 6 nodes (n1-highmem-16)

Scylla Nodes used in this run:
- longevity-10gb-3h-master-db-node-0e149ab8-0-8 (35.231.79.24 | 10.142.0.167) (shards: 14)
- longevity-10gb-3h-master-db-node-0e149ab8-0-7 (35.237.87.120 | 10.142.0.148) (shards: 14)
- longevity-10gb-3h-master-db-node-0e149ab8-0-6 (35.237.106.25 | 10.142.0.138) (shards: 14)
- longevity-10gb-3h-master-db-node-0e149ab8-0-5 (34.73.87.48 | 10.142.0.135) (shards: 14)
- longevity-10gb-3h-master-db-node-0e149ab8-0-4 (35.196.158.208 | 10.142.0.134) (shards: 14)
- longevity-10gb-3h-master-db-node-0e149ab8-0-3 (35.237.164.64 | 10.142.0.132) (shards: 14)
- longevity-10gb-3h-master-db-node-0e149ab8-0-2 (35.227.113.27 | 10.142.0.128) (shards: 14)
- longevity-10gb-3h-master-db-node-0e149ab8-0-1 (35.231.107.26 | 10.142.0.127) (shards: 14)

OS / Image: `https://www.googleapis.com/compute/v1/projects/scylla-images/global/images/7776066699477661801` (gce: us-east1)

Test: `longevity-10gb-3h-gce-test`
Test id: `0e149ab8-42af-4f21-b7ca-6f8364ac436e`
Test name: `scylla-master/longevity/longevity-10gb-3h-gce-test`
Test config file(s):

- [longevity-10gb-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/a636137df0fc812520298bc1aaee56f643fc5bef/test-cases/longevity/longevity-10gb-3h.yaml)

## Issue description

Seems like the reboot of the node, doesn't make the run_nodetool() to be stop or fail

and the nemsis  fails with the following error
```
< t:2022-06-22 13:15:51,928 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2022-06-22 13:15:51.925: (DisruptionEvent Severity.ERROR) period_type=end event_id=214291c6-3860-47be-a59e-ba976c50c3c9 duration=10m1s: nemesis_name=DecommissionStreamingErr target_node=Node longevity-10gb-3h-master-db-node-0e149ab8-0-6 [35.237.106.25 | 10.142.0.138] (seed: False) errors=when running on: [functools.partial(<bound method BaseNode.run_nodetool of <sdcm.cluster_gce.GCENode object at 0x7fcd3c2cb670>>, sub_cmd='decommission', warning_event_on_exception=(<class 'Exception'>,)), functools.partial(<bound method Nemesis._call_disrupt_func_after_expression_logged of <sdcm.nemesis.SisyphusMonkey object at 0x7fcd3c1fbe50>>, expression='DECOMMISSIONING: unbootstrap starts', disrupt_func=<function Nemesis.reboot_node at 0x7fcd4445cee0>, disrupt_func_kwargs={'target_node': <sdcm.cluster_gce.GCENode object at 0x7fcd3c2cb670>, 'hard': True, 'verify_ssh': True}, delay=0)]
< t:2022-06-22 13:15:51,928 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > Traceback (most recent call last):
< t:2022-06-22 13:15:51,928 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3415, in wrapper
< t:2022-06-22 13:15:51,928 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     result = method(*args, **kwargs)
< t:2022-06-22 13:15:51,928 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2937, in disrupt_decommission_streaming_err
< t:2022-06-22 13:15:51,928 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     self.start_and_interrupt_decommission_streaming()
< t:2022-06-22 13:15:51,928 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2877, in start_and_interrupt_decommission_streaming
< t:2022-06-22 13:15:51,928 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     ParallelObject(objects=[trigger, watcher], timeout=600).call_objects()
< t:2022-06-22 13:15:51,928 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 460, in call_objects
< t:2022-06-22 13:15:51,928 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     return self.run(lambda x: x())
< t:2022-06-22 13:15:51,928 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 436, in run
< t:2022-06-22 13:15:51,928 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     raise FuturesTimeoutError("when running on: %s" % [r.obj for r in results])
< t:2022-06-22 13:15:51,928 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > concurrent.futures._base.TimeoutError: when running on: [functools.partial(<bound method BaseNode.run_nodetool of <sdcm.cluster_gce.GCENode object at 0x7fcd3c2cb670>>, sub_cmd='decommission', warning_event_on_exception=(<class 'Exception'>,)), functools.partial(<bound method Nemesis._call_disrupt_func_after_expression_logged of <sdcm.nemesis.SisyphusMonkey object at 0x7fcd3c1fbe50>>, expression='DECOMMISSIONING: unbootstrap starts', disrupt_func=<function Nemesis.reboot_node at 0x7fcd4445cee0>, disrupt_func_kwargs={'target_node': <sdcm.cluster_gce.GCENode object at 0x7fcd3c2cb670>, 'hard': True, 'verify_ssh': True}, delay=0)]
```

Since the parallel object is used, it's really not clear which command timeout.
we might need to think about adding a timeout nodetool command, so it would be clearer.

anyhow it's not scylla fault the nodetool doesn't return, we should put a timeout on it, 
and expect it to possibly timeout.

- Restore Monitor Stack command: `$ hydra investigate show-monitor 0e149ab8-42af-4f21-b7ca-6f8364ac436e`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=0e149ab8-42af-4f21-b7ca-6f8364ac436e)
- Show all stored logs command: `$ hydra investigate show-logs 0e149ab8-42af-4f21-b7ca-6f8364ac436e`

## Logs:
- **db-cluster-0e149ab8.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/0e149ab8-42af-4f21-b7ca-6f8364ac436e/20220622_144726/db-cluster-0e149ab8.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/0e149ab8-42af-4f21-b7ca-6f8364ac436e/20220622_144726/db-cluster-0e149ab8.tar.gz)
- **monitor-set-0e149ab8.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/0e149ab8-42af-4f21-b7ca-6f8364ac436e/20220622_144726/monitor-set-0e149ab8.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/0e149ab8-42af-4f21-b7ca-6f8364ac436e/20220622_144726/monitor-set-0e149ab8.tar.gz)
- **loader-set-0e149ab8.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/0e149ab8-42af-4f21-b7ca-6f8364ac436e/20220622_144726/loader-set-0e149ab8.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/0e149ab8-42af-4f21-b7ca-6f8364ac436e/20220622_144726/loader-set-0e149ab8.tar.gz)
- **sct-runner-0e149ab8.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/0e149ab8-42af-4f21-b7ca-6f8364ac436e/20220622_144726/sct-runner-0e149ab8.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/0e149ab8-42af-4f21-b7ca-6f8364ac436e/20220622_144726/sct-runner-0e149ab8.tar.gz)
- **parallel-timelines-report-0e149ab8.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/0e149ab8-42af-4f21-b7ca-6f8364ac436e/20220622_144726/parallel-timelines-report-0e149ab8.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/0e149ab8-42af-4f21-b7ca-6f8364ac436e/20220622_144726/parallel-timelines-report-0e149ab8.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-10gb-3h-gce-test/190/)

**Comment by fruch** [comment]
@KnifeyMoloko can you take a look at it, to see if my analysis here is correct ?

**Comment by fruch** [comment]
closing as it duplicate of #4890
