### ISSUE TITLE
[k8s-functional] provider is set to none, failing report to Argus

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#5001]
```
21:56:02  < t:2022-07-12 18:56:02,045 f:cluster.py      l:319  c:sdcm.cluster         p:ERROR > Encountered an unhandled exception while interacting with Argus < t:2022-07-12 18:56:02,045 f:cluster.py      l:319  c:sdcm.cluster         p:ERROR > Encountered an unhandled exception while interacting with Argus
21:56:02  < t:2022-07-12 18:56:02,045 f:cluster.py      l:319  c:sdcm.cluster         p:ERROR > Traceback (most recent call last):
21:56:02  < t:2022-07-12 18:56:02,045 f:cluster.py      l:319  c:sdcm.cluster         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 309, in _init_argus_resource
21:56:02  < t:2022-07-12 18:56:02,045 f:cluster.py      l:319  c:sdcm.cluster         p:ERROR >     instance_details = CloudInstanceDetails(public_ip=self.public_ip_address, region=self.region,
21:56:02  < t:2022-07-12 18:56:02,045 f:cluster.py      l:319  c:sdcm.cluster         p:ERROR >   File "<string>", line 11, in __init__
21:56:02  < t:2022-07-12 18:56:02,045 f:cluster.py      l:319  c:sdcm.cluster         p:ERROR >   File "/usr/local/lib/python3.10/site-packages/pydantic/dataclasses.py", line 99, in _pydantic_post_init
21:56:02  < t:2022-07-12 18:56:02,045 f:cluster.py      l:319  c:sdcm.cluster         p:ERROR >     raise validation_error
21:56:02  < t:2022-07-12 18:56:02,045 f:cluster.py      l:319  c:sdcm.cluster         p:ERROR > pydantic.error_wrappers.ValidationError: 1 validation error for CloudInstanceDetails
21:56:02  < t:2022-07-12 18:56:02,045 f:cluster.py      l:319  c:sdcm.cluster         p:ERROR > provider
21:56:02  < t:2022-07-12 18:56:02,045 f:cluster.py      l:319  c:sdcm.cluster         p:ERROR >   none is not an allowed value (type=type_error.none.not_allowed)
```

**Comment by fruch** [comment]
Fixed, those tests are now reporting on ok
