### ISSUE TITLE
A Scylla K8S node becomes inoperational and gets replaced afterwards

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-cluster-tests#5020]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master
* **scylla**: 4.4.5

### Logs
* test_id: e5c9f556-ef54-4c22-8096-8cbe2483a5b4
* job log: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/valerii/job/vp-perf-regression-latency-eks-multitenant-7-clients/13

### Description

It happens that running K8S multitenant setup we get following error:
```
< t:2022-07-12 14:14:13,262 f:base.py         l:146  c:LocalCmdRunner       p:ERROR > 
    Error executing command: "
        kubectl --cache-dir=/home/ubuntu/sct-results/20220712-132715-550602/.kube/http-cache 
        --namespace=default exec -ti local-volume-provisioner-wxjqw -- 
        sh -c 'fstrim -v /mnt/raid-disks/disk0/'
    "; 
    Exit status: 1
```

Pods list:

```
$ kubectl get pods -A -o wide                                                                          
NAMESPACE     NAME                                         READY   STATUS             RESTARTS   AGE   IP           NODE   
cert-manager  cert-manager-759575d694-2w5w5                1/1     Running            0          74m   10.0.1.64    ip-10-0-0-163.ec2.internal
cert-manager  cert-manager-cainjector-77977c9f5c-4xg7s     1/1     Running            0          74m   10.0.2.254   ip-10-0-0-163.ec2.internal 
cert-manager  cert-manager-webhook-746769d4-crmxp          1/1     Running            0          74m   10.0.0.87    ip-10-0-0-163.ec2.internal
default       cpu-policy-9qt8s                             1/1     Running            1          73m   10.0.3.62    ip-10-0-0-198.ec2.internal
default       cpu-policy-fts77                             1/1     Running            1          73m   10.0.0.24    ip-10-0-1-28.ec2.internal  
default       cpu-policy-sf592                             1/1     Running            1          73m   10.0.1.215   ip-10-0-3-128.ec2.internal  
default       local-volume-provisioner-9s754               1/1     Running            0          73m   10.0.0.112   ip-10-0-1-28.ec2.internal  
default       local-volume-provisioner-jwsdr               1/1     Running            0          73m   10.0.3.159   ip-10-0-0-198.ec2.internal
default       local-volume-provisioner-wxjqw               0/1     CrashLoopBackOff   2          73m   <none>       ip-10-0-3-128.ec2.internal 
default       node-setup-bvv6t                             2/2     Running            0          73m   10.0.0.78    ip-10-0-3-128.ec2.internal
default       node-setup-w8wkl                             2/2     Running            0          73m   10.0.1.126   ip-10-0-1-28.ec2.internal  
default       node-setup-xtgbj                             2/2     Running            0          73m   10.0.2.38    ip-10-0-0-198.ec2.internal 
kube-system   aws-node-4llzp                               1/1     Running            0          77m   10.0.3.238   ip-10-0-3-238.ec2.internal 
...                                                                                                    
kube-system   aws-node-vz5mw                               1/1     Running            0          77m   10.0.0.118   ip-10-0-0-118.ec2.internal
kube-system   aws-node-whzm6                               0/1     CrashLoopBackOff   10         77m   10.0.3.128   ip-10-0-3-128.ec2.internal
kube-system   aws-node-wwglq                               1/1     Running            0          77m   10.0.1.253   ip-10-0-1-253.ec2.interna
```

List of events for the problematic node:
```
Events:
  Type     Reason     Age                  From     Message
  ----     ------     ----                 ----     -------
  Warning  Unhealthy  26m (x2 over 26m)    kubelet  Liveness probe failed: OCI runtime exec failed: fork/exec /usr/sbin/runc: resource temporarily unavailable: unknown
  Warning  Unhealthy  26m                  kubelet  Liveness probe failed: OCI runtime exec failed: runc did not terminate successfully: unknown
  Normal   Killing    26m                  kubelet  Container aws-node failed liveness probe, will be restarted
  Warning  Unhealthy  26m (x3 over 26m)    kubelet  Readiness probe failed: OCI runtime exec failed: fork/exec /usr/sbin/runc: resource temporarily unavailable: unknown
  Normal   Pulled     26m                  kubelet  Successfully pulled image "602401143452.dkr.ecr.us-east-1.amazonaws.com/amazon-k8s-cni:v1.7.5-eksbuild.1" in 161.968649ms
  Normal   Pulled     26m                  kubelet  Successfully pulled image "602401143452.dkr.ecr.us-east-1.amazonaws.com/amazon-k8s-cni:v1.7.5-eksbuild.1" in 109.840398ms
  Warning  Failed     26m (x2 over 26m)    kubelet  Error: failed to start container "aws-node": Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:338: starting init process command caused: fork/exec /proc/self/exe: resource temporarily unavailable: unknown
  Normal   Created    25m (x3 over 26m)    kubelet  Created container aws-node
  Warning  Failed     25m                  kubelet  Error: failed to start container "aws-node": Error response from daemon: : fork/exec /usr/bin/containerd-shim-runc-v2: resource temporarily unavailable: unknown
  Normal   Pulled     25m                  kubelet  Successfully pulled image "602401143452.dkr.ecr.us-east-1.amazonaws.com/amazon-k8s-cni:v1.7.5-eksbuild.1" in 102.468691ms
  Normal   Pulling    25m (x4 over 26m)    kubelet  Pulling image "602401143452.dkr.ecr.us-east-1.amazonaws.com/amazon-k8s-cni:v1.7.5-eksbuild.1"
  Normal   Pulled     25m                  kubelet  Successfully pulled image "602401143452.dkr.ecr.us-east-1.amazonaws.com/amazon-k8s-cni:v1.7.5-eksbuild.1" in 105.538628ms
  Warning  BackOff    97s (x119 over 26m)  kubelet  Back-off restarting failed container
```

And here is the part of the description of the `local-volume-provisioner` pod:
```
$ kubectl describe pod local-volume-provisioner-wxjqw
Name:           local-volume-provisioner-wxjqw
Namespace:      default
Priority:       0
Node:           ip-10-0-3-128.ec2.internal/10.0.3.128
Start Time:     Wed, 13 Jul 2022 12:15:28 +0300
Labels:         app=local-volume-provisioner
                controller-revision-hash=5b6b58bfd9
                pod-template-generation=1
Annotations:    kubernetes.io/psp: eks.privileged
Status:         Running
IP:             
IPs:            <none>
Controlled By:  DaemonSet/local-volume-provisioner
Containers:
  provisioner:
    Container ID:  docker://743a47a7bc08155a3501c70ab23f4ad59c9351a40ded6f60d49c6fe432c3f637
    Image:         quay.io/external_storage/local-volume-provisioner:v2.3.4
    Image ID:      docker-pullable://quay.io/external_storage/local-volume-provisioner@sha256:3799dfe81a5392d2d68951527c857402e591240cbb638f4ef0e4b8bb57c1da64
    Port:          <none>
    Host Port:     <none>
    State:         Waiting
      Reason:      CrashLoopBackOff
    Last State:    Terminated
      Reason:      ContainerCannotRun
      Message:     runtime: failed to create new OS thread (have 9 already; errno=11)
runtime: may need to increase max user processes (ulimit -u)
fatal error: newosproc
...
huge golang traceback here
...
  Warning  Failed   19m                kubelet  Error: failed to start container "provisioner": Error response from daemon: runtime: failed to create new OS thread (have 9 already; errno=11)
runtime: may need to increase max user processes (ulimit -u)
fatal error: newosproc
...
goroutine 9 [runnable]:
github.com/containerd/containerd/runtime/v2/runc/v2.(*service).forward(0xc000090080, 0x9a4dd8, 0xc000098000, 0x99fed8, 0xc000070180)
  /builddir/build/BUILD/containerd-1.4.13-3.amzn2/src/github.com/containerd/containerd/runtime/v2/runc/v2/service.go:800
created by github.com/containerd/containerd/runtime/v2/runc/v2.New
  /builddir/build/BUILD/containerd-1.4.13-3.amzn2/src/github.com/containerd/containerd/runtime/v2/runc/v2/service.go:106 +0x2c7
: exit status 2: unknown
  Warning  BackOff         19m                   kubelet  Back-off restarting failed container
  Normal   SandboxChanged  4m48s (x69 over 19m)  kubelet  Pod sandbox changed, it will be killed and re-created.
```

So, when this problem happens the broken node never gets healed and just gets replaced by a new node automatically by the `node group`s logic. It takes up to an hour making a test run fail.

Happens, approximately, in 2 runs from 5.

The broken node and pods are replaced when the K8S logs start being gathered. So, resulting logs contain too few details.

`Thoughts`
The fact that it happens only to some of Scylla K8S node makes me assume that our additional actions to it may be the cause.
We have `cpu-policy` pods which change kubelet configuration and restart it, we have operator perf tuning, we have storage provisioner pods... So, requires more deeper investigation.
Also, worth trying to update K8S version in addition to the CNI version.

### Steps to Reproduce

1. Run K8S multitenant test several times until error appears
2. See error.
3. [and so on...]

**Expected behavior:** All the K8S nodes are alive and working ok

**Actual behavior:** 1 of Scylla K8S nodes dies and gets replaced during a 1 hour time range.

**Comment by fruch** [comment]
FYI on master since https://github.com/scylladb/scylla/commit/a19d00ef9b8b50ce520bb2cfbf5bc00b30de5cda
XFS online discard is use by scylla_setup by default, and fstrim timer is disabled.

If we can enable this XFS feature (maybe we can also skip those fstrim)

again, not that those calls should be kill pods like you are seeing. but maybe we can stop wasting time on those calls

**Comment by fruch** [comment]
@avi since ages we are running fstrim before/after performance tests, for making sure we start each round of stress with with everything on disk. do you think that if XFS online discard is enabled, we can stop doing that ?

**Comment by fruch** [comment]
@vponomaryov is this issue still relevant ? it got solved on it's "own" ?
