### ISSUE TITLE
disrupt_nodetool_refresh consistantly fails with Permission denied

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla-cluster-tests#5083]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master
* **scylla**: master:latest

### Logs
* test_id: 79a06b0c-521a-467a-8613-7fdcef134c6a

### Description

After https://github.com/scylladb/scylla-cluster-tests/pull/4968 has been merged, disrupt_nodetool_refresh consistantly fails due to permission denied:
```
Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3614, in wrapper
    result = method(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1465, in disrupt_nodetool_refresh
    SstableLoadUtils.upload_sstables(node, test_data=test_data[0])
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/sstable/load_utils.py", line 68, in upload_sstables
    node.remoter.sudo(f'tar xvfz {test_data.sstable_file} -C {tmp_folder.folder_name}/', user='scylla')
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/base.py", line 123, in sudo
    return self.run(cmd=cmd,
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run
    result = _run()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 67, in inner
    return func(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run
    return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
    result = connection.run(**command_kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
    return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 654, in _complete_run
    raise UnexpectedExit(result)
sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!

Command: 'sudo -u scylla tar xvfz /tmp/keyspace1.standard1.tar.gz -C /tmp/tmp.wUtrdYx7bd/'

Exit code: 2

Stdout:



Stderr:

tar: /tmp/tmp.wUtrdYx7bd: Cannot open: Permission denied
tar: Error is not recoverable: exiting now
```

### Steps to Reproduce

1. start an longevity run
2. wait for disrupt_nodetool_refresh to run

**Comment by ShlomiBalalis** [comment]
The nodetool refresh nemesis passed this week after #5091 was merged. Closing.
