### ISSUE TITLE
Unhandled exception during AbortRepair expects [200, 201, 202]

### ISSUE THREAD

**Issue by harelassayag** [scylladb/scylla-cluster-tests#510]
```
2018-02-26 17:49:03,927 connectionpool   L0396 DEBUG| https://www.googleapis.com:443 "GET /compute/v1/projects/skilled-adapter-452/aggregated/disks?maxResults=500 HTTP/1.1" 200 None
2018-02-26 17:49:03,942 connectionpool   L0208 DEBUG| Starting new HTTP connection (1): 35.229.125.230
2018-02-26 17:49:03,950 connectionpool   L0396 DEBUG| http://35.229.125.230:10000 "GET /stream_manager/ HTTP/1.1" 200 2
2018-02-26 17:49:03,962 nemesis          L0505 DEBUG| sdcm.nemesis.ChaosMonkey: Abort repair streaming by storage_service/force_terminate_repair API
2018-02-26 17:49:04,087 connectionpool   L0396 DEBUG| https://www.googleapis.com:443 "GET /compute/v1/projects/skilled-adapter-452/zones/us-east1-b/instances/longevity-tls-50gb-4d-enterprise-db-node-d97a364e-0-9
 HTTP/1.1" 200 None
2018-02-26 17:49:04,273 connectionpool   L0396 DEBUG| https://www.googleapis.com:443 "GET /compute/v1/projects/skilled-adapter-452/aggregated/disks?maxResults=500 HTTP/1.1" 200 None
2018-02-26 17:49:04,287 connectionpool   L0208 DEBUG| Starting new HTTP connection (1): 35.229.125.230
2018-02-26 17:49:04,292 connectionpool   L0396 DEBUG| http://35.229.125.230:10000 "POST /storage_service/force_terminate_repair HTTP/1.1" 404 37
2018-02-26 17:49:04,293 nemesis          L0552 ERROR| sdcm.nemesis.ChaosMonkey: Unhandled exception in method <function disrupt at 0x5336d70>
Traceback (most recent call last):
  File "/jenkins/slave/workspace/scylla-enterprise-2017.1-longevity-gce/label/gce/sdcm/nemesis.py", line 548, in wrapper
    result = method(*args, **kwargs)
  File "/jenkins/slave/workspace/scylla-enterprise-2017.1-longevity-gce/label/gce/sdcm/nemesis.py", line 685, in disrupt
    self.call_random_disrupt_method()
  File "/jenkins/slave/workspace/scylla-enterprise-2017.1-longevity-gce/label/gce/sdcm/nemesis.py", line 393, in call_random_disrupt_method
    disrupt_method()
  File "/jenkins/slave/workspace/scylla-enterprise-2017.1-longevity-gce/label/gce/sdcm/nemesis.py", line 508, in disrupt_abort_repair
    assert resp.status_code in [200, 201, 202]
AssertionError

```
@amoskong the full log is in public-jenkins-builder1:/jenkins/slave/workspace/scylla-enterprise-2017.1-longevity-gce/label/gce/job-2018-02-26T12.23-e0fff3e
do you mind taking a look? thanks

**Comment by amoskong** [comment]
On Tue, Feb 27, 2018 at 10:23 PM, harelassayag <notifications@github.com>
wrote:

> 2018-02-26 17:49:03,927 connectionpool   L0396 DEBUG| https://www.googleapis.com:443 "GET /compute/v1/projects/skilled-adapter-452/aggregated/disks?maxResults=500 HTTP/1.1" 200 None
> 2018-02-26 17:49:03,942 connectionpool   L0208 DEBUG| Starting new HTTP connection (1): 35.229.125.230
> 2018-02-26 17:49:03,950 connectionpool   L0396 DEBUG| http://35.229.125.230:10000 "GET /stream_manager/ HTTP/1.1" 200 2
> 2018-02-26 17:49:03,962 nemesis          L0505 DEBUG| sdcm.nemesis.ChaosMonkey: Abort repair streaming by storage_service/force_terminate_repair API
> 2018-02-26 17:49:04,087 connectionpool   L0396 DEBUG| https://www.googleapis.com:443 "GET /compute/v1/projects/skilled-adapter-452/zones/us-east1-b/instances/longevity-tls-50gb-4d-enterprise-db-node-d97a364e-0-9
>  HTTP/1.1" 200 None
> 2018-02-26 17:49:04,273 connectionpool   L0396 DEBUG| https://www.googleapis.com:443 "GET /compute/v1/projects/skilled-adapter-452/aggregated/disks?maxResults=500 HTTP/1.1" 200 None
> 2018-02-26 17:49:04,287 connectionpool   L0208 DEBUG| Starting new HTTP connection (1): 35.229.125.230
> 2018-02-26 17:49:04,292 connectionpool   L0396 DEBUG| http://35.229.125.230:10000 "POST /storage_service/force_terminate_repair HTTP/1.1" 404 37
> 2018-02-26 17:49:04,293 nemesis          L0552 ERROR| sdcm.nemesis.ChaosMonkey: Unhandled exception in method <function disrupt at 0x5336d70>
> Traceback (most recent call last):
>   File "/jenkins/slave/workspace/scylla-enterprise-2017.1-longevity-gce/label/gce/sdcm/nemesis.py", line 548, in wrapper
>     result = method(*args, **kwargs)
>   File "/jenkins/slave/workspace/scylla-enterprise-2017.1-longevity-gce/label/gce/sdcm/nemesis.py", line 685, in disrupt
>     self.call_random_disrupt_method()
>   File "/jenkins/slave/workspace/scylla-enterprise-2017.1-longevity-gce/label/gce/sdcm/nemesis.py", line 393, in call_random_disrupt_method
>     disrupt_method()
>   File "/jenkins/slave/workspace/scylla-enterprise-2017.1-longevity-gce/label/gce/sdcm/nemesis.py", line 508, in disrupt_abort_repair
>     assert resp.status_code in [200, 201, 202]
> AssertionError
>
>
> @amoskong <https://github.com/amoskong> the full log is in
> public-jenkins-builder1:/jenkins/slave/workspace/scylla-enterprise-2017.1-
> longevity-gce/label/gce/latest
> do you mind taking a look? thanks
>
Thanks for the reporting, I will check it soon.

**Comment by amoskong** [comment]
reopen this issue if it still exists.
