### ISSUE TITLE
clean-sct-runners is not working on Azure

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#5173]
After recent change cleaning SCT runners for Azure is not working:
```
21:18:29  1 SCT runner(s) found:
21:18:29      [azure/eastus] sct-runner-1.5-instance-3b639d53, launched at August 24, 2022, 16:33:17 UTC, keep: 13, keep_action: terminate, public IPs are ['13.82.6.49']
21:18:29  Managing SCT runner: sct-runner-1.5-instance-3b639d53 in region: eastus
21:18:35  Found no matching instances
21:18:35  UTC now: 2022-08-24 19:18:34.870113+00:00
21:18:35  Managing runner's tags. Timeout flag: False, logs_collected: None, dry_run: False
21:18:35  Traceback (most recent call last):
21:18:35    File "/home/jenkins/slave/workspace/scylla-staging/lukasz/mini-longevity/scylla-cluster-tests/./sct.py", line 1499, in <module>
21:18:35      cli()
21:18:35    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1137, in __call__
21:18:35      return self.main(*args, **kwargs)
21:18:35    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1062, in main
21:18:35      rv = self.invoke(ctx)
21:18:35    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1668, in invoke
21:18:35      return _process_result(sub_ctx.command.invoke(sub_ctx))
21:18:35    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
21:18:35      return ctx.invoke(self.callback, **ctx.params)
21:18:35    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 763, in invoke
21:18:35      return __callback(*args, **kwargs)
21:18:35    File "/home/jenkins/slave/workspace/scylla-staging/lukasz/mini-longevity/scylla-cluster-tests/./sct.py", line 1427, in clean_runner_instances
21:18:35      clean_sct_runners(test_runner_ip=runner_ip, test_status=test_status, dry_run=dry_run)
21:18:35    File "/home/jenkins/slave/workspace/scylla-staging/lukasz/mini-longevity/scylla-cluster-tests/sdcm/sct_runner.py", line 1137, in clean_sct_runners
21:18:35      sct_runner_info = _manage_runner_keep_tag_value(test_status=test_status, utc_now=utc_now,
21:18:35    File "/home/jenkins/slave/workspace/scylla-staging/lukasz/mini-longevity/scylla-cluster-tests/sdcm/sct_runner.py", line 1102, in _manage_runner_keep_tag_value
21:18:35      sct_runner_info.sct_runner_class.set_tags(sct_runner_info, {"keep": "alive", "keep_action": "keep"})
21:18:35    File "/home/jenkins/slave/workspace/scylla-staging/lukasz/mini-longevity/scylla-cluster-tests/sdcm/sct_runner.py", line 1016, in set_tags
21:18:35      resource_mgmt_client.tags.create_or_update_at_scope(scope=instance.id, parameters=params)
21:18:35    File "/usr/local/lib/python3.10/site-packages/azure/mgmt/resource/resources/v2021_04_01/operations/_tags_operations.py", line 421, in create_or_update_at_scope
21:18:35      raise HttpResponseError(response=response, error_format=ARMErrorFormat)
21:18:35  azure.core.exceptions.HttpResponseError: (InvalidRequestContent) The request content was invalid and could not be deserialized: 'Could not find member 'operation' on object of type 'TagsDefinition'. Path 'operation', line 1, position 13.'.
21:18:35  Code: InvalidRequestContent
21:18:35  Message: The request content was invalid and could not be deserialized: 'Could not find member 'operation' on object of type 'TagsDefinition'. Path 'operation', line 1, position 13.'.
```

**Comment by soyacz** [comment]
I don't think it reproduces. Closing
