### ISSUE TITLE
Multiple nemesis longevity: two nemeses start without a target node and fail instantly

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla-cluster-tests#5179]
### Prerequisites

* [ ] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: branch-2022.2
* **scylla**: 2022.2.0~rc0-0

### Logs
* test_id: 106870ad-dc22-4572-8fd1-87455e1af652
* job link: https://jenkins.scylladb.com/job/enterprise-2022.2/job/longevity/job/longevity-2TB-48h-authorization-and-tls-ssl-1dis-2nondis-nemesis-test/

### Description

In this scenario, `1dis-2nondis-nemesis`, SCT starts multiple nemeses threads. However, it seems that the two "nondis" (`NonDisruptiveMonkey`) nemesis threads are not encapsulated in the `disrupt_method_wrapper` wrapper the same way that the dis (`DisruptiveMonkey`) nemesis thread does. As a result, the 2 nondis nemesis threads fail immediately since no target node is picked for them, since the target node is picked inside the wrapper. This can be seen here:
```
< t:2022-08-23 16:48:29,658 f:nemesis.py      l:334  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.DisruptiveMonkey: Interval: 1800 s
< t:2022-08-23 16:48:29,659 f:nemesis.py      l:1573 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.DisruptiveMonkey: >>>>>>>>>>>>>Started random_disrupt_method rolling_config_change_internode_compression
< t:2022-08-23 16:48:29,659 f:nemesis.py      l:326  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.DisruptiveMonkey: Current Target: Node longevity-tls-2tb-48h-1dis-2nondis--db-node-106870ad-1 [54.171.229.22 | 10.4.3.156] (seed: True) with running nemesis: None
< t:2022-08-23 16:48:29,659 f:cluster.py      l:3946 c:sdcm.cluster         p:DEBUG > Cluster longevity-tls-2tb-48h-1dis-2nondis--db-cluster-106870ad (AMI: ['ami-044020f115ee292eb'] Type: i3en.3xlarge): Cluster health check disabled
< t:2022-08-23 16:48:29,659 f:nemesis.py      l:3610 c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.DisruptiveMonkey: Start disruption at `2022-08-23 16:48:29.659722`
< t:2022-08-23 16:48:29,660 f:nemesis.py      l:1001 c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.DisruptiveMonkey: Set current_disruption -> RollingConfigChangeInternodeCompression Node longevity-tls-2tb-48h-1dis-2nondis--db-node-106870ad-1 [54.171.229.22 | 10.4.3.156] (seed: True)
...
< t:2022-08-23 16:48:29,685 f:nemesis.py      l:334  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.NonDisruptiveMonkey: Interval: 1800 s
< t:2022-08-23 16:48:29,685 f:nemesis.py      l:1573 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.NonDisruptiveMonkey: >>>>>>>>>>>>>Started random_disrupt_method no_corrupt_repair
< t:2022-08-23 16:48:29,685 f:nemesis.py      l:1413 c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.NonDisruptiveMonkey: Prepare test tables if they do not exist
< t:2022-08-23 16:48:29,686 f:nemesis.py      l:1579 c:sdcm.nemesis         p:ERROR > sdcm.nemesis.NonDisruptiveMonkey: ('Exception in random_disrupt_method %s: %s', 'no_corrupt_repair', AttributeError("'NoneType' object has no attribute 'CQL_PORT'"))
< t:2022-08-23 16:48:29,698 f:nemesis.py      l:334  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.NonDisruptiveMonkey: Interval: 1800 s
< t:2022-08-23 16:48:29,698 f:nemesis.py      l:1573 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.NonDisruptiveMonkey: >>>>>>>>>>>>>Started random_disrupt_method ldap_connection_toggle
< t:2022-08-23 16:48:29,699 f:nemesis.py      l:1579 c:sdcm.nemesis         p:ERROR > sdcm.nemesis.NonDisruptiveMonkey: ('Exception in random_disrupt_method %s: %s', 'ldap_connection_toggle', UnsupportedNemesis('Cluster is not configured to run with LDAP authorization, hence skipping'))
< t:2022-08-23 16:48:29,699 f:nemesis.py      l:344  c:sdcm.nemesis         p:WARNING > sdcm.nemesis.NonDisruptiveMonkey: Skipping unsupported nemesis: Cluster is not configured to run with LDAP authorization, hence skipping
< t:2022-08-23 16:48:29,699 f:nemesis.py      l:1573 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.NonDisruptiveMonkey: >>>>>>>>>>>>>Started random_disrupt_method run_cdcstressor_tool
< t:2022-08-23 16:48:29,700 f:nemesis.py      l:1579 c:sdcm.nemesis         p:ERROR > sdcm.nemesis.NonDisruptiveMonkey: ('Exception in random_disrupt_method %s: %s', 'run_cdcstressor_tool', AttributeError("'NoneType' object has no attribute 'CQL_PORT'"))
```
```
2022-08-23 17:18:29.687: (ThreadFailedEvent Severity.ERROR) period_type=one-time event_id=b19a1bfd-1f19-4eed-8b4c-cde6f77ac0e2: message='NoneType' object has no attribute 'CQL_PORT'
Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/sct_events/decorators.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 342, in run
    self.disrupt()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4509, in disrupt
    self.call_random_disrupt_method(disrupt_methods=self.disrupt_methods_list)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1569, in call_random_disrupt_method
    self.execute_disrupt_method(disrupt_method)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1576, in execute_disrupt_method
    disrupt_method()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1414, in disrupt_no_corrupt_repair
    self._prepare_test_table(ks=f'drop_table_during_repair_ks_{i}', table='standard1')
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1667, in _prepare_test_table
    ks_cfs = self.cluster.get_non_system_ks_cf_list(db_node=self.target_node)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3354, in get_non_system_ks_cf_list
    return self.get_any_ks_cf_list(db_node, filter_out_table_with_counter=filter_out_table_with_counter,
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3415, in get_any_ks_cf_list
    with self.cql_connection_patient(db_node) as session:
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 67, in inner
    return func(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3333, in cql_connection_patient
    return self.cql_connection(**kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3304, in cql_connection
    return self._create_session(node=node, keyspace=keyspace, user=user, password=password,
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3262, in _create_session
    port = node.CQL_PORT
AttributeError: 'NoneType' object has no attribute 'CQL_PORT'
```
```
2022-08-23 17:18:29.700: (ThreadFailedEvent Severity.ERROR) period_type=one-time event_id=b597d91c-2e5b-4471-8f7e-46736434dd69: message='NoneType' object has no attribute 'CQL_PORT'
Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/sct_events/decorators.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 342, in run
    self.disrupt()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4509, in disrupt
    self.call_random_disrupt_method(disrupt_methods=self.disrupt_methods_list)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1569, in call_random_disrupt_method
    self.execute_disrupt_method(disrupt_method)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1576, in execute_disrupt_method
    disrupt_method()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3405, in disrupt_run_cdcstressor_tool
    ks_tables_with_cdc = self.cluster.get_all_tables_with_cdc(self.target_node)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3445, in get_all_tables_with_cdc
    all_ks_cf = self.get_any_ks_cf_list(db_node,
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3415, in get_any_ks_cf_list
    with self.cql_connection_patient(db_node) as session:
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 67, in inner
    return func(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3333, in cql_connection_patient
    return self.cql_connection(**kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3304, in cql_connection
    return self._create_session(node=node, keyspace=keyspace, user=user, password=password,
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3262, in _create_session
    port = node.CQL_PORT
AttributeError: 'NoneType' object has no attribute 'CQL_PORT'
```

### Steps to Reproduce

1. Start a 1dis2nondis longevity
2. See as the two nondis nemeses immediately fail.

**Expected behavior:** All nemeses are wrapped accordingly and are able to run with a selected target node.

**Actual behavior:** Two of the 3 nemesis threads are DOA since they have no target node

**Comment by fruch** [comment]
Seems like https://github.com/scylladb/scylla-cluster-tests/pull/5086 needs to be reverted. seems like `wrapped_disruptive_methods` is shared why the `cls` passed to `__new__` is not the same one hence only one class get wrapped. @juliayakovlev seems like we'll still need the initial approach of removing the `__new__`  and moving the warping code to `__init__`.

since in this case we use two different nemesis class, and not the same one, we never hit the issue of double wrapping.

**Comment by juliayakovlev** [comment]
> Seems like #5086 needs to be reverted. seems like `wrapped_disruptive_methods` is shared why the `cls` passed to `__new__` is not the same one hence only one class get wrapped. @juliayakovlev seems like we'll still need the initial approach of removing the `__new__` and moving the warping code to `__init__`.
> 
> since in this case we use two different nemesis class, and not the same one, we never hit the issue of double wrapping.

@fruch 
yes, I am on it
