### ISSUE TITLE
manifest for scylladb/scylla-enterprise:2022.1 not found: manifest unknown: manifest unknown

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-cluster-tests#5183]
Failed to run longevity test with docker backed and version "2022.1"

Error:
```
Traceback (most recent call last):
  File "/home/juliayakovlev/scylla_repo/scylla-cluster-tests/sdcm/tester.py", line 144, in wrapper
    return method(*args, **kwargs)
  File "/home/juliayakovlev/scylla_repo/scylla-cluster-tests/sdcm/utils/decorators.py", line 116, in inner
    res = func(*args, **kwargs)
  File "/home/juliayakovlev/scylla_repo/scylla-cluster-tests/sdcm/tester.py", line 694, in setUp
    self.init_resources()
  File "/home/juliayakovlev/scylla_repo/scylla-cluster-tests/sdcm/tester.py", line 1587, in init_resources
    self.get_cluster_docker()
  File "/home/juliayakovlev/scylla_repo/scylla-cluster-tests/sdcm/tester.py", line 1157, in get_cluster_docker
    self.db_cluster = cluster_docker.ScyllaDockerCluster(n_nodes=[self.params.get("n_db_nodes"), ],
  File "/home/juliayakovlev/scylla_repo/scylla-cluster-tests/sdcm/cluster_docker.py", line 265, in __init__
    super().__init__(docker_image=docker_image,
  File "/home/juliayakovlev/scylla_repo/scylla-cluster-tests/sdcm/cluster.py", line 3537, in __init__
    super().__init__(*args, **kwargs)
  File "/home/juliayakovlev/scylla_repo/scylla-cluster-tests/sdcm/cluster_docker.py", line 195, in __init__
    super().__init__(cluster_prefix=cluster_prefix,
  File "/home/juliayakovlev/scylla_repo/scylla-cluster-tests/sdcm/cluster.py", line 2998, in __init__
    self.add_nodes(num, dc_idx=dc_idx, enable_auto_bootstrap=self.auto_bootstrap)
  File "/home/juliayakovlev/scylla_repo/scylla-cluster-tests/sdcm/cluster_docker.py", line 252, in add_nodes
    return self._get_nodes() if self.test_config.REUSE_CLUSTER else self._create_nodes(count, enable_auto_bootstrap)
  File "/home/juliayakovlev/scylla_repo/scylla-cluster-tests/sdcm/cluster_docker.py", line 237, in _create_nodes
    node = self._create_node(node_index)
  File "/home/juliayakovlev/scylla_repo/scylla-cluster-tests/sdcm/cluster_docker.py", line 219, in _create_node
    ContainerManager.build_container_image(node, "node")
  File "/home/juliayakovlev/scylla_repo/scylla-cluster-tests/sdcm/utils/docker_utils.py", line 380, in build_container_image
    image, logs = docker_client.images.build(tag=image_tag, **dockerfile_args, **build_args)
  File "/usr/local/lib/python3.10/site-packages/docker/models/images.py", line 287, in build
    raise BuildError(chunk['error'], result_stream)
docker.errors.BuildError: manifest for scylladb/scylla-enterprise:2022.1 not found: manifest unknown: manifest unknown
```

Ran it as:
```
juliayakovlev@juliayakovlev-Latitude-5421 ~/Downloads/sct-runner-af445ef4 $ export SCT_SCYLLA_VERSION=2022.1
juliayakovlev@juliayakovlev-Latitude-5421 ~/Downloads/sct-runner-af445ef4 $ hydra run-test longevity_sla_test.LongevitySlaTest.test_custom_time --backend docker --config /home/juliayakovlev/scylla_repo/scylla-cluster-tests/test-cases/longevity/longevity-sla-10gb-3h.yaml
```

Run it for the new test, does not exist in master.

**Comment by juliayakovlev** [comment]
ok, thanks
