### ISSUE TITLE
azure.core.exceptions.ClientAuthenticationError: Authentication failed running cleanup on dev machine

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-cluster-tests#5280]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master
* **scylla**: any

### Logs
* test_id: -
* job log: -

### Description

Running following SCT command on my dev laptop:
```
`pwd`/sct.py clean-resources --test-id %test-id%
```

I get following error in the end of the scenario:

```
...
There are no clusters to remove in GKE
Found following orphaned GKE disks: {}
Going to delete: kubernetes-platform-upgrade-dev-f680f401
There are no instances to remove in GCE
kubernetes-platform-upgrade-dev-f680f401 deleted=None
There are no instances to remove in GCE
Traceback (most recent call last):
  File "%full-path%/sct.py", line 1513, in <module>
    cli()
  File "%full-lib-path%/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "%full-lib-path%/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "%full-lib-path%/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "%full-lib-path%/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "%full-lib-path%/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "%full-lib-path%/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "%full-path%/sct.py", line 297, in clean_resources
    clean_func(param, dry_run=dry_run)
  File "%full-path%/sdcm/utils/common.py", line 553, in clean_cloud_resources
    clean_instances_azure(tags_dict, dry_run=dry_run)
  File "%full-path%/sdcm/utils/common.py", line 1168, in clean_instances_azure
    provisioners = AzureProvisioner.discover_regions(tags_dict.get("TestId", ""))
  File "%full-path%/sdcm/provision/azure/provisioner.py", line 87, in discover_regions
    all_resource_groups: List[ResourceGroup] = [rg for rg in azure_service.resource.resource_groups.list()
  File "%full-path%/sdcm/provision/azure/provisioner.py", line 87, in <listcomp>
    all_resource_groups: List[ResourceGroup] = [rg for rg in azure_service.resource.resource_groups.list()
  File "%full-lib-path%/site-packages/azure/core/paging.py", line 128, in __next__
    return next(self._page_iterator)
  File "%full-lib-path%/site-packages/azure/core/paging.py", line 76, in __next__
    self._response = self._get_next(self.continuation_token)
  File "%full-lib-path%/site-packages/azure/mgmt/resource/resources/v2021_04_01/operations/_resource_groups_operations.py", line 599, in get_next
    pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)
  File "%full-lib-path%/site-packages/azure/core/pipeline/_base.py", line 211, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "%full-lib-path%/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "%full-lib-path%/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "%full-lib-path%/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "%full-lib-path%/site-packages/azure/mgmt/core/policies/_base.py", line 47, in send
    response = self.next.send(request)
  File "%full-lib-path%/site-packages/azure/core/pipeline/policies/_redirect.py", line 158, in send
    response = self.next.send(request)
  File "%full-lib-path%/site-packages/azure/core/pipeline/policies/_retry.py", line 446, in send
    response = self.next.send(request)
  File "%full-lib-path%/site-packages/azure/core/pipeline/policies/_authentication.py", line 116, in send
    self.on_request(request)
  File "%full-lib-path%/site-packages/azure/core/pipeline/policies/_authentication.py", line 93, in on_request
    self._token = self._credential.get_token(*self._scopes)
  File "%full-lib-path%/site-packages/azure/identity/_internal/get_token_mixin.py", line 72, in get_token
    token = self._request_token(*scopes)
  File "%full-lib-path%/site-packages/azure/identity/_internal/decorators.py", line 45, in wrapper
    return fn(*args, **kwargs)
  File "%full-lib-path%/site-packages/azure/identity/_internal/client_credential_base.py", line 42, in _request_token
    raise ClientAuthenticationError(message=message)
azure.core.exceptions.ClientAuthenticationError: Authentication failed: AADSTS7000222: The provided client secret keys for app 'b4003937-b8c1-4bc5-91cc-66da6c7c7fff' are expired. Visit the Azure portal to create new keys for your app: https://aka.ms/NewClientSecret, or consider using certificate credentials for added security: https://aka.ms/certCreds.
Trace ID: c6d216e9-d899-431c-b64b-ab247d892000
Correlation ID: 8c9db794-9e93-4c30-91fd-3bdbb1d1ff54
Timestamp: 2022-09-15 14:36:58Z
ERROR: InvocationError for command /usr/bin/bash -c '%full-path%/sct.py clean-resources --test-id f680f401-87cd-414b-b95d-acc333e17574' (exited with code 1)
```

Yes, I don't have azure creds and don't need it cleaning up AWS/GCE resources.

### Steps to Reproduce

1. Do not configure azure auth
2. Run sct cleanup by test id
3. See error

**Expected behavior:** no error, because azure creds must be taken from the keystore the same way it is done for AWS and GCE.

**Actual behavior:** Not having azure client configured locally I get this error.

**Comment by fgelcer** [comment]
it was already fixed.. the problem was that the credentials have expired, and new ones are in place.

**Comment by fgelcer** [comment]
it was already fixed.. the problem was that the credentials have expired, and new ones are in place.
