### ISSUE TITLE
`disrupt_hot_reloading_internode_certificate` not seeing the reload message

### ISSUE THREAD

**Issue by k0machi** [scylladb/scylla-cluster-tests#5354]
The run below failed due to this nemesis failing to find the reload message:
```
Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3669, in wrapper
    result = method(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3338, in disrupt_hot_reloading_internode_certificate
    if not check_ssl_reload_log(node_system_logs[node]):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 67, in inner
    return func(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3315, in check_ssl_reload_log
    raise LogContentNotFound('Reload SSL message not found in node log')
sdcm.nemesis.LogContentNotFound: Reload SSL message not found in node log
```
However, it is present in the log in all six nodes (7th node was created after this nemesis):
```
longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-2/messages.log
14355:2022-10-11T18:51:43+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-2     !INFO | scylla[7922]:  [shard  0] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
14356:2022-10-11T18:51:43+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-2     !INFO | scylla[7922]:  [shard  6] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
14357:2022-10-11T18:51:43+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-2     !INFO | scylla[7922]:  [shard  9] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
14358:2022-10-11T18:51:43+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-2     !INFO | scylla[7922]:  [shard 12] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
14359:2022-10-11T18:51:43+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-2     !INFO | scylla[7922]:  [shard 13] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
14360:2022-10-11T18:51:43+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-2     !INFO | scylla[7922]:  [shard 11] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
14361:2022-10-11T18:51:43+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-2     !INFO | scylla[7922]:  [shard  8] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
14362:2022-10-11T18:51:43+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-2     !INFO | scylla[7922]:  [shard  5] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
14363:2022-10-11T18:51:43+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-2     !INFO | scylla[7922]:  [shard  3] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
14364:2022-10-11T18:51:43+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-2     !INFO | scylla[7922]:  [shard  7] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
14365:2022-10-11T18:51:43+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-2     !INFO | scylla[7922]:  [shard  4] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
14366:2022-10-11T18:51:43+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-2     !INFO | scylla[7922]:  [shard  1] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
14367:2022-10-11T18:51:43+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-2     !INFO | scylla[7922]:  [shard  2] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
14368:2022-10-11T18:51:43+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-2     !INFO | scylla[7922]:  [shard 10] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}

longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-6/messages.log
7736:2022-10-11T18:52:09+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-6     !INFO | scylla[8182]:  [shard  1] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
7737:2022-10-11T18:52:09+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-6     !INFO | scylla[8182]:  [shard  6] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
7738:2022-10-11T18:52:09+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-6     !INFO | scylla[8182]:  [shard 10] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
7739:2022-10-11T18:52:09+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-6     !INFO | scylla[8182]:  [shard  7] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
7740:2022-10-11T18:52:09+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-6     !INFO | scylla[8182]:  [shard  2] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
7741:2022-10-11T18:52:09+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-6     !INFO | scylla[8182]:  [shard 11] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
7742:2022-10-11T18:52:09+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-6     !INFO | scylla[8182]:  [shard  8] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
7743:2022-10-11T18:52:09+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-6     !INFO | scylla[8182]:  [shard  9] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
7744:2022-10-11T18:52:09+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-6     !INFO | scylla[8182]:  [shard 13] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
7745:2022-10-11T18:52:09+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-6     !INFO | scylla[8182]:  [shard  4] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
7746:2022-10-11T18:52:09+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-6     !INFO | scylla[8182]:  [shard  3] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
7747:2022-10-11T18:52:09+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-6     !INFO | scylla[8182]:  [shard 12] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
7748:2022-10-11T18:52:09+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-6     !INFO | scylla[8182]:  [shard  0] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
7749:2022-10-11T18:52:09+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-6     !INFO | scylla[8182]:  [shard  5] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}

longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-5/messages.log
44449:2022-10-11T18:53:51+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-5     !INFO | scylla[11134]:  [shard  6] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
44450:2022-10-11T18:53:51+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-5     !INFO | scylla[11134]:  [shard 10] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
44451:2022-10-11T18:53:51+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-5     !INFO | scylla[11134]:  [shard 13] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
44452:2022-10-11T18:53:51+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-5     !INFO | scylla[11134]:  [shard  3] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
44453:2022-10-11T18:53:51+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-5     !INFO | scylla[11134]:  [shard  5] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
44454:2022-10-11T18:53:51+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-5     !INFO | scylla[11134]:  [shard  7] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
44455:2022-10-11T18:53:51+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-5     !INFO | scylla[11134]:  [shard  2] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
44456:2022-10-11T18:53:51+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-5     !INFO | scylla[11134]:  [shard 11] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
44457:2022-10-11T18:53:51+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-5     !INFO | scylla[11134]:  [shard 12] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
44458:2022-10-11T18:53:51+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-5     !INFO | scylla[11134]:  [shard  0] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
44459:2022-10-11T18:53:51+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-5     !INFO | scylla[11134]:  [shard  1] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
44460:2022-10-11T18:53:51+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-5     !INFO | scylla[11134]:  [shard  9] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
44461:2022-10-11T18:53:51+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-5     !INFO | scylla[11134]:  [shard  4] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
44462:2022-10-11T18:53:51+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-5     !INFO | scylla[11134]:  [shard  8] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}

longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-4/messages.log
11239:2022-10-11T18:51:59+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-4     !INFO | scylla[8057]:  [shard  6] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
11240:2022-10-11T18:51:59+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-4     !INFO | scylla[8057]:  [shard  3] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
11241:2022-10-11T18:51:59+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-4     !INFO | scylla[8057]:  [shard  9] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
11242:2022-10-11T18:51:59+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-4     !INFO | scylla[8057]:  [shard 11] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
11243:2022-10-11T18:51:59+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-4     !INFO | scylla[8057]:  [shard  5] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
11244:2022-10-11T18:51:59+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-4     !INFO | scylla[8057]:  [shard 13] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
11245:2022-10-11T18:51:59+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-4     !INFO | scylla[8057]:  [shard 10] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
11246:2022-10-11T18:51:59+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-4     !INFO | scylla[8057]:  [shard  0] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
11247:2022-10-11T18:51:59+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-4     !INFO | scylla[8057]:  [shard  8] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
11248:2022-10-11T18:51:59+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-4     !INFO | scylla[8057]:  [shard  1] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
11249:2022-10-11T18:51:59+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-4     !INFO | scylla[8057]:  [shard 12] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
11250:2022-10-11T18:51:59+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-4     !INFO | scylla[8057]:  [shard  7] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
11251:2022-10-11T18:51:59+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-4     !INFO | scylla[8057]:  [shard  4] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
11252:2022-10-11T18:51:59+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-4     !INFO | scylla[8057]:  [shard  2] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}

longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-3/messages.log
12449:2022-10-11T18:51:50+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-3     !INFO | scylla[8001]:  [shard 10] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
12450:2022-10-11T18:51:50+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-3     !INFO | scylla[8001]:  [shard  2] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
12451:2022-10-11T18:51:50+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-3     !INFO | scylla[8001]:  [shard  0] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
12452:2022-10-11T18:51:50+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-3     !INFO | scylla[8001]:  [shard  4] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
12453:2022-10-11T18:51:50+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-3     !INFO | scylla[8001]:  [shard  1] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
12454:2022-10-11T18:51:50+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-3     !INFO | scylla[8001]:  [shard  8] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
12455:2022-10-11T18:51:50+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-3     !INFO | scylla[8001]:  [shard  3] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
12456:2022-10-11T18:51:50+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-3     !INFO | scylla[8001]:  [shard  5] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
12457:2022-10-11T18:51:50+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-3     !INFO | scylla[8001]:  [shard 12] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
12458:2022-10-11T18:51:50+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-3     !INFO | scylla[8001]:  [shard 13] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
12459:2022-10-11T18:51:50+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-3     !INFO | scylla[8001]:  [shard  6] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
12460:2022-10-11T18:51:50+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-3     !INFO | scylla[8001]:  [shard 11] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
12461:2022-10-11T18:51:50+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-3     !INFO | scylla[8001]:  [shard  9] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
12462:2022-10-11T18:51:50+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-3     !INFO | scylla[8001]:  [shard  7] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}

longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-1/messages.log
18036:2022-10-11T18:51:34+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-1     !INFO | scylla[7850]:  [shard 10] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
18037:2022-10-11T18:51:34+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-1     !INFO | scylla[7850]:  [shard  1] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
18038:2022-10-11T18:51:34+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-1     !INFO | scylla[7850]:  [shard 13] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
18039:2022-10-11T18:51:34+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-1     !INFO | scylla[7850]:  [shard  0] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
18040:2022-10-11T18:51:34+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-1     !INFO | scylla[7850]:  [shard 12] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
18041:2022-10-11T18:51:34+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-1     !INFO | scylla[7850]:  [shard  7] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
18042:2022-10-11T18:51:34+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-1     !INFO | scylla[7850]:  [shard 11] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
18043:2022-10-11T18:51:34+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-1     !INFO | scylla[7850]:  [shard  3] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
18044:2022-10-11T18:51:34+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-1     !INFO | scylla[7850]:  [shard  8] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
18045:2022-10-11T18:51:34+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-1     !INFO | scylla[7850]:  [shard  2] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
18046:2022-10-11T18:51:34+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-1     !INFO | scylla[7850]:  [shard  6] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
18047:2022-10-11T18:51:34+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-1     !INFO | scylla[7850]:  [shard  9] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
18048:2022-10-11T18:51:34+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-1     !INFO | scylla[7850]:  [shard  4] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
18049:2022-10-11T18:51:34+00:00 longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-1     !INFO | scylla[7850]:  [shard  5] messaging_service - Reloaded {/etc/scylla/ssl_conf/db.crt}
```

[Run](https://argus.scylladb.com/test/e22b6425-5904-460e-b79d-f9ca0ca02bf9/runs?additionalRuns%5B%5D=aaa975d8-6ea6-4acc-b9bc-d94f55c82ff8)

## Installation details

Kernel Version: 5.15.0-1020-aws
Scylla version (or git commit hash): `5.1.0~rc3-20221009.9deeeb4db1cd` with build-id `4e3d124e4636ed9e7f88aeaace85c1ac637ed200`
Relocatable Package: http://downloads.scylladb.com/unstable/scylla/branch-5.1/relocatable/2022-10-09T10:30:27Z/scylla-x86_64-package.tar.gz
Cluster size: 6 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-7 (54.236.240.226 | 10.12.1.234) (shards: 14)
- longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-6 (3.238.149.179 | 10.12.0.189) (shards: 14)
- longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-5 (3.239.216.179 | 10.12.3.239) (shards: 14)
- longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-4 (3.238.77.70 | 10.12.0.138) (shards: 14)
- longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-3 (54.237.148.48 | 10.12.3.231) (shards: 14)
- longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-2 (3.237.201.120 | 10.12.2.241) (shards: 14)
- longevity-cdc-100gb-4h-5-1-db-node-aaa975d8-1 (100.26.245.126 | 10.12.2.76) (shards: 14)

OS / Image: `ami-0509186cdf80e8530` (aws: us-east-1)

Test: `longevity-cdc-100gb-4h-test`
Test id: `aaa975d8-6ea6-4acc-b9bc-d94f55c82ff8`
Test name: `scylla-5.1/longevity/longevity-cdc-100gb-4h-test`
Test config file(s):

- [longevity-cdc-100gb-4h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/cd760149ebe9899cc3d5400d271b0f103877f842/test-cases/longevity/longevity-cdc-100gb-4h.yaml)

- Restore Monitor Stack command: `$ hydra investigate show-monitor aaa975d8-6ea6-4acc-b9bc-d94f55c82ff8`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=aaa975d8-6ea6-4acc-b9bc-d94f55c82ff8)
- Show all stored logs command: `$ hydra investigate show-logs aaa975d8-6ea6-4acc-b9bc-d94f55c82ff8`

## Logs:
- **db-cluster-aaa975d8.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/aaa975d8-6ea6-4acc-b9bc-d94f55c82ff8/20221011_220433/db-cluster-aaa975d8.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/aaa975d8-6ea6-4acc-b9bc-d94f55c82ff8/20221011_220433/db-cluster-aaa975d8.tar.gz)
- **monitor-set-aaa975d8.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/aaa975d8-6ea6-4acc-b9bc-d94f55c82ff8/20221011_220433/monitor-set-aaa975d8.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/aaa975d8-6ea6-4acc-b9bc-d94f55c82ff8/20221011_220433/monitor-set-aaa975d8.tar.gz)
- **loader-set-aaa975d8.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/aaa975d8-6ea6-4acc-b9bc-d94f55c82ff8/20221011_220433/loader-set-aaa975d8.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/aaa975d8-6ea6-4acc-b9bc-d94f55c82ff8/20221011_220433/loader-set-aaa975d8.tar.gz)
- **sct-runner-aaa975d8.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/aaa975d8-6ea6-4acc-b9bc-d94f55c82ff8/20221011_220433/sct-runner-aaa975d8.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/aaa975d8-6ea6-4acc-b9bc-d94f55c82ff8/20221011_220433/sct-runner-aaa975d8.tar.gz)
- **parallel-timelines-report-aaa975d8.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/aaa975d8-6ea6-4acc-b9bc-d94f55c82ff8/20221011_220433/parallel-timelines-report-aaa975d8.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/aaa975d8-6ea6-4acc-b9bc-d94f55c82ff8/20221011_220433/parallel-timelines-report-aaa975d8.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-5.1/job/longevity/job/longevity-cdc-100gb-4h-test/6/)

**Comment by k0machi** [comment]
I think the nemesis doesn't wait for the message, node 5 had this message appear 1 minute after nemesis failed.

**Comment by fruch** [comment]
@ShlomiBalalis didn't you had something similar that ended up in being a glitch with the logging system ?

**Comment by roydahan** [comment]
If we don't wait long enough for the message, let's increase the wait.

**Comment by fgelcer** [comment]
from code perspective, we wait 10 minutes:
```
@timeout_decor(timeout=600, allowed_exceptions=(LogContentNotFound, ))
        def check_ssl_reload_log(node_system_log):
            if not list(node_system_log):
                raise LogContentNotFound('Reload SSL message not found in node log')
            return True
```

**Comment by fgelcer** [comment]
> from code perspective, we wait 10 minutes:
> 

i'm wrong, for branches 2022.2 and 5.1 we wait only 20 seconds:
```
@timeout_decor(timeout=20, allowed_exceptions=(LogContentNotFound, ))
    def check_ssl_reload_log(node_system_log):
        if not list(node_system_log):
            raise LogContentNotFound('Reload SSL message not found in node log')
        return True
```

most likely we should backport #5297
