### ISSUE TITLE
"hydra.sh clean-resources --user " failed to clean azure resources

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-cluster-tests#5373]
Command `./docker/env/hydra.sh clean-resources --user julia.yakovlev` failed to clean azure resources:

```
Cleaning everything for test id: eastus in region: eastus
Initiating cleanup of resource group: SCT-eastus-eastus...
Traceback (most recent call last):
  File "/home/juliayakovlev/scylla_repo/scylla-cluster-tests/./sct.py", line 1513, in <module>
    cli()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/juliayakovlev/scylla_repo/scylla-cluster-tests/./sct.py", line 297, in clean_resources
    clean_func(param, dry_run=dry_run)
  File "/home/juliayakovlev/scylla_repo/scylla-cluster-tests/sdcm/utils/common.py", line 553, in clean_cloud_resources
    clean_instances_azure(tags_dict, dry_run=dry_run)
  File "/home/juliayakovlev/scylla_repo/scylla-cluster-tests/sdcm/utils/common.py", line 1176, in clean_instances_azure
    provisioner.cleanup(wait=False)
  File "/home/juliayakovlev/scylla_repo/scylla-cluster-tests/sdcm/provision/azure/provisioner.py", line 157, in cleanup
    self._rg_provider.delete(wait)
  File "/home/juliayakovlev/scylla_repo/scylla-cluster-tests/sdcm/provision/azure/resource_group_provider.py", line 65, in delete
    task = self._azure_service.resource.resource_groups.begin_delete(self._name)
  File "/usr/local/lib/python3.10/site-packages/azure/mgmt/resource/resources/v2021_04_01/operations/_resource_groups_operations.py", line 256, in begin_delete
    raw_result = self._delete_initial(
  File "/usr/local/lib/python3.10/site-packages/azure/mgmt/resource/resources/v2021_04_01/operations/_resource_groups_operations.py", line 211, in _delete_initial
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/usr/local/lib/python3.10/site-packages/azure/core/exceptions.py", line 107, in map_error
    raise error
azure.core.exceptions.ResourceNotFoundError: (ResourceGroupNotFound) Resource group 'SCT-eastus-eastus' could not be found.
Code: ResourceGroupNotFound
Message: Resource group 'SCT-eastus-eastus' could not be found.
```

Last commit `3f90fd6d44e1ac96f89c5bd78bdd5b743d1de210`

**Comment by fruch** [comment]
Did you had any resources in azure ?

**Comment by juliayakovlev** [comment]
> Did you had any resources in azure ?

yes
