### ISSUE TITLE
disrupt_terminate_and_replace_node

### ISSUE THREAD

**Issue by harelassayag** [scylladb/scylla-cluster-tests#540]
cc: @bentsi
when running reuse on a cluster we encounter this:
```
018-04-10 12:14:59,725 connectionpool   L0396 DEBUG| https://www.googleapis.com:443 "GET /compute/v1/projects/skilled-adapter-452/aggregated/disks?maxResults=500 HTTP/1.1" 200 None
2018-04-10 12:14:59,737 nemesis          L0240 INFO | sdcm.nemesis.ChaosMonkey: Monitoring node: Node longevity-1tb-7d-ent-2018-1-monitor-node-bba4b9d3-0-1 [35.227.39.126 | 10.142.0.10] (seed: None)
2018-04-10 12:14:59,738 nemesis          L0711 ERROR| sdcm.nemesis.ChaosMonkey: Unhandled exception in method <function disrupt at 0x535f140>
Traceback (most recent call last):
  File "/jenkins/slave/workspace/scylla-enterprise-2018.1-longevity-1TB-gce/label/gce3-qavpc/sdcm/nemesis.py", line 707, in wrapper
    result = method(*args, **kwargs)
  File "/jenkins/slave/workspace/scylla-enterprise-2018.1-longevity-1TB-gce/label/gce3-qavpc/sdcm/nemesis.py", line 844, in disrupt
    self.call_random_disrupt_method()
  File "/jenkins/slave/workspace/scylla-enterprise-2018.1-longevity-1TB-gce/label/gce3-qavpc/sdcm/nemesis.py", line 406, in call_random_disrupt_method
    disrupt_method()
  File "/jenkins/slave/workspace/scylla-enterprise-2018.1-longevity-1TB-gce/label/gce3-qavpc/sdcm/nemesis.py", line 290, in disrupt_terminate_and_replace_node
    self._terminate_cluster_node(self.target_node)
  File "/jenkins/slave/workspace/scylla-enterprise-2018.1-longevity-1TB-gce/label/gce3-qavpc/sdcm/nemesis.py", line 253, in _terminate_cluster_node
    self.reconfigure_monitoring()
  File "/jenkins/slave/workspace/scylla-enterprise-2018.1-longevity-1TB-gce/label/gce3-qavpc/sdcm/nemesis.py", line 241, in reconfigure_monitoring
    monitoring_node.reconfigure_prometheus(targets={'db_nodes': targets, 'loaders': loader_targets})
  File "/jenkins/slave/workspace/scylla-enterprise-2018.1-longevity-1TB-gce/label/gce3-qavpc/sdcm/cluster.py", line 589, in reconfigure_prometheus
    self._write_prometheus_cfg(targets)
  File "/jenkins/slave/workspace/scylla-enterprise-2018.1-longevity-1TB-gce/label/gce3-qavpc/sdcm/cluster.py", line 577, in _write_prometheus_cfg
    self.prometheus_custom_cfg_basename)
AttributeError: 'GCENode' object has no attribute 'prometheus_custom_cfg_basename'
```

**Comment by larisau** [comment]
I'll fix it.
