### ISSUE TITLE
Recent master runs aren't getting reported to Argus

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#5473]
Recent runs in master doesn't seems to be reported in Argus

https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-10gb-3h-gce-test/285/
https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-10gb-3h-gce-test/286/

argus.log:
```
< t:2022-11-23 17:17:54,833 f:argus_test_run.py l:244  c:sdcm.argus_test_run  p:INFO  > Preparing Test Details...
< t:2022-11-23 17:17:54,835 f:argus_test_run.py l:258  c:sdcm.argus_test_run  p:INFO  > Preparing Resource Setup...
< t:2022-11-23 17:17:54,835 f:argus_test_run.py l:278  c:sdcm.argus_test_run  p:INFO  > Initializing TestRun...
< t:2022-11-23 17:21:21,283 f:argus_test_run.py l:236  c:sdcm.argus_test_run  p:WARNING > Returning MagicMock from ArgusTestRun.get() as we are unable to acquire Argus connection
```

**Comment by fruch** [comment]
looking at the logs...
```
< t:2022-11-23 17:17:56,584 f:tester.py       l:370  c:LongevityTest        p:WARNING > Unable to set up Argus connection: Unable to connect to any servers
< t:2022-11-23 17:17:56,584 f:tester.py       l:371  c:LongevityTest        p:DEBUG > Error details:  < t:2022-11-23 17:17:56,584 f:tester.py       l:371  c:LongevityTest        p:DEBUG > Error details:
< t:2022-11-23 17:17:56,584 f:tester.py       l:371  c:LongevityTest        p:DEBUG > Traceback (most recent call last):
< t:2022-11-23 17:17:56,584 f:tester.py       l:371  c:LongevityTest        p:DEBUG >   File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 365, in argus_test_run
< t:2022-11-23 17:17:56,584 f:tester.py       l:371  c:LongevityTest        p:DEBUG >     argus_test_run = ArgusTestRun.from_sct_config(test_id=UUID(self.test_id),
< t:2022-11-23 17:17:56,584 f:tester.py       l:371  c:LongevityTest        p:DEBUG >   File "/home/ubuntu/scylla-cluster-tests/sdcm/argus_test_run.py", line 279, in from_sct_config
< t:2022-11-23 17:17:56,584 f:tester.py       l:371  c:LongevityTest        p:DEBUG >     cls.TESTRUN_INSTANCE = TestRunWithHeartbeat(test_id=test_id, build_id=job_name,  # pylint: disable=unexpected-keyword-arg,no-value-for-parameter
< t:2022-11-23 17:17:56,584 f:tester.py       l:371  c:LongevityTest        p:DEBUG >   File "/usr/local/lib/python3.10/site-packages/argus/db/testrun.py", line 698, in __init__
< t:2022-11-23 17:17:56,584 f:tester.py       l:371  c:LongevityTest        p:DEBUG >     self._heartbeat_statement = self.argus.session.prepare(
< t:2022-11-23 17:17:56,584 f:tester.py       l:371  c:LongevityTest        p:DEBUG >   File "/usr/local/lib/python3.10/site-packages/argus/db/testrun.py", line 447, in argus
< t:2022-11-23 17:17:56,584 f:tester.py       l:371  c:LongevityTest        p:DEBUG >     self.get_argus(self._config)
< t:2022-11-23 17:17:56,584 f:tester.py       l:371  c:LongevityTest        p:DEBUG >   File "/usr/local/lib/python3.10/site-packages/argus/db/testrun.py", line 436, in get_argus
< t:2022-11-23 17:17:56,584 f:tester.py       l:371  c:LongevityTest        p:DEBUG >     cls._ARGUS_DB_INTERFACE = ArgusDatabase(config=config)
< t:2022-11-23 17:17:56,584 f:tester.py       l:371  c:LongevityTest        p:DEBUG >   File "/usr/local/lib/python3.10/site-packages/argus/db/interface.py", line 97, in __init__
< t:2022-11-23 17:17:56,584 f:tester.py       l:371  c:LongevityTest        p:DEBUG >     self.session = self.cluster.connect()
< t:2022-11-23 17:17:56,584 f:tester.py       l:371  c:LongevityTest        p:DEBUG >   File "cassandra/cluster.py", line 1778, in cassandra.cluster.Cluster.connect
< t:2022-11-23 17:17:56,584 f:tester.py       l:371  c:LongevityTest        p:DEBUG >   File "cassandra/cluster.py", line 1850, in cassandra.cluster.Cluster._new_session
< t:2022-11-23 17:17:56,584 f:tester.py       l:371  c:LongevityTest        p:DEBUG >   File "cassandra/cluster.py", line 2631, in cassandra.cluster.Session.__init__
< t:2022-11-23 17:17:56,584 f:tester.py       l:371  c:LongevityTest        p:DEBUG > cassandra.cluster.NoHostAvailable: ('Unable to connect to any servers', ['10.0.2.153', '10.0.1.247', '10.0.2.59'])
```

I think out servers are down...

**Comment by fruch** [comment]
and I take it back, they are not down:
```
< t:2022-11-23 17:17:54,973 f:interface.py    l:97   c:cassandra.cluster    p:DEBUG > Connecting to cluster, contact points: ['13.51.52.79', '13.53.252.230', '13.49.166.9']; protocol version: 4
< t:2022-11-23 17:17:54,973 f:interface.py    l:97   c:cassandra.pool       p:DEBUG > Host 13.51.52.79:9042 is now marked up
< t:2022-11-23 17:17:54,973 f:interface.py    l:97   c:cassandra.pool       p:DEBUG > Host 13.53.252.230:9042 is now marked up
< t:2022-11-23 17:17:54,973 f:interface.py    l:97   c:cassandra.pool       p:DEBUG > Host 13.49.166.9:9042 is now marked up
< t:2022-11-23 17:17:54,973 f:interface.py    l:97   c:cassandra.cluster    p:DEBUG > [control connection] Opening new connection to 13.51.52.79:9042
< t:2022-11-23 17:17:55,087 f:libevreactor.py l:87   c:cassandra.io.libevreactor p:DEBUG > Starting libev event loop
< t:2022-11-23 17:17:55,432 f:interface.py    l:97   c:cassandra.cluster    p:DEBUG > [control connection] Established new connection <LibevConnection(140128925615728) 13.51.52.79:9042>, registering watchers and refreshing schema and topology
< t:2022-11-23 17:17:55,885 f:interface.py    l:97   c:cassandra.cluster    p:DEBUG > [control connection] Refreshing node list and token map using preloaded results
< t:2022-11-23 17:17:55,886 f:interface.py    l:97   c:cassandra.cluster    p:DEBUG > [control connection] Found new host to connect to: 10.0.1.247:9042
< t:2022-11-23 17:17:55,886 f:interface.py    l:97   c:cassandra.cluster    p:INFO  > New Cassandra host <Host: 10.0.1.247:9042 eu-north> discovered
< t:2022-11-23 17:17:55,886 f:interface.py    l:97   c:cassandra.cluster    p:DEBUG > Handling new host <Host: 10.0.1.247:9042 eu-north> and notifying listeners
< t:2022-11-23 17:17:55,886 f:interface.py    l:97   c:cassandra.cluster    p:DEBUG > Not adding connection pool for new host <Host: 10.0.1.247:9042 eu-north> because the load balancing policy has marked it as IGNORED
< t:2022-11-23 17:17:55,886 f:interface.py    l:97   c:cassandra.cluster    p:DEBUG > [control connection] Found new host to connect to: 10.0.2.59:9042
< t:2022-11-23 17:17:55,886 f:interface.py    l:97   c:cassandra.cluster    p:INFO  > New Cassandra host <Host: 10.0.2.59:9042 eu-north> discovered
< t:2022-11-23 17:17:55,886 f:interface.py    l:97   c:cassandra.cluster    p:DEBUG > Handling new host <Host: 10.0.2.59:9042 eu-north> and notifying listeners
< t:2022-11-23 17:17:55,887 f:interface.py    l:97   c:cassandra.cluster    p:DEBUG > Not adding connection pool for new host <Host: 10.0.2.59:9042 eu-north> because the load balancing policy has marked it as IGNORED
< t:2022-11-23 17:17:55,887 f:interface.py    l:97   c:cassandra.cluster    p:DEBUG > [control connection] Removing host not found in peers metadata: <Host: 10.0.2.153:9042 eu-north>
< t:2022-11-23 17:17:55,887 f:interface.py    l:97   c:cassandra.cluster    p:DEBUG > [control connection] Removing host not found in peers metadata: <Host: 13.53.252.230:9042>
< t:2022-11-23 17:17:55,887 f:interface.py    l:97   c:cassandra.cluster    p:DEBUG > [control connection] Removing host not found in peers metadata: <Host: 13.49.166.9:9042>
< t:2022-11-23 17:17:55,887 f:interface.py    l:97   c:cassandra.cluster    p:DEBUG > [control connection] Finished fetching ring info
< t:2022-11-23 17:17:55,887 f:interface.py    l:97   c:cassandra.cluster    p:DEBUG > [control connection] Rebuilding token map due to topology changes
< t:2022-11-23 17:17:56,583 f:interface.py    l:97   c:cassandra.cluster    p:DEBUG > Control connection created
< t:2022-11-23 17:17:56,584 f:tester.py       l:370  c:LongevityTest        p:WARNING > Unable to set up Argus connection: Unable to connect to any servers
```

but we seem to be unable to connect to them...

**Comment by fruch** [comment]
Reverting the upgrade of the python-driver

https://github.com/scylladb/scylla-cluster-tests/pull/5476

Will need to address this in the driver code, before introducing.

**Comment by fruch** [comment]
Code reverted, and now it's fixed
