### ISSUE TITLE
Improve error handling in `RebuildStreamingErr` in case of missed data queries

### ISSUE THREAD

**Issue by KnifeyMoloko** [scylladb/scylla-cluster-tests#5508]
## Installation details

Kernel Version: 5.15.0-1023-aws
Scylla version (or git commit hash): `5.2.0~dev-20221124.d7310fd083f9` with build-id `63347c5a972f3c53037049189549b0896b5a148e`

Cluster size: 4 nodes (i3en.2xlarge)

Scylla Nodes used in this run:
- longevity-twcs-48h-master-db-node-72859ada-9 (3.94.152.33 | 10.12.9.131) (shards: 7)
- longevity-twcs-48h-master-db-node-72859ada-8 (54.167.49.135 | 10.12.9.37) (shards: 7)
- longevity-twcs-48h-master-db-node-72859ada-7 (54.89.173.202 | 10.12.11.250) (shards: 7)
- longevity-twcs-48h-master-db-node-72859ada-6 (107.21.71.235 | 10.12.8.177) (shards: 7)
- longevity-twcs-48h-master-db-node-72859ada-5 (3.80.26.215 | 10.12.9.236) (shards: 7)
- longevity-twcs-48h-master-db-node-72859ada-4 (3.88.23.151 | 10.12.11.205) (shards: 7)
- longevity-twcs-48h-master-db-node-72859ada-3 (3.95.181.10 | 10.12.11.244) (shards: 7)
- longevity-twcs-48h-master-db-node-72859ada-2 (54.234.38.132 | 10.12.11.16) (shards: 7)
- longevity-twcs-48h-master-db-node-72859ada-1 (52.201.56.222 | 10.12.11.140) (shards: 7)

OS / Image: `ami-059243fdd254e12e9` (aws: us-east-1)

Test: `longevity-twcs-48h-test`
Test id: `72859ada-1b0d-457f-88fe-20b8c617afdc`
Test name: `scylla-master/longevity/longevity-twcs-48h-test`
Test config file(s):

- [longevity-twcs-48h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/47adce42af3d0d6e9f2221496d1136180038511d/test-cases/longevity/longevity-twcs-48h.yaml)

## Issue description

**>>>>>>>**
When running `RebuildStreamingErr` we search for non-system cf with data to corrupt, before restarting the node and attempting to interrupt the rebuild process. However if the check for the cf data fails for whatever reason (here: to many tombstones to be processed by an unpaged query) we have no candidate tables for the data corruption and we fail a `random.choice` call in `destroy_data_and_restart_scylla()`.

sct.log:
```
< t:2022-11-25 11:59:07,765 f:common.py       l:1474 c:utils                p:DEBUG > Executing CQL 'SELECT * FROM scylla_bench.test LIMIT 1' ...
...
...
...
< t:2022-11-25 11:59:08,099 f:cluster.py      l:3015 c:sdcm.cluster         p:DEBUG > Retrying read after timeout. Attempt #1
< t:2022-11-25 11:59:08,147 f:cluster.py      l:3015 c:sdcm.cluster         p:DEBUG > Retrying read after timeout. Attempt #2
< t:2022-11-25 11:59:08,331 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-11-25T11:59:08+00:00 longevity-twcs-48h-master-db-node-72859ada-1  !WARNING | scylla[5354]:  [shard 2] storage_proxy - Exception when communicating with 10.12.11.244, to read from scylla_bench.test: Tombstones processed by unpaged query exceeds limit of 10000 (configured via query_tombstone_page_limit)
< t:2022-11-25 11:59:08,331 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-11-25T11:59:08+00:00 longevity-twcs-48h-master-db-node-72859ada-1  !WARNING | scylla[5354]:  [shard 2] storage_proxy - Exception when communicating with 10.12.11.244, to read from scylla_bench.test: Tombstones processed by unpaged query exceeds limit of 10000 (configured via query_tombstone_page_limit)
< t:2022-11-25 11:59:08,332 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-11-25T11:59:08+00:00 longevity-twcs-48h-master-db-node-72859ada-1  !WARNING | scylla[5354]:  [shard 0] storage_proxy - Exception when communicating with 10.12.11.244, to read from scylla_bench.test: Tombstones processed by unpaged query exceeds limit of 10000 (configured via query_tombstone_page_limit)
< t:2022-11-25 11:59:08,839 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:DEBUG > 2022-11-25T11:59:08+00:00 longevity-twcs-48h-master-db-node-72859ada-1  !WARNING | scylla[5354]:  [shard 4] storage_proxy - Exception when communicating with 10.12.11.244, to read from scylla_bench.test: Tombstones processed by unpaged query exceeds limit of 10000 (configured via query_tombstone_page_limit)
< t:2022-11-25 11:59:09,035 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 7h22m59.7s   92883       0      0 58ms   32ms   6.2ms  2.8ms  2.3ms  1.3ms  1.6ms
< t:2022-11-25 11:59:09,132 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-11-25T11:59:09+00:00 longevity-twcs-48h-master-db-node-72859ada-5   !NOTICE | sudo[9319]: scyllaadm : PWD=/home/scyllaadm ; USER=root ; COMMAND=/usr/bin/systemctl stop scylla-server.service
```

We should raise a more informative exception at that point and avoid restarting the target node.

**<<<<<<<**

- Restore Monitor Stack command: `$ hydra investigate show-monitor 72859ada-1b0d-457f-88fe-20b8c617afdc`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=72859ada-1b0d-457f-88fe-20b8c617afdc)
- Show all stored logs command: `$ hydra investigate show-logs 72859ada-1b0d-457f-88fe-20b8c617afdc`

## Logs:
- **db-cluster-72859ada.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/72859ada-1b0d-457f-88fe-20b8c617afdc/20221125_211822/db-cluster-72859ada.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/72859ada-1b0d-457f-88fe-20b8c617afdc/20221125_211822/db-cluster-72859ada.tar.gz)
- **monitor-set-72859ada.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/72859ada-1b0d-457f-88fe-20b8c617afdc/20221125_211822/monitor-set-72859ada.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/72859ada-1b0d-457f-88fe-20b8c617afdc/20221125_211822/monitor-set-72859ada.tar.gz)
- **loader-set-72859ada.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/72859ada-1b0d-457f-88fe-20b8c617afdc/20221125_211822/loader-set-72859ada.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/72859ada-1b0d-457f-88fe-20b8c617afdc/20221125_211822/loader-set-72859ada.tar.gz)
- **sct-runner-72859ada.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/72859ada-1b0d-457f-88fe-20b8c617afdc/20221125_211822/sct-runner-72859ada.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/72859ada-1b0d-457f-88fe-20b8c617afdc/20221125_211822/sct-runner-72859ada.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-twcs-48h-test/66/)

**Comment by yarongilor** [comment]
This PR will help avoiding nemesis failure:
https://github.com/scylladb/scylla-cluster-tests/pull/5540

**Comment by fruch** [comment]
what's "too many tombstones to be processed by an unpaged query" ? 

we shouldn't be hiding this and skipping the nemesis.

**Comment by fruch** [comment]
@yarongilor I've opened the log from your run, and there a much more severe issue here:
```
< t:2022-12-02 06:27:23,278 f:nemesis.py      l:2729 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.SisyphusMonkey: Take few tables snapshot
< t:2022-12-02 06:27:26,306 f:cluster.py      l:3470 c:sdcm.cluster         p:WARNING > Cluster longevity-twcs-48h-master-db-cluster-41fa60db (AMI: ['ami-058aaa3c56c451303'] Type: i3en.2xlarge): Failed to get rows from system.IndexInfo table. Error: Error from server: code=2200 [Invalid query] message="unconfigured table indexinfo"
< t:2022-12-02 06:27:26,307 f:cluster.py      l:3470 c:sdcm.cluster         p:WARNING > Cluster longevity-twcs-48h-master-db-cluster-41fa60db (AMI: ['ami-058aaa3c56c451303'] Type: i3en.2xlarge): Failed to get rows from system.IndexInfo table. Error: Error from server: code=2200 [Invalid query] message="unconfigured table indexinfo"
< t:2022-12-02 06:27:26,308 f:cluster.py      l:3470 c:sdcm.cluster         p:WARNING > Cluster longevity-twcs-48h-master-db-cluster-41fa60db (AMI: ['ami-058aaa3c56c451303'] Type: i3en.2xlarge): Failed to get rows from system.IndexInfo table. Error: Error from server: code=2200 [Invalid query] message="unconfigured table indexinfo"
< t:2022-12-02 06:27:27,752 f:libevreactor.py l:370  c:cassandra.connection p:ERROR > Error decoding response from Cassandra. ver(3); flags(0000); stream(16); op(8); offset(9); len(236); buffer: b'\x83\x00\x00\x10\x08\x00\x00\x00\xec\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x05\x00\x06system\x00\ttruncated\x00\ntable_uuid\x00\x0c\x00\x06system\x00\ttruncated\x00\x05shard\x00\t\x00\x06system\x00\ttruncated\x00\x0ctruncated_at\x00\x0b\x00\x06system\x00\ttruncated\x00\x08position\x00\t\x00\x06system\x00\ttruncated\x00\nsegment_id\x00\x02\x00\x00\x00\x01\x00\x00\x00\x10\x03Y\xbcqq#>\xe1\x9aJ\xb9\xdf\xb1\x1f\xc1%\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x08\x7f\xff\xff\xff\xff\xff\xff\xff\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x08\x00\x00\x00\x00\x00\x00\x00\x00' < t:2022-12-02 06:27:27,752 f:libevreactor.py l:370  c:cassandra.connection p:ERROR > Error decoding response from Cassandra. ver(3); flags(0000); stream(16); op(8); offset(9); len(236); buffer: b'\x83\x00\x00\x10\x08\x00\x00\x00\xec\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x05\x00\x06system\x00\ttruncated\x00\ntable_uuid\x00\x0c\x00\x06system\x00\ttruncated\x00\x05shard\x00\t\x00\x06system\x00\ttruncated\x00\x0ctruncated_at\x00\x0b\x00\x06system\x00\ttruncated\x00\x08position\x00\t\x00\x06system\x00\ttruncated\x00\nsegment_id\x00\x02\x00\x00\x00\x01\x00\x00\x00\x10\x03Y\xbcqq#>\xe1\x9aJ\xb9\xdf\xb1\x1f\xc1%\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x08\x7f\xff\xff\xff\xff\xff\xff\xff\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x08\x00\x00\x00\x00\x00\x00\x00\x00'
< t:2022-12-02 06:27:27,752 f:libevreactor.py l:370  c:cassandra.connection p:ERROR > Traceback (most recent call last):
< t:2022-12-02 06:27:27,752 f:libevreactor.py l:370  c:cassandra.connection p:ERROR >   File "cassandra/obj_parser.pyx", line 72, in cassandra.obj_parser.TupleRowParser.unpack_row
< t:2022-12-02 06:27:27,752 f:libevreactor.py l:370  c:cassandra.connection p:ERROR >   File "cassandra/deserializers.pxd", line 41, in cassandra.deserializers.from_binary
< t:2022-12-02 06:27:27,752 f:libevreactor.py l:370  c:cassandra.connection p:ERROR >   File "cassandra/deserializers.pyx", line 143, in cassandra.deserializers.DesDateType.deserialize
< t:2022-12-02 06:27:27,752 f:libevreactor.py l:370  c:cassandra.connection p:ERROR >   File "cassandra/cython_utils.pyx", line 62, in cassandra.cython_utils.datetime_from_timestamp
< t:2022-12-02 06:27:27,752 f:libevreactor.py l:370  c:cassandra.connection p:ERROR >   File ".eggs/Cython-0.29.32-py3.10-linux-x86_64.egg/Cython/Includes/cpython/datetime.pxd", line 125, in cpython.datetime.timedelta_new
< t:2022-12-02 06:27:27,752 f:libevreactor.py l:370  c:cassandra.connection p:ERROR > OverflowError: days=2147458792; must have magnitude <= 999999999
< t:2022-12-02 06:27:27,752 f:libevreactor.py l:370  c:cassandra.connection p:ERROR > 
< t:2022-12-02 06:27:27,752 f:libevreactor.py l:370  c:cassandra.connection p:ERROR > During handling of the above exception, another exception occurred:
< t:2022-12-02 06:27:27,752 f:libevreactor.py l:370  c:cassandra.connection p:ERROR > 
< t:2022-12-02 06:27:27,752 f:libevreactor.py l:370  c:cassandra.connection p:ERROR > Traceback (most recent call last):
< t:2022-12-02 06:27:27,752 f:libevreactor.py l:370  c:cassandra.connection p:ERROR >   File "cassandra/row_parser.pyx", line 38, in cassandra.row_parser.make_recv_results_rows.recv_results_rows
< t:2022-12-02 06:27:27,752 f:libevreactor.py l:370  c:cassandra.connection p:ERROR >   File "cassandra/obj_parser.pyx", line 31, in cassandra.obj_parser.ListParser.parse_rows
< t:2022-12-02 06:27:27,752 f:libevreactor.py l:370  c:cassandra.connection p:ERROR >   File "cassandra/obj_parser.pyx", line 74, in cassandra.obj_parser.TupleRowParser.unpack_row
< t:2022-12-02 06:27:27,752 f:libevreactor.py l:370  c:cassandra.connection p:ERROR > cassandra.DriverException: Failed decoding result column "truncated_at" of type timestamp: days=2147458792; must have magnitude <= 999999999
< t:2022-12-02 06:27:27,752 f:libevreactor.py l:370  c:cassandra.connection p:ERROR > 
< t:2022-12-02 06:27:27,752 f:libevreactor.py l:370  c:cassandra.connection p:ERROR > During handling of the above exception, another exception occurred:
< t:2022-12-02 06:27:27,752 f:libevreactor.py l:370  c:cassandra.connection p:ERROR > 
< t:2022-12-02 06:27:27,752 f:libevreactor.py l:370  c:cassandra.connection p:ERROR > Traceback (most recent call last):
< t:2022-12-02 06:27:27,752 f:libevreactor.py l:370  c:cassandra.connection p:ERROR >   File "cassandra/obj_parser.pyx", line 72, in cassandra.obj_parser.TupleRowParser.unpack_row
< t:2022-12-02 06:27:27,752 f:libevreactor.py l:370  c:cassandra.connection p:ERROR >   File "cassandra/deserializers.pxd", line 41, in cassandra.deserializers.from_binary
< t:2022-12-02 06:27:27,752 f:libevreactor.py l:370  c:cassandra.connection p:ERROR >   File "cassandra/deserializers.pyx", line 143, in cassandra.deserializers.DesDateType.deserialize
< t:2022-12-02 06:27:27,752 f:libevreactor.py l:370  c:cassandra.connection p:ERROR >   File "cassandra/cython_utils.pyx", line 62, in cassandra.cython_utils.datetime_from_timestamp
< t:2022-12-02 06:27:27,752 f:libevreactor.py l:370  c:cassandra.connection p:ERROR >   File ".eggs/Cython-0.29.32-py3.10-linux-x86_64.egg/Cython/Includes/cpython/datetime.pxd", line 125, in cpython.datetime.timedelta_new
< t:2022-12-02 06:27:27,752 f:libevreactor.py l:370  c:cassandra.connection p:ERROR > OverflowError: days=2147458792; must have magnitude <= 999999999
< t:2022-12-02 06:27:27,752 f:libevreactor.py l:370  c:cassandra.connection p:ERROR > 
< t:2022-12-02 06:27:27,752 f:libevreactor.py l:370  c:cassandra.connection p:ERROR > During handling of the above exception, another exception occurred:
< t:2022-12-02 06:27:27,752 f:libevreactor.py l:370  c:cassandra.connection p:ERROR > 
< t:2022-12-02 06:27:27,752 f:libevreactor.py l:370  c:cassandra.connection p:ERROR > Traceback (most recent call last):
< t:2022-12-02 06:27:27,752 f:libevreactor.py l:370  c:cassandra.connection p:ERROR >   File "cassandra/connection.py", line 1266, in cassandra.connection.Connection.process_msg
< t:2022-12-02 06:27:27,752 f:libevreactor.py l:370  c:cassandra.connection p:ERROR >   File "cassandra/protocol.py", line 1196, in cassandra.protocol._ProtocolHandler.decode_message
< t:2022-12-02 06:27:27,752 f:libevreactor.py l:370  c:cassandra.connection p:ERROR >   File "cassandra/protocol.py", line 744, in cassandra.protocol.ResultMessage.recv_body
< t:2022-12-02 06:27:27,752 f:libevreactor.py l:370  c:cassandra.connection p:ERROR >   File "cassandra/protocol.py", line 730, in cassandra.protocol.ResultMessage.recv
< t:2022-12-02 06:27:27,752 f:libevreactor.py l:370  c:cassandra.connection p:ERROR >   File "cassandra/row_parser.pyx", line 46, in cassandra.row_parser.make_recv_results_rows.recv_results_rows
< t:2022-12-02 06:27:27,752 f:libevreactor.py l:370  c:cassandra.connection p:ERROR >   File "cassandra/obj_parser.pyx", line 57, in cassandra.obj_parser.TupleRowParser.unpack_row
< t:2022-12-02 06:27:27,752 f:libevreactor.py l:370  c:cassandra.connection p:ERROR >   File "cassandra/obj_parser.pyx", line 74, in cassandra.obj_parser.TupleRowParser.unpack_row
< t:2022-12-02 06:27:27,752 f:libevreactor.py l:370  c:cassandra.connection p:ERROR > cassandra.DriverException: Failed decoding result column "truncated_at" of type timestamp: days=2147458792; must have magnitude <= 999999999
< t:2022-12-02 06:27:27,753 f:cluster.py      l:3470 c:sdcm.cluster         p:WARNING > Cluster longevity-twcs-48h-master-db-cluster-41fa60db (AMI: ['ami-058aaa3c56c451303'] Type: i3en.2xlarge): Failed to get rows from system.truncated table. Error: Failed decoding result column "truncated_at" of type timestamp: days=2147458792; must have magnitude <= 999999999
```

this look like a CQL protocol error, seems like scylla is send wrong date for `truncated_at`, please open a scylla core  issue for this.

**Comment by yarongilor** [comment]
@fruch , i think in this case, what's hiding data is SCT code that just catches a broad exception:
```
        try:
            current_rows = session.execute(f"SELECT * FROM {table_name} LIMIT 1").current_rows
        except Exception as exc:  # pylint: disable=broad-except
            self.log.warning(f'Failed to get rows from {table_name} table. Error: {exc}')
```

**Comment by fruch** [comment]
> @fruch , i think in this case, what's hiding data is SCT code that just catches a broad exception:
> 
> ```
>         try:
>             current_rows = session.execute(f"SELECT * FROM {table_name} LIMIT 1").current_rows
>         except Exception as exc:  # pylint: disable=broad-except
>             self.log.warning(f'Failed to get rows from {table_name} table. Error: {exc}')
> ```

so fix it

**Comment by yarongilor** [comment]
opened https://github.com/scylladb/scylladb/issues/12239

**Comment by fruch** [comment]
We are doing the default

https://python-driver.docs.scylladb.com/stable/query_paging.html

I'm not aware that you need Todo anything else for paging it should be automatic

**Comment by yarongilor** [comment]
fixed by https://github.com/scylladb/scylla-cluster-tests/pull/5540
