### ISSUE TITLE
Azure service timeout failed `hydra clean-resources' call

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#5543]
Azure failed `hydra clean-resources' call
https://jenkins.scylladb.com/job/scylla-staging/job/fruch/job/longevity-scylla-operator-3h-multitenant-eks/34/execution/node/192/log/

```
19:22:45  Going to list Azure instances
19:25:23  Traceback (most recent call last):
19:25:23    File "/home/ubuntu/scylla-cluster-tests/./sct.py", line 1563, in <module>
19:25:23      cli()
19:25:23    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1137, in __call__
19:25:23      return self.main(*args, **kwargs)
19:25:23    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1062, in main
19:25:23      rv = self.invoke(ctx)
19:25:23    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1668, in invoke
19:25:23      return _process_result(sub_ctx.command.invoke(sub_ctx))
19:25:23    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
19:25:23      return ctx.invoke(self.callback, **ctx.params)
19:25:23    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 763, in invoke
19:25:23      return __callback(*args, **kwargs)
19:25:23    File "/home/ubuntu/scylla-cluster-tests/./sct.py", line 1129, in collect_logs
19:25:23      update_sct_runner_tags(test_id=collector.test_id, tags={"logs_collected": True})
19:25:23    File "/home/ubuntu/scylla-cluster-tests/sdcm/sct_runner.py", line 1066, in update_sct_runner_tags
19:25:23      listed_runners = list_sct_runners()
19:25:23    File "/home/ubuntu/scylla-cluster-tests/sdcm/sct_runner.py", line 1048, in list_sct_runners
19:25:23      sct_runners = list(sct_runners)
19:25:23    File "/home/ubuntu/scylla-cluster-tests/sdcm/sct_runner.py", line 1039, in <genexpr>
19:25:23      sct_runners = chain.from_iterable(cls.list_sct_runners() for cls in sct_runner_classes)
19:25:23    File "/home/ubuntu/scylla-cluster-tests/sdcm/sct_runner.py", line 981, in list_sct_runners
19:25:23      for instance in list_instances_azure(tags_dict={"NodeType": cls.NODE_TYPE}, verbose=True):
19:25:23    File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/azure_utils.py", line 212, in list_instances_azure
19:25:23      instances = [get_virtual_machine(resource_group_name=vm["resourceGroup"], vm_name=vm["name"]) for vm in res]
19:25:23    File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/azure_utils.py", line 212, in <listcomp>
19:25:23      instances = [get_virtual_machine(resource_group_name=vm["resourceGroup"], vm_name=vm["name"]) for vm in res]
19:25:23    File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/azure_utils.py", line 180, in paged_query
19:25:23      response = self.resource_graph.resources(request)
19:25:23    File "/usr/local/lib/python3.10/site-packages/azure/mgmt/resourcegraph/operations/_resource_graph_client_operations.py", line 67, in resources
19:25:23      pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)
19:25:23    File "/usr/local/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 211, in run
19:25:23      return first_node.send(pipeline_request)  # type: ignore
19:25:23    File "/usr/local/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 71, in send
19:25:23      response = self.next.send(request)
19:25:23    File "/usr/local/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 71, in send
19:25:23      response = self.next.send(request)
19:25:23    File "/usr/local/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 71, in send
19:25:23      response = self.next.send(request)
19:25:23    [Previous line repeated 2 more times]
19:25:23    File "/usr/local/lib/python3.10/site-packages/azure/mgmt/core/policies/_base.py", line 47, in send
19:25:23      response = self.next.send(request)
19:25:23    File "/usr/local/lib/python3.10/site-packages/azure/core/pipeline/policies/_redirect.py", line 153, in send
19:25:23      response = self.next.send(request)
19:25:23    File "/usr/local/lib/python3.10/site-packages/azure/core/pipeline/policies/_retry.py", line 467, in send
19:25:23      raise err
19:25:23    File "/usr/local/lib/python3.10/site-packages/azure/core/pipeline/policies/_retry.py", line 445, in send
19:25:23      response = self.next.send(request)
19:25:23    File "/usr/local/lib/python3.10/site-packages/azure/core/pipeline/policies/_authentication.py", line 113, in send
19:25:23      response = self.next.send(request)
19:25:23    File "/usr/local/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 71, in send
19:25:23      response = self.next.send(request)
19:25:23    File "/usr/local/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 71, in send
19:25:23      response = self.next.send(request)
19:25:23    File "/usr/local/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 71, in send
19:25:23      response = self.next.send(request)
19:25:23    [Previous line repeated 1 more time]
19:25:23    File "/usr/local/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 103, in send
19:25:23      self._sender.send(request.http_request, **request.context.options),
19:25:23    File "/usr/local/lib/python3.10/site-packages/azure/core/pipeline/transport/_requests_basic.py", line 360, in send
19:25:23      raise error
19:25:23  azure.core.exceptions.ServiceResponseError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

we probably need some retry, or check if they have automatic retries (same as boto3 has, not that we using)

**Comment by soyacz** [comment]
fixed by https://github.com/scylladb/scylla-cluster-tests/pull/5635
