### ISSUE TITLE
GKE evicts valueable pods from Scylla K8S node when enospc nemesis is applied

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-cluster-tests#5671]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master
* **scylla**: any

### Logs
* test_id: d457af3c-14d9-454a-a7ca-02f379e03c70
* job log: https://jenkins.scylladb.com/job/scylla-operator/job/operator-1.8/job/gke/job/longevity-scylla-operator-basic-12h-gke/6/consoleFull

### Description

When we run longevity job on the GKE (K8S) backend and trigger the `disrupt_nodetool_enospc` nemesis then 
we get the following situation change:

1) All our pods get killed on that affected Scylla K8S node:
```
NAMESPACE         NAME                                                             READY   STATUS      RESTARTS      AGE     IP            NODE                                                  NOMINATED NODE   READINESS GATES
...
default           static-local-volume-provisioner-ds-kt4b4                         0/1     Evicted     0             4m57s   <none>        gke-longev-scylla-operat--scylla-pool-ba70b468-89xk   <none>           <none>
...
default           xfs-formatter-g66b5                                              0/2     Evicted     0             4m58s   <none>        gke-longev-scylla-operat--scylla-pool-ba70b468-89xk   <none>           <none>
...
scylla            sct-cluster-us-east1-b-us-east1-2                                0/2     Pending     0             6h7m    <none>        <none>                                                <none>           <none>
```

2) The affected scylla pod becomes unschedulable with the following status:
```
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-01-10T22:45:52Z"
    message: '0/8 nodes are available: 1 node(s) had untolerated taint {node.kubernetes.io/disk-pressure:
      }, 1 node(s) had volume node affinity conflict, 2 Insufficient cpu, 2 Insufficient
      memory, 4 node(s) didn''t match Pod''s node affinity/selector. preemption: 0/8
      nodes are available: 2 No preemption victims found for incoming pod, 6 Preemption
      is not helpful for scheduling.'
    reason: Unschedulable
    status: "False"
    type: PodScheduled
  phase: Pending
  qosClass: Guaranteed
```

And, the `enospc` effect fails to be reverted and makes the whole test run be broken till it's end:

```
p:ERROR > Wait for: Wait for new ENOSPC error occurs in database: timeout - 300 seconds - expired   
p:ERROR > last error: RetryableNetworkException('(0)\nReason: Handshake status 400 Bad Request\n')  
 p:ERROR > '_run': Number of retries exceeded!                                                         
p:ERROR > sdcm.nemesis.SisyphusMonkey: Unhandled exception in method <bound method Nemesis.disrupt_nodetool_enospc of <sdcm.nemesis.SisyphusMonkey object at 0x7febd8666aa0>> < t:2023-01-10 22:52:11,731 f:nemesis.py      l:3884 c:sdcm.nemesis         p:ERROR > sdcm.nemesis.SisyphusMonkey: Unhandled exception in method <bound method Nemesis.disrupt_nodetool_enospc of <sdcm.nemesis.SisyphusMonkey object at 0x7febd8666aa0>>
p:ERROR > Traceback (most recent call last):                                                           
p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run  
p:ERROR >     return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers) 
p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/kubernetes_cmd_runner.py", line 203, in _run_execute
p:ERROR >     return super()._run_execute(cmd, timeout=timeout, ignore_status=ignore_status, verbose=verbose,
p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 530, in _run_execute
p:ERROR >     result = connection.run(**command_kwargs)                                                
p:ERROR >   File "/usr/local/lib/python3.10/site-packages/invoke/runners.py", line 380, in run         
p:ERROR >     return self._run_body(command, **kwargs)                                                 
p:ERROR >   File "/usr/local/lib/python3.10/site-packages/invoke/runners.py", line 431, in _run_body
p:ERROR >     self.start(command, self.opts["shell"], self.env)                                        
p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/kubernetes_cmd_runner.py", line 97, in start
p:ERROR >     raise ConnectionError(str(exc)) from None                                                
p:ERROR > ConnectionError: (0)                                                                         
p:ERROR > Reason: Handshake status 400 Bad Request                                                     
p:ERROR >                                                                                              
p:ERROR >                                                                                              
p:ERROR > During handling of the above exception, another exception occurred:                          
p:ERROR >                                                                                              
p:ERROR > Traceback (most recent call last):                                                           
p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3873, in wrapper            
p:ERROR >     result = method(*args[1:], **kwargs)                                                     
p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1577, in disrupt_nodetool_enospc
p:ERROR >     clean_enospc_on_node(target_node=node, sleep_time=sleep_time)                            
p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 2504, in clean_enospc_on_node
p:ERROR >     target_node.remoter.sudo('rm -rf /var/lib/scylla/occupy_90percent.*')                    
p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/base.py", line 123, in sudo            
p:ERROR >     return self.run(cmd=cmd,                                                                 
p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/kubernetes_cmd_runner.py", line 164, in run 
p:ERROR >     return super().run(cmd, **kwargs)                                                        
p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run   
p:ERROR >     result = _run()                                                                          
p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 67, in inner       
p:ERROR >     return func(*args, **kwargs)                                                             
p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 606, in _run  
p:ERROR >     if self._run_on_retryable_exception(exc, new_session):                                   
p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/kubernetes_cmd_runner.py", line 223, in _run_on_retryable_exception
p:ERROR >     raise RetryableNetworkException(str(exc), original=exc)                                  
p:ERROR > sdcm.remote.base.RetryableNetworkException: (0)                                              
p:ERROR > Reason: Handshake status 400 Bad Request                                                     
p:INFO  > POST https://746f0ad652a3447d83b1572f657c67cb.us-east-1.aws.found.io:9243/nemesis_data/nemesis [status:201 request:0.279s]
```

### Steps to Reproduce

1. Run Longevity job on GKE backend with the `disrupt_nodetool_enospc` nemesis enabled.
2. See error

**Expected behavior:** None of the pods must be killed

**Actual behavior:** Whole set of Scylla-related pods are killed that are hosted on the affected, by nemesis, Scylla K8S node.

**Comment by fruch** [comment]
@vponomaryov it's an operator issue from my POV, and we should retest this once they implement what they are working for M4

anyhow we should look into why GKE is behaving such way, it might be still problematic even with how they would setup the disks.

**Comment by vponomaryov** [comment]
> @vponomaryov it's an operator issue from my POV, and we should retest this once they implement what they are working for M4
> 
> anyhow we should look into why GKE is behaving such way, it might be still problematic even with how they would setup the disks.

It is not operator issue from my POV. GKE is configured to behave like this by default.
Personally, I didn't check the disk configuration on GKE, it may worth looking at it to understand why `enospc` is so critical to it.
Probably scylla's disk is used somewhere else in the node system...
