### ISSUE TITLE
nodetool flush fails on default timeout of 60 seconds when running ebs gp3 

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#5694]
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

```
2023-01-12 23:54:29.684: (NodetoolEvent Severity.ERROR) period_type=end event_id=22059296-de38-431f-9047-9557126b6f13 duration=1h32m0s: nodetool_command=flush node=longevity-100gb-4h-2022-2-db-node-3c0c1125-1 errors=["Command did not complete within 60 seconds!\n\nCommand: '/usr/bin/nodetool  flush '\n\nStdout:\n\n\n\nStderr:\n\n\n\n", 'Traceback (most recent call last):\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run\n    return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute\n    result = connection.run(**command_kwargs)\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run\n    return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 651, in _complete_run\n    raise CommandTimedOut(result, timeout)\nsdcm.remote.libssh2_client.exceptions.CommandTimedOut: Command did not complete within 60 seconds!\n\nCommand: \'/usr/bin/nodetool  flush \'\n\nStdout:\n\n\n\nStderr:\n\n\n\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2537, in run_nodetool\n    self.remoter.run(cmd, timeout=timeout, ignore_status=ignore_status, verbose=verbose, retry=retry)\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run\n    result = _run()\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 67, in inner\n    return func(*args, **kwargs)\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 606, in _run\n    if self._run_on_retryable_exception(exc, new_session):\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_libssh_cmd_runner.py", line 78, in _run_on_retryable_exception\n    raise RetryableNetworkException(str(exc), original=exc)\nsdcm.remote.base.RetryableNetworkException: Command did not complete within 60 seconds!\n\nCommand: \'/usr/bin/nodetool  flush \'\n\nStdout:\n\n\n\nStderr:\n\n\n\n\n']
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run
return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
result = connection.run(**command_kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 651, in _complete_run
raise CommandTimedOut(result, timeout)
sdcm.remote.libssh2_client.exceptions.CommandTimedOut: Command did not complete within 60 seconds!
Command: '/usr/bin/nodetool  flush '
Stdout:
Stderr:
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2537, in run_nodetool
self.remoter.run(cmd, timeout=timeout, ignore_status=ignore_status, verbose=verbose, retry=retry)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run
result = _run()
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 67, in inner
return func(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 606, in _run
if self._run_on_retryable_exception(exc, new_session):
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_libssh_cmd_runner.py", line 78, in _run_on_retryable_exception
raise RetryableNetworkException(str(exc), original=exc)
sdcm.remote.base.RetryableNetworkException: Command did not complete within 60 seconds!
Command: '/usr/bin/nodetool  flush '
Stdout:
Stderr:
```
(original job: [https://argus.scylladb.com/test/46061924-4d7e-47da-a546-cb7a50249a49/runs?additionalRuns[]=263f002d-1731-41b4-b73e-207d7670a34c](https://argus.scylladb.com/test/46061924-4d7e-47da-a546-cb7a50249a49/runs?additionalRuns%5B%5D=263f002d-1731-41b4-b73e-207d7670a34c) )

It appears that nodetool flush takes 143 seconds, much more than currently SCT configured timeout of 60 seconds:
```
yarongilor@yarongilor:~/Downloads/logs/sct-runner-16688cf7$ grep '/usr/bin/nodetool  flush ' sct.log 
&lt; t:2022-11-15 19:27:49,721 f:remote_base.py  l:520  c:RemoteLibSSH2CmdRunner p:DEBUG &gt; Running command "/usr/bin/nodetool  flush "...
&lt; t:2022-11-15 19:30:12,789 f:base.py         l:142  c:RemoteLibSSH2CmdRunner p:DEBUG &gt; Command "/usr/bin/nodetool  flush " finished with status 0
&lt; t:2022-11-15 19:30:12,789 f:cluster.py      l:2550 c:sdcm.cluster_aws     p:DEBUG &gt; Node longevity-100gb-4h-fix-gene-db-node-16688cf7-1 [34.247.159.5 | 10.4.1.6] (seed: True): Command '/usr/bin/nodetool  flush ' duration -&gt; 143.06740939199972 s
```
We can consider applying the simple tested solution above: `def run_nodetool(self, sub_cmd, args="", options="", timeout=300`
Or think of a more advanced way which would be dependant on `data_volume_disk_type` parameter like:
```
def run_nodetool(self, sub_cmd, args="", options="", timeout=None ...):

    volume_type = self.params.get("data_volume_disk_type")
    if not timeout and  volume_type == 'gp3':
        timeout = 300
```

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Kernel Version: 5.15.0-1028-aws
Scylla version (or git commit hash): `2022.2.0-20230112.4f0f82ff2e1d` with build-id `a1d0fdd6fed1f802854040dbefcf5c45bbc4e820`
Relocatable Package: http://downloads.scylladb.com/unstable/scylla-enterprise/enterprise-2022.2/relocatable/2023-01-12T16:08:35Z/scylla-enterprise-x86_64-package.tar.gz

Cluster size: 6 nodes (r5b.2xlarge)

Scylla Nodes used in this run:
- longevity-100gb-4h-2022-2-db-node-3c0c1125-6 (34.244.26.235 | 10.4.3.216) (shards: 7)
- longevity-100gb-4h-2022-2-db-node-3c0c1125-5 (176.34.150.88 | 10.4.3.203) (shards: 7)
- longevity-100gb-4h-2022-2-db-node-3c0c1125-4 (54.216.126.25 | 10.4.2.129) (shards: 7)
- longevity-100gb-4h-2022-2-db-node-3c0c1125-3 (3.253.4.40 | 10.4.1.34) (shards: 7)
- longevity-100gb-4h-2022-2-db-node-3c0c1125-2 (34.247.88.4 | 10.4.0.83) (shards: 7)
- longevity-100gb-4h-2022-2-db-node-3c0c1125-1 (34.245.0.74 | 10.4.0.124) (shards: 7)

OS / Image: `ami-0adef4664b7d52a67` (aws: eu-west-1)

Test: `longevity-100gb-4h-ebs-gp3-test`
Test id: `3c0c1125-48ea-467c-a22b-750a613243df`
Test name: `enterprise-2022.2/longevity/longevity-100gb-4h-ebs-gp3-test`
Test config file(s):

- [longevity-100gb-4h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/1fede40e24b751c5ce1e84883885fe7be765afa5/test-cases/longevity/longevity-100gb-4h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 3c0c1125-48ea-467c-a22b-750a613243df`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=3c0c1125-48ea-467c-a22b-750a613243df)
- Show all stored logs command: `$ hydra investigate show-logs 3c0c1125-48ea-467c-a22b-750a613243df`

## Logs:
- **db-cluster-3c0c1125.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/3c0c1125-48ea-467c-a22b-750a613243df/20230113_030243/db-cluster-3c0c1125.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/3c0c1125-48ea-467c-a22b-750a613243df/20230113_030243/db-cluster-3c0c1125.tar.gz)
- **monitor-set-3c0c1125.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/3c0c1125-48ea-467c-a22b-750a613243df/20230113_030243/monitor-set-3c0c1125.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/3c0c1125-48ea-467c-a22b-750a613243df/20230113_030243/monitor-set-3c0c1125.tar.gz)
- **loader-set-3c0c1125.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/3c0c1125-48ea-467c-a22b-750a613243df/20230113_030243/loader-set-3c0c1125.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/3c0c1125-48ea-467c-a22b-750a613243df/20230113_030243/loader-set-3c0c1125.tar.gz)
- **sct-runner-3c0c1125.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/3c0c1125-48ea-467c-a22b-750a613243df/20230113_030243/sct-runner-3c0c1125.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/3c0c1125-48ea-467c-a22b-750a613243df/20230113_030243/sct-runner-3c0c1125.tar.gz)
- **parallel-timelines-report-3c0c1125.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/3c0c1125-48ea-467c-a22b-750a613243df/20230113_030243/parallel-timelines-report-3c0c1125.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/3c0c1125-48ea-467c-a22b-750a613243df/20230113_030243/parallel-timelines-report-3c0c1125.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2022.2/job/longevity/job/longevity-100gb-4h-ebs-gp3-test/8/)
</details>

**Comment by yarongilor** [comment]
@roydahan , please advise

**Comment by fgelcer** [comment]
> @roydahan , please advise

@yarongilor , what do you suggest? how long should be the flush, on EBS GP3?

**Comment by roydahan** [comment]
Do we know that with larger timeout it works?

**Comment by yarongilor** [comment]
> Do we know that with larger timeout it works?

yes. passed in: https://argus.scylladb.com/workspace?state=WyIxYzRmMGE3MC1mZDA1LTQwZjItYjY2Mi01MDIzYmUzNDg4NWMiXQ
