### ISSUE TITLE
scylla io setup causes heavy load for machine (network isn't available)

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla-cluster-tests#576]
self.wait_ssh_up(verbose=False), it uses default timeout 300 seconds.

```
2018-06-07 05:55:18,970 remote           L0194 DEBUG| [35.196.27.64] [stdout] Processing triggers for libc-bin (2.23-0ubuntu10) ...
2018-06-07 05:55:19,913 remote           L0194 DEBUG| [35.196.27.64] [stdout] kernel.core_pattern = |/lib/systemd/systemd-coredump %P %u %g %s %t 9223372036854775808 %e
2018-06-07 05:55:19,916 remote           L0194 DEBUG| [35.196.27.64] [stdout] Setting parameters on /etc/default/scylla-server
2018-06-07 05:55:33,364 remote           L0194 DEBUG| [35.196.27.64] [stdout] Generating evaluation file sized 10GB...10GB written in 13 seconds
2018-06-07 05:56:28,459 remote           L0194 DEBUG| [35.196.27.64] [stdout] Refining search for maximum. So far, 373812 IOPS
2018-06-07 05:56:31,195 remote           L0194 DEBUG| [35.196.27.64] [stdout] Maximum throughput: 373838 IOPS
2018-06-07 05:59:44,841 remote           L0707 ERROR| Remote [scylla-test@35.196.27.64]: Error while executing SSH command: Command: /bin/ssh -tt -a -x  -o ControlPath=/var/tmp/ssh-masterylP3NZ/socket -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpZi1v8t -o BatchMode=yes -o ConnectTimeout=30 -o ServerAliveInterval=300 -l scylla-test -p 22 -i /home/amos/.ssh/scylla-test 35.196.27.64 "true"
Exit status: -15
Duration: 30.0033638477
Stdout:

Stderr:


2018-06-07 06:00:24,862 remote           L0707 ERROR| Remote [scylla-test@35.196.27.64]: Error while executing SSH command: Command: /bin/ssh -tt -a -x  -o ControlPath=/var/tmp/ssh-masterylP3NZ/socket -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpZi1v8t -o BatchMode=yes -o ConnectTimeout=30 -o ServerAliveInterval=300 -l scylla-test -p 22 -i /home/amos/.ssh/scylla-test 35.196.27.64 "true"
Exit status: -15
Duration: 30.0036251545
Stdout:

Stderr:
...

2018-06-07 06:04:34,983 wait             L0052 WARNI| Wait for: None: timeout - 300 seconds - expired
2018-06-07 06:04:34,984 output           L0642 DEBUG| Exception in thread Thread-2:
2018-06-07 06:04:34,985 output           L0642 DEBUG| Traceback (most recent call last):
2018-06-07 06:04:34,985 output           L0642 DEBUG|   File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
2018-06-07 06:04:34,985 output           L0642 DEBUG|     self.run()
2018-06-07 06:04:34,986 output           L0642 DEBUG|   File "/usr/lib64/python2.7/threading.py", line 765, in run
2018-06-07 06:04:34,986 output           L0642 DEBUG|     self.__target(*self.__args, **self.__kwargs)
2018-06-07 06:04:34,986 output           L0642 DEBUG|   File "/home/amos/space/scylla-cluster-tests/sdcm/cluster.py", line 798, in backtrace_thread
2018-06-07 06:04:34,986 output           L0642 DEBUG|     self.get_backtraces()
2018-06-07 06:04:34,987 output           L0642 DEBUG|   File "/home/amos/space/scylla-cluster-tests/sdcm/cluster.py", line 779, in get_backtraces
2018-06-07 06:04:34,987 output           L0642 DEBUG|     self.wait_ssh_up(verbose=False)
2018-06-07 06:04:34,987 output           L0642 DEBUG|   File "/home/amos/space/scylla-cluster-tests/sdcm/cluster.py", line 830, in wait_ssh_up
2018-06-07 06:04:34,987 output           L0642 DEBUG|     wait.wait_for(func=self.remoter.is_up, step=10, text=text, timeout=timeout, throw_exc=True)
2018-06-07 06:04:34,988 output           L0642 DEBUG|   File "/home/amos/space/scylla-cluster-tests/sdcm/wait.py", line 54, in wait_for
2018-06-07 06:04:34,988 output           L0642 DEBUG|     raise WaitTimeoutExpired(err)
2018-06-07 06:04:34,988 output           L0642 DEBUG| WaitTimeoutExpired: Wait for: None: timeout - 300 seconds - expired

```

**Comment by amoskong** [comment]
I increased it to 500 seconds in commit dd510d19. We didn't see this issue in recent test.

Close this issue.
