### ISSUE TITLE
Upgrade Alternator test having troubles with 

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylla-cluster-tests#5805]
### Prerequisites

* [ ] Are you rebased to master ?
* [ ] Is it reproducible ?
* [ ] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: branch-5.2
* **scylla**: branch-5.2

### Logs
* test_id: 855cdfbe-c420-4d40-87b6-564234a8ad45
* job log: https://jenkins.scylladb.com/job/scylla-5.2/job/rolling-upgrade/job/rolling-upgrade-alternator-test/5/
 https://argus.scylladb.com/workspace?state=WyI3MmQxZGViZi00MzBkLTQ5YTUtOGMxMS1mYTRiYTk2ZDVlNTQiXQ

### Description

Alternator runs are taking wrong credentials, making the test to fail.
seems like since e6d9785de11b4f66e277c4f02e911fa0b9f55dff we are having some issues with alternator rolling upgrade:
```
< t:2023-02-12 12:12:31,787 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 2023-02-12 12:12:31.785: (YcsbStressEvent Severity.ERROR) period_type=not-set event_id=4ea11a24-8717-46e6-a5af-2ea911f59da5: type=error node=Node rolling-upgrade--centos-loader-node-855cdfbe-0-1 [34.138.28.108 | 10.142.0.50] (seed: False)
< t:2023-02-12 12:12:31,787 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > stress_cmd=bin/ycsb run dynamodb -P workloads/workloada -threads 100 -p recordcount=1010020 -p readproportion=0 -p updateproportion=1 -p scanproportion=0 -p insertproportion=0 -p requestdistribution=uniform -p fieldcount=10 -p fieldlength=512 -p operationcount=1010020 -p table=usertable -s  -P /tmp/dynamodb.properties -p maxexecutiontime=22200
< t:2023-02-12 12:12:31,787 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > errors:
< t:2023-02-12 12:12:31,787 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 
< t:2023-02-12 12:12:31,787 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 502  [Thread-13] ERROR site.ycsb.db.DynamoDBClient  -com.amazonaws.services.dynamodbv2.model.AmazonDynamoDBException: User not found: alternator (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: UnrecognizedClientException; Request ID: null; Proxy: null)
< t:2023-02-12 12:12:31,789 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 505  [Thread-57] ERROR site.ycsb.db.DynamoDBClient  -com.amazonaws.services.dynamodbv2.model.AmazonDynamoDBException: User not found: alternator (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: UnrecognizedClientException; Request ID: null; Proxy: null)
< t:2023-02-12 12:12:31,801 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 511  [Thread-35] ERROR site.ycsb.db.DynamoDBClient  -com.amazonaws.services.dynamodbv2.model.AmazonDynamoDBException: User not found: alternator (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: UnrecognizedClientException; Request ID: null; Proxy: null)
```

**Comment by fruch** [comment]
Happened once in master, two months ago:

https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-alternator-test/123/

I've triggered it again, to see if it's working.

Doesn't seem to be related to any specific SCT code change, 

it might not be propagating fast enough to all nodes, and we should be doing the CQL to add the role with cl.ALL ?

**Comment by fgelcer** [comment]
> Happened once in master, two months ago:
> 
> https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-alternator-test/123/
> 
> I've triggered it again, to see if it's working.
> 
> Doesn't seem to be related to any specific SCT code change,
> 
> it might not be propagating fast enough to all nodes, and we should be doing the CQL to add the role with cl.ALL ?

@fruch , failed again, and it seems to be the same thing

**Comment by fruch** [comment]
> > Happened once in master, two months ago:
> > https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-alternator-test/123/
> > I've triggered it again, to see if it's working.
> > Doesn't seem to be related to any specific SCT code change,
> > it might not be propagating fast enough to all nodes, and we should be doing the CQL to add the role with cl.ALL ?
> 
> @fruch , failed again, and it seems to be the same thing

no it doesn't seem like the same error, stress commands start fine, and then test fail on this:
```
2023-02-13 22:49:26.091: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=5d809858-6e3f-4759-b785-bc761bcdfdd1, source=UpgradeTest.test_generic_cluster_upgrade (upgrade_test.UpgradeTest)() message=Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/upgrade_test.py", line 862, in test_generic_cluster_upgrade
self._start_and_wait_for_node_upgrade(node_to_upgrade, step=next(step))
File "/home/ubuntu/scylla-cluster-tests/upgrade_test.py", line 784, in _start_and_wait_for_node_upgrade
self.upgrade_node(node, upgrade_sstables=self.params.get('upgrade_sstables'))
File "/home/ubuntu/scylla-cluster-tests/upgrade_test.py", line 61, in inner
with self.db_cluster.cql_connection_patient(node, keyspace='truncate_ks') as session:
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 67, in inner
return func(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3429, in cql_connection_patient
return self.cql_connection(**kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3385, in cql_connection
return self._create_session(node=node, keyspace=keyspace, user=user, password=password,
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3369, in _create_session
session.set_keyspace(keyspace)
File "cassandra/cluster.py", line 3362, in cassandra.cluster.Session.set_keyspace
File "cassandra/cluster.py", line 2699, in cassandra.cluster.Session.execute
File "cassandra/cluster.py", line 5018, in cassandra.cluster.ResponseFuture.result
cassandra.InvalidRequest: Error from server: code=2200 [Invalid query] message="Keyspace 'truncate_ks' does not exist"
```
