### ISSUE TITLE
TRUNCATE ... USING TIMEOUT is failing on operator 

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#5874]
## Issue description

```
Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4108, in wrapper
    result = method(*args[1:], **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1850, in disrupt_truncate_large_partition
    self.target_node.run_cqlsh(cmd=f'TRUNCATE {ks_name}.{table} USING TIMEOUT {truncate_timeout}',
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2779, in run_cqlsh
    cqlsh_out = self.remoter.run(cmd, timeout=timeout + 30,  # we give 30 seconds to cqlsh timeout mechanism to work
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/kubernetes_cmd_runner.py", line 164, in run
    return super().run(cmd, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run
    result = _run()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 67, in inner
    return func(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run
    return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/kubernetes_cmd_runner.py", line 203, in _run_execute
    return super()._run_execute(cmd, timeout=timeout, ignore_status=ignore_status, verbose=verbose,
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 530, in _run_execute
    result = connection.run(**command_kwargs)
  File "/usr/local/lib/python3.10/site-packages/invoke/runners.py", line 380, in run
    return self._run_body(command, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/invoke/runners.py", line 442, in _run_body
    return self.make_promise() if self._asynchronous else self._finish()
  File "/usr/local/lib/python3.10/site-packages/invoke/runners.py", line 509, in _finish
    raise UnexpectedExit(result)
invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!

Command: 'cqlsh --no-color   --request-timeout=600 --connect-timeout=60  -e "TRUNCATE ks_truncate_large_partition.test_table USING TIMEOUT 600" 10.0.2.73 9042'

Exit code: 2

Stdout:



Stderr:

<stdin>:1:InvalidRequest: Error from server: code=2200 [Invalid query] message="Invalid INTEGER constant (600) for "[timeout]" of type duration"


```

## Installation details

Kernel Version: 5.10.165-143.735.amzn2.x86_64
Scylla version (or git commit hash): `5.3.0~dev-20230304.4b71f8759464` with build-id `e748e632702e534ee8d500ae4e3bac8b4d1f4bed`

Operator Image: scylladb/scylla-operator:latest
Operator Helm Version: v1.9.0-alpha.1-35-g7a3f124
Operator Helm Repository: https://storage.googleapis.com/scylla-operator-charts/latest
Cluster size: 4 nodes (i3.4xlarge)

Scylla Nodes used in this run:
**No resources left at the end of the run**

OS / Image: `` (k8s-eks: eu-north-1)

Test: `longevity-scylla-operator-3h-eks`
Test id: `88a3ea05-1e74-4e81-a06a-0803ff8b23a0`
Test name: `scylla-operator/operator-master/eks/longevity-scylla-operator-3h-eks`
Test config file(s):

- [longevity-scylla-operator-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/7d691c9db7946a26ee15cf27aab317dbfb95465e/test-cases/scylla-operator/longevity-scylla-operator-3h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 88a3ea05-1e74-4e81-a06a-0803ff8b23a0`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=88a3ea05-1e74-4e81-a06a-0803ff8b23a0)
- Show all stored logs command: `$ hydra investigate show-logs 88a3ea05-1e74-4e81-a06a-0803ff8b23a0`

## Logs:
*No logs captured during this run.*

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-operator/job/operator-master/job/eks/job/longevity-scylla-operator-3h-eks/56/)
</details>

**Comment by fruch** [comment]
happens in five different test cases 

https://70f106c98484448dbc4705050eb3f7e9.us-east-1.aws.found.io:9243/goto/f45dd300-bb2f-11ed-baf0-09544f843571
