### ISSUE TITLE
C-S fails with "java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter" error using dockerized Scylla

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-cluster-tests#5883]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master
* **scylla**: scylladb/scylla-nightly:5.2.0-rc0-0.20230119.34ab98e1be2e

### Logs
* test_id: a540f72e-c1cd-4987-a547-cdbe4e70c020
* job log: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/valerii/job/perf-regression-throughput-eks/28

### Description

If we enable `use_hdr_cs_histogram: true` option running on K8S then we get following errors on loaders:

```
===== Using optimized driver!!! =====
Connected to cluster: sct-cluster, max pending requests per connection null, max connections per host 8
Datatacenter: us-east1-b; Host: ac2ebcfc23261424bbbc408051d336b8-1378399727.us-east-1.elb.amazonaws.com/34.236.196.24; Rack: us-east1
Datatacenter: us-east1-b; Host: ac2ebcfc23261424bbbc408051d336b8-1378399727.us-east-1.elb.amazonaws.com/52.4.188.236; Rack: us-east1
Datatacenter: us-east1-b; Host: ac2ebcfc23261424bbbc408051d336b8-1378399727.us-east-1.elb.amazonaws.com/34.236.196.24; Rack: us-east1
WARN  12:34:04,188 Not using advanced port-based shard awareness with ac2ebcfc23261424bbbc408051d336b8-1378399727.us-east-1.elb.amazonaws.com:9142:4c2c6857-fdb4-4d70-af36-f36795283ae2.cql.sct-cluster.sct.scylladb.com because it's disabled in configuration
WARN  12:34:05,508 Not using advanced port-based shard awareness with ac2ebcfc23261424bbbc408051d336b8-1378399727.us-east-1.elb.amazonaws.com:9142:4dc87297-c8bd-4ffe-ab23-99c74f6b2ca4.cql.sct-cluster.sct.scylladb.com because it's disabled in configuration
WARN  12:34:06,241 Not using advanced port-based shard awareness with ac2ebcfc23261424bbbc408051d336b8-1378399727.us-east-1.elb.amazonaws.com:9142:e3347c50-a4ec-4ce8-a80c-ba9140f93208.cql.sct-cluster.sct.scylladb.com because it's disabled in configuration
Created keyspaces. Sleeping 1s for propagation.
Sleeping 2s...
Running WRITE with 100 threads 60 minutes
Failed to connect over JMX; not collecting these stats
type       total ops,    op/s,    pk/s,   row/s,    mean,     med,     .95,     .99,    .999,     max,   time,   stderr, errors,  gc: #,  max ms,  sum ms,  sdv ms,      mb
Exception in thread "StressMetrics" java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at org.HdrHistogram.HistogramLogWriter.outputIntervalHistogram(HistogramLogWriter.java:135)
	at org.HdrHistogram.HistogramLogWriter.outputIntervalHistogram(HistogramLogWriter.java:154)
	at org.HdrHistogram.HistogramLogWriter.outputIntervalHistogram(HistogramLogWriter.java:175)
	at org.apache.cassandra.stress.report.StressMetrics.logHistogram(StressMetrics.java:336)
	at org.apache.cassandra.stress.report.StressMetrics.logHistograms(StressMetrics.java:320)
	at org.apache.cassandra.stress.report.StressMetrics.recordInterval(StressMetrics.java:253)
	at org.apache.cassandra.stress.report.StressMetrics.reportingLoop(StressMetrics.java:172)
	at org.apache.cassandra.stress.report.StressMetrics.lambda$new$1(StressMetrics.java:124)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 9 more
```

### Steps to Reproduce

1. Enable `use_hdr_cs_histogram: true` option
2. Run a test on any K8S backend.
3. See error

**Expected behavior:** HDR feature of the `cassandra-stress` must work on K8S using dockerized Scylla images.

**Actual behavior:** It fails to run

**Comment by aleksbykov** [comment]
@vponomaryov hdr option is running only with java8. you can change to use another image see: configurations/stress_images/cs-java8.yaml

**Comment by vponomaryov** [comment]
> configurations/stress_images/cs-java8.yaml

It must be image with the `cloud-bundle` support. Does it have it?

**Comment by fruch** [comment]
> @vponomaryov hdr option is running only with java8. you can change to use another image see: configurations/stress_images/cs-java8.yaml 

Is there any issue for tracking the fix to have it working on the formal Scylla images ? (i.e. with java 11)

**Comment by aleksbykov** [comment]
@fruch i didn't open, because it is c-s issue, as i think. Where better to open?

**Comment by fruch** [comment]
for scylla: https://github.com/scylladb/scylla-tools-java, 
and if it's relevent to c-s upstream so also in https://issues.apache.org/jira/projects/CASSANDRA/issues

we should strive to fix it, we can't assume we can always gonna be able to go back to older java version

**Comment by aleksbykov** [comment]
Ok i will open

**Comment by aleksbykov** [comment]
Open issue: https://github.com/scylladb/scylla-tools-java/issues/328

For c-s upstream couldn't open, i don't have an account. I request account, when i got it , i will open for upstream
