### ISSUE TITLE
Cassandra driver: RuntimeError: cannot schedule new futures after interpreter shutdown

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#5907]
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

error log:
```
Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4088, in wrapper
    result = method(*args[1:], **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1091, in disrupt_destroy_data_then_rebuild
    self._destroy_data_and_restart_scylla()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/sct_events/group_common_events.py", line 250, in inner_func
    return func(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1028, in _destroy_data_and_restart_scylla
    ks_cfs = self.cluster.get_non_system_ks_cf_list(db_node=self.target_node, filter_empty_tables=False)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3460, in get_non_system_ks_cf_list
    return self.get_any_ks_cf_list(db_node, filter_out_table_with_counter=filter_out_table_with_counter,
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3521, in get_any_ks_cf_list
    with self.cql_connection_patient(db_node) as session:
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 67, in inner
    return func(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3439, in cql_connection_patient
    return self.cql_connection(**kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3395, in cql_connection
    return self._create_session(node=node, keyspace=keyspace, user=user, password=password,
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3372, in _create_session
    session = cluster_driver.connect()
  File "cassandra/cluster.py", line 1781, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 1853, in cassandra.cluster.Cluster._new_session
  File "cassandra/cluster.py", line 2622, in cassandra.cluster.Session.__init__
  File "cassandra/cluster.py", line 3301, in cassandra.cluster.Session.add_or_renew_pool
  File "cassandra/cluster.py", line 3426, in cassandra.cluster.Session.submit
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 163, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown
```
It reproduced tons of times:
```
$ grep -c 'p:ERROR > RuntimeError: cannot schedule new futures after interpreter shutdown' sct.log 
275443

```

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Kernel Version: 5.15.0-1031-aws
Scylla version (or git commit hash): `2023.1.0~rc2-20230302.726f8a090337` with build-id `efcc950cda22875aa488c5295c6cc68f35d9cc6f`

Cluster size: 4 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- longevity-tls-1tb-7d-2023-1-db-node-52776f27-8 (54.247.18.109 | 10.4.1.79) (shards: 14)
- longevity-tls-1tb-7d-2023-1-db-node-52776f27-7 (3.253.57.198 | 10.4.3.240) (shards: 14)
- longevity-tls-1tb-7d-2023-1-db-node-52776f27-6 (34.247.183.17 | 10.4.0.35) (shards: 14)
- longevity-tls-1tb-7d-2023-1-db-node-52776f27-5 (3.250.177.43 | 10.4.2.134) (shards: 14)
- longevity-tls-1tb-7d-2023-1-db-node-52776f27-4 (54.75.80.9 | 10.4.1.130) (shards: 14)
- longevity-tls-1tb-7d-2023-1-db-node-52776f27-3 (54.72.86.47 | 10.4.1.247) (shards: 14)
- longevity-tls-1tb-7d-2023-1-db-node-52776f27-2 (34.244.176.55 | 10.4.3.44) (shards: 14)
- longevity-tls-1tb-7d-2023-1-db-node-52776f27-1 (34.245.12.22 | 10.4.0.24) (shards: 14)

OS / Image: `ami-0336a5a646b08dc25` (aws: eu-west-1)

Test: `ics-longevity-1tb-7days-test`
Test id: `52776f27-b99b-444c-982e-89fbb62999ad`
Test name: `enterprise-2023.1/SCT_Enterprise_Features/ICS/ics-longevity-1tb-7days-test`
Test config file(s):

- [longevity-1TB-5days-authorization-and-tls-ssl.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/9a5f163455e77d1518d00ea2a5ac14df134cf2f6/test-cases/longevity/longevity-1TB-5days-authorization-and-tls-ssl.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 52776f27-b99b-444c-982e-89fbb62999ad`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=52776f27-b99b-444c-982e-89fbb62999ad)
- Show all stored logs command: `$ hydra investigate show-logs 52776f27-b99b-444c-982e-89fbb62999ad`

## Logs:
- **db-cluster-52776f27.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/db-cluster-52776f27.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/db-cluster-52776f27.tar.gz)
- **output-52776f27.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/output-52776f27.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/output-52776f27.log.tar.gz)
- **debug-52776f27.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/debug-52776f27.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/debug-52776f27.log.tar.gz)
- **events-52776f27.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/events-52776f27.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/events-52776f27.log.tar.gz)
- **sct-52776f27.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/sct-52776f27.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/sct-52776f27.log.tar.gz)
- **normal-52776f27.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/normal-52776f27.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/normal-52776f27.log.tar.gz)
- **argus-52776f27.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/argus-52776f27.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/argus-52776f27.log.tar.gz)
- **raw_events-52776f27.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/raw_events-52776f27.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/raw_events-52776f27.log.tar.gz)
- **critical-52776f27.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/critical-52776f27.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/critical-52776f27.log.tar.gz)
- **warning-52776f27.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/warning-52776f27.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/warning-52776f27.log.tar.gz)
- **summary-52776f27.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/summary-52776f27.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/summary-52776f27.log.tar.gz)
- **error-52776f27.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/error-52776f27.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/error-52776f27.log.tar.gz)
- **monitor-set-52776f27.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/monitor-set-52776f27.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/monitor-set-52776f27.tar.gz)
- **loader-set-52776f27.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/loader-set-52776f27.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/loader-set-52776f27.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2023.1/job/SCT_Enterprise_Features/job/ICS/job/ics-longevity-1tb-7days-test/2/)
</details>

**Comment by yarongilor** [comment]
@fruch , @fgelcer , could it be related to a new scylla driver version used?
