### ISSUE TITLE
Fail clean user resources due Argus client error

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#5909]
When running `hydra clean-resources --user <user>`
error appears:
```
Clean all resources belong to user `<user>'
Traceback (most recent call last):
  File "/home/ls/repos/scylla-cluster-tests/./sct.py", line 1678, in <module>
    cli.main(prog_name="hydra")
  File "/home/ls/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/ls/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ls/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ls/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/ls/.local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ls/repos/scylla-cluster-tests/./sct.py", line 295, in clean_resources
    clean_func(param, dry_run=dry_run)
  File "/home/ls/repos/scylla-cluster-tests/sdcm/utils/common.py", line 549, in clean_cloud_resources
    clean_instances_aws(tags_dict, dry_run=dry_run)
  File "/home/ls/repos/scylla-cluster-tests/sdcm/utils/common.py", line 767, in clean_instances_aws
    argus_client = get_argus_client(run_id=tags_dict["TestId"])
KeyError: 'TestId'
```

**Comment by fgelcer** [comment]
i spoke with @k0machi about it few days ago, but i don't remember if a fix was already sent

**Comment by fruch** [comment]
I think this probably should be the fix:
https://github.com/scylladb/scylla-cluster-tests/pull/5901

**Comment by k0machi** [comment]
PR was merged, I think we can close this.
