### ISSUE TITLE
K8S - decommission can't start (AssertionError: Can withdraw the last node only)

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#5956]
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

In multiple case of decommission we are getting this error: 
```
2023-03-26 04:35:53.633: (DisruptionEvent Severity.ERROR) period_type=end event_id=0dd3543c-783f-4634-8f18-4d2e50391ffa duration=6m17s: nemesis_name=DrainKubernetesNodeThenDecommissionAndAddScyllaNode target_node=Node sct-cluster-2-us-east1-b-us-east1-1 [10.0.0.160 | 10.0.0.85] (seed: False) errors=Can withdraw the last node only
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4231, in wrapper
result = method(*args[1:], **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1412, in disrupt_drain_kubernetes_node_then_decommission_and_add_scylla_node
self._disrupt_kubernetes_then_decommission_and_add_scylla_node('drain_k8s_node')
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1435, in _disrupt_kubernetes_then_decommission_and_add_scylla_node
self.cluster.decommission(node, soft_timeout=MAX_TIME_WAIT_FOR_DECOMMISSION)
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster_k8s/__init__.py", line 2665, in decommission
assert rack_nodes[-1] == node, "Can withdraw the last node only"
AssertionError: Can withdraw the last node only
```

## Impact

can do decomissions

## How frequently does it reproduce?

first time encountered

## Installation details

Kernel Version: 5.10.167-147.601.amzn2.x86_64
Scylla version (or git commit hash): `5.3.0~dev-20230325.e8fb718e4ad4` with build-id `6eed28a1ac2addc02aceea60af4d6ee4acd56955`

Operator Image: scylladb/scylla-operator:latest
Operator Helm Version: v1.9.0-alpha.2-2-g1ae0bfc
Operator Helm Repository: https://storage.googleapis.com/scylla-operator-charts/latest
Cluster size: 4 nodes (i3.4xlarge)

Scylla Nodes used in this run:
**No resources left at the end of the run**

OS / Image: `` (k8s-eks: eu-north-1)

Test: `longevity-scylla-operator-3h-multitenant-eks`
Test id: `8366a073-73be-4a66-bcdf-1d7c87b5b7ae`
Test name: `scylla-operator/operator-master/eks/longevity-scylla-operator-3h-multitenant-eks`
Test config file(s):

- [longevity-scylla-operator-3h-multitenant.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/208d4af177d46b03473dd95e15a276916a704964/test-cases/scylla-operator/longevity-scylla-operator-3h-multitenant.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 8366a073-73be-4a66-bcdf-1d7c87b5b7ae`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=8366a073-73be-4a66-bcdf-1d7c87b5b7ae)
- Show all stored logs command: `$ hydra investigate show-logs 8366a073-73be-4a66-bcdf-1d7c87b5b7ae`

## Logs:
- **db-cluster-8366a073.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8366a073-73be-4a66-bcdf-1d7c87b5b7ae/20230326_045330/db-cluster-8366a073.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8366a073-73be-4a66-bcdf-1d7c87b5b7ae/20230326_045330/db-cluster-8366a073.tar.gz)
- **sct-runner-events-8366a073.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8366a073-73be-4a66-bcdf-1d7c87b5b7ae/20230326_045330/sct-runner-events-8366a073.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8366a073-73be-4a66-bcdf-1d7c87b5b7ae/20230326_045330/sct-runner-events-8366a073.tar.gz)
- **sct-8366a073.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8366a073-73be-4a66-bcdf-1d7c87b5b7ae/20230326_045330/sct-8366a073.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8366a073-73be-4a66-bcdf-1d7c87b5b7ae/20230326_045330/sct-8366a073.log.tar.gz)
- **monitor-set-8366a073.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8366a073-73be-4a66-bcdf-1d7c87b5b7ae/20230326_045330/monitor-set-8366a073.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8366a073-73be-4a66-bcdf-1d7c87b5b7ae/20230326_045330/monitor-set-8366a073.tar.gz)
- **loader-set-8366a073.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8366a073-73be-4a66-bcdf-1d7c87b5b7ae/20230326_045330/loader-set-8366a073.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8366a073-73be-4a66-bcdf-1d7c87b5b7ae/20230326_045330/loader-set-8366a073.tar.gz)
- **kubernetes-8366a073.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8366a073-73be-4a66-bcdf-1d7c87b5b7ae/20230326_045330/kubernetes-8366a073.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8366a073-73be-4a66-bcdf-1d7c87b5b7ae/20230326_045330/kubernetes-8366a073.tar.gz)
- **parallel-timelines-report-8366a073.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8366a073-73be-4a66-bcdf-1d7c87b5b7ae/20230326_045330/parallel-timelines-report-8366a073.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8366a073-73be-4a66-bcdf-1d7c87b5b7ae/20230326_045330/parallel-timelines-report-8366a073.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-operator/job/operator-master/job/eks/job/longevity-scylla-operator-3h-multitenant-eks/27/)
</details>

**Comment by fruch** [comment]
seem like `Nemesis._get_target_nodes` doesn't return a sorted list as `BaseScyllaCluster.get_rack_nodes` does.
and in some case they could generate different order list and the assumption on selecting the last node in a rack doesn't work as expected.

**Comment by fruch** [comment]
seems like the root cause is that `disrupt_terminate_kubernetes_host_then_decommission_and_add_scylla_node` has failed in the middle, and the the cluster seem to be left in some unexpected state.
```
Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4231, in wrapper
    result = method(*args[1:], **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1415, in disrupt_terminate_kubernetes_host_then_decommission_and_add_scylla_node
    self._disrupt_kubernetes_then_decommission_and_add_scylla_node('terminate_k8s_host')
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1437, in _disrupt_kubernetes_then_decommission_and_add_scylla_node
    new_node = self.add_new_node(rack=node.rack)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 171, in wrapped
    res = func(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3513, in add_new_node
    return self._add_and_init_new_cluster_node(rack=rack)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 67, in inner
    return func(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1200, in _add_and_init_new_cluster_node
    if new_node.is_replacement_by_host_id_supported:
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2751, in is_replacement_by_host_id_supported
    return ComparableScyllaVersion(self.scylla_version) > '5.2.0~dev'
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 245, in __get__
    return super().__get__(instance=instance, owner=owner)
  File "/usr/local/lib/python3.10/functools.py", line 970, in __get__
    val = self.func(instance)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2137, in scylla_version
    if scylla_version := self.scylla_version_detailed:
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 245, in __get__
    return super().__get__(instance=instance, owner=owner)
  File "/usr/local/lib/python3.10/functools.py", line 970, in __get__
    val = self.func(instance)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2123, in scylla_version_detailed
    scylla_version = self.get_scylla_binary_version()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2102, in get_scylla_binary_version
    result = self.remoter.run(f"{self.add_install_prefix('/usr/bin/scylla')} --version", ignore_status=True)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/kubernetes_cmd_runner.py", line 164, in run
    return super().run(cmd, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run
    result = _run()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 67, in inner
    return func(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run
    return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/kubernetes_cmd_runner.py", line 203, in _run_execute
    return super()._run_execute(cmd, timeout=timeout, ignore_status=ignore_status, verbose=verbose,
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 530, in _run_execute
    result = connection.run(**command_kwargs)
  File "/usr/local/lib/python3.10/site-packages/invoke/runners.py", line 380, in run
    return self._run_body(command, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/invoke/runners.py", line 442, in _run_body
    return self.make_promise() if self._asynchronous else self._finish()
  File "/usr/local/lib/python3.10/site-packages/invoke/runners.py", line 496, in _finish
    result = self._collate_result(watcher_errors)
  File "/usr/local/lib/python3.10/site-packages/invoke/runners.py", line 590, in _collate_result
    exited = None if watcher_errors else self.returncode()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/kubernetes_cmd_runner.py", line 108, in returncode
    return self.process.returncode
  File "/usr/local/lib/python3.10/site-packages/kubernetes/stream/ws_client.py", line 238, in returncode
    self._returncode = int(err['details']['causes'][0]['message'])
ValueError: invalid literal for int() with base 10: 'error executing command in container: failed to exec in container: failed to start exec "96bc849232f5301a95172fe5374480c20eae3420ddd8ab96f469fa44ab936dc7": OCI runtime exec failed: exec failed: canno

```

**Comment by fruch** [comment]
it's both `is_replacement_by_host_id_supported` and `disrupt_terminate_kubernetes_host_then_decommission_and_add_scylla_node`

I think we are trying to talk with a node that is currently been removed, to get the scylla version and it's not available, i.e. currently was decommissioned  

@vponomaryov can you take a look ? i think we might need to call the parse function in order to cache it as soon as the node is up.

**Comment by fruch** [comment]
> > ValueError: invalid literal for int() with base 10: 'error executing command in container: failed to exec in container: failed to start exec "96bc849232f5301a95172fe5374480c20eae3420ddd8ab96f469fa44ab936dc7": OCI runtime exec failed: exec failed: canno
> 
> As I already answered you in the argus thread, the following error:
> 
> ```
> ValueError: invalid literal for int() with base 10: 'error executing command in container: failed to exec in container: failed to start exec "96bc849232f5301a95172fe5374480c20eae3420ddd8ab96f469fa44ab936dc7": OCI runtime exec failed: exec failed: canno
> ```
> 
> Means that the OCI driver on that node is misconfigured and any `kubectl exec ...` command will fail. If you see this error then need to rerun test.

to we have any reference to this issue ? so we can track how to resolve handle it ?

**Comment by vponomaryov** [comment]
> > > ValueError: invalid literal for int() with base 10: 'error executing command in container: failed to exec in container: failed to start exec "96bc849232f5301a95172fe5374480c20eae3420ddd8ab96f469fa44ab936dc7": OCI runtime exec failed: exec failed: canno
> > 
> > 
> > As I already answered you in the argus thread, the following error:
> > ```
> > ValueError: invalid literal for int() with base 10: 'error executing command in container: failed to exec in container: failed to start exec "96bc849232f5301a95172fe5374480c20eae3420ddd8ab96f469fa44ab936dc7": OCI runtime exec failed: exec failed: canno
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Means that the OCI driver on that node is misconfigured and any `kubectl exec ...` command will fail. If you see this error then need to rerun test.
> 
> to we have any reference to this issue ? so we can track how to resolve handle it ? is it this one ? [kubernetes-client/python#1840](https://github.com/kubernetes-client/python/issues/1840) ?

The problem is in the misconfiguration of the EKS nodes, which happen from time to time.
Such issues like the one you referred to are only about `nice error messages`. 
The test run is scewed when you see this error because none of `kubectl exec` command will work on node where it appeared.

> Also it's a bit weird we don't see the whole failure message, that might shed some light on what's wrong

It is available in the SCT.log file.

**Comment by fruch** [comment]
> The problem is in the misconfiguration of the EKS nodes, which happen from time to time.

if this kind of thing happens we need to track it somewhere, if it happens to us, can it happen on the cloud serverless ?

**Comment by vponomaryov** [comment]
> > The problem is in the misconfiguration of the EKS nodes, which happen from time to time.
> 
> if this kind of thing happens we need to track it somewhere, if it happens to us, can it happen on the cloud serverless ?

It can happen on any EKS node.

**Comment by fruch** [comment]
> It is available in the SCT.log file.

can you help me find it ?

> The problem is in the misconfiguration of the EKS nodes, which happen from time to time.

do you know which missconfiguration we are talking about ? I failed to find any details.

**Comment by vponomaryov** [comment]
> > It is available in the SCT.log file.
> 
> can you help me find it ?

Hm, you caught it in a different place. When I faced it, it was during the local CSI driver installation, which is just absent in your setup.

So, it was looking like following:

```
error: 
  Internal error occurred: 
    error executing command in container: 
      failed to exec in container: 
        failed to start exec "5c28bc051826ba49232ba8a5f139de4c11d982eab9abcea83fef70add0f42f65": 
          OCI runtime exec failed: 
            exec failed: 
              unable to start container process: 
                error adding pid 4299 to cgroups: 
                  failed to write 4299: openat2 /sys/fs/cgroup/systemd/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod32e8662d_6ba5_49e1_8b6f_219d77e8bb16.slice/cri-containerd-e1697ef4ca767cc66764ccd28b7d063824ad0b674c86e91b73a6ddb54153d859.scope/cgroup.procs: 
                    no such file or directory: unknown
```

> 
> > The problem is in the misconfiguration of the EKS nodes, which happen from time to time.
> 
> do you know which missconfiguration we are talking about ? I failed to find any details.

Configuration of EKS nodes itself, which we can influence, technically, but do not manage.
It's totally platform problem. I haven't spent a lot of time to dig in to the full details.
Just simple EKS node recreation solves the problem.
So, I see it as a broken provisioning on the EKS side and incorrectly working health checkers.

**Comment by tnozicka** [comment]
I think you'd have to collect more info or try to see if there is a reproducer to identify the correct component to file the bug to and show that's not framework related. E.g. if you do exec and the pod dies / restarts / gets deleted in the meantime the cgroup slice won't be there anymore and it will fail.
