### ISSUE TITLE
disrupt_add_remove_mv is timing out on DROP of the MV

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#6099]
## Issue description

- [ ] This issue is a regression.
- [x] It is unknown if this issue is a regression.

disrupt_add_remove_mv is timing out on DROP of the MV on some of the cases

```
Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4375, in wrapper
    result = method(*args[1:], **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4267, in disrupt_add_remove_mv
    drop_materialized_view(session, ks_name, view_name)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/nemesis_utils/indexes.py", line 134, in drop_materialized_view
    session.execute(f'DROP MATERIALIZED VIEW {ks}.{view_name}')
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 1665, in execute_verbose
    return execute_orig(*args, **kwargs)
  File "cassandra/cluster.py", line 2699, in cassandra.cluster.Session.execute
  File "cassandra/cluster.py", line 5018, in cassandra.cluster.ResponseFuture.result
cassandra.OperationTimedOut: errors={'10.12.8.103:9042': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=10.12.8.103:9042
```

```
Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4263, in disrupt_add_remove_mv
    session.execute(SimpleStatement(f'SELECT * FROM {ks_name}.{view_name} limit 1', fetch_size=10))
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 1665, in execute_verbose
    return execute_orig(*args, **kwargs)
  File "cassandra/cluster.py", line 2699, in cassandra.cluster.Session.execute
  File "cassandra/cluster.py", line 5018, in cassandra.cluster.ResponseFuture.result
cassandra.OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=10.12.11.181:9042

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4375, in wrapper
    result = method(*args[1:], **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4267, in disrupt_add_remove_mv
    drop_materialized_view(session, ks_name, view_name)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/nemesis_utils/indexes.py", line 134, in drop_materialized_view
    session.execute(f'DROP MATERIALIZED VIEW {ks}.{view_name}')
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 1665, in execute_verbose
    return execute_orig(*args, **kwargs)
  File "cassandra/cluster.py", line 2699, in cassandra.cluster.Session.execute
  File "cassandra/cluster.py", line 5018, in cassandra.cluster.ResponseFuture.result
cassandra.OperationTimedOut: errors={'10.12.11.132:9042': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=10.12.11.132:9042
```

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Kernel Version: 5.15.0-1035-aws
Scylla version (or git commit hash): `2023.2.0~dev-20230430.e4ffb1fcf18f` with build-id `b00af6f2c2d1242afd656abf34634515e9d0425e`

Cluster size: 4 nodes (i3en.2xlarge)

Scylla Nodes used in this run:
- longevity-twcs-48h-master-db-node-238dcdc9-9 (3.85.208.64 | 10.12.8.29) (shards: 7)
- longevity-twcs-48h-master-db-node-238dcdc9-8 (54.224.71.163 | 10.12.11.181) (shards: 7)
- longevity-twcs-48h-master-db-node-238dcdc9-7 (54.81.96.203 | 10.12.11.132) (shards: 7)
- longevity-twcs-48h-master-db-node-238dcdc9-6 (52.90.127.135 | 10.12.10.252) (shards: 7)
- longevity-twcs-48h-master-db-node-238dcdc9-5 (54.175.67.36 | 10.12.11.227) (shards: 7)
- longevity-twcs-48h-master-db-node-238dcdc9-4 (54.87.49.221 | 10.12.8.70) (shards: 7)
- longevity-twcs-48h-master-db-node-238dcdc9-3 (54.242.133.5 | 10.12.9.26) (shards: 7)
- longevity-twcs-48h-master-db-node-238dcdc9-2 (54.167.46.159 | 10.12.11.103) (shards: 7)
- longevity-twcs-48h-master-db-node-238dcdc9-10 (3.80.135.175 | 10.12.9.109) (shards: 7)
- longevity-twcs-48h-master-db-node-238dcdc9-1 (54.210.133.141 | 10.12.8.103) (shards: 7)

OS / Image: `ami-056b298594bed344b` (aws: us-east-1)

Test: `longevity-twcs-48h-test`
Test id: `238dcdc9-1251-45ef-9232-d9f8c53ab609`
Test name: `scylla-enterprise/longevity/longevity-twcs-48h-test`
Test config file(s):

- [longevity-twcs-48h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/1d31a3941d1ba6c9ab69bc16f603aa1d36b70505/test-cases/longevity/longevity-twcs-48h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 238dcdc9-1251-45ef-9232-d9f8c53ab609`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=238dcdc9-1251-45ef-9232-d9f8c53ab609)
- Show all stored logs command: `$ hydra investigate show-logs 238dcdc9-1251-45ef-9232-d9f8c53ab609`

## Logs:
- **db-cluster-238dcdc9.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/238dcdc9-1251-45ef-9232-d9f8c53ab609/20230507_043515/db-cluster-238dcdc9.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/238dcdc9-1251-45ef-9232-d9f8c53ab609/20230507_043515/db-cluster-238dcdc9.tar.gz)
- **email_data-238dcdc9.json.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/238dcdc9-1251-45ef-9232-d9f8c53ab609/20230507_043515/email_data-238dcdc9.json.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/238dcdc9-1251-45ef-9232-d9f8c53ab609/20230507_043515/email_data-238dcdc9.json.tar.gz)
- **output-238dcdc9.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/238dcdc9-1251-45ef-9232-d9f8c53ab609/20230507_043515/output-238dcdc9.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/238dcdc9-1251-45ef-9232-d9f8c53ab609/20230507_043515/output-238dcdc9.log.tar.gz)
- **debug-238dcdc9.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/238dcdc9-1251-45ef-9232-d9f8c53ab609/20230507_043515/debug-238dcdc9.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/238dcdc9-1251-45ef-9232-d9f8c53ab609/20230507_043515/debug-238dcdc9.log.tar.gz)
- **events-238dcdc9.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/238dcdc9-1251-45ef-9232-d9f8c53ab609/20230507_043515/events-238dcdc9.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/238dcdc9-1251-45ef-9232-d9f8c53ab609/20230507_043515/events-238dcdc9.log.tar.gz)
- **normal-238dcdc9.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/238dcdc9-1251-45ef-9232-d9f8c53ab609/20230507_043515/normal-238dcdc9.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/238dcdc9-1251-45ef-9232-d9f8c53ab609/20230507_043515/normal-238dcdc9.log.tar.gz)
- **argus-238dcdc9.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/238dcdc9-1251-45ef-9232-d9f8c53ab609/20230507_043515/argus-238dcdc9.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/238dcdc9-1251-45ef-9232-d9f8c53ab609/20230507_043515/argus-238dcdc9.log.tar.gz)
- **raw_events-238dcdc9.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/238dcdc9-1251-45ef-9232-d9f8c53ab609/20230507_043515/raw_events-238dcdc9.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/238dcdc9-1251-45ef-9232-d9f8c53ab609/20230507_043515/raw_events-238dcdc9.log.tar.gz)
- **critical-238dcdc9.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/238dcdc9-1251-45ef-9232-d9f8c53ab609/20230507_043515/critical-238dcdc9.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/238dcdc9-1251-45ef-9232-d9f8c53ab609/20230507_043515/critical-238dcdc9.log.tar.gz)
- **warning-238dcdc9.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/238dcdc9-1251-45ef-9232-d9f8c53ab609/20230507_043515/warning-238dcdc9.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/238dcdc9-1251-45ef-9232-d9f8c53ab609/20230507_043515/warning-238dcdc9.log.tar.gz)
- **summary-238dcdc9.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/238dcdc9-1251-45ef-9232-d9f8c53ab609/20230507_043515/summary-238dcdc9.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/238dcdc9-1251-45ef-9232-d9f8c53ab609/20230507_043515/summary-238dcdc9.log.tar.gz)
- **left_processes-238dcdc9.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/238dcdc9-1251-45ef-9232-d9f8c53ab609/20230507_043515/left_processes-238dcdc9.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/238dcdc9-1251-45ef-9232-d9f8c53ab609/20230507_043515/left_processes-238dcdc9.log.tar.gz)
- **error-238dcdc9.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/238dcdc9-1251-45ef-9232-d9f8c53ab609/20230507_043515/error-238dcdc9.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/238dcdc9-1251-45ef-9232-d9f8c53ab609/20230507_043515/error-238dcdc9.log.tar.gz)
- **sct-238dcdc9.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/238dcdc9-1251-45ef-9232-d9f8c53ab609/20230507_043515/sct-238dcdc9.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/238dcdc9-1251-45ef-9232-d9f8c53ab609/20230507_043515/sct-238dcdc9.log.tar.gz)
- **monitor-set-238dcdc9.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/238dcdc9-1251-45ef-9232-d9f8c53ab609/20230507_043515/monitor-set-238dcdc9.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/238dcdc9-1251-45ef-9232-d9f8c53ab609/20230507_043515/monitor-set-238dcdc9.tar.gz)
- **loader-set-238dcdc9.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/238dcdc9-1251-45ef-9232-d9f8c53ab609/20230507_043515/loader-set-238dcdc9.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/238dcdc9-1251-45ef-9232-d9f8c53ab609/20230507_043515/loader-set-238dcdc9.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-enterprise/job/longevity/job/longevity-twcs-48h-test/15/)
</details>

**Comment by fruch** [comment]
@yarongilor have you seen those kind of timing out before ?

**Comment by yarongilor** [comment]
@fruch , haven't seen this. i would consider opening a scylla issue for it.

**Comment by fgelcer** [comment]
> @fruch , haven't seen this. i would consider opening a scylla issue for it.

i think this is an issue with the SCT code, perhaps similar to #6086 , as we are trying to run a command when the node is down.. maybe we need to wait for the node to be fully started when we run the repair (and the other 2 queries afterwards

**Comment by fgelcer** [comment]
seeing this on master (new tier1 runs):

```
Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4521, in wrapper
    result = method(*args[1:], **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4413, in disrupt_add_remove_mv
    drop_materialized_view(session, ks_name, view_name)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/nemesis_utils/indexes.py", line 136, in drop_materialized_view
    session.execute(f'DROP MATERIALIZED VIEW {ks}.{view_name}')
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 1742, in execute_verbose
    return execute_orig(*args, **kwargs)
  File "cassandra/cluster.py", line 2699, in cassandra.cluster.Session.execute
  File "cassandra/cluster.py", line 5018, in cassandra.cluster.ResponseFuture.result
cassandra.OperationTimedOut: errors={'10.4.8.121:9042': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=10.4.8.121:9042
```

test details below:
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

*Describe your issue in detail and steps it took to produce it.*

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Kernel Version: 5.15.0-1040-aws
Scylla version (or git commit hash): `5.4.0~dev-20230728.7351c8424df3` with build-id `d47e513b9bff8db5782a5220c05f5ac2a70b7a6c`





Cluster size: 4 nodes (i3en.2xlarge)

Scylla Nodes used in this run:
- longevity-twcs-48h-master-db-node-c2980c40-6 (34.245.150.193 | 10.4.11.144) (shards: 7)
- longevity-twcs-48h-master-db-node-c2980c40-5 (54.170.18.70 | 10.4.10.90) (shards: 7)
- longevity-twcs-48h-master-db-node-c2980c40-4 (18.203.83.141 | 10.4.8.102) (shards: 7)
- longevity-twcs-48h-master-db-node-c2980c40-3 (52.212.201.24 | 10.4.8.121) (shards: 7)
- longevity-twcs-48h-master-db-node-c2980c40-2 (54.74.237.57 | 10.4.11.112) (shards: 7)
- longevity-twcs-48h-master-db-node-c2980c40-1 (46.137.140.147 | 10.4.10.171) (shards: 7)


OS / Image: `` (aws: undefined_region)

Test: `longevity-twcs-48h-test`
Test id: `c2980c40-bc05-40f3-9a72-f7f0b481f4bb`
Test name: `scylla-master/longevity/longevity-twcs-48h-test`
Test config file(s):

- [longevity-twcs-48h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/6e3d34cd1b9fc6533a4e5a3874fd36ad401b9a81/test-cases/longevity/longevity-twcs-48h.yaml)


<details>
<summary>
Logs and commands
</summary>


- Restore Monitor Stack command: `$ hydra investigate show-monitor c2980c40-bc05-40f3-9a72-f7f0b481f4bb`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=c2980c40-bc05-40f3-9a72-f7f0b481f4bb)
- Show all stored logs command: `$ hydra investigate show-logs c2980c40-bc05-40f3-9a72-f7f0b481f4bb`


## Logs:
- **db-cluster-c2980c40.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c2980c40-bc05-40f3-9a72-f7f0b481f4bb/20230730_040823/db-cluster-c2980c40.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c2980c40-bc05-40f3-9a72-f7f0b481f4bb/20230730_040823/db-cluster-c2980c40.tar.gz)
- **sct-runner-events-c2980c40.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c2980c40-bc05-40f3-9a72-f7f0b481f4bb/20230730_040823/sct-runner-events-c2980c40.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c2980c40-bc05-40f3-9a72-f7f0b481f4bb/20230730_040823/sct-runner-events-c2980c40.tar.gz)
- **sct-c2980c40.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c2980c40-bc05-40f3-9a72-f7f0b481f4bb/20230730_040823/sct-c2980c40.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c2980c40-bc05-40f3-9a72-f7f0b481f4bb/20230730_040823/sct-c2980c40.log.tar.gz)
- **loader-set-c2980c40.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c2980c40-bc05-40f3-9a72-f7f0b481f4bb/20230730_040823/loader-set-c2980c40.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c2980c40-bc05-40f3-9a72-f7f0b481f4bb/20230730_040823/loader-set-c2980c40.tar.gz)
- **monitor-set-c2980c40.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c2980c40-bc05-40f3-9a72-f7f0b481f4bb/20230730_040823/monitor-set-c2980c40.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c2980c40-bc05-40f3-9a72-f7f0b481f4bb/20230730_040823/monitor-set-c2980c40.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-twcs-48h-test/78/)
[Argus](https://argus.scylladb.com/test/ca1ac895-78c0-4abd-80d5-0ba6dc7844bf/runs?additionalRuns[]=c2980c40-bc05-40f3-9a72-f7f0b481f4bb)
</details>

**Comment by fruch** [comment]
Looks like it's quite similar to

https://github.com/scylladb/scylladb/issues/9623

Drop properly needs a bigger timeout, but it's not clear how big...

**Comment by fruch** [comment]
> we could drop it few times with "infinite" timeout and figure it out, no?

It's not timing out 100% of the times, so doing a few drops won't tell us the maximum time it might take.

We could use adaptive timeout to collect the data, and then a fter a while to set it based on results.

Anyhow we should get some feedback from devs about the general expectations in those cass

**Comment by fruch** [comment]
Not relevant anymore
