### ISSUE TITLE
Nemesis ToggleLdapConfiguration fails with: LDAPSessionTerminatedByServerError

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#6103]
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.
Nemesis ToggleLdapConfiguration fails with:
```
2022-09-11 13:18:08.186: (InfoEvent Severity.NORMAL) period_type=not-set event_id=dd5e3fdd-c041-4640-b820-733d0260ccef: message=Re-enable LDAP Authorization Configuration
sdcm.nemesis.ToggleLdapConfiguration: Unhandled exception in method <function Nemesis.disrupt_disable_enable_ldap_authorization at 0x7ff866c07250>
Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3660, in wrapper
    result = method(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1087, in disrupt_disable_enable_ldap_authorization
    create_ldap_container()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1069, in create_ldap_container
    self.tester.configure_ldap(self.tester.localhost)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 505, in configure_ldap
    self.localhost.add_ldap_entry(ip=ldap_address[0], ldap_port=ldap_address[1],
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/ldap.py", line 83, in add_ldap_entry
    LdapContainerMixin.ldap_conn.add(*ldap_entry)
  File "/usr/local/lib/python3.10/site-packages/ldap3/core/connection.py", line 1013, in add
    response = self.post_send_single_response(self.send('addRequest', request, controls))
  File "/usr/local/lib/python3.10/site-packages/ldap3/strategy/sync.py", line 160, in post_send_single_response
    responses, result = self.get_response(message_id)
  File "/usr/local/lib/python3.10/site-packages/ldap3/strategy/base.py", line 370, in get_response
    raise LDAPSessionTerminatedByServerError(self.connection.last_error)
ldap3.core.exceptions.LDAPSessionTerminatedByServerError: session terminated by server
```

[argus](https://argus.scylladb.com/test/02b92677-373f-4eb8-bde8-683559dc1812/runs?additionalRuns[]=b7442e7c-f645-40ff-bb73-e5053092944d)
## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Kernel Version: 5.15.0-1031-aws
Scylla version (or git commit hash): `2023.1.0~rc2-20230302.726f8a090337` with build-id `efcc950cda22875aa488c5295c6cc68f35d9cc6f`

Cluster size: 4 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- longevity-200gb-48h-verify-limited--db-node-b7442e7c-8 (34.243.190.148 | 10.4.2.228) (shards: 14)
- longevity-200gb-48h-verify-limited--db-node-b7442e7c-7 (34.243.250.71 | 10.4.3.49) (shards: 14)
- longevity-200gb-48h-verify-limited--db-node-b7442e7c-6 (52.213.23.42 | 10.4.0.118) (shards: 14)
- longevity-200gb-48h-verify-limited--db-node-b7442e7c-5 (3.252.208.68 | 10.4.0.192) (shards: 14)
- longevity-200gb-48h-verify-limited--db-node-b7442e7c-4 (54.73.96.156 | 10.4.1.135) (shards: 14)
- longevity-200gb-48h-verify-limited--db-node-b7442e7c-3 (52.18.238.130 | 10.4.0.20) (shards: 14)
- longevity-200gb-48h-verify-limited--db-node-b7442e7c-2 (3.253.12.18 | 10.4.0.93) (shards: 14)
- longevity-200gb-48h-verify-limited--db-node-b7442e7c-1 (3.252.250.28 | 10.4.3.176) (shards: 14)

OS / Image: `ami-0336a5a646b08dc25` (aws: eu-west-1)

Test: `features-ldap-authorization-longevity-200gb-48h-test`
Test id: `b7442e7c-f645-40ff-bb73-e5053092944d`
Test name: `enterprise-2023.1/SCT_Enterprise_Features/LDAP/features-ldap-authorization-longevity-200gb-48h-test`
Test config file(s):

- [longevity-200GB-48h-verifier-LimitedMonkey-tls.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/9a5f163455e77d1518d00ea2a5ac14df134cf2f6/test-cases/longevity/longevity-200GB-48h-verifier-LimitedMonkey-tls.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor b7442e7c-f645-40ff-bb73-e5053092944d`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=b7442e7c-f645-40ff-bb73-e5053092944d)
- Show all stored logs command: `$ hydra investigate show-logs b7442e7c-f645-40ff-bb73-e5053092944d`

## Logs:
- **db-cluster-b7442e7c.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b7442e7c-f645-40ff-bb73-e5053092944d/20230304_220638/db-cluster-b7442e7c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b7442e7c-f645-40ff-bb73-e5053092944d/20230304_220638/db-cluster-b7442e7c.tar.gz)
- **sct-runner-b7442e7c.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b7442e7c-f645-40ff-bb73-e5053092944d/20230304_220638/sct-runner-b7442e7c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b7442e7c-f645-40ff-bb73-e5053092944d/20230304_220638/sct-runner-b7442e7c.tar.gz)
- **monitor-set-b7442e7c.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b7442e7c-f645-40ff-bb73-e5053092944d/20230304_220638/monitor-set-b7442e7c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b7442e7c-f645-40ff-bb73-e5053092944d/20230304_220638/monitor-set-b7442e7c.tar.gz)
- **loader-set-b7442e7c.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b7442e7c-f645-40ff-bb73-e5053092944d/20230304_220638/loader-set-b7442e7c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b7442e7c-f645-40ff-bb73-e5053092944d/20230304_220638/loader-set-b7442e7c.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2023.1/job/SCT_Enterprise_Features/job/LDAP/job/features-ldap-authorization-longevity-200gb-48h-test/2/)
</details>

**Comment by fruch** [comment]
looks like more issue in that run:
```
2023-03-04 04:00:54.091 <2023-03-04 04:00:54.000>: (DatabaseLogEvent Severity.ERROR) period_type=one-time event_id=55eb2161-ceb1-496a-b5ff-7037449986a2 during_nemesis=AddRemoveDc: type=DATABASE_ERROR regex=(^ERROR|!\s*?ERR).*\[shard.*\] line_number=5698 node=longevity-200gb-48h-verify-limited--db-node-b7442e7c-7
2023-03-04T04:00:54+00:00 longevity-200gb-48h-verify-limited--db-node-b7442e7c-7      !ERR | scylla[5513]:  [shard  0] ldap_role_manager - error in reconnect: std::system_error (error system:111, Connection refused);
```

i.e. I don't think the LDAP servrer is expose to both regions, i.e. this add_dc nemesis might be a bit problematic in LDAP cases.

and for the original issue described here:
1) do we collect logs of the LDAP server we are running ?
2) do we have some status check of it ? to see it's up and running ?

**Comment by yarongilor** [comment]
> looks like more issue in that run:
> 
> ```
> 2023-03-04 04:00:54.091 <2023-03-04 04:00:54.000>: (DatabaseLogEvent Severity.ERROR) period_type=one-time event_id=55eb2161-ceb1-496a-b5ff-7037449986a2 during_nemesis=AddRemoveDc: type=DATABASE_ERROR regex=(^ERROR|!\s*?ERR).*\[shard.*\] line_number=5698 node=longevity-200gb-48h-verify-limited--db-node-b7442e7c-7
> 2023-03-04T04:00:54+00:00 longevity-200gb-48h-verify-limited--db-node-b7442e7c-7      !ERR | scylla[5513]:  [shard  0] ldap_role_manager - error in reconnect: std::system_error (error system:111, Connection refused);
> ```
> 
> i.e. I don't think the LDAP servrer is expose to both regions, i.e. this add_dc nemesis might be a bit problematic in LDAP cases.
> 
> and for the original issue described here:
> 
> 1. do we collect logs of the LDAP server we are running ?
> 2. do we have some status check of it ? to see it's up and running ?

@fruch , it's good points. i have a task for the second issue in: 
https://github.com/scylladb/qa-tasks/issues/1158
perhaps we can add some extra logging to our Ldap functions there, in order to cover item 1 as well.

**Comment by fgelcer** [comment]
> perhaps we can add some extra logging to our Ldap functions there, in order to cover item 1 as well.

indeed, before we destroy the docker container of our LDAP, we should run `docker logs --details <container_id>`, and add it to the node's log collection (we can sync it to the SCT runner if needed)
