### ISSUE TITLE
AddRemoveDc nemesis losing connection during rebuild 

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#6133]
Recently we started seeing rebuild getting retried

And retries were removed in: https://github.com/scylladb/scylla-cluster-tests/pull/6061

we are still seeing cases that rebuild is failing escpecily in add_remove_dc nemesis, and it's not clear why it's getting dissconnected 
i.e. rebuild is starting on the node (and then fails the cleanup decomission, leaving the node in place)

```
Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run
    return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
    result = connection.run(**command_kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
    return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 649, in _complete_run
    raise exception
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 77, in run
    self._read_output(self._session, self._channel, self._timeout,
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 105, in _read_output
    stdout_size, stdout_chunk = channel.read()
  File "ssh2/channel.pyx", line 116, in ssh2.channel.Channel.read
  File "ssh2/channel.pyx", line 144, in ssh2.channel.Channel.read_ex
  File "ssh2/utils.pyx", line 214, in ssh2.utils.handle_error_codes
ssh2.exceptions.SocketRecvError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3971, in disrupt_add_remove_dc
    new_node.run_nodetool(sub_cmd=f"rebuild -- {datacenters[0]}", retry=0)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2555, in run_nodetool
    self.remoter.run(cmd, timeout=timeout, ignore_status=ignore_status, verbose=verbose, retry=retry)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run
    result = _run()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 62, in inner
    return func(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 606, in _run
    if self._run_on_retryable_exception(exc, new_session):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_libssh_cmd_runner.py", line 78, in _run_on_retryable_exception
    raise RetryableNetworkException(str(exc), original=exc)
sdcm.remote.base.RetryableNetworkException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4375, in wrapper
    result = method(*args[1:], **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3986, in disrupt_add_remove_dc
    self.cluster.decommission(new_node)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 4632, in decommission
    node.run_nodetool("decommission", timeout=timeout, retry=0)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2555, in run_nodetool
    self.remoter.run(cmd, timeout=timeout, ignore_status=ignore_status, verbose=verbose, retry=retry)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run
    result = _run()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 62, in inner
    return func(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run
    return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
    result = connection.run(**command_kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
    return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 654, in _complete_run
    raise UnexpectedExit(result)
sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!

Command: "/usr/bin/nodetool -u cassandra -pw 'cassandra'  decommission "

Exit code: 1

Stdout:

nodetool: Scylla API server HTTP POST to URL '/storage_service/decommission' failed: std::runtime_error (Operation rebuild is in progress, try again)
See 'nodetool help' or 'nodetool help <command>'.

Stderr:
```

## Impact

we are failing to cleanup after this nemesis, i.e. a node in different region is left and not decommissioned

## How frequently does it reproduce?

happens almost every weekly run of 50gb case

## Installation details

Kernel Version: 5.15.0-1035-aws
Scylla version (or git commit hash): `5.3.0~dev-20230425.124153d43915` with build-id `c084d51a610cd0c9956abf5bed57fbd54301731c`

Cluster size: 6 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
- longevity-tls-50gb-3d-master-db-node-e54b587c-9 (184.72.66.80 | 10.12.8.114) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-e54b587c-8 (54.160.161.180 | 10.12.9.166) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-e54b587c-7 (54.83.112.20 | 10.12.11.96) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-e54b587c-6 (50.19.169.131 | 10.12.10.218) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-e54b587c-5 (3.82.57.165 | 10.12.11.202) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-e54b587c-4 (52.90.101.24 | 10.12.11.209) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-e54b587c-34 (52.91.218.46 | 10.12.9.132) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-e54b587c-33 (18.214.100.171 | 10.12.11.68) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-e54b587c-32 (54.173.10.82 | 10.12.9.204) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-e54b587c-31 (54.174.80.177 | 10.12.9.228) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-e54b587c-30 (54.90.107.239 | 10.12.11.65) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-e54b587c-3 (54.242.246.247 | 10.12.8.191) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-e54b587c-29 (54.196.179.157 | 10.12.9.110) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-e54b587c-28 (54.163.218.241 | 10.12.11.89) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-e54b587c-27 (18.232.170.107 | 10.12.9.197) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-e54b587c-26 (34.229.79.46 | 10.12.11.169) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-e54b587c-25 (54.204.201.6 | 10.12.10.192) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-e54b587c-24 (54.198.125.151 | 10.12.8.6) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-e54b587c-23 (54.234.12.29 | 10.12.10.37) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-e54b587c-22 (34.228.60.188 | 10.12.9.191) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-e54b587c-21 (54.167.58.36 | 10.12.11.146) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-e54b587c-20 (54.227.34.24 | 10.12.8.53) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-e54b587c-2 (54.160.154.84 | 10.12.10.198) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-e54b587c-19 (54.226.240.191 | 10.12.8.34) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-e54b587c-18 (34.233.123.181 | 10.12.10.207) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-e54b587c-17 (54.208.58.89 | 10.12.9.237) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-e54b587c-16 (54.197.37.118 | 10.12.11.250) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-e54b587c-15 (18.208.216.194 | 10.12.9.145) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-e54b587c-14 (54.160.231.179 | 10.12.11.220) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-e54b587c-13 (100.25.219.83 | 10.12.11.98) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-e54b587c-12 (54.167.85.50 | 10.12.8.143) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-e54b587c-11 (3.95.204.90 | 10.12.9.9) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-e54b587c-10 (54.234.38.41 | 10.12.8.187) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-e54b587c-1 (54.226.144.78 | 10.12.8.238) (shards: 14)

OS / Image: `ami-0594293f3fa584dd4` (aws: us-east-1)

Test: `longevity-50gb-3days-test`
Test id: `e54b587c-def5-4c06-b67e-21bba454c8c9`
Test name: `scylla-master/longevity/longevity-50gb-3days-test`
Test config file(s):

- [longevity-50GB-3days-authorization-and-tls-ssl.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/1d31a3941d1ba6c9ab69bc16f603aa1d36b70505/test-cases/longevity/longevity-50GB-3days-authorization-and-tls-ssl.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor e54b587c-def5-4c06-b67e-21bba454c8c9`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=e54b587c-def5-4c06-b67e-21bba454c8c9)
- Show all stored logs command: `$ hydra investigate show-logs e54b587c-def5-4c06-b67e-21bba454c8c9`

## Logs:
- **db-cluster-e54b587c.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e54b587c-def5-4c06-b67e-21bba454c8c9/20230508_045418/db-cluster-e54b587c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e54b587c-def5-4c06-b67e-21bba454c8c9/20230508_045418/db-cluster-e54b587c.tar.gz)
- **email_data-e54b587c.json.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e54b587c-def5-4c06-b67e-21bba454c8c9/20230508_045418/email_data-e54b587c.json.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e54b587c-def5-4c06-b67e-21bba454c8c9/20230508_045418/email_data-e54b587c.json.tar.gz)
- **output-e54b587c.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e54b587c-def5-4c06-b67e-21bba454c8c9/20230508_045418/output-e54b587c.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e54b587c-def5-4c06-b67e-21bba454c8c9/20230508_045418/output-e54b587c.log.tar.gz)
- **debug-e54b587c.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e54b587c-def5-4c06-b67e-21bba454c8c9/20230508_045418/debug-e54b587c.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e54b587c-def5-4c06-b67e-21bba454c8c9/20230508_045418/debug-e54b587c.log.tar.gz)
- **events-e54b587c.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e54b587c-def5-4c06-b67e-21bba454c8c9/20230508_045418/events-e54b587c.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e54b587c-def5-4c06-b67e-21bba454c8c9/20230508_045418/events-e54b587c.log.tar.gz)
- **normal-e54b587c.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e54b587c-def5-4c06-b67e-21bba454c8c9/20230508_045418/normal-e54b587c.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e54b587c-def5-4c06-b67e-21bba454c8c9/20230508_045418/normal-e54b587c.log.tar.gz)
- **argus-e54b587c.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e54b587c-def5-4c06-b67e-21bba454c8c9/20230508_045418/argus-e54b587c.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e54b587c-def5-4c06-b67e-21bba454c8c9/20230508_045418/argus-e54b587c.log.tar.gz)
- **raw_events-e54b587c.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e54b587c-def5-4c06-b67e-21bba454c8c9/20230508_045418/raw_events-e54b587c.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e54b587c-def5-4c06-b67e-21bba454c8c9/20230508_045418/raw_events-e54b587c.log.tar.gz)
- **critical-e54b587c.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e54b587c-def5-4c06-b67e-21bba454c8c9/20230508_045418/critical-e54b587c.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e54b587c-def5-4c06-b67e-21bba454c8c9/20230508_045418/critical-e54b587c.log.tar.gz)
- **warning-e54b587c.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e54b587c-def5-4c06-b67e-21bba454c8c9/20230508_045418/warning-e54b587c.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e54b587c-def5-4c06-b67e-21bba454c8c9/20230508_045418/warning-e54b587c.log.tar.gz)
- **summary-e54b587c.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e54b587c-def5-4c06-b67e-21bba454c8c9/20230508_045418/summary-e54b587c.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e54b587c-def5-4c06-b67e-21bba454c8c9/20230508_045418/summary-e54b587c.log.tar.gz)
- **left_processes-e54b587c.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e54b587c-def5-4c06-b67e-21bba454c8c9/20230508_045418/left_processes-e54b587c.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e54b587c-def5-4c06-b67e-21bba454c8c9/20230508_045418/left_processes-e54b587c.log.tar.gz)
- **error-e54b587c.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e54b587c-def5-4c06-b67e-21bba454c8c9/20230508_045418/error-e54b587c.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e54b587c-def5-4c06-b67e-21bba454c8c9/20230508_045418/error-e54b587c.log.tar.gz)
- **2023_05_05__03_08_38_479.sct-e54b587c.log.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e54b587c-def5-4c06-b67e-21bba454c8c9/20230508_045418/2023_05_05__03_08_38_479.sct-e54b587c.log.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e54b587c-def5-4c06-b67e-21bba454c8c9/20230508_045418/2023_05_05__03_08_38_479.sct-e54b587c.log.gz)
- **2023_05_06__20_20_23_889.sct-e54b587c.log.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e54b587c-def5-4c06-b67e-21bba454c8c9/20230508_045418/2023_05_06__20_20_23_889.sct-e54b587c.log.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e54b587c-def5-4c06-b67e-21bba454c8c9/20230508_045418/2023_05_06__20_20_23_889.sct-e54b587c.log.gz)
- **monitor-set-e54b587c.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e54b587c-def5-4c06-b67e-21bba454c8c9/20230508_045418/monitor-set-e54b587c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e54b587c-def5-4c06-b67e-21bba454c8c9/20230508_045418/monitor-set-e54b587c.tar.gz)
- **loader-set-e54b587c.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e54b587c-def5-4c06-b67e-21bba454c8c9/20230508_045418/loader-set-e54b587c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e54b587c-def5-4c06-b67e-21bba454c8c9/20230508_045418/loader-set-e54b587c.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-50gb-3days-test/193/)
</details>

**Comment by fruch** [comment]
happened again this week, but logs wasn't fully collected


## Installation details

Kernel Version: 5.15.0-1035-aws
Scylla version (or git commit hash): `5.3.0~dev-20230508.5fa459bd1a4a` with build-id `5d6a48f1aeb4a57ecbbb890013b0c3b2881ad268`




Cluster size: 6 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
- longevity-tls-50gb-3d-master-db-node-7d50d95d-9 (54.221.118.156 | 10.12.10.174) (shards: -1)
- longevity-tls-50gb-3d-master-db-node-7d50d95d-8 (54.87.20.65 | 10.12.9.217) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-7d50d95d-7 (54.91.61.190 | 10.12.10.225) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-7d50d95d-6 (23.22.141.201 | 10.12.11.111) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-7d50d95d-5 (23.20.89.121 | 10.12.11.250) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-7d50d95d-4 (18.234.31.240 | 10.12.8.56) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-7d50d95d-3 (35.175.177.223 | 10.12.8.108) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-7d50d95d-2 (100.24.47.136 | 10.12.10.243) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-7d50d95d-1 (3.95.211.196 | 10.12.10.27) (shards: 14)


OS / Image: `ami-0ed9f2084041b9abf` (aws: us-east-1)

Test: `longevity-50gb-3days-test`
Test id: `7d50d95d-f58a-426c-9e8a-db21ce30cd98`
Test name: `scylla-master/longevity/longevity-50gb-3days-test`
Test config file(s):

- [longevity-50GB-3days-authorization-and-tls-ssl.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/08f927dd885ce1fc5ad7b712138146d4434d1451/test-cases/longevity/longevity-50GB-3days-authorization-and-tls-ssl.yaml)


<details>
<summary>
Logs and commands
</summary>


- Restore Monitor Stack command: `$ hydra investigate show-monitor 7d50d95d-f58a-426c-9e8a-db21ce30cd98`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=7d50d95d-f58a-426c-9e8a-db21ce30cd98)
- Show all stored logs command: `$ hydra investigate show-logs 7d50d95d-f58a-426c-9e8a-db21ce30cd98`


## Logs:
*No logs captured during this run.*

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-50gb-3days-test/194/)
</details>

**Comment by fruch** [comment]
@soyacz can you take a closer look on what we can do to gather more information on this `ssh2.exceptions.SocketRecvError` failure ?

**Comment by roydahan** [comment]
@fruch isn't it a scylla issue?

**Comment by fruch** [comment]
> @fruch isn't it a scylla issue?

Not without proof, it's not 100% reproducible. we need a more focused reproducer to be able to show its scylla or not.

**Comment by fruch** [comment]
seems very similar to:
https://github.com/scylladb/scylladb/issues/11528#issuecomment-1365206311

we get a reactor stall and ssh get disconnected at the same time:
```
2023-05-07T09:23:31+00:00 longevity-tls-50gb-3d-master-db-node-e54b587c-24     !INFO | scylla[5484]: Reactor stalled for 32 ms on shard 9. Backtrace: 0x54adb03 0x54aceb0 0x54ae2df 0x3cb1f 0x547b2a4 0x547d73a 0x140b0d8 0x3f01000 0x3efedf2 0x3efe478 0x3f0352d 0x3f03184 0x54bec84 0x54bff07 0x54e24f1 0x548f0da 0x8b12c 0x10cbbf
2023-05-07T09:23:31+00:00 longevity-tls-50gb-3d-master-db-node-e54b587c-24     !INFO | scylla[5484]: kernel callstack:
2023-05-07T09:23:31+00:00 longevity-tls-50gb-3d-master-db-node-e54b587c-24     !INFO | scylla[5484]: Reactor stalled for 32 ms on shard 9. Backtrace: 0x54adb03 0x54aceb0 0x54ae2df 0x3cb1f 0x14d5949 0x16da4b5 0x16d80b6 0x3f00fe5 0x3efedf2 0x3efe478 0x3f0352d 0x3f03184 0x54bec84 0x54bff07 0x54e24f1 0x548f0da 0x8b12c 0x10cbbf
2023-05-07T09:23:31+00:00 longevity-tls-50gb-3d-master-db-node-e54b587c-24     !INFO | scylla[5484]: kernel callstack:
2023-05-07T09:23:32+00:00 longevity-tls-50gb-3d-master-db-node-e54b587c-24     !INFO | sshd[4636]: Bad packet length 3505249440.
2023-05-07T09:23:32+00:00 longevity-tls-50gb-3d-master-db-node-e54b587c-24     !INFO | sshd[4636]: ssh_dispatch_run_fatal: Connection from user scyllaadm 10.12.8.184 port 33874: message authentication code incorrect
```

it was consider a kernel issue, that we never identified it's source

**Comment by fruch** [comment]
> @fruch to workaround this problem, I propose to add `WaitForRebuildCompletes(node)` context manager which could be used around `run_nodetool('rebuild')` that would wait for rebuild to be completed regardless of exception (and log exception if happens). Ctx manager would get log marker and upon **exit** wait for rebuild finish WDYT?

it's a bit tricky, since I think the root cause is a kernel getting stuck, and breaking our SSH connection
those can happen right about anywhere, and ignoring it, means we won't find the root cause, and it would pop up somewhere else.

but if this context manager can serve as an example for more similar cases we might want guard

**Comment by fruch** [comment]
> I don't understand why we try to solve it in SCT and not in scylla.
> 

It's not fixing the issue, it's more about recovering from it.

The actual issue is open on Scylla, but I don't see it getting fixed since the root cause is yet unclear.

**Comment by fruch** [comment]
> > I don't understand why we try to solve it in SCT and not in scylla.
> > 
> 
> It's not fixing the issue, it's more about recovering from it.
> 
> The actual issue is open on Scylla, but I don't see it getting fixed since the root cause is yet unclear.

This has same side effect as in: 
https://github.com/scylladb/scylladb/issues/11528

Our ssh connection gets broken with a bad packet same time there is a reactor stall

**Comment by Mark-Gurevich** [comment]
Reproduced 2 times on longevity-10gb-3h-gce-test.

## Issue description
- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

*Describe your issue in detail and steps it took to produce it.*

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?
Happened on longevity-10gb-3h-gce-test.
Reproduced in builds 139 and 141

## Installation details

Kernel Version: 5.19.0-1022-gcp
Scylla version (or git commit hash): `2023.2.0~dev-20230427.e4ffb1fcf18f` with build-id `6233f9b12c6c2204bcbc461bfe8c69d8f65811a5`


Cluster size: 6 nodes (n1-highmem-16)

Scylla Nodes used in this run:
- longevity-10gb-3h-master-db-node-6813e59a-0-9 (34.23.235.237 | 10.142.0.121) (shards: 14)
- longevity-10gb-3h-master-db-node-6813e59a-0-8 (104.196.34.37 | 10.142.0.82) (shards: 14)
- longevity-10gb-3h-master-db-node-6813e59a-0-7 (34.148.110.69 | 10.142.0.120) (shards: 14)
- longevity-10gb-3h-master-db-node-6813e59a-0-6 (35.227.41.197 | 10.142.0.83) (shards: 14)
- longevity-10gb-3h-master-db-node-6813e59a-0-5 (34.138.49.30 | 10.142.0.48) (shards: 14)
- longevity-10gb-3h-master-db-node-6813e59a-0-4 (34.74.25.241 | 10.142.0.46) (shards: 14)
- longevity-10gb-3h-master-db-node-6813e59a-0-3 (34.138.61.133 | 10.142.0.45) (shards: 14)
- longevity-10gb-3h-master-db-node-6813e59a-0-2 (35.237.98.220 | 10.142.0.44) (shards: 14)
- longevity-10gb-3h-master-db-node-6813e59a-0-10 (34.75.150.20 | 10.142.0.125) (shards: 14)
- longevity-10gb-3h-master-db-node-6813e59a-0-1 (34.75.205.211 | 10.142.0.43) (shards: 14)


OS / Image: `https://www.googleapis.com/compute/v1/projects/scylla-images/global/images/900493631077932048` (gce: us-east1)

Test: `longevity-10gb-3h-gce-test`
Test id: `6813e59a-bfbb-46c9-92f5-a8f07246108a`
Test name: `scylla-enterprise/longevity/longevity-10gb-3h-gce-test`
Test config file(s):

- [longevity-10gb-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/a8da7cf7c837c115ea01c60a71348358616f890f/test-cases/longevity/longevity-10gb-3h.yaml)


<details>
<summary>
Logs and commands
</summary>


- Restore Monitor Stack command: `$ hydra investigate show-monitor 6813e59a-bfbb-46c9-92f5-a8f07246108a`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=6813e59a-bfbb-46c9-92f5-a8f07246108a)
- Show all stored logs command: `$ hydra investigate show-logs 6813e59a-bfbb-46c9-92f5-a8f07246108a`


## Logs:
- **db-cluster-6813e59a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/6813e59a-bfbb-46c9-92f5-a8f07246108a/20230428_110704/db-cluster-6813e59a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/6813e59a-bfbb-46c9-92f5-a8f07246108a/20230428_110704/db-cluster-6813e59a.tar.gz)
- **sct-runner-events-6813e59a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/6813e59a-bfbb-46c9-92f5-a8f07246108a/20230428_110704/sct-runner-events-6813e59a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/6813e59a-bfbb-46c9-92f5-a8f07246108a/20230428_110704/sct-runner-events-6813e59a.tar.gz)
- **sct-6813e59a.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/6813e59a-bfbb-46c9-92f5-a8f07246108a/20230428_110704/sct-6813e59a.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/6813e59a-bfbb-46c9-92f5-a8f07246108a/20230428_110704/sct-6813e59a.log.tar.gz)
- **monitor-set-6813e59a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/6813e59a-bfbb-46c9-92f5-a8f07246108a/20230428_110704/monitor-set-6813e59a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/6813e59a-bfbb-46c9-92f5-a8f07246108a/20230428_110704/monitor-set-6813e59a.tar.gz)
- **loader-set-6813e59a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/6813e59a-bfbb-46c9-92f5-a8f07246108a/20230428_110704/loader-set-6813e59a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/6813e59a-bfbb-46c9-92f5-a8f07246108a/20230428_110704/loader-set-6813e59a.tar.gz)
- **parallel-timelines-report-6813e59a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/6813e59a-bfbb-46c9-92f5-a8f07246108a/20230428_110704/parallel-timelines-report-6813e59a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/6813e59a-bfbb-46c9-92f5-a8f07246108a/20230428_110704/parallel-timelines-report-6813e59a.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-enterprise/job/longevity/job/longevity-10gb-3h-gce-test/139/)
[Argus](https://argus.scylladb.com/test/96abf9ef-b4bb-4c5f-bc48-7ba439312908/runs?additionalRuns[]=6813e59a-bfbb-46c9-92f5-a8f07246108a)
</details>

**Comment by fruch** [comment]
> Reproduced 2 times on longevity-10gb-3h-gce-test.
> 
> ## How frequently does it reproduce?
> Happened on longevity-10gb-3h-gce-test. Reproduced in builds 139 and 141
> 
> ## Installation details
> Kernel Version: 5.19.0-1022-gcp Scylla version (or git commit hash): `2023.2.0~dev-20230427.e4ffb1fcf18f` with build-id `6233f9b12c6c2204bcbc461bfe8c69d8f65811a5`
> 
> Cluster size: 6 nodes (n1-highmem-16)
> 
> Scylla Nodes used in this run:
> 
> * longevity-10gb-3h-master-db-node-6813e59a-0-9 (34.23.235.237 | 10.142.0.121) (shards: 14)
> * longevity-10gb-3h-master-db-node-6813e59a-0-8 (104.196.34.37 | 10.142.0.82) (shards: 14)
> * longevity-10gb-3h-master-db-node-6813e59a-0-7 (34.148.110.69 | 10.142.0.120) (shards: 14)
> * longevity-10gb-3h-master-db-node-6813e59a-0-6 (35.227.41.197 | 10.142.0.83) (shards: 14)
> * longevity-10gb-3h-master-db-node-6813e59a-0-5 (34.138.49.30 | 10.142.0.48) (shards: 14)
> * longevity-10gb-3h-master-db-node-6813e59a-0-4 (34.74.25.241 | 10.142.0.46) (shards: 14)
> * longevity-10gb-3h-master-db-node-6813e59a-0-3 (34.138.61.133 | 10.142.0.45) (shards: 14)
> * longevity-10gb-3h-master-db-node-6813e59a-0-2 (35.237.98.220 | 10.142.0.44) (shards: 14)
> * longevity-10gb-3h-master-db-node-6813e59a-0-10 (34.75.150.20 | 10.142.0.125) (shards: 14)
> * longevity-10gb-3h-master-db-node-6813e59a-0-1 (34.75.205.211 | 10.142.0.43) (shards: 14)
> 
> OS / Image: `https://www.googleapis.com/compute/v1/projects/scylla-images/global/images/900493631077932048` (gce: us-east1)
> 
> Test: `longevity-10gb-3h-gce-test` Test id: `6813e59a-bfbb-46c9-92f5-a8f07246108a` Test name: `scylla-enterprise/longevity/longevity-10gb-3h-gce-test` Test config file(s):
> 
> * [longevity-10gb-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/a8da7cf7c837c115ea01c60a71348358616f890f/test-cases/longevity/longevity-10gb-3h.yaml)
> 
> Logs and commands

The issue with AddRemoveDc looks similar, but you have anthoer case rebuild didn't really manged to connect, I think it's a different issue 
```
2023-04-28T07:50:48+00:00 longevity-10gb-3h-master-db-node-6813e59a-0-7     !INFO | sshd[2600]: Bad packet length 2870181173.
2023-04-28T07:50:48+00:00 longevity-10gb-3h-master-db-node-6813e59a-0-7     !INFO | sshd[2600]: ssh_dispatch_run_fatal: Connection from user scylla-test 10.142.0.41 port 55278: message
```

**Comment by fruch** [comment]
@mykaul seems like we enough enough occurrences of this exactly during rebuild of a new node in a new region, and seen on AWS and GCP

can you transfer this one to scylla-core ?

**Comment by roydahan** [comment]
@fruch I can move, but can you please edit the title and the original description 3 first lines to explain the issue exactly.
