### ISSUE TITLE
[unittest] TestMBM.test_execute_mbm_from_cli once in a while with no clear reason

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#6144]
```
17:38:23  ______________________ TestMBM.test_execute_mbm_from_cli _______________________
17:38:23  
17:38:23  self = <unit_tests.test_microbenchmarking.TestMBM testMethod=test_execute_mbm_from_cli>
17:38:23  
17:38:23      def test_execute_mbm_from_cli(self):
17:38:23          result_path = os.path.join(os.path.dirname(__file__), 'test_data/test_microbenchmarking/PFF_with_AVGAIO')
17:38:23          html_report = tempfile.mkstemp(suffix=".html", prefix="microbenchmarking-")[1]
17:38:23          with subprocess.Popen(['./microbenchmarking.py', 'check',
17:38:23                                 '--results-path', result_path,
17:38:23                                 '--email-recipients', 'alex.bykov@scylladb.com',
17:38:23                                 '--report-path', html_report,
17:38:23                                 '--hostname', self.mbra.hostname],
17:38:23                                cwd=self.cwd,
17:38:23                                stdout=subprocess.PIPE,
17:38:23                                stderr=subprocess.PIPE) as ps:
17:38:23              stdout, _ = ps.communicate()
17:38:23              print(_)
17:38:23              print(stdout)
17:38:23  >           self.assertEqual(ps.returncode, 0)
17:38:23  E           AssertionError: 1 != 0
17:38:23  
17:38:23  unit_tests/test_microbenchmarking.py:281: AssertionError
17:38:23  ----------------------------- Captured stdout call -----------------------------
17:38:23  b'/usr/local/lib/python3.10/site-packages/elasticsearch/connection/http_urllib3.py:209: UserWarning: Connecting to https://746f0ad652a3447d83b1572f657c67cb.us-east-1.aws.found.io:9243/ using SSL with verify_certs=False is insecure.\n  warnings.warn(\nTraceback (most recent call last):\n  File "/tmp/jenkins/workspace/can_scylla-cluster-tests_PR-6137/sdcm/./microbenchmarking.py", line 574, in <module>\n    main(ARGS)\n  File "/tmp/jenkins/workspace/can_scylla-cluster-tests_PR-6137/sdcm/./microbenchmarking.py", line 526, in main\n    report_results = mbra.check_regression(results)\n  File "/tmp/jenkins/workspace/can_scylla-cluster-tests_PR-6137/sdcm/./microbenchmarking.py", line 135, in check_regression\n    assert tests_filtered, "No results from DB"\nAssertionError: No results from DB\n'
17:38:23  b'Found credentials in environment variables.\n/tmp/jenkins/workspace/can_scylla-cluster-tests_PR-6137/unit_tests/test_data/test_microbenchmarking/PFF_with_AVGAIO/perf_fast_forward_output\n/tmp/jenkins/workspace/can_scylla-cluster-tests_PR-6137/unit_tests/test_data/test_microbenchmarking/PFF_with_AVGAIO/perf_fast_forward_output/large-partition-forwarding\n/tmp/jenkins/workspace/can_scylla-cluster-tests_PR-6137/unit_tests/test_data/test_microbenchmarking/PFF_with_AVGAIO/perf_fast_forward_output/large-partition-forwarding/large-part-ds1\nDataset name: large-part-ds1\nTest set: large-partition-forwarding\nReading: large-partition-forwarding/large-part-ds1/no.1.json\nReading: large-partition-forwarding/large-part-ds1/yes.1.json\n/tmp/jenkins/workspace/can_scylla-cluster-tests_PR-6137/unit_tests/test_data/test_microbenchmarking/PFF_with_AVGAIO/perf_fast_forward_output/small-partition-slicing\n/tmp/jenkins/workspace/can_scylla-cluster-tests_PR-6137/unit_tests/test_data/test_microbenchmarking/PFF_with_AVGAIO/perf_fast_forward_output/small-partition-slicing/small-part\nDataset name: small-part\nTest set: small-partition-slicing\nReading: small-partition-slicing/small-part/500000-4096.1.json\nReading: small-partition-slicing/small-part/0-256.1.json\nGET https://746f0ad652a3447d83b1572f657c67cb.us-east-1.aws.found.io:9243/ [status:200 request:0.225s]\nPOST https://746f0ad652a3447d83b1572f657c67cb.us-east-1.aws.found.io:9243/microbenchmarkingv2/_search?q=hostname%3A%27godzilla.cloudius-systems.com%27+AND+versions.scylla-server.version%3A3.1%2A+AND+%28%28-_exists_%3Aexcluded%29+OR+%28excluded%3Afalse%29%29&filter_path=hits.hits._id%2Chits.hits._source.test_args%2Chits.hits.test_group_properties.name%2Chits.hits._source.hostname%2Chits.hits._source.test_run_date%2Chits.hits._source.test_group_properties.name%2Chits.hits._source.results.stats.aio%2Chits.hits._source.results.stats.avg+aio%2Chits.hits._source.results.stats.cpu%2Chits.hits._source.results.stats.time+%28s%29%2Chits.hits._source.results.stats.frag%2Fs%2Chits.hits._source.versions%2Chits.hits._source.excluded [status:200 request:0.093s]\n'
```
https://jenkins.scylladb.com/job/sct-github-PRs-scan/job/scylla-cluster-tests/job/PR-6137/17/execution/node/36/log/

**Comment by fruch** [comment]
the url does come back empty:

https://746f0ad652a3447d83b1572f657c67cb.us-east-1.aws.found.io:9243/microbenchmarkingv2/_search?q=hostname%3A%27godzilla.cloudius-systems.com%27+AND+versions.scylla-server.version%3A3.1%2A+AND+%28%28-_exists_%3Aexcluded%29+OR+%28excluded%3Afalse%29%29&filter_path=hits.hits._id%2Chits.hits._source.test_args%2Chits.hits.test_group_properties.name%2Chits.hits._source.hostname%2Chits.hits._source.test_run_date%2Chits.hits._source.test_group_properties.name%2Chits.hits._source.results.stats.aio%2Chits.hits._source.results.stats.avg+aio%2Chits.hits._source.results.stats.cpu%2Chits.hits._source.results.stats.time+%28s%29%2Chits.hits._source.results.stats.frag%2Fs%2Chits.hits._source.versions%2Chits.hits._source.excluded

looks like it's looking for scylla version 3.1 ? @aleksbykov  @temichus did we cleared some results out of it ?

**Comment by aleksbykov** [comment]
I didn't
@roydahan did you clear something?

**Comment by aleksbykov** [comment]
will prepare a fix for them
