### ISSUE TITLE
get nodetool status ends with KeyError: 'us-east1-b` in EKS test

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#6224]
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

In scylla-operator eks test, during nodes setup error appeared:
```
< t:2023-06-03 23:47:06,349 f:base.py         l:222  c:KubernetesCmdRunner  p:DEBUG > Datacenter: us-east1-b
< t:2023-06-03 23:47:06,661 f:base.py         l:222  c:KubernetesCmdRunner  p:DEBUG > ======================
< t:2023-06-03 23:47:06,661 f:base.py         l:222  c:KubernetesCmdRunner  p:DEBUG > Status=Up/Down
< t:2023-06-03 23:47:06,662 f:base.py         l:222  c:KubernetesCmdRunner  p:DEBUG > |/ State=Normal/Leaving/Joining/Moving
< t:2023-06-03 23:47:06,903 f:base.py         l:222  c:KubernetesCmdRunner  p:DEBUG > --  Address         Load       Tokens       Owns    Host ID                               Rack
< t:2023-06-03 23:47:06,913 f:base.py         l:142  c:KubernetesCmdRunner  p:DEBUG > Command "/usr/bin/nodetool  status " finished with status 0
< t:2023-06-03 23:47:06,914 f:cluster.py      l:2554 c:sdcm.cluster         p:DEBUG > Node sct-cluster-us-east1-b-us-east1-0 [10.0.0.36 | 10.0.1.131] (seed: False): Command '/usr/bin/nodetool  status ' duration -> 2.0735297870000977 s
< t:2023-06-03 23:47:07,368 f:cluster.py      l:3209 c:sdcm.cluster         p:ERROR > Failed to get nodes status from node Node sct-cluster-us-east1-b-us-east1-0 [10.0.0.36 | 10.0.1.131] (seed: False)
< t:2023-06-03 23:47:07,405 f:tester.py       l:172  c:sdcm.tester          p:ERROR > Exception in setUp. Will call tearDown < t:2023-06-03 23:47:07,405 f:tester.py       l:172  c:sdcm.tester          p:ERROR > Exception in setUp. Will call tearDown
< t:2023-06-03 23:47:07,405 f:tester.py       l:172  c:sdcm.tester          p:ERROR > Traceback (most recent call last):
< t:2023-06-03 23:47:07,405 f:tester.py       l:172  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 165, in wrapper
< t:2023-06-03 23:47:07,405 f:tester.py       l:172  c:sdcm.tester          p:ERROR >     return method(*args, **kwargs)
< t:2023-06-03 23:47:07,405 f:tester.py       l:172  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 116, in inner
< t:2023-06-03 23:47:07,405 f:tester.py       l:172  c:sdcm.tester          p:ERROR >     res = func(*args, **kwargs)
< t:2023-06-03 23:47:07,405 f:tester.py       l:172  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 826, in setUp
< t:2023-06-03 23:47:07,405 f:tester.py       l:172  c:sdcm.tester          p:ERROR >     self.set_system_auth_rf(db_cluster=db_cluster)
< t:2023-06-03 23:47:07,405 f:tester.py       l:172  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 900, in set_system_auth_rf
< t:2023-06-03 23:47:07,405 f:tester.py       l:172  c:sdcm.tester          p:ERROR >     datacenters.update({dc_by_region[region]: len(nodes_by_region[region])})
< t:2023-06-03 23:47:07,405 f:tester.py       l:172  c:sdcm.tester          p:ERROR > KeyError: 'us-east1-b'
< t:2023-06-03 23:47:07,407 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 2023-06-03 23:47:07.405: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=64fc9c69-d0db-46bf-9a47-2f12dcc70219, source=LongevityTest.SetUp()
< t:2023-06-03 23:47:07,407 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > exception='us-east1-b'
```
Looks like we didn't get any row with scylla nodes for datacenter. Previous `nodetool status` command executed right before was working without issues.

## Impact

failed test on cluster setup and failing the test.

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Cluster size: 4 nodes (i3.4xlarge)

Scylla Nodes used in this run:
**No resources left at the end of the run**

OS / Image: `` (k8s-eks: undefined_region)

Test: `longevity-scylla-operator-basic-12h-eks`
Test id: `391ae062-079f-44c6-8432-ee9d93aa736d`
Test name: `scylla-operator/operator-master/eks/longevity-scylla-operator-basic-12h-eks`
Test config file(s):

- [longevity-scylla-operator-basic-12h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/bf744770ce5797ed2a164edf551160fc5e5e4646/test-cases/scylla-operator/longevity-scylla-operator-basic-12h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 391ae062-079f-44c6-8432-ee9d93aa736d`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=391ae062-079f-44c6-8432-ee9d93aa736d)
- Show all stored logs command: `$ hydra investigate show-logs 391ae062-079f-44c6-8432-ee9d93aa736d`

## Logs:
- **db-cluster-391ae062.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/391ae062-079f-44c6-8432-ee9d93aa736d/20230603_234901/db-cluster-391ae062.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/391ae062-079f-44c6-8432-ee9d93aa736d/20230603_234901/db-cluster-391ae062.tar.gz)
- **sct-runner-events-391ae062.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/391ae062-079f-44c6-8432-ee9d93aa736d/20230603_234901/sct-runner-events-391ae062.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/391ae062-079f-44c6-8432-ee9d93aa736d/20230603_234901/sct-runner-events-391ae062.tar.gz)
- **sct-391ae062.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/391ae062-079f-44c6-8432-ee9d93aa736d/20230603_234901/sct-391ae062.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/391ae062-079f-44c6-8432-ee9d93aa736d/20230603_234901/sct-391ae062.log.tar.gz)
- **monitor-set-391ae062.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/391ae062-079f-44c6-8432-ee9d93aa736d/20230603_234901/monitor-set-391ae062.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/391ae062-079f-44c6-8432-ee9d93aa736d/20230603_234901/monitor-set-391ae062.tar.gz)
- **kubernetes-391ae062.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/391ae062-079f-44c6-8432-ee9d93aa736d/20230603_234901/kubernetes-391ae062.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/391ae062-079f-44c6-8432-ee9d93aa736d/20230603_234901/kubernetes-391ae062.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-operator/job/operator-master/job/eks/job/longevity-scylla-operator-basic-12h-eks/66/)
[Argus](https://argus.scylladb.com/test/c3f68ac3-b7cf-4ac8-8cf4-270db06f0e14/runs?additionalRuns[]=391ae062-079f-44c6-8432-ee9d93aa736d)
</details>

**Comment by soyacz** [comment]
I don't know if it still reproduces. Reopen if happens again.
