### ISSUE TITLE
`disrupt_resetlocalschema` nemesis fails in 14 clients K8S setup

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-cluster-tests#6229]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master
* **scylla**: `5.2.1-20230508.f1c45553bc29`

### Logs
* test_id: 89e9b8a0-ec21-4198-b129-a3ae7cfc3fa1
* job log: https://argus.scylladb.com/test/83ae89e2-4917-4171-bb28-b54a6594c727/runs?additionalRuns[]=89e9b8a0-ec21-4198-b129-a3ae7cfc3fa1

### Description

Running 14 tenants longevity test on K8S the `disrupt_resetlocalschema` nemesis fails 16/17 times with the following error:
```
Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4425, in wrapper
    result = method(*args[1:], **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 833, in disrupt_resetlocalschema
    assert wait_for(
AssertionError: Schema version has not been recalculated
```

### Steps to Reproduce

1. Run 14 clients longevity test with the `disrupt_resetlocalschema` nemesis
2. See error

**Expected behavior:** The `disrupt_resetlocalschema` nemesis must pass

**Actual behavior:** It fails

**Comment by fruch** [comment]
One of two option or 30sec isn't enough
or it's again a nemesis base on node log, and we don't have it working stable enough
