### ISSUE TITLE
Events process EventsAnalyzer is still alive after timeout

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#6232]
## Issue description

- [ ] This issue is a regression.
- [x] It is unknown if this issue is a regression.

during teardown `EventsAnalyzer` doesn't seem to stop correctly:
```
2023-06-08 10:01:27.662: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=f0b75a5e-07b5-409d-84c7-e991bb1591e5 during_nemesis=RemoveNodeThenAddNode, source=LongevityTest.stop_event_analyzer() message=stop_event_analyzer (silenced) failed with:
exception=Events process EventsAnalyzer is still alive after timeout
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/./sct.py", line 1729, in <module>
cli.main(prog_name="hydra")
File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
rv = self.invoke(ctx)
File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
return __callback(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/./sct.py", line 1104, in run_test
unittest.main(module=None, argv=['python -m unittest', argv],
File "/usr/local/lib/python3.10/unittest/main.py", line 101, in __init__
self.runTests()
File "/usr/local/lib/python3.10/unittest/main.py", line 271, in runTests
self.result = testRunner.run(self.test)
File "/usr/local/lib/python3.10/unittest/runner.py", line 176, in run
test(result)
File "/usr/local/lib/python3.10/unittest/suite.py", line 84, in __call__
return self.run(*args, **kwds)
File "/usr/local/lib/python3.10/unittest/suite.py", line 122, in run
test(result)
File "/usr/local/lib/python3.10/unittest/suite.py", line 84, in __call__
return self.run(*args, **kwds)
File "/usr/local/lib/python3.10/unittest/suite.py", line 122, in run
test(result)
File "/usr/local/lib/python3.10/unittest/case.py", line 650, in __call__
return self.run(*args, **kwds)
File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 673, in run
result = super().run(self.result)
File "/usr/local/lib/python3.10/unittest/case.py", line 594, in run
self._callTearDown()
File "/usr/local/lib/python3.10/unittest/case.py", line 552, in _callTearDown
self.tearDown()
File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 2823, in tearDown
self.stop_event_analyzer()
File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 222, in decor
self._store_test_result(args[0], exc, exc.__traceback__, name)
```

## Impact

test is mark as failed, event nothing in the scylla under test has failed

## How frequently does it reproduce?

seen once 

## Installation details

Kernel Version: 5.15.0-1039-azure
Scylla version (or git commit hash): `5.4.0~dev-20230608.ce6a1ca13b59` with build-id `338ed34c5123d64cbe4a8152c87776a62a11fc97`

Cluster size: 6 nodes (Standard_L8s_v3)

Scylla Nodes used in this run:
- longevity-10gb-3h-master-db-node-6060fa74-eastus-9 (23.101.129.105 | 10.0.0.9) (shards: 7)
- longevity-10gb-3h-master-db-node-6060fa74-eastus-8 (172.173.156.230 | 10.0.0.14) (shards: 7)
- longevity-10gb-3h-master-db-node-6060fa74-eastus-7 (172.174.59.79 | 10.0.0.10) (shards: 7)
- longevity-10gb-3h-master-db-node-6060fa74-eastus-6 (172.171.198.243 | 10.0.0.10) (shards: 7)
- longevity-10gb-3h-master-db-node-6060fa74-eastus-5 (172.171.218.142 | 10.0.0.9) (shards: 7)
- longevity-10gb-3h-master-db-node-6060fa74-eastus-4 (172.171.196.242 | 10.0.0.8) (shards: 7)
- longevity-10gb-3h-master-db-node-6060fa74-eastus-3 (20.232.195.169 | 10.0.0.7) (shards: 7)
- longevity-10gb-3h-master-db-node-6060fa74-eastus-2 (172.171.222.231 | 10.0.0.6) (shards: 7)
- longevity-10gb-3h-master-db-node-6060fa74-eastus-12 (172.190.7.189 | 10.0.0.10) (shards: 7)
- longevity-10gb-3h-master-db-node-6060fa74-eastus-11 (172.190.63.192 | 10.0.0.8) (shards: 7)
- longevity-10gb-3h-master-db-node-6060fa74-eastus-10 (20.168.200.14 | 10.0.0.6) (shards: 7)
- longevity-10gb-3h-master-db-node-6060fa74-eastus-1 (20.172.214.134 | 10.0.0.5) (shards: 7)

OS / Image: `null` (azure: undefined_region)

Test: `longevity-10gb-3h-azure-test`
Test id: `6060fa74-a389-47e2-a487-55182f419ff6`
Test name: `scylla-master/longevity/longevity-10gb-3h-azure-test`
Test config file(s):

- [longevity-10gb-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/405f9eb84957c57b523278545ea1e06809079bc3/test-cases/longevity/longevity-10gb-3h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 6060fa74-a389-47e2-a487-55182f419ff6`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=6060fa74-a389-47e2-a487-55182f419ff6)
- Show all stored logs command: `$ hydra investigate show-logs 6060fa74-a389-47e2-a487-55182f419ff6`

## Logs:
- **db-cluster-6060fa74.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/6060fa74-a389-47e2-a487-55182f419ff6/20230608_102903/db-cluster-6060fa74.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/6060fa74-a389-47e2-a487-55182f419ff6/20230608_102903/db-cluster-6060fa74.tar.gz)
- **sct-runner-events-6060fa74.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/6060fa74-a389-47e2-a487-55182f419ff6/20230608_102903/sct-runner-events-6060fa74.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/6060fa74-a389-47e2-a487-55182f419ff6/20230608_102903/sct-runner-events-6060fa74.tar.gz)
- **sct-6060fa74.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/6060fa74-a389-47e2-a487-55182f419ff6/20230608_102903/sct-6060fa74.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/6060fa74-a389-47e2-a487-55182f419ff6/20230608_102903/sct-6060fa74.log.tar.gz)
- **monitor-set-6060fa74.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/6060fa74-a389-47e2-a487-55182f419ff6/20230608_102903/monitor-set-6060fa74.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/6060fa74-a389-47e2-a487-55182f419ff6/20230608_102903/monitor-set-6060fa74.tar.gz)
- **loader-set-6060fa74.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/6060fa74-a389-47e2-a487-55182f419ff6/20230608_102903/loader-set-6060fa74.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/6060fa74-a389-47e2-a487-55182f419ff6/20230608_102903/loader-set-6060fa74.tar.gz)
- **parallel-timelines-report-6060fa74.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/6060fa74-a389-47e2-a487-55182f419ff6/20230608_102903/parallel-timelines-report-6060fa74.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/6060fa74-a389-47e2-a487-55182f419ff6/20230608_102903/parallel-timelines-report-6060fa74.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-10gb-3h-azure-test/199/)
[Argus](https://argus.scylladb.com/test/aa05fe67-89bd-4e30-88db-5e2b2e3d986d/runs?additionalRuns[]=6060fa74-a389-47e2-a487-55182f419ff6)
</details>

                            

```[tasklist]
### Tasks
```

**Comment by ShlomiBalalis** [comment]
The issue was reproduced in a manager 3.1 job:
Event though there was no error/critical event in the run, the teardown failed with the following traceback:
```
2023-06-08 10:01:27.662: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=f0b75a5e-07b5-409d-84c7-e991bb1591e5 during_nemesis=RemoveNodeThenAddNode, source=LongevityTest.stop_event_analyzer() message=stop_event_analyzer (silenced) failed with:
exception=Events process EventsAnalyzer is still alive after timeout
Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/./sct.py", line 1729, in <module>
    cli.main(prog_name="hydra")
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/./sct.py", line 1104, in run_test
    unittest.main(module=None, argv=['python -m unittest', argv],
  File "/usr/local/lib/python3.10/unittest/main.py", line 101, in __init__
    self.runTests()
  File "/usr/local/lib/python3.10/unittest/main.py", line 271, in runTests
    self.result = testRunner.run(self.test)
  File "/usr/local/lib/python3.10/unittest/runner.py", line 176, in run
    test(result)
  File "/usr/local/lib/python3.10/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/local/lib/python3.10/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/local/lib/python3.10/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/local/lib/python3.10/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/local/lib/python3.10/unittest/case.py", line 650, in __call__
    return self.run(*args, **kwds)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 673, in run
    result = super().run(self.result)
  File "/usr/local/lib/python3.10/unittest/case.py", line 594, in run
    self._callTearDown()
  File "/usr/local/lib/python3.10/unittest/case.py", line 552, in _callTearDown
    self.tearDown()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 2823, in tearDown
    self.stop_event_analyzer()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 222, in decor
    self._store_test_result(args[0], exc, exc.__traceback__, name)
```


[Build url](https://jenkins.scylladb.com/view/scylla-manager/job/manager-3.1/job/centos-sanity-ipv6-test/15/)
Logs:
[db-cluster - https://cloudius-jenkins-test.s3.amazonaws.com/cf548911-8fc7-49c4-aca2-d08d9cc3f080/20230704_163326/db-cluster-cf548911.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cf548911-8fc7-49c4-aca2-d08d9cc3f080/20230704_163326/db-cluster-cf548911.tar.gz)
[loader-set - https://cloudius-jenkins-test.s3.amazonaws.com/cf548911-8fc7-49c4-aca2-d08d9cc3f080/20230704_163326/loader-set-cf548911.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cf548911-8fc7-49c4-aca2-d08d9cc3f080/20230704_163326/loader-set-cf548911.tar.gz)
[monitor-set - https://cloudius-jenkins-test.s3.amazonaws.com/cf548911-8fc7-49c4-aca2-d08d9cc3f080/20230704_163326/monitor-set-cf548911.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cf548911-8fc7-49c4-aca2-d08d9cc3f080/20230704_163326/monitor-set-cf548911.tar.gz)
[sct - https://cloudius-jenkins-test.s3.amazonaws.com/cf548911-8fc7-49c4-aca2-d08d9cc3f080/20230704_163326/sct-runner-cf548911.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cf548911-8fc7-49c4-aca2-d08d9cc3f080/20230704_163326/sct-runner-cf548911.tar.gz)

**Comment by ShlomiBalalis** [comment]
Happened again in a manager job:
## Issue description

```
2023-08-16 15:49:05.528: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=61f706f5-9352-4d85-89f6-c57a54316f8b, source=MgmtCliTest.stop_event_analyzer() message=stop_event_analyzer (silenced) failed with:
exception=Events process EventsAnalyzer is still alive after timeout
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/./sct.py", line 1742, in <module>
cli.main(prog_name="hydra")
File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
rv = self.invoke(ctx)
File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
return __callback(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/./sct.py", line 1106, in run_test
unittest.main(module=None, argv=['python -m unittest', argv],
File "/usr/local/lib/python3.10/unittest/main.py", line 101, in __init__
self.runTests()
File "/usr/local/lib/python3.10/unittest/main.py", line 271, in runTests
self.result = testRunner.run(self.test)
File "/usr/local/lib/python3.10/unittest/runner.py", line 184, in run
test(result)
File "/usr/local/lib/python3.10/unittest/suite.py", line 84, in __call__
return self.run(*args, **kwds)
File "/usr/local/lib/python3.10/unittest/suite.py", line 122, in run
test(result)
File "/usr/local/lib/python3.10/unittest/suite.py", line 84, in __call__
return self.run(*args, **kwds)
File "/usr/local/lib/python3.10/unittest/suite.py", line 122, in run
test(result)
File "/usr/local/lib/python3.10/unittest/case.py", line 650, in __call__
return self.run(*args, **kwds)
File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 673, in run
result = super().run(self.result)
File "/usr/local/lib/python3.10/unittest/case.py", line 594, in run
self._callTearDown()
File "/usr/local/lib/python3.10/unittest/case.py", line 552, in _callTearDown
self.tearDown()
File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 2832, in tearDown
self.stop_event_analyzer()
File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 222, in decor
self._store_test_result(args[0], exc, exc.__traceback__, name)
```

## Impact

Causes the test to fail, even though the rest of the test was completely successful. Not only does the job fails, the downstream jobs are not triggered as a result

## How frequently does it reproduce?

Seems to be occasional

## Installation details

Kernel Version: 5.15.0-1040-aws
Scylla version (or git commit hash): `5.1.15-20230730.12966e84352e` with build-id `5ad69bfc0fd19f17f279a754ddd260e83a06aa4d`

Cluster size: 3 nodes (i4i.large)

Scylla Nodes used in this run:
- manager-regression-manager--db-node-ddabd532-3 (34.220.177.147 | 10.15.0.26) (shards: 2)
- manager-regression-manager--db-node-ddabd532-2 (44.197.241.201 | 10.12.0.167) (shards: 2)
- manager-regression-manager--db-node-ddabd532-1 (34.239.233.23 | 10.12.3.96) (shards: 2)


OS / Image: `ami-0b5aa5b3607c52672 ami-0505b3da72437bf69` (aws: undefined_region)

Test: `centos-sanity-test`
Test id: `ddabd532-787e-43b0-8027-b4147faa8bca`
Test name: `scylla-staging/Shlomo/centos-sanity-test`
Test config file(s):

- [manager-regression-multiDC-set-distro.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/476e5050857fd15f625ad7bf1f2fce54a9679723/test-cases/manager/manager-regression-multiDC-set-distro.yaml)


<details>
<summary>
Logs and commands
</summary>


- Restore Monitor Stack command: `$ hydra investigate show-monitor ddabd532-787e-43b0-8027-b4147faa8bca`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=ddabd532-787e-43b0-8027-b4147faa8bca)
- Show all stored logs command: `$ hydra investigate show-logs ddabd532-787e-43b0-8027-b4147faa8bca`


## Logs:
- **db-cluster-ddabd532.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ddabd532-787e-43b0-8027-b4147faa8bca/20230816_154959/db-cluster-ddabd532.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ddabd532-787e-43b0-8027-b4147faa8bca/20230816_154959/db-cluster-ddabd532.tar.gz)
- **sct-runner-events-ddabd532.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ddabd532-787e-43b0-8027-b4147faa8bca/20230816_154959/sct-runner-events-ddabd532.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ddabd532-787e-43b0-8027-b4147faa8bca/20230816_154959/sct-runner-events-ddabd532.tar.gz)
- **sct-ddabd532.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ddabd532-787e-43b0-8027-b4147faa8bca/20230816_154959/sct-ddabd532.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ddabd532-787e-43b0-8027-b4147faa8bca/20230816_154959/sct-ddabd532.log.tar.gz)
- **loader-set-ddabd532.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ddabd532-787e-43b0-8027-b4147faa8bca/20230816_154959/loader-set-ddabd532.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ddabd532-787e-43b0-8027-b4147faa8bca/20230816_154959/loader-set-ddabd532.tar.gz)
- **monitor-set-ddabd532.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ddabd532-787e-43b0-8027-b4147faa8bca/20230816_154959/monitor-set-ddabd532.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ddabd532-787e-43b0-8027-b4147faa8bca/20230816_154959/monitor-set-ddabd532.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/Shlomo/job/centos-sanity-test/6/)
[Argus](https://argus.scylladb.com/test/f36eea72-33ce-426e-9d5c-db29091bf58d/runs?additionalRuns[]=ddabd532-787e-43b0-8027-b4147faa8bca)
</details>

**Comment by fruch** [comment]
@soyacz seems like this is happening quite a lot especially on manager sanity

My guess is that we have lots of unhandled events, but I'm not quite sure

We'll need to add some more debug information to figure this one out.

Or maybe to replace the error with a warning, if the test doesn't hang after it.

**Comment by soyacz** [comment]
I analyzed the issue, and I think it's happening because we have stream of warnings from db (repair warnings) - which seems to be common for mgmt test. 
Analyzer stops after having a break of 1s in events stream which does not happen.
Possible solutions:
1. force EventAnalyzer to stop immediately (e.g. by calling `GeneratorExit` on inbound_events generator) - in that case we lose unprocessed events if were present
2. using `stop_resources_stop_tasks_threads` or other mean to stop new events coming to Events Analyzer

Maybe there are other ways. @fruch  what do you think?

**Comment by fruch** [comment]
both seems legit, i.e. at this point we are existing anyhow, those event are not really interesting, especially if they are warning.

**Comment by soyacz** [comment]
I added solution for stopping all events processes under these circumstances: https://github.com/scylladb/scylla-cluster-tests/pull/6561
for review.

**Comment by fruch** [comment]
fixed in https://github.com/scylladb/scylla-cluster-tests/pull/6561
