### ISSUE TITLE
AddRemoveDc breaks when simulated racks are being used

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#6236]
## Issue description

- [x] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

Since introduction of #6111, seems like the new node in `AddRemoveDc` is not added in a new DC
```
2023-06-11 08:42:15.917: (DisruptionEvent Severity.ERROR) period_type=end event_id=88b74d12-5e8b-4a8a-a02d-dcb1c1213217 duration=30m11s: nemesis_name=AddRemoveDc target_node=Node longevity-cdc-100gb-4h-master-db-node-d1b683b2-5 [54.229.157.143 | 10.4.2.208] (seed: True) errors=new datacenter was not registered
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4425, in wrapper
result = method(*args[1:], **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4009, in disrupt_add_remove_dc
assert new_dc_list, "new datacenter was not registered"
AssertionError: new datacenter was not registered
```

new node `10.4.2.123` is expected to be in `eu-west-1 _nemesis_dc`, but it's not:
```
< t:2023-06-11 08:31:15,279 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Datacenter: eu-west-1
< t:2023-06-11 08:31:15,281 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > =====================
< t:2023-06-11 08:31:15,281 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Status=Up/Down
< t:2023-06-11 08:31:15,282 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > |/ State=Normal/Leaving/Joining/Moving
< t:2023-06-11 08:31:15,303 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > --  Address     Load       Tokens       Owns    Host ID                               Rack
< t:2023-06-11 08:31:15,337 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UN  10.4.2.48   4.12 GB    256          ?       98eb8dae-c1ee-4dd1-b523-25344b6b33e9  RACK2
< t:2023-06-11 08:31:15,428 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UN  10.4.2.208  4.68 GB    256          ?       bb893bde-f262-44a4-97c1-6d8733c624d6  RACK1
< t:2023-06-11 08:31:15,504 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UN  10.4.0.16   4.68 GB    256          ?       ff50afc6-0d54-460d-9d3d-256bd5842da1  RACK2
< t:2023-06-11 08:31:15,521 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UN  10.4.0.195  4.47 GB    256          ?       67b7da59-4c9b-4180-a5cd-1dc31075d8f2  RACK0
< t:2023-06-11 08:31:15,536 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UN  10.4.1.237  4.12 GB    256          ?       333b4ac2-3b3b-4a67-926a-2037efc8f44e  RACK1
< t:2023-06-11 08:31:15,754 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UN  10.4.0.63   4.48 GB    256          ?       17c99787-ef4d-4484-a6ab-7e18ef6e3292  RACK0
< t:2023-06-11 08:31:15,820 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UN  10.4.2.123  3.68 GB    256          ?       c0a08277-dd78-4243-a6c2-7cd4f981db80  RACK0
```

the `cassandra-rackdc.properties` file seems to be correct, but not clear why `dc_suffix` isn't honored :
```
< t:2023-06-11 08:15:55,828 f:remote_base.py  l:238  c:RemoteLibSSH2CmdRunner p:DEBUG > Command scp -r -o StrictHostKeyChecking=no -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -o UserKnownHostsFile=/tmp/tmplspif9vn -P 22 -i /home/ubuntu/.ssh/scylla-qa-ec2 scyllaadm@[10.4.2.123]:"/etc/scylla/cassandra-rackdc.properties" '/tmp/sct5sb810k8/cassandra-rackdc.properties' with status 0
< t:2023-06-11 08:15:55,829 f:remote_file.py  l:63   c:sdcm.remote.remote_file p:DEBUG > New content of `/etc/scylla/cassandra-rackdc.properties':
< t:2023-06-11 08:15:55,829 f:remote_file.py  l:63   c:sdcm.remote.remote_file p:DEBUG > #
< t:2023-06-11 08:15:55,829 f:remote_file.py  l:63   c:sdcm.remote.remote_file p:DEBUG > # cassandra-rackdc.properties
< t:2023-06-11 08:15:55,829 f:remote_file.py  l:63   c:sdcm.remote.remote_file p:DEBUG > # The lines may include white spaces at the beginning and the end.
< t:2023-06-11 08:15:55,829 f:remote_file.py  l:63   c:sdcm.remote.remote_file p:DEBUG > # The rack and data center names may also include white spaces.
< t:2023-06-11 08:15:55,829 f:remote_file.py  l:63   c:sdcm.remote.remote_file p:DEBUG > # All trailing and leading white spaces will be trimmed.
< t:2023-06-11 08:15:55,829 f:remote_file.py  l:63   c:sdcm.remote.remote_file p:DEBUG > #
< t:2023-06-11 08:15:55,829 f:remote_file.py  l:63   c:sdcm.remote.remote_file p:DEBUG > # dc=my_data_center
< t:2023-06-11 08:15:55,829 f:remote_file.py  l:63   c:sdcm.remote.remote_file p:DEBUG > # rack=my_rack
< t:2023-06-11 08:15:55,829 f:remote_file.py  l:63   c:sdcm.remote.remote_file p:DEBUG > # prefer_local=<false | true>
< t:2023-06-11 08:15:55,829 f:remote_file.py  l:63   c:sdcm.remote.remote_file p:DEBUG > # dc_suffix=<Data Center name suffix, used by EC2SnitchXXX snitches>
< t:2023-06-11 08:15:55,829 f:remote_file.py  l:63   c:sdcm.remote.remote_file p:DEBUG >
< t:2023-06-11 08:15:55,829 f:remote_file.py  l:63   c:sdcm.remote.remote_file p:DEBUG >
< t:2023-06-11 08:15:55,829 f:remote_file.py  l:63   c:sdcm.remote.remote_file p:DEBUG > dc_suffix = _nemesis_dc
< t:2023-06-11 08:15:55,829 f:remote_file.py  l:63   c:sdcm.remote.remote_file p:DEBUG > dc = eu-west-1
< t:2023-06-11 08:15:55,829 f:remote_file.py  l:63   c:sdcm.remote.remote_file p:DEBUG > rack = RACK0
< t:2023-06-11 08:15:55,829 f:remote_file.py  l:63   c:sdcm.remote.remote_file p:DEBUG > prefer_local = true
````

## Impact

`AddRemoveDc` nemesis isn't working anymore on case that use simulated racks

## How frequently does it reproduce?

it's 100% reproducible 

## Installation details

Kernel Version: 5.15.0-1037-aws
Scylla version (or git commit hash): `5.4.0~dev-20230610.e464ad25686c` with build-id `206e139fcde8692bd60fa69c1f56dcb3260b3fe3`

Cluster size: 6 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- longevity-cdc-100gb-4h-master-db-node-d1b683b2-7 (54.246.75.175 | 10.4.2.123) (shards: 14)
- longevity-cdc-100gb-4h-master-db-node-d1b683b2-6 (54.217.45.101 | 10.4.0.16) (shards: 14)
- longevity-cdc-100gb-4h-master-db-node-d1b683b2-5 (54.229.157.143 | 10.4.2.208) (shards: 14)
- longevity-cdc-100gb-4h-master-db-node-d1b683b2-4 (3.253.45.180 | 10.4.0.63) (shards: 14)
- longevity-cdc-100gb-4h-master-db-node-d1b683b2-3 (34.241.186.179 | 10.4.2.48) (shards: 14)
- longevity-cdc-100gb-4h-master-db-node-d1b683b2-2 (54.154.181.93 | 10.4.1.237) (shards: 14)
- longevity-cdc-100gb-4h-master-db-node-d1b683b2-1 (34.250.14.70 | 10.4.0.195) (shards: 14)

OS / Image: `` (aws: undefined_region)

Test: `longevity-cdc-100gb-4h-test`
Test id: `d1b683b2-b743-4a6b-9950-a7f2a9e7b6f2`
Test name: `scylla-master/longevity/longevity-cdc-100gb-4h-test`
Test config file(s):

- [longevity-cdc-100gb-4h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/a1036e1b789a92d48c76d0614c975cbc67ee50bf/test-cases/longevity/longevity-cdc-100gb-4h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor d1b683b2-b743-4a6b-9950-a7f2a9e7b6f2`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=d1b683b2-b743-4a6b-9950-a7f2a9e7b6f2)
- Show all stored logs command: `$ hydra investigate show-logs d1b683b2-b743-4a6b-9950-a7f2a9e7b6f2`

## Logs:
- **db-cluster-d1b683b2.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d1b683b2-b743-4a6b-9950-a7f2a9e7b6f2/20230611_094924/db-cluster-d1b683b2.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d1b683b2-b743-4a6b-9950-a7f2a9e7b6f2/20230611_094924/db-cluster-d1b683b2.tar.gz)
- **sct-runner-events-d1b683b2.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d1b683b2-b743-4a6b-9950-a7f2a9e7b6f2/20230611_094924/sct-runner-events-d1b683b2.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d1b683b2-b743-4a6b-9950-a7f2a9e7b6f2/20230611_094924/sct-runner-events-d1b683b2.tar.gz)
- **sct-d1b683b2.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d1b683b2-b743-4a6b-9950-a7f2a9e7b6f2/20230611_094924/sct-d1b683b2.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d1b683b2-b743-4a6b-9950-a7f2a9e7b6f2/20230611_094924/sct-d1b683b2.log.tar.gz)
- **monitor-set-d1b683b2.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d1b683b2-b743-4a6b-9950-a7f2a9e7b6f2/20230611_094924/monitor-set-d1b683b2.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d1b683b2-b743-4a6b-9950-a7f2a9e7b6f2/20230611_094924/monitor-set-d1b683b2.tar.gz)
- **loader-set-d1b683b2.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d1b683b2-b743-4a6b-9950-a7f2a9e7b6f2/20230611_094924/loader-set-d1b683b2.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d1b683b2-b743-4a6b-9950-a7f2a9e7b6f2/20230611_094924/loader-set-d1b683b2.tar.gz)
- **parallel-timelines-report-d1b683b2.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d1b683b2-b743-4a6b-9950-a7f2a9e7b6f2/20230611_094924/parallel-timelines-report-d1b683b2.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d1b683b2-b743-4a6b-9950-a7f2a9e7b6f2/20230611_094924/parallel-timelines-report-d1b683b2.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-cdc-100gb-4h-test/395/)
[Argus](https://argus.scylladb.com/test/7a6140ad-4139-4155-8313-49557f1387ec/runs?additionalRuns[]=d1b683b2-b743-4a6b-9950-a7f2a9e7b6f2)
</details>

**Comment by fruch** [comment]
happened again this week, boot took 20min (SCT wait for VM to be create + scylla boot time)

```
2023-06-18T04:13:24+00:00 longevity-cdc-100gb-4h-master-db-node-50bd51dd-7     !INFO | systemd[1]: Starting Scylla Server...
...
2023-06-18T04:31:33+00:00 longevity-cdc-100gb-4h-master-db-node-50bd51dd-7     !INFO | scylla[5563]:  [shard  0] cql_server_controller - Starting listening for CQL clients on 10.4.2.217:9042 (unencrypted, non-shard-aware)
2023-06-18T04:31:33+00:00 longevity-cdc-100gb-4h-master-db-node-50bd51dd-7     !INFO | scylla[5563]:  [shard  0] cql_server_controller - Starting listening for CQL clients on 10.4.2.217:19042 (unencrypted, shard-aware)
2023-06-18T04:31:33+00:00 longevity-cdc-100gb-4h-master-db-node-50bd51dd-7     !INFO | scylla[5563]:  [shard  0] init - serving
2023-06-18T04:31:33+00:00 longevity-cdc-100gb-4h-master-db-node-50bd51dd-7     !INFO | scylla[5563]:  [shard  0] init - Scylla version 5.4.0~dev-0.20230613.b7022cd74e7a initialization completed.
```

## Installation details

Kernel Version: 5.15.0-1037-aws
Scylla version (or git commit hash): `5.4.0~dev-20230613.b7022cd74e7a` with build-id `b976d1863ce70323f73bff2740f5296fecb7e5c0`

Cluster size: 6 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- longevity-cdc-100gb-4h-master-db-node-50bd51dd-7 (34.247.156.175 | 10.4.2.217) (shards: 14)
- longevity-cdc-100gb-4h-master-db-node-50bd51dd-6 (34.241.249.67 | 10.4.2.130) (shards: 14)
- longevity-cdc-100gb-4h-master-db-node-50bd51dd-5 (3.250.76.197 | 10.4.1.164) (shards: 14)
- longevity-cdc-100gb-4h-master-db-node-50bd51dd-4 (54.195.184.210 | 10.4.0.182) (shards: 14)
- longevity-cdc-100gb-4h-master-db-node-50bd51dd-3 (54.217.83.2 | 10.4.0.83) (shards: 14)
- longevity-cdc-100gb-4h-master-db-node-50bd51dd-2 (54.216.105.16 | 10.4.1.221) (shards: 14)
- longevity-cdc-100gb-4h-master-db-node-50bd51dd-1 (54.246.1.131 | 10.4.0.198) (shards: 14)


OS / Image: `` (aws: undefined_region)

Test: `longevity-cdc-100gb-4h-test`
Test id: `50bd51dd-5f3c-49f1-932e-f77ea855a0e7`
Test name: `scylla-master/longevity/longevity-cdc-100gb-4h-test`
Test config file(s):

- [longevity-cdc-100gb-4h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/e38ad755c3db62ee7ee9c6b67a5cd34936f6e515/test-cases/longevity/longevity-cdc-100gb-4h.yaml)


<details>
<summary>
Logs and commands
</summary>


- Restore Monitor Stack command: `$ hydra investigate show-monitor 50bd51dd-5f3c-49f1-932e-f77ea855a0e7`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=50bd51dd-5f3c-49f1-932e-f77ea855a0e7)
- Show all stored logs command: `$ hydra investigate show-logs 50bd51dd-5f3c-49f1-932e-f77ea855a0e7`


## Logs:
- **db-cluster-50bd51dd.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/50bd51dd-5f3c-49f1-932e-f77ea855a0e7/20230618_070110/db-cluster-50bd51dd.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/50bd51dd-5f3c-49f1-932e-f77ea855a0e7/20230618_070110/db-cluster-50bd51dd.tar.gz)
- **sct-runner-events-50bd51dd.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/50bd51dd-5f3c-49f1-932e-f77ea855a0e7/20230618_070110/sct-runner-events-50bd51dd.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/50bd51dd-5f3c-49f1-932e-f77ea855a0e7/20230618_070110/sct-runner-events-50bd51dd.tar.gz)
- **sct-50bd51dd.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/50bd51dd-5f3c-49f1-932e-f77ea855a0e7/20230618_070110/sct-50bd51dd.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/50bd51dd-5f3c-49f1-932e-f77ea855a0e7/20230618_070110/sct-50bd51dd.log.tar.gz)
- **monitor-set-50bd51dd.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/50bd51dd-5f3c-49f1-932e-f77ea855a0e7/20230618_070110/monitor-set-50bd51dd.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/50bd51dd-5f3c-49f1-932e-f77ea855a0e7/20230618_070110/monitor-set-50bd51dd.tar.gz)
- **loader-set-50bd51dd.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/50bd51dd-5f3c-49f1-932e-f77ea855a0e7/20230618_070110/loader-set-50bd51dd.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/50bd51dd-5f3c-49f1-932e-f77ea855a0e7/20230618_070110/loader-set-50bd51dd.tar.gz)
- **parallel-timelines-report-50bd51dd.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/50bd51dd-5f3c-49f1-932e-f77ea855a0e7/20230618_070110/parallel-timelines-report-50bd51dd.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/50bd51dd-5f3c-49f1-932e-f77ea855a0e7/20230618_070110/parallel-timelines-report-50bd51dd.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-cdc-100gb-4h-test/396/)
[Argus](https://argus.scylladb.com/test/7a6140ad-4139-4155-8313-49557f1387ec/runs?additionalRuns[]=50bd51dd-5f3c-49f1-932e-f77ea855a0e7)
</details>

**Comment by soyacz** [comment]
It is because `dc_suffix` is not accepted by GossipingPropertyFileSnitch, for that case we need to modify `dc` param

**Comment by soyacz** [comment]
fixed in https://github.com/scylladb/scylla-cluster-tests/pull/6297

**Comment by yarongilor** [comment]
@soyacz , it looks like issue is reproduced, can you please advise?
```
2023-07-09 04:33:57.264: (DisruptionEvent Severity.ERROR) period_type=end event_id=c5397fea-2810-499a-bb48-5c63d565a3d3 duration=28m52s: nemesis_name=AddRemoveDc target_node=Node longevity-cdc-100gb-4h-master-db-node-1e720e97-1 [54.229.166.63 | 10.4.2.178] (seed: True) errors=new datacenter was not registered
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4521, in wrapper
result = method(*args[1:], **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4104, in disrupt_add_remove_dc
assert new_dc_list, "new datacenter was not registered"
AssertionError: new datacenter was not registered
```

## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

*Describe your issue in detail and steps it took to produce it.*

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Kernel Version: 5.15.0-1039-aws
Scylla version (or git commit hash): `5.4.0~dev-20230703.1ab2bb69b8a6` with build-id `1054adfa55f238441c3044e6213fd02d31d43279`




Cluster size: 6 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- longevity-cdc-100gb-4h-master-db-node-1e720e97-7 (3.250.92.43 | 10.4.1.79) (shards: 14)
- longevity-cdc-100gb-4h-master-db-node-1e720e97-6 (52.213.225.205 | 10.4.2.155) (shards: 14)
- longevity-cdc-100gb-4h-master-db-node-1e720e97-5 (34.244.151.37 | 10.4.0.154) (shards: 14)
- longevity-cdc-100gb-4h-master-db-node-1e720e97-4 (54.154.252.29 | 10.4.0.63) (shards: 14)
- longevity-cdc-100gb-4h-master-db-node-1e720e97-3 (34.252.178.49 | 10.4.3.124) (shards: 14)
- longevity-cdc-100gb-4h-master-db-node-1e720e97-2 (34.252.125.213 | 10.4.3.60) (shards: 14)
- longevity-cdc-100gb-4h-master-db-node-1e720e97-1 (54.229.166.63 | 10.4.2.178) (shards: 14)


OS / Image: `` (aws: undefined_region)

Test: `longevity-cdc-100gb-4h-test`
Test id: `1e720e97-e12a-47ee-938e-7a1059c611b1`
Test name: `scylla-master/longevity/longevity-cdc-100gb-4h-test`
Test config file(s):

- [longevity-cdc-100gb-4h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/c34f91b1a83f9848be2ae1027d5cc64fe0b864fa/test-cases/longevity/longevity-cdc-100gb-4h.yaml)


<details>
<summary>
Logs and commands
</summary>


- Restore Monitor Stack command: `$ hydra investigate show-monitor 1e720e97-e12a-47ee-938e-7a1059c611b1`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=1e720e97-e12a-47ee-938e-7a1059c611b1)
- Show all stored logs command: `$ hydra investigate show-logs 1e720e97-e12a-47ee-938e-7a1059c611b1`


## Logs:
- **db-cluster-1e720e97.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/1e720e97-e12a-47ee-938e-7a1059c611b1/20230709_075244/db-cluster-1e720e97.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/1e720e97-e12a-47ee-938e-7a1059c611b1/20230709_075244/db-cluster-1e720e97.tar.gz)
- **sct-runner-events-1e720e97.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/1e720e97-e12a-47ee-938e-7a1059c611b1/20230709_075244/sct-runner-events-1e720e97.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/1e720e97-e12a-47ee-938e-7a1059c611b1/20230709_075244/sct-runner-events-1e720e97.tar.gz)
- **sct-1e720e97.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/1e720e97-e12a-47ee-938e-7a1059c611b1/20230709_075244/sct-1e720e97.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/1e720e97-e12a-47ee-938e-7a1059c611b1/20230709_075244/sct-1e720e97.log.tar.gz)
- **monitor-set-1e720e97.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/1e720e97-e12a-47ee-938e-7a1059c611b1/20230709_075244/monitor-set-1e720e97.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/1e720e97-e12a-47ee-938e-7a1059c611b1/20230709_075244/monitor-set-1e720e97.tar.gz)
- **loader-set-1e720e97.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/1e720e97-e12a-47ee-938e-7a1059c611b1/20230709_075244/loader-set-1e720e97.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/1e720e97-e12a-47ee-938e-7a1059c611b1/20230709_075244/loader-set-1e720e97.tar.gz)
- **parallel-timelines-report-1e720e97.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/1e720e97-e12a-47ee-938e-7a1059c611b1/20230709_075244/parallel-timelines-report-1e720e97.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/1e720e97-e12a-47ee-938e-7a1059c611b1/20230709_075244/parallel-timelines-report-1e720e97.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-cdc-100gb-4h-test/399/)
[Argus](https://argus.scylladb.com/test/7a6140ad-4139-4155-8313-49557f1387ec/runs?additionalRuns[]=1e720e97-e12a-47ee-938e-7a1059c611b1)
</details>

**Comment by soyacz** [comment]
@yarongilor this one should do the job: https://github.com/scylladb/scylla-cluster-tests/pull/6347

**Comment by fruch** [comment]
It's not working...
