### ISSUE TITLE
EKS single-tenant throughput tests run only 6-7 loader threads at once instead of required 8.

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-cluster-tests#6289]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master
* **scylla**: 2022.2.9

### Logs
* test_id: fb7cfcd6-e92a-453f-a5a0-94f0ee6ad1a8
* job log: [CI](https://jenkins.scylladb.com/job/scylla-operator/job/operator-1.9/job/performance/job/perf-regression-throughput-eks/8/execution/node/233/log/)

### Description

If we run `perf-regression-throughput-eks` CI job then each of the sub-tests (`test_write`, `test_read`, `test_mixed`) fails with the following error:
```
2023-06-23 18:01:49,793 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 2023-06-23 18:01:49.792: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=fb157eea-4f02-4e4e-8e5c-1c36ce204840, source=PerformanceRegressionTest.test_write (performance_regression_test.PerformanceRegressionTest)() message=Traceback (most recent call last):
2023-06-23 18:01:49,793 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/performance_regression_test.py", line 517, in test_write
2023-06-23 18:01:49,793 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     results = self.get_stress_results(queue=stress_queue)
2023-06-23 18:01:49,793 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 2118, in get_stress_results
2023-06-23 18:01:49,793 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     results = queue.get_results()
2023-06-23 18:01:49,793 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/stress_thread.py", line 342, in get_results
2023-06-23 18:01:49,793 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     results = super().get_results()
2023-06-23 18:01:49,793 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/stress/base.py", line 86, in get_results
2023-06-23 18:01:49,793 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     for future in concurrent.futures.as_completed(self.results_futures, timeout=timeout):
2023-06-23 18:01:49,793 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 241, in as_completed
2023-06-23 18:01:49,793 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     raise TimeoutError(
2023-06-23 18:01:49,793 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > concurrent.futures._base.TimeoutError: 2 (of 8) futures unfinished
```

It is caused by the fact that some of loaders, in current case 2, start after some other 2 finish execution.
It also happens to be just 1 such `waiting` loader.
So, from 8 needed loader threads we get run `6` or `7` at a time.
At first it spoils the idea of the `performance` test and second it fails the `throughput` test all the time.

Proof that there is delay:
```
2023-06-23 16:44:17,295 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2023-06-23 16:44:17.293: (CassandraStressLogEvent Severity.NORMAL) period_type=one-time event_id=bc01279f-cb91-4609-b2da-0314e06f9147: type=ShardAwareDriver regex=Using optimized driver line_number=97 node=Node sct-loaders-0 [10.12.7.118 | 10.12.7.213] (seed: False)
2023-06-23 16:44:17,295 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > ===== Using optimized driver!!! =====
...
2023-06-23 16:44:46,538 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2023-06-23 16:44:46.535: (CassandraStressLogEvent Severity.NORMAL) period_type=one-time event_id=79630fad-87ad-47b6-bbd7-1a27bb948d7d: type=ShardAwareDriver regex=Using optimized driver line_number=97 node=Node sct-loaders-0 [10.12.7.118 | 10.12.7.213] (seed: False)
2023-06-23 16:44:46,538 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > ===== Using optimized driver!!! =====
2023-06-23 16:44:46,797 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2023-06-23 16:44:46.795: (CassandraStressLogEvent Severity.NORMAL) period_type=one-time event_id=2471c81d-c7a2-482d-9573-b03c68c79c3b: type=ShardAwareDriver regex=Using optimized driver line_number=97 node=Node sct-loaders-2 [10.12.6.128 | 10.12.7.31] (seed: False)
2023-06-23 16:44:46,797 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > ===== Using optimized driver!!! =====
2023-06-23 16:44:46,807 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2023-06-23 16:44:46.805: (CassandraStressLogEvent Severity.NORMAL) period_type=one-time event_id=95f90f09-77e6-44d6-8358-078f26c87fb7: type=ShardAwareDriver regex=Using optimized driver line_number=97 node=Node sct-loaders-3 [10.12.7.196 | 10.12.6.67] (seed: False)
2023-06-23 16:44:46,807 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > ===== Using optimized driver!!! =====
2023-06-23 16:44:46,862 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2023-06-23 16:44:46.860: (CassandraStressLogEvent Severity.NORMAL) period_type=one-time event_id=fe9d1151-4e7c-41be-b0fd-2e6cd3e48f6d: type=ShardAwareDriver regex=Using optimized driver line_number=97 node=Node sct-loaders-3 [10.12.7.196 | 10.12.6.67] (seed: False)
2023-06-23 16:44:46,862 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > ===== Using optimized driver!!! =====
2023-06-23 16:44:46,964 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2023-06-23 16:44:46.961: (CassandraStressLogEvent Severity.NORMAL) period_type=one-time event_id=b3853a0b-1f85-4a45-bf9b-5834b0095cf3: type=ShardAwareDriver regex=Using optimized driver line_number=97 node=Node sct-loaders-1 [10.12.4.7 | 10.12.4.208] (seed: False)
...
2023-06-23 17:44:57,376 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2023-06-23 17:44:57.375: (CassandraStressLogEvent Severity.NORMAL) period_type=one-time event_id=5d2e8a47-3763-4f3c-9b7e-fae5136af451: type=ShardAwareDriver regex=Using optimized driver line_number=97 node=Node sct-loaders-1 [10.12.4.7 | 10.12.4.208] (seed: False)
2023-06-23 17:44:57,376 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > ===== Using optimized driver!!! =====
2023-06-23 17:44:57,451 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2023-06-23 17:44:57.450: (CassandraStressLogEvent Severity.NORMAL) period_type=one-time event_id=c1d956ef-6484-465e-8eef-0a9ebdba4690: type=ShardAwareDriver regex=Using optimized driver line_number=97 node=Node sct-loaders-2 [10.12.6.128 | 10.12.7.31] (seed: False)
2023-06-23 17:44:57,451 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > ===== Using optimized driver!!! =====
2023-06-23 18:01:44,542 f:tester.py       l:2821 c:PerformanceRegressionTest p:INFO  > TearDown is starting...
```

### Steps to Reproduce

1. Run EKS single-tenant throughput tests
2. Wait while loader threads start
3. See that 1 or 2 loader threads were not started in addition to the first 6-7.

**Expected behavior:** All the loader threads must run at once (the very first one starts for `30` sec earlier - expected)

**Actual behavior:** 1-2 loader threads doesn't fit some hidden `pool` of the `6-7` threads.

**Comment by vponomaryov** [comment]
The bug disappears if we set `use_hdr_cs_histogram` config option to `false`.
So, HDR introduces the concurrency limitation.

**Comment by vponomaryov** [comment]
> I just saw recent commit that was changing something about collecting HDR histograms (I don't know if related for EKS): [1556348](https://github.com/scylladb/scylla-cluster-tests/commit/15563489878b54dc9d39ea665f38237c2842a7f5)

Tried it out in here: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/valerii/job/perf-regression-throughput-eks/47

The `mixed` test failed due to unrelated reason - `api error Throttling: Rate exceeded`.
The `read` and `write` tests passed and stress commands ran as expected - concurrently where first one starts for 30 seconds earlier than all others.

Note that the bug was reproduced not in 100% cases, but looks like it is fixed. Especially after looking at the fix details.
Worth running 1 or 2 times more to make sure it is not coincidence.
