### ISSUE TITLE
`load_and_stream` nemesis fails to find `end log` line

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-cluster-tests#6314]
### Prerequisites

* [x] Are you rebased to master ?
* [ ] Is it reproducible ?
* [ ] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master
* **scylla**: 2022.2.6-20230423.b9a1478dba07

### Logs
* test_id: 283a201c-789c-4562-9294-1d949a7675ae
* job log: [Argus](https://argus.scylladb.com/test/5c32ee82-a403-40cf-aa96-8ab6b68626fa/runs?additionalRuns[]=283a201c-789c-4562-9294-1d949a7675ae), [CI](https://jenkins.scylladb.com/job/scylla-operator/job/operator-1.9/job/gke/job/longevity-scylla-operator-basic-12h-gke/2/consoleFull)

### Description

The `load_and_stream` nemesis failed with the following error:
```
Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4425, in wrapper
    result = method(*args[1:], **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1570, in disrupt_load_and_stream
    SstableLoadUtils.run_load_and_stream(load_on_node)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/sstable/load_utils.py", line 115, in run_load_and_stream
    with wait_for_log_lines(node, start_line_patterns=[cls.LOAD_AND_STREAM_RUN_EXPR],
  File "/usr/local/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/wait.py", line 149, in wait_for_log_lines
    raise TimeoutError(
TimeoutError: timeout occurred while waiting for end log line (['(?:storage_service|sstables_loader) - load_and_stream:'] on node: sct-cluster-us-east1-b-us-east1-2
```

Node logs:
```
INFO  2023-06-11 17:22:45,104 [shard  2] sstables_loader - Loading new SSTables for keyspace=keyspace1, table=standard1, load_and_stream=true, primary_replica_only=false
INFO  2023-06-11 17:22:45,118 [shard 11] sstables_loader - load_and_stream: started ops_uuid=d6b500e0-4263-4f85-9a2f-9decdd8c73da, process [0-1] out of 1 sstables={/var/lib/scylla/data/keyspace1/standard1-754ffdc0087011eea410dd42b84ee2fe/upload/md-11-big-Data.db}
...
INFO  2023-06-11 17:22:52,129 [shard  2] sstables_loader - Done loading new SSTables for keyspace=keyspace1, table=standard1, load_and_stream=true, primary_replica_only=false, status=succeeded
```

So, the Scylla worked as expected, but SCT failed to match existing proper logs.

### Steps to Reproduce

1. Run `load_and_stream` nemesis
2. See error

**Expected behavior:** SCT should match logs when it exists

**Actual behavior:** SCT fails to match existing logs.

**Comment by vponomaryov** [comment]
The exception message has typo. Fix for the typo is here: https://github.com/scylladb/scylla-cluster-tests/pull/6313

**Comment by vponomaryov** [comment]
@soyacz any ideas?

**Comment by fruch** [comment]
> @soyacz any ideas?

Just a sec the log exists and we didn't match it ? or the log is missing coming in late ?

Cause we know we have an issue with the logs that might get stuck after bursts of logs

**Comment by vponomaryov** [comment]
> > @soyacz any ideas?
> 
> Just a sec the log exists and we didn't match it ? or the log is missing coming in late ?
> 
> Cause we know we have an issue with the logs that might get stuck after bursts of logs

The bug description answers your question. Both log messages exist with the 7s diff.

**Comment by soyacz** [comment]
Reason of this issue is that log line arrives late to sct. See time diff it got to sct and time it actually happened is very long (almost 9 minutes):
```
 t:2023-06-11 17:31:49,923 f:db_log_reader.py l:114  c:sdcm.db_log_reader   p:DEBUG > INFO  2023-06-11 17:22:52,129 [shard  2] sstables_loader - Done loading new SSTables for keyspace=keyspace1
```

**Comment by vponomaryov** [comment]
> Reason of this issue is that log line arrives late to sct. See time diff it got to sct and time it actually happened is very long (almost 9 minutes):
> 
> ```
>  t:2023-06-11 17:31:49,923 f:db_log_reader.py l:114  c:sdcm.db_log_reader   p:DEBUG > INFO  2023-06-11 17:22:52,129 [shard  2] sstables_loader - Done loading new SSTables for keyspace=keyspace1
> ```

It happens in 100% cases on K8S.
