### ISSUE TITLE
'*Cluster' object has no attribute 'nodelist'

### ISSUE THREAD

**Issue by bentsi** [scylladb/scylla-cluster-tests#633]
```
2018-09-23 12:37:42,581 tester           L0956 DEBUG| _wait_for_view_build_start: [[u'-9221980948815979134'], [u'-9219751849886585836']]
2018-09-23 12:37:42,581 tester           L0933 DEBUG| Waiting for view keyspace1.standard1_mv to finish building...
2018-09-23 12:37:42,581 stacktrace       L0036 ERROR| 
2018-09-23 12:37:42,581 stacktrace       L0039 ERROR| Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado/core/test.py:449
2018-09-23 12:37:42,582 stacktrace       L0042 ERROR| Traceback (most recent call last):
2018-09-23 12:37:42,582 stacktrace       L0042 ERROR|   File "/sct/performance_regression_test.py", line 175, in test_write_with_mv_populated
2018-09-23 12:37:42,582 stacktrace       L0042 ERROR|     self._write_with_mv(on_populated=True)
2018-09-23 12:37:42,582 stacktrace       L0042 ERROR|   File "/sct/performance_regression_test.py", line 197, in _write_with_mv
2018-09-23 12:37:42,582 stacktrace       L0042 ERROR|     self.prepare_mv(on_populated=on_populated)
2018-09-23 12:37:42,582 stacktrace       L0042 ERROR|   File "/sct/performance_regression_test.py", line 147, in prepare_mv
2018-09-23 12:37:42,582 stacktrace       L0042 ERROR|     self._wait_for_view(self.db_cluster, session, ks_name, view_name)
2018-09-23 12:37:42,582 stacktrace       L0042 ERROR|   File "/sct/sdcm/tester.py", line 942, in _wait_for_view
2018-09-23 12:37:42,582 stacktrace       L0042 ERROR|     live_nodes_amount = len([node for node in cluster.nodelist() if node.status == 'UP'])
2018-09-23 12:37:42,582 stacktrace       L0042 ERROR| AttributeError: 'ScyllaAWSCluster' object has no attribute 'nodelist'
```

The issue is in `tester.py`
```
        attempts = 20
        live_nodes_amount = len([node for node in cluster.nodelist() if node.status == 'UP'])
        while attempts > 0:
            if _view_build_finished(live_nodes_amount):
```

**Comment by juliayakovlev** [comment]
@bentsi  Opened PR with fix: https://github.com/scylladb/scylla-cluster-tests/pull/636

**Comment by juliayakovlev** [comment]
@bentsi  Please, close the issue, if the fix has been passed
