### ISSUE TITLE
`get_scylla_versions` is broken for offline installer tests

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#6388]
`get_scylla_versions` is broken for offline installer tests

```
23:42:29  < t:2023-07-18 20:42:29,109 f:base.py         l:146  c:RemoteLibSSH2CmdRunner p:ERROR > Error executing command: "rpm -qa |grep scylla"; Exit status: 1
23:42:29  < t:2023-07-18 20:42:29,109 f:db_stats.py     l:583  c:sdcm.db_stats        p:ERROR > Failed getting scylla versions: Encountered a bad command exit code!
23:42:29  < t:2023-07-18 20:42:29,109 f:db_stats.py     l:583  c:sdcm.db_stats        p:ERROR > 
23:42:29  < t:2023-07-18 20:42:29,109 f:db_stats.py     l:583  c:sdcm.db_stats        p:ERROR > Command: 'rpm -qa |grep scylla'
23:42:29  < t:2023-07-18 20:42:29,109 f:db_stats.py     l:583  c:sdcm.db_stats        p:ERROR > 
23:42:29  < t:2023-07-18 20:42:29,109 f:db_stats.py     l:583  c:sdcm.db_stats        p:ERROR > Exit code: 1
23:42:29  < t:2023-07-18 20:42:29,109 f:db_stats.py     l:583  c:sdcm.db_stats        p:ERROR > 
23:42:29  < t:2023-07-18 20:42:29,109 f:db_stats.py     l:583  c:sdcm.db_stats        p:ERROR > Stdout:
23:42:29  < t:2023-07-18 20:42:29,109 f:db_stats.py     l:583  c:sdcm.db_stats        p:ERROR > 
23:42:29  < t:2023-07-18 20:42:29,109 f:db_stats.py     l:583  c:sdcm.db_stats        p:ERROR > 
23:42:29  < t:2023-07-18 20:42:29,109 f:db_stats.py     l:583  c:sdcm.db_stats        p:ERROR > 
23:42:29  < t:2023-07-18 20:42:29,109 f:db_stats.py     l:583  c:sdcm.db_stats        p:ERROR > Stderr:
23:42:29  < t:2023-07-18 20:42:29,109 f:db_stats.py     l:583  c:sdcm.db_stats        p:ERROR > 
23:42:29  < t:2023-07-18 20:42:29,109 f:db_stats.py     l:583  c:sdcm.db_stats        p:ERROR > 
23:42:29  < t:2023-07-18 20:42:29,109 f:db_stats.py     l:583  c:sdcm.db_stats        p:ERROR > 
23:42:30  < t:2023-07-18 20:42:29,968 f:tester.py       l:491  c:ArtifactsTest        p:ERROR > Unable to collect package versions for Argus - skipping... < t:2023-07-18 20:42:29,968 f:tester.py       l:491  c:ArtifactsTest        p:ERROR > Unable to collect package versions for Argus - skipping...
23:42:30  < t:2023-07-18 20:42:29,968 f:tester.py       l:491  c:ArtifactsTest        p:ERROR > Traceback (most recent call last):
23:42:30  < t:2023-07-18 20:42:29,968 f:tester.py       l:491  c:ArtifactsTest        p:ERROR >   File "/tmp/jenkins/workspace/scylla-staging/fruch/artifacts-amazon2-arm-test/scylla-cluster-tests/sdcm/tester.py", line 473, in argus_collect_packages
23:42:30  < t:2023-07-18 20:42:29,968 f:tester.py       l:491  c:ArtifactsTest        p:ERROR >     versions = self.get_scylla_versions()
23:42:30  < t:2023-07-18 20:42:29,968 f:tester.py       l:491  c:ArtifactsTest        p:ERROR >   File "/tmp/jenkins/workspace/scylla-staging/fruch/artifacts-amazon2-arm-test/scylla-cluster-tests/sdcm/db_stats.py", line 586, in get_scylla_versions
23:42:30  < t:2023-07-18 20:42:29,968 f:tester.py       l:491  c:ArtifactsTest        p:ERROR >     versions['scylla-server']['build_mode'] = node.scylla_build_mode
23:42:30  < t:2023-07-18 20:42:29,968 f:tester.py       l:491  c:ArtifactsTest        p:ERROR > KeyError: 'scylla-server'
```

1) code is using rpm/apt to figure versions, and it's not relevant for offline installer case
2) after code is failing, it's trying to assign the build mode to non-existing dict item.

**Comment by fruch** [comment]
there a fallback to `generate_scylla_server_package` on case of this failure.
but `generate_scylla_server_package` doesn't have build mode

**Comment by fruch** [comment]
@fgelcer  FYI

**Comment by roydahan** [comment]
Is it still relevant or already fixed?

**Comment by fruch** [comment]
> Is it still relevant or already fixed?

I don't think anyone fixed it.
It's not blocking anything

**Comment by roydahan** [comment]
Isn't it blocking Argus from showing the Scylla version of the offline artifact tests?

**Comment by fruch** [comment]
> Isn't it blocking Argus from showing the Scylla version of the offline artifact tests?
> 

Yes it is.

**Comment by roydahan** [comment]
OK, so let's fix it :)
Moved to next sprints queue.
