### ISSUE TITLE
SCT Docker image build failure: writing top-level names to lib3/PyYAML.egg-info/top_level.txt: AttributeError: cython_sources

### ISSUE THREAD

**Issue by enaydanov** [scylladb/scylla-cluster-tests#6389]
Recently Cython released version 3.0.0 which caused problems with installation of PyYAML: https://github.com/yaml/pyyaml/issues/724 : 

```
$ ./build_n_push.sh 
...
Building...
...
UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
    error: subprocess-exited-with-error
    
    × Getting requirements to build wheel did not run successfully.
    │ exit code: 1
    ╰─> [62 lines of output]
...
        writing lib3/PyYAML.egg-info/PKG-INFO
        writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
        writing top-level names to lib3/PyYAML.egg-info/top_level.txt
        Traceback (most recent call last):
          ...
          File "/tmp/pip-build-env-ey_3t5no/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
            return self._get_build_requires(config_settings, requirements=['wheel'])
          File "/tmp/pip-build-env-ey_3t5no/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
            self.run_setup()
          File "/tmp/pip-build-env-ey_3t5no/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in run_setup
            exec(code, locals())
          File "<string>", line 271, in <module>
          File "/tmp/pip-build-env-ey_3t5no/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
            return distutils.core.setup(**attrs)
          File "/tmp/pip-build-env-ey_3t5no/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
            return run_commands(dist)
          File "/tmp/pip-build-env-ey_3t5no/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
            dist.run_commands()
          File "/tmp/pip-build-env-ey_3t5no/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
            self.run_command(cmd)
          File "/tmp/pip-build-env-ey_3t5no/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
            super().run_command(command)
          File "/tmp/pip-build-env-ey_3t5no/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
            cmd_obj.run()
          File "/tmp/pip-build-env-ey_3t5no/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 314, in run
            self.find_sources()
          File "/tmp/pip-build-env-ey_3t5no/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 322, in find_sources
            mm.run()
          File "/tmp/pip-build-env-ey_3t5no/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 551, in run
            self.add_defaults()
          File "/tmp/pip-build-env-ey_3t5no/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
            sdist.add_defaults(self)
          File "/tmp/pip-build-env-ey_3t5no/overlay/lib/python3.10/site-packages/setuptools/command/sdist.py", line 104, in add_defaults
            super().add_defaults()
          File "/tmp/pip-build-env-ey_3t5no/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
            self._add_defaults_ext()
          File "/tmp/pip-build-env-ey_3t5no/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
            self.filelist.extend(build_ext.get_source_files())
          File "<string>", line 201, in get_source_files
          File "/tmp/pip-build-env-ey_3t5no/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
            raise AttributeError(attr)
        AttributeError: cython_sources
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
...
pip._internal.exceptions.InstallationSubprocessError: Getting requirements to build wheel exited with 1
```

The problem can't be solved by pinning Cython<3 in our requirements because it's a build requirement of PyYAML itself. They released fixed version 6.0.1, and we can upgrade it to this version, but in this case we need to upgrade awscli package to version >=1.29.4  too because the version we use now is pinned to PyYAML<5.5

The only incompatibility introduced by PyYAML 6 is required `loader` parameter for `yaml.load()`. I see only few occurrences of this function in SCT in 2 unit tests:

```
unit_tests/provisioner/test_user_data_builder.py
65:    loaded_yaml = yaml.load(user_data_yaml)
86:    loaded_yaml = yaml.load(user_data_yaml)
99:    loaded_yaml = yaml.load(user_data_yaml)
109:    loaded_yaml = yaml.load(user_data_yaml)

unit_tests/test_scylla_yaml.py
433:            test_config_file_yaml = yaml.load(test_file)
434:            append_scylla_args_dict = yaml.load(test_config_file_yaml["append_scylla_yaml"])
```

Just need to replace the calls of `yaml.load()` with `yaml.safe_load()`

**Comment by fruch** [comment]
this is resolved already
