### ISSUE TITLE
Despite setting `enable_argus: false` a lot of Argus related errors are emitted during SCT runs

### ISSUE THREAD

**Issue by eliransin** [scylladb/scylla-cluster-tests#6413]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: latest
* **scylla**: irrelevant

### Logs
During SCT runs with `enable_argus: 'false'` I still see a lot of errors similar to:

```
p:ERROR > Encountered an unhandled exception while interacting with Argus < t:2023-07-23 09:36:14,284 f:cluster.py      l:331  c:sdcm.cluster         p:ERROR > Encountered an unhandled exception while interacting with Argus
< t:2023-07-23 09:36:14,284 f:cluster.py      l:331  c:sdcm.cluster         p:ERROR > Traceback (most recent call last):
< t:2023-07-23 09:36:14,284 f:cluster.py      l:331  c:sdcm.cluster         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 320, in _add_node_to_argus
< t:2023-07-23 09:36:14,284 f:cluster.py      l:331  c:sdcm.cluster         p:ERROR >     client.create_resource(
< t:2023-07-23 09:36:14,284 f:cluster.py      l:331  c:sdcm.cluster         p:ERROR >   File "/usr/local/lib/python3.10/site-packages/argus/client/sct/client.py", line 140, in create_resource
< t:2023-07-23 09:36:14,284 f:cluster.py      l:331  c:sdcm.cluster         p:ERROR >     self.check_response(response)
< t:2023-07-23 09:36:14,284 f:cluster.py      l:331  c:sdcm.cluster         p:ERROR >   File "/usr/local/lib/python3.10/site-packages/argus/client/base.py", line 64, in check_response
< t:2023-07-23 09:36:14,284 f:cluster.py      l:331  c:sdcm.cluster         p:ERROR >     raise ArgusClientError(
< t:2023-07-23 09:36:14,284 f:cluster.py      l:331  c:sdcm.cluster         p:ERROR > argus.client.base.ArgusClientError: ('API Error encountered using endpoint: POST /api/v1/client/sct/5609be18-57e1-47a7-8040-1496d80c3e98/resource/create', 'Run not found')
```

**Comment by fruch** [comment]
@eliransin 

can you try it with `enable_argus: false` ? i.e. not passing a string to it ?
