### ISSUE TITLE
GCE instance was not cleaned up because of GCP quota being exceeded

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylla-cluster-tests#6427]
```
Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/./sct.py", line 1523, in <module>
    cli()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/./sct.py", line 291, in clean_resources
    clean_func(param, dry_run=dry_run)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 2151, in clean_resources_according_post_behavior
    clean_cloud_resources(params | {"NodeType": node_type}, dry_run=dry_run)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 553, in clean_cloud_resources
    clean_instances_gce(tags_dict, dry_run=dry_run)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 1134, in clean_instances_gce
    gce_instances_to_clean = list_instances_gce(tags_dict=tags_dict)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 958, in list_instances_gce
    all_gce_instances = compute_engine.list_nodes()
  File "/usr/local/lib/python3.10/site-packages/libcloud/compute/drivers/gce.py", line 2597, in list_nodes
    response = self.connection.request_aggregated_items('instances',
  File "/usr/local/lib/python3.10/site-packages/libcloud/compute/drivers/gce.py", line 170, in request_aggregated_items
    response = self.request(request_path, method='GET').object
  File "/usr/local/lib/python3.10/site-packages/libcloud/compute/drivers/gce.py", line 126, in request
    response = super(GCEConnection, self).request(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/libcloud/common/google.py", line 811, in request
    return super(GoogleBaseConnection, self).request(
  File "/usr/local/lib/python3.10/site-packages/libcloud/common/base.py", line 655, in request
    response = responseCls(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/libcloud/common/base.py", line 169, in __init__
    self.object = self.parse_body()
  File "/usr/local/lib/python3.10/site-packages/libcloud/common/google.py", line 294, in parse_body
    raise GoogleBaseError(message, self.status, code)
libcloud.common.google.GoogleBaseError: {'message': "Quota exceeded for quota metric 'Heavy-weight read requests' and limit 'Heavy-weight read requests per minute' of service 'compute.googleapis.com' for consumer 'project_number:1070746702980'.", 'domain': 'usageLimits', 'reason': 'rateLimitExceeded'}
```

[example of a job we are seeing it](https://jenkins.scylladb.com/job/scylla-5.1/job/rolling-upgrade/job/rolling-upgrade-alternator-test/54/execution/node/233/log/)

**Comment by fgelcer** [comment]
another example in [this job](https://jenkins.scylladb.com/job/scylla-5.2/job/artifacts/job/artifacts-gce-image-persistent-disk-test/52/execution/node/92/log/)

**Comment by fruch** [comment]
Or asking for more Heavy-weight read requests

Or we need a retry on the cleanup of gce.


Also it failed the log collection

**Comment by fruch** [comment]
we asked for a bigger quota
