### ISSUE TITLE
Need to increase timeout for test_manager_sanity

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla-cluster-tests#6432]
As of now it is 240, while it can take([1](https://jenkins.scylladb.com/job/scylla-staging/job/dkropachev/job/3-1-centos-sanity-test/5), [2](https://jenkins.scylladb.com/view/scylla-manager/job/manager-3.1/job/ubuntu18-sanity-test/44)) up to 120 minutes to prepare environment, while whole test workflow takes 120-+10minutes

**Comment by fgelcer** [comment]
> As of now it is 240, while it can take([1](https://jenkins.scylladb.com/job/scylla-staging/job/dkropachev/job/3-1-centos-sanity-test/5), [2](https://jenkins.scylladb.com/view/scylla-manager/job/manager-3.1/job/ubuntu18-sanity-test/44)) up to 120 minutes to prepare environment, while whole test workflow takes 120-+10minutes

i see the rebuild of these 2 builds above passed

**Comment by dkropachev** [comment]
Timeout failure - https://jenkins.scylladb.com/view/scylla-manager/job/manager-3.1/job/centos-sanity-ipv6-test/18

**Comment by fruch** [comment]
> Timeout failure - https://jenkins.scylladb.com/view/scylla-manager/job/manager-3.1/job/centos-sanity-ipv6-test/18

@dkropachev this is not a test timeout, it's the event analyzer failing to stop, it's a whole different issue, and if it's happening a lot in manager tests we'll need to figure it out, but adding more to the test timeout won't solve it:
```
21:09:49  < t:2023-07-27 18:09:41,716 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > exception=Events process EventsAnalyzer is still alive after timeout
21:09:49  < t:2023-07-27 18:09:41,716 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > Traceback (most recent call last):
21:09:49  < t:2023-07-27 18:09:41,716 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/./sct.py", line 1660, in <module>
21:09:49  < t:2023-07-27 18:09:41,716 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     cli.main(prog_name="hydra")
21:09:49  < t:2023-07-27 18:09:41,716 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
21:09:49  < t:2023-07-27 18:09:41,716 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     rv = self.invoke(ctx)
21:09:49  < t:2023-07-27 18:09:41,716 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
21:09:49  < t:2023-07-27 18:09:41,716 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     return _process_result(sub_ctx.command.invoke(sub_ctx))
21:09:49  < t:2023-07-27 18:09:41,716 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
21:09:49  < t:2023-07-27 18:09:41,716 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     return ctx.invoke(self.callback, **ctx.params)
21:09:49  < t:2023-07-27 18:09:41,716 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
21:09:49  < t:2023-07-27 18:09:41,716 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     return __callback(*args, **kwargs)
21:09:49  < t:2023-07-27 18:09:41,716 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/./sct.py", line 1080, in run_test
21:09:49  < t:2023-07-27 18:09:41,716 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     unittest.main(module=None, argv=['python -m unittest', argv],
21:09:49  < t:2023-07-27 18:09:41,716 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/usr/local/lib/python3.10/unittest/main.py", line 101, in __init__
21:09:49  < t:2023-07-27 18:09:41,716 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     self.runTests()
21:09:49  < t:2023-07-27 18:09:41,716 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/usr/local/lib/python3.10/unittest/main.py", line 271, in runTests
21:09:49  < t:2023-07-27 18:09:41,716 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     self.result = testRunner.run(self.test)
21:09:49  < t:2023-07-27 18:09:41,716 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/usr/local/lib/python3.10/unittest/runner.py", line 176, in run
21:09:49  < t:2023-07-27 18:09:41,716 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     test(result)
21:09:49  < t:2023-07-27 18:09:41,716 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/usr/local/lib/python3.10/unittest/suite.py", line 84, in __call__
21:09:49  < t:2023-07-27 18:09:41,716 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     return self.run(*args, **kwds)
21:09:49  < t:2023-07-27 18:09:41,716 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/usr/local/lib/python3.10/unittest/suite.py", line 122, in run
21:09:49  < t:2023-07-27 18:09:41,716 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     test(result)
21:09:49  < t:2023-07-27 18:09:41,716 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/usr/local/lib/python3.10/unittest/suite.py", line 84, in __call__
21:09:49  < t:2023-07-27 18:09:41,716 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     return self.run(*args, **kwds)
21:09:49  < t:2023-07-27 18:09:41,716 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/usr/local/lib/python3.10/unittest/suite.py", line 122, in run
21:09:49  < t:2023-07-27 18:09:41,716 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     test(result)
21:09:49  < t:2023-07-27 18:09:41,716 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/usr/local/lib/python3.10/unittest/case.py", line 650, in __call__
21:09:49  < t:2023-07-27 18:09:41,716 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     return self.run(*args, **kwds)
21:09:49  < t:2023-07-27 18:09:41,716 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 622, in run
21:09:49  < t:2023-07-27 18:09:41,716 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     result = super().run(self.result)
21:09:49  < t:2023-07-27 18:09:41,716 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/usr/local/lib/python3.10/unittest/case.py", line 594, in run
21:09:49  < t:2023-07-27 18:09:41,716 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     self._callTearDown()
21:09:49  < t:2023-07-27 18:09:41,716 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/usr/local/lib/python3.10/unittest/case.py", line 552, in _callTearDown
21:09:49  < t:2023-07-27 18:09:41,716 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     self.tearDown()
21:09:49  < t:2023-07-27 18:09:41,716 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 2742, in tearDown
21:09:49  < t:2023-07-27 18:09:41,716 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     self.stop_event_analyzer()
21:09:49  < t:2023-07-27 18:09:41,716 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 213, in decor
21:09:49  < t:2023-07-27 18:09:41,716 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     self._store_test_result(args[0], exc, exc.__traceback__, name)
```

**Comment by dkropachev** [comment]
@fruch , definitely I have pasted something different

**Comment by dkropachev** [comment]
Recent examples:
https://jenkins.scylladb.com/view/scylla-manager/job/manager-3.1/job/centos-sanity-test/51

**Comment by fgelcer** [comment]
> Recent examples: https://jenkins.scylladb.com/view/scylla-manager/job/manager-3.1/job/centos-sanity-test/51

@dkropachev , 2 things:
1st, why some times it does pass, and some times it doesn't? we should understand what is wasting the extra time... as it could be either in Scylla, or in SCT, but also in the manager, and it should be fixed
2nd, how much you think would be enough timeout, but OTOH not too much, so we wouldn't leave a test running too long before catching new unexpected long operations?
