### ISSUE TITLE
SpotMonitoringThread endup throwing `JSONDecodeError`

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla-cluster-tests#6433]
### Prerequisites

Test failed on SpotMonitoringThread with `JSONDecodeError`:
```
[2023-07-26T17:24:03.877Z] Exception in thread SpotMonitoringThread:
[2023-07-26T17:24:03.877Z] Traceback (most recent call last):
[2023-07-26T17:24:03.877Z]   File "/usr/local/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
[2023-07-26T17:24:03.877Z]     self.run()
[2023-07-26T17:24:03.877Z]   File "/usr/local/lib/python3.10/threading.py", line 946, in run
[2023-07-26T17:24:03.877Z]     self._target(*self._args, **self._kwargs)
[2023-07-26T17:24:03.877Z]   File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 896, in spot_monitoring_thread
[2023-07-26T17:24:03.877Z]     next_check_delay = self.check_spot_termination() or SPOT_TERMINATION_CHECK_DELAY
[2023-07-26T17:24:03.877Z]   File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster_aws.py", line 483, in check_spot_termination
[2023-07-26T17:24:03.877Z]     terminate_action = json.loads(status)
[2023-07-26T17:24:03.877Z]   File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
[2023-07-26T17:24:03.877Z]     return _default_decoder.decode(s)
[2023-07-26T17:24:03.877Z]   File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
[2023-07-26T17:24:03.877Z]     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
[2023-07-26T17:24:03.877Z]   File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
[2023-07-26T17:24:03.877Z]     raise JSONDecodeError("Expecting value", s, err.value) from None
[2023-07-26T17:24:03.877Z] json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

### Versions
* **SCT**: manager-3.1

### Logs
* test_id: 71349be9-4b8f-405c-89b7-e8e8596ee0f9
* Job: https://jenkins.scylladb.com/job/scylla-staging/job/dkropachev/job/3-1-longevity-large-partition-8h/3

db-cluster: https://cloudius-jenkins-test.s3.amazonaws.com/71349be9-4b8f-405c-89b7-e8e8596ee0f9/20230727_004338/db-cluster-71349be9.tar.gz
sct-runner:  https://cloudius-jenkins-test.s3.amazonaws.com/71349be9-4b8f-405c-89b7-e8e8596ee0f9/20230727_004338/sct-runner-71349be9.tar.gz
monitor-set: https://cloudius-jenkins-test.s3.amazonaws.com/71349be9-4b8f-405c-89b7-e8e8596ee0f9/20230727_004338/monitor-set-71349be9.tar.gz
loader-set: https://cloudius-jenkins-test.s3.amazonaws.com/71349be9-4b8f-405c-89b7-e8e8596ee0f9/20230727_004338/loader-set-71349be9.tar.gz

**Comment by fruch** [comment]
1) this thread need to be decorated with `@raise_event_on_failure`
2) looks like the check on AWS doesn't check for 503
```
< t:2023-07-26 17:24:02,414 f:cluster_aws.py  l:482  c:sdcm.cluster_aws     p:WARNING > Node longevity-large-partitions-8h-dk-si-monitor-node-71349be9-1 [3.252.247.61 | 10.4.2.39] (seed: False): Got spot termination notification from AWS <?xml version="1.0" encoding="iso-8859-1"?>
< t:2023-07-26 17:24:02,414 f:cluster_aws.py  l:482  c:sdcm.cluster_aws     p:WARNING > <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
< t:2023-07-26 17:24:02,414 f:cluster_aws.py  l:482  c:sdcm.cluster_aws     p:WARNING >                  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
< t:2023-07-26 17:24:02,414 f:cluster_aws.py  l:482  c:sdcm.cluster_aws     p:WARNING > <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
< t:2023-07-26 17:24:02,414 f:cluster_aws.py  l:482  c:sdcm.cluster_aws     p:WARNING >  <head>
< t:2023-07-26 17:24:02,414 f:cluster_aws.py  l:482  c:sdcm.cluster_aws     p:WARNING >   <title>503 - Service Unavailable</title>
< t:2023-07-26 17:24:02,414 f:cluster_aws.py  l:482  c:sdcm.cluster_aws     p:WARNING >  </head>
< t:2023-07-26 17:24:02,414 f:cluster_aws.py  l:482  c:sdcm.cluster_aws     p:WARNING >  <body>
< t:2023-07-26 17:24:02,414 f:cluster_aws.py  l:482  c:sdcm.cluster_aws     p:WARNING >   <h1>503 - Service Unavailable</h1>
< t:2023-07-26 17:24:02,414 f:cluster_aws.py  l:482  c:sdcm.cluster_aws     p:WARNING >  </body>
< t:2023-07-26 17:24:02,414 f:cluster_aws.py  l:482  c:sdcm.cluster_aws     p:WARNING > </html>
```

Anyhow we might want to refactor the `curl` command to fail on an other status 

3) we should catch exception on the json parsing, and let it retry

**Comment by fruch** [comment]
fixed in https://github.com/scylladb/scylla-cluster-tests/pull/7604
