### ISSUE TITLE
Invalid query: Cannot create secondary index on partition key column pk

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-cluster-tests#6444]
### Versions
* **SCT**: 5.2
* **scylla**: 5.2

### Logs
* test_id: c0270484-06f5-4a6f-9c00-e45a46b9702e
* job log: [Argus](https://argus.scylladb.com/test/4d85e295-2ce4-4704-afa7-8ea748b17a88/runs?additionalRuns[]=c0270484-06f5-4a6f-9c00-e45a46b9702e), [CI](https://jenkins.scylladb.com/job/scylla-5.2/job/longevity/job/longevity-large-partition-asymmetric-cluster-3h-test/21/consoleFull)

### Description

Running the `test-cases/longevity/longevity-large-partition-3h.yaml` config file which tries to run following command:

```
post_prepare_cql_cmds: "CREATE INDEX si_text ON scylla_bench.test(pk)"
```

Fails:

```
20:01:18  < t:2023-07-30 17:01:18,091 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 2023-07-30 17:01:18.060: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=40ef978a-72fa-4690-ba27-74d15d234139, source=LargePartitionLongevityTest.test_large_partition_longevity (longevity_large_partition_test.LargePartitionLongevityTest)() message=Traceback (most recent call last):
20:01:18  < t:2023-07-30 17:01:18,091 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/longevity_large_partition_test.py", line 11, in test_large_partition_longevity
20:01:18  < t:2023-07-30 17:01:18,091 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     self.test_custom_time()
20:01:18  < t:2023-07-30 17:01:18,091 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/longevity_test.py", line 104, in test_custom_time
20:01:18  < t:2023-07-30 17:01:18,091 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     self.run_prepare_write_cmd()
20:01:18  < t:2023-07-30 17:01:18,091 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/loader_utils.py", line 209, in run_prepare_write_cmd
20:01:18  < t:2023-07-30 17:01:18,091 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     self.run_post_prepare_cql_cmds()
20:01:18  < t:2023-07-30 17:01:18,091 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/loader_utils.py", line 152, in run_post_prepare_cql_cmds
20:01:18  < t:2023-07-30 17:01:18,091 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     self._run_cql_commands(post_prepare_cql_cmds)
20:01:18  < t:2023-07-30 17:01:18,091 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/loader_utils.py", line 143, in _run_cql_commands
20:01:18  < t:2023-07-30 17:01:18,091 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     session.execute(cmd)
20:01:18  < t:2023-07-30 17:01:18,091 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 1727, in execute_verbose
20:01:18  < t:2023-07-30 17:01:18,091 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     return execute_orig(*args, **kwargs)
20:01:18  < t:2023-07-30 17:01:18,091 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "cassandra/cluster.py", line 2699, in cassandra.cluster.Session.execute
20:01:18  < t:2023-07-30 17:01:18,091 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "cassandra/cluster.py", line 5018, in cassandra.cluster.ResponseFuture.result
20:01:18  < t:2023-07-30 17:01:18,091 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > cassandra.InvalidRequest: Error from server: code=2200 [Invalid query] message="Cannot create secondary index on partition key column pk"
```

Directly related to the following changes: https://github.com/scylladb/scylla-cluster-tests/pull/5944 and https://github.com/scylladb/scylla-cluster-tests/pull/6405

We should use non partition key column for the secondary index.
So, need to choose another column.

**Comment by vponomaryov** [comment]
@soyacz , @fruch ^

**Comment by fruch** [comment]
> @soyacz , @fruch ^

The question is to @k0machi and @roydahan why this case with it's different configuration wasn't tested, even when it had a bug with the comment, and it's still doesn't work.

For now let's open a PR to revert this index creation from 5.2 (and backport to 2023.1)
