### ISSUE TITLE
 _parse_cs_summary: ValueError: substring not found

### ISSUE THREAD

**Issue by bentsi** [scylladb/scylla-cluster-tests#650]
```
2018-10-12 05:08:28,684 remote           L0194 DEBUG| [18.212.141.237] [stdout] Results:
2018-10-12 05:08:28,685 remote           L0194 DEBUG| [18.212.141.237] [stdout] Op rate                   :    9,152 op/s  [READ: 9,152 op/s]
2018-10-12 05:08:28,685 remote           L0194 DEBUG| [18.212.141.237] [stdout] Partition rate            :    9,152 pk/s  [READ: 9,152 pk/s]
2018-10-12 05:08:28,685 remote           L0194 DEBUG| [18.212.141.237] [stdout] Row rate                  :    9,152 row/s [READ: 9,152 row/s]
2018-10-12 05:08:28,685 remote           L0194 DEBUG| [18.212.141.237] [stdout] Latency mean              :   54.5 ms [READ: 54.5 ms]
2018-10-12 05:08:28,686 remote           L0194 DEBUG| [18.212.141.237] [stdout] Latency median            :    0.9 ms [READ: 0.9 ms]
2018-10-12 05:08:28,686 remote           L0194 DEBUG| [18.212.141.237] [stdout] Latency 95th percentile   :   58.6 ms [READ: 58.6 ms]
2018-10-12 05:08:28,686 remote           L0194 DEBUG| [18.212.141.237] [stdout] Latency 99th percentile   : 2533.4 ms [READ: 2,533.4 ms]
2018-10-12 05:08:28,686 remote           L0194 DEBUG| [18.212.141.237] [stdout] Latency 99.9th percentile : 2617.2 ms [READ: 2,617.2 ms]
2018-10-12 05:08:28,686 remote           L0194 DEBUG| [18.212.141.237] [stdout] Latency max               : 3143.6 ms [READ: 3,143.6 ms]
2018-10-12 05:08:28,687 remote           L0194 DEBUG| [18.212.141.237] [stdout] Total partitions          :  5,515,602 [READ: 5,515,602]
2018-10-12 05:08:28,687 remote           L0194 DEBUG| [18.212.141.237] [stdout] Total errors              :          0 [READ: 0]
2018-10-12 05:08:28,687 remote           L0194 DEBUG| [18.212.141.237] [stdout] Total GC count            : 0
2018-10-12 05:08:28,687 remote           L0194 DEBUG| [18.212.141.237] [stdout] Total GC memory           : 0.000 KiB
2018-10-12 05:08:28,687 remote           L0194 DEBUG| [18.212.141.237] [stdout] Total GC time             :    0.0 seconds
2018-10-12 05:08:28,687 remote           L0194 DEBUG| [18.212.141.237] [stdout] Avg GC time               :    NaN ms
2018-10-12 05:08:28,688 remote           L0194 DEBUG| [18.212.141.237] [stdout] StdDev GC time            :    0.0 ms
2018-10-12 05:08:28,688 remote           L0194 DEBUG| [18.212.141.237] [stdout] Total operation time      : 00:10:02
2018-10-12 05:08:28,688 remote           L0194 DEBUG| [18.212.141.237] [stdout] 
2018-10-12 05:08:28,688 remote           L0194 DEBUG| [18.212.141.237] [stdout] END
2018-10-12 05:08:30,950 remote           L0194 DEBUG| [18.212.141.237] [stderr] /home/centos/run_cassandra_stress.sh: line 1:  6567 Done                    cat /tmp/cs_
read_pipe_$1_$2
2018-10-12 05:08:30,951 remote           L0194 DEBUG| [18.212.141.237] [stderr]       6568 Terminated              | python /usr/bin/cassandra_stress_exporter read
2018-10-12 05:08:30,954 tester           L0130 ERROR| Exception in run_stress. Will clean resources
Traceback (most recent call last):
  File "/jenkins/slave/workspace/scylla-staging-scale-cluster-test-clone-amos/label/aws-scylla-qa-builder1/sdcm/tester.py", line 128, in wrapper
    return method(*args, **kwargs)
  File "/jenkins/slave/workspace/scylla-staging-scale-cluster-test-clone-amos/label/aws-scylla-qa-builder1/sdcm/tester.py", line 662, in run_stress
    self.verify_stress_thread(stress_queue)
  File "/jenkins/slave/workspace/scylla-staging-scale-cluster-test-clone-amos/label/aws-scylla-qa-builder1/sdcm/tester.py", line 699, in verify_stress_thread
    results, errors = self.loaders.verify_stress_thread(queue, self.db_cluster)
  File "/jenkins/slave/workspace/scylla-staging-scale-cluster-test-clone-amos/label/aws-scylla-qa-builder1/sdcm/cluster.py", line 2140, in verify_stress_thread
    node_cs_res = self._parse_cs_summary(lines)
  File "/jenkins/slave/workspace/scylla-staging-scale-cluster-test-clone-amos/label/aws-scylla-qa-builder1/sdcm/cluster.py", line 2014, in _parse_cs_summary
    split_idx = line.index(':')
ValueError: substring not found
2018-10-12 05:08:30,956 tester           L0988 DEBUG| Cleaning up resources used in the test
```

**Comment by bentsi** [comment]
Discussed with @roydahan  and this should be fixed by dc9b60a. Closing this issue.
