### ISSUE TITLE
`disrupt_network_random_interruptions` nemesis fails if prometheus has the same data for the `node_network_receive_bytes_total` metric

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-cluster-tests#6505]
### Prerequisites

* [x] Are you rebased to master ?
* [ ] Is it reproducible ?
* [ ] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master
* **scylla**: `5.4.0~dev-20230812.d1d1b6cf6e01`

### Logs
* test_id: `9b9c3e29-c92d-42ad-9624-0ccdd8226d48`
* job log: [Argus](https://argus.scylladb.com/test/028aa2df-5ce5-4883-a4a8-16bfbbe8dcc8/runs?additionalRuns[]=9b9c3e29-c92d-42ad-9624-0ccdd8226d48), [CI](https://jenkins.scylladb.com/job/scylla-operator/job/operator-master/job/eks/job/longevity-scylla-operator-3h-eks/110/)

### Description

The `disrupt_network_random_interruptions` nemesis fails the following way:

```
Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4907, in wrapper
    result = method(*args[1:], **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3145, in disrupt_network_random_interruptions
    self._disrupt_network_random_interruptions_k8s(list_of_timeout_options)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3103, in _disrupt_network_random_interruptions_k8s
    rate_limit: Optional[str] = self.get_rate_limit_for_network_disruption()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3099, in get_rate_limit_for_network_disruption
    return "{}{}".format(random.randrange(min_limit, max_limit), rate_limit_suffix)
  File "/usr/local/lib/python3.10/random.py", line 353, in randrange
    raise ValueError("empty range for randrange() (%d, %d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (0, 0, 0)
```

When the prometheus returns the same data for the following query:
```
query = 'avg(node_network_receive_bytes_total{instance=~".*?%s.*?", device="eth0"})' % self.target_node.ip_address
...
results = prometheus_stats.query(query=query, start=now - 600, end=now)
...
avg_bitrate_per_node = (received_bytes_over_time[-1] - received_bytes_over_time[0]) / 600
...
```

### Steps to Reproduce

1. Run the `disrupt_network_random_interruptions` nemesis
2. See error

**Expected behavior:** Nemesis must be smart enough and detect that the data may be the same.

**Actual behavior:** Nemesis fails unexpectedly when the data is the same.

**Comment by soyacz** [comment]
Happened again,
The reason is that in previous nemesis target node got new IP address and is still not receiving data. 
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

*Describe your issue in detail and steps it took to produce it.*

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Kernel Version: 5.10.192-183.736.amzn2.x86_64
Scylla version (or git commit hash): `2023.1.1-20230906.f4633ec973b0` with build-id `b454e7a22f80cf71a33b2f39e47127225e8fbc13`


Operator Image: scylladb/scylla-operator:latest
Operator Helm Version: v1.11.0-alpha.0-114-g8ac0a21
Operator Helm Repository: https://storage.googleapis.com/scylla-operator-charts/latest
Cluster size: 4 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
**No resources left at the end of the run**

OS / Image: `` (k8s-eks: undefined_region)

Test: `longevity-scylla-operator-basic-12h-eks`
Test id: `3146781b-80d9-4b4d-a5e2-563b278fe302`
Test name: `scylla-operator/operator-master/eks/longevity-scylla-operator-basic-12h-eks`
Test config file(s):

- [longevity-scylla-operator-basic-12h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/fa73cde2127567560e3cf64260f55b3275a86a24/test-cases/scylla-operator/longevity-scylla-operator-basic-12h.yaml)


<details>
<summary>
Logs and commands
</summary>


- Restore Monitor Stack command: `$ hydra investigate show-monitor 3146781b-80d9-4b4d-a5e2-563b278fe302`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=3146781b-80d9-4b4d-a5e2-563b278fe302)
- Show all stored logs command: `$ hydra investigate show-logs 3146781b-80d9-4b4d-a5e2-563b278fe302`


## Logs:
- **kubernetes-3146781b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/3146781b-80d9-4b4d-a5e2-563b278fe302/20231001_044313/kubernetes-3146781b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/3146781b-80d9-4b4d-a5e2-563b278fe302/20231001_044313/kubernetes-3146781b.tar.gz)
- **db-cluster-3146781b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/3146781b-80d9-4b4d-a5e2-563b278fe302/20231001_044313/db-cluster-3146781b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/3146781b-80d9-4b4d-a5e2-563b278fe302/20231001_044313/db-cluster-3146781b.tar.gz)
- **sct-runner-events-3146781b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/3146781b-80d9-4b4d-a5e2-563b278fe302/20231001_044313/sct-runner-events-3146781b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/3146781b-80d9-4b4d-a5e2-563b278fe302/20231001_044313/sct-runner-events-3146781b.tar.gz)
- **sct-3146781b.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/3146781b-80d9-4b4d-a5e2-563b278fe302/20231001_044313/sct-3146781b.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/3146781b-80d9-4b4d-a5e2-563b278fe302/20231001_044313/sct-3146781b.log.tar.gz)
- **loader-set-3146781b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/3146781b-80d9-4b4d-a5e2-563b278fe302/20231001_044313/loader-set-3146781b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/3146781b-80d9-4b4d-a5e2-563b278fe302/20231001_044313/loader-set-3146781b.tar.gz)
- **monitor-set-3146781b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/3146781b-80d9-4b4d-a5e2-563b278fe302/20231001_044313/monitor-set-3146781b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/3146781b-80d9-4b4d-a5e2-563b278fe302/20231001_044313/monitor-set-3146781b.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-operator/job/operator-master/job/eks/job/longevity-scylla-operator-basic-12h-eks/83/)
[Argus](https://argus.scylladb.com/test/c3f68ac3-b7cf-4ac8-8cf4-270db06f0e14/runs?additionalRuns[]=3146781b-80d9-4b4d-a5e2-563b278fe302)
</details>
