### ISSUE TITLE
`snapshot_operations` nemesis fails with `Snapshot content not as expected` error

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-cluster-tests#6527]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [ ] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master
* **scylla**: 2023.1.0

### Logs
* test_id: 1c711258-2b82-4865-aace-4ce9d1655a60
* job log: [Argus](https://argus.scylladb.com/test/d0b7bb8c-5d12-43bc-abe9-fd7a4f20bc5c/runs?additionalRuns[]=1c711258-2b82-4865-aace-4ce9d1655a60), [CI](https://jenkins.scylladb.com/job/scylla-operator/job/operator-1.10/job/eks/job/longevity-scylla-operator-lwt-24h/3/console)

### Description

Running the `snapshot_operations` nemesis within the  `longevity-scylla-operator-lwt-24h` CI job it fails with the following error:

```
Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4918, in wrapper
    result = method(*args[1:], **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3040, in disrupt_snapshot_operations
    self._validate_snapshot(nodetool_cmd=nodetool_cmd, snapshot_content=snapshot_content)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2938, in _validate_snapshot
    raise AssertionError(f"Snapshot content not as expected. \n"
AssertionError: Snapshot content not as expected. 
Expected content: [
	['cqlstress_lwt_example', 'blogposts'], 
	['cqlstress_lwt_example', 'blogposts_not_updated_lwt_indicator_expect'], 
	['cqlstress_lwt_example', 'blogposts_update_2_columns_lwt_indicator_expect'], 
	['cqlstress_lwt_example', 'blogposts_update_one_column_lwt_indicator_expect']
] 

 Actual snapshot content: [
 	['cqlstress_lwt_example', 'blogposts'], 
 	['cqlstress_lwt_example', 'blogposts_not_updated_lwt_indicator'], 
 	['cqlstress_lwt_example', 'blogposts_not_updated_lwt_indicator_expect'], 
 	['cqlstress_lwt_example', 'blogposts_update_2_columns_lwt_indicator'], 
 	['cqlstress_lwt_example', 'blogposts_update_2_columns_lwt_indicator_after_update'], 
 	['cqlstress_lwt_example', 'blogposts_update_2_columns_lwt_indicator_expect'], 
 	['cqlstress_lwt_example', 'blogposts_update_one_column_lwt_indicator'], 
 	['cqlstress_lwt_example', 'blogposts_update_one_column_lwt_indicator_after_update'], 
 	['cqlstress_lwt_example', 'blogposts_update_one_column_lwt_indicator_expect']
 ]
```

The `expected` part is subset of the `actual` one.
Moreover, the redundant ones differ only with suffixes.

### Steps to Reproduce

1. Run `snapshot_operations` nemesis with the `24h LWT` CI job
2. See error

**Expected behavior:** The `snapshot_operations` must work.

**Actual behavior:** It fails.

**Comment by fruch** [comment]
seems like the fix in https://github.com/scylladb/scylla-cluster-tests/issues/4775
wasn't enough, we removed the MV from the command, but MV are still getting part of the snapshot, and we need to count them for validation.

**Comment by juliayakovlev** [comment]
Looks like Scylla issue. 

Snapshot command is correct:
```
< t:2023-08-19 12:57:14,989 f:cluster.py      l:2625 c:sdcm.cluster         p:DEBUG > Node sct-cluster-us-east1-b-us-east1-1 [10.0.11.4 | 10.0.8.236] (seed: False): Command '/usr/bin/nodetool  snapshot cqlstress_lwt_example -cf blogposts_update_one_column_lwt_indicator_expect,blogposts,blogposts_update_2_columns_lwt_indicator_expect,blogposts_not_updated_lwt_indicator_expect ' duration -> 5.914317393999227 s
```

Despite snapshot was asked for tables only:
```
blogposts_update_one_column_lwt_indicator_expect,
blogposts,blogposts_update_2_columns_lwt_indicator_expect,
blogposts_not_updated_lwt_indicator_expect
```

I do not see table names in request (maybe it is ok and should not be there? need to check):
```
< t:2023-08-19 12:57:14,990 f:nemesis.py      l:3029 c:sdcm.nemesis         p:DEBUG > Requested creating snapshot(s) for [cqlstress_lwt_example] with snapshot name [1692449830828] and options {skipFlush=false}
```

And snapshot with name `1692449830828` includes MV in addition to asked tables :
```
< t:2023-08-19 12:57:15,009 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2023-08-19 12:57:14.990: (NodetoolEvent Severity.NORMAL) period_type=begin event_id=edc83f7b-7b9f-4099-8a4a-f1533d0de989: nodetool_command=listsnapshots node=sct-cluster-us-east1-b-us-east1-1
< t:2023-08-19 12:57:14,990 f:remote_base.py  l:520  c:KubernetesCmdRunner  p:DEBUG > Running command "/usr/bin/nodetool  listsnapshots "...

Snapshot name Keyspace name         Column family name                                     True size Size on disk
1692449830828 cqlstress_lwt_example blogposts                                              0 bytes   601.13 MB   
1692449830828 cqlstress_lwt_example blogposts_update_one_column_lwt_indicator              16.19 MB  18.87 MB    
1692449830828 cqlstress_lwt_example blogposts_update_one_column_lwt_indicator_after_update 0 bytes   0 bytes     
1692449830828 cqlstress_lwt_example blogposts_update_2_columns_lwt_indicator               14.11 MB  16.41 MB    
1692449830828 cqlstress_lwt_example blogposts_update_2_columns_lwt_indicator_after_update  52 KB     52 KB       
1692449830828 cqlstress_lwt_example blogposts_not_updated_lwt_indicator                    0 bytes   793 KB      
1692449830828 cqlstress_lwt_example blogposts_not_updated_lwt_indicator_expect             0 bytes   789 KB      
1692449830828 cqlstress_lwt_example blogposts_update_one_column_lwt_indicator_expect       0 bytes   15.25 MB    
1692449830828 cqlstress_lwt_example blogposts_update_2_columns_lwt_indicator_expect        0 bytes   13.02 MB    
< t:2023-08-19 12:57:17,522 f:base.py         l:142  c:KubernetesCmdRunner  p:DEBUG > Command "/usr/bin/nodetool  listsnapshots " finished with status 0
```

I do not find opened issue.
Also this failure happened only in this k8s longevity: https://70f106c98484448dbc4705050eb3f7e9.us-east-1.aws.found.io:9243/app/dashboards#/view/9312c960-2d8e-11eb-8579-3fa2093e3e28?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-90d,to:now))

**Comment by juliayakovlev** [comment]
I am checking if it is expected - to keep MVs

**Comment by juliayakovlev** [comment]
@fruch 
I found the answer: https://github.com/scylladb/scylladb/issues/11612
It was merged in 2022, but nemesis was not adjusted.
We need to fix it
