### ISSUE TITLE
Linting is causing 'RequestLimitExceeded' 

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#6535]
Our checks in SCT pipeline:
```
[...]
15:43:46  ---- linting: ./test-cases/nemesis/longevity-5gb-1h-DeleteByRowsRangeMonkey.yaml -----
15:43:48  ---- linting: ./test-cases/nemesis/longevity-5gb-1h-ScyllaKillMonkey.yaml -----
15:43:48  ---- linting: ./test-cases/nemesis/longevity-5gb-1h-StartStopCleanupCompaction.yaml -----
15:43:48  Traceback (most recent call last):
15:43:48    File "/tmp/jenkins/workspace/can_scylla-cluster-tests_PR-6532/./sct.py", line 765, in _run_yaml_test
15:43:48      config = SCTConfiguration()
15:43:48    File "/tmp/jenkins/workspace/can_scylla-cluster-tests_PR-6532/sdcm/sct_config.py", line 1651, in __init__
15:43:48      self[key] = convert_name_to_ami_if_needed(param, self.region_names)
15:43:48    File "/tmp/jenkins/workspace/can_scylla-cluster-tests_PR-6532/sdcm/utils/common.py", line 1951, in convert_name_to_ami_if_needed
15:43:48      if images := sorted(
15:43:48    File "/usr/local/lib/python3.10/site-packages/boto3/resources/collection.py", line 81, in __iter__
15:43:48      for page in self.pages():
15:43:48    File "/usr/local/lib/python3.10/site-packages/boto3/resources/collection.py", line 171, in pages
15:43:48      for page in pages:
15:43:48    File "/usr/local/lib/python3.10/site-packages/botocore/paginate.py", line 269, in __iter__
15:43:48      response = self._make_request(current_kwargs)
15:43:48    File "/usr/local/lib/python3.10/site-packages/botocore/paginate.py", line 357, in _make_request
15:43:48      return self._method(**current_kwargs)
15:43:48    File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 534, in _api_call
15:43:48      return self._make_api_call(operation_name, kwargs)
15:43:48    File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 976, in _make_api_call
15:43:48      raise error_class(parsed_response, operation_name)
15:43:48  botocore.exceptions.ClientError: An error occurred (RequestLimitExceeded) when calling the DescribeImages operation (reached max retries: 4): Request limit exceeded.
```

Example link: https://jenkins.scylladb.com/job/sct-github-PRs-scan/job/scylla-cluster-tests/job/PR-6532/2/execution/node/49/log/

It looks like linting each file creates `SCTConfiguration` object which runs `convert_name_to_ami_if_needed` - and somehow we started to hit the request limit.

This causes our PR's pipeline to fail.

**Comment by fruch** [comment]
we probably cache this call...

**Comment by soyacz** [comment]
@fruch I think you already did that. Closing - please reopen if I'm wrong.
