### ISSUE TITLE
`disrupt_toggle_audit_syslog` nemesis may fail due to timing issues in multi-DC setups

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-cluster-tests#6619]
### Prerequisites

* [x] Are you rebased to master ?
* [ ] Is it reproducible ?
* [ ] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: master
* **scylla**: `2023.1.1-0.20230906.f4633ec973b0 with build-id b454e7a22f80cf71a33b2f39e47127225e8fbc13`

### Logs
* test_id: 2d6dee97-3401-4ce4-ba7b-d9fd8a622a57
* job log: [Argus](https://argus.scylladb.com/test/444c8f91-4d90-42fd-8d56-0fa8194ed7e0/runs?additionalRuns[]=2d6dee97-3401-4ce4-ba7b-d9fd8a622a57), [CI](https://jenkins.scylladb.com/job/scylla-staging/job/valerii/job/vp-EaR-longevity-kms-20gb-6h-multidc-test/12/)

### Description

Running the `disrupt_toggle_audit_syslog` nemesis may appear following error:
```
2023-09-19 23:29:28,564 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > Traceback (most recent call last):
2023-09-19 23:29:28,564 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 5030, in wrapper
2023-09-19 23:29:28,564 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     result = method(*args[1:], **kwargs)
2023-09-19 23:29:28,564 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4670, in disrupt_toggle_audit_syslog
2023-09-19 23:29:28,564 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     self._disrupt_toggle_audit(store="syslog")
2023-09-19 23:29:28,564 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4771, in _disrupt_toggle_audit
2023-09-19 23:29:28,564 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     raise AuditLogTestFailure("\n".join(errors))
2023-09-19 23:29:28,564 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > sdcm.exceptions.AuditLogTestFailure: Audit log is empty while should contain executed DDL (alter table) operation
```

But in logs we see following:
```
2023-09-19 23:28:58,395 f:common.py       l:1752 c:utils                p:DEBUG > Executing CQL 'ALTER TABLE audit_keyspace.audit_cf WITH read_repair_chance = 0.0' ...
2023-09-19 23:28:58,395 f:common.py       l:1760 c:utils                p:DEBUG > Executing CQL 'ALTER TABLE audit_keyspace.audit_cf WITH read_repair_chance = 0.0' ...
2023-09-19 23:28:58,502 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > WARN  23:28:58,294 Error creating netty channel to ip-10-4-3-116.eu-west-1.compute.internal/10.4.3.116:9042
2023-09-19 23:28:58,741 f:db_log_reader.py l:114  c:sdcm.db_log_reader   p:DEBUG > 2023-09-19T23:28:58+00:00 long-encrypt-at-rest-20gb-6h-multid-db-node-2d6dee97-3   !NOTICE | scylla-audit[22367]: "10.4.3.222:0", "DDL", "ONE", "audit_cf", "audit_keyspace", "ALTER TABLE audit_keyspace.audit_cf WITH read_repair_chance = 0.0", "10.4.2.89:0", "anonymous", "false"
```

So, looks like we have concurrency issue in the following piece of code:
```
audit_start = datetime.datetime.now()
query = f"ALTER TABLE {keyspace_name}.{table_name} WITH read_repair_chance = 0.0"
session.execute(query)
self.cluster.wait_for_schema_agreement()
audit_rows = audit.get_audit_log(from_datetime=audit_start, category="DDL", operation=query, limit_rows=10)
if not audit_rows:
    errors.append("Audit log is empty while should contain executed DDL (alter table) operation")
```

Where `audit_start` may be newer than the expected message timing in different region node.

### Steps to Reproduce

1. Run `disrupt_toggle_audit_syslog` nemesis in multi-DC setup where there may be some time skew.
2. See above mentioned error

**Expected behavior:** Audit nemesis must work.

**Actual behavior:** Audit read command may not catch the existing DB node message.

**Comment by vponomaryov** [comment]
@soyacz ^
