### ISSUE TITLE
start_grafana_monitoring: Error: Grafana container failed to start

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla-cluster-tests#664]
SCT version: f1d1bcd664c01aaa0254f2739de5dee5967c6b96

Test job: http://jenkins.cloudius-systems.com:8080/job/scylla-staging-scale-cluster-test-clone-amos/label=aws-scylla-qa-builder1/30/console

I touched this problem in scale-test multiple times, I would try to find the real error, the error `Error: Grafana container failed to start` from start-all.sh isn't clear.

I'm trying to workaround this issue by retry.

```
18:48:51 [52.55.250.219] Running '/bin/ssh  -a -x   -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpIXYg8J -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l centos -p 22 -i /var/tmp/cluster-scale-test-sct-c54bb2fc.pem 52.55.250.219 "sudo bash -ce '
18:48:51 cd /var/lib/scylla/scylla-grafana-monitoring-branch-2.0
18:48:51 sudo systemctl start docker
18:48:51 mkdir -p /var/lib/scylla/scylla-grafana-monitoring-data
18:48:51 chmod 777 /var/lib/scylla/scylla-grafana-monitoring-data
18:48:51 ./start-all.sh -s /var/lib/scylla/scylla-grafana-monitoring-branch-2.0/config/scylla_servers.yml -n /var/lib/scylla/scylla-grafana-monitoring-branch-2.0/config/node_exporter_servers.yml -d /var/lib/scylla/scylla-grafana-monitoring-data -v 2.3
18:48:51 '"'
18:48:58 [52.55.250.219] [stdout] Wait for alert manager container to start.Loading prometheus data from /var/lib/scylla/scylla-grafana-monitoring-data
18:48:58 [52.55.250.219] [stdout] 335cbcffdebb0729fbde9d106001dc249e823e89afc98e638c42d1e6cd967918
....
18:49:39 [52.55.250.219] [stdout] Waiting for Grafana container to start........Error: Grafana container failed to start
18:49:39 
18:49:39 Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado/core/test.py:449
18:49:39 Traceback (most recent call last):
18:49:39   File "/jenkins/slave/workspace/scylla-staging-scale-cluster-test-clone-amos/label/aws-scylla-qa-builder1/grow_cluster_test.py", line 156, in test_grow_x_to_y
18:49:39     stress_cmd=self.get_stress_cmd())
18:49:39   File "/jenkins/slave/workspace/scylla-staging-scale-cluster-test-clone-amos/label/aws-scylla-qa-builder1/grow_cluster_test.py", line 99, in grow_cluster
18:49:39     self.add_nodes(add_node_cnt)
18:49:39   File "/jenkins/slave/workspace/scylla-staging-scale-cluster-test-clone-amos/label/aws-scylla-qa-builder1/grow_cluster_test.py", line 82, in add_nodes
18:49:39     self.monitors.reconfigure_scylla_monitoring()
18:49:39   File "/jenkins/slave/workspace/scylla-staging-scale-cluster-test-clone-amos/label/aws-scylla-qa-builder1/sdcm/cluster.py", line 2426, in reconfigure_scylla_monitoring
18:49:39     self.start_scylla_monitoring(node)
18:49:39   File "/jenkins/slave/workspace/scylla-staging-scale-cluster-test-clone-amos/label/aws-scylla-qa-builder1/sdcm/cluster.py", line 2445, in start_scylla_monitoring
18:49:39     node.remoter.run("sudo bash -ce '%s'" % run_script, verbose=True)
18:49:39   File "/jenkins/slave/workspace/scylla-staging-scale-cluster-test-clone-amos/label/aws-scylla-qa-builder1/sdcm/remote.py", line 906, in run
18:49:39     watch_stdout_pattern=watch_stdout_pattern)
18:49:39   File "/jenkins/slave/workspace/scylla-staging-scale-cluster-test-clone-amos/label/aws-scylla-qa-builder1/sdcm/remote.py", line 847, in _run
18:49:39     watch_stdout_pattern=watch_stdout_pattern)
18:49:39   File "/jenkins/slave/workspace/scylla-staging-scale-cluster-test-clone-amos/label/aws-scylla-qa-builder1/sdcm/remote.py", line 805, in ssh_run
18:49:39     raise process.CmdError(cmd, sp.result)
18:49:39 CmdError: Command '/bin/ssh  -a -x   -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpIXYg8J -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l centos -p 22 -i /var/tmp/cluster-scale-test-sct-c54bb2fc.pem 52.55.250.219 "sudo bash -ce '
18:49:39 cd /var/lib/scylla/scylla-grafana-monitoring-branch-2.0
18:49:39 sudo systemctl start docker
18:49:39 mkdir -p /var/lib/scylla/scylla-grafana-monitoring-data
18:49:39 chmod 777 /var/lib/scylla/scylla-grafana-monitoring-data
18:49:39 ./start-all.sh -s /var/lib/scylla/scylla-grafana-monitoring-branch-2.0/config/scylla_servers.yml -n /var/lib/scylla/scylla-grafana-monitoring-branch-2.0/config/node_exporter_servers.yml -d /var/lib/scylla/scylla-grafana-monitoring-data -v 2.3
18:49:39 '"' failed (rc=1)
18:49:39 
18:49:39 Cleaning up resources used in the test
```

@tzach @bentsi

**Comment by amoskong** [comment]
Another job also failed:
http://jenkins.cloudius-systems.com:8080/job/scylla-staging-scale-cluster-test-clone-amos/label=aws-scylla-qa-builder1/31/artifact/latest/job.log

```
2018-10-20 12:40:21,771 remote           L0194 DEBUG| [54.164.87.68] [stdout] Waiting for Grafana container to start........Error: Grafana container failed to start
2018-10-20 12:40:21,782 stacktrace       L0036 ERROR|
2018-10-20 12:40:21,782 stacktrace       L0039 ERROR| Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado/core/test.py:449
2018-10-20 12:40:21,784 stacktrace       L0042 ERROR| Traceback (most recent call last):
2018-10-20 12:40:21,784 stacktrace       L0042 ERROR|   File "/jenkins/slave/workspace/scylla-staging-scale-cluster-test-clone-amos/label/aws-scylla-qa-builder1/grow_cluster_test.py", line 156, in test_grow_x_to_y
2018-10-20 12:40:21,785 stacktrace       L0042 ERROR|     stress_cmd=self.get_stress_cmd())
2018-10-20 12:40:21,785 stacktrace       L0042 ERROR|   File "/jenkins/slave/workspace/scylla-staging-scale-cluster-test-clone-amos/label/aws-scylla-qa-builder1/grow_cluster_test.py", line 99, in grow_cluster
2018-10-20 12:40:21,785 stacktrace       L0042 ERROR|     self.add_nodes(add_node_cnt)
2018-10-20 12:40:21,785 stacktrace       L0042 ERROR|   File "/jenkins/slave/workspace/scylla-staging-scale-cluster-test-clone-amos/label/aws-scylla-qa-builder1/grow_cluster_test.py", line 82, in add_nodes
2018-10-20 12:40:21,785 stacktrace       L0042 ERROR|     self.monitors.reconfigure_scylla_monitoring()
2018-10-20 12:40:21,785 stacktrace       L0042 ERROR|   File "/jenkins/slave/workspace/scylla-staging-scale-cluster-test-clone-amos/label/aws-scylla-qa-builder1/sdcm/cluster.py", line 2426, in reconfigure_scylla_monitoring
2018-10-20 12:40:21,786 stacktrace       L0042 ERROR|     self.start_scylla_monitoring(node)
2018-10-20 12:40:21,787 stacktrace       L0042 ERROR|   File "/jenkins/slave/workspace/scylla-staging-scale-cluster-test-clone-amos/label/aws-scylla-qa-builder1/sdcm/cluster.py", line 2445, in start_scylla_monitoring
2018-10-20 12:40:21,787 stacktrace       L0042 ERROR|     node.remoter.run("sudo bash -ce '%s'" % run_script, verbose=True)
2018-10-20 12:40:21,787 stacktrace       L0042 ERROR|   File "/jenkins/slave/workspace/scylla-staging-scale-cluster-test-clone-amos/label/aws-scylla-qa-builder1/sdcm/remote.py", line 906, in run
2018-10-20 12:40:21,787 stacktrace       L0042 ERROR|     watch_stdout_pattern=watch_stdout_pattern)
2018-10-20 12:40:21,788 stacktrace       L0042 ERROR|   File "/jenkins/slave/workspace/scylla-staging-scale-cluster-test-clone-amos/label/aws-scylla-qa-builder1/sdcm/remote.py", line 847, in _run
2018-10-20 12:40:21,788 stacktrace       L0042 ERROR|     watch_stdout_pattern=watch_stdout_pattern)
2018-10-20 12:40:21,788 stacktrace       L0042 ERROR|   File "/jenkins/slave/workspace/scylla-staging-scale-cluster-test-clone-amos/label/aws-scylla-qa-builder1/sdcm/remote.py", line 805, in ssh_run
2018-10-20 12:40:21,788 stacktrace       L0042 ERROR|     raise process.CmdError(cmd, sp.result)
2018-10-20 12:40:21,789 stacktrace       L0042 ERROR| CmdError: Command '/bin/ssh  -a -x   -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpuowyff -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l centos -p 22 -i /var/tmp/cluster-scale-test-sct-dbebf832.pem 54.164.87.68 "sudo bash -ce '
2018-10-20 12:40:21,789 stacktrace       L0042 ERROR| cd /var/lib/scylla/scylla-grafana-monitoring-branch-2.0
2018-10-20 12:40:21,789 stacktrace       L0042 ERROR| sudo systemctl start docker
2018-10-20 12:40:21,789 stacktrace       L0042 ERROR| mkdir -p /var/lib/scylla/scylla-grafana-monitoring-data
2018-10-20 12:40:21,790 stacktrace       L0042 ERROR| chmod 777 /var/lib/scylla/scylla-grafana-monitoring-data
2018-10-20 12:40:21,790 stacktrace       L0042 ERROR| ./start-all.sh -s /var/lib/scylla/scylla-grafana-monitoring-branch-2.0/config/scylla_servers.yml -n /var/lib/scylla/scylla-grafana-monitoring-branch-2.0/config/node_exporter_servers.yml -d /var/lib/scylla/scylla-grafana-monitoring-data -v 2.3
2018-10-20 12:40:21,790 stacktrace       L0042 ERROR| '"' failed (rc=1)
```

**Comment by tzach** [comment]
@amoskong do you have the logs from the Grafana docker container?
```
docker log agraf
```

**Comment by bentsi** [comment]
Hi Amos, 

Why do you think that this is an SCT issue? 
If you see Python stack trace, it doesn't always mean that this is a SCT issue.
In this case you need login to the server where the command failed and run the command that was suggested by @tzach

**Comment by amoskong** [comment]
Reproduce script:
```
while true; do 

cd /var/lib/scylla/scylla-grafana-monitoring-branch-2.0
sudo ./kill-all.sh
sudo ./start-all.sh -s /var/lib/scylla/scylla-grafana-monitoring-branch-2.0/config/scylla_servers.yml -n /var/lib/scylla/scylla-grafana-monitoring-branch-2.0/config/node_exporter_servers.yml -d /var/lib/scylla/scylla-grafana-monitoring-data -v 2.3 || break

done
```

Problem occurred in 6 times retry.  I tried 44 times to reproduce again.
Logs:
```
aprom
agraf
agraf
aalert
aalert
Wait for alert manager container to start.Loading prometheus data from /var/lib/scylla/scylla-grafana-monitoring-data
3f384df2c61a330b5ae0104f21fcbc59224974e72b315f58b11c5bf306ad101a
Wait for Prometheus container to start..f9da7709a070252c5bd8639bb4db905bbde1f728ab258b3a7cf6ce2a21e2c869
Waiting for Grafana container to start........Error: Grafana container failed to start
[centos@ip-172-16-1-213 scylla-grafana-monitoring-branch-2.0]$ sudo docker logs agraf
installing grafana-piechart-panel @ 1.3.3
from url: https://grafana.com/api/plugins/grafana-piechart-panel/versions/1.3.3/download
into: /var/lib/grafana/plugins
✔ Installed grafana-piechart-panel successfully 
Restart grafana after installing plugins . <service grafana-server restart>
Failed to send requesterrorGet https://grafana.com/api/plugins/repo/camptocamp-prometheus-alertmanager-datasource: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Error: ✗ Failed to send request. error: Get https://grafana.com/api/plugins/repo/camptocamp-prometheus-alertmanager-datasource: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
NAME:
   Grafana cli plugins install - install <plugin id> <plugin version (optional)>
USAGE:
   Grafana cli plugins install [arguments...]
[centos@ip-172-16-1-213 scylla-grafana-monitoring-branch-2.0]$ 
```

**Comment by amoskong** [comment]
On Sun, Oct 21, 2018 at 7:36 PM, Bentsi <notifications@github.com> wrote:

> Hi Amos,
>
> Why do you think that this is an SCT issue?
>
I certainly knew the root problem is caused by unstable external tool
(scylla-grafana-monitoring), this is why I CC tzach.
The problem was occurred in running SCT, it's not good to report a issue
for scylla-grafna-monitoring includes some SCT details.

> If you see Python stack trace, it doesn't always mean that this is a SCT
> issue.
>
We need the problem doesn't break the whole test. SCT can't assume that the
external tool works 100%. So SCT _has_ problem.
In the PAST (before your refactor), the monitor_setup doesn't has this
problem. So it's a SCT regression, please fix it.

> In this case you need login to the server where the command failed and run
> the command that was suggested by @tzach <https://github.com/tzach>
>
 The server was deleted when I see the problem. I rerun the job in the
weekend the env was deleted by Roy. I will rerun now.

**Comment by amoskong** [comment]
Fixed by pr #666

**Comment by bentsi** [comment]
Amos, I don't agree that this is an SCT issue, this is clearly a `scylla-grafana-monitoring` issue that should be reported but meantime we needed a workaround and you provided it. Thanks.

**Comment by amoskong** [comment]
You are right.
