### ISSUE TITLE
"BACKTRACE" event was created instead of "ABORTING_ON_SHARD"

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-cluster-tests#6654]
"BACKTRACE" event was created instead of "ABORTING_ON_SHARD"

```
< t:2023-10-01 20:35:10,517 f:db_log_reader.py l:114  c:sdcm.db_log_reader   p:DEBUG > 2023-10-01T20:35:10+00:00 rolling-upgrade-sla--ubuntu-jammy-db-node-df56520e-0-2     !INFO | scylla[24725]: Aborting on shard 2.
< t:2023-10-01 20:35:10,517 f:db_log_reader.py l:114  c:sdcm.db_log_reader   p:DEBUG > 2023-10-01T20:35:10+00:00 rolling-upgrade-sla--ubuntu-jammy-db-node-df56520e-0-2     !INFO | scylla[24725]: Backtrace:
< t:2023-10-01 20:35:10,518 f:db_log_reader.py l:114  c:sdcm.db_log_reader   p:DEBUG > 2023-10-01T20:35:10+00:00 rolling-upgrade-sla--ubuntu-jammy-db-node-df56520e-0-2     !INFO | scylla[24725]:   0x538df08
< t:2023-10-01 20:35:10,518 f:db_log_reader.py l:114  c:sdcm.db_log_reader   p:DEBUG > 2023-10-01T20:35:10+00:00 rolling-upgrade-sla--ubuntu-jammy-db-node-df56520e-0-2     !INFO | scylla[24725]:   0x53c0242
< t:2023-10-01 20:35:10,518 f:db_log_reader.py l:114  c:sdcm.db_log_reader   p:DEBUG > 2023-10-01T20:35:10+00:00 rolling-upgrade-sla--ubuntu-jammy-db-node-df56520e-0-2     !INFO | scylla[24725]:   /opt/scylladb/libreloc/libc.so.6+0x3cb1f
< t:2023-10-01 20:35:10,518 f:db_log_reader.py l:114  c:sdcm.db_log_reader   p:DEBUG > 2023-10-01T20:35:10+00:00 rolling-upgrade-sla--ubuntu-jammy-db-node-df56520e-0-2     !INFO | scylla[24725]:   /opt/scylladb/libreloc/libc.so.6+0x8ce5b
< t:2023-10-01 20:35:10,518 f:db_log_reader.py l:114  c:sdcm.db_log_reader   p:DEBUG > 2023-10-01T20:35:10+00:00 rolling-upgrade-sla--ubuntu-jammy-db-node-df56520e-0-2     !INFO | scylla[24725]:   /opt/scylladb/libreloc/libc.so.6+0x3ca75
< t:2023-10-01 20:35:10,518 f:db_log_reader.py l:114  c:sdcm.db_log_reader   p:DEBUG > 2023-10-01T20:35:10+00:00 rolling-upgrade-sla--ubuntu-jammy-db-node-df56520e-0-2     !INFO | scylla[24725]:   /opt/scylladb/libreloc/libc.so.6+0x267fb
< t:2023-10-01 20:35:10,519 f:db_log_reader.py l:114  c:sdcm.db_log_reader   p:DEBUG > 2023-10-01T20:35:10+00:00 rolling-upgrade-sla--ubuntu-jammy-db-node-df56520e-0-2     !INFO | scylla[24725]:   0x536fff2
< t:2023-10-01 20:35:10,519 f:db_log_reader.py l:114  c:sdcm.db_log_reader   p:DEBUG > 2023-10-01T20:35:10+00:00 rolling-upgrade-sla--ubuntu-jammy-db-node-df56520e-0-2     !INFO | scylla[24725]:   0x1f7663e
< t:2023-10-01 20:35:10,519 f:db_log_reader.py l:114  c:sdcm.db_log_reader   p:DEBUG > 2023-10-01T20:35:10+00:00 rolling-upgrade-sla--ubuntu-jammy-db-node-df56520e-0-2     !INFO | scylla[24725]:   0x4189b6a
< t:2023-10-01 20:35:10,519 f:db_log_reader.py l:114  c:sdcm.db_log_reader   p:DEBUG > 2023-10-01T20:35:10+00:00 rolling-upgrade-sla--ubuntu-jammy-db-node-df56520e-0-2     !INFO | scylla[24725]:   0x1f1ead0
< t:2023-10-01 20:35:10,519 f:db_log_reader.py l:114  c:sdcm.db_log_reader   p:DEBUG > 2023-10-01T20:35:10+00:00 rolling-upgrade-sla--ubuntu-jammy-db-node-df56520e-0-2     !INFO | scylla[24725]:   0x1f6598f
< t:2023-10-01 20:35:10,519 f:db_log_reader.py l:114  c:sdcm.db_log_reader   p:DEBUG > 2023-10-01T20:35:10+00:00 rolling-upgrade-sla--ubuntu-jammy-db-node-df56520e-0-2     !INFO | scylla[24725]:   0x1f2fb2a
< t:2023-10-01 20:35:10,519 f:db_log_reader.py l:114  c:sdcm.db_log_reader   p:DEBUG > 2023-10-01T20:35:10+00:00 rolling-upgrade-sla--ubuntu-jammy-db-node-df56520e-0-2     !INFO | scylla[24725]:   0x539e784
< t:2023-10-01 20:35:10,519 f:db_log_reader.py l:114  c:sdcm.db_log_reader   p:DEBUG > 2023-10-01T20:35:10+00:00 rolling-upgrade-sla--ubuntu-jammy-db-node-df56520e-0-2     !INFO | scylla[24725]:   0x539fa07
< t:2023-10-01 20:35:10,519 f:db_log_reader.py l:114  c:sdcm.db_log_reader   p:DEBUG > 2023-10-01T20:35:10+00:00 rolling-upgrade-sla--ubuntu-jammy-db-node-df56520e-0-2     !INFO | scylla[24725]:   0x53c06f1
< t:2023-10-01 20:35:10,520 f:db_log_reader.py l:114  c:sdcm.db_log_reader   p:DEBUG > 2023-10-01T20:35:10+00:00 rolling-upgrade-sla--ubuntu-jammy-db-node-df56520e-0-2     !INFO | scylla[24725]:   0x5370b7a
< t:2023-10-01 20:35:10,520 f:db_log_reader.py l:114  c:sdcm.db_log_reader   p:DEBUG > 2023-10-01T20:35:10+00:00 rolling-upgrade-sla--ubuntu-jammy-db-node-df56520e-0-2     !INFO | scylla[24725]:   /opt/scylladb/libreloc/libc.so.6+0x8b12c
< t:2023-10-01 20:35:10,520 f:db_log_reader.py l:114  c:sdcm.db_log_reader   p:DEBUG > 2023-10-01T20:35:10+00:00 rolling-upgrade-sla--ubuntu-jammy-db-node-df56520e-0-2     !INFO | scylla[24725]:   /opt/scylladb/libreloc/libc.so.6+0x10cbbf
< t:2023-10-01 20:35:10,520 f:base.py         l:281  c:sdcm.sct_events.base p:DEBUG > (DatabaseLogEvent Severity.ERROR) period_type=one-time event_id=396d604d-8bcb-4ec9-9757-43cb60eb5b71: type=BACKTRACE regex=^(?!.*audit:).*backtrace line_number=20662 node=rolling-upgrade-sla--ubuntu-jammy-db-node-df56520e-0-2
< t:2023-10-01 20:35:10,520 f:base.py         l:281  c:sdcm.sct_events.base p:DEBUG > 2023-10-01T20:35:10+00:00 rolling-upgrade-sla--ubuntu-jammy-db-node-df56520e-0-2     !INFO | scylla[24725]: Backtrace:
< t:2023-10-01 20:35:10,520 f:base.py         l:281  c:sdcm.sct_events.base p:DEBUG > 0x538df08
< t:2023-10-01 20:35:10,520 f:base.py         l:281  c:sdcm.sct_events.base p:DEBUG > 0x53c0242
< t:2023-10-01 20:35:10,520 f:base.py         l:281  c:sdcm.sct_events.base p:DEBUG > /libreloc/libc.so.6+0x3cb1f
< t:2023-10-01 20:35:10,520 f:base.py         l:281  c:sdcm.sct_events.base p:DEBUG > /libreloc/libc.so.6+0x8ce5b
< t:2023-10-01 20:35:10,520 f:base.py         l:281  c:sdcm.sct_events.base p:DEBUG > /libreloc/libc.so.6+0x3ca75
< t:2023-10-01 20:35:10,520 f:base.py         l:281  c:sdcm.sct_events.base p:DEBUG > /libreloc/libc.so.6+0x267fb
< t:2023-10-01 20:35:10,520 f:base.py         l:281  c:sdcm.sct_events.base p:DEBUG > 0x536fff2
< t:2023-10-01 20:35:10,520 f:base.py         l:281  c:sdcm.sct_events.base p:DEBUG > 0x1f7663e
< t:2023-10-01 20:35:10,520 f:base.py         l:281  c:sdcm.sct_events.base p:DEBUG > 0x4189b6a
< t:2023-10-01 20:35:10,520 f:base.py         l:281  c:sdcm.sct_events.base p:DEBUG > 0x1f1ead0
< t:2023-10-01 20:35:10,520 f:base.py         l:281  c:sdcm.sct_events.base p:DEBUG > 0x1f6598f
< t:2023-10-01 20:35:10,520 f:base.py         l:281  c:sdcm.sct_events.base p:DEBUG > 0x1f2fb2a
< t:2023-10-01 20:35:10,520 f:base.py         l:281  c:sdcm.sct_events.base p:DEBUG > 0x539e784
< t:2023-10-01 20:35:10,520 f:base.py         l:281  c:sdcm.sct_events.base p:DEBUG > 0x539fa07
< t:2023-10-01 20:35:10,520 f:base.py         l:281  c:sdcm.sct_events.base p:DEBUG > 0x53c06f1
< t:2023-10-01 20:35:10,520 f:base.py         l:281  c:sdcm.sct_events.base p:DEBUG > 0x5370b7a
< t:2023-10-01 20:35:10,520 f:base.py         l:281  c:sdcm.sct_events.base p:DEBUG > /libreloc/libc.so.6+0x8b12c
< t:2023-10-01 20:35:10,520 f:base.py         l:281  c:sdcm.sct_events.base p:DEBUG > /libreloc/libc.so.6+0x10cbbf marked to not publish
```

## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

*Describe your issue in detail and steps it took to produce it.*

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Kernel Version: 6.2.0-1014-gcp
Scylla version (or git commit hash): `5.2.9-20230920.5709d0043978` with build-id `686601fd1656c6724f7f042163b9285bf3efd582`
Target Scylla version (or git commit hash): `2023.1.2-20231001.646df23cc4b3` with build-id `367fcf1672d44f5cbddc88f946cf272e2551b85a`

Cluster size: 3 nodes (n1-highmem-8)

Scylla Nodes used in this run:
- rolling-upgrade-sla--ubuntu-jammy-db-node-df56520e-0-3 (34.75.127.122 | 10.142.0.171) (shards: 7)
- rolling-upgrade-sla--ubuntu-jammy-db-node-df56520e-0-2 (104.196.206.137 | 10.142.0.167) (shards: 7)
- rolling-upgrade-sla--ubuntu-jammy-db-node-df56520e-0-1 (34.73.123.21 | 10.142.0.161) (shards: 7)

OS / Image: `https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/family/ubuntu-2204-lts` (gce: us-east1)

Test: `rolling-upgrade-with-sla-test`
Test id: `df56520e-c627-428a-a44d-19cfe85e5e7a`
Test name: `enterprise-2023.1/rolling-upgrade/rolling-upgrade-with-sla-test`
Test config file(s):

- [generic-rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/6fca1327efdcb1fc1629a6544d092e6ed3863b53/test-cases/upgrades/generic-rolling-upgrade.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor df56520e-c627-428a-a44d-19cfe85e5e7a`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=df56520e-c627-428a-a44d-19cfe85e5e7a)
- Show all stored logs command: `$ hydra investigate show-logs df56520e-c627-428a-a44d-19cfe85e5e7a`

## Logs:
- **db-cluster-df56520e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/df56520e-c627-428a-a44d-19cfe85e5e7a/20231001_214542/db-cluster-df56520e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/df56520e-c627-428a-a44d-19cfe85e5e7a/20231001_214542/db-cluster-df56520e.tar.gz)
- **sct-runner-events-df56520e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/df56520e-c627-428a-a44d-19cfe85e5e7a/20231001_214542/sct-runner-events-df56520e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/df56520e-c627-428a-a44d-19cfe85e5e7a/20231001_214542/sct-runner-events-df56520e.tar.gz)
- **sct-df56520e.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/df56520e-c627-428a-a44d-19cfe85e5e7a/20231001_214542/sct-df56520e.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/df56520e-c627-428a-a44d-19cfe85e5e7a/20231001_214542/sct-df56520e.log.tar.gz)
- **monitor-set-df56520e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/df56520e-c627-428a-a44d-19cfe85e5e7a/20231001_214542/monitor-set-df56520e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/df56520e-c627-428a-a44d-19cfe85e5e7a/20231001_214542/monitor-set-df56520e.tar.gz)
- **loader-set-df56520e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/df56520e-c627-428a-a44d-19cfe85e5e7a/20231001_214542/loader-set-df56520e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/df56520e-c627-428a-a44d-19cfe85e5e7a/20231001_214542/loader-set-df56520e.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2023.1/job/rolling-upgrade/job/rolling-upgrade-with-sla-test/32/)
[Argus](https://argus.scylladb.com/test/5f030eae-214c-44b1-a26f-2c2d44056182/runs?additionalRuns[]=df56520e-c627-428a-a44d-19cfe85e5e7a)
</details>

**Comment by fruch** [comment]
@juliayakovlev why does it make any difference which one was being raised ? both should fail the test.

**Comment by fruch** [comment]
as I suspected:
```
< t:2023-10-01 20:35:34,529 f:db_log_reader.py l:201  c:sdcm.db_log_reader   p:ERROR > failed to read db log < t:2023-10-01 20:35:34,529 f:db_log_reader.py l:201  c:sdcm.db_log_reader   p:ERROR > failed to read db log
< t:2023-10-01 20:35:34,529 f:db_log_reader.py l:201  c:sdcm.db_log_reader   p:ERROR > Traceback (most recent call last):
< t:2023-10-01 20:35:34,529 f:db_log_reader.py l:201  c:sdcm.db_log_reader   p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/db_log_reader.py", line 197, in run
< t:2023-10-01 20:35:34,529 f:db_log_reader.py l:201  c:sdcm.db_log_reader   p:ERROR >     self._read_and_publish_events()
< t:2023-10-01 20:35:34,529 f:db_log_reader.py l:201  c:sdcm.db_log_reader   p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/db_log_reader.py", line 176, in _read_and_publish_events
< t:2023-10-01 20:35:34,529 f:db_log_reader.py l:201  c:sdcm.db_log_reader   p:ERROR >     scylla_debug_info = self.get_scylla_debuginfo_file()
< t:2023-10-01 20:35:34,529 f:db_log_reader.py l:201  c:sdcm.db_log_reader   p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/db_log_reader.py", line 251, in get_scylla_debuginfo_file
< t:2023-10-01 20:35:34,529 f:db_log_reader.py l:201  c:sdcm.db_log_reader   p:ERROR >     raise Exception("Couldn't find scylla debug information")
< t:2023-10-01 20:35:34,529 f:db_log_reader.py l:201  c:sdcm.db_log_reader   p:ERROR > Exception: Couldn't find scylla debug information
```

**Comment by fruch** [comment]
@juliayakovlev 

I've backported:
https://github.com/scylladb/scylla-cluster-tests/pull/6219

we still need to investigate why debug info wasn't available

**Comment by fruch** [comment]
we install symbols just for the base
```
< t:2023-10-01 18:38:31,931 f:base.py         l:142  c:RemoteLibSSH2CmdRunner p:DEBUG > Command "sudo apt-get install -y scylla-server-dbg=5.2.9\*" finished with status 0
```

I think that after upgrade we might no have symbols

**Comment by juliayakovlev** [comment]
![aborting_decode_error](https://github.com/scylladb/scylla-cluster-tests/assets/34435448/8960b3c9-f728-4923-82f6-be1290218f4e)

**Comment by juliayakovlev** [comment]
But it received with Scylla 2023

**Comment by fruch** [comment]
this is solved, the fix is backport
the issue with decoding, isn't related
