### ISSUE TITLE
[Azure] run command doesn't work with `allowExtensionOperations: false`

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#6656]
seems like the mix of disabling extensions and using `run command` doesn't work:
```
Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 5035, in wrapper
    result = method(*args[1:], **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 845, in disrupt_multiple_hard_reboot_node
    self.reboot_node(target_node=self.target_node, hard=True)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/sct_events/group_common_events.py", line 274, in inner_func
    return func(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3610, in reboot_node
    target_node.reboot(hard=hard, verify_ssh=verify_ssh)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 1066, in reboot
    self.hard_reboot()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster_azure.py", line 119, in hard_reboot
    self._instance.reboot(wait=True, hard=True)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/provision/provisioner.py", line 94, in reboot
    self._provisioner.reboot_instance(self.name, wait, hard)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/provision/azure/provisioner.py", line 157, in reboot_instance
    self._vm_provider.reboot(name, wait, hard)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/provision/azure/virtual_machine_provider.py", line 150, in reboot
    self.run_command(name, f"reboot {flags}")
  File "/home/ubuntu/scylla-cluster-tests/sdcm/provision/azure/virtual_machine_provider.py", line 233, in run_command
    result = self._azure_service.compute.virtual_machines.begin_run_command(
  File "/usr/local/lib/python3.10/site-packages/azure/mgmt/compute/v2021_07_01/operations/_virtual_machines_operations.py", line 2492, in begin_run_command
    raw_result = self._run_command_initial(
  File "/usr/local/lib/python3.10/site-packages/azure/mgmt/compute/v2021_07_01/operations/_virtual_machines_operations.py", line 2445, in _run_command_initial
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/usr/local/lib/python3.10/site-packages/azure/core/exceptions.py", line 112, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: (OperationNotAllowed) This operation cannot be performed when extension operations are disallowed. To allow, please ensure VM Agent is installed on the VM and the osProfile.allowExtensionOperations property is true.
Code: OperationNotAllowed
Message: This operation cannot be performed when extension operations are disallowed. To allow, please ensure VM Agent is installed on the VM and the osProfile.allowExtensionOperations property is true.
```

**Comment by fruch** [comment]
@soyacz  look like we shoot ourself in the leg here...

back to the drawing board, on one  of them (don't know which one)

**Comment by soyacz** [comment]
> @soyacz look like we shoot ourself in the leg here...
> 
> back to the drawing board, on one of them (don't know which one)

I'd opt to bring back extensions and disable auditd (or check if we can prevent only this one) or make auditd logs to not be collected.

From the other hand, we could change AzureNode to run `reboot -ff` instead calling `instance.reboot`

**Comment by fruch** [comment]
> > @soyacz look like we shoot ourself in the leg here...
> > back to the drawing board, on one of them (don't know which one)
> 
> I'd opt to bring back extensions and disable auditd (or check if we can prevent only this one) or make auditd logs to not be collected.
> 
> From the other hand, we could change AzureNode to run `reboot -ff` instead calling `instance.reboot`

disabling specific extension is a bit more complicated, and I was waiting for the right permission for doing so.
I think moving to doing reboot with ssh might be a quicker path...

**Comment by soyacz** [comment]
> disabling specific extension is a bit more complicated, and I was waiting for the right permission for doing so. I think moving to doing reboot with ssh might be a quicker path...

As a quick win we can do it. Anyway I'd opt to disable `auditd` process (maybe later during Scylla setup) or tweak logging to not collect these

**Comment by fruch** [comment]
it's

> > disabling specific extension is a bit more complicated, and I was waiting for the right permission for doing so. I think moving to doing reboot with ssh might be a quicker path...
> 
> As a quick win we can do it. Anyway I'd opt to disable `auditd` process (maybe later during Scylla setup) or tweak logging to not collect these

it's problematic, since the install of auditd happen on it's own, not straight at boot
