### ISSUE TITLE
ubuntu 14.04: cassandra_stress_exporter fails to connect with collectd

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla-cluster-tests#668]
```
16:06:00 GCE Cluster rolling-upgrade-u14-3-0-loader-set-d09f7d71 | Image: ubuntu-1404-trusty-v20180722 | Root Disk: pd-standard 50 GB | Type: n1-standard-2: Stress script content:
16:06:00 mkfifo /tmp/cs_write_pipe_$1_$2; cat /tmp/cs_write_pipe_$1_$2|python /usr/bin/cassandra_stress_exporter write & cassandra-stress write no-warmup cl=QUORUM n=10000000 -schema keyspace=keyspace$2 'replication(factor=3) compression=LZ4Compressor' -port jmx=6868 -mode cql3 native compression=lz4 -rate threads=1000 -pop seq=1..10000000 -log interval=5 -node 10.240.0.145|tee /tmp/cs_write_pipe_$1_$2; pkill -P $$ -f cassandra_stress_exporter; rm -f /tmp/cs_write_pipe_$1_$2
16:06:00 GCE Cluster rolling-upgrade-u14-3-0-loader-set-d09f7d71 | Image: ubuntu-1404-trusty-v20180722 | Root Disk: pd-standard 50 GB | Type: n1-standard-2: cassandra-stress log: /jenkins/slave/workspace/scylla-3.0/3.0-test/scylla-rolling-upgrade-ubuntu-14.04-test/base_version/2.3/label/gce3-qavpc/version_desc/3-0/job-2018-10-22T07.48-e00334c/test-results/1-upgrade_test.py:UpgradeTest.test_rolling_upgrade/data/rolling-upgrade-u14-3-0-loader-set-d09f7d71/cassandra-stress-l0-c0-d0040cf7-449e-4a8c-8bfd-64463cccb592.log
16:06:00 Remote [scylla-test@35.190.142.33]: Send files (src) /var/tmp/avocado_scriptufulSt/run_cassandra_stress.sh -> (dst) /home/scylla-test
16:06:00 Remote [scylla-test@35.190.142.33]: Running 'chmod +x /home/scylla-test/run_cassandra_stress.sh'
16:06:00 [35.190.142.33] Running '/bin/ssh -tt -a -x  -o ControlPath=/var/tmp/ssh-masterRtHS7Z/socket -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpDSW5g0 -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l scylla-test -p 22 -i /jenkins/.ssh/scylla-test 35.190.142.33 "chmod +x /home/scylla-test/run_cassandra_stress.sh"'
16:06:00 [35.190.142.33] [stderr] Shared connection to 35.190.142.33 closed.
16:06:00 Remote [scylla-test@35.190.142.33]: Running 'echo TAG: loader_idx:0-cpu_idx:0-keyspace_idx:1; /home/scylla-test/run_cassandra_stress.sh 0 1'
16:06:00 [35.190.142.33] Running '/bin/ssh -tt -a -x  -o ControlPath=/var/tmp/ssh-masterRtHS7Z/socket -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpDSW5g0 -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l scylla-test -p 22 -i /jenkins/.ssh/scylla-test 35.190.142.33 "echo TAG: loader_idx:0-cpu_idx:0-keyspace_idx:1; /home/scylla-test/run_cassandra_stress.sh 0 1"'
16:06:00 [35.190.142.33] [stdout] TAG: loader_idx:0-cpu_idx:0-keyspace_idx:1
16:06:00 [35.190.142.33] [stdout] Traceback (most recent call last):
16:06:00 [35.190.142.33] [stdout]   File "/usr/bin/cassandra_stress_exporter", line 37, in <module>
16:06:00 [35.190.142.33] [stdout]     server.connect('/var/run/collectd-unixsock')
16:06:00 [35.190.142.33] [stdout]   File "/usr/lib/python2.7/socket.py", line 224, in meth
16:06:00 [35.190.142.33] [stdout]     return getattr(self._sock,name)(*args)
16:06:00 [35.190.142.33] [stdout] socket.error: [Errno 2] No such file or directory
16:06:01 [35.190.142.33] [stdout] Exception in thread "main" java.lang.UnsupportedClassVersionError: org/apache/cassandra/stress/Stress : Unsupported major.minor version 52.0
16:06:01 [35.190.142.33] [stdout] 	at java.lang.ClassLoader.defineClass1(Native Method)
16:06:01 [35.190.142.33] [stdout] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:808)
16:06:01 [35.190.142.33] [stdout] 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
16:06:01 [35.190.142.33] [stdout] 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
16:06:01 [35.190.142.33] [stdout] 	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
16:06:01 [35.190.142.33] [stdout] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
16:06:01 [35.190.142.33] [stdout] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
16:06:01 [35.190.142.33] [stdout] 	at java.security.AccessController.doPrivileged(Native Method)
16:06:01 [35.190.142.33] [stdout] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
16:06:01 [35.190.142.33] [stdout] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:430)
16:06:01 [35.190.142.33] [stdout] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:323)
16:06:01 [35.190.142.33] [stdout] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
16:06:01 [35.190.142.33] [stdout] 	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
```

**Comment by amoskong** [comment]
collectd service is running.
```
~$ sudo service collectd status
 * collectd is running


$ cat /etc/collectd/collectd.conf

LoadPlugin network
LoadPlugin disk
LoadPlugin interface
LoadPlugin unixsock
LoadPlugin df
LoadPlugin processes
<Plugin network>
        Listen "127.0.0.1" "25826"
        Server "127.0.0.1" "65534"
        Forward true
</Plugin>
<Plugin disk>
</Plugin>
<Plugin interface>
</Plugin>
<Plugin "df">
  FSType "xfs"
  IgnoreSelected false
</Plugin>
<Plugin unixsock>
    SocketFile "/var/run/collectd-unixsock"
    SocketPerms "0666"
</Plugin>
<Plugin processes>
    Process "scylla"
</Plugin>
```

**Comment by amoskong** [comment]
Fixed this problem by update the SocketPerms to "0770", referencing to http://manpages.ubuntu.com/manpages/trusty/man5/collectd-unixsock.5.html
