### ISSUE TITLE
artifacts-ami-arm-test: Failed with 

### ISSUE THREAD

**Issue by yaronkaikov** [scylladb/scylla-cluster-tests#6699]
https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-ami-arm-test/188/consoleFull

```
13:12:17  < t:2023-10-19 10:12:17,358 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2023-10-19 10:12:17.354: (InfoEvent Severity.NORMAL) period_type=not-set event_id=ecc482d7-6c23-4d82-a449-921034e7367a: message=TEST_START test_id=bfb1bccb-069a-4c12-9136-1033a779ee7e
13:12:20  < t:2023-10-19 10:12:19,541 f:cluster.py      l:3219 c:sdcm.cluster         p:INFO  > Cluster artifacts-ami-jenkins-db-cluster-bfb1bccb (AMI: ['ami-0ac21b0789acae111'] Type: im4gn.xlarge): Init nodes
13:12:20  /usr/local/lib/python3.10/site-packages/elasticsearch/connection/http_urllib3.py:209: UserWarning: Connecting to https://746f0ad652a3447d83b1572f657c67cb.us-east-1.aws.found.io:9243/ using SSL with verify_certs=False is insecure.
13:12:20    warnings.warn(
13:12:20  < t:2023-10-19 10:12:19,977 f:cluster_aws.py  l:359  c:sdcm.cluster         p:INFO  > Cluster artifacts-ami-jenkins-db-cluster-bfb1bccb (AMI: ['ami-0ac21b0789acae111'] Type: im4gn.xlarge): Found no provisioned instances. Provision them.
13:12:20  < t:2023-10-19 10:12:19,977 f:cluster_aws.py  l:218  c:sdcm.cluster         p:INFO  > Cluster artifacts-ami-jenkins-db-cluster-bfb1bccb (AMI: ['ami-0ac21b0789acae111'] Type: im4gn.xlarge): Create on_demand instance(s)
13:12:31  < t:2023-10-19 10:12:30,533 f:tester.py       l:1266 c:ArtifactsTest        p:WARNING > Failed creating a Scylla AWS cluster: An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 4): We currently do not have sufficient im4gn.xlarge capacity in the Availability Zone you requested (us-east-1c). Our system will be working on provisioning additional capacity. You can currently get im4gn.xlarge capacity by not specifying an Availability Zone in your request or choosing us-east-1b, us-east-1d.
13:12:31  < t:2023-10-19 10:12:30,540 f:cluster.py      l:3219 c:sdcm.cluster         p:INFO  > Cluster artifacts-ami-jenkins-db-cluster-bfb1bccb (AMI: ['ami-0ac21b0789acae111'] Type: im4gn.xlarge): Init nodes
13:12:31  < t:2023-10-19 10:12:31,453 f:cluster_aws.py  l:359  c:sdcm.cluster         p:INFO  > Cluster artifacts-ami-jenkins-db-cluster-bfb1bccb (AMI: ['ami-0ac21b0789acae111'] Type: im4gn.xlarge): Found no provisioned instances. Provision them.
13:12:31  < t:2023-10-19 10:12:31,454 f:cluster_aws.py  l:218  c:sdcm.cluster         p:INFO  > Cluster artifacts-ami-jenkins-db-cluster-bfb1bccb (AMI: ['ami-0ac21b0789acae111'] Type: im4gn.xlarge): Create on_demand instance(s)
13:12:47  < t:2023-10-19 10:12:45,585 f:tester.py       l:1266 c:ArtifactsTest        p:WARNING > Failed creating a Scylla AWS cluster: An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 4): We currently do not have sufficient im4gn.xlarge capacity in the Availability Zone you requested (us-east-1b). Our system will be working on provisioning additional capacity. You can currently get im4gn.xlarge capacity by not specifying an Availability Zone in your request or choosing us-east-1c, us-east-1d.
13:12:47  < t:2023-10-19 10:12:45,592 f:cluster.py      l:3219 c:sdcm.cluster         p:INFO  > Cluster artifacts-ami-jenkins-db-cluster-bfb1bccb (AMI: ['ami-0ac21b0789acae111'] Type: im4gn.xlarge): Init nodes
13:12:47  < t:2023-10-19 10:12:46,492 f:cluster_aws.py  l:359  c:sdcm.cluster         p:INFO  > Cluster artifacts-ami-jenkins-db-cluster-bfb1bccb (AMI: ['ami-0ac21b0789acae111'] Type: im4gn.xlarge): Found no provisioned instances. Provision them.
13:12:47  < t:2023-10-19 10:12:46,492 f:cluster_aws.py  l:218  c:sdcm.cluster         p:INFO  > Cluster artifacts-ami-jenkins-db-cluster-bfb1bccb (AMI: ['ami-0ac21b0789acae111'] Type: im4gn.xlarge): Create on_demand instance(s)
13:13:00  < t:2023-10-19 10:12:59,123 f:tester.py       l:1266 c:ArtifactsTest        p:WARNING > Failed creating a Scylla AWS cluster: An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 4): We currently do not have sufficient im4gn.xlarge capacity in the Availability Zone you requested (us-east-1d). Our system will be working on provisioning additional capacity. You can currently get im4gn.xlarge capacity by not specifying an Availability Zone in your request or choosing us-east-1b, us-east-1c.
13:13:00  E
13:13:00  ======================================================================
13:13:00  ERROR: test_scylla_service (artifacts_test.ArtifactsTest)
13:13:00  ----------------------------------------------------------------------
13:13:00  Traceback (most recent call last):
13:13:00    File "/tmp/jenkins/workspace/scylla-master/artifacts/artifacts-ami-arm-test/scylla-cluster-tests/artifacts_test.py", line 45, in setUp
13:13:00      super().setUp()
13:13:00    File "/tmp/jenkins/workspace/scylla-master/artifacts/artifacts-ami-arm-test/scylla-cluster-tests/sdcm/tester.py", line 165, in wrapper
13:13:00      return method(*args, **kwargs)
13:13:00    File "/tmp/jenkins/workspace/scylla-master/artifacts/artifacts-ami-arm-test/scylla-cluster-tests/sdcm/utils/decorators.py", line 119, in inner
13:13:00      res = func(*args, **kwargs)
13:13:00    File "/tmp/jenkins/workspace/scylla-master/artifacts/artifacts-ami-arm-test/scylla-cluster-tests/sdcm/tester.py", line 827, in setUp
13:13:00      self.init_resources()
13:13:00    File "/tmp/jenkins/workspace/scylla-master/artifacts/artifacts-ami-arm-test/scylla-cluster-tests/sdcm/tester.py", line 1852, in init_resources
13:13:00      self.get_cluster_aws(loader_info=loader_info, db_info=db_info,
13:13:00    File "/tmp/jenkins/workspace/scylla-master/artifacts/artifacts-ami-arm-test/scylla-cluster-tests/sdcm/tester.py", line 1322, in get_cluster_aws
13:13:00      self.db_cluster = create_cluster(db_type)
13:13:00    File "/tmp/jenkins/workspace/scylla-master/artifacts/artifacts-ami-arm-test/scylla-cluster-tests/sdcm/tester.py", line 1284, in create_cluster
13:13:00      return _create_auto_zone_scylla_aws_cluster()
13:13:00    File "/tmp/jenkins/workspace/scylla-master/artifacts/artifacts-ami-arm-test/scylla-cluster-tests/sdcm/tester.py", line 1270, in _create_auto_zone_scylla_aws_cluster
13:13:00      raise CriticalTestFailure(f"Failed creating a Scylla AWS cluster: {capacity_errors}")
13:13:00  sdcm.tester.CriticalTestFailure: Failed creating a Scylla AWS cluster: [ClientError('An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 4): We currently do not have sufficient im4gn.xlarge capacity in the Availability Zone you requested (us-east-1c). Our system will be working on provisioning additional capacity. You can currently get im4gn.xlarge capacity by not specifying an Availability Zone in your request or choosing us-east-1b, us-east-1d.'), ClientError('An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 4): We currently do not have sufficient im4gn.xlarge capacity in the Availability Zone you requested (us-east-1b). Our system will be working on provisioning additional capacity. You can currently get im4gn.xlarge capacity by not specifying an Availability Zone in your request or choosing us-east-1c, us-east-1d.'), ClientError('An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 4): We currently do not have sufficient im4gn.xlarge capacity in the Availability Zone you requested (us-east-1d). Our system will be working on provisioning additional capacity. You can currently get im4gn.xlarge capacity by not specifying an Availability Zone in your request or choosing us-east-1b, us-east-1c.')]
13:13:00  
13:13:00  ----------------------------------------------------------------------
13:13:00  Ran 1 test in 41.770s
13:13:00  
13:13:00 
 FAILED (errors=1)
```

**Comment by soyacz** [comment]
SCT already tries with different AZ's - seems AWS have problem with this instance.
We can wait and see if this is temporary AWS issue or implement `fallback_to_different_vm_size`

**Comment by fruch** [comment]
> SCT already tries with different AZ's - seems AWS have problem with this instance. We can wait and see if this is temporary AWS issue or implement `fallback_to_different_vm_size`

maybe switch to a different type and that's it.

and if that doesn't  help, different region (more complex, need the ami available in that region)

**Comment by fruch** [comment]
running with a bigger one works:
https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-ami-arm-test/190/console

lets start with picking one that is more available, before designing new features

**Comment by fruch** [comment]
8 last run on master are working o.k.

I'm closing this one for now.
