### ISSUE TITLE
[Artifacts] Debian10 offline installation fails on the `ca-certificates-java` package setup which is needed for the `openjdk-11-jre-headless:arm64`

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-cluster-tests#6763]
### Prerequisites

* [ ] Are you rebased to master ?
* [x] Is it reproducible ?
* [ ] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: branch-5.2
* **scylla**: 5.2

### Logs
* test_id: f31850f4-d57d-4c57-b361-4af9df6f648a
* job log: [Argus](https://argus.scylladb.com/test/0069365a-f260-48ad-b7f8-c819b8fc064d/runs?additionalRuns[]=f31850f4-d57d-4c57-b361-4af9df6f648a), [CI](https://jenkins.scylladb.com/job/scylla-5.2/job/artifacts-offline-install/job/artifacts-debian10-arm-test/34/consoleFull)

### Description

Running the `scylla-5.2/artifacts-offline-install/artifacts-debian10-arm-test` CI jobs we get following error:
```
< t:2023-11-06 13:11:39,870 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Setting up ca-certificates-java (20190405) ...
< t:2023-11-06 13:11:39,899 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > head: cannot open '/etc/ssl/certs/java/cacerts' for reading: No such file or directory
< t:2023-11-06 13:11:40,016 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Exception in thread "main" java.lang.InternalError: Error loading java.security file
< t:2023-11-06 13:11:40,016 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 	at java.base/java.security.Security.initialize(Security.java:94)
< t:2023-11-06 13:11:40,016 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 	at java.base/java.security.Security$1.run(Security.java:79)
< t:2023-11-06 13:11:40,016 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 	at java.base/java.security.Security$1.run(Security.java:77)
< t:2023-11-06 13:11:40,016 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 	at java.base/java.security.AccessController.doPrivileged(Native Method)
< t:2023-11-06 13:11:40,016 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 	at java.base/java.security.Security.<clinit>(Security.java:77)
< t:2023-11-06 13:11:40,016 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 	at java.base/sun.security.jca.ProviderList.<init>(ProviderList.java:176)
< t:2023-11-06 13:11:40,016 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 	at java.base/sun.security.jca.ProviderList$2.run(ProviderList.java:94)
< t:2023-11-06 13:11:40,016 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 	at java.base/sun.security.jca.ProviderList$2.run(ProviderList.java:92)
< t:2023-11-06 13:11:40,016 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 	at java.base/java.security.AccessController.doPrivileged(Native Method)
< t:2023-11-06 13:11:40,017 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 	at java.base/sun.security.jca.ProviderList.fromSecurityProperties(ProviderList.java:91)
< t:2023-11-06 13:11:40,017 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 	at java.base/sun.security.jca.Providers.<clinit>(Providers.java:54)
< t:2023-11-06 13:11:40,017 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 	at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:156)
< t:2023-11-06 13:11:40,017 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 	at java.base/java.security.cert.CertificateFactory.getInstance(CertificateFactory.java:193)
< t:2023-11-06 13:11:40,017 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 	at org.debian.security.KeyStoreHandler.<init>(KeyStoreHandler.java:50)
< t:2023-11-06 13:11:40,017 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 	at org.debian.security.UpdateCertificates.<init>(UpdateCertificates.java:65)
< t:2023-11-06 13:11:40,017 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 	at org.debian.security.UpdateCertificates.main(UpdateCertificates.java:51)
< t:2023-11-06 13:11:40,022 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > dpkg: error processing package ca-certificates-java (--configure):
< t:2023-11-06 13:11:40,022 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG >  installed ca-certificates-java package post-installation script subprocess returned error exit status 1
< t:2023-11-06 13:11:40,022 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > dpkg: dependency problems prevent configuration of openjdk-11-jre-headless:arm64:
< t:2023-11-06 13:11:40,022 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG >  openjdk-11-jre-headless:arm64 depends on ca-certificates-java (>= 20190405~); however:
< t:2023-11-06 13:11:40,022 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG >   Package ca-certificates-java is not configured yet.
< t:2023-11-06 13:11:40,022 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 
< t:2023-11-06 13:11:40,022 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > dpkg: error processing package openjdk-11-jre-headless:arm64 (--configure):
< t:2023-11-06 13:11:40,022 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG >  dependency problems - leaving unconfigured
< t:2023-11-06 13:11:40,023 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Processing triggers for systemd (241-7~deb10u8) ...
< t:2023-11-06 13:11:40,125 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Processing triggers for man-db (2.8.5-2) ...
< t:2023-11-06 13:11:40,663 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Processing triggers for ca-certificates (20200601~deb10u2) ...
< t:2023-11-06 13:11:40,672 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Updating certificates in /etc/ssl/certs...
< t:2023-11-06 13:11:41,196 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 0 added, 0 removed; done.
< t:2023-11-06 13:11:41,197 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Running hooks in /etc/ca-certificates/update.d...
< t:2023-11-06 13:11:41,199 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 
< t:2023-11-06 13:11:41,329 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Exception in thread "main" java.lang.InternalError: Error loading java.security file
< t:2023-11-06 13:11:41,329 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 	at java.base/java.security.Security.initialize(Security.java:94)
< t:2023-11-06 13:11:41,329 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 	at java.base/java.security.Security$1.run(Security.java:79)
< t:2023-11-06 13:11:41,329 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 	at java.base/java.security.Security$1.run(Security.java:77)
< t:2023-11-06 13:11:41,329 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 	at java.base/java.security.AccessController.doPrivileged(Native Method)
< t:2023-11-06 13:11:41,330 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 	at java.base/java.security.Security.<clinit>(Security.java:77)
< t:2023-11-06 13:11:41,330 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 	at java.base/sun.security.jca.ProviderList.<init>(ProviderList.java:176)
< t:2023-11-06 13:11:41,330 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 	at java.base/sun.security.jca.ProviderList$2.run(ProviderList.java:94)
< t:2023-11-06 13:11:41,330 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 	at java.base/sun.security.jca.ProviderList$2.run(ProviderList.java:92)
< t:2023-11-06 13:11:41,330 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 	at java.base/java.security.AccessController.doPrivileged(Native Method)
< t:2023-11-06 13:11:41,330 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 	at java.base/sun.security.jca.ProviderList.fromSecurityProperties(ProviderList.java:91)
< t:2023-11-06 13:11:41,330 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 	at java.base/sun.security.jca.Providers.<clinit>(Providers.java:54)
< t:2023-11-06 13:11:41,330 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 	at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:156)
< t:2023-11-06 13:11:41,330 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 	at java.base/java.security.cert.CertificateFactory.getInstance(CertificateFactory.java:193)
< t:2023-11-06 13:11:41,330 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 	at org.debian.security.KeyStoreHandler.<init>(KeyStoreHandler.java:50)
< t:2023-11-06 13:11:41,330 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 	at org.debian.security.UpdateCertificates.<init>(UpdateCertificates.java:65)
< t:2023-11-06 13:11:41,330 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 	at org.debian.security.UpdateCertificates.main(UpdateCertificates.java:51)
< t:2023-11-06 13:11:41,335 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > E: /etc/ca-certificates/update.d/jks-keystore exited with code 1.
< t:2023-11-06 13:11:41,335 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > done.
< t:2023-11-06 13:11:41,343 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Processing triggers for sgml-base (1.29) ...
< t:2023-11-06 13:11:41,369 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Setting up libfontconfig1:arm64 (2.13.1-2) ...
< t:2023-11-06 13:11:41,382 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Processing triggers for mime-support (3.62) ...
< t:2023-11-06 13:11:41,553 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Processing triggers for libc-bin (2.28-10) ...
< t:2023-11-06 13:11:43,507 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Processing triggers for initramfs-tools (0.133+deb10u1) ...
< t:2023-11-06 13:11:43,537 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > update-initramfs: Generating /boot/initrd.img-4.19.0-18-arm64
< t:2023-11-06 13:12:10,705 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Errors were encountered while processing:
< t:2023-11-06 13:12:10,705 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG >  ca-certificates-java
< t:2023-11-06 13:12:10,705 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG >  openjdk-11-jre-headless:arm64
< t:2023-11-06 13:12:11,205 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > E: Sub-process /usr/bin/dpkg returned an error code (1)
< t:2023-11-06 13:12:11,206 f:base.py         l:146  c:RemoteLibSSH2CmdRunner p:ERROR > Error executing command: "sudo apt-get install -y openjdk-11-jre-headless xfsprogs mdadm python2"; Exit status: 100
< t:2023-11-06 13:12:11,206 f:base.py         l:148  c:RemoteLibSSH2CmdRunner p:DEBUG > STDOUT: in (2.28-10) ...
< t:2023-11-06 13:12:11,206 f:base.py         l:148  c:RemoteLibSSH2CmdRunner p:DEBUG > Processing triggers for initramfs-tools (0.133+deb10u1) ...
< t:2023-11-06 13:12:11,206 f:base.py         l:148  c:RemoteLibSSH2CmdRunner p:DEBUG > update-initramfs: Generating /boot/initrd.img-4.19.0-18-arm64
< t:2023-11-06 13:12:11,206 f:base.py         l:148  c:RemoteLibSSH2CmdRunner p:DEBUG > Errors were encountered while processing:
< t:2023-11-06 13:12:11,206 f:base.py         l:148  c:RemoteLibSSH2CmdRunner p:DEBUG >  ca-certificates-java
< t:2023-11-06 13:12:11,206 f:base.py         l:148  c:RemoteLibSSH2CmdRunner p:DEBUG >  openjdk-11-jre-headless:arm64
< t:2023-11-06 13:12:11,206 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG > STDERR: E: Sub-process /usr/bin/dpkg returned an error code (1)
```

### Steps to Reproduce

1. Run the `debian10` offline install artifacts CI job
2. See error

**Expected behavior:** The required packages must be installed successfully.

**Actual behavior:** The dependency packages fail to be installed.

**Comment by vponomaryov** [comment]
@fruch , @fgelcer , @aleksbykov  any idea about the root cause?

**Comment by vponomaryov** [comment]
If I create the not found directory before hand then the following failure happens:
```
< t:2023-11-06 17:23:45,781 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > cp: -r not specified; omitting directory '/etc/ssl/certs/java/cacerts'
< t:2023-11-06 17:23:45,783 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > dpkg: error processing package ca-certificates-java (--configure):
< t:2023-11-06 17:23:45,783 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG >  installed ca-certificates-java package post-installation script subprocess returned error exit status 1
< t:2023-11-06 17:23:45,783 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Processing triggers for libc-bin (2.28-10) ...
< t:2023-11-06 17:23:49,895 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Processing triggers for man-db (2.8.5-2) ...
< t:2023-11-06 17:23:50,012 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Processing triggers for ca-certificates (20200601~deb10u2) ...
< t:2023-11-06 17:23:50,032 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Updating certificates in /etc/ssl/certs...
< t:2023-11-06 17:23:50,777 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 0 added, 0 removed; done.
< t:2023-11-06 17:23:50,777 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Running hooks in /etc/ca-certificates/update.d...
< t:2023-11-06 17:23:50,779 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 
< t:2023-11-06 17:23:51,035 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Exception in thread "main" java.lang.InternalError: Error loading java.security file
< t:2023-11-06 17:23:51,035 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 	at java.base/java.security.Security.initialize(Security.java:94)
< t:2023-11-06 17:23:51,035 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 	at java.base/java.security.Security$1.run(Security.java:79)
< t:2023-11-06 17:23:51,036 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 	at java.base/java.security.Security$1.run(Security.java:77)
< t:2023-11-06 17:23:51,036 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 	at java.base/java.security.AccessController.doPrivileged(Native Method)
< t:2023-11-06 17:23:51,036 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 	at java.base/java.security.Security.<clinit>(Security.java:77)
< t:2023-11-06 17:23:51,036 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 	at java.base/sun.security.jca.ProviderList.<init>(ProviderList.java:176)
< t:2023-11-06 17:23:51,036 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 	at java.base/sun.security.jca.ProviderList$2.run(ProviderList.java:94)
< t:2023-11-06 17:23:51,036 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 	at java.base/sun.security.jca.ProviderList$2.run(ProviderList.java:92)
< t:2023-11-06 17:23:51,036 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 	at java.base/java.security.AccessController.doPrivileged(Native Method)
< t:2023-11-06 17:23:51,036 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 	at java.base/sun.security.jca.ProviderList.fromSecurityProperties(ProviderList.java:91)
< t:2023-11-06 17:23:51,036 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 	at java.base/sun.security.jca.Providers.<clinit>(Providers.java:54)
< t:2023-11-06 17:23:51,036 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 	at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:156)
< t:2023-11-06 17:23:51,036 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 	at java.base/java.security.cert.CertificateFactory.getInstance(CertificateFactory.java:193)
< t:2023-11-06 17:23:51,036 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 	at org.debian.security.KeyStoreHandler.<init>(KeyStoreHandler.java:50)
< t:2023-11-06 17:23:51,036 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 	at org.debian.security.UpdateCertificates.<init>(UpdateCertificates.java:65)
< t:2023-11-06 17:23:51,036 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 	at org.debian.security.UpdateCertificates.main(UpdateCertificates.java:51)
< t:2023-11-06 17:23:51,100 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > E: /etc/ca-certificates/update.d/jks-keystore exited with code 1.
< t:2023-11-06 17:23:51,100 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > done.
```

**Comment by fruch** [comment]
I've backported the fixes today, try running it again.

**Comment by vponomaryov** [comment]
> I've backported the fixes today, try running it again.

It is different kind of failure which is taken using the latest `branch-5.2` state.

**Comment by vponomaryov** [comment]
@fruch need to backport this fix: https://github.com/scylladb/scylla-cluster-tests/pull/6740 and that comment for it: https://github.com/scylladb/scylla-cluster-tests/pull/6748

**Comment by vponomaryov** [comment]
Backported above PRs and the problem has gone: https://jenkins.scylladb.com/job/scylla-5.2/job/artifacts-offline-install/job/artifacts-debian10-arm-test/36/consoleFull
