### ISSUE TITLE
SCT runner cleanup - should be according to backend (eliminate irrelevant errors in the end of Jenkins jobs)

### ISSUE THREAD

**Issue by benipeled** [scylladb/scylla-cluster-tests#6837]
Seen on https://jenkins.scylladb.com/view/scylla-manager/job/manager-3.2/job/ubuntu20-upgrade-test/7/consoleFull
AFAIK it's the first time we facing this issue

```
02:02:51  Test runner ip in update_sct_runner_tags: None; test_id: 79d9bf9d-c249-468c-93d2-c6e9e2b13a03
02:02:58  Traceback (most recent call last):
02:02:58    File "/home/ubuntu/scylla-cluster-tests/./sct.py", line 1742, in <module>
02:02:58      cli.main(prog_name="hydra")
02:02:58    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
02:02:58      rv = self.invoke(ctx)
02:02:58    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
02:02:58      return _process_result(sub_ctx.command.invoke(sub_ctx))
02:02:58    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
02:02:58      return ctx.invoke(self.callback, **ctx.params)
02:02:58    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
02:02:58      return __callback(*args, **kwargs)
02:02:58    File "/home/ubuntu/scylla-cluster-tests/./sct.py", line 1193, in collect_logs
02:02:58      update_sct_runner_tags(test_id=collector.test_id, tags={"logs_collected": True})
02:02:58    File "/home/ubuntu/scylla-cluster-tests/sdcm/sct_runner.py", line 1134, in update_sct_runner_tags
02:02:58      listed_runners = list_sct_runners(verbose=False)
02:02:58    File "/home/ubuntu/scylla-cluster-tests/sdcm/sct_runner.py", line 1116, in list_sct_runners
02:02:58      sct_runners = list(sct_runners)
02:02:58    File "/home/ubuntu/scylla-cluster-tests/sdcm/sct_runner.py", line 1107, in <genexpr>
02:02:58      sct_runners = chain.from_iterable(cls.list_sct_runners(verbose=False) for cls in sct_runner_classes)
02:02:58    File "/home/ubuntu/scylla-cluster-tests/sdcm/sct_runner.py", line 1045, in list_sct_runners
02:02:58      for instance in list_instances_azure(tags_dict={"NodeType": cls.NODE_TYPE}, verbose=verbose):
02:02:58    File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/azure_utils.py", line 230, in list_instances_azure
02:02:58      instances = [get_virtual_machine(resource_group_name=vm["resourceGroup"], vm_name=vm["name"]) for vm in res]
02:02:58    File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/azure_utils.py", line 230, in <listcomp>
02:02:58      instances = [get_virtual_machine(resource_group_name=vm["resourceGroup"], vm_name=vm["name"]) for vm in res]
02:02:58    File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/azure_utils.py", line 198, in paged_query
02:02:58      response = self.resource_graph.resources(request)
02:02:58    File "/usr/local/lib/python3.10/site-packages/azure/mgmt/resourcegraph/operations/_resource_graph_client_operations.py", line 73, in resources
02:02:58      raise HttpResponseError(response=response, model=error, error_format=ARMErrorFormat)
02:02:58  azure.core.exceptions.HttpResponseError: (RateLimiting) Please provide below info when asking for support: timestamp = 2023-11-19T00:02:57.5021878Z, correlationId = 9637e0cd-602b-4bfd-b12b-c25cf2d1a40c.
02:02:58  Code: RateLimiting
02:02:58  Message: Please provide below info when asking for support: timestamp = 2023-11-19T00:02:57.5021878Z, correlationId = 9637e0cd-602b-4bfd-b12b-c25cf2d1a40c.
02:02:58  Exception Details:	(RateLimiting) Client application has been throttled and should not attempt to repeat the request until an amount of time has elapsed. Please see https://aka.ms/resourcegraph-throttling for help.
02:02:58  	Code: RateLimiting
02:02:58  	Message: Client application has been throttled and should not attempt to repeat the request until an amount of time has elapsed. Please see https://aka.ms/resourcegraph-throttling for help.
02:03:19  Cleaning SSH agent
02:03:19  Agent pid 6086 killed
```

**Comment by fruch** [comment]
Two options to handle it

Ask for a higher limit (like we do on other clouds)

Check if the azure client can automatically retry, like boto3 can.

**Comment by fruch** [comment]
we can use RetryPolicy if needed as in:

https://github.com/Azure/azure-sdk-for-python/blob/7c336ab74767cbb61089cc55f233ecb145006684/sdk/core/azure-core/samples/test_example_sync.py#L129

lets track it some more to see if happens more, could be an azure issue

**Comment by roydahan** [comment]
In any case, I don't think this failed the test and it's just a background noise in the job.
Why does SCT list azure instances during a test in AWS is the more concerning part here...

**Comment by fruch** [comment]
> In any case, I don't think this failed the test and it's just a background noise in the job.
> Why does SCT list azure instances during a test in AWS is the more concerning part here...

We aligned the clean resources to work per backend

But the clear sct-runnner stage still scans all backends

**Comment by vponomaryov** [comment]
The error in the bug report happened during the `collect logs` stage, not `cleanup`.
The `cleanup` passed just fine because it was done exactly `per-backend`.

So, I assume this task is still valid even if it is about `collect logs` stage.

**Comment by fruch** [comment]
> The error in the bug report happened during the `collect logs` stage, not `cleanup`.
> The `cleanup` passed just fine because it was done exactly `per-backend`.
> 
> So, I assume this task is still valid even if it is about `collect logs` stage.

It's the list_sct_runners that breaks here, and yes it can be called from multiple places (from log collection, and from sct runner cleanup stage as well)

So we need to make sure all phases are per backend, to minimize those types of errors shown above
