### ISSUE TITLE
Call of `disable_daily_triggered_services` on Azure loaders breaks it using the `5.2` branch

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-cluster-tests#6859]
### Prerequisites

* [ ] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: `branch-5.2`
* **scylla**: `5.2.11-0.20231126.a65838ee9c09 with build-id 19149958503a961b9fc3b558e9e6cc22d3994169`

### Logs
* test_id: 236aa67f-fc4b-4135-a19e-4faa3d88f5d5
* job log: [Argus](https://argus.scylladb.com/test/8c977b7f-0cad-49ba-a41d-604ac9130d59/runs?additionalRuns[]=236aa67f-fc4b-4135-a19e-4faa3d88f5d5), [CI](https://jenkins.scylladb.com/job/scylla-5.2/job/longevity/job/longevity-10gb-3h-azure-test/33/)

### Description

After backport of the https://github.com/scylladb/scylla-cluster-tests/pull/6759/files to the `branch-5.2` SCT branch we get following error trying to pull docker image on loader nodes:
```
2023-11-27 09:50:30,869 f:base.py         l:146  c:RemoteLibSSH2CmdRunner p:ERROR > Error executing command: "sudo docker pull scylladb/scylla:latest"; Exit status: 1
2023-11-27 09:50:36,379 f:base.py         l:146  c:RemoteLibSSH2CmdRunner p:ERROR > Error executing command: "sudo docker pull scylladb/scylla:latest"; Exit status: 1
2023-11-27 09:50:41,888 f:base.py         l:146  c:RemoteLibSSH2CmdRunner p:ERROR > Error executing command: "sudo docker pull scylladb/scylla:latest"; Exit status: 1
2023-11-27 09:50:46,894 f:decorators.py   l:72   c:sdcm.utils.decorators p:ERROR > '_run': Number of retries exceeded!
...
2023-11-27 09:51:10,451 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 2023-11-27 09:51:10.449: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=61903151-f406-43f0-b799-bf3bba3f8f22, source=LongevityTest.test_custom_time (longevity_test.LongevityTest)() message=Traceback (most recent call last):
2023-11-27 09:51:10,451 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/longevity_test.py", line 120, in test_custom_time
2023-11-27 09:51:10,451 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     self.assemble_and_run_all_stress_cmd(stress_queue, stress_cmd, keyspace_num)
2023-11-27 09:51:10,451 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/loader_utils.py", line 82, in assemble_and_run_all_stress_cmd
2023-11-27 09:51:10,451 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     self._run_all_stress_cmds(stress_queue, params)
2023-11-27 09:51:10,451 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/loader_utils.py", line 114, in _run_all_stress_cmds
2023-11-27 09:51:10,451 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     stress_queue.append(self.run_stress_thread(**stress_params))
2023-11-27 09:51:10,451 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 1811, in run_stress_thread
2023-11-27 09:51:10,451 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     return self.run_stress_cassandra_thread(**params)
2023-11-27 09:51:10,451 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 1847, in run_stress_cassandra_thread
2023-11-27 09:51:10,451 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     cs_thread = CassandraStressThread(loader_set=self.loaders,
2023-11-27 09:51:10,451 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/stress_thread.py", line 93, in __init__
2023-11-27 09:51:10,451 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     super().__init__(loader_set=loader_set, stress_cmd=stress_cmd, timeout=timeout,
2023-11-27 09:51:10,451 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/stress/base.py", line 50, in __init__
2023-11-27 09:51:10,451 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     RemoteDocker.pull_image(loader, self.docker_image_name)
2023-11-27 09:51:10,451 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/docker_remote.py", line 115, in pull_image
2023-11-27 09:51:10,451 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     node.remoter.run(
2023-11-27 09:51:10,451 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run
2023-11-27 09:51:10,451 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     result = _run()
2023-11-27 09:51:10,451 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 67, in inner
2023-11-27 09:51:10,451 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     return func(*args, **kwargs)
2023-11-27 09:51:10,451 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run
2023-11-27 09:51:10,451 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
2023-11-27 09:51:10,451 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
2023-11-27 09:51:10,451 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     result = connection.run(**command_kwargs)
2023-11-27 09:51:10,451 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
2023-11-27 09:51:10,451 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
2023-11-27 09:51:10,451 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 654, in _complete_run
2023-11-27 09:51:10,451 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     raise UnexpectedExit(result)
2023-11-27 09:51:10,451 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!
2023-11-27 09:51:10,451 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 
2023-11-27 09:51:10,451 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > Command: 'sudo docker pull scylladb/scylla:latest'
2023-11-27 09:51:10,451 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 
2023-11-27 09:51:10,451 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > Exit code: 1
2023-11-27 09:51:10,451 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 
2023-11-27 09:51:10,451 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > Stdout:
2023-11-27 09:51:10,451 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 
2023-11-27 09:51:10,451 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 
2023-11-27 09:51:10,451 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 
2023-11-27 09:51:10,451 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > Stderr:
2023-11-27 09:51:10,451 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 
2023-11-27 09:51:10,451 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > sudo: docker: command not found
```

Revert of the changes made in the https://github.com/scylladb/scylla-cluster-tests/pull/6759 solve the problem.

### Steps to Reproduce

1. Run azure CI job using the `branch-5.2` SCT branch.
2. See above described error.

**Expected behavior:** docker must work on loader nodes

**Actual behavior:** docker fails on the loader nodes

**Comment by fruch** [comment]
> Test run with the fix successfully passed the failure step here: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/valerii/job/vp-longevity-10gb-3h-azure-test/8/consoleFull

Which of the command there breaks docker ?

I.e. we need a fix for that, reverting meaning we might fail during setup of loader or monitor.

**Comment by vponomaryov** [comment]
> > Test run with the fix successfully passed the failure step here: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/valerii/job/vp-longevity-10gb-3h-azure-test/8/consoleFull
> 
> Which of the command there breaks docker ?

Logs don't have explicit evidence, but I would say that not some command breaks loaders but absence of command(s)
which run when background stuff are not disabled.

> I.e. we need a fix for that, reverting meaning we might fail during setup of loader or monitor.

Azure CI job never failed with the bug that was fixed the https://github.com/scylladb/scylla-cluster-tests/pull/6759 PR
With that PR the Azure is broken in 100% cases.
