### ISSUE TITLE
Start of node exporter (via docker run) fails

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylla-cluster-tests#6861]
```
docker: Error response from daemon: Get "https://quay.io/v2/": context deadline exceeded (Client.Timeout exceeded while awaiting headers).
See 'docker run --help'.
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3661, in node_setup
cl_inst.node_setup(_node, **setup_kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 5123, in node_setup
self.install_scylla_monitoring(node)
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 119, in inner
res = func(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 5466, in install_scylla_monitoring
self.start_node_exporter(node)
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 5254, in start_node_exporter
node.remoter.run("bash -ce '%s'" % start_node_exporter_script)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 614, in run
result = _run()
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 70, in inner
return func(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 605, in _run
return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 538, in _run_execute
result = connection.run(**command_kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 655, in _complete_run
raise UnexpectedExit(result)
sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!
Command: 'bash -ce \'\ndocker run --restart=always -d --net="host" --pid="host" -v "/:/host:ro,rslave" --cap-add=SYS_TIME             quay.io/prometheus/node-exporter --path.rootfs=/host\n\''
Exit code: 125
Stdout:
Stderr:
Unable to find image 'quay.io/prometheus/node-exporter:latest' locally
docker: Error response from daemon: Get "https://quay.io/v2/": context deadline exceeded (Client.Timeout exceeded while awaiting headers).
See 'docker run --help'.
```

Need to:
1. Add retries
2. Perhaps pull before run?
3. Use more than a single registry

**Comment by mykaul** [comment]
I do see that when using RemoteDocker class it is retried 3 times:
```
res = self.node.remoter.run(
            f'{self.sudo_needed} docker run {extra_docker_opts} -d {ports} {image_name} {command_line}',
            verbose=True, retry=3)
```

The code for node exporter doesn't use it.

**Comment by mykaul** [comment]
CC @fruch

**Comment by fruch** [comment]
we'll replace this part, and install the node_exporter directly on the monitor node.
once we'll move to using the official images of monitor, we'll ask for it to come pre-installed

**Comment by roydahan** [comment]
Long term, we should move to monitor images and have node_exporter installed as part of them (we have a task for it, need to check if it includes the node_exporter)

Short term, we can add a fallback to install node_exporter if we failed pulling the docker image.
