### ISSUE TITLE
[2022.2] offline-installer: artifacts-debian10-arm-test failed during package installation

### ISSUE THREAD

**Issue by yaronkaikov** [scylladb/scylla-cluster-tests#6877]
https://jenkins.scylladb.com/job/enterprise-2022.2/job/artifacts-offline-install/job/artifacts-debian10-arm-test/40/consoleFull

```
13:00:54  < t:2023-11-30 11:00:49,826 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 2023-11-30 11:00:49.818: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=ec2ee685-bb15-43e0-bbb4-3d99ab5294cc, source=ArtifactsTest.SetUp()
13:00:54  < t:2023-11-30 11:00:49,826 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > exception=[Node artifacts-debian10-jenkins-db-node-816d152b-1 [54.75.113.14 | 10.4.3.207] (seed: True)] NodeSetupFailed: Encountered a bad command exit code!
13:00:54  < t:2023-11-30 11:00:49,826 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 
13:00:54  < t:2023-11-30 11:00:49,826 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > Command: 'sudo apt-get install -y openjdk-11-jre-headless xfsprogs mdadm python2'
13:00:54  < t:2023-11-30 11:00:49,826 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 
13:00:54  < t:2023-11-30 11:00:49,826 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > Exit code: 100
13:00:54  < t:2023-11-30 11:00:49,826 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 
13:00:54  < t:2023-11-30 11:00:49,826 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > Stdout:
13:00:54  < t:2023-11-30 11:00:49,826 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 
13:00:54  < t:2023-11-30 11:00:49,826 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > done.
13:00:54  < t:2023-11-30 11:00:49,826 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > Processing triggers for sgml-base (1.29) ...
13:00:54  < t:2023-11-30 11:00:49,826 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > Setting up libfontconfig1:arm64 (2.13.1-2) ...
13:00:54  < t:2023-11-30 11:00:49,826 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > Processing triggers for mime-support (3.62) ...
13:00:54  < t:2023-11-30 11:00:49,826 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > Processing triggers for libc-bin (2.28-10) ...
13:00:54  < t:2023-11-30 11:00:49,826 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > Processing triggers for initramfs-tools (0.133+deb10u1) ...
13:00:54  < t:2023-11-30 11:00:49,826 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > update-initramfs: Generating /boot/initrd.img-4.19.0-18-arm64
13:00:54  < t:2023-11-30 11:00:49,826 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > Errors were encountered while processing:
13:00:54  < t:2023-11-30 11:00:49,826 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >  ca-certificates-java
13:00:54  < t:2023-11-30 11:00:49,826 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >  openjdk-11-jre-headless:arm64
13:00:54  < t:2023-11-30 11:00:49,826 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 
13:00:54  < t:2023-11-30 11:00:49,826 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > Stderr:
13:00:54  < t:2023-11-30 11:00:49,826 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 
13:00:54  < t:2023-11-30 11:00:49,826 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > E: Sub-process /usr/bin/dpkg returned an error code (1)
13:00:54  < t:2023-11-30 11:00:49,826 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 
13:00:54  < t:2023-11-30 11:00:49,826 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 
13:00:54  < t:2023-11-30 11:00:49,826 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > Traceback (most recent call last):
13:00:54  < t:2023-11-30 11:00:49,826 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/home/jenkins/slave/workspace/enterprise-2022.2/artifacts-offline-install/artifacts-debian10-arm-test/scylla-cluster-tests/sdcm/cluster.py", line 3505, in node_setup
13:00:54  < t:2023-11-30 11:00:49,826 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     cl_inst.node_setup(_node, **setup_kwargs)
13:00:54  < t:2023-11-30 11:00:49,826 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/home/jenkins/slave/workspace/enterprise-2022.2/artifacts-offline-install/artifacts-debian10-arm-test/scylla-cluster-tests/sdcm/cluster.py", line 4163, in node_setup
13:00:54  < t:2023-11-30 11:00:49,826 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     self._scylla_install(node)
13:00:54  < t:2023-11-30 11:00:49,826 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/home/jenkins/slave/workspace/enterprise-2022.2/artifacts-offline-install/artifacts-debian10-arm-test/scylla-cluster-tests/sdcm/cluster.py", line 4244, in _scylla_install
13:00:54  < t:2023-11-30 11:00:49,826 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     node.offline_install_scylla(unified_package=self.params.get('unified_package'),
13:00:54  < t:2023-11-30 11:00:49,826 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/home/jenkins/slave/workspace/enterprise-2022.2/artifacts-offline-install/artifacts-debian10-arm-test/scylla-cluster-tests/sdcm/cluster.py", line 1983, in offline_install_scylla
13:00:54  < t:2023-11-30 11:00:49,826 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     self.remoter.run(f'sudo apt-get install -y openjdk-11-jre-headless {additional_pkgs}')
13:00:54  < t:2023-11-30 11:00:49,826 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/home/jenkins/slave/workspace/enterprise-2022.2/artifacts-offline-install/artifacts-debian10-arm-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run
13:00:54  < t:2023-11-30 11:00:49,826 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     result = _run()
13:00:54  < t:2023-11-30 11:00:49,826 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/home/jenkins/slave/workspace/enterprise-2022.2/artifacts-offline-install/artifacts-debian10-arm-test/scylla-cluster-tests/sdcm/utils/decorators.py", line 67, in inner
13:00:54  < t:2023-11-30 11:00:49,826 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     return func(*args, **kwargs)
13:00:54  < t:2023-11-30 11:00:49,826 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/home/jenkins/slave/workspace/enterprise-2022.2/artifacts-offline-install/artifacts-debian10-arm-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run
13:00:54  < t:2023-11-30 11:00:49,826 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
13:00:54  < t:2023-11-30 11:00:49,826 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/home/jenkins/slave/workspace/enterprise-2022.2/artifacts-offline-install/artifacts-debian10-arm-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
13:00:54  < t:2023-11-30 11:00:49,826 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     result = connection.run(**command_kwargs)
13:00:54  < t:2023-11-30 11:00:49,826 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/home/jenkins/slave/workspace/enterprise-2022.2/artifacts-offline-install/artifacts-debian10-arm-test/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
13:00:54  < t:2023-11-30 11:00:49,826 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
13:00:54  < t:2023-11-30 11:00:49,826 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/home/jenkins/slave/workspace/enterprise-2022.2/artifacts-offline-install/artifacts-debian10-arm-test/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 654, in _complete_run
13:00:54  < t:2023-11-30 11:00:49,826 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     raise UnexpectedExit(result)
13:00:54  < t:2023-11-30 11:00:49,826 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!
13:00:54  < t:2023-11-30 11:00:49,826 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 
13:00:54  < t:2023-11-30 11:00:49,826 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > Command: 'sudo apt-get install -y openjdk-11-jre-headless xfsprogs mdadm python2'
```

**Comment by vponomaryov** [comment]
Need to backport the https://github.com/scylladb/scylla-cluster-tests/pull/6740 to the SCT `2022.2` branch.

**Comment by vponomaryov** [comment]
Next test run using the backported change passed: https://jenkins.scylladb.com/job/enterprise-2022.2/job/artifacts-offline-install/job/artifacts-debian10-arm-test/41/consoleFull
