### ISSUE TITLE
Improper describe command error during add_remove_dc nemesis

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla-cluster-tests#6878]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [x] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: MASTER
* **scylla**: 5.4.0~rc1-20231029.24efacf90d0b

### Logs
* test_id:  e9db935f-ffe4-459b-8569-1fb494924933
* job log: https://cloudius-jenkins-test.s3.amazonaws.com/e9db935f-ffe4-459b-8569-1fb494924933/20231109_051158/sct-e9db935f.log.tar.gz
* Argus: https://argus.scylladb.com/test/feba54c6-b2a9-4889-9991-6cc027f6fb9d/runs?additionalRuns[]=e9db935f-ffe4-459b-8569-1fb494924933

### Description

cqlsh command failed during getting description of keyspace:
```
Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 5074, in wrapper
    result = method(*args[1:], **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4390, in disrupt_add_remove_dc
    self._switch_to_network_replication_strategy(self.cluster.get_test_keyspaces() + system_keyspaces)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4369, in _switch_to_network_replication_strategy
    replication_strategy = ReplicationStrategy.get(node, keyspace)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/replication_strategy_utils.py", line 24, in get
    create_ks_statement = node.run_cqlsh(f"describe {keyspace}").stdout.splitlines()[1]
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2856, in run_cqlsh
    cqlsh_out = self.remoter.run(cmd, timeout=timeout + 120,  # we give 30 seconds to cqlsh timeout mechanism to work
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run
    result = _run()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 70, in inner
    return func(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run
    return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
    result = connection.run(**command_kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
    return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 655, in _complete_run
    raise UnexpectedExit(result)
sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!

Command: '/usr/bin/cqlsh --no-color -u cassandra -p \'cassandra\'  --request-timeout=120 --connect-timeout=60 --ssl -e "describe "10gb_sizetiered"" 10.4.3.137 9042'

Exit code: 2

Stdout:



Stderr:


Warning: Using a password on the command line interface can be insecure.
Recommendation: use the credentials file to securely provide the password.

<stdin>:1:Improper describe command.
```
### Steps to Reproduce

1. Need to fix cqlsh command 'describe keyspace <keyspace>'

**Expected behavior:** [What you expected to happen]
returned info about keyspace

**Actual behavior:** [What actually happened]
failed with wrong syntax

**Comment by bhalevy** [comment]
@aleksbykov despite the error message, I don't think it's wrong syntax, but rather it's what printed when the keyspace doesn't exist.

```
bhalevy@lt scylla-cqlsh$ ./bin/cqlsh -e "describe foo"

<stdin>:1:'foo' not found in keyspaces
```

**Comment by bhalevy** [comment]
Can this be related to https://github.com/scylladb/scylla-manager/issues/3525?

**Comment by bhalevy** [comment]
This is weird:

```
bhalevy@lt scylla-cqlsh$ ./bin/cqlsh -e "describe 10gb"
<stdin>:1:Improper describe command.
bhalevy@lt scylla-cqlsh$ ./bin/cqlsh -e "describe foo"

<stdin>:1:'foo' not found in keyspaces
```

Maybe cqlsh doens't like keyspaces starting with a digit character?

**Comment by bhalevy** [comment]
Apparently, the quotation marks are needed in this case:

```
cqlsh> CREATE KEYSPACE "10gb" WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};

Warnings :
SimpleStrategy replication class is not recommended, but was used for keyspace 10gb. You may suppress this warning by delisting SimpleStrategy from replication_strategy_warn_list configuration option, or make it into an error by listing this replication strategy on replication_strategy_fail_list.

Using Replication Factor replication_factor=1 lower than the minimum_replication_factor_warn_threshold=3 is not recommended.

cqlsh> DESCRIBE 10gb
Improper DESCRIBE command.
cqlsh> DESCRIBE "10gb"

CREATE KEYSPACE "10gb" WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;
```

so they need to be escaped on the command like that:
```
bhalevy@lt scylla-cqlsh$ ./bin/cqlsh -e "describe \"10gb\""

CREATE KEYSPACE "10gb" WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;
```

**Comment by vponomaryov** [comment]
See following existing PR:
- https://github.com/scylladb/scylla-cluster-tests/pull/6897

**Comment by fruch** [comment]
since it starts with number, and also if it's CamelCase, I think the quotes are needed

**Comment by fruch** [comment]
it's two part to its, the usage of cqlsh, and the fact we have leftovers from manager restore nemesis, that should leave behind  `10gb_sizetiered` keyspace when it's done.
