### ISSUE TITLE
Refresh nemesis - tar command fails

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla-cluster-tests#689]
```
2018-11-10 01:53:31,382 remote           L0895 DEBUG| Remote [centos@172.30.0.86]: Running 'sudo tar xvfz /tmp/keyspace1.standard1.tar.gz -C /var/lib/scylla/data/keyspace1/counter1-34338dd0e48411e88b85000000000004/upload/'
2018-11-10 01:53:31,383 remote           L0094 INFO | [172.30.0.86] Running '/bin/ssh  -a -x   -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpfmKrq0 -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l centos -p 22 -i /root/.ssh/scylla-qa-
ec2 172.30.0.86 "sudo tar xvfz /tmp/keyspace1.standard1.tar.gz -C /var/lib/scylla/data/keyspace1/counter1-34338dd0e48411e88b85000000000004/upload/"'
2018-11-10 01:53:31,466 remote           L0194 DEBUG| [172.30.0.223] [stdout] Nov 10 01:53:31 info   |  [shard 0] rpc - client 172.30.0.185: fail to connect: Connection refused
2018-11-10 01:53:31,497 remote           L0194 DEBUG| [172.30.0.86] [stderr]
2018-11-10 01:53:31,497 remote           L0194 DEBUG| [172.30.0.86] [stderr] gzip: stdin: not in gzip format
2018-11-10 01:53:31,497 remote           L0194 DEBUG| [172.30.0.86] [stderr] tar: Child returned status 1
2018-11-10 01:53:31,498 remote           L0194 DEBUG| [172.30.0.86] [stderr] tar: Error is not recoverable: exiting now
2018-11-10 01:53:31,499 nemesis          L0444 ERROR| sdcm.nemesis.ChaosMonkey: Exception in random_disrupt_method nodetool_refresh: Command '/bin/ssh  -a -x   -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpfmKrq0 -o BatchMode=yes -o ConnectTimeout=300 -o
 ServerAliveInterval=300 -l centos -p 22 -i /root/.ssh/scylla-qa-ec2 172.30.0.86 "sudo tar xvfz /tmp/keyspace1.standard1.tar.gz -C /var/lib/scylla/data/keyspace1/counter1-34338dd0e48411e88b85000000000004/upload/"' failed (rc=2)
2018-11-10 01:53:31,499 nemesis          L0716 ERROR| sdcm.nemesis.ChaosMonkey: Unhandled exception in method <function disrupt at 0x7f513eab0848>
Traceback (most recent call last):
  File "/sct/sdcm/nemesis.py", line 712, in wrapper
    result = method(*args, **kwargs)
  File "/sct/sdcm/nemesis.py", line 866, in disrupt
    self.call_random_disrupt_method()
  File "/sct/sdcm/nemesis.py", line 442, in call_random_disrupt_method
    disrupt_method()
  File "/sct/sdcm/nemesis.py", line 337, in disrupt_nodetool_refresh
    node.remoter.run('sudo tar xvfz {} -C /var/lib/scylla/data/keyspace1/{}/upload/'.format(sstable_file, upload_dir))
  File "/sct/sdcm/remote.py", line 906, in run
    watch_stdout_pattern=watch_stdout_pattern)
  File "/sct/sdcm/remote.py", line 847, in _run
    watch_stdout_pattern=watch_stdout_pattern)
  File "/sct/sdcm/remote.py", line 805, in ssh_run
    raise process.CmdError(cmd, sp.result)
CmdError: Command '/bin/ssh  -a -x   -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpfmKrq0 -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l centos -p 22 -i /root/.ssh/scylla-qa-ec2 172.30.0.86 "sudo tar xvfz /tmp/keyspace1.standard1.ta
r.gz -C /var/lib/scylla/data/keyspace1/counter1-34338dd0e48411e88b85000000000004/upload/"' failed (rc=2)
2018-11-10 01:53:31,500 nemesis          L0727 DEBUG| sdcm.nemesis.ChaosMonkey: Refresh keyspace1.standard1 on longevity-36gb-in-memory-2018-1-6-db-node-e9c2ef7e-2 duration -> 2 s
```

**Comment by amoskong** [comment]
It's problem of S3 file permission.
```
$ curl https://s3.amazonaws.com/scylla-qa-team/keyspace1.standard1.100M.tar.gz
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>325EE014F5E6AE82</RequestId><HostId>t+YB7GeYCzPfAuBEeYySK+M0qaRjDJLmuARIl0lMwOXYG058QaY6JeoeC7bK0HE1C7g5aLUBNwE=</HostId></Error>
```

**Comment by amoskong** [comment]
The files are not allowed to be downloaded by Anonymous, they can be downloaded successfully after assigned a valid user-agent in curl cmdline.
