### ISSUE TITLE
`end_of_quota_nemesis` nemesis fails incorrectly parsing the `mount` command

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-cluster-tests#6936]
In the `longevity-mv-si-4days-test` CI job we use `instance_type_db: i4i.8xlarge` where RAID disks from several SSD get created.
And when the `end_of_quota_nemesis` nemesis gets run there we get following error:
```
2023-12-09 20:37:33,968 f:quota.py        l:34   c:sdcm.utils.quota     p:INFO  > Verifying quota is configured on the node longevity-mv-si-4d-master-db-node-1df78dff-6
2023-12-09 20:37:33,968 f:remote_base.py  l:521  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "mount | grep /var/lib/scylla | awk {'print $6'} | cut -d ',' -f 8"...
...
2023-12-09 20:37:34,056 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > sunit=2048  
2023-12-09 20:37:34,057 f:base.py         l:142  c:RemoteLibSSH2CmdRunner p:DEBUG > Command "mount | grep /var/lib/scylla | awk {'print $6'} | cut -d ',' -f 8" finished with status 0
2023-12-09 20:37:34,057 f:quota.py        l:38   c:sdcm.utils.quota     p:WARNING > User quota on user scylla at /var/lib/scylla is not enabled
2023-12-09 20:37:34,062 f:nemesis.py      l:5077 c:sdcm.nemesis         p:ERROR > sdcm.nemesis.SisyphusMonkey: Unhandled exception in method <bound method Nemesis.disrupt_end_of_quota_nemesis of <sdcm.nemesis.SisyphusMonkey         object at 0x7f668fdbe530>> < t:2023-12-09 20:37:34,062 f:nemesis.py      l:5077 c:sdcm.nemesis         p:ERROR > sdcm.nemesis.SisyphusMonkey: Unhandled exception in method <bound method Nemesis.disrupt_end_of_quota_nemesis of <sdcm.nemesis.SisyphusMonkey object at 0x7f668fdbe530>>
2023-12-09 20:37:34,062 f:nemesis.py      l:5077 c:sdcm.nemesis         p:ERROR > Traceback (most recent call last):
2023-12-09 20:37:34,062 f:nemesis.py      l:5077 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 5053, in wrapper
2023-12-09 20:37:34,062 f:nemesis.py      l:5077 c:sdcm.nemesis         p:ERROR >     result = method(*args[1:], **kwargs)
2023-12-09 20:37:34,062 f:nemesis.py      l:5077 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1719, in disrupt_end_of_quota_nemesis
2023-12-09 20:37:34,062 f:nemesis.py      l:5077 c:sdcm.nemesis         p:ERROR >     raise QuotaConfigurationFailure("Failed to configure quota on the cluster")
2023-12-09 20:37:34,062 f:nemesis.py      l:5077 c:sdcm.nemesis         p:ERROR > sdcm.exceptions.QuotaConfigurationFailure: Failed to configure quota on the cluster
```

The code that parses the `mount` command:
```
def is_quota_enabled_on_node(node):
    """ Verify usrquota is enabled on scylla user. """
    LOGGER.info("Verifying quota is configured on the node {}".format(node.name))
    verify_usrquot_in_mount_cmd = "mount | grep /var/lib/scylla | awk {'print $6'} | cut -d ',' -f 8"
    result = node.remoter.run(cmd=verify_usrquot_in_mount_cmd).stdout.rstrip().replace(")", "")
    if not result == "usrquota":
        LOGGER.warning("User quota on user scylla at /var/lib/scylla is not enabled")
        return False
    return True
```

The failure appears because `sunit=2048` string is not equal to the `usrquota`.
The `sunit` option of the `mount` is `Used to specify the stripe unit and width for a RAID device or a stripe volume.`
The `i4i.8xlarge` instance type has 2 SSDs and will result in creating the `RAID0` device.
The implementation in the https://github.com/scylladb/scylla-cluster-tests/pull/6616 was tested against the `i4i.large` instance type which has only one SSD disk not causing the `RAID0` creation.

So, need to update the mount checker the way that it
- doesn't depend on the specific option position
- prints out the mount command in logs for the debug purposes

## Installation details

Kernel Version: 5.15.0-1050-aws
Scylla version (or git commit hash): `5.5.0~dev-20231205.4505a86f46df` with build-id `2355da584169ed4dedccb225347f30c5896efe06`

Cluster size: 5 nodes (i4i.8xlarge)

Scylla Nodes used in this run:
- longevity-mv-si-4d-master-db-node-1df78dff-9 (54.74.47.254 | 10.4.8.78) (shards: 30)
- longevity-mv-si-4d-master-db-node-1df78dff-8 (3.254.137.194 | 10.4.9.43) (shards: 30)
- longevity-mv-si-4d-master-db-node-1df78dff-7 (63.33.57.138 | 10.4.8.203) (shards: -1)
- longevity-mv-si-4d-master-db-node-1df78dff-6 (3.253.0.244 | 10.4.10.248) (shards: 30)
- longevity-mv-si-4d-master-db-node-1df78dff-5 (3.252.95.28 | 10.4.9.169) (shards: 30)
- longevity-mv-si-4d-master-db-node-1df78dff-4 (34.242.142.136 | 10.4.10.96) (shards: 30)
- longevity-mv-si-4d-master-db-node-1df78dff-3 (3.249.49.235 | 10.4.8.129) (shards: 30)
- longevity-mv-si-4d-master-db-node-1df78dff-2 (54.74.243.128 | 10.4.11.241) (shards: 30)
- longevity-mv-si-4d-master-db-node-1df78dff-1 (34.252.198.50 | 10.4.11.222) (shards: 30)

OS / Image: `ami-0934195d8e2431362` (aws: undefined_region)

Test: `longevity-mv-si-4days-test`
Test id: `1df78dff-873f-44a8-90f8-816c6301740f`
Test name: `scylla-master/longevity/longevity-mv-si-4days-test`
Test config file(s):

- [longevity-mv-si-4days.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/3d32370733caa48cfe5af0014e1a1b1bb3a48a37/test-cases/longevity/longevity-mv-si-4days.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 1df78dff-873f-44a8-90f8-816c6301740f`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=1df78dff-873f-44a8-90f8-816c6301740f)
- Show all stored logs command: `$ hydra investigate show-logs 1df78dff-873f-44a8-90f8-816c6301740f`

## Logs:
- **db-cluster-1df78dff.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/1df78dff-873f-44a8-90f8-816c6301740f/20231210_070419/db-cluster-1df78dff.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/1df78dff-873f-44a8-90f8-816c6301740f/20231210_070419/db-cluster-1df78dff.tar.gz)
- **sct-runner-events-1df78dff.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/1df78dff-873f-44a8-90f8-816c6301740f/20231210_070419/sct-runner-events-1df78dff.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/1df78dff-873f-44a8-90f8-816c6301740f/20231210_070419/sct-runner-events-1df78dff.tar.gz)
- **sct-1df78dff.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/1df78dff-873f-44a8-90f8-816c6301740f/20231210_070419/sct-1df78dff.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/1df78dff-873f-44a8-90f8-816c6301740f/20231210_070419/sct-1df78dff.log.tar.gz)
- **loader-set-1df78dff.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/1df78dff-873f-44a8-90f8-816c6301740f/20231210_070419/loader-set-1df78dff.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/1df78dff-873f-44a8-90f8-816c6301740f/20231210_070419/loader-set-1df78dff.tar.gz)
- **monitor-set-1df78dff.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/1df78dff-873f-44a8-90f8-816c6301740f/20231210_070419/monitor-set-1df78dff.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/1df78dff-873f-44a8-90f8-816c6301740f/20231210_070419/monitor-set-1df78dff.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-mv-si-4days-test/26/)
[Argus](https://argus.scylladb.com/test/b49dc529-c8e7-4117-a01d-2c6669c4dc05/runs?additionalRuns[]=1df78dff-873f-44a8-90f8-816c6301740f)
</details>

**Comment by fruch** [comment]
@bhalevy @Mark-Gurevich, seem like more fallout from `disrupt_end_of_quota_nemesis` that need to be addressed
