### ISSUE TITLE
LoadAndStream nemesis is failing on 

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#6962]
Docker backend seems to be failing during `LoadAndStream`
```
[2023-12-18T11:51:21.169Z] 2023-12-18 11:50:25.356: (DisruptionEvent Severity.ERROR) period_type=end event_id=07e47fd1-e0d8-4d33-89c9-de128ea1d209 duration=25s: nemesis_name=LoadAndStream target_node=Node PR-provision-docker-PR-6955-db-node-99722d4e-0 [172.17.0.2 | 172.17.0.2] (seed: True) errors=Encountered a bad command exit code!
[2023-12-18T11:51:21.169Z] Command: 'tar xvfz /tmp/node1.keyspace1.standard1.tar.gz -C /var/lib/scylla/data/keyspace1/standard1-74d657c09d9b11eebf62d9c8530cc4a5/upload/'
[2023-12-18T11:51:21.169Z] Exit code: 2
[2023-12-18T11:51:21.170Z] Stdout:
[2023-12-18T11:51:21.170Z] md-8-big-TOC.txt
[2023-12-18T11:51:21.170Z] md-9-big-CRC.db
[2023-12-18T11:51:21.170Z] md-9-big-Data.db
[2023-12-18T11:51:21.170Z] md-9-big-Digest.crc32
[2023-12-18T11:51:21.170Z] md-9-big-Filter.db
[2023-12-18T11:51:21.170Z] md-9-big-Index.db
[2023-12-18T11:51:21.170Z] md-9-big-Scylla.db
[2023-12-18T11:51:21.170Z] md-9-big-Statistics.db
[2023-12-18T11:51:21.170Z] md-9-big-Summary.db
[2023-12-18T11:51:21.170Z] md-9-big-TOC.txt
[2023-12-18T11:51:21.170Z] Stderr:
[2023-12-18T11:51:21.170Z] tar: md-9-big-CRC.db: Cannot open: Permission denied
[2023-12-18T11:51:21.170Z] tar: md-9-big-Data.db: Cannot open: Permission denied
[2023-12-18T11:51:21.170Z] tar: md-9-big-Digest.crc32: Cannot open: Permission denied
[2023-12-18T11:51:21.170Z] tar: md-9-big-Filter.db: Cannot open: Permission denied
[2023-12-18T11:51:21.170Z] tar: md-9-big-Index.db: Cannot open: Permission denied
[2023-12-18T11:51:21.170Z] tar: md-9-big-Scylla.db: Cannot open: Permission denied
[2023-12-18T11:51:21.170Z] tar: md-9-big-Statistics.db: Cannot open: Permission denied
[2023-12-18T11:51:21.170Z] tar: md-9-big-Summary.db: Cannot open: Permission denied
[2023-12-18T11:51:21.170Z] tar: md-9-big-TOC.txt: Cannot open: Permission denied
[2023-12-18T11:51:21.170Z] tar: Exiting with failure status due to previous errors
[2023-12-18T11:51:21.170Z] Traceback (most recent call last):
[2023-12-18T11:51:21.170Z] File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 5055, in wrapper
[2023-12-18T11:51:21.170Z] result = method(*args[1:], **kwargs)
[2023-12-18T11:51:21.170Z] File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1594, in disrupt_load_and_stream
[2023-12-18T11:51:21.170Z] SstableLoadUtils.upload_sstables(load_on_node, test_data=sstables_info, table_name="standard1")
[2023-12-18T11:51:21.170Z] File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/sstable/load_utils.py", line 104, in upload_sstables
[2023-12-18T11:51:21.170Z] node.remoter.run(f'tar xvfz {test_data.sstable_file} -C {table_folder}/upload/')
[2023-12-18T11:51:21.170Z] File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 614, in run
[2023-12-18T11:51:21.170Z] result = _run()
[2023-12-18T11:51:21.170Z] File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 70, in inner
[2023-12-18T11:51:21.170Z] return func(*args, **kwargs)
[2023-12-18T11:51:21.170Z] File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 605, in _run
[2023-12-18T11:51:21.170Z] return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
[2023-12-18T11:51:21.170Z] File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 538, in _run_execute
[2023-12-18T11:51:21.170Z] result = connection.run(**command_kwargs)
[2023-12-18T11:51:21.170Z] File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
[2023-12-18T11:51:21.170Z] return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
[2023-12-18T11:51:21.171Z] File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 655, in _complete_run
[2023-12-18T11:51:21.171Z] raise UnexpectedExit(result)
[2023-12-18T11:51:21.171Z] sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!
[2023-12-18T11:51:21.171Z] Command: 'tar xvfz /tmp/node1.keyspace1.standard1.tar.gz -C /var/lib/scylla/data/keyspace1/standard1-74d657c09d9b11eebf62d9c8530cc4a5/upload/'
[2023-12-18T11:51:21.171Z] Exit code: 2
[2023-12-18T11:51:21.171Z] Stdout:
[2023-12-18T11:51:21.171Z] md-8-big-TOC.txt
[2023-12-18T11:51:21.171Z] md-9-big-CRC.db
[2023-12-18T11:51:21.171Z] md-9-big-Data.db
[2023-12-18T11:51:21.171Z] md-9-big-Digest.crc32
[2023-12-18T11:51:21.171Z] md-9-big-Filter.db
[2023-12-18T11:51:21.171Z] md-9-big-Index.db
[2023-12-18T11:51:21.171Z] md-9-big-Scylla.db
[2023-12-18T11:51:21.171Z] md-9-big-Statistics.db
[2023-12-18T11:51:21.171Z] md-9-big-Summary.db
[2023-12-18T11:51:21.171Z] md-9-big-TOC.txt
[2023-12-18T11:51:21.171Z] Stderr:
[2023-12-18T11:51:21.171Z] tar: md-9-big-CRC.db: Cannot open: Permission denied
[2023-12-18T11:51:21.171Z] tar: md-9-big-Data.db: Cannot open: Permission denied
[2023-12-18T11:51:21.171Z] tar: md-9-big-Digest.crc32: Cannot open: Permission denied
[2023-12-18T11:51:21.171Z] tar: md-9-big-Filter.db: Cannot open: Permission denied
[2023-12-18T11:51:21.171Z] tar: md-9-big-Index.db: Cannot open: Permission denied
[2023-12-18T11:51:21.171Z] tar: md-9-big-Scylla.db: Cannot open: Permission denied
[2023-12-18T11:51:21.171Z] tar: md-9-big-Statistics.db: Cannot open: Permission denied
[2023-12-18T11:51:21.171Z] tar: md-9-big-Summary.db: Cannot open: Permission denied
[2023-12-18T11:51:21.171Z] tar: md-9-big-TOC.txt: Cannot open: Permission denied
[2023-12-18T11:51:21.171Z] tar: Exiting with failure status due to previous errors
```

https://jenkins.scylladb.com/job/sct-github-PRs-scan/job/scylla-cluster-tests/job/PR-6955/7/pipeline-console/?start-byte=27523&selected-node=239

**Comment by dimakr** [comment]
The same error is also observed for the following nemesis on docker backend:
- RefreshBigMonkey
- RefreshMonkey

**Comment by dimakr** [comment]
PR https://github.com/scylladb/scylla-cluster-tests/pull/7343 implements fix for the issue.
