### ISSUE TITLE
Rolling upgrade debian failure `apt cloud-sdk-buster InRelease'`

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-cluster-tests#6979]
Debian rolling upgrade tests from enterprise base version failed with:
```
2023-12-19 20:51:20.911: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=8c1ff00a-69c6-48df-97fb-e38ab6a52567, source=UpgradeTest.test_rolling_upgrade (upgrade_test.UpgradeTest)() message=Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/upgrade_test.py", line 667, in test_rolling_upgrade
self.upgrade_node(self.db_cluster.node_to_upgrade)
File "/home/ubuntu/scylla-cluster-tests/upgrade_test.py", line 60, in inner
func_result = func(self, *args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/sct_events/group_common_events.py", line 256, in inner_func
return func(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/upgrade_test.py", line 249, in upgrade_node
node.remoter.run('sudo apt-get update')
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run
result = _run()
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 67, in inner
return func(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run
return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
result = connection.run(**command_kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 654, in _complete_run
raise UnexpectedExit(result)
sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!
Command: 'sudo apt-get update'
Exit code: 100
Stdout:
Hit:1 https://packages.cloud.google.com/apt google-compute-engine-buster-stable InRelease
Hit:2 https://deb.debian.org/debian buster InRelease
Hit:3 https://deb.debian.org/debian-security buster/updates InRelease
Hit:4 https://deb.debian.org/debian buster-updates InRelease
Hit:5 https://deb.debian.org/debian buster-backports InRelease
Get:6 https://packages.cloud.google.com/apt cloud-sdk-buster InRelease [1740 B]
Hit:7 https://downloads.scylladb.com/unstable/scylla-enterprise/enterprise-2023.1/deb/unified/2023-12-19T14:26:23Z/scylladb-2023.1 stable InRelease
Reading package lists...
Stderr:
E: Repository 'https://packages.cloud.google.com/apt cloud-sdk-buster InRelease' changed its 'Origin' value from 'cloud-sdk-buster' to 'namespaces/google.com:cloudsdktool/repositories/cloud-sdk-buster'
E: Repository 'https://packages.cloud.google.com/apt cloud-sdk-buster InRelease' changed its 'Label' value from 'cloud-sdk-buster' to 'namespaces/google.com:cloudsdktool/repositories/cloud-sdk-buster'
```

But exactly same test and base version in [2022.2](https://argus.scylladb.com/test/364fa5aa-8118-4851-a312-f173c0f29213/runs?additionalRuns[]=70b9afed-e3c7-41d2-81ac-7024599c58af) passed.

Same failure in  [debian 11 test](https://argus.scylladb.com/test/bc409cd5-99ce-4d9c-8bfb-4a423bf617ef/runs?additionalRuns[]=718d557e-8066-4457-b9c6-5478ddb4f861)

## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

*Describe your issue in detail and steps it took to produce it.*

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Kernel Version: 4.19.0-25-cloud-amd64
Scylla version (or git commit hash): `2022.2.15-20231129.8e6c47831239` with build-id `180b8f5759079b8444b6bb2c225f8b7832015bec`
Target Scylla version (or git commit hash): `2023.1.3-20231219.b890271f125b` with build-id `26667e5fe9023e6f688ca3bab2ee5f910abfd2cb`

Cluster size: 4 nodes (n2-highmem-32)

Scylla Nodes used in this run:
- rolling-upgrade--debian-buster-db-node-d3beaec6-0-4 (35.231.47.226 | 10.142.0.206) (shards: 30)
- rolling-upgrade--debian-buster-db-node-d3beaec6-0-3 (34.148.85.248 | 10.142.0.200) (shards: 30)
- rolling-upgrade--debian-buster-db-node-d3beaec6-0-2 (35.196.29.57 | 10.142.0.194) (shards: 30)
- rolling-upgrade--debian-buster-db-node-d3beaec6-0-1 (34.73.254.111 | 10.142.15.243) (shards: 30)

OS / Image: `https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/family/debian-10` (gce: us-east1)

Test: `rolling-upgrade-debian10-test`
Test id: `d3beaec6-6539-403e-af30-9d70a907922c`
Test name: `enterprise-2023.1/rolling-upgrade/rolling-upgrade-debian10-test`
Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/d2d65636c2fe92a63456f7facbf159ff47aa225a/test-cases/upgrades/rolling-upgrade.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor d3beaec6-6539-403e-af30-9d70a907922c`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=d3beaec6-6539-403e-af30-9d70a907922c)
- Show all stored logs command: `$ hydra investigate show-logs d3beaec6-6539-403e-af30-9d70a907922c`

## Logs:
- **db-cluster-d3beaec6.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d3beaec6-6539-403e-af30-9d70a907922c/20231219_210551/db-cluster-d3beaec6.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d3beaec6-6539-403e-af30-9d70a907922c/20231219_210551/db-cluster-d3beaec6.tar.gz)
- **sct-runner-events-d3beaec6.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d3beaec6-6539-403e-af30-9d70a907922c/20231219_210551/sct-runner-events-d3beaec6.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d3beaec6-6539-403e-af30-9d70a907922c/20231219_210551/sct-runner-events-d3beaec6.tar.gz)
- **sct-d3beaec6.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d3beaec6-6539-403e-af30-9d70a907922c/20231219_210551/sct-d3beaec6.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d3beaec6-6539-403e-af30-9d70a907922c/20231219_210551/sct-d3beaec6.log.tar.gz)
- **monitor-set-d3beaec6.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d3beaec6-6539-403e-af30-9d70a907922c/20231219_210551/monitor-set-d3beaec6.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d3beaec6-6539-403e-af30-9d70a907922c/20231219_210551/monitor-set-d3beaec6.tar.gz)
- **loader-set-d3beaec6.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d3beaec6-6539-403e-af30-9d70a907922c/20231219_210551/loader-set-d3beaec6.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d3beaec6-6539-403e-af30-9d70a907922c/20231219_210551/loader-set-d3beaec6.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2023.1/job/rolling-upgrade/job/rolling-upgrade-debian10-test/21/)
[Argus](https://argus.scylladb.com/test/8ee0aa66-4834-4cab-bef1-26b20b221249/runs?additionalRuns[]=d3beaec6-6539-403e-af30-9d70a907922c)
</details>

**Comment by fruch** [comment]
so far look like it was a temporary issue, cause all re-run worked..

**Comment by fruch** [comment]
we didn't seen this issue since then, closing
