### ISSUE TITLE
`check_group0_tokenring_consistency` shouldn't be raising exception, just events

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#7049]
## Issue description

- [ ] This issue is a regression.
- [x] It is unknown if this issue is a regression.

if there a failure in `check_group0_tokenring_consistency`, it breaks down the whole nemesis thread with it:
```
2024-01-01 22:53:52.751: (ThreadFailedEvent Severity.ERROR) period_type=one-time event_id=1ee2a732-059d-4ef6-970a-e9f37c6ad378: message=Encountered a bad command exit code!
Command: '/usr/bin/nodetool  info '
Exit code: 1
Stdout:
Off Heap Memory (MB)   : 15215.77
Data Center            : UNKNOWN_DC
Rack                   : UNKNOWN_RACK
Exceptions             : 0
Key Cache              : entries 0, size 0 bytes, capacity 0 bytes, 0 hits, 0 requests, 0.000 recent hit rate, 0 save period in seconds
Row Cache              : entries 1521506, size 1.45 MiB, capacity 2.36 GiB, 154658078 hits, 155097219 requests, 0.997 recent hit rate, 0 save period in seconds
Counter Cache          : entries 0, size 0 bytes, capacity 0 bytes, 0 hits, 0 requests, 0.000 recent hit rate, 0 save period in seconds
Percent Repaired       : 0.0%
nodetool: Scylla API server HTTP GET to URL '/storage_service/tokens/null' failed: std::invalid_argument (null)
See 'nodetool help' or 'nodetool help <command>'.
Stderr:
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/sct_events/decorators.py", line 26, in wrapper
return func(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 396, in run
self.disrupt()
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 6225, in disrupt
self.call_next_nemesis()
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1891, in call_next_nemesis
self.execute_disrupt_method(disrupt_method=next(self.disruptions_cycle))
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1817, in execute_disrupt_method
disrupt_method()
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 5121, in wrapper
args[0].cluster.check_cluster_health()
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 4153, in check_cluster_health
node.check_node_health()
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2586, in check_node_health
event = next(events, None)
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/health_checker.py", line 275, in check_group0_tokenring_consistency
current_node.name, current_node.host_id)
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 393, in host_id
return self.parent_cluster.get_nodetool_info(self, publish_event=False).get('ID')
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 4135, in get_nodetool_info
res = node.run_nodetool('info', **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2525, in run_nodetool
self.remoter.run(cmd, timeout=timeout, ignore_status=ignore_status, verbose=verbose, retry=retry)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 614, in run
result = _run()
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 70, in inner
return func(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 605, in _run
return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 538, in _run_execute
result = connection.run(**command_kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 655, in _complete_run
raise UnexpectedExit(result)
sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!
Command: '/usr/bin/nodetool  info '
Exit code: 1
Stdout:
Off Heap Memory (MB)   : 15215.77
Data Center            : UNKNOWN_DC
Rack                   : UNKNOWN_RACK
Exceptions             : 0
Key Cache              : entries 0, size 0 bytes, capacity 0 bytes, 0 hits, 0 requests, 0.000 recent hit rate, 0 save period in seconds
Row Cache              : entries 1521506, size 1.45 MiB, capacity 2.36 GiB, 154658078 hits, 155097219 requests, 0.997 recent hit rate, 0 save period in seconds
Counter Cache          : entries 0, size 0 bytes, capacity 0 bytes, 0 hits, 0 requests, 0.000 recent hit rate, 0 save period in seconds
Percent Repaired       : 0.0%
nodetool: Scylla API server HTTP GET to URL '/storage_service/tokens/null' failed: std::invalid_argument (null)
See 'nodetool help' or 'nodetool help <command>'.
Stderr:
```
## Impact

one failure in this those check, and no more nemesis would run

## How frequently does it reproduce?

once it enough that we need to handle it

## Installation details

Kernel Version: 5.15.0-1051-aws
Scylla version (or git commit hash): `2024.1.0~rc3-20240101.29b16c9e1ed0` with build-id `f4edb0c76f35d065557787684ec836ac6ad625b5`

Cluster size: 6 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
- longevity-cdc-100gb-4h-2024-1-db-node-4dd90c7b-7 (3.82.218.123 | 10.12.7.145) (shards: -1)
- longevity-cdc-100gb-4h-2024-1-db-node-4dd90c7b-6 (3.94.119.176 | 10.12.11.208) (shards: 14)
- longevity-cdc-100gb-4h-2024-1-db-node-4dd90c7b-5 (54.226.68.246 | 10.12.9.93) (shards: 14)
- longevity-cdc-100gb-4h-2024-1-db-node-4dd90c7b-4 (54.172.255.81 | 10.12.5.88) (shards: 14)
- longevity-cdc-100gb-4h-2024-1-db-node-4dd90c7b-3 (3.85.239.7 | 10.12.4.82) (shards: 14)
- longevity-cdc-100gb-4h-2024-1-db-node-4dd90c7b-2 (44.200.246.240 | 10.12.2.215) (shards: 14)
- longevity-cdc-100gb-4h-2024-1-db-node-4dd90c7b-1 (44.212.11.90 | 10.12.0.115) (shards: 14)

OS / Image: `ami-08ea1540e932ad3f6` (aws: undefined_region)

Test: `longevity-cdc-100gb-4h-test`
Test id: `4dd90c7b-6de2-40da-81dc-1e2faaac480c`
Test name: `enterprise-2024.1/longevity/longevity-cdc-100gb-4h-test`
Test config file(s):

- [longevity-cdc-100gb-4h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/380c1b8984c71ac34e6fecce1cd5dd188d190a7e/test-cases/longevity/longevity-cdc-100gb-4h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 4dd90c7b-6de2-40da-81dc-1e2faaac480c`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=4dd90c7b-6de2-40da-81dc-1e2faaac480c)
- Show all stored logs command: `$ hydra investigate show-logs 4dd90c7b-6de2-40da-81dc-1e2faaac480c`

## Logs:
- **db-cluster-4dd90c7b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4dd90c7b-6de2-40da-81dc-1e2faaac480c/20240101_232839/db-cluster-4dd90c7b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4dd90c7b-6de2-40da-81dc-1e2faaac480c/20240101_232839/db-cluster-4dd90c7b.tar.gz)
- **sct-runner-events-4dd90c7b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4dd90c7b-6de2-40da-81dc-1e2faaac480c/20240101_232839/sct-runner-events-4dd90c7b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4dd90c7b-6de2-40da-81dc-1e2faaac480c/20240101_232839/sct-runner-events-4dd90c7b.tar.gz)
- **sct-4dd90c7b.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4dd90c7b-6de2-40da-81dc-1e2faaac480c/20240101_232839/sct-4dd90c7b.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4dd90c7b-6de2-40da-81dc-1e2faaac480c/20240101_232839/sct-4dd90c7b.log.tar.gz)
- **loader-set-4dd90c7b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4dd90c7b-6de2-40da-81dc-1e2faaac480c/20240101_232839/loader-set-4dd90c7b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4dd90c7b-6de2-40da-81dc-1e2faaac480c/20240101_232839/loader-set-4dd90c7b.tar.gz)
- **monitor-set-4dd90c7b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4dd90c7b-6de2-40da-81dc-1e2faaac480c/20240101_232839/monitor-set-4dd90c7b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4dd90c7b-6de2-40da-81dc-1e2faaac480c/20240101_232839/monitor-set-4dd90c7b.tar.gz)
- **parallel-timelines-report-4dd90c7b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4dd90c7b-6de2-40da-81dc-1e2faaac480c/20240101_232839/parallel-timelines-report-4dd90c7b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4dd90c7b-6de2-40da-81dc-1e2faaac480c/20240101_232839/parallel-timelines-report-4dd90c7b.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2024.1/job/longevity/job/longevity-cdc-100gb-4h-test/9/)
[Argus](https://argus.scylladb.com/test/c64d7261-b3df-451a-9d66-b8d6acb4cb35/runs?additionalRuns[]=4dd90c7b-6de2-40da-81dc-1e2faaac480c)
</details>

                            

Migrated to Jira: [SCT-13](https://scylladb.atlassian.net/browse/SCT-13)

[SCT-13]: https://scylladb.atlassian.net/browse/SCT-13?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by fruch** [comment]
Something similar happened in
https://argus.scylladb.com/tests/scylla-cluster-tests/f0094227-edde-463e-b35b-b5e1cd320f47

`check_group0_tokenring_consistency` should generate healthcheck errors when called within healthcheck, and never raise exceptions that would kill the nemesis thread

Also within in it should handle None response better filter them out or clear error events message about them
