### ISSUE TITLE
unhandled exception in RefreshMonkey

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla-cluster-tests#712]
happened in http://jenkins.cloudius-systems.com:8080/job/scylla-3.0/job/3.0-test/job/scylla-longevity-test/label=aws-scylla-qa-builder1/14/

@amoskong this is on branch-3.0 with the fix you did for refresh monkey.
Please take a look.

```
08:52:56 avocado.test: sdcm.nemesis.ChaosMonkey: Exception in random_disrupt_method nodetool_refresh: Command '/bin/ssh  -a -x   -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpqayqXW -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l centos -p 22 -i /var/tmp/longevity-10gb-3h-2.3-sct-df8a750b.pem 18.208.183.146 "sudo tar xvfz /tmp/keyspace1.standard1.tar.gz -C /var/lib/scylla/data/keyspace1/counter1-1c188ee0feb411e8aa86000000000008/upload/"' failed (rc=2)
08:52:56 avocado.test: sdcm.nemesis.ChaosMonkey: Unhandled exception in method <function disrupt at 0x35f1c08>
08:52:56 Traceback (most recent call last):
08:52:56   File "/jenkins/slave/workspace/scylla-3.0/3.0-test/scylla-longevity-test/label/aws-scylla-qa-builder1/sdcm/nemesis.py", line 727, in wrapper
08:52:56     result = method(*args, **kwargs)
08:52:56   File "/jenkins/slave/workspace/scylla-3.0/3.0-test/scylla-longevity-test/label/aws-scylla-qa-builder1/sdcm/nemesis.py", line 881, in disrupt
08:52:56     self.call_random_disrupt_method()
08:52:56   File "/jenkins/slave/workspace/scylla-3.0/3.0-test/scylla-longevity-test/label/aws-scylla-qa-builder1/sdcm/nemesis.py", line 443, in call_random_disrupt_method
08:52:56     disrupt_method()
08:52:56   File "/jenkins/slave/workspace/scylla-3.0/3.0-test/scylla-longevity-test/label/aws-scylla-qa-builder1/sdcm/nemesis.py", line 338, in disrupt_nodetool_refresh
08:52:56     node.remoter.run('sudo tar xvfz {} -C /var/lib/scylla/data/keyspace1/{}/upload/'.format(sstable_file, upload_dir))
08:52:56   File "/jenkins/slave/workspace/scylla-3.0/3.0-test/scylla-longevity-test/label/aws-scylla-qa-builder1/sdcm/remote.py", line 906, in run
08:52:56     watch_stdout_pattern=watch_stdout_pattern)
08:52:56   File "/jenkins/slave/workspace/scylla-3.0/3.0-test/scylla-longevity-test/label/aws-scylla-qa-builder1/sdcm/remote.py", line 847, in _run
08:52:56     watch_stdout_pattern=watch_stdout_pattern)
08:52:56   File "/jenkins/slave/workspace/scylla-3.0/3.0-test/scylla-longevity-test/label/aws-scylla-qa-builder1/sdcm/remote.py", line 805, in ssh_run
08:52:56     raise process.CmdError(cmd, sp.result)
08:52:56 CmdError: Command '/bin/ssh  -a -x   -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpqayqXW -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l centos -p 22 -i /var/tmp/longevity-10gb-3h-2.3-sct-df8a750b.pem 18.208.183.146 "sudo tar xvfz /tmp/keyspace1.standard1.tar.gz -C /var/lib/scylla/data/keyspace1/counter1-1c188ee0feb411e8aa86000000000008/upload/"' failed (rc=2)
```

**Comment by amoskong** [comment]
I just added user_agent parameter to http://jenkins.cloudius-systems.com:8080/job/scylla-3.0/job/3.0-test/job/scylla-longevity-test/configure.

**Comment by amoskong** [comment]
Verified by: http://jenkins.cloudius-systems.com:8080/job/scylla-staging/job/scylla-longevity-test-clone/1

RefreshMonkey nemesis can succeed after assigned 'user_agent' parameter in sct yaml config file.

TODO: add user_agent parameter in all job which will run refresh nemesis.

**Comment by roydahan** [comment]
@amoskong, did you add user_agent to all yamls?
@bentsi, don't we have a better solution for this?

**Comment by amoskong** [comment]
I had added user_agent parameter to all 3.0 & master longevity jobs:
```
http://jenkins.cloudius-systems.com:8080/job/scylla-master-longevity/configure
http://jenkins.cloudius-systems.com:8080/job/scylla-master-longevity-1TB-aws-SST3-test/configure
http://jenkins.cloudius-systems.com:8080/job/scylla-3.0/job/3.0-test/job/scylla-longevity-test/configure
http://jenkins.cloudius-systems.com:8080/job/scylla-3.0/job/3.0-test/job/scylla-longevity-gce-test/configure
http://jenkins.cloudius-systems.com:8080/job/scylla-3.0/job/3.0-test/job/scylla-longevity-mv-si-4days/configure
http://jenkins.cloudius-systems.com:8080/job/scylla-3.0/job/3.0-test/job/scylla-longevity-1TB-aws-test/configure
http://jenkins.cloudius-systems.com:8080/job/scylla-3.0/job/3.0-test/job/scylla-longevity-1TB-gce-test/configure
http://jenkins.cloudius-systems.com:8080/job/scylla-3.0/job/3.0-test/job/scylla-longevity-multi-ks-aws/configure
http://jenkins.cloudius-systems.com:8080/job/scylla-master/job/scylla-master-longevity-1TB-aws-test/configure
http://jenkins.cloudius-systems.com:8080/job/scylla-3.0/job/3.0-test/job/scylla-longevity-200GB-with-verify-aws-test/configure
```

**Comment by bentsi** [comment]
@roydahan Yes, I sent an email 8 days ago :) Maybe it was missed somehow.
In the SCT we now have KeyStore class defined in `sdcm/keystore.py`. The purpose of this class to retrieve credentials from secure store (currently implemented as private S3 bucket). 
I will forward you again

**Comment by bentsi** [comment]
@amoskong as mentioned in the email never store any secrets anywhere except in the secure store.
