### ISSUE TITLE
Unhandled exception in RestartThenRepair nemesis - scylla_create_devices

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla-cluster-tests#713]
Failed in http://jenkins.cloudius-systems.com:8080/job/scylla-3.0/job/3.0-test/job/scylla-longevity-test/label=aws-scylla-qa-builder1/14/

@amoskong, after fixing please run 3 hours longevity with this nemesis only and make sure it works.

```
avocado.test: sdcm.nemesis.ChaosMonkey: Unhandled exception in method <function disrupt at 0x35f1c08>
11:43:17 Traceback (most recent call last):
11:43:17   File "/jenkins/slave/workspace/scylla-3.0/3.0-test/scylla-longevity-test/label/aws-scylla-qa-builder1/sdcm/nemesis.py", line 727, in wrapper
11:43:17     result = method(*args, **kwargs)
11:43:17   File "/jenkins/slave/workspace/scylla-3.0/3.0-test/scylla-longevity-test/label/aws-scylla-qa-builder1/sdcm/nemesis.py", line 881, in disrupt
11:43:17     self.call_random_disrupt_method()
11:43:17   File "/jenkins/slave/workspace/scylla-3.0/3.0-test/scylla-longevity-test/label/aws-scylla-qa-builder1/sdcm/nemesis.py", line 443, in call_random_disrupt_method
11:43:17     disrupt_method()
11:43:17   File "/jenkins/slave/workspace/scylla-3.0/3.0-test/scylla-longevity-test/label/aws-scylla-qa-builder1/sdcm/nemesis.py", line 167, in disrupt_restart_then_repair_node
11:43:17     self.target_node.restart()
11:43:17   File "/jenkins/slave/workspace/scylla-3.0/3.0-test/scylla-longevity-test/label/aws-scylla-qa-builder1/sdcm/cluster_aws.py", line 352, in restart
11:43:17     self.remoter.run('sudo /usr/lib/scylla/scylla-ami/scylla_create_devices')
11:43:17   File "/jenkins/slave/workspace/scylla-3.0/3.0-test/scylla-longevity-test/label/aws-scylla-qa-builder1/sdcm/remote.py", line 906, in run
11:43:17     watch_stdout_pattern=watch_stdout_pattern)
11:43:17   File "/jenkins/slave/workspace/scylla-3.0/3.0-test/scylla-longevity-test/label/aws-scylla-qa-builder1/sdcm/remote.py", line 847, in _run
11:43:17     watch_stdout_pattern=watch_stdout_pattern)
11:43:17   File "/jenkins/slave/workspace/scylla-3.0/3.0-test/scylla-longevity-test/label/aws-scylla-qa-builder1/sdcm/remote.py", line 805, in ssh_run
11:43:17     raise process.CmdError(cmd, sp.result)
11:43:17 CmdError: Command '/bin/ssh  -a -x   -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpYGPgUS -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l centos -p 22 -i /var/tmp/longevity-10gb-3h-2.3-sct-df8a750b.pem 35.174.165.156 "sudo /usr/lib/scylla/scylla-ami/scylla_create_devices"' failed (rc=255)
```

**Comment by amoskong** [comment]
I found some backtraces and one coredump in the job log, just sent an email to qa-list with details.
subject: Coredump in longevity 3.0

**Comment by amoskong** [comment]
In this job, two nemesis was executed.
```
2018-12-13 09:34:49,865 | : >>>>>>>>>>>>>Started random_disrupt_method restart_then_repair_node
2018-12-13 09:41:15,391 | : <<<<<<<<<<<<<Finished random_disrupt_method restart_then_repair_node
2018-12-13 11:41:43,629 | : >>>>>>>>>>>>>Started random_disrupt_method restart_then_repair_node
```

First restart_then_repair nemesis finished without error (code exception, error).
Second restart_then_repair nemesis broke in creating the device. It seems the network isn't available when executed the scylla_create_devices command.

I added a self.wait_ssh_up() before execute scylla_create_devices command, and submitted a job to test only RestartThenRepairNodeMonkey.
