### ISSUE TITLE
scylla with custom release string fails

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla-cluster-tests#7153]
```
20:54:21  < t:2024-01-27 18:54:20,932 f:tester.py       l:168  c:sdcm.tester          p:ERROR > Exception in setUp. Will call tearDown < t:2024-01-27 18:54:20,932 f:tester.py       l:168  c:sdcm.tester          p:ERROR > Exception in setUp. Will call tearDown
20:54:21  < t:2024-01-27 18:54:20,932 f:tester.py       l:168  c:sdcm.tester          p:ERROR > Traceback (most recent call last):
20:54:21  < t:2024-01-27 18:54:20,932 f:tester.py       l:168  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 161, in wrapper
20:54:21  < t:2024-01-27 18:54:20,932 f:tester.py       l:168  c:sdcm.tester          p:ERROR >     return method(*args, **kwargs)
20:54:21  < t:2024-01-27 18:54:20,932 f:tester.py       l:168  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 119, in inner
20:54:21  < t:2024-01-27 18:54:20,932 f:tester.py       l:168  c:sdcm.tester          p:ERROR >     res = func(*args, **kwargs)
20:54:21  < t:2024-01-27 18:54:20,932 f:tester.py       l:168  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 827, in setUp
20:54:21  < t:2024-01-27 18:54:20,932 f:tester.py       l:168  c:sdcm.tester          p:ERROR >     self.create_test_stats()
20:54:21  < t:2024-01-27 18:54:20,932 f:tester.py       l:168  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/db_stats.py", line 657, in create_test_stats
20:54:21  < t:2024-01-27 18:54:20,932 f:tester.py       l:168  c:sdcm.tester          p:ERROR >     self._stats['versions'] = self.get_scylla_versions()
20:54:21  < t:2024-01-27 18:54:20,932 f:tester.py       l:168  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/db_stats.py", line 581, in get_scylla_versions
20:54:21  < t:2024-01-27 18:54:20,932 f:tester.py       l:168  c:sdcm.tester          p:ERROR >     versions['scylla-server']['build_mode'] = node.scylla_build_mode
20:54:21  < t:2024-01-27 18:54:20,932 f:tester.py       l:168  c:sdcm.tester          p:ERROR > KeyError: 'scylla-server'
20:54:21  < t:2024-01-27 18:54:20,934 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 2024-01-27 18:54:20.931: 
```

I suspect the regex in get_scylla_versions is too tight.

**Comment by fruch** [comment]
this code isn't safe regardless of which version string it is.


@avikivity can you share the version ? so whom would work fixing it can try it out ?

**Comment by fruch** [comment]
this specific issue was handled in

f6e16274962c226067f21f5d94217652ba640dcf

it was a mistake, and the code wasn't safe enough, assuming optional things always happen.
