### ISSUE TITLE
artifact tests failed on ClusterNodesNotReady: Not all nodes joined the cluster

### ISSUE THREAD

**Issue by Annamikhlin** [scylladb/scylla-cluster-tests#7274]
### Issue description

all artifact tests failed with the following ERROR:
```
01:07:41  ======================================================================
01:07:41  ERROR: test_scylla_service (artifacts_test.ArtifactsTest)
01:07:41  ----------------------------------------------------------------------
01:07:41  Traceback (most recent call last):
01:07:41    File "/tmp/jenkins/workspace/scylla-master/artifacts/artifacts-docker-test/scylla-cluster-tests/artifacts_test.py", line 46, in setUp
01:07:41      super().setUp()
01:07:41    File "/tmp/jenkins/workspace/scylla-master/artifacts/artifacts-docker-test/scylla-cluster-tests/sdcm/tester.py", line 175, in wrapper
01:07:41      return method(*args, **kwargs)
01:07:41    File "/tmp/jenkins/workspace/scylla-master/artifacts/artifacts-docker-test/scylla-cluster-tests/sdcm/utils/decorators.py", line 119, in inner
01:07:41      res = func(*args, **kwargs)
01:07:41    File "/tmp/jenkins/workspace/scylla-master/artifacts/artifacts-docker-test/scylla-cluster-tests/sdcm/tester.py", line 890, in setUp
01:07:41      self.init_nodes(db_cluster=db_cluster)
01:07:41    File "/tmp/jenkins/workspace/scylla-master/artifacts/artifacts-docker-test/scylla-cluster-tests/sdcm/tester.py", line 768, in init_nodes
01:07:41      db_cluster.wait_for_init(node_list=db_cluster.nodes)
01:07:41    File "/tmp/jenkins/workspace/scylla-master/artifacts/artifacts-docker-test/scylla-cluster-tests/sdcm/cluster.py", line 3802, in wrapper
01:07:41      cl_inst.wait_for_nodes_up_and_normal(nodes=node_list, verification_node=node_list[0], timeout=timeout)
01:07:41    File "/tmp/jenkins/workspace/scylla-master/artifacts/artifacts-docker-test/scylla-cluster-tests/sdcm/cluster.py", line 4273, in wait_for_nodes_up_and_normal
01:07:41      _wait_for_nodes_up_and_normal()
01:07:41    File "/tmp/jenkins/workspace/scylla-master/artifacts/artifacts-docker-test/scylla-cluster-tests/sdcm/utils/decorators.py", line 70, in inner
01:07:41      return func(*args, **kwargs)
01:07:41    File "/tmp/jenkins/workspace/scylla-master/artifacts/artifacts-docker-test/scylla-cluster-tests/sdcm/cluster.py", line 4271, in _wait_for_nodes_up_and_normal
01:07:41      self.check_nodes_up_and_normal(nodes=nodes, verification_node=verification_node)
01:07:41    File "/tmp/jenkins/workspace/scylla-master/artifacts/artifacts-docker-test/scylla-cluster-tests/sdcm/cluster.py", line 4240, in check_nodes_up_and_normal
01:07:41      raise ClusterNodesNotReady("Not all nodes joined the cluster")
01:07:41  sdcm.cluster.ClusterNodesNotReady: Not all nodes joined the cluster
01:07:41  
01:07:41  ----------------------------------------------------------------------
01:07:41  Ran 1 test in 376.157s
01:07:41  
01:07:41  FAILED (errors=2) 
```

#### Steps to Reproduce

Re-run the artifact tests.

### Impact

unified-deb, centos-rpm and docker jobs failed on master branch

### How frequently does it reproduce?

every run started from Mar 15 

### Logs
* artifacts-docker-test: https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-docker-test/856
* artifacts-rocky8-test: https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-rocky8-test/400
* artifacts-ubuntu2204-test: https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-ubuntu2204-test/464

**Comment by fruch** [comment]
look like the regex SCT was using was a bit to sensitive on spacing between values, and hence is failing to read the output of the new tool

**Comment by fruch** [comment]
seems like this should the fix, but we should accompany it with some unit tests, to validate both outputs
 
```diff
diff --git a/sdcm/cluster.py b/sdcm/cluster.py
index 2d8fe7801..2359e0d31 100644
--- a/sdcm/cluster.py
+++ b/sdcm/cluster.py
@@ -4130,7 +4130,7 @@ class BaseScyllaCluster:  # pylint: disable=too-many-public-methods, too-many-in
             r"(?P<load>[\d.]+ [\w]+|\?)\s+"
             r"(?P<tokens>[\d]+)\s+"
             r"(?P<owns>[\w?]+)\s+"
-            r"(?P<host_id>[\w-]+)\s{2,}"
+            r"(?P<host_id>[\w-]+)\s+"
             r"(?P<rack>[\w]+|$)")

         for dc in data_centers:
```

**Comment by soyacz** [comment]
I can handle it

**Comment by benipeled** [comment]
The issue still occurs on both master and enterprise,
**The last successful** offline-install run was on **Feb.15**
```
01:03:51  ======================================================================
01:03:51  ERROR: test_scylla_service (artifacts_test.ArtifactsTest)
01:03:51  ----------------------------------------------------------------------
01:03:51  Traceback (most recent call last):
01:03:51    File "/tmp/workspace/scylla-master/artifacts-offline-install/artifacts-ubuntu2204-nonroot-test/scylla-cluster-tests/artifacts_test.py", line 46, in setUp
01:03:51      super().setUp()
01:03:51    File "/tmp/workspace/scylla-master/artifacts-offline-install/artifacts-ubuntu2204-nonroot-test/scylla-cluster-tests/sdcm/tester.py", line 175, in wrapper
01:03:51      return method(*args, **kwargs)
01:03:51    File "/tmp/workspace/scylla-master/artifacts-offline-install/artifacts-ubuntu2204-nonroot-test/scylla-cluster-tests/sdcm/utils/decorators.py", line 119, in inner
01:03:51      res = func(*args, **kwargs)
01:03:51    File "/tmp/workspace/scylla-master/artifacts-offline-install/artifacts-ubuntu2204-nonroot-test/scylla-cluster-tests/sdcm/tester.py", line 890, in setUp
01:03:51      self.init_nodes(db_cluster=db_cluster)
01:03:51    File "/tmp/workspace/scylla-master/artifacts-offline-install/artifacts-ubuntu2204-nonroot-test/scylla-cluster-tests/sdcm/tester.py", line 768, in init_nodes
01:03:51      db_cluster.wait_for_init(node_list=db_cluster.nodes)
01:03:51    File "/tmp/workspace/scylla-master/artifacts-offline-install/artifacts-ubuntu2204-nonroot-test/scylla-cluster-tests/sdcm/cluster.py", line 3808, in wrapper
01:03:51      cl_inst.wait_for_nodes_up_and_normal(nodes=node_list, verification_node=node_list[0], timeout=timeout)
01:03:51    File "/tmp/workspace/scylla-master/artifacts-offline-install/artifacts-ubuntu2204-nonroot-test/scylla-cluster-tests/sdcm/cluster.py", line 4279, in wait_for_nodes_up_and_normal
01:03:51      _wait_for_nodes_up_and_normal()
01:03:51    File "/tmp/workspace/scylla-master/artifacts-offline-install/artifacts-ubuntu2204-nonroot-test/scylla-cluster-tests/sdcm/utils/decorators.py", line 70, in inner
01:03:51      return func(*args, **kwargs)
01:03:51    File "/tmp/workspace/scylla-master/artifacts-offline-install/artifacts-ubuntu2204-nonroot-test/scylla-cluster-tests/sdcm/cluster.py", line 4277, in _wait_for_nodes_up_and_normal
01:03:51      self.check_nodes_up_and_normal(nodes=nodes, verification_node=verification_node)
01:03:51    File "/tmp/workspace/scylla-master/artifacts-offline-install/artifacts-ubuntu2204-nonroot-test/scylla-cluster-tests/sdcm/cluster.py", line 4246, in check_nodes_up_and_normal
01:03:51      raise ClusterNodesNotReady("Not all nodes joined the cluster")
01:03:51  sdcm.cluster.ClusterNodesNotReady: Not all nodes joined the cluster
01:03:51  
01:03:51  ----------------------------------------------------------------------
01:03:51  Ran 1 test in 786.386s
01:03:51  
01:03:51  FAILED (errors=2)
```

**Comment by fruch** [comment]
@benipeled 

it's not an SCT issue, it's core issue

```
< t:2024-04-08 22:57:08,538 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > /home/scylla-test/scylladb/share/cassandra/bin/nodetool: line 40:  5792 Aborted                 (core dumped) "$SCYLLA_PATH" nodetool "$@" $help_opt &> /dev/null
< t:2024-04-08 22:57:09,039 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > terminate called after throwing an instance of 'std::runtime_error'
< t:2024-04-08 22:57:09,539 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG >   what():  Could not setup Async I/O: Resource temporarily unavailable. The required nr_event (1) exceeds the limit of request capacity in /proc/sys/fs/aio-max-nr (65536). Try increasing that number or reducing the amount of logical CPUs available for your application
< t:2024-04-08 22:57:09,540 f:base.py         l:140  c:RemoteLibSSH2CmdRunner p:DEBUG > STDERR: /home/scylla-test/scylladb/share/cassandra/bin/nodetool: line 40:  5792 Aborted                 (core dumped) "$SCYLLA_PATH" nodetool "$@" $help_opt &> /dev/null
```

nodetool cmd is crashing
it's https://github.com/scylladb/scylladb/issues/17412, it's wasn't solved completely

**Comment by fruch** [comment]
it's https://github.com/scylladb/scylladb/issues/17412
