### ISSUE TITLE
[YCSB][alternaor-dns][GCP] Temporary failure in name resolution 

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#7302]
## Packages

Scylla version: `5.4.4-20240228.58a1be93b212` with build-id `f385c89e3d29e70e0a8beab1dfefcace5e909775`

Kernel Version: `3.10.0-1160.108.1.el7.x86_64`

## Issue description

- [x] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

recently this upgrade job started failing in running YCSB with alternator, this jos is using the alternator-dns 

and seems like it's failing like the following:
```
Exception happened during processing of request from ('172.17.0.3', 55272)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/local/lib/python3.8/site-packages/dnslib/server.py", line 144, in handle
    rdata = self.get_reply(data)
  File "/usr/local/lib/python3.8/site-packages/dnslib/server.py", line 161, in get_reply
    reply = resolver.resolve(request,self)
  File "/dns_server.py", line 66, in resolve
    proxy_r = request.send(self.address, self.port,
  File "/usr/local/lib/python3.8/site-packages/dnslib/dns.py", line 368, in send
    length = struct.unpack("!H",bytes(response[:2]))[0]
struct.error: unpack requires a buffer of 2 bytes
----------------------------------------
```

not clear why not getting response from the name server at all 

## Impact

we can't run alternator case on GCE anymore, since we need the DNS to work
for be able to restart nodes (or run nemesis)

## How frequently does it reproduce?

it reproduced in two jobs in a row

## Installation details

Cluster size: 3 nodes (n1-highmem-8)

Scylla Nodes used in this run:
- rolling-upgrade--centos-db-node-32917f0d-0-3 (35.231.250.109 | 10.142.0.42) (shards: 7)
- rolling-upgrade--centos-db-node-32917f0d-0-2 (34.23.141.33 | 10.142.0.30) (shards: 7)
- rolling-upgrade--centos-db-node-32917f0d-0-1 (34.23.35.162 | 10.142.0.13) (shards: 7)

OS / Image: `https://www.googleapis.com/compute/v1/projects/centos-cloud/global/images/family/centos-7` (gce: undefined_region)

Test: `rolling-upgrade-alternator-test`
Test id: `32917f0d-fca1-483a-9987-401d613a4e07`
Test name: `scylla-master/rolling-upgrade/rolling-upgrade-alternator-test`
Test config file(s):

- [generic-rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/a452ce97e5d1b1852d990dd1ac69b5e276495a14/test-cases/upgrades/generic-rolling-upgrade.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 32917f0d-fca1-483a-9987-401d613a4e07`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=32917f0d-fca1-483a-9987-401d613a4e07)
- Show all stored logs command: `$ hydra investigate show-logs 32917f0d-fca1-483a-9987-401d613a4e07`

## Logs:
- **db-cluster-32917f0d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/32917f0d-fca1-483a-9987-401d613a4e07/20240323_110350/db-cluster-32917f0d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/32917f0d-fca1-483a-9987-401d613a4e07/20240323_110350/db-cluster-32917f0d.tar.gz)
- **sct-runner-events-32917f0d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/32917f0d-fca1-483a-9987-401d613a4e07/20240323_110350/sct-runner-events-32917f0d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/32917f0d-fca1-483a-9987-401d613a4e07/20240323_110350/sct-runner-events-32917f0d.tar.gz)
- **sct-32917f0d.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/32917f0d-fca1-483a-9987-401d613a4e07/20240323_110350/sct-32917f0d.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/32917f0d-fca1-483a-9987-401d613a4e07/20240323_110350/sct-32917f0d.log.tar.gz)
- **loader-set-32917f0d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/32917f0d-fca1-483a-9987-401d613a4e07/20240323_110350/loader-set-32917f0d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/32917f0d-fca1-483a-9987-401d613a4e07/20240323_110350/loader-set-32917f0d.tar.gz)
- **monitor-set-32917f0d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/32917f0d-fca1-483a-9987-401d613a4e07/20240323_110350/monitor-set-32917f0d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/32917f0d-fca1-483a-9987-401d613a4e07/20240323_110350/monitor-set-32917f0d.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-alternator-test/203/)
[Argus](https://argus.scylladb.com/test/47e85d0a-e0a6-4909-83f0-928a1bf18c9e/runs?additionalRuns[]=32917f0d-fca1-483a-9987-401d613a4e07)
</details>

**Comment by fruch** [comment]
seem like docker is now version `docker-ce-26.0.0-1.el7.x86_64` vs. `docker-ce-25.0.4-1.el7.x86_64` in a working job

**Comment by fruch** [comment]
look like the new version is fixing some security issue 
https://github.com/moby/moby/pull/47538

and it's now blocking the DNS requests, and we'll need to configure it a bit differently to have access to the external DNS
