### ISSUE TITLE
` AttributeError: 'CollectingNode' object has no attribute 'parent_cluster'` error calling `get_grafana_snapshot` function

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-cluster-tests#7323]
## Packages

Base Scylla version: `5.4.5-20240328.fd7d57b9fa26` with build-id `0bb6a5f3f87d481576ab0c3c6247b2beba69c17a`
Target Scylla version (or git commit hash): `5.5.0~dev-20240403.baae811142e2` with build-id `030312786e4ec5fc082f65330ae641c075e2ddb5`

Kernel Version: `5.15.0-1053-gcp`

## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

In the `log collection` stage we started having following error:
```
21:59:36  scylla-monitoring-src, branch-4.6, 5.4
21:59:44  Error taking monitor screenshot: 'CollectingNode' object has no attribute 'parent_cluster', traceback: Traceback (most recent call last):
21:59:44    File "/home/ubuntu/scylla-cluster-tests/sdcm/logcollector.py", line 493, in get_grafana_screenshot
21:59:44      self.remote_browser = RemoteBrowser(node)
21:59:44    File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/remotewebbrowser.py", line 67, in __init__
21:59:44      backend = self.node.parent_cluster.params.get("cluster_backend")
21:59:44  AttributeError: 'CollectingNode' object has no attribute 'parent_cluster'
21:59:44  
21:59:45  Error taking monitor snapshot: 'CollectingNode' object has no attribute 'parent_cluster', traceback: Traceback (most recent call last):
21:59:45    File "/home/ubuntu/scylla-cluster-tests/sdcm/logcollector.py", line 555, in get_grafana_snapshot
21:59:45      self.remote_browser = RemoteBrowser(node)
21:59:45    File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/remotewebbrowser.py", line 67, in __init__
21:59:45      backend = self.node.parent_cluster.params.get("cluster_backend")
21:59:45  AttributeError: 'CollectingNode' object has no attribute 'parent_cluster'
```

The root cause is here: https://github.com/scylladb/scylla-cluster-tests/pull/7315/commits/5014b13ed4cd5d69c96c58c83acc4eebba1a6666

## Installation details

Cluster size: 4 nodes (n2-highmem-64)

Scylla Nodes used in this run:
- rolling-upgrade--ubuntu-focal-db-node-151d470d-0-4 (34.148.186.115 | 10.142.0.77) (shards: 60)
- rolling-upgrade--ubuntu-focal-db-node-151d470d-0-3 (34.148.169.76 | 10.142.0.72) (shards: 60)
- rolling-upgrade--ubuntu-focal-db-node-151d470d-0-2 (34.148.94.141 | 10.142.0.63) (shards: 60)
- rolling-upgrade--ubuntu-focal-db-node-151d470d-0-1 (34.74.61.253 | 10.142.0.31) (shards: 60)

OS / Image: `https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/family/ubuntu-2004-lts` (gce: undefined_region)

Test: `vp-rolling-upgrade-ubuntu20.04-test`
Test id: `151d470d-0dd5-4f07-b3f7-6a6329d839b5`
Test name: `scylla-staging/valerii/vp-rolling-upgrade-ubuntu20.04-test`
Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/8bce59add5bcda1593a64adcfce0d213b855e956/test-cases/upgrades/rolling-upgrade.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 151d470d-0dd5-4f07-b3f7-6a6329d839b5`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=151d470d-0dd5-4f07-b3f7-6a6329d839b5)
- Show all stored logs command: `$ hydra investigate show-logs 151d470d-0dd5-4f07-b3f7-6a6329d839b5`

## Logs:
- **db-cluster-151d470d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/151d470d-0dd5-4f07-b3f7-6a6329d839b5/20240404_182240/db-cluster-151d470d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/151d470d-0dd5-4f07-b3f7-6a6329d839b5/20240404_182240/db-cluster-151d470d.tar.gz)
- **sct-runner-events-151d470d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/151d470d-0dd5-4f07-b3f7-6a6329d839b5/20240404_182240/sct-runner-events-151d470d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/151d470d-0dd5-4f07-b3f7-6a6329d839b5/20240404_182240/sct-runner-events-151d470d.tar.gz)
- **sct-151d470d.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/151d470d-0dd5-4f07-b3f7-6a6329d839b5/20240404_182240/sct-151d470d.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/151d470d-0dd5-4f07-b3f7-6a6329d839b5/20240404_182240/sct-151d470d.log.tar.gz)
- **loader-set-151d470d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/151d470d-0dd5-4f07-b3f7-6a6329d839b5/20240404_182240/loader-set-151d470d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/151d470d-0dd5-4f07-b3f7-6a6329d839b5/20240404_182240/loader-set-151d470d.tar.gz)
- **monitor-set-151d470d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/151d470d-0dd5-4f07-b3f7-6a6329d839b5/20240404_182240/monitor-set-151d470d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/151d470d-0dd5-4f07-b3f7-6a6329d839b5/20240404_182240/monitor-set-151d470d.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/valerii/job/vp-rolling-upgrade-ubuntu20.04-test/2/)
[Argus](https://argus.scylladb.com/test/ba1076d0-9130-44ef-a261-16974aea400f/runs?additionalRuns[]=151d470d-0dd5-4f07-b3f7-6a6329d839b5)
</details>

**Comment by fruch** [comment]
The job you reference here has much more concerning failure

```
 Fatal Python error: Segmentation fault
```

**Comment by vponomaryov** [comment]
> The job you reference here has much more concerning failure
> 
> ```
>  Fatal Python error: Segmentation fault
> ```

This one is not repeatable. And looks unrelated to our codebase.

**Comment by fruch** [comment]
@vponomaryov 

can you please look into fixing this one ? (I won't be able to get to it)
