### ISSUE TITLE
cql_connection_patient: gaierror: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by bentsi** [scylladb/scylla-cluster-tests#737]
When connection is created during  "restart_then_repair_node" nmesis public ip changes and 
when `WhiteListRoundRobinPolicy` chooses the node that is selected as target we get following exception:

```
Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado/core/test.py:449
Traceback (most recent call last):
  File "/sct/longevity_test.py", line 169, in test_custom_time
    self._run_all_stress_cmds(stress_queue, params)
  File "/sct/longevity_test.py", line 43, in _run_all_stress_cmds
    self._parse_stress_cmd(stress_cmd, params)
  File "/sct/longevity_test.py", line 62, in _parse_stress_cmd
    self._create_counter_table()
  File "/sct/longevity_test.py", line 180, in _create_counter_table
    session = self.cql_connection_patient(node)
  File "/sct/sdcm/tester.py", line 820, in cql_connection_patient
    bypassed_exception=NoHostAvailable)
  File "/sct/sdcm/tester.py", line 108, in retry_till_success
    return fun(*args, **kwargs)
  File "/sct/sdcm/tester.py", line 786, in cql_connection
    wlrr = WhiteListRoundRobinPolicy(self.db_cluster.get_node_public_ips())
  File "/usr/lib64/python2.7/site-packages/cassandra/policies.py", line 417, in __init__
    for endpoint in socket.getaddrinfo(a, None, socket.AF_UNSPEC, socket.SOCK_STREAM)]
gaierror: [Errno -2] Name or service not known
```

Possible fixes:
- consider using `RetryPolicy`
- add exception handling in `cql_connection_patient` code (probably use @retrying decorator)

**Comment by bentsi** [comment]
very rare and we wrap cql_connection_patient with retrying decorator
