### ISSUE TITLE
Error during create screenshot of per-server-metrics

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#7476]
Trying to run perf test on master shows error with screenshot creation:
```
10:20:21  Save a screenshot of http://10.12.3.105:3000/d/c1ec8611-2c48-4444-b5a6-309312472add/cd79dcb8-2282-5c7c-a9ec-9482b4c8b883?from=1716430673000&to=now&refresh=1d to /home/ubuntu/sct-results/20240523-063544-666428/collected_logs/20240523_081753/monitor-set-473d3695/perf-regression-i4i-4x-650gb-ubuntu-monitor-node-473d3695-1/grafana-screenshot-perf-regression-throughput-non-shard-aware-i4i-4xlarge-test-650gb-scylla-per-server-metrics-nemesis-20240523_082000-perf-regression-i4i-4x-650gb-ubuntu-monitor-node-473d3695-1.png
10:20:47  Exception (client): Error reading SSH protocol banner
10:20:47  Traceback (most recent call last):
10:20:47    File "/usr/local/lib/python3.10/site-packages/paramiko/transport.py", line 2327, in _check_banner
10:20:47      buf = self.packetizer.readline(timeout)
10:20:47    File "/usr/local/lib/python3.10/site-packages/paramiko/packet.py", line 381, in readline
10:20:47      buf += self._read_timeout(timeout)
10:20:47    File "/usr/local/lib/python3.10/site-packages/paramiko/packet.py", line 626, in _read_timeout
10:20:47      raise socket.timeout()
10:20:47  TimeoutError
10:20:47  
10:20:47  During handling of the above exception, another exception occurred:
10:20:47  
10:20:47  Traceback (most recent call last):
10:20:47    File "/usr/local/lib/python3.10/site-packages/paramiko/transport.py", line 2143, in run
10:20:47      self._check_banner()
10:20:47    File "/usr/local/lib/python3.10/site-packages/paramiko/transport.py", line 2331, in _check_banner
10:20:47      raise SSHException(
10:20:47  paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
10:20:47  
10:21:09  Error get screenshot perf-regression-throughput-non-shard-aware-i4i-4xlarge-test-650gb-scylla-per-server-metrics-nemesis: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"Unable to capture screenshot"}
10:21:09    (Session info: chrome=91.0.4472.114)
10:21:09  Traceback (most recent call last):
10:21:09    File "/home/ubuntu/scylla-cluster-tests/sdcm/logcollector.py", line 519, in get_grafana_screenshot
10:21:09      self.remote_browser.get_screenshot(grafana_url, screenshot_path)
10:21:09    File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/remotewebbrowser.py", line 112, in get_screenshot
10:21:09      self.browser.get_screenshot_as_file(screenshot_path)
10:21:09    File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 1032, in get_screenshot_as_file
10:21:09      png = self.get_screenshot_as_png()
10:21:09    File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 1064, in get_screenshot_as_png
10:21:09      return base64.b64decode(self.get_screenshot_as_base64().encode('ascii'))
10:21:09    File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 1074, in get_screenshot_as_base64
10:21:09      return self.execute(Command.SCREENSHOT)['value']
10:21:09    File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
10:21:09      self.error_handler.check_response(response)
10:21:09    File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
10:21:09      raise exception_class(message, screen, stacktrace)
10:21:09  selenium.common.exceptions.WebDriverException: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"Unable to capture screenshot"}
10:21:09    (Session info: chrome=91.0.4472.114)
10:21:09  
10:21:09  Grafana - browser quit
```
argus: https://argus.scylladb.com/test/38715366-8bed-41b7-8031-d1e4df2abb0f/runs?additionalRuns[]=473d3695-1e92-43a8-af69-d443a3e3b86d
jenkins job: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/lukasz/job/perf-regression-throughput-non-shard-aware-i4i-4xlarge-test-650gb/59/

**Comment by fruch** [comment]
We should ditch all those web driver parts...


It's a bit of a gentle work, but hopefully would be working better

**Comment by fruch** [comment]
we did ditched the webdriver.

no more selenium issues.
