### ISSUE TITLE
error while sending email from within the test

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#7477]
During perf test run on master, teardown tries to send email with results (I don't know why yet), and it fails causing the test to fail:
```
2024-05-23 08:17:36.686: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=cc59e623-542e-4a28-968b-1b3fc323cd09, source=PerformanceRegressionTestSplitRanges.send_email() message=send_email (silenced) failed with:
exception=An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/./sct.py", line 1798, in <module>
cli.main(prog_name="hydra")
File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
rv = self.invoke(ctx)
File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
return __callback(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/./sct.py", line 1137, in run_test
unittest.main(module=None, argv=['python -m unittest', argv],
File "/usr/local/lib/python3.10/unittest/main.py", line 101, in __init__
self.runTests()
File "/usr/local/lib/python3.10/unittest/main.py", line 271, in runTests
self.result = testRunner.run(self.test)
File "/usr/local/lib/python3.10/unittest/runner.py", line 184, in run
test(result)
File "/usr/local/lib/python3.10/unittest/suite.py", line 84, in __call__
return self.run(*args, **kwds)
File "/usr/local/lib/python3.10/unittest/suite.py", line 122, in run
test(result)
File "/usr/local/lib/python3.10/unittest/suite.py", line 84, in __call__
return self.run(*args, **kwds)
File "/usr/local/lib/python3.10/unittest/suite.py", line 122, in run
test(result)
File "/usr/local/lib/python3.10/unittest/case.py", line 650, in __call__
return self.run(*args, **kwds)
File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 720, in run
result = super().run(self.result)
File "/usr/local/lib/python3.10/unittest/case.py", line 594, in run
self._callTearDown()
File "/usr/local/lib/python3.10/unittest/case.py", line 552, in _callTearDown
self.tearDown()
File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 2856, in tearDown
self.send_email()
File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 235, in decor
self._store_test_result(args[0], exc, exc.__traceback__, name)
```

argus: https://argus.scylladb.com/test/38715366-8bed-41b7-8031-d1e4df2abb0f/runs?additionalRuns[]=473d3695-1e92-43a8-af69-d443a3e3b86d

**Comment by fruch** [comment]
It's not really sending mail, but it fails retrieving something from s3

Mail credentials maybe ?

**Comment by fruch** [comment]
@soyacz 

we agreed that we need to disable this option in all tests
