### ISSUE TITLE
artifacts-azure-image-test failed with AssertionError: New row wasn't saved in housekeeping.checkversion

### ISSUE THREAD

**Issue by yaronkaikov** [scylladb/scylla-cluster-tests#7487]
Seen in https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-azure-image-test/523 and also in https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-ami-arm-test/
```
02:26:28  < t:2024-05-25 23:26:27,357 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 2024-05-25 23:26:27.355: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=0752699a-7447-437f-86b0-741ed3d6e53b, source=ArtifactsTest.test_scylla_service (artifacts_test.ArtifactsTest) [check Scylla server after restart]() message=Traceback (most recent call last):
02:26:28  < t:2024-05-25 23:26:27,357 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/tmp/jenkins/workspace/scylla-master/artifacts/artifacts-azure-image-test/scylla-cluster-tests/artifacts_test.py", line 433, in test_scylla_service
02:26:28  < t:2024-05-25 23:26:27,357 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     self.check_scylla_version_in_housekeepingdb(prev_id=version_id_after_stop,
02:26:28  < t:2024-05-25 23:26:27,357 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   File "/tmp/jenkins/workspace/scylla-master/artifacts/artifacts-azure-image-test/scylla-cluster-tests/artifacts_test.py", line 93, in check_scylla_version_in_housekeepingdb
02:26:28  < t:2024-05-25 23:26:27,357 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     assert row[0] > prev_id, f"New row wasn't saved in {self.CHECK_VERSION_TABLE}"
02:26:28  < t:2024-05-25 23:26:27,357 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > AssertionError: New row wasn't saved in housekeeping.checkversion
```
@fruch suggested it may be related to https://github.com/scylladb/scylla-cluster-tests/pull/7445

**Comment by benipeled** [comment]
@fruch seen again on 6.0 https://jenkins.scylladb.com/job/scylla-6.0/job/artifacts/job/artifacts-azure-image-test/6/consoleFull
`c:sdcm.utils.decorators p:ERROR > 'check_scylla_version_in_housekeepingdb': Number of retries exceeded!`

**Comment by soyacz** [comment]
Most of the tests passed, I think 50 secs wait was too little. Created fix PR: https://github.com/scylladb/scylla-cluster-tests/pull/7514
