### ISSUE TITLE
disrupt_grow_shrink_cluster should be marked as 'skipped' if it failed to grow as it could not find instances to be allocated for it

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylla-cluster-tests#7531]
Example:
```
Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 5111, in wrapper
    result = method(*args[1:], **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4005, in disrupt_grow_shrink_cluster
    self._grow_cluster(rack=None)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4029, in _grow_cluster
    added_node = self.add_new_node(rack=rack_idx)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 178, in wrapped
    res = func(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3973, in add_new_node
    return self._add_and_init_new_cluster_node(rack=rack)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1231, in _add_and_init_new_cluster_node
    new_node = self.cluster.add_nodes(
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster_aws.py", line 892, in add_nodes
    added_nodes = super().add_nodes(
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster_aws.py", line 387, in add_nodes
    instances = self._create_or_find_instances(
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster_aws.py", line 366, in _create_or_find_instances
    return self._create_instances(count, ec2_user_data, dc_idx, az_idx, instance_type=instance_type)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster_aws.py", line 229, in _create_instances
    instances = self._create_on_demand_instances(count, interfaces, ec2_user_data, dc_idx,
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster_aws.py", line 158, in _create_on_demand_instances
    instances = self._ec2_services[dc_idx].create_instances(**params)
  File "/usr/local/lib/python3.10/site-packages/boto3/resources/factory.py", line 580, in do_action
    response = action(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/boto3/resources/action.py", line 88, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 534, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 976, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 4): We currently do not have sufficient i4i.2xlarge capacity in zones with support for 'gp3' volumes. Our system will be working on provisioning additional capacity.
```

This specific exception should be caught and handled - we could not grow the cluster as it did not manage to find more instances (unsure why it needed 'gp3' volumes?!).
In this specific case, the Nemesis should be skipped.

**Comment by mykaul** [comment]
I think the error is UnfulfillableCapacity (based on https://docs.aws.amazon.com/AWSEC2/latest/APIReference/errors-overview.html#CommonErrors ), but who knows.
