### ISSUE TITLE
rolling-upgrade-alternator-test failed to setup YCSB thread

### ISSUE THREAD

**Issue by enaydanov** [scylladb/scylla-cluster-tests#7532]
```
2024-05-30 11:39:50.648: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=4b26451c-021d-4f1f-943b-0d89066c097a, source=UpgradeTest.test_generic_cluster_upgrade (upgrade_test.UpgradeTest)() message=Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/upgrade_test.py", line 990, in test_generic_cluster_upgrade
self._run_stress_workload("stress_after_cluster_upgrade", wait_for_finish=True)
File "/home/ubuntu/scylla-cluster-tests/upgrade_test.py", line 916, in _run_stress_workload
self.verify_stress_thread(thread_pool)
File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 2174, in verify_stress_thread
results, errors = cs_thread_pool.verify_results()
File "/home/ubuntu/scylla-cluster-tests/sdcm/stress/base.py", line 104, in verify_results
results.append(future.result())
File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 451, in result
return self.__get_result()
File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
raise self._exception
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/ycsb_thread.py", line 273, in _run_stress
self.copy_template(cmd_runner, loader.name)
File "/home/ubuntu/scylla-cluster-tests/sdcm/ycsb_thread.py", line 163, in copy_template
secretKey = {alternator.api.Alternator.get_salted_hash(node=self.node_list[0], username=self.params.get('alternator_access_key_id'))}
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/alternator/api.py", line 56, in get_salted_hash
return next(iter(response)).salted_hash
File "cassandra/cluster.py", line 5263, in cassandra.cluster.ResultSet.next
File "cassandra/cluster.py", line 5258, in cassandra.cluster.ResultSet.next
StopIteration
```

Base ScyllaDB version is 5.4.6-20240418.10f137e367e3

Failure in scylla-master job: https://argus.scylladb.com/test/47e85d0a-e0a6-4909-83f0-928a1bf18c9e/runs?additionalRuns[]=cdc39b75-0318-4d81-aabd-0d98f5edbd3e

Failure in scylla-6.0 job: https://argus.scylladb.com/test/0413e443-5c26-4854-9dc0-8a6cf3792571/runs?additionalRuns[]=66ee9e18-b4d6-441c-a827-c9642af362d5

This code was introduced in https://github.com/scylladb/scylla-cluster-tests/pull/7422/

**Comment by fruch** [comment]
it was fixed in:
https://github.com/scylladb/scylla-cluster-tests/pull/7439

**Comment by fruch** [comment]
was passing yesterday on 6.0
https://argus.scylladb.com/test/0413e443-5c26-4854-9dc0-8a6cf3792571/runs?additionalRuns[]=845093a4-8eb7-40b1-90d0-6e8b09f07ac1

**Comment by enaydanov** [comment]
@fruch it's failed again: https://argus.scylladb.com/test/0413e443-5c26-4854-9dc0-8a6cf3792571/runs?additionalRuns[]=ec73a25c-1eff-4836-947f-c0ca92ac5fca
