### ISSUE TITLE
`artifacts-centos8-arm-test` failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist

### ISSUE THREAD

**Issue by Annamikhlin** [scylladb/scylla-cluster-tests#7542]
`artifacts-centos8-arm-test` failed on few branches (master/enterprise/branch-6.0/branch-5.4) with the same error:
```
0:48:11  ERROR: test_scylla_service (artifacts_test.ArtifactsTest)
10:48:11  ----------------------------------------------------------------------
10:48:11  sdcm.sct_events.system.TestResultEvent: ================================= TEST RESULTS =================================
10:48:11  
10:48:11  ----- LAST ERROR EVENT -------------------------------------------------------
10:48:11  2024-06-03 07:47:56.715: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=791cfb78-e036-4a48-8ebc-d66fd6dd4560, source=ArtifactsTest.SetUp()
10:48:11  exception=[Node artifacts-centos8-jenkins-db-node-9cd864f1-1 [34.253.104.181 | 10.4.2.124]] NodeSetupFailed: Encountered a bad command exit code!
10:48:11  Command: 'sudo yum install -y python3'
10:48:11  Exit code: 1
10:48:11  Stdout:
10:48:11  CentOS Stream 8 - AppStream                     979  B/s |  38  B     00:00
10:48:11  Stderr:
10:48:11  Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
10:48:11  Traceback (most recent call last):
10:48:11  File "/tmp/jenkins/workspace/scylla-master/artifacts/artifacts-centos8-arm-test/scylla-cluster-tests/sdcm/cluster.py", line 3775, in node_setup
10:48:11  cl_inst.node_setup(_node, **setup_kwargs)
10:48:11  File "/tmp/jenkins/workspace/scylla-master/artifacts/artifacts-centos8-arm-test/scylla-cluster-tests/sdcm/cluster.py", line 4524, in node_setup
10:48:11  node.install_package('python3')
10:48:11  File "/tmp/jenkins/workspace/scylla-master/artifacts/artifacts-centos8-arm-test/scylla-cluster-tests/sdcm/utils/decorators.py", line 70, in inner
10:48:11  return func(*args, **kwargs)
10:48:11  File "/tmp/jenkins/workspace/scylla-master/artifacts/artifacts-centos8-arm-test/scylla-cluster-tests/sdcm/cluster.py", line 1793, in install_package
10:48:11  self.remoter.sudo(f'{pkg_cmd} install -y {package_name}', ignore_status=ignore_status)
10:48:11  File "/tmp/jenkins/workspace/scylla-master/artifacts/artifacts-centos8-arm-test/scylla-cluster-tests/sdcm/remote/base.py", line 123, in sudo
10:48:11  return self.run(cmd=cmd,
10:48:11  File "/tmp/jenkins/workspace/scylla-master/artifacts/artifacts-centos8-arm-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 614, in run
10:48:11  result = _run()
10:48:11  File "/tmp/jenkins/workspace/scylla-master/artifacts/artifacts-centos8-arm-test/scylla-cluster-tests/sdcm/utils/decorators.py", line 70, in inner
10:48:11  return func(*args, **kwargs)
10:48:11  File "/tmp/jenkins/workspace/scylla-master/artifacts/artifacts-centos8-arm-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 605, in _run
10:48:11  return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
10:48:11  File "/tmp/jenkins/workspace/scylla-master/artifacts/artifacts-centos8-arm-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 538, in _run_execute
10:48:11  result = connection.run(**command_kwargs)
10:48:11  File "/tmp/jenkins/workspace/scylla-master/artifacts/artifacts-centos8-arm-test/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
10:48:11  return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
10:48:11  File "/tmp/jenkins/workspace/scylla-master/artifacts/artifacts-centos8-arm-test/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 655, in _complete_run
10:48:11  raise UnexpectedExit(result)
10:48:11  sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!
10:48:11  Command: 'sudo yum install -y python3'
10:48:11  Exit code: 1
10:48:11  Stdout:
10:48:11  CentOS Stream 8 - AppStream                     979  B/s |  38  B     00:00
10:48:11  Stderr:
10:48:11  Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
```

link to one of the failed jobs:
https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-centos8-arm-test/597/

**Comment by fruch** [comment]
Centos 8 Stream is EOL - (31 May 2024)

the packages in the URLs in those images doesn't exists anymore...

we need to drop it
