### ISSUE TITLE
Hydra investigate show-monitor doesn't work due missing eq operator 

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-cluster-tests#7588]
Recently I tried show monitor and this is what I got:
```
hydra investigate show-monitor b9dba6e5-794a-4ba3-8231-f53620573634                                    
Traceback (most recent call last):
  File "/home/ls/repos/scylla-cluster-tests/sdcm/utils/get_username.py", line 15, in <module>
    import getpass
  File "/home/ls/.pyenv/versions/3.11.1/lib/python3.11/getpass.py", line 17, in <module>
    import contextlib
  File "/home/ls/.pyenv/versions/3.11.1/lib/python3.11/contextlib.py", line 6, in <module>
    from collections import deque
  File "/home/ls/.pyenv/versions/3.11.1/lib/python3.11/collections/__init__.py", line 36, in <module>
    from operator import eq as _eq
ImportError: cannot import name 'eq' from 'operator' (/home/ls/repos/scylla-cluster-tests/sdcm/utils/operator/__init__.py)

```

**Comment by soyacz** [comment]
seems something with my env. Closing.
