### ISSUE TITLE
make sure async reboot completes in hard_reboot nemesis

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla-cluster-tests#759]
PROBLEM 1 in short longevity 3.0.1: 3.0.1-0.20190120.3c4f8cf6e

SCT nemesis issue: Problem in hard_reboot nemesis:
after aws called hard reboot, returned but instance is still running.  we can't treat instance had been shutdown after self.target_node.reboot(hard=True) returned.

We had patch in sct master to verify network after reboot, it can't solve the problem 100%
I will backport this patch （https://github.com/scylladb/scylla-cluster-tests/commit/28f774746771e45c0f0ea5a921bd8d760af05b8a）  to SCT branch-3.0 first.

Better additional solution:
- option 1: check uptime before and after reboot to make sure the system really rebooted
- option 2: check scylla-server log with journactl --since '$reboot_time' |grep 'Scylla version' to make sure the system really rebooted

```
2019-01-20 16:42:20,399 nemesis          L0442 INFO | sdcm.nemesis.ChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method hard_reboot_node

2019-01-20 16:42:20,400 nemesis          L0212 DEBUG| sdcm.nemesis.ChaosMonkey: Set current_disruption -> HardRebootNode Node longevity-10gb-3h-3.0-db-node-fb9823b6-6 [34.203.40.100 | 172.30.0.103] (seed: False)

2019-01-20 16:42:20,400 nemesis          L0214 INFO | sdcm.nemesis.ChaosMonkey: HardRebootNode Node longevity-10gb-3h-3.0-db-node-fb9823b6-6 [34.203.40.100 | 172.30.0.103] (seed: False)

2019-01-20 16:42:20,400 cluster_aws      L0359 DEBUG| Node longevity-10gb-3h-3.0-db-node-fb9823b6-6 [34.203.40.100 | 172.30.0.103] (seed: None): Hardly rebooting node

2019-01-20 16:42:20,403 retry            L0200 DEBUG| Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0, status=None)

2019-01-20 16:42:20,403 connectionpool   L0243 DEBUG| Resetting dropped connection: ec2.us-east-1.amazonaws.com

2019-01-20 16:42:20,614 connectionpool   L0396 DEBUG| https://ec2.us-east-1.amazonaws.com:443 "POST / HTTP/1.1" 200 231

2019-01-20 16:42:20,615 nemesis          L0178 INFO | sdcm.nemesis.ChaosMonkey: Waiting scylla services to start after node reboot

2019-01-20 16:42:20,617 retry            L0200 DEBUG| Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0, status=None)

2019-01-20 16:42:20,714 connectionpool   L0396 DEBUG| https://ec2.us-east-1.amazonaws.com:443 "POST / HTTP/1.1" 200 7284

2019-01-20 16:42:20,717 wait             L0026 DEBUG| Node longevity-10gb-3h-3.0-db-node-fb9823b6-6 [34.203.40.100 | 172.30.0.103] (seed: False): Waiting for DB services to be up (0.000004 secs)

2019-01-20 16:42:20,864 remote           L0194 DEBUG| [34.203.40.100] [stdout] Jan 20 16:42:20 info   | Stopping Scylla JMX...

2019-01-20 16:42:20,932 remote           L0194 DEBUG| [34.203.40.100] [stderr] Connection to 34.203.40.100 closed by remote host.

2019-01-20 16:42:20,951 remote           L0707 ERROR| Remote [centos@34.203.40.100]: Error while executing SSH command: Command: /bin/ssh  -a -x   -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpDp1

QFR -o BatchMode=yes -o ConnectTimeout=30 -o ServerAliveInterval=300 -l centos -p 22 -i /var/tmp/longevity-10gb-3h-3.0-sct-f490d2b4.pem 34.203.40.100 "true"

Exit status: 255

Duration: 0.00652384757996

Stdout:



Stderr:

ssh: connect to host 34.203.40.100 port 22: Connection refused
```

**Comment by amoskong** [comment]
@roydahan It's a short longevity, we can easily run it again to know if this problem still exists. 
If not we can add more strict check (mentioned in comment 0).

**Comment by roydahan** [comment]
ok

**Comment by amoskong** [comment]
This problem still existed 3.1 longevity-50GB (test job: http://jenkins.scylladb.com/job/scylla-3.1/job/longevity/job/longevity-50gb-4days/4/)

ssh verify was PASS before reboot. So we need a way to make sure the reboot completes.
- sleep might solve the problem, but it's not good
- compare the `uptime -s`, I will send a PR


```
2019-06-26 13:25:26,035 nemesis          L0543 INFO | sdcm.nemesis.ChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method multiple_hard_reboot_node
2019-06-26 13:25:26,036 nemesis          L0296 DEBUG| sdcm.nemesis.ChaosMonkey: Set current_disruption -> MultipleHardRebootNode Node longevity-tls-50gb-4d-3-1-db-node-dd5f218f-5 [54.154.40.1
06 | 10.0.242.237] (seed: False)
2019-06-26 13:25:26,036 nemesis          L0298 INFO | sdcm.nemesis.ChaosMonkey: MultipleHardRebootNode Node longevity-tls-50gb-4d-3-1-db-node-dd5f218f-5 [54.154.40.106 | 10.0.242.237] (seed: 
False)
2019-06-26 13:25:26,047 sct_events       L0387 INFO | 2019-06-26 13:25:26.036: (DisruptionEvent Severity.NORMAL): type=start name=MultipleHardRebootNode node=Node longevity-tls-50gb-4d-3-1-db
-node-dd5f218f-5 [54.154.40.106 | 10.0.242.237] (seed: False) duration=None
2019-06-26 13:25:26,049 nemesis          L0230 DEBUG| sdcm.nemesis.ChaosMonkey: Rebooting 1 out of 5 times
2019-06-26 13:25:26,049 cluster_aws      L0447 DEBUG| Node longevity-tls-50gb-4d-3-1-db-node-dd5f218f-5 [54.154.40.106 | 10.0.242.237] (seed: False): Hardly rebooting node
2019-06-26 13:25:26,055 connectionpool   L0208 DEBUG| Starting new HTTP connection (1): 63.32.61.162
2019-06-26 13:25:26,064 connectionpool   L0396 DEBUG| http://63.32.61.162:3000 "POST /api/annotations HTTP/1.1" 200 40
2019-06-26 13:25:26,066 sct_events       L0444 INFO | {"id":1068,"message":"Annotation added"}
2019-06-26 13:25:26,303 wait             L0026 DEBUG| Node longevity-tls-50gb-4d-3-1-db-node-dd5f218f-5 [54.154.40.106 | 10.0.242.237] (seed: False): Waiting for SSH to be up (0.000009 secs)
2019-06-26 13:25:26,376 nemesis          L0233 INFO | sdcm.nemesis.ChaosMonkey: Waiting scylla services to start after node reboot
2019-06-26 13:25:26,377 wait             L0026 DEBUG| Node longevity-tls-50gb-4d-3-1-db-node-dd5f218f-5 [54.154.40.106 | 10.0.242.237] (seed: False): Waiting for DB services to be up (0.00001
1 secs)
2019-06-26 13:25:26,589 nemesis          L0549 ERROR| sdcm.nemesis.ChaosMonkey: Exception in random_disrupt_method multiple_hard_reboot_node: 
2019-06-26 13:25:26,590 nemesis          L0953 ERROR| sdcm.nemesis.ChaosMonkey: Unhandled exception in method <function disrupt at 0x7fbc5e6a1d70>
Traceback (most recent call last):
  File "/sct/sdcm/nemesis.py", line 949, in wrapper
    result = method(*args, **kwargs)
  File "/sct/sdcm/nemesis.py", line 1161, in disrupt
    self.call_random_disrupt_method()
  File "/sct/sdcm/nemesis.py", line 547, in call_random_disrupt_method
    disrupt_method()
  File "/sct/sdcm/nemesis.py", line 234, in disrupt_multiple_hard_reboot_node
    self.target_node.wait_db_up()
  File "/sct/sdcm/cluster.py", line 1052, in wait_db_up
    self._report_housekeeping_uuid()
  File "/sct/sdcm/cluster.py", line 1040, in _report_housekeeping_uuid
    ignore_status=True, verbose=verbose)
  File "/sct/sdcm/remote.py", line 247, in run
    watchers=watchers, cmd_timeout=timeout)
  File "/sct/sdcm/remote.py", line 64, in run
    return super(ConnectionCmdTimeout, self).run(command, **kwargs)
  File "<decorator-gen-3>", line 2, in run
  File "/usr/lib/python2.7/site-packages/fabric/connection.py", line 30, in opens
    return method(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/fabric/connection.py", line 702, in run
    return self._run(self._remote_runner(), command, **kwargs)
  File "/usr/lib/python2.7/site-packages/invoke/context.py", line 101, in _run
    return runner.run(command, **kwargs)
  File "/usr/lib/python2.7/site-packages/invoke/runners.py", line 271, in run
    return self._run_body(command, **kwargs)
  File "/usr/lib/python2.7/site-packages/invoke/runners.py", line 285, in _run_body
    self.start(command, shell, env)
```
