### ISSUE TITLE
nodetool decommission nemesis fails with tablets for: "Unable to find new replica for tablet"

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#7620]
## Packages

Scylla version: `6.1.0~dev-20240608.f4706be8a8c4` with build-id `0ec6514e055a70c10c38dd4e048e3b520e1f1321`

Kernel Version: `5.15.0-1062-gcp`

## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

*Describe your issue in detail and steps it took to produce it.*

scenario:
run nemesis of disrupt_load_and_stream that calls `self._prepare_test_table(ks='keyspace1', table='standard1')`, generating a ks with rf=5 (nodes-num)
then disrupt_nodetool_decommission fails to decommission a node with:
```
Nemesis Information
Class: Sisyphus
Name: disrupt_nodetool_decommission
Status: Failed
Failure reason
Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 5116, in wrapper
    result = method(*args[1:], **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1296, in disrupt_nodetool_decommission
    return self._nodetool_decommission(add_node=add_node)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1273, in _nodetool_decommission
    self.cluster.decommission(self.target_node)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 4896, in decommission
    node.run_nodetool("decommission", timeout=timeout, retry=0)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2593, in run_nodetool
    self.remoter.run(cmd, timeout=timeout, ignore_status=ignore_status, verbose=verbose, retry=retry)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 614, in run
    result = _run()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 65, in inner
    return func(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 605, in _run
    return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 538, in _run_execute
    result = connection.run(**command_kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
    return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 655, in _complete_run
    raise UnexpectedExit(result)
sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!

Command: '/usr/bin/nodetool  decommission '

Exit code: 4

Stdout:



Stderr:

error executing POST request to http://localhost:10000/storage_service/decommission with parameters {}: remote replied with status code 500 Internal Server Error:
std::runtime_error (Decommission failed. See earlier errors (Rolled back: Failed to drain tablets: std::runtime_error (Unable to find new replica for tablet 12cfdbb0-2661-11ef-a073-5136f9848e08:7 on 2d841d1f-c0bd-463b-99bb-51700bd42633:7 when draining {2d841d1f-c0bd-463b-99bb-51700bd42633})))

```
possible solution is modifying _prepare_test_table reliable_replication_factor to return number-of-nodes - 1
## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Cluster size: 5 nodes (n2-highmem-16)

Scylla Nodes used in this run:
- longevity-large-partitions-200k-pks-db-node-40b26312-0-6 (34.73.178.35 | 10.142.0.22) (shards: 14)
- longevity-large-partitions-200k-pks-db-node-40b26312-0-5 (35.227.62.230 | 10.142.0.57) (shards: 14)
- longevity-large-partitions-200k-pks-db-node-40b26312-0-4 (34.73.80.129 | 10.142.0.56) (shards: 14)
- longevity-large-partitions-200k-pks-db-node-40b26312-0-3 (34.139.170.178 | 10.142.0.55) (shards: 14)
- longevity-large-partitions-200k-pks-db-node-40b26312-0-2 (35.237.239.18 | 10.142.0.54) (shards: 14)
- longevity-large-partitions-200k-pks-db-node-40b26312-0-1 (34.73.227.49 | 10.142.0.27) (shards: 14)

OS / Image: `https://www.googleapis.com/compute/v1/projects/scylla-images/global/images/scylla-6-1-0-dev-x86-64-2024-06-09t01-55-06` (gce: undefined_region)

Test: `longevity-large-partition-200k-pks-4days-gce-test`
Test id: `40b26312-64fb-4656-9be1-f796a829c547`
Test name: `scylla-staging/yarongilor/longevity-large-partition-200k-pks-4days-gce-test`
Test config file(s):

- [longevity-large-partition-200k_pks-4days.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/6d50a25f498b86d76cd5a9aa4ca6ee6aa874541b/test-cases/longevity/longevity-large-partition-200k_pks-4days.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 40b26312-64fb-4656-9be1-f796a829c547`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=40b26312-64fb-4656-9be1-f796a829c547)
- Show all stored logs command: `$ hydra investigate show-logs 40b26312-64fb-4656-9be1-f796a829c547`

## Logs:
*No logs captured during this run.*

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/yarongilor/job/longevity-large-partition-200k-pks-4days-gce-test/2/)
[Argus](https://argus.scylladb.com/test/3d7ecc1b-e7c3-4fb8-9178-0f397b3d9c7c/runs?additionalRuns[]=40b26312-64fb-4656-9be1-f796a829c547)
</details>

**Comment by jsmolar** [comment]
Hi @yarongilor . I found very similar issue in this run: https://argus.scylladb.com/tests/scylla-cluster-tests/775d283e-b7e8-49b8-96ff-da9050f2817c

It happened during `AddRemoveDc` nemesis, but it seems it is related to this issue. Could you please have a look?
