### ISSUE TITLE
Private ip address is used to check the manager agent status when test run locally

### ISSUE THREAD

**Issue by mikliapko** [scylladb/scylla-cluster-tests#7636]
### Issue description

- [x] This issue is a regression.

The changes in [commit](https://github.com/scylladb/scylla-cluster-tests/commit/aea611d6142a6fb80cca4d7663a419407879ae90) breaks the opportunity to run tests from local developer PC.

The setup fails on `wait_manager_agent_up` function as tries to access nodes via private ip address:
```
Traceback (most recent call last):
  File "/home/mikita/scylla/repos/scylla-cluster-tests/sdcm/cluster.py", line 3804, in node_startup
    cl_inst.node_startup(_node, **setup_kwargs)
  File "/home/mikita/scylla/repos/scylla-cluster-tests/sdcm/cluster.py", line 4648, in node_startup
    node.wait_manager_agent_up()
  File "/home/mikita/scylla/repos/scylla-cluster-tests/sdcm/cluster.py", line 1364, in wait_manager_agent_up
    wait.wait_for(func=self.is_manager_agent_up, step=10, text=text, timeout=timeout, throw_exc=True)
  File "/home/mikita/scylla/repos/scylla-cluster-tests/sdcm/wait.py", line 70, in wait_for
    res = retry(func, **kwargs)
  File "/home/mikita/scylla/repos/scylla-cluster-tests/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "/home/mikita/scylla/repos/scylla-cluster-tests/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 360, in iter
    raise retry_exc.reraise()
  File "/home/mikita/scylla/repos/scylla-cluster-tests/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 193, in reraise
    raise self.last_attempt.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/mikita/scylla/repos/scylla-cluster-tests/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "/home/mikita/scylla/repos/scylla-cluster-tests/sdcm/cluster.py", line 1357, in is_manager_agent_up
    response = requests.get(f"https://{normalize_ipv6_url(self.ip_address)}:{port}/ping", verify=False)
  File "/home/mikita/scylla/repos/scylla-cluster-tests/.venv/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/mikita/scylla/repos/scylla-cluster-tests/.venv/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/mikita/scylla/repos/scylla-cluster-tests/.venv/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/mikita/scylla/repos/scylla-cluster-tests/.venv/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/mikita/scylla/repos/scylla-cluster-tests/.venv/lib/python3.10/site-packages/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='10.12.0.119', port=10001): Max retries exceeded with url: /ping (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7d06099fb7f0>, 'Connection to 10.12.0.119 timed out. (connect timeout=None)'))
```

The issue goes away when the commit is reverted.

### Impact

No way to run tests from local dev PC.

### How frequently does it reproduce?

Every time.

### Installation details

SCT Version: eefe1b15def703c830f96153c50587955cfeace2

**Comment by juliayakovlev** [comment]
https://github.com/scylladb/scylla-cluster-tests/pull/7735
