### ISSUE TITLE
Test can't parse the replication strategy

### ISSUE THREAD

**Issue by xtrey** [scylladb/scylla-cluster-tests#7740]
### Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

#### Steps to Reproduce
Looks like the SCT not handling correctly extraction of the replication strategy.
```
< t:2024-06-08 08:26:19,958 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2024-06-08 08:26:19.954: (NodetoolEvent Severity.NORMAL) period_type=end event_id=6deb46d3-8da2-46e6-a78b-d6e8dd2c5ee5 duration=0s: nodetool_command=info node=longevity-parallel-topology-schema--db-node-56ff9e60-1
< t:2024-06-08 08:26:20,566 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.10.138>: 
< t:2024-06-08 08:26:20,567 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.10.138>: CREATE KEYSPACE keyspace1 WITH replication = {'class': 'org.apache.cassandra.locator.NetworkTopologyStrategy', 'eu-west': '3'} AND durable_writes = true;
< t:2024-06-08 08:26:20,567 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.10.138>: 
< t:2024-06-08 08:26:20,567 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.10.138>: CREATE TABLE keyspace1.standard1 (
< t:2024-06-08 08:26:20,567 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.10.138>:     key blob,
< t:2024-06-08 08:26:20,567 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.10.138>:     "C0" blob,
< t:2024-06-08 08:26:20,567 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.10.138>:     "C1" blob,
< t:2024-06-08 08:26:20,567 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.10.138>:     "C2" blob,
< t:2024-06-08 08:26:20,567 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.10.138>:     "C3" blob,
< t:2024-06-08 08:26:20,567 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.10.138>:     "C4" blob,
< t:2024-06-08 08:26:20,567 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.10.138>:     "C5" blob,
< t:2024-06-08 08:26:20,567 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.10.138>:     "C6" blob,
< t:2024-06-08 08:26:20,567 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.10.138>:     "C7" blob,
< t:2024-06-08 08:26:20,567 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.10.138>:     "C8" blob,
< t:2024-06-08 08:26:20,567 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.10.138>:     "C9" blob,
< t:2024-06-08 08:26:20,567 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.10.138>:     PRIMARY KEY (key)
< t:2024-06-08 08:26:20,567 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.10.138>: ) WITH bloom_filter_fp_chance = 0.01
< t:2024-06-08 08:26:20,567 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.10.138>:     AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
< t:2024-06-08 08:26:20,567 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.10.138>:     AND comment = ''
< t:2024-06-08 08:26:20,567 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.10.138>:     AND compaction = {'class': 'LeveledCompactionStrategy', 'sstable_size_in_mb': '160'}
< t:2024-06-08 08:26:20,567 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.10.138>:     AND compression = {}
< t:2024-06-08 08:26:20,567 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.10.138>:     AND crc_check_chance = 1
< t:2024-06-08 08:26:20,567 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.10.138>:     AND default_time_to_live = 1872622
< t:2024-06-08 08:26:20,567 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.10.138>:     AND gc_grace_seconds = 864000
< t:2024-06-08 08:26:20,567 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.10.138>:     AND max_index_interval = 2048
< t:2024-06-08 08:26:20,567 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.10.138>:     AND memtable_flush_period_in_ms = 0
< t:2024-06-08 08:26:20,567 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.10.138>:     AND min_index_interval = 128
< t:2024-06-08 08:26:20,567 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.10.138>:     AND speculative_retry = '99.0PERCENTILE'
< t:2024-06-08 08:26:20,567 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.10.138>:     AND paxos_grace_seconds = 864000
< t:2024-06-08 08:26:20,567 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.10.138>:     AND tombstone_gc = {'mode': 'repair', 'propagation_delay_in_seconds': '3600'};
< t:2024-06-08 08:26:20,567 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.10.138>: 
< t:2024-06-08 08:26:20,567 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.10.138>: 
< t:2024-06-08 08:26:20,567 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.10.138>: CREATE INDEX standard1_c3_nemesis ON keyspace1.standard1("C3");
< t:2024-06-08 08:26:20,567 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.10.138>: 
< t:2024-06-08 08:26:20,756 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.9.127>: 5h1m40s    1000   25500      0 4.1ms  4.1ms  2.8ms  2.5ms  2.4ms  2ms    2ms    
< t:2024-06-08 08:26:20,767 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.8.249>: 5h1m50s    1000   50000      0 5.7ms  5.5ms  5.1ms  4.5ms  3.9ms  2.4ms  2.6ms  
< t:2024-06-08 08:26:21,068 f:base.py         l:143  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.10.138>: Command "/usr/bin/cqlsh --no-color   --request-timeout=120 --connect-timeout=60  -e "describe keyspace1" 10.4.10.138" finished with status 0
< t:2024-06-08 08:26:21,068 f:nemesis.py      l:5140 c:sdcm.nemesis         p:ERROR > sdcm.nemesis.SisyphusMonkey: Unhandled exception in method <bound method Nemesis.disrupt_add_remove_dc of <sdcm.nemesis.SisyphusMonkey object at 0x7fd67a0ab670>> < t:2024-06-08 08:26:21,068 f:nemesis.py      l:5140 c:sdcm.nemesis         p:ERROR > sdcm.nemesis.SisyphusMonkey: Unhandled exception in method <bound method Nemesis.disrupt_add_remove_dc of <sdcm.nemesis.SisyphusMonkey object at 0x7fd67a0ab670>>
< t:2024-06-08 08:26:21,068 f:nemesis.py      l:5140 c:sdcm.nemesis         p:ERROR > Traceback (most recent call last):
< t:2024-06-08 08:26:21,068 f:nemesis.py      l:5140 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 5116, in wrapper
< t:2024-06-08 08:26:21,068 f:nemesis.py      l:5140 c:sdcm.nemesis         p:ERROR >     result = method(*args[1:], **kwargs)
< t:2024-06-08 08:26:21,068 f:nemesis.py      l:5140 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4513, in disrupt_add_remove_dc
< t:2024-06-08 08:26:21,068 f:nemesis.py      l:5140 c:sdcm.nemesis         p:ERROR >     self._switch_to_network_replication_strategy(self.cluster.get_test_keyspaces() + system_keyspaces)
< t:2024-06-08 08:26:21,068 f:nemesis.py      l:5140 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4492, in _switch_to_network_replication_strategy
< t:2024-06-08 08:26:21,068 f:nemesis.py      l:5140 c:sdcm.nemesis         p:ERROR >     replication_strategy = ReplicationStrategy.get(node, keyspace)
< t:2024-06-08 08:26:21,068 f:nemesis.py      l:5140 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/replication_strategy_utils.py", line 26, in get
< t:2024-06-08 08:26:21,068 f:nemesis.py      l:5140 c:sdcm.nemesis         p:ERROR >     return ReplicationStrategy.from_string(create_ks_statement)
< t:2024-06-08 08:26:21,068 f:nemesis.py      l:5140 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/replication_strategy_utils.py", line 21, in from_string
< t:2024-06-08 08:26:21,068 f:nemesis.py      l:5140 c:sdcm.nemesis         p:ERROR >     raise ValueError(f"Couldn't find such replication strategy: {replication_value}")
< t:2024-06-08 08:26:21,068 f:nemesis.py      l:5140 c:sdcm.nemesis         p:ERROR > ValueError: Couldn't find such replication strategy: <re.Match object; span=(0, 126), match="CREATE KEYSPACE keyspace1 WITH replication = {'cl>
```

**Expected behavior:** Able to extract strategy or fail with meaningful error 

**Actual behavior:** Fails without clear reason what happened

### Installation details

SCT Version: master
Scylla version (or git commit hash): scylla-6.1.0-dev-x86_64-2024-06-08T02-07-36(ami-0cdf073ec8f09003f)

### Logs
* test_id: 56ff9e60-582f-4b23-a511-2677a13326e0
* job log: https://cloudius-jenkins-test.s3.amazonaws.com/56ff9e60-582f-4b23-a511-2677a13326e0/20240609_034655/sct-56ff9e60.log.tar.gz

**Comment by xtrey** [comment]
Obsolete

**Comment by soyacz** [comment]
what happened? can be closed?

**Comment by soyacz** [comment]
ah, I remember, already fixed recently.

**Comment by xtrey** [comment]
Had an old version of repo locally. After update noticed that it's actually fixed, and the test was executed before fix.
