### ISSUE TITLE
(publickey,gssapi-keyex,gssapi-with-mic). fatal: Could not read from remote repository.) 

### ISSUE THREAD

**Issue by bismaya123** [scylladb/scylla-cluster-tests#780]
Hello I'm getting below error(Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
fatal: Could not read from remote repository.) in jenkin build log though i have added the ssh public key to git server.
can anyone please help me on this.

Fetching changes from the remote Git repository

C:\Program Files\Git\bin\git config remote.origin.url git@git.sami.int.thomsonreuters.com:TRDA-Development/database.git # timeout=10
Fetching upstream changes from git@git.sami.int.thomsonreuters.com:TRDA-Development/database.git
C:\Program Files\Git\bin\git --version # timeout=10
C:\Program Files\Git\bin\git fetch --tags --progress git@git.sami.int.thomsonreuters.com:TRDA-Development/database.git +refs/heads/:refs/remotes/origin/
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from git@git.sami.int.thomsonreuters.com:TRDA-Development/database.git
at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:888)
at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1155)
at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1186)
at org.jenkinsci.plugins.multiplescms.MultiSCM.checkout(MultiSCM.java:129)
at hudson.scm.SCM.checkout(SCM.java:485)
at hudson.model.AbstractProject.checkout(AbstractProject.java:1269)
at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:607)
at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
at hudson.model.Run.execute(Run.java:1738)
at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
at hudson.model.ResourceController.execute(ResourceController.java:98)
at hudson.model.Executor.run(Executor.java:410)
Caused by: hudson.plugins.git.GitException: Command "C:\Program Files\Git\bin\git fetch --tags --progress git@git.sami.int.thomsonreuters.com:TRDA-Development/database.git +refs/heads/:refs/remotes/origin/" returned status code 128:
stdout:
stderr: ***************************************************************************

This computer system is the property of Thomson Reuters and may be *
accessed only by authorized users. Unauthorized use of this system is *
strictly prohibited and may be subject to criminal prosecution. Your *
use of Thomson Reuters systems and networks is permitted only in *
accordance with Thomson Reuters policies, including the Code of *
Business Conduct and Ethics. Where permitted by applicable law, we *
reserve the right to monitor your use of these systems and networks and *
review any communications made through them. By accessing the Thomson *
Reuters system, you consent to such monitoring and to the retrieval of *
information required for law enforcement or for the purpose of *
protecting Thomson Reuters intellectual property and the *
confidentiality of our corporate, client, and personnel data. *
                                                                    *
For support on SAMI Git please visit: *
  https://thehub.thomsonreuters.com/groups/sami                   *
Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Can anyone please help me on this. Thanks in Advance.

**Comment by bentsi** [comment]
This is not a support forum for Jenkins. As suggested before, please sites as:

- stackoverflow.com

- https://jenkins.io/chat/
