### ISSUE TITLE
If BYO step fails, the pipeline should fail right away.

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla-cluster-tests#7884]
Seems like failures of the BYO step, are not failing the whole pipeline, and we end up starting the test
and failing like the following:
```
assert all(self.get(o) for o in options_must_exist), \
14:54:40  < t:2024-07-08 11:54:40,199 f:log.py          l:23   c:sdcm.utils.log       p:ERROR > AssertionError: scylla version/repos wasn't configured correctly
14:54:40  < t:2024-07-08 11:54:40,199 f:log.py          l:23   c:sdcm.utils.log       p:ERROR > configure those options: ['ami_id_db_scylla']
14:54:40  < t:2024-07-08 11:54:40,199 f:log.py          l:23   c:sdcm.utils.log       p:ERROR > and those environment variables: ['SCT_AMI_ID_DB_SCYLLA']
```

Seen in: https://jenkins.scylladb.com/job/enterprise-2024.1/job/reproducers/job/longevity-lwt-multi-dc-Tesla/4/

**Comment by vponomaryov** [comment]
The bug topic must be `If BYO step fails fail the pipeline right away`.

The error you got is caused by the fact of the BYO failure:

```
14:51:43  Also:   org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: 662af161-7966-456c-b915-84eac0c1054d
14:51:43  groovy.lang.MissingPropertyException: No such property: jobResults for class: byoScylladb
14:51:43  	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:66)
14:51:43  	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.getProperty(ScriptBytecodeAdapter.java:471)
14:51:43  	at PluginClassLoader for script-security//org.kohsuke.groovy.sandbox.impl.Checker$7.call(Checker.java:377)
14:51:43  	at PluginClassLoader for script-security//org.kohsuke.groovy.sandbox.GroovyInterceptor.onGetProperty(GroovyInterceptor.java:68)
14:51:43  	at PluginClassLoader for script-security//org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onGetProperty(SandboxInterceptor.java:347)
14:51:43  	at PluginClassLoader for script-security//org.kohsuke.groovy.sandbox.impl.Checker$7.call(Checker.java:375)
14:51:43  	at PluginClassLoader for script-security//org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:379)
14:51:43  	at PluginClassLoader for workflow-cps//com.cloudbees.groovy.cps.sandbox.SandboxInvoker.getProperty(SandboxInvoker.java:29)
14:51:43  	at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.LoggingInvoker.getProperty(LoggingInvoker.java:121)
14:51:43  	at PluginClassLoader for workflow-cps//com.cloudbees.groovy.cps.impl.PropertyAccessBlock.rawGet(PropertyAccessBlock.java:20)
14:51:43  	at byoScylladb.call(byoScylladb.groovy:87)
14:51:43  	at longevityPipeline.call(longevityPipeline.groovy:237)
14:51:43  	at ___cps.transform___(Native Method)
14:51:43  	at PluginClassLoader for workflow-cps//com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.get(PropertyishBlock.java:73)
14:51:43  	at PluginClassLoader for workflow-cps//com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)
14:51:43  	at PluginClassLoader for workflow-cps//com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.fixName(PropertyishBlock.java:65)
14:51:43  	at jdk.internal.reflect.GeneratedMethodAccessor457.invoke(Unknown Source)
14:51:43  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
14:51:43  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
14:51:43  	at PluginClassLoader for workflow-cps//com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
14:51:43  	at PluginClassLoader for workflow-cps//com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
14:51:43  	at PluginClassLoader for workflow-cps//com.cloudbees.groovy.cps.Next.step(Next.java:83)
14:51:43  	at PluginClassLoader for workflow-cps//com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:147)
14:51:43  	at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:17)
14:51:43  	at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:49)
14:51:43  	at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:180)
14:51:43  	at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:423)
14:51:43  	at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:331)
14:51:43  	at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:295)
14:51:43  	at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService.lambda$wrap$4(CpsVmExecutorService.java:136)
14:51:43  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
14:51:43  	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)
14:51:43  	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
14:51:43  	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
14:51:43  	at jenkins.util.ErrorLoggingExecutorService.lambda$wrap$0(ErrorLoggingExecutorService.java:51)
14:51:43  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
14:51:43  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
14:51:43  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
14:51:43  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
14:51:43  	at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$1.call(CpsVmExecutorService.java:53)
14:51:43  	at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$1.call(CpsVmExecutorService.java:50)
14:51:43  	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:136)
14:51:43  	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:275)
14:51:43  	at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService.lambda$categoryThreadFactory$0(CpsVmExecutorService.java:50)
14:51:43  	at java.base/java.lang.Thread.run(Thread.java:829)
14:51:43  Setting overall build result to FAILURE
```
