### ISSUE TITLE
(master) artifacts-offline-install/job/artifacts-oel81-test is failing with Error: No module named 'cassandra'

### ISSUE THREAD

**Issue by yaronkaikov** [scylladb/scylla-cluster-tests#7995]
This job has been failing since https://jenkins.scylladb.com/job/scylla-master/job/artifacts-offline-install/job/artifacts-oel81-test/420/

```
15:00:12  ----- LAST ERROR EVENT -------------------------------------------------------
15:00:12  2024-06-23 12:00:01.322: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=88d0a955-ab5d-44b4-a41a-2b2e3df332f1, source=ArtifactsTest.test_scylla_service (artifacts_test.ArtifactsTest) [check cqlsh installation]() message=Traceback (most recent call last):
15:00:12  File "/tmp/jenkins/workspace/scylla-master/artifacts-offline-install/artifacts-oel81-test/scylla-cluster-tests/artifacts_test.py", line 352, in test_scylla_service
15:00:12  self.check_cqlsh()
15:00:12  File "/tmp/jenkins/workspace/scylla-master/artifacts-offline-install/artifacts-oel81-test/scylla-cluster-tests/artifacts_test.py", line 142, in check_cqlsh
15:00:12  output = self.node.run_cqlsh("desc keyspaces")
15:00:12  File "/tmp/jenkins/workspace/scylla-master/artifacts-offline-install/artifacts-oel81-test/scylla-cluster-tests/sdcm/cluster.py", line 2841, in run_cqlsh
15:00:12  cqlsh_out = self.remoter.run(cmd, timeout=timeout + 120,  # we give 30 seconds to cqlsh timeout mechanism to work
15:00:12  File "/tmp/jenkins/workspace/scylla-master/artifacts-offline-install/artifacts-oel81-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 614, in run
15:00:12  result = _run()
15:00:12  File "/tmp/jenkins/workspace/scylla-master/artifacts-offline-install/artifacts-oel81-test/scylla-cluster-tests/sdcm/utils/decorators.py", line 70, in inner
15:00:12  return func(*args, **kwargs)
15:00:12  File "/tmp/jenkins/workspace/scylla-master/artifacts-offline-install/artifacts-oel81-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 605, in _run
15:00:12  return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
15:00:12  File "/tmp/jenkins/workspace/scylla-master/artifacts-offline-install/artifacts-oel81-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 538, in _run_execute
15:00:12  result = connection.run(**command_kwargs)
15:00:12  File "/tmp/jenkins/workspace/scylla-master/artifacts-offline-install/artifacts-oel81-test/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
15:00:12  return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
15:00:12  File "/tmp/jenkins/workspace/scylla-master/artifacts-offline-install/artifacts-oel81-test/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 655, in _complete_run
15:00:12  raise UnexpectedExit(result)
15:00:12  sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!
15:00:12  Command: '/usr/bin/cqlsh --no-color   --request-timeout=120 --connect-timeout=60  -e "desc keyspaces" 10.4.7.210'
15:00:12  Exit code: 1
15:00:12  Stdout:
15:00:12  Stderr:
15:00:12  /etc/bashrc: line 100: TMOUT: readonly variable
15:00:12  Python Cassandra driver not installed, or not on PYTHONPATH.
15:00:12  You might try "pip install cassandra-driver".
15:00:12  Python: /opt/scylladb/share/cassandra/bin/../../../python3/bin/python3
15:00:12  Module load path: ['/opt/scylladb/share/cassandra/libexec/../lib/PyYAML-6.0.1.zip', '/opt/scylladb/share/cassandra/libexec/../lib/six-1.16.0.zip', '/opt/scylladb/share/cassandra/libexec', '/opt/scylladb/share/cassandra/bin', '/opt/scylladb/share/cassandra/libexec', '/home/ec2-user', '/usr/lib64/python36.zip', '/usr/lib64/python3.6', '/usr/lib64/python3.6/lib-dynload', '/usr/lib64/python3.6/site-packages', '/usr/lib/python3.6/site-packages']
15:00:12  Error: No module named 'cassandra'

```

**Comment by roydahan** [comment]
It looks like an issue with cqlsh.
@yaronkaikov please check with @fruch and if so, move it to cqlsh repo.

**Comment by yaronkaikov** [comment]
@fruch is it related to SCT or cqlsh?

**Comment by fruch** [comment]
> @fruch is it related to SCT or cqlsh?

it's not SCT, and it's not clear if it's cqlsh itself or maybe scylla-python3

**Comment by roydahan** [comment]
Closing as dup.
