### ISSUE TITLE
instance_provision: spot_low_price cause exception ZeroDivisionError

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla-cluster-tests#831]
4ba6f225009731b023", "test_name": "longevity_test.py:LongevityTest.test_custom_time", "start_host": "SCT-CONTAINER", "job_name": ""}}}
< {"_index":"longevitytest","_type":"test_stats","_id":"20190312-151809-631892","_version":2,"result":"noop","_shards":{"total":0,"successful":0,"failed":0}}

Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado/core/test.py:436
Traceback (most recent call last):
  File "/sct/sdcm/tester.py", line 131, in wrapper
    return method(*args, **kwargs)
  File "/sct/sdcm/tester.py", line 205, in setUp
    self.init_resources()
  File "/sct/sdcm/tester.py", line 131, in wrapper
    return method(*args, **kwargs)
  File "/sct/sdcm/tester.py", line 680, in init_resources
    monitor_info=monitor_info)
  File "/sct/sdcm/tester.py", line 508, in get_cluster_aws
    self.db_cluster = create_cluster(db_type)
  File "/sct/sdcm/tester.py", line 491, in create_cluster
    **cl_params)
  File "/sct/sdcm/cluster_aws.py", line 531, in __init__
    params=params)
  File "/sct/sdcm/cluster.py", line 1783, in __init__
    super(BaseScyllaCluster, self).__init__(*args, **kwargs)
  File "/sct/sdcm/cluster_aws.py", line 109, in __init__
    region_names=self.region_names)
  File "/sct/sdcm/cluster.py", line 1593, in __init__
    self.add_nodes(num, dc_idx=dc_idx)
  File "/sct/sdcm/cluster_aws.py", line 560, in add_nodes
    enable_auto_bootstrap=enable_auto_bootstrap)
  File "/sct/sdcm/cluster_aws.py", line 279, in add_nodes
    instances = self._create_instances(count, ec2_user_data, dc_idx)
  File "/sct/sdcm/cluster_aws.py", line 210, in _create_instances
    instances = self._create_mixed_instances(count, interfaces, ec2_user_data, dc_idx, tags_list=tags_list)
  File "/sct/sdcm/cluster_aws.py", line 240, in _create_mixed_instances
    instances.extend(self._create_spot_instances(count_spot, interfaces, ec2_user_data, dc_idx, tags_list=tags_list))
  File "/sct/sdcm/cluster_aws.py", line 185, in _create_spot_instances
    instances_i = ec2.create_spot_instances(**spot_params)
  File "/sct/sdcm/ec2_client.py", line 262, in create_spot_instances
    spot_price = self._get_spot_price(instance_type, region_name=region_name)
  File "/sct/sdcm/ec2_client.py", line 140, in _get_spot_price
    price_avg = round(sum(prices) / len(prices), 4)
ZeroDivisionError: integer division or modulo by zero

ERROR 1-longevity_test.py:LongevityTest.test_custom_time -> TestSetupFail: integer division or modulo by zero

**Comment by aleksbykov** [comment]
Part of config file:
    aws: !mux
        instance_provision: 'spot_low_price' 
        cluster_backend: 'aws'

**Comment by fruch** [comment]
we should put this one as part of spot work, we need to remove this calculation

**Comment by bentsi** [comment]
Fixed in #835
