### ISSUE TITLE
provision stage fails with [user_data_format_version: none is not an allowed value (type=type_error.none.not_allowed)]

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#8340]
Provision step is failing for cases starting with images which is no scylla image:

```
01:43:16  Traceback (most recent call last):
01:43:16    File "/home/ubuntu/scylla-cluster-tests/./sct.py", line 1863, in <module>
01:43:16      cli.main(prog_name="hydra")
01:43:16    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
01:43:16      rv = self.invoke(ctx)
01:43:16    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
01:43:16      return _process_result(sub_ctx.command.invoke(sub_ctx))
01:43:16    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
01:43:16      return ctx.invoke(self.callback, **ctx.params)
01:43:16    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
01:43:16      return __callback(*args, **kwargs)
01:43:16    File "/home/ubuntu/scylla-cluster-tests/./sct.py", line 235, in provision_resources
01:43:16      layout.provision()
01:43:16    File "/home/ubuntu/scylla-cluster-tests/sdcm/sct_provision/aws/layout.py", line 34, in provision
01:43:16      self.db_cluster.provision()
01:43:16    File "/home/ubuntu/scylla-cluster-tests/sdcm/sct_provision/aws/cluster.py", line 228, in provision
01:43:16      instance_parameters = self._instance_parameters(region_id=region_id, availability_zone=az_id)
01:43:16    File "/home/ubuntu/scylla-cluster-tests/sdcm/sct_provision/aws/cluster.py", line 212, in _instance_parameters
01:43:16      user_data_raw=self._user_data,
01:43:16    File "/home/ubuntu/scylla-cluster-tests/sdcm/sct_provision/aws/cluster.py", line 253, in _user_data
01:43:16      return ScyllaUserDataBuilder(
01:43:16    File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
01:43:16  pydantic.error_wrappers.ValidationError: 1 validation error for ScyllaUserDataBuilder
01:43:16  user_data_format_version
01:43:16    none is not an allowed value (type=type_error.none.not_allowed)
```

Jenkins run:
- https://jenkins.scylladb.com/job/scylla-enterprise/job/SCT_Enterprise_Features/job/FIPS/job/longevity-100gb-4h-fips-test/111/

**Comment by roydahan** [comment]
Not interesting.
