### ISSUE TITLE
Reuse cluster doesn't work with multi-DC

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla-cluster-tests#836]
We need a way to pass list per region or something like that
```
 Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado/core/test.py:436
10:51:04 Traceback (most recent call last):
10:51:04   File "/sct/sdcm/tester.py", line 131, in wrapper
10:51:04     return method(*args, **kwargs)
10:51:04   File "/sct/sdcm/tester.py", line 205, in setUp
10:51:04     self.init_resources()
10:51:04   File "/sct/sdcm/tester.py", line 131, in wrapper
10:51:04     return method(*args, **kwargs)
10:51:04   File "/sct/sdcm/tester.py", line 680, in init_resources
10:51:04     monitor_info=monitor_info)
10:51:04   File "/sct/sdcm/tester.py", line 508, in get_cluster_aws
10:51:04     self.db_cluster = create_cluster(db_type)
10:51:04   File "/sct/sdcm/tester.py", line 491, in create_cluster
10:51:04     **cl_params)
10:51:04   File "/sct/sdcm/cluster_aws.py", line 531, in __init__
10:51:04     params=params)
10:51:04   File "/sct/sdcm/cluster.py", line 1783, in __init__
10:51:04     super(BaseScyllaCluster, self).__init__(*args, **kwargs)
10:51:04   File "/sct/sdcm/cluster_aws.py", line 109, in __init__
10:51:04     region_names=self.region_names)
10:51:04   File "/sct/sdcm/cluster.py", line 1593, in __init__
10:51:04     self.add_nodes(num, dc_idx=dc_idx)
10:51:04   File "/sct/sdcm/cluster_aws.py", line 560, in add_nodes
10:51:04     enable_auto_bootstrap=enable_auto_bootstrap)
10:51:04   File "/sct/sdcm/cluster_aws.py", line 277, in add_nodes
10:51:04     instances = self._get_instances(dc_idx)
10:51:04   File "/sct/sdcm/cluster_aws.py", line 257, in _get_instances
10:51:04     return [ec2.get_instance_by_private_ip(ip) for ip in self._node_private_ips]
10:51:04   File "/sct/sdcm/ec2_client.py", line 339, in get_instance_by_private_ip
10:51:04     raise GetInstanceByPrivateIpError("Cannot find instance by private ip: %s" % private_ip)
10:51:04 GetInstanceByPrivateIpError: Cannot find instance by private ip: 172.31.36.137
```

**Comment by fruch** [comment]
closed by #840
