### ISSUE TITLE
Reuse cluster is not working for k8s-local-kind

### ISSUE THREAD

**Issue by grzywin** [scylladb/scylla-cluster-tests#8404]
For Operator tests I was using SCT_REUSE_CLUSTER parameter to (obviously) reuse cluster. Recently I noticed that it stopped working as now I am getting error in setUp (pasted below). I did some digging and I found that it stopped working after this commit: https://github.com/scylladb/scylla-cluster-tests/commit/d4ddf76c64a819ffaee04382611a79fefc7772e7 After commenting out call for **destroy_unregistered_containers** method from cluster.py file, reusing cluster works again. 

ERROR    sdcm.tester:tester.py:192 Exception in setUp. Will call tearDown
Traceback (most recent call last):
  File "/home/grzywink/Projects/scylla-cluster-tests/sdcm/tester.py", line 185, in wrapper
    return method(*args, **kwargs)
  File "/home/grzywink/Projects/scylla-cluster-tests/sdcm/utils/decorators.py", line 121, in inner
    res = func(*args, **kwargs)
  File "/home/grzywink/Projects/scylla-cluster-tests/sdcm/tester.py", line 958, in setUp
    self.init_resources()
  File "/home/grzywink/Projects/scylla-cluster-tests/sdcm/tester.py", line 1920, in init_resources
    self.get_cluster_k8s_local_kind_cluster()
  File "/home/grzywink/Projects/scylla-cluster-tests/sdcm/tester.py", line 1578, in get_cluster_k8s_local_kind_cluster
    k8s_cluster.deploy()
  File "/home/grzywink/Projects/scylla-cluster-tests/sdcm/cluster_k8s/mini_k8s.py", line 394, in deploy
    self.setup_prerequisites()
  File "/home/grzywink/Projects/scylla-cluster-tests/sdcm/cluster_k8s/mini_k8s.py", line 199, in setup_prerequisites
    [self.log.info](http://self.log.info/)("Install prerequisites to %s", self.host_node)
  File "/usr/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/home/grzywink/Projects/scylla-cluster-tests/sdcm/cluster_k8s/mini_k8s.py", line 437, in host_node
    node.init()
  File "/home/grzywink/Projects/scylla-cluster-tests/sdcm/cluster.py", line 375, in init
    ContainerManager.destroy_unregistered_containers(self)
  File "/home/grzywink/Projects/scylla-cluster-tests/sdcm/utils/docker_utils.py", line 378, in destroy_unregistered_containers
    f"TestId={instance.tags['TestId']}",
  File "/usr/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/home/grzywink/Projects/scylla-cluster-tests/sdcm/cluster.py", line 535, in tags
    "Name": str([self.name](http://self.name/)), "UserName": str(self.ssh_login_info.get('user'))}
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by vponomaryov** [comment]
@Strasznik the traceback doesn't look completed

**Comment by Strasznik** [comment]
@vponomaryov Full output log attached.
[output.log](https://github.com/user-attachments/files/16687813/output.log)

**Comment by vponomaryov** [comment]
> @vponomaryov Full output log attached. [output.log](https://github.com/user-attachments/files/16687813/output.log)

The following is valuable part that is missing in the bug report:

```
...
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by Strasznik** [comment]
It was a copy/paste error. I added this line "AttributeError: 'NoneType' object has no attribute 'get'" to original traceback for visibility.
