### ISSUE TITLE
artifact tests failed with 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Annamikhlin** [scylladb/scylla-cluster-tests#8527]
### Issue description

artifact tests failed with error:

```
01:39:09  ======================================================================
01:39:09  ERROR: test_scylla_service (artifacts_test.ArtifactsTest)
01:39:09  ----------------------------------------------------------------------
01:39:09  Traceback (most recent call last):
01:39:09    File "/tmp/workspace/scylla-master/artifacts/artifacts-centos9-test/scylla-cluster-tests/artifacts_test.py", line 50, in setUp
01:39:09      super().setUp()
01:39:09    File "/tmp/workspace/scylla-master/artifacts/artifacts-centos9-test/scylla-cluster-tests/sdcm/tester.py", line 185, in wrapper
01:39:09      return method(*args, **kwargs)
01:39:09    File "/tmp/workspace/scylla-master/artifacts/artifacts-centos9-test/scylla-cluster-tests/sdcm/utils/decorators.py", line 121, in inner
01:39:09      res = func(*args, **kwargs)
01:39:09    File "/tmp/workspace/scylla-master/artifacts/artifacts-centos9-test/scylla-cluster-tests/sdcm/tester.py", line 958, in setUp
01:39:09      self.init_resources()
01:39:09    File "/tmp/workspace/scylla-master/artifacts/artifacts-centos9-test/scylla-cluster-tests/sdcm/tester.py", line 1913, in init_resources
01:39:09      self.get_cluster_gce(loader_info=loader_info, db_info=db_info,
01:39:09    File "/tmp/workspace/scylla-master/artifacts/artifacts-centos9-test/scylla-cluster-tests/sdcm/tester.py", line 1256, in get_cluster_gce
01:39:09      self.db_cluster = ScyllaGCECluster(gce_image=self.params.get('gce_image_db').strip(),
01:39:09    File "/tmp/workspace/scylla-master/artifacts/artifacts-centos9-test/scylla-cluster-tests/sdcm/cluster_gce.py", line 548, in __init__
01:39:09      super().__init__(
01:39:09    File "/tmp/workspace/scylla-master/artifacts/artifacts-centos9-test/scylla-cluster-tests/sdcm/cluster.py", line 3968, in __init__
01:39:09      super().__init__(*args, **kwargs)
01:39:09    File "/tmp/workspace/scylla-master/artifacts/artifacts-centos9-test/scylla-cluster-tests/sdcm/cluster_gce.py", line 273, in __init__
01:39:09      super().__init__(cluster_uuid=cluster_uuid,
01:39:09    File "/tmp/workspace/scylla-master/artifacts/artifacts-centos9-test/scylla-cluster-tests/sdcm/cluster.py", line 3231, in __init__
01:39:09      self.add_nodes(nodes_per_az[az_index], dc_idx=dc_idx, rack=rack,
01:39:09    File "/tmp/workspace/scylla-master/artifacts/artifacts-centos9-test/scylla-cluster-tests/sdcm/cluster_gce.py", line 518, in add_nodes
01:39:09      instances = self._create_instances(
01:39:09    File "/tmp/workspace/scylla-master/artifacts/artifacts-centos9-test/scylla-cluster-tests/sdcm/cluster_gce.py", line 446, in _create_instances
01:39:09      instances.append(self._create_instance(node_index, dc_idx, spot,
01:39:09    File "/tmp/workspace/scylla-master/artifacts/artifacts-centos9-test/scylla-cluster-tests/sdcm/cluster_gce.py", line 397, in _create_instance
01:39:09      "user-data": self.prepare_user_data(enable_auto_bootstrap),
01:39:09    File "/tmp/workspace/scylla-master/artifacts/artifacts-centos9-test/scylla-cluster-tests/sdcm/cluster.py", line 3404, in prepare_user_data
01:39:09      return user_data_builder.to_string()
01:39:09    File "/tmp/workspace/scylla-master/artifacts/artifacts-centos9-test/scylla-cluster-tests/sdcm/sct_provision/aws/user_data.py", line 74, in to_string
01:39:09      return self.return_in_format_v3()
01:39:09    File "/tmp/workspace/scylla-master/artifacts/artifacts-centos9-test/scylla-cluster-tests/sdcm/sct_provision/aws/user_data.py", line 78, in return_in_format_v3
01:39:09      scylla_image_configuration = self.dict()
01:39:09    File "/tmp/workspace/scylla-master/artifacts/artifacts-centos9-test/scylla-cluster-tests/sdcm/provision/common/builders.py", line 73, in dict
01:39:09      attribs.update({prop: getattr(self, prop) for prop in props})
01:39:09    File "/tmp/workspace/scylla-master/artifacts/artifacts-centos9-test/scylla-cluster-tests/sdcm/provision/common/builders.py", line 73, in <dictcomp>
01:39:09      attribs.update({prop: getattr(self, prop) for prop in props})
01:39:09    File "/tmp/workspace/scylla-master/artifacts/artifacts-centos9-test/scylla-cluster-tests/sdcm/sct_provision/aws/user_data.py", line 63, in post_configuration_script
01:39:09      ).to_string()
01:39:09    File "/tmp/workspace/scylla-master/artifacts/artifacts-centos9-test/scylla-cluster-tests/sdcm/provision/common/configuration_script.py", line 42, in to_string
01:39:09      script += self._script_body()
01:39:09    File "/tmp/workspace/scylla-master/artifacts/artifacts-centos9-test/scylla-cluster-tests/sdcm/provision/aws/configuration_script.py", line 29, in _script_body
01:39:09      script = super()._script_body()
01:39:09    File "/tmp/workspace/scylla-master/artifacts/artifacts-centos9-test/scylla-cluster-tests/sdcm/provision/common/configuration_script.py", line 90, in _script_body
01:39:09      host=self.syslog_host_port[0],
01:39:09  TypeError: 'NoneType' object is not subscriptable
01:39:09  
01:39:09  ----------------------------------------------------------------------
01:39:09  Ran 1 test in 8.645s
01:39:09  
01:39:09  FAILED (errors=2)
```

- [X] This issue is a regression.

### Link to failed jobs:
* https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-ubuntu2204-test/637
* https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-centos9-test/53/
* https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-rocky8-test/546/

**Comment by Annamikhlin** [comment]
related to commit: https://github.com/scylladb/scylla-cluster-tests/pull/8405/commits/4899ec5d75d5ace1db4d6518eba33f722a925bdc
