### ISSUE TITLE
nemesis AbortRepairMonkey threw exception

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylla-cluster-tests#885]
[longevity-large-partitions-4d-test](http://jenkins.cloudius-systems.com:8080/job/enterprise-2019.1/job/longevity-tests/job/longevity-large-partitions-4d-test/4/label=aws-eu-west1-qa-builder2/parameters/)

```
2019-04-02 21:54:47,651 wait             L0052 WARNI| Wait for: Wait for repair starts: timeout - 300 seconds - expired
2019-04-02 21:54:47,651 nemesis          L0503 ERROR| sdcm.nemesis.ChaosMonkey: Exception in random_disrupt_method abort_repair: Wait for: Wait for repair starts: timeout - 300 seconds - expired
2019-04-02 21:54:47,652 nemesis          L0883 ERROR| sdcm.nemesis.ChaosMonkey: Unhandled exception in method <function disrupt at 0x7ff9e55f40c8>
Traceback (most recent call last):
  File "/sct/sdcm/nemesis.py", line 879, in wrapper
    result = method(*args, **kwargs)
  File "/sct/sdcm/nemesis.py", line 1051, in disrupt
    self.call_random_disrupt_method()
  File "/sct/sdcm/nemesis.py", line 501, in call_random_disrupt_method
    disrupt_method()
  File "/sct/sdcm/nemesis.py", line 792, in disrupt_abort_repair
    text='Wait for repair starts')
  File "/sct/sdcm/wait.py", line 54, in wait_for
    raise WaitTimeoutExpired(err)
WaitTimeoutExpired: Wait for: Wait for repair starts: timeout - 300 seconds - expired
2019-04-02 21:54:47,652 nemesis          L0894 DEBUG| sdcm.nemesis.ChaosMonkey: AbortRepairMonkey duration -> 301 s
```

**Comment by fgelcer** [comment]
it seems like we are looking for repair start, but we didn't catch that the repair already started.

```
Running 'curl -X GET --header "Content-Type: application/json" --header "Accept: application/json" "http://127.0.0.1:10000/stream_manager/"'
2019-04-02 21:49:58,920 remote           L0103 INFO | [10.0.85.26] Running '/bin/ssh  -a -x   -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpRUWmWf -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l centos -p 22 -i /home/jenkins/.ssh/scylla-q
a-ec2 10.0.85.26 "curl -X GET --header \"Content-Type: application/json\" --header \"Accept: application/json\" \"http://127.0.0.1:10000/stream_manager/\""'
2019-04-02 21:49:59,100 remote           L0203 DEBUG| [10.0.239.180] [stdout] Apr 02 21:49:59 info   |  [shard 2] compaction - Compacting [/var/lib/scylla/data/scylla_bench/test-ed526c50554f11e98ae1000000000005/la-506-big-Data.db:level=0, /var/lib/scylla/data/scylla_bench/te
st-ed526c50554f11e98ae1000000000005/la-522-big-Data.db:level=0, ]
2019-04-02 21:49:59,311 remote           L0203 DEBUG| [10.0.85.26] [stderr]   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2019-04-02 21:49:59,311 remote           L0203 DEBUG| [10.0.85.26] [stderr]                                  Dload  Upload   Total   Spent    Left  Speed
2019-04-02 21:49:59,312 remote           L0203 DEBUG| [10.0.85.26] [stderr] 
2019-04-02 21:49:59,312 remote           L0203 DEBUG| [10.0.85.26] [stderr]   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
2019-04-02 21:49:59,312 remote           L0203 DEBUG| [10.0.85.26] [stderr] 100     2  100     2    0     0    444      0 --:--:-- --:--:-- --:--:--   666
2019-04-02 21:49:59,312 remote           L0187 DEBUG| [10.0.85.26] [stdout] []
2019-04-02 21:50:00,314 wait             L0026 DEBUG| Wait for repair starts (13.681385 secs)
2019-04-02 21:50:00,314 remote           L0905 DEBUG| Remote [centos@10.0.85.26]: Running 'curl -X GET --header "Content-Type: application/json" --header "Accept: application/json" "http://127.0.0.1:10000/stream_manager/"'
2019-04-02 21:50:00,315 remote           L0103 INFO | [10.0.85.26] Running '/bin/ssh  -a -x   -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpRUWmWf -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l centos -p 22 -i /home/jenkins/.ssh/scylla-q
a-ec2 10.0.85.26 "curl -X GET --header \"Content-Type: application/json\" --header \"Accept: application/json\" \"http://127.0.0.1:10000/stream_manager/\""'
2019-04-02 21:50:00,450 remote           L0203 DEBUG| [10.0.85.26] [stdout] Apr 02 21:50:00 info   |  [shard 1] repair - Repair 203 out of 761 ranges, id=3, shard=1, keyspace=scylla_bench, table={test_counters, test}, range=(-4776883712712103008, -4772897421438471027]
2019-04-02 21:50:00,458 remote           L0203 DEBUG| [10.0.85.26] [stdout] Apr 02 21:50:00 info   |  [shard 4] repair - Repair 261 out of 761 ranges, id=3, shard=4, keyspace=scylla_bench, table={test_counters, test}, range=(-3563488953440728831, -3543912777400080017]
2019-04-02 21:50:00,458 remote           L0203 DEBUG| [10.0.85.26] [stdout] Apr 02 21:50:00 info   |  [shard 1] repair - Repair 204 out of 761 ranges, id=3, shard=1, keyspace=scylla_bench, table={test_counters, test}, range=(-4772897421438471027, -4721986705506090419]
```

**Comment by amoskong** [comment]
If there is no inconsistent data, streaming won't be started. So we can try to stop the target node a while (30 seconds) to make the data to be inconsistent, then repair.

**Comment by roydahan** [comment]
I don’t think this was the issue, the streaming did started in that case.

**Comment by amoskong** [comment]
Yes, we don't need to trigger repair streaming in all nemesis.
Here we can make the timeout exception more friendly.

**Comment by fgelcer** [comment]
seen this issue again... could be related to https://github.com/scylladb/scylla/issues/6186

**Comment by amoskong** [comment]
> seen this issue again... could be related to [scylladb/scylla#6186](https://github.com/scylladb/scylla/issues/6186)

what's the job link?

**Comment by fgelcer** [comment]
> > seen this issue again... could be related to [scylladb/scylla#6186](https://github.com/scylladb/scylla/issues/6186)
> 
> what's the job link? or test id

@amoskong , test_id=dd38362b-7e8d-4a40-9367-a6f0687fadde

**Comment by amoskong** [comment]
In [4.1 longevity-200gb-48h/2/ ](https://jenkins.scylladb.com/job/scylla-4.1/job/longevity/job/longevity-200gb-48h/2/), 7 abort_repair nemesis had been executed, only one failed for this issue.

I checked the log, the repair was executed almost 20 mins, and repair logs kept raised from the db log.

The problem is in the result pattern, it can only identify the result `< 10.

```
        def repair_streaming_exists():   
            active_repair_cmd = 'curl -s -X GET --header "Content-Type: application/json" --header ' \
                                '"Accept: application/json" "http://127.0.0.1:10000/storage_service/active_repair/"'
            result = self.target_node.remoter.run(active_repair_cmd)            
            active_repairs = re.match(r".*\[(\d)\].*", result.stdout)           
            if active_repairs:
                self.log.debug("Found '%s' active repairs", active_repairs.group(1))
                return True
            return False
```

I will send a fix to SCT.

```
diff --git a/sdcm/nemesis.py b/sdcm/nemesis.py
index d2709622..82aecd4c 100644
--- a/sdcm/nemesis.py
+++ b/sdcm/nemesis.py
@@ -1310,7 +1310,7 @@ class Nemesis:  # pylint: disable=too-many-instance-attributes,too-many-public-m
             active_repair_cmd = 'curl -s -X GET --header "Content-Type: application/json" --header ' \
                                 '"Accept: application/json" "http://127.0.0.1:10000/storage_service/active_repair/"'
             result = self.target_node.remoter.run(active_repair_cmd)
-            active_repairs = re.match(r".*\[(\d)\].*", result.stdout)
+            active_repairs = re.match(r".*\[(\d)+\].*", result.stdout)
             if active_repairs:
                 self.log.debug("Found '%s' active repairs", active_repairs.group(1))
                 return True
```
