### ISSUE TITLE
[disrupt_add_drop_column] wrong node was selected for nemises after new dc been added\removed

### ISSUE THREAD

**Issue by timtimb0t** [scylladb/scylla-cluster-tests#8929]
## Packages

Scylla version: `2024.2.0~rc3-20241004.89f8638e9e9b` with build-id `95fdcb05a2d968f52fbcfc46114ef612aaf56608`

Kernel Version: `5.15.0-1070-aws`

## Issue description

- This issue is a regression.

*Describe your issue in detail and steps it took to produce it.*
- Run **disrupt_add_remove_dc** nemises
- Run **disrupt_add_drop_column** nemises

According to the logs node #10 been created during **disrupt_add_remove_dc** nemises and picked for **disrupt_add_drop_column**, but it shouldnt

```
2024-10-06 15:58:18.695: (DisruptionEvent Severity.ERROR) period_type=end event_id=625cf12b-adc6-474d-84df-082391d71c7e duration=9m58s: nemesis_name=AddDropColumn target_node=Node longevity-parallel-topology-schema--db-node-7e255144-10 [52.5.228.215 | 10.12.10.241] errors=Failed to run a command due to exception!
Command: '/usr/bin/cqlsh --no-color   --request-timeout=120 --connect-timeout=60  -e "describe keyspace1.standard1" 10.12.32.230'
Stdout:
Stderr:
Exception:  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 588, in run
self.connect()
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 524, in connect
raise ConnectTimeout(ex_msg) from exc
Failed to connect in 60 seconds, last error: (ConnectError)Error connecting to host '10.12.10.241:22' - No route to host
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 417, in _init_socket
self.sock.connect((host, port))
OSError: [Errno 113] No route to host
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 515, in connect
self._connect()
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 530, in _connect
self._init_socket(self.host, self.port)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 422, in _init_socket
raise ConnectError("Error connecting to host '%s:%s' - %s" % (host, port, str(error_type))) from ex
sdcm.remote.libssh2_client.exceptions.ConnectError: Error connecting to host '10.12.10.241:22' - No route to host
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 588, in run
self.connect()
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 524, in connect
raise ConnectTimeout(ex_msg) from exc
sdcm.remote.libssh2_client.exceptions.ConnectTimeout: Failed to connect in 60 seconds, last error: (ConnectError)Error connecting to host '10.12.10.241:22' - No route to host
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 605, in _run
return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 538, in _run_execute
result = connection.run(**command_kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 591, in run
return self._complete_run(
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 650, in _complete_run
raise exception
sdcm.remote.libssh2_client.exceptions.FailedToRunCommand: Failed to run a command due to exception!
Command: '/usr/bin/cqlsh --no-color   --request-timeout=120 --connect-timeout=60  -e "describe keyspace1.standard1" 10.12.32.230'
Stdout:
Stderr:
Exception:  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 588, in run
self.connect()
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 524, in connect
raise ConnectTimeout(ex_msg) from exc
Failed to connect in 60 seconds, last error: (ConnectError)Error connecting to host '10.12.10.241:22' - No route to host
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 5219, in wrapper
result = method(*args[1:], **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2510, in disrupt_add_drop_column
self._add_drop_column_run_in_cycle()
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2239, in _add_drop_column_run_in_cycle
self._add_drop_column()
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2205, in _add_drop_column
self._add_drop_column_target_table = self._add_drop_column_get_target_table(
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2130, in _add_drop_column_get_target_table
current_tables = self._get_all_tables_with_no_compact_storage(self._add_drop_column_tables_to_ignore)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2118, in _get_all_tables_with_no_compact_storage
tables = get_db_tables(session=session,
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 1611, in get_db_tables
create_table_statement = node.run_cqlsh(f"describe {keyspace_name}.{row.table_name}").stdout.upper()
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2860, in run_cqlsh
cqlsh_out = self.remoter.run(cmd, timeout=timeout + 120,  # we give 30 seconds to cqlsh timeout mechanism to work
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 614, in run
result = _run()
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 72, in inner
return func(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 607, in _run
if self._run_on_retryable_exception(exc, new_session):
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_libssh_cmd_runner.py", line 78, in _run_on_retryable_exception
raise RetryableNetworkException(str(exc), original=exc)
sdcm.remote.base.RetryableNetworkException: Failed to run a command due to exception!
Command: '/usr/bin/cqlsh --no-color   --request-timeout=120 --connect-timeout=60  -e "describe keyspace1.standard1" 10.12.32.230'
Stdout:
Stderr:
Exception:  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 588, in run
self.connect()
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 524, in connect
raise ConnectTimeout(ex_msg) from exc
Failed to connect in 60 seconds, last error: (ConnectError)Error connecting to host '10.12.10.241:22' - No route to host
```

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Cluster size: 5 nodes (i4i.2xlarge)

Scylla Nodes used in this run:
- longevity-parallel-topology-schema--db-node-7e255144-9 (3.213.26.225 | 10.12.8.106) (shards: 7)
- longevity-parallel-topology-schema--db-node-7e255144-8 (52.23.32.149 | 10.12.8.164) (shards: 7)
- longevity-parallel-topology-schema--db-node-7e255144-7 (54.208.63.86 | 10.12.11.154) (shards: 7)
- longevity-parallel-topology-schema--db-node-7e255144-6 (52.4.144.66 | 10.12.8.203) (shards: -1)
- longevity-parallel-topology-schema--db-node-7e255144-5 (34.199.239.11 | 10.12.11.33) (shards: 7)
- longevity-parallel-topology-schema--db-node-7e255144-4 (18.205.211.173 | 10.12.10.18) (shards: 7)
- longevity-parallel-topology-schema--db-node-7e255144-30 (34.196.78.255 | 10.12.8.224) (shards: 7)
- longevity-parallel-topology-schema--db-node-7e255144-3 (18.215.94.155 | 10.12.11.219) (shards: 7)
- longevity-parallel-topology-schema--db-node-7e255144-29 (3.225.55.34 | 10.12.11.117) (shards: 7)
- longevity-parallel-topology-schema--db-node-7e255144-28 (34.201.191.243 | 10.12.10.136) (shards: -1)
- longevity-parallel-topology-schema--db-node-7e255144-27 (3.215.198.46 | 10.12.9.223) (shards: 7)
- longevity-parallel-topology-schema--db-node-7e255144-26 (52.1.231.248 | 10.12.9.254) (shards: 7)
- longevity-parallel-topology-schema--db-node-7e255144-25 (3.213.43.155 | 10.12.9.149) (shards: 7)
- longevity-parallel-topology-schema--db-node-7e255144-24 (3.228.57.238 | 10.12.11.241) (shards: 7)
- longevity-parallel-topology-schema--db-node-7e255144-23 (54.157.183.79 | 10.12.11.61) (shards: 7)
- longevity-parallel-topology-schema--db-node-7e255144-22 (54.236.67.136 | 10.12.9.172) (shards: 7)
- longevity-parallel-topology-schema--db-node-7e255144-21 (18.233.212.63 | 10.12.10.129) (shards: 7)
- longevity-parallel-topology-schema--db-node-7e255144-20 (44.194.189.187 | 10.12.9.187) (shards: -1)
- longevity-parallel-topology-schema--db-node-7e255144-2 (34.226.61.74 | 10.12.8.70) (shards: 7)
- longevity-parallel-topology-schema--db-node-7e255144-19 (34.196.154.150 | 10.12.8.250) (shards: 7)
- longevity-parallel-topology-schema--db-node-7e255144-18 (54.224.46.8 | 10.12.9.164) (shards: 7)
- longevity-parallel-topology-schema--db-node-7e255144-17 (23.21.41.179 | 10.12.11.31) (shards: 7)
- longevity-parallel-topology-schema--db-node-7e255144-16 (34.228.154.24 | 10.12.11.45) (shards: 7)
- longevity-parallel-topology-schema--db-node-7e255144-15 (18.214.245.85 | 10.12.11.112) (shards: 7)
- longevity-parallel-topology-schema--db-node-7e255144-14 (54.225.163.120 | 10.12.8.67) (shards: 7)
- longevity-parallel-topology-schema--db-node-7e255144-13 (54.157.216.102 | 10.12.10.199) (shards: 7)
- longevity-parallel-topology-schema--db-node-7e255144-12 (3.226.204.237 | 10.12.9.18) (shards: 7)
- longevity-parallel-topology-schema--db-node-7e255144-11 (34.232.32.175 | 10.12.8.57) (shards: -1)
- longevity-parallel-topology-schema--db-node-7e255144-10 (52.5.228.215 | 10.12.10.241) (shards: 7)
- longevity-parallel-topology-schema--db-node-7e255144-1 (34.197.13.65 | 10.12.11.115) (shards: 7)

OS / Image: `ami-02ba7d8e39a118a2d` (aws: undefined_region)

Test: `longevity-schema-topology-changes-12h-test`
Test id: `7e255144-9d18-48a9-b0b8-106e741b2630`
Test name: `enterprise-2024.2/tier1/longevity-schema-topology-changes-12h-test`
Test method: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):

- [longevity-parallel-schema-changes-12h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/5c604c7363757dcd9084b9f267b4b1b90bee9776/test-cases/longevity/longevity-parallel-schema-changes-12h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 7e255144-9d18-48a9-b0b8-106e741b2630`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=7e255144-9d18-48a9-b0b8-106e741b2630)
- Show all stored logs command: `$ hydra investigate show-logs 7e255144-9d18-48a9-b0b8-106e741b2630`

## Logs:
- **longevity-parallel-topology-schema--db-node-7e255144-6** - [https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241006_132449/longevity-parallel-topology-schema--db-node-7e255144-6-7e255144.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241006_132449/longevity-parallel-topology-schema--db-node-7e255144-6-7e255144.tar.gz)
- **longevity-parallel-topology-schema--db-node-7e255144-5** - [https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241006_132449/longevity-parallel-topology-schema--db-node-7e255144-5-7e255144.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241006_132449/longevity-parallel-topology-schema--db-node-7e255144-5-7e255144.tar.gz)
- **longevity-parallel-topology-schema--db-node-7e255144-2** - [https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241006_132449/longevity-parallel-topology-schema--db-node-7e255144-2-7e255144.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241006_132449/longevity-parallel-topology-schema--db-node-7e255144-2-7e255144.tar.gz)
- **longevity-parallel-topology-schema--db-node-7e255144-8** - [https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241006_132449/longevity-parallel-topology-schema--db-node-7e255144-8-7e255144.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241006_132449/longevity-parallel-topology-schema--db-node-7e255144-8-7e255144.tar.gz)
- **longevity-parallel-topology-schema--db-node-7e255144-10** - [https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241006_132449/longevity-parallel-topology-schema--db-node-7e255144-10-7e255144.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241006_132449/longevity-parallel-topology-schema--db-node-7e255144-10-7e255144.tar.gz)
- **longevity-parallel-topology-schema--db-node-7e255144-11** - [https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241006_132449/longevity-parallel-topology-schema--db-node-7e255144-11-7e255144.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241006_132449/longevity-parallel-topology-schema--db-node-7e255144-11-7e255144.tar.gz)
- **longevity-parallel-topology-schema--db-node-7e255144-3** - [https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241006_132449/longevity-parallel-topology-schema--db-node-7e255144-3-7e255144.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241006_132449/longevity-parallel-topology-schema--db-node-7e255144-3-7e255144.tar.gz)
- **longevity-parallel-topology-schema--db-node-7e255144-7** - [https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241006_132449/longevity-parallel-topology-schema--db-node-7e255144-7-7e255144.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241006_132449/longevity-parallel-topology-schema--db-node-7e255144-7-7e255144.tar.gz)
- **longevity-parallel-topology-schema--db-node-7e255144-1** - [https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241006_132449/longevity-parallel-topology-schema--db-node-7e255144-1-7e255144.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241006_132449/longevity-parallel-topology-schema--db-node-7e255144-1-7e255144.tar.gz)
- **longevity-parallel-topology-schema--db-node-7e255144-13** - [https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241006_132449/longevity-parallel-topology-schema--db-node-7e255144-13-7e255144.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241006_132449/longevity-parallel-topology-schema--db-node-7e255144-13-7e255144.tar.gz)
- **longevity-parallel-topology-schema--db-node-7e255144-14** - [https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241006_132449/longevity-parallel-topology-schema--db-node-7e255144-14-7e255144.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241006_132449/longevity-parallel-topology-schema--db-node-7e255144-14-7e255144.tar.gz)
- **longevity-parallel-topology-schema--db-node-7e255144-12** - [https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241006_132449/longevity-parallel-topology-schema--db-node-7e255144-12-7e255144.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241006_132449/longevity-parallel-topology-schema--db-node-7e255144-12-7e255144.tar.gz)
- **longevity-parallel-topology-schema--db-node-7e255144-9** - [https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241006_132449/longevity-parallel-topology-schema--db-node-7e255144-9-7e255144.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241006_132449/longevity-parallel-topology-schema--db-node-7e255144-9-7e255144.tar.gz)
- **longevity-parallel-topology-schema--db-node-7e255144-19** - [https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241006_132449/longevity-parallel-topology-schema--db-node-7e255144-19-7e255144.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241006_132449/longevity-parallel-topology-schema--db-node-7e255144-19-7e255144.tar.gz)
- **longevity-parallel-topology-schema--db-node-7e255144-20** - [https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241006_132449/longevity-parallel-topology-schema--db-node-7e255144-20-7e255144.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241006_132449/longevity-parallel-topology-schema--db-node-7e255144-20-7e255144.tar.gz)
- **longevity-parallel-topology-schema--db-node-7e255144-4** - [https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241006_132449/longevity-parallel-topology-schema--db-node-7e255144-4-7e255144.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241006_132449/longevity-parallel-topology-schema--db-node-7e255144-4-7e255144.tar.gz)
- **longevity-parallel-topology-schema--db-node-7e255144-18** - [https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241006_132449/longevity-parallel-topology-schema--db-node-7e255144-18-7e255144.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241006_132449/longevity-parallel-topology-schema--db-node-7e255144-18-7e255144.tar.gz)
- **longevity-parallel-topology-schema--db-node-7e255144-15** - [https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241006_132449/longevity-parallel-topology-schema--db-node-7e255144-15-7e255144.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241006_132449/longevity-parallel-topology-schema--db-node-7e255144-15-7e255144.tar.gz)
- **longevity-parallel-topology-schema--db-node-7e255144-16** - [https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241006_132449/longevity-parallel-topology-schema--db-node-7e255144-16-7e255144.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241006_132449/longevity-parallel-topology-schema--db-node-7e255144-16-7e255144.tar.gz)
- **longevity-parallel-topology-schema--db-node-7e255144-21** - [https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241006_132449/longevity-parallel-topology-schema--db-node-7e255144-21-7e255144.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241006_132449/longevity-parallel-topology-schema--db-node-7e255144-21-7e255144.tar.gz)
- **longevity-parallel-topology-schema--db-node-7e255144-26** - [https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241006_132449/longevity-parallel-topology-schema--db-node-7e255144-26-7e255144.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241006_132449/longevity-parallel-topology-schema--db-node-7e255144-26-7e255144.tar.gz)
- **longevity-parallel-topology-schema--db-node-7e255144-27** - [https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241006_132449/longevity-parallel-topology-schema--db-node-7e255144-27-7e255144.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241006_132449/longevity-parallel-topology-schema--db-node-7e255144-27-7e255144.tar.gz)
- **longevity-parallel-topology-schema--db-node-7e255144-28** - [https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241006_132449/longevity-parallel-topology-schema--db-node-7e255144-28-7e255144.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241006_132449/longevity-parallel-topology-schema--db-node-7e255144-28-7e255144.tar.gz)
- **longevity-parallel-topology-schema--db-node-7e255144-29** - [https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241006_132449/longevity-parallel-topology-schema--db-node-7e255144-29-7e255144.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241006_132449/longevity-parallel-topology-schema--db-node-7e255144-29-7e255144.tar.gz)
- **longevity-parallel-topology-schema--db-node-7e255144-23** - [https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241006_132449/longevity-parallel-topology-schema--db-node-7e255144-23-7e255144.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241006_132449/longevity-parallel-topology-schema--db-node-7e255144-23-7e255144.tar.gz)
- **db-cluster-7e255144.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241007_015457/db-cluster-7e255144.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241007_015457/db-cluster-7e255144.tar.gz)
- **sct-runner-events-7e255144.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241007_015457/sct-runner-events-7e255144.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241007_015457/sct-runner-events-7e255144.tar.gz)
- **sct-7e255144.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241007_015457/sct-7e255144.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241007_015457/sct-7e255144.log.tar.gz)
- **loader-set-7e255144.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241007_015457/loader-set-7e255144.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241007_015457/loader-set-7e255144.tar.gz)
- **monitor-set-7e255144.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241007_015457/monitor-set-7e255144.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7e255144-9d18-48a9-b0b8-106e741b2630/20241007_015457/monitor-set-7e255144.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2024.2/job/tier1/job/longevity-schema-topology-changes-12h-test/7/)
[Argus](https://argus.scylladb.com/test/95f71148-1ff5-4118-8753-d6340560b071/runs?additionalRuns[]=7e255144-9d18-48a9-b0b8-106e741b2630)
</details>

**Comment by aleksbykov** [comment]
New node added to new DC, is not marked with running_nemesis, and it could be choosen for another nemesis. Need to set and then remove  running_nemesis property  for add_remove_dc

**Comment by juliayakovlev** [comment]
This is dupl of https://github.com/scylladb/scylla-cluster-tests/issues/8401

**Comment by fruch** [comment]
fixed in https://github.com/scylladb/scylla-cluster-tests/issues/8401
