### ISSUE TITLE
Running hydra on Mac (Apple Silicone)

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla-cluster-tests#8973]
This is an issue to track all problems I've got and hopefully reaching a working state:

1. Trying to run "hydra bash" fails with
```
docker: Error response from daemon: error while creating mount source path '/host_mnt/private/etc/sudoers': mkdir /host_mnt/private/etc/sudoers: permission denied.

```
Solution: Change "file sharing implementation" of docker desktop settings (general tab) from **VirtioFS** to '**gRPC FUSE**'

hydra bash works.

2. Trying to run any hydra command, even "hydra help" fails with:

```
Traceback (most recent call last):
  File "/Users/roy/git/scylla/scylla-cluster-tests/./sct.py", line 42, in <module>
    import sct_ssh
  File "/Users/roy/git/scylla/scylla-cluster-tests/sct_ssh.py", line 27, in <module>
    from sdcm.cluster import BaseScyllaCluster, BaseCluster, BaseNode
  File "/Users/roy/git/scylla/scylla-cluster-tests/sdcm/cluster.py", line 62, in <module>
    from sdcm.node_exporter_setup import NodeExporterSetup
  File "/Users/roy/git/scylla/scylla-cluster-tests/sdcm/node_exporter_setup.py", line 1, in <module>
    from sdcm.remote import shell_script_cmd
  File "/Users/roy/git/scylla/scylla-cluster-tests/sdcm/remote/__init__.py", line 31, in <module>
    LOCALRUNNER = LocalCmdRunner()
  File "/Users/roy/git/scylla/scylla-cluster-tests/sdcm/remote/local_cmd_runner.py", line 32, in __init__
    user = getpass.getuser()
  File "/usr/local/lib/python3.10/getpass.py", line 169, in getuser
    return pwd.getpwuid(os.getuid())[0]
KeyError: 'getpwuid(): uid not found: 501'

```

Workaround (not sure how good is the workaround):
```
diff --git a/sdcm/remote/local_cmd_runner.py b/sdcm/remote/local_cmd_runner.py
index 266c661e9..da6cd12e3 100644
--- a/sdcm/remote/local_cmd_runner.py
+++ b/sdcm/remote/local_cmd_runner.py
@@ -29,7 +29,8 @@ class LocalCmdRunner(CommandRunner):  # pylint: disable=too-few-public-methods
         if hostname is None:
             hostname = socket.gethostname()
         if user is None:
-            user = getpass.getuser()
+            # user = getpass.getuser()
+            user = 'roy'
         super().__init__(user=user, hostname=hostname)

```

Next problem is:
```
Going to run './sct.py  help'...
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
/usr/local/lib/python3.10/site-packages/paramiko/pkey.py:100: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "cipher": algorithms.TripleDES,
/usr/local/lib/python3.10/site-packages/paramiko/transport.py:259: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "class": algorithms.TripleDES,
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/usr/local/lib/python3.10/site-packages/docker/transport/unixconn.py", line 26, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 589, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 802, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 552, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/usr/local/lib/python3.10/site-packages/docker/transport/unixconn.py", line 26, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/docker/api/client.py", line 223, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/usr/local/lib/python3.10/site-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/usr/local/lib/python3.10/site-packages/docker/utils/decorators.py", line 44, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/docker/api/client.py", line 246, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 604, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/roy/git/scylla/scylla-cluster-tests/./sct.py", line 42, in <module>
    import sct_ssh
  File "/Users/roy/git/scylla/scylla-cluster-tests/sct_ssh.py", line 27, in <module>
    from sdcm.cluster import BaseScyllaCluster, BaseCluster, BaseNode
  File "/Users/roy/git/scylla/scylla-cluster-tests/sdcm/cluster.py", line 63, in <module>
    from sdcm.db_log_reader import DbLogReader
  File "/Users/roy/git/scylla/scylla-cluster-tests/sdcm/db_log_reader.py", line 28, in <module>
    from sdcm.utils.common import make_threads_be_daemonic_by_default
  File "/Users/roy/git/scylla/scylla-cluster-tests/sdcm/utils/common.py", line 70, in <module>
    from sdcm.utils.aws_utils import (
  File "/Users/roy/git/scylla/scylla-cluster-tests/sdcm/utils/aws_utils.py", line 29, in <module>
    from sdcm.test_config import TestConfig
  File "/Users/roy/git/scylla/scylla-cluster-tests/sdcm/test_config.py", line 20, in <module>
    from sdcm.utils.docker_utils import ContainerManager
  File "/Users/roy/git/scylla/scylla-cluster-tests/sdcm/utils/docker_utils.py", line 66, in <module>
    _docker = DockerClient.from_env(timeout=DOCKER_API_CALL_TIMEOUT)  # pylint: disable=invalid-name
  File "/usr/local/lib/python3.10/site-packages/docker/client.py", line 94, in from_env
    return cls(
  File "/usr/local/lib/python3.10/site-packages/docker/client.py", line 45, in __init__
    self.api = APIClient(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/docker/api/client.py", line 207, in __init__
    self._version = self._retrieve_server_version()
  File "/usr/local/lib/python3.10/site-packages/docker/api/client.py", line 230, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

```

**Comment by roydahan** [comment]
Installing ssh2-python has a problem with clang 16 which comes on Mac.
To be able to pip install it correctly, we should do:

git clone ssh2-python repo.
`CFLAGS=-Wno-error=incompatible-function-pointer-types pip install .`

**Comment by roydahan** [comment]
Solving the ssh2-python installation issue, I could run ./sct.py, but still can't run hydra.

Tried adding all possible configurations around docker.sock but couldn't make it work.

 ![Image](https://github.com/user-attachments/assets/093a08b4-83f5-4d27-91e3-a46044b034e1)

**Comment by unfixa1** [comment]
You can try to find or build a Hydra image for the ARM architecture to avoid platform mismatch issues. 
You can also consider using tools such as [servbay](servbay.com), which is faster than docker.

**Comment by roydahan** [comment]
Meanwhile, tested also with podman:

```
HYDRA_TOOL=podman hydra list-images

Pull version v1.77-argus-0.12.10 from Docker Hub...
Trying to pull docker.io/scylladb/hydra:v1.77-argus-0.12.10...
Getting image source signatures
Copying blob sha256:428bad6fa2424960758fa690720e615f635324a1f04f82ab7974af4877c00872
...
...
Writing manifest to image destination
WARNING: image platform (linux/amd64) does not match the expected platform (linux/arm64)
ea401cd1288caa9606d29050820266d0e6642cd23a06901fa27108a2a4113607
Going to run './sct.py  list-images'...
Error: unknown shorthand flag: 't' in -t
See 'podman system --help'
WARNING: image platform (linux/amd64) does not match the expected platform (linux/arm64)
Error: unknown mount option "uid=501": invalid mount option

```

**Comment by roydahan** [comment]
After hacking session together with @fruch we reached to these changes and it works!

```
diff --git a/docker/env/hydra.sh b/docker/env/hydra.sh
index c51ba9be1..7b3272185 100755
--- a/docker/env/hydra.sh
+++ b/docker/env/hydra.sh
@@ -225,7 +225,7 @@ function run_in_docker () {
     REMOTE_DOCKER_HOST=$2
     if [ -z "$is_podman" ]; then
         docker_common_args+=(
-           -v /var/run:/run
+           -v /var/run/docker.sock:/var/run/docker.sock
            -v /dev:/dev:rw
            )
     else
@@ -249,6 +249,7 @@ function run_in_docker () {
         -v /var/tmp:/var/tmp \
         -v "${HOME_DIR}:${HOME_DIR}" \
         --tmpfs "${HOME_DIR}/.local:exec,uid=$(id -u ${USER}),gid=$(id -g ${USER})" \
+        --tmpfs "${HOME_DIR}/.docker:exec,uid=$(id -u ${USER}),gid=$(id -g ${USER})" \
         -w "${SCT_DIR}" \
         -e JOB_NAME="${JOB_NAME}" \
         -e BUILD_URL="${BUILD_URL}" \
@@ -256,7 +257,7 @@ function run_in_docker () {
         -e _SCT_BASE_DIR="${SCT_DIR}" \
         -e GIT_USER_EMAIL \
         -e RUNNER_IP \
-        -u ${USER_ID} \
+        -e HOME="${HOME_DIR}" \
         -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
         -v /etc/passwd:/etc/passwd:ro \
         -v /etc/group:/etc/group:ro \

```

**Comment by roydahan** [comment]
note to self: I still needed to manually allow some permissions to docker on my mac, probably full disk access can solve it.

**Comment by roydahan** [comment]
Sent PR to add support - https://github.com/scylladb/scylla-cluster-tests/pull/9004
