### ISSUE TITLE
decomission nemesis failed to clean scylla_bench keyspace

### ISSUE THREAD

**Issue by bentsi** [scylladb/scylla-cluster-tests#908]
When running scylla bench and `disrupt_nodetool_decommission`, the nemesis shouldn't clean 
scylla_bench keyspace
```
2019-04-16 15:54:50,679 nemesis          L0883 ERROR| sdcm.nemesis.ChaosMonkey: Unhandled exception in method <function disrupt at 0x7f8d6c8821b8>
Traceback (most recent call last):
  File "/sct/sdcm/nemesis.py", line 879, in wrapper
    result = method(*args, **kwargs)
  File "/sct/sdcm/nemesis.py", line 1051, in disrupt
    self.call_random_disrupt_method()
  File "/sct/sdcm/nemesis.py", line 501, in call_random_disrupt_method
    disrupt_method()
  File "/sct/sdcm/nemesis.py", line 351, in disrupt_nodetool_decommission
    node.remoter.run('nodetool --host localhost cleanup {}'.format(keyspace), verbose=True)
  File "/sct/sdcm/remote.py", line 916, in run
    watch_stdout_pattern=watch_stdout_pattern)
  File "/sct/sdcm/remote.py", line 857, in _run
    watch_stdout_pattern=watch_stdout_pattern)
  File "/sct/sdcm/remote.py", line 814, in ssh_run
    raise process.CmdError(cmd, sp.result)
CmdError: Command '/bin/ssh  -a -x   -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpPxMMmN -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l centos -p 22 -i /home/jenkins/.ssh/scylla-qa-ec2 10.0.115.51 "nodetool --host localhost cleanup scylla_bench"' failed (rc=255)
```

**Comment by bentsi** [comment]
(opened task in trello)

**Comment by roydahan** [comment]
Why?

**Comment by bentsi** [comment]
hmm, good question. We need to handle the exception so...

**Comment by roydahan** [comment]
From what I see we run cleanup on all keyspaces that we find, it command shouldn't fail.
We need the failure reason (someone to look in logs and findout why it failed).

**Comment by bentsi** [comment]
will add `verbose=True` to the cleanup command

**Comment by bentsi** [comment]
checked: currently(in Fabric Remote era), we print error on each remote command failure, so nothing to improve
