### ISSUE TITLE
When resources provisioning failed on provision stage, creation monitor instance failed during run stage

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-cluster-tests#9083]
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

When resources provisioning failed on provision stage, creation monitor instance failed during run stage.
Provisioning of db nodes and loaders succeeded.

Provision Resources for test_latency_read_with_upgrade during **provision stage**:
```
Using placement group 'arn:aws:ec2:eu-west-1:797456418907:placement-group/perf-latency-upgrade-ubuntu-placement_group-a22c015f' for capacity reservation.
15:14:07  Creating capacity reservation for test a22c015f-57fb-4b93-8938-7205131d1ec2 with request: {'i3en.2xlarge': 9, 'c6i.2xlarge': 4}
15:14:07  Supported availability zones for instance types ['i3en.2xlarge', 'c6i.2xlarge']: ['eu-west-1b', 'eu-west-1c', 'eu-west-1a']
15:14:07  Creating capacity reservation in eu-west-1b
15:14:07  using placement group for CR: arn:aws:ec2:eu-west-1:797456418907:placement-group/perf-latency-upgrade-ubuntu-placement_group-a22c015f
15:14:08  Capacity reservation created for i3en.2xlarge
15:14:08  using placement group for CR: arn:aws:ec2:eu-west-1:797456418907:placement-group/perf-latency-upgrade-ubuntu-placement_group-a22c015f
15:14:14  Failed to create capacity reservation for c6i.2xlarge. Error: An error occurred (InsufficientInstanceCapacity) when calling the CreateCapacityReservation operation (reached max retries: 4): Insufficient capacity.
15:14:14  Failed to create capacity reservation in eu-west-1b
15:14:14  Capacity reservation cr-04318edd8664f5b7c for i3en.2xlarge cancelled successfully.
15:14:14  waiting 30s before falling back to next AZ to release placement group
15:14:45  Falling back to next availability zone.
15:14:45  Creating capacity reservation in eu-west-1c
15:14:45  using placement group for CR: arn:aws:ec2:eu-west-1:797456418907:placement-group/perf-latency-upgrade-ubuntu-placement_group-a22c015f
15:14:45  Capacity reservation created for i3en.2xlarge
15:14:45  using placement group for CR: arn:aws:ec2:eu-west-1:797456418907:placement-group/perf-latency-upgrade-ubuntu-placement_group-a22c015f
15:14:53  Failed to create capacity reservation for c6i.2xlarge. Error: An error occurred (InsufficientInstanceCapacity) when calling the CreateCapacityReservation operation (reached max retries: 4): Insufficient capacity.
15:14:53  Failed to create capacity reservation in eu-west-1c
15:14:54  Capacity reservation cr-0d206030bb740ef0c for i3en.2xlarge cancelled successfully.
15:14:54  waiting 30s before falling back to next AZ to release placement group
15:15:24  Falling back to next availability zone.
15:15:24  Creating capacity reservation in eu-west-1a
15:15:24  using placement group for CR: arn:aws:ec2:eu-west-1:797456418907:placement-group/perf-latency-upgrade-ubuntu-placement_group-a22c015f
15:15:24  Capacity reservation created for i3en.2xlarge
15:15:24  using placement group for CR: arn:aws:ec2:eu-west-1:797456418907:placement-group/perf-latency-upgrade-ubuntu-placement_group-a22c015f
15:15:30  Failed to create capacity reservation for c6i.2xlarge. Error: An error occurred (InsufficientInstanceCapacity) when calling the CreateCapacityReservation operation (reached max retries: 4): Insufficient capacity.
15:15:30  Failed to create capacity reservation in eu-west-1a
15:15:30  Capacity reservation cr-0a69ced0627f6a490 for i3en.2xlarge cancelled successfully.
15:15:30  waiting 30s before falling back to next AZ to release placement group
15:16:05  Falling back to next availability zone.
15:16:05  Traceback (most recent call last):
15:16:05    File "/home/ubuntu/scylla-cluster-tests/./sct.py", line 1863, in <module>
15:16:05      cli.main(prog_name="hydra")
15:16:05    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
15:16:05      rv = self.invoke(ctx)
15:16:05    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
15:16:05      return _process_result(sub_ctx.command.invoke(sub_ctx))
15:16:05    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
15:16:05      return ctx.invoke(self.callback, **ctx.params)
15:16:05    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
15:16:05      return __callback(*args, **kwargs)
15:16:05    File "/home/ubuntu/scylla-cluster-tests/./sct.py", line 233, in provision_resources
15:16:05      layout.provision()
15:16:05    File "/home/ubuntu/scylla-cluster-tests/sdcm/sct_provision/aws/layout.py", line 32, in provision
15:16:05      SCTCapacityReservation.reserve(self._params)
15:16:05    File "/home/ubuntu/scylla-cluster-tests/sdcm/provision/aws/capacity_reservation.py", line 182, in reserve
15:16:05      raise CapacityReservationError("Failed to create capacity reservation in any availability zone.")
15:16:05  sdcm.exceptions.CapacityReservationError: Failed to create capacity reservation in any availability zone.
```

Create instance failed during **run stage**:
```
< t:2024-10-27 13:19:55,925 f:tester.py       l:192  c:sdcm.tester          p:ERROR > Traceback (most recent call last):
< t:2024-10-27 13:19:55,925 f:tester.py       l:192  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 185, in wrapper
< t:2024-10-27 13:19:55,925 f:tester.py       l:192  c:sdcm.tester          p:ERROR >     return method(*args, **kwargs)
< t:2024-10-27 13:19:55,925 f:tester.py       l:192  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 121, in inner
< t:2024-10-27 13:19:55,925 f:tester.py       l:192  c:sdcm.tester          p:ERROR >     res = func(*args, **kwargs)
< t:2024-10-27 13:19:55,925 f:tester.py       l:192  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 952, in setUp
< t:2024-10-27 13:19:55,925 f:tester.py       l:192  c:sdcm.tester          p:ERROR >     self.init_resources()
< t:2024-10-27 13:19:55,925 f:tester.py       l:192  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 1904, in init_resources
< t:2024-10-27 13:19:55,925 f:tester.py       l:192  c:sdcm.tester          p:ERROR >     self.get_cluster_aws(loader_info=loader_info, db_info=db_info,
< t:2024-10-27 13:19:55,925 f:tester.py       l:192  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 1505, in get_cluster_aws
< t:2024-10-27 13:19:55,925 f:tester.py       l:192  c:sdcm.tester          p:ERROR >     self.monitors = MonitorSetAWS(
< t:2024-10-27 13:19:55,925 f:tester.py       l:192  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster_aws.py", line 1081, in __init__
< t:2024-10-27 13:19:55,925 f:tester.py       l:192  c:sdcm.tester          p:ERROR >     AWSCluster.__init__(self,
< t:2024-10-27 13:19:55,925 f:tester.py       l:192  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster_aws.py", line 112, in __init__
< t:2024-10-27 13:19:55,925 f:tester.py       l:192  c:sdcm.tester          p:ERROR >     super().__init__(cluster_uuid=cluster_uuid,
< t:2024-10-27 13:19:55,925 f:tester.py       l:192  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3256, in __init__
< t:2024-10-27 13:19:55,925 f:tester.py       l:192  c:sdcm.tester          p:ERROR >     self.add_nodes(nodes_per_az[az_index], rack=rack, enable_auto_bootstrap=self.auto_bootstrap)
< t:2024-10-27 13:19:55,925 f:tester.py       l:192  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster_aws.py", line 405, in add_nodes
< t:2024-10-27 13:19:55,925 f:tester.py       l:192  c:sdcm.tester          p:ERROR >     instances.extend(self._create_or_find_instances(
< t:2024-10-27 13:19:55,925 f:tester.py       l:192  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster_aws.py", line 381, in _create_or_find_instances
< t:2024-10-27 13:19:55,925 f:tester.py       l:192  c:sdcm.tester          p:ERROR >     return self._create_instances(count, ec2_user_data, dc_idx, az_idx, instance_type=instance_type)
< t:2024-10-27 13:19:55,925 f:tester.py       l:192  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster_aws.py", line 234, in _create_instances
< t:2024-10-27 13:19:55,925 f:tester.py       l:192  c:sdcm.tester          p:ERROR >     instances = self._create_on_demand_instances(count, interfaces, ec2_user_data, dc_idx,
< t:2024-10-27 13:19:55,925 f:tester.py       l:192  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster_aws.py", line 161, in _create_on_demand_instances
< t:2024-10-27 13:19:55,925 f:tester.py       l:192  c:sdcm.tester          p:ERROR >     instances = self._ec2_services[dc_idx].create_instances(**params)
< t:2024-10-27 13:19:55,925 f:tester.py       l:192  c:sdcm.tester          p:ERROR >   File "/usr/local/lib/python3.10/site-packages/boto3/resources/factory.py", line 580, in do_action
< t:2024-10-27 13:19:55,925 f:tester.py       l:192  c:sdcm.tester          p:ERROR >     response = action(self, *args, **kwargs)
< t:2024-10-27 13:19:55,925 f:tester.py       l:192  c:sdcm.tester          p:ERROR >   File "/usr/local/lib/python3.10/site-packages/boto3/resources/action.py", line 88, in __call__
< t:2024-10-27 13:19:55,925 f:tester.py       l:192  c:sdcm.tester          p:ERROR >     response = getattr(parent.meta.client, operation_name)(*args, **params)
< t:2024-10-27 13:19:55,925 f:tester.py       l:192  c:sdcm.tester          p:ERROR >   File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 534, in _api_call
< t:2024-10-27 13:19:55,925 f:tester.py       l:192  c:sdcm.tester          p:ERROR >     return self._make_api_call(operation_name, kwargs)
< t:2024-10-27 13:19:55,925 f:tester.py       l:192  c:sdcm.tester          p:ERROR >   File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 976, in _make_api_call
< t:2024-10-27 13:19:55,925 f:tester.py       l:192  c:sdcm.tester          p:ERROR >     raise error_class(parsed_response, operation_name)
< t:2024-10-27 13:19:55,925 f:tester.py       l:192  c:sdcm.tester          p:ERROR > botocore.exceptions.ClientError: An error occurred (InvalidParameterCombination) when calling the RunInstances operation: Cluster placement groups are not supported by the 't3.large' instance type. Specify a supported instance type or change the placement group strategy, and try again.
```

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Cluster size: 6 nodes (i3en.2xlarge)

Scylla Nodes used in this run:
- perf-latency-upgrade-ubuntu-db-node-a22c015f-6 (34.254.177.51 | 10.4.4.91) (shards: -1)
- perf-latency-upgrade-ubuntu-db-node-a22c015f-5 (18.201.79.96 | 10.4.6.25) (shards: -1)
- perf-latency-upgrade-ubuntu-db-node-a22c015f-4 (3.253.245.69 | 10.4.6.63) (shards: -1)
- perf-latency-upgrade-ubuntu-db-node-a22c015f-3 (34.254.157.36 | 10.4.6.53) (shards: -1)
- perf-latency-upgrade-ubuntu-db-node-a22c015f-2 (54.78.112.155 | 10.4.7.227) (shards: -1)
- perf-latency-upgrade-ubuntu-db-node-a22c015f-1 (34.244.64.64 | 10.4.6.48) (shards: -1)

OS / Image: `ami-0e3b0cb94b0c86638` (aws: undefined_region)

Test: `scylla-master-perf-regression-latency-650gb-during-rolling-upgrade`
Test id: `a22c015f-57fb-4b93-8938-7205131d1ec2`
Test name: `scylla-master/perf-regression/scylla-master-perf-regression-latency-650gb-during-rolling-upgrade`
Test method: `performance_regression_test.PerformanceRegressionUpgradeTest.test_latency_read_with_upgrade`
Test config file(s):

- [perf-regression-latency-650gb-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/0e7989b52d19f68dd31b2cfb3a2c9956625856b9/test-cases/performance/perf-regression-latency-650gb-upgrade.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor a22c015f-57fb-4b93-8938-7205131d1ec2`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=a22c015f-57fb-4b93-8938-7205131d1ec2)
- Show all stored logs command: `$ hydra investigate show-logs a22c015f-57fb-4b93-8938-7205131d1ec2`

## Logs:
- **db-cluster-a22c015f.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a22c015f-57fb-4b93-8938-7205131d1ec2/20241027_132058/db-cluster-a22c015f.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a22c015f-57fb-4b93-8938-7205131d1ec2/20241027_132058/db-cluster-a22c015f.tar.gz)
- **sct-runner-events-a22c015f.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a22c015f-57fb-4b93-8938-7205131d1ec2/20241027_132058/sct-runner-events-a22c015f.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a22c015f-57fb-4b93-8938-7205131d1ec2/20241027_132058/sct-runner-events-a22c015f.tar.gz)
- **sct-a22c015f.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a22c015f-57fb-4b93-8938-7205131d1ec2/20241027_132058/sct-a22c015f.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a22c015f-57fb-4b93-8938-7205131d1ec2/20241027_132058/sct-a22c015f.log.tar.gz)
- **loader-set-a22c015f.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a22c015f-57fb-4b93-8938-7205131d1ec2/20241027_132058/loader-set-a22c015f.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a22c015f-57fb-4b93-8938-7205131d1ec2/20241027_132058/loader-set-a22c015f.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/perf-regression/job/scylla-master-perf-regression-latency-650gb-during-rolling-upgrade/24/)
[Argus](https://argus.scylladb.com/test/3ec1793e-7b3f-4b15-b10f-8dab7bb83cde/runs?additionalRuns[]=a22c015f-57fb-4b93-8938-7205131d1ec2)
</details>

**Comment by soyacz** [comment]
I think idea is to fail whole test if provision step fails. @fruch I'm right? fix then would be stopping CI from next steps (cleanup only) in that case.

**Comment by juliayakovlev** [comment]
> I think idea is to fail whole test if provision step fails. [@fruch](https://github.com/fruch) I'm right? fix then would be stopping CI from next steps (cleanup only) in that case.

The monitor instance only was failed. I am not familiar with placement groups, but why monitor instance can not be provisioned during run stage?

**Comment by fruch** [comment]
@soyacz 

let's fix it for the perf pipeline, to fail the pipeline completely if provision step failed 
then we'll consider if we want the same for other pipelines.
