### ISSUE TITLE
Nodetool commands can sometimes be incorrectly decoded

### ISSUE THREAD

**Issue by pehala** [scylladb/scylla-cluster-tests#9174]
Nodetool commands can throw `UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 3047: invalid start byte`. Since we do a lot of processing, it could very well be error on our part. Happened during `ToggleAuditSyslog` nemesis

Recent changes: https://github.com/soyacz/scylla-cluster-tests/commit/81f48ad53cab1b1b7edf88c8e0b4da4ab07b468f

Stacktrace:
```
2024-11-08 01:06:34.479: (DisruptionEvent Severity.ERROR) period_type=end event_id=f8a6a20b-9df8-4c0a-a528-67e7164fe047 duration=5m54s: nemesis_name=ToggleAuditSyslog target_node=Node longevity-10gb-3h-master-db-node-fe1a03b7-eastus-1 [None | 10.0.0.5] errors='utf-8' codec can't decode byte 0x80 in position 3047: invalid start byte
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 5354, in wrapper
result = method(*args[1:], **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 5062, in disrupt_toggle_audit_syslog
self._disrupt_toggle_audit(store="syslog")
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 5114, in _disrupt_toggle_audit
rows = audit.get_audit_log(from_datetime=audit_start, category="DML", limit_rows=1500)
File "/home/ubuntu/scylla-cluster-tests/sdcm/audit.py", line 220, in get_audit_log
return reader.read(from_datetime=from_datetime, category=category, operation=operation, limit_rows=limit_rows)
File "/home/ubuntu/scylla-cluster-tests/sdcm/audit.py", line 164, in read
rows += list(get_audit_log_rows(node,
File "/home/ubuntu/scylla-cluster-tests/sdcm/audit.py", line 120, in get_audit_log_rows
for line in log_file:
File "/usr/local/lib/python3.10/codecs.py", line 322, in decode
(result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 3047: invalid start byte
```

**Comment by soyacz** [comment]
@pehala wrong referenced commit, should be https://github.com/scylladb/scylla-cluster-tests/commit/a09dd1ecf657584e96e6c7003e1560cbb3443645 and refers to ssh2 lib.

Remoter change it's not related here. Issues this test faced is with new scylla log lines.
See e.g. line 5480 from messages.log of db node 1:
```
2024-11-08T01:03:38.956+00:00 longevity-10gb-3h-master-db-node-fe1a03b7-eastus-1     !INFO | scylla[6487]: `<?
```
There's more lines like such, and log follower can't handle that.
cc @fruch

**Comment by soyacz** [comment]
More examples:
```
2024-11-08T01:01:21.666+00:00 longevity-10gb-3h-master-db-node-fe1a03b7-eastus-1     !INFO | scylla[6487]:  [shard 1:main] migration_manager - Schema agreement check passed.
2024-11-08T01:01:21.666+00:00 longevity-10gb-3h-master-db-node-fe1a03b7-eastus-1     !INFO | scylla[6487]: ?x
2024-11-08T01:01:21.666+00:00 longevity-10gb-3h-master-db-node-fe1a03b7-eastus-1     !INFO | scylla[6487]:  [shard 0:sl:d] cql_server_controller - Starting listening for CQL clients on 10.0.0.5:9042 (unencrypted, non-shard-aware)
[...]
2024-11-08T01:03:38.418+00:00 longevity-10gb-3h-master-db-node-fe1a03b7-eastus-1     !INFO | scylla[6487]:  [shard 1:comp] compaction - [Compact keyspace1.standard1 4975aea0-9d6d-11ef-8cc6-3b65d46080cf] Compacting [/var/lib/scylla/data/keyspace1/standard1-e0907d609d6811ef94818899c18e7ee4/me-3gl2_02y0_3mj2o252gig65hwmvj-big-Data.db:level=0:origin=memtable,/var/lib/scylla/data/keyspace1/standard1-e0907d609d6811ef94818899c18e7ee4/me-3gl2_02w8_0lnbk252gig65hwmvj-big-Data.db:level=0:origin=compaction]
2024-11-08T01:03:38.956+00:00 longevity-10gb-3h-master-db-node-fe1a03b7-eastus-1     !INFO | scylla[6487]: `<?
2024-11-08T01:03:38.956+00:00 longevity-10gb-3h-master-db-node-fe1a03b7-eastus-1   !NOTICE | scylla-audit[6487]: "10.0.0.5:0", "DML", "ONE", "false", "audit_keyspace", "UPDATE "standard1" SET "C0" = ? WHERE KEY=?", "10.0.0.11:0", "standard1", "anonymous"
2024-11-08T01:03:38.956+00:00 longevity-10gb-3h-master-db-node-fe1a03b7-eastus-1     !INFO | scylla[6487]: `<?
2024-11-08T01:03:38.956+00:00 longevity-10gb-3h-master-db-node-fe1a03b7-eastus-1   !NOTICE | scylla-audit[6487]: "10.0.0.5:0", "DML", "ONE", "false", "audit_keyspace", "UPDATE "standard1" SET "C0" = ? WHERE KEY=?", "10.0.0.11:0", "standard1", "anonymous"

```

**Comment by soyacz** [comment]
somehow we don't get proper logs from db upon collect logs. So I can't say it's something that syslogng introducing or scylla started to print these. Need to investigate why we don't collect logs.

**Comment by soyacz** [comment]
found culprit commit for missing logs: https://github.com/scylladb/scylla-cluster-tests/issues/9178

**Comment by fruch** [comment]
we see it first in:
https://argus.scylladb.com/tests/scylla-cluster-tests/86db2ab7-c07b-47f1-acee-0edf7ebfa8d4

Scylla version: 2024.3.0~dev-20241105.d4d8b612c993

**Comment by soyacz** [comment]
Ok, now with logs I can see how it looks without syslong transformations. Issue created: https://github.com/scylladb/scylla-enterprise/issues/4916. Closing this one as it's not related to SCT.
