### ISSUE TITLE
[Azure] Timing out on pinging scylla-manger-agent

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#9229]
## Issue description

- [ ] This issue is a regression.
- [x] It is unknown if this issue is a regression.

ping for manager port is stuck for ~5min, and fails with return code of 000:
```
2024-10-14 23:57:26.027: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=3f91d078-e113-442c-a378-b346329dd4b8, source=ArtifactsTest.SetUp()
exception=[Node artifacts-azure-image-jenkins-db-node-d52e93b0-eastus-1 [52.170.196.250 | 10.0.0.4]] NodeSetupFailed: Wait for: artifacts-azure-image-jenkins-db-node-d52e93b0-eastus-1: Waiting for manager agent to be up: timeout - 180 seconds - expired
Traceback (most recent call last):
File "/tmp/jenkins/workspace/scylla-master/artifacts/artifacts-azure-image-test/scylla-cluster-tests/sdcm/wait.py", line 70, in wait_for
res = retry(func, **kwargs)
File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 404, in __call__
do = self.iter(retry_state=retry_state)
File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 360, in iter
raise retry_exc.reraise()
File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 194, in reraise
raise self
tenacity.RetryError: RetryError[<Future at 0x7c54b351d180 state=finished returned bool>]
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/tmp/jenkins/workspace/scylla-master/artifacts/artifacts-azure-image-test/scylla-cluster-tests/sdcm/cluster.py", line 3899, in node_startup
cl_inst.node_startup(_node, **setup_kwargs)
File "/tmp/jenkins/workspace/scylla-master/artifacts/artifacts-azure-image-test/scylla-cluster-tests/sdcm/cluster.py", line 4774, in node_startup
node.wait_manager_agent_up()
File "/tmp/jenkins/workspace/scylla-master/artifacts/artifacts-azure-image-test/scylla-cluster-tests/sdcm/cluster.py", line 1386, in wait_manager_agent_up
wait.wait_for(func=self.is_manager_agent_up, step=10, text=text, timeout=timeout, throw_exc=True)
File "/tmp/jenkins/workspace/scylla-master/artifacts/artifacts-azure-image-test/scylla-cluster-tests/sdcm/wait.py", line 86, in wait_for
raise raising_exc from ex
sdcm.exceptions.WaitForTimeoutError: Wait for: artifacts-azure-image-jenkins-db-node-d52e93b0-eastus-1: Waiting for manager agent to be up: timeout - 180 seconds - expired
```

since the time it take to fail one iteration more then timeout, there no 2nd attempt: 
```
< t:2024-11-16 00:29:42,987 f:remote_base.py  l:560  c:RemoteLibSSH2CmdRunner p:DEBUG > <172.172.140.133>: Running command "curl -k --write-out "%{http_code}
< t:2024-11-16 00:29:42,987 f:remote_base.py  l:560  c:RemoteLibSSH2CmdRunner p:DEBUG > " --silent --output /dev/null "https://172.172.140.133:10001/ping""...

< t:2024-11-16 00:34:43,871 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <172.172.140.133>: 000
< t:2024-11-16 00:34:43,871 f:cluster.py      l:1385 c:sdcm.cluster         p:DEBUG > curl with scylla_listen_address stdout: 000

< t:2024-11-16 00:34:43,872 f:wait.py         l:79   c:sdcm.wait            p:ERROR > Wait for: artifacts-azure-image-jenkins-db-node-b635013f-eastus-1: Waiting for manager agent to be up: timeout - 180 seconds - expired
< t:2024-11-16 00:34:43,872 f:wait.py         l:83   c:sdcm.wait            p:ERROR > last error: RetryError(<Future at 0x79b589bc0280 state=finished returned bool>)
```

## Impact

test can finish node setup

## How frequently does it reproduce?

identified 2 time this happened on Azure artifact test

## Installation details

Cluster size: 1 nodes (Standard_L8s_v3)

Scylla Nodes used in this run:
- artifacts-azure-image-jenkins-db-node-b635013f-eastus-1 (172.172.140.133 | 172.172.140.133) (shards: 7)

OS / Image: `/subscriptions/6c268694-47ab-43ab-b306-3c5514bc4112/resourceGroups/scylla-images/providers/Microsoft.Compute/images/scylla-6.3.0-dev-x86_64-2024-11-16T02-06-29` (azure: undefined_region)

Test: `artifacts-azure-image-test`
Test id: `b635013f-c9cd-4fea-87d1-3b0338420152`
Test name: `scylla-master/artifacts/artifacts-azure-image-test`
Test method: `artifacts_test`
Test config file(s):

- [azure-image.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/3c880d356e617d2de7b7ecaa53ab4d00c7061fd1/test-cases/artifacts/azure-image.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor b635013f-c9cd-4fea-87d1-3b0338420152`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=b635013f-c9cd-4fea-87d1-3b0338420152)
- Show all stored logs command: `$ hydra investigate show-logs b635013f-c9cd-4fea-87d1-3b0338420152`

## Logs:
- **db-cluster-b635013f.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b635013f-c9cd-4fea-87d1-3b0338420152/20241116_003511/db-cluster-b635013f.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b635013f-c9cd-4fea-87d1-3b0338420152/20241116_003511/db-cluster-b635013f.tar.gz)
- **sct-runner-events-b635013f.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b635013f-c9cd-4fea-87d1-3b0338420152/20241116_003511/sct-runner-events-b635013f.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b635013f-c9cd-4fea-87d1-3b0338420152/20241116_003511/sct-runner-events-b635013f.tar.gz)
- **sct-b635013f.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b635013f-c9cd-4fea-87d1-3b0338420152/20241116_003511/sct-b635013f.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b635013f-c9cd-4fea-87d1-3b0338420152/20241116_003511/sct-b635013f.log.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-azure-image-test/679/)
[Argus](https://argus.scylladb.com/test/49d66dac-199a-4027-89cf-950c8e553774/runs?additionalRuns[]=b635013f-c9cd-4fea-87d1-3b0338420152)
</details>

**Comment by fruch** [comment]
@soyacz 

any thoughts ? what we might be missing ? or what debug information can be added to help ?

**Comment by fruch** [comment]
it's been 3 months no once encounter this issue, closing for now
