### ISSUE TITLE
Collecting corrupted sstables for node failed

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-cluster-tests#9304]
## Packages

Scylla version: `6.3.0~dev-20241119.733a4f94c7b2` with build-id `89a16d00ef82b3c15eb73e944afc60f15c478452`
Kernel Version: `6.8.0-1019-aws`

## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

Collecting corrupted sstables for node failed:
```
13:02:52  Start collect logs for cluster corrupted-sstables
13:02:52  Collecting sstables for node perf-latency-nemesis-ubuntu-db-node-29a73f9d-3...
13:02:52  < t:2024-11-20 11:02:50,989 f:remote_libssh_cmd_runner.py l:66   c:RemoteLibSSH2CmdRunner p:ERROR > Failed to run a command due to exception!
13:02:52  < t:2024-11-20 11:02:50,989 f:remote_libssh_cmd_runner.py l:66   c:RemoteLibSSH2CmdRunner p:ERROR > 
13:02:52  < t:2024-11-20 11:02:50,989 f:remote_libssh_cmd_runner.py l:66   c:RemoteLibSSH2CmdRunner p:ERROR > Command: 'docker ps -a -q | xargs docker rm -f'
13:02:52  < t:2024-11-20 11:02:50,989 f:remote_libssh_cmd_runner.py l:66   c:RemoteLibSSH2CmdRunner p:ERROR > 
13:02:52  < t:2024-11-20 11:02:50,989 f:remote_libssh_cmd_runner.py l:66   c:RemoteLibSSH2CmdRunner p:ERROR > Stdout:
13:02:52  < t:2024-11-20 11:02:50,989 f:remote_libssh_cmd_runner.py l:66   c:RemoteLibSSH2CmdRunner p:ERROR > 
13:02:52  < t:2024-11-20 11:02:50,989 f:remote_libssh_cmd_runner.py l:66   c:RemoteLibSSH2CmdRunner p:ERROR > 
13:02:52  < t:2024-11-20 11:02:50,989 f:remote_libssh_cmd_runner.py l:66   c:RemoteLibSSH2CmdRunner p:ERROR > 
13:02:52  < t:2024-11-20 11:02:50,989 f:remote_libssh_cmd_runner.py l:66   c:RemoteLibSSH2CmdRunner p:ERROR > Stderr:
13:02:52  < t:2024-11-20 11:02:50,989 f:remote_libssh_cmd_runner.py l:66   c:RemoteLibSSH2CmdRunner p:ERROR > 
13:02:52  < t:2024-11-20 11:02:50,989 f:remote_libssh_cmd_runner.py l:66   c:RemoteLibSSH2CmdRunner p:ERROR > 
13:02:52  < t:2024-11-20 11:02:50,989 f:remote_libssh_cmd_runner.py l:66   c:RemoteLibSSH2CmdRunner p:ERROR > 
13:02:52  < t:2024-11-20 11:02:50,989 f:remote_libssh_cmd_runner.py l:66   c:RemoteLibSSH2CmdRunner p:ERROR > Exception:  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 594, in run
13:02:52  < t:2024-11-20 11:02:50,989 f:remote_libssh_cmd_runner.py l:66   c:RemoteLibSSH2CmdRunner p:ERROR >     channel = self.open_channel()
13:02:52  < t:2024-11-20 11:02:50,989 f:remote_libssh_cmd_runner.py l:66   c:RemoteLibSSH2CmdRunner p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 693, in open_channel
13:02:52  < t:2024-11-20 11:02:50,989 f:remote_libssh_cmd_runner.py l:66   c:RemoteLibSSH2CmdRunner p:ERROR >     raise OpenChannelTimeout(f'Failed to open channel in {timeout} seconds')
13:02:52  < t:2024-11-20 11:02:50,989 f:remote_libssh_cmd_runner.py l:66   c:RemoteLibSSH2CmdRunner p:ERROR > 
13:02:52  < t:2024-11-20 11:02:50,989 f:remote_libssh_cmd_runner.py l:66   c:RemoteLibSSH2CmdRunner p:ERROR > Failed to open channel in 15 seconds
13:02:56  < t:2024-11-20 11:02:56,574 f:cluster.py      l:5248 c:sdcm.cluster         p:INFO  > Cluster perf-latency-nemesis-ubuntu-loader-set-9bc07447 (AMI: ['ami-09eac484a78b27c96'] Type: c5.2xlarge): Killed docker loader on node: perf-latency-nemesis-ubuntu-loader-node-9bc07447-3
13:03:14  < t:2024-11-20 11:03:13,189 f:remote_libssh_cmd_runner.py l:66   c:RemoteLibSSH2CmdRunner p:ERROR > Failed to run a command due to exception!
13:03:14  < t:2024-11-20 11:03:13,189 f:remote_libssh_cmd_runner.py l:66   c:RemoteLibSSH2CmdRunner p:ERROR > 
13:03:14  < t:2024-11-20 11:03:13,189 f:remote_libssh_cmd_runner.py l:66   c:RemoteLibSSH2CmdRunner p:ERROR > Command: 'docker ps -a -q | xargs docker rm -f'
13:03:14  < t:2024-11-20 11:03:13,189 f:remote_libssh_cmd_runner.py l:66   c:RemoteLibSSH2CmdRunner p:ERROR > 
13:03:14  < t:2024-11-20 11:03:13,189 f:remote_libssh_cmd_runner.py l:66   c:RemoteLibSSH2CmdRunner p:ERROR > Stdout:
13:03:14  < t:2024-11-20 11:03:13,189 f:remote_libssh_cmd_runner.py l:66   c:RemoteLibSSH2CmdRunner p:ERROR > 
13:03:14  < t:2024-11-20 11:03:13,189 f:remote_libssh_cmd_runner.py l:66   c:RemoteLibSSH2CmdRunner p:ERROR > 
13:03:14  < t:2024-11-20 11:03:13,189 f:remote_libssh_cmd_runner.py l:66   c:RemoteLibSSH2CmdRunner p:ERROR > 
13:03:14  < t:2024-11-20 11:03:13,189 f:remote_libssh_cmd_runner.py l:66   c:RemoteLibSSH2CmdRunner p:ERROR > Stderr:
13:03:14  < t:2024-11-20 11:03:13,189 f:remote_libssh_cmd_runner.py l:66   c:RemoteLibSSH2CmdRunner p:ERROR > 
13:03:14  < t:2024-11-20 11:03:13,189 f:remote_libssh_cmd_runner.py l:66   c:RemoteLibSSH2CmdRunner p:ERROR > 
13:03:14  < t:2024-11-20 11:03:13,189 f:remote_libssh_cmd_runner.py l:66   c:RemoteLibSSH2CmdRunner p:ERROR > 
13:03:14  < t:2024-11-20 11:03:13,189 f:remote_libssh_cmd_runner.py l:66   c:RemoteLibSSH2CmdRunner p:ERROR > Exception:  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 594, in run
13:03:14  < t:2024-11-20 11:03:13,189 f:remote_libssh_cmd_runner.py l:66   c:RemoteLibSSH2CmdRunner p:ERROR >     channel = self.open_channel()
13:03:14  < t:2024-11-20 11:03:13,189 f:remote_libssh_cmd_runner.py l:66   c:RemoteLibSSH2CmdRunner p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 693, in open_channel
13:03:14  < t:2024-11-20 11:03:13,189 f:remote_libssh_cmd_runner.py l:66   c:RemoteLibSSH2CmdRunner p:ERROR >     raise OpenChannelTimeout(f'Failed to open channel in {timeout} seconds')
13:03:14  < t:2024-11-20 11:03:13,189 f:remote_libssh_cmd_runner.py l:66   c:RemoteLibSSH2CmdRunner p:ERROR > 
13:03:14  < t:2024-11-20 11:03:13,189 f:remote_libssh_cmd_runner.py l:66   c:RemoteLibSSH2CmdRunner p:ERROR > Failed to open channel in 15 seconds
```

And later
```
 Collecting sstables for node perf-latency-nemesis-ubuntu-db-node-9bc07447-2...
14:31:30  Cancelling nested steps due to timeout
14:31:30  Sending interrupt signal to process
14:31:35  Cancelling nested steps due to timeout
14:31:35  Sending interrupt signal to process
14:31:39  time="2024-11-20T12:31:30Z" level=error msg="error waiting for container: "
```

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Cluster size: 3 nodes (i3en.2xlarge)

Scylla Nodes used in this run:
- perf-latency-nemesis-ubuntu-db-node-2805dd59-3 (34.250.233.74 | 10.4.11.251) (shards: 7)
- perf-latency-nemesis-ubuntu-db-node-2805dd59-2 (54.74.124.94 | 10.4.8.78) (shards: 7)
- perf-latency-nemesis-ubuntu-db-node-2805dd59-1 (3.248.184.8 | 10.4.10.113) (shards: 7)

OS / Image: `ami-0d782b5935da36d59` (aws: undefined_region)

Test: `scylla-master-perf-regression-latency-650gb-with-nemesis`
Test id: `2805dd59-bc75-4611-bf02-dd3395f6dc57`
Test name: `scylla-master/perf-regression/scylla-master-perf-regression-latency-650gb-with-nemesis`
Test method: `performance_regression_test.PerformanceRegressionTest.test_latency_write_with_nemesis`
Test config file(s):

- [perf-regression-latency-650gb-with-nemesis.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/c124bfd47fdfcd23fab85a2fc1ddd011650b2e3f/test-cases/performance/perf-regression-latency-650gb-with-nemesis.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 2805dd59-bc75-4611-bf02-dd3395f6dc57`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=2805dd59-bc75-4611-bf02-dd3395f6dc57)
- Show all stored logs command: `$ hydra investigate show-logs 2805dd59-bc75-4611-bf02-dd3395f6dc57`

## Logs:
*No logs captured during this run.*

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/perf-regression/job/scylla-master-perf-regression-latency-650gb-with-nemesis/30/)
[Argus](https://argus.scylladb.com/test/4f088858-cbf2-4984-9d44-d319c207f521/runs?additionalRuns[]=2805dd59-bc75-4611-bf02-dd3395f6dc57)
</details>

**Comment by fruch** [comment]
@soyacz 

can you take a look at this one, it's a bit alarming that the machinery to collect malformed sstable is getting stuck...  (we can loose them)

**Comment by soyacz** [comment]
from log on sct-runner:
```
Collecting sstables for node perf-latency-nemesis-ubuntu-db-node-29a73f9d-3...
failed collecting malformed sstables:
An error occurred (InvalidArgument) when calling the UploadPart operation: Part number must be an integer between 1 and 10000, inclusive
Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/logcollector.py", line 1280, in collect_logs
    s3_link = upload_remote_files_directly_to_s3(
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/s3_remote_uploader.py", line 82, in upload_remote_files_directly_to_s3
    s3.upload_fileobj(chan_response, s3_bucket, s3_key, ExtraArgs=extra_args)
  File "/usr/local/lib/python3.10/site-packages/boto3/s3/inject.py", line 636, in upload_fileobj
    return future.result()
  File "/usr/local/lib/python3.10/site-packages/s3transfer/futures.py", line 103, in result
    return self._coordinator.result()
  File "/usr/local/lib/python3.10/site-packages/s3transfer/futures.py", line 266, in result
    raise self._exception
  File "/usr/local/lib/python3.10/site-packages/s3transfer/tasks.py", line 139, in __call__
    return self._execute_main(kwargs)
  File "/usr/local/lib/python3.10/site-packages/s3transfer/tasks.py", line 162, in _execute_main
    return_value = self._main(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/s3transfer/upload.py", line 787, in _main
    response = client.upload_part(
  File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 534, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 976, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidArgument) when calling the UploadPart operation: Part number must be an integer between 1 and 10000, inclusive
There are no logs collected for corrupted-sstables
Start collect logs for cluster jepsen-data
```

**Comment by fruch** [comment]
meaning the file was too big, and our chuck size was too small ?

**Comment by soyacz** [comment]
> meaning the file was too big, and our chuck size was too small ?

I don't know yet - i just quickly got into sct runner to get this logs.
Another possible issue is that `boto` client changed and does not work anymore with SCT like that - I'll verify it.
