### ISSUE TITLE
A node decommission of GrowShrinkCluster nemesis takes longer than SCT soft timeout of 2 hours: "operation 'DECOMMISSION' took 7596.210433244705s and soft-timeout was set to 7200s"

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#9308]
The `disrupt_grow_shrink_cluster` ran 3 times in the below longevity, where one of these experienced a soft timeout of 2 hours for node decommission.

So this may be considered as a potential scylla perf regression issue, but not sure it's easy to "prove"/confirm that.

The logs shows the following node-decommission duration during this nemesis:

ShrinkCluster started:
```
2024-11-19 05:50:22.657: (InfoEvent Severity.NORMAL) period_type=not-set event_id=ea90b395-ea9f-4a29-9cbf-cbaf567cf6a1: message=StartEvent - ShrinkCluster started decommissioning a node Node alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-4 [52.212.181.70 | 10.4.2.73]
```
duration=1h55m18s:
```
2024-11-19 05:50:24.005: (NodetoolEvent Severity.NORMAL) period_type=begin event_id=f54231f1-3eda-4cd4-ad90-12d5979e51ac: nodetool_command=decommission node=alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-4
2024-11-19 07:45:42.582: (NodetoolEvent Severity.NORMAL) period_type=end event_id=f54231f1-3eda-4cd4-ad90-12d5979e51ac duration=1h55m18s: nodetool_command=decommission node=alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-4
```
nemesis finish:
```
2024-11-19 07:48:19.727: (InfoEvent Severity.NORMAL) period_type=not-set event_id=828d784f-8172-499c-801d-b5eef94d225e: message=FinishEvent - ShrinkCluster has done decommissioning a node Node alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-4 [52.212.181.70 | 10.4.2.73]
2024-11-19 07:49:50.539: (DisruptionEvent Severity.NORMAL) period_type=end event_id=5d218f73-baf5-4d82-a1ec-21e27f33e5b7 duration=4h42m23s: nemesis_name=GrowShrinkCluster target_node=Node alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-7 [3.252.196.238 | 10.4.2.72]
```
second GrowShrinkCluster:
```
2024-11-19 14:45:26.464: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=b8b5dd86-31a4-4403-9f7f-60922f7d7ffa: nemesis_name=GrowShrinkCluster target_node=Node alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-8 [34.253.221.34 | 10.4.1.102]
2024-11-19 16:33:28.151: (InfoEvent Severity.NORMAL) period_type=not-set event_id=d36957cd-cf89-4789-bd78-47f2dcbf67a0: message=Start shrink cluster by 1 nodes
2024-11-19 16:33:28.172: (InfoEvent Severity.NORMAL) period_type=not-set event_id=e91da522-998f-4df7-8a3a-88669f7b6c5f: message=StartEvent - ShrinkCluster started decommissioning 1 nodes
2024-11-19 16:33:28.180: (InfoEvent Severity.NORMAL) period_type=not-set event_id=b469949e-652a-4cd9-ae6b-ce762f5a7b87: message=StartEvent - ShrinkCluster started decommissioning a node Node alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-7 [3.252.196.238 | 10.4.2.72]
```
node deommission exceeds the 2 hours soft timeout (duration=2h6m36s):
```
2024-11-19 16:33:29.854: (NodetoolEvent Severity.NORMAL) period_type=begin event_id=4dc74f1b-4288-4591-ac42-d1f201389dbd: nodetool_command=decommission node=alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-7
2024-11-19 18:40:06.064: (NodetoolEvent Severity.NORMAL) period_type=end event_id=4dc74f1b-4288-4591-ac42-d1f201389dbd duration=2h6m36s: nodetool_command=decommission node=alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-7
2024-11-19 18:40:06.065: (SoftTimeoutEvent Severity.ERROR) period_type=one-time event_id=6d17cd8c-18cb-4f28-9d8e-3cfadb037448 during_nemesis=GrowShrinkCluster, source=SoftTimeout message=operation 'DECOMMISSION' took 7596.210433244705s and soft-timeout was set to 7200s
2024-11-19 18:43:07.268: (InfoEvent Severity.NORMAL) period_type=not-set event_id=63b9e220-1a15-482e-bfe6-6cce8ffca3f7: message=FinishEvent - ShrinkCluster has done decommissioning a node Node alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-7 [3.252.196.238 | 10.4.2.72]
2024-11-19 18:43:31.085: (InfoEvent Severity.NORMAL) period_type=not-set event_id=b1af9f61-3a58-4b6b-a3fe-23a74f9f3a45: message=FinishEvent - ShrinkCluster has done decommissioning 1 nodes
```
nemesis finish:
```
2024-11-19 18:44:40.052: (InfoEvent Severity.NORMAL) period_type=not-set event_id=886e18da-fb64-46aa-81f0-96ab320629ca: message=Cluster shrink finished. Current number of nodes 4
2024-11-19 18:44:40.785: (DisruptionEvent Severity.NORMAL) period_type=end event_id=b8b5dd86-31a4-4403-9f7f-60922f7d7ffa duration=3h59m14s: nemesis_name=GrowShrinkCluster target_node=Node alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-8 [34.253.221.34 | 10.4.1.102]
```
3rd GrowShrinkCluster starts:
```
2024-11-19 19:12:56.850: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=60a4b371-3447-4889-8cb6-af59e8965a2c: nemesis_name=GrowShrinkCluster target_node=Node alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-3 [54.171.148.253 | 10.4.2.229]
2024-11-19 20:34:48.127: (InfoEvent Severity.NORMAL) period_type=not-set event_id=7f5967d3-5bcc-444d-8b7f-90d4ae7532bf: message=Start shrink cluster by 1 nodes
2024-11-19 20:34:48.145: (InfoEvent Severity.NORMAL) period_type=not-set event_id=c091046d-294f-44ac-b730-7f12ccf79a1e: message=StartEvent - ShrinkCluster started decommissioning 1 nodes
2024-11-19 20:34:48.152: (InfoEvent Severity.NORMAL) period_type=not-set event_id=071d614a-df05-4764-837d-36198235f73e: message=StartEvent - ShrinkCluster started decommissioning a node Node alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-8 [34.253.221.34 | 10.4.1.102]
```
Now decommission takes less time - duration=1h41m6s:
```
2024-11-19 20:34:49.245: (NodetoolEvent Severity.NORMAL) period_type=begin event_id=00d8c390-3d92-4469-a384-c6969f41f134: nodetool_command=decommission node=alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-8
2024-11-19 22:15:55.409: (NodetoolEvent Severity.NORMAL) period_type=end event_id=00d8c390-3d92-4469-a384-c6969f41f134 duration=1h41m6s: nodetool_command=decommission node=alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-8
```
nemesis finish:
```
2024-11-19 22:18:55.295: (InfoEvent Severity.NORMAL) period_type=not-set event_id=2543784f-e146-432c-8bbe-8926b65360ea: message=FinishEvent - ShrinkCluster has done decommissioning a node Node alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-8 [34.253.221.34 | 10.4.1.102]
2024-11-19 22:19:19.052: (InfoEvent Severity.NORMAL) period_type=not-set event_id=32783fb5-99a4-4f44-9ee0-03fa96d9ed16: message=FinishEvent - ShrinkCluster has done decommissioning 1 nodes
2024-11-19 22:20:24.140: (InfoEvent Severity.NORMAL) period_type=not-set event_id=8fda8ff5-a627-4b95-b800-44d9b8585e5b: message=Cluster shrink finished. Current number of nodes 4
2024-11-19 22:20:24.951: (DisruptionEvent Severity.NORMAL) period_type=end event_id=60a4b371-3447-4889-8cb6-af59e8965a2c duration=3h7m28s: nemesis_name=GrowShrinkCluster target_node=Node alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-3 [54.171.148.253 | 10.4.2.229]
```

Then a different nemesis of seed node decommission takes even less than te above:
```
2024-11-19 23:05:22.775: (NodetoolEvent Severity.NORMAL) period_type=begin event_id=89523787-801a-4fec-9268-564be3e454bb: nodetool_command=decommission node=alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-1
2024-11-20 00:28:12.860: (NodetoolEvent Severity.NORMAL) period_type=end event_id=89523787-801a-4fec-9268-564be3e454bb duration=1h22m50s: nodetool_command=decommission node=alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-1
```

So i'm really not sure what would be the expected timeout duration in this case.
I couldn't find any previous runs of this nemesis in this longevity.
We can consider increasing this soft timeout a bit, for the moment, following the durations of 1h55m18s and 2h6m36s.
@fruch , @soyacz can you please advise?

```

## Packages

Scylla version: `2024.2.0~rc4-20241117.c04983cb0342` with build-id `3f8c1af5b6163378931b6edfbf1daac3a57a30bd`





Kernel Version: `5.15.0-1072-aws`


## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

*Describe your issue in detail and steps it took to produce it.*

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Cluster size: 4 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
- alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-9 (52.209.26.149 | 10.4.1.217) (shards: 14)
- alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-8 (34.253.221.34 | 10.4.1.102) (shards: 14)
- alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-7 (54.246.72.183 | 10.4.2.72) (shards: 14)
- alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-6 (3.250.98.2 | 10.4.3.143) (shards: -1)
- alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-5 (3.249.243.17 | 10.4.3.245) (shards: 14)
- alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-4 (34.245.63.25 | 10.4.2.73) (shards: 14)
- alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-3 (54.171.148.253 | 10.4.2.229) (shards: 14)
- alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-2 (52.209.20.249 | 10.4.0.209) (shards: 14)
- alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-12 (54.171.11.176 | 10.4.2.83) (shards: 14)
- alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-11 (54.247.220.169 | 10.4.2.35) (shards: 14)
- alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-10 (3.253.104.23 | 10.4.2.64) (shards: 14)
- alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-1 (3.253.25.30 | 10.4.3.117) (shards: 14)


OS / Image: `ami-0c4defd1155c9848c` (aws: undefined_region)

Test: `longevity-alternator-1h-scan-12h-ttl-no-lwt-2h-grace-4loaders-sisyphus-test`
Test id: `7a3125fb-cb7d-4a42-8610-2c944e453de7`
Test name: `enterprise-2024.2/alternator_tablets/longevity-alternator-1h-scan-12h-ttl-no-lwt-2h-grace-4loaders-sisyphus-test`
Test method: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):

- [longevity-alternator-1h-scan-12h-ttl-no-lwt-2h-grace-4loaders-sisyphus.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/8672d338b2ce83acf6ab81b6be5f3d7f72b03ff4/test-cases/features/alternator-ttl/longevity-alternator-1h-scan-12h-ttl-no-lwt-2h-grace-4loaders-sisyphus.yaml)


<details>
<summary>
Logs and commands
</summary>


- Restore Monitor Stack command: `$ hydra investigate show-monitor 7a3125fb-cb7d-4a42-8610-2c944e453de7`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=7a3125fb-cb7d-4a42-8610-2c944e453de7)
- Show all stored logs command: `$ hydra investigate show-logs 7a3125fb-cb7d-4a42-8610-2c944e453de7`


## Logs:
- **alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-5** - [https://cloudius-jenkins-test.s3.amazonaws.com/7a3125fb-cb7d-4a42-8610-2c944e453de7/20241118_093203/alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-5-7a3125fb.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7a3125fb-cb7d-4a42-8610-2c944e453de7/20241118_093203/alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-5-7a3125fb.tar.gz)
- **alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-6** - [https://cloudius-jenkins-test.s3.amazonaws.com/7a3125fb-cb7d-4a42-8610-2c944e453de7/20241118_093203/alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-6-7a3125fb.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7a3125fb-cb7d-4a42-8610-2c944e453de7/20241118_093203/alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-6-7a3125fb.tar.gz)
- **alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-2** - [https://cloudius-jenkins-test.s3.amazonaws.com/7a3125fb-cb7d-4a42-8610-2c944e453de7/20241118_093203/alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-2-7a3125fb.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7a3125fb-cb7d-4a42-8610-2c944e453de7/20241118_093203/alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-2-7a3125fb.tar.gz)
- **alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-4** - [https://cloudius-jenkins-test.s3.amazonaws.com/7a3125fb-cb7d-4a42-8610-2c944e453de7/20241118_093203/alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-4-7a3125fb.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7a3125fb-cb7d-4a42-8610-2c944e453de7/20241118_093203/alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-4-7a3125fb.tar.gz)
- **alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-7** - [https://cloudius-jenkins-test.s3.amazonaws.com/7a3125fb-cb7d-4a42-8610-2c944e453de7/20241118_093203/alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-7-7a3125fb.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7a3125fb-cb7d-4a42-8610-2c944e453de7/20241118_093203/alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-7-7a3125fb.tar.gz)
- **alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-8** - [https://cloudius-jenkins-test.s3.amazonaws.com/7a3125fb-cb7d-4a42-8610-2c944e453de7/20241118_093203/alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-8-7a3125fb.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7a3125fb-cb7d-4a42-8610-2c944e453de7/20241118_093203/alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-8-7a3125fb.tar.gz)
- **alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-1** - [https://cloudius-jenkins-test.s3.amazonaws.com/7a3125fb-cb7d-4a42-8610-2c944e453de7/20241118_093203/alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-1-7a3125fb.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7a3125fb-cb7d-4a42-8610-2c944e453de7/20241118_093203/alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-1-7a3125fb.tar.gz)
- **alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-3** - [https://cloudius-jenkins-test.s3.amazonaws.com/7a3125fb-cb7d-4a42-8610-2c944e453de7/20241118_093203/alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-3-7a3125fb.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7a3125fb-cb7d-4a42-8610-2c944e453de7/20241118_093203/alternator-ttl-4-loaders-no-lwt-sis-db-node-7a3125fb-3-7a3125fb.tar.gz)
- **db-cluster-7a3125fb.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7a3125fb-cb7d-4a42-8610-2c944e453de7/20241120_115613/db-cluster-7a3125fb.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7a3125fb-cb7d-4a42-8610-2c944e453de7/20241120_115613/db-cluster-7a3125fb.tar.gz)
- **email_data-7a3125fb.json.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7a3125fb-cb7d-4a42-8610-2c944e453de7/20241120_115613/email_data-7a3125fb.json.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7a3125fb-cb7d-4a42-8610-2c944e453de7/20241120_115613/email_data-7a3125fb.json.tar.gz)
- **critical-7a3125fb.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7a3125fb-cb7d-4a42-8610-2c944e453de7/20241120_115613/critical-7a3125fb.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7a3125fb-cb7d-4a42-8610-2c944e453de7/20241120_115613/critical-7a3125fb.log.tar.gz)
- **output-7a3125fb.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7a3125fb-cb7d-4a42-8610-2c944e453de7/20241120_115613/output-7a3125fb.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7a3125fb-cb7d-4a42-8610-2c944e453de7/20241120_115613/output-7a3125fb.log.tar.gz)
- **error-7a3125fb.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7a3125fb-cb7d-4a42-8610-2c944e453de7/20241120_115613/error-7a3125fb.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7a3125fb-cb7d-4a42-8610-2c944e453de7/20241120_115613/error-7a3125fb.log.tar.gz)
- **left_processes-7a3125fb.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7a3125fb-cb7d-4a42-8610-2c944e453de7/20241120_115613/left_processes-7a3125fb.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7a3125fb-cb7d-4a42-8610-2c944e453de7/20241120_115613/left_processes-7a3125fb.log.tar.gz)
- **debug-7a3125fb.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7a3125fb-cb7d-4a42-8610-2c944e453de7/20241120_115613/debug-7a3125fb.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7a3125fb-cb7d-4a42-8610-2c944e453de7/20241120_115613/debug-7a3125fb.log.tar.gz)
- **raw_events-7a3125fb.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7a3125fb-cb7d-4a42-8610-2c944e453de7/20241120_115613/raw_events-7a3125fb.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7a3125fb-cb7d-4a42-8610-2c944e453de7/20241120_115613/raw_events-7a3125fb.log.tar.gz)
- **warning-7a3125fb.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7a3125fb-cb7d-4a42-8610-2c944e453de7/20241120_115613/warning-7a3125fb.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7a3125fb-cb7d-4a42-8610-2c944e453de7/20241120_115613/warning-7a3125fb.log.tar.gz)
- **argus-7a3125fb.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7a3125fb-cb7d-4a42-8610-2c944e453de7/20241120_115613/argus-7a3125fb.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7a3125fb-cb7d-4a42-8610-2c944e453de7/20241120_115613/argus-7a3125fb.log.tar.gz)
- **summary-7a3125fb.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7a3125fb-cb7d-4a42-8610-2c944e453de7/20241120_115613/summary-7a3125fb.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7a3125fb-cb7d-4a42-8610-2c944e453de7/20241120_115613/summary-7a3125fb.log.tar.gz)
- **events-7a3125fb.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7a3125fb-cb7d-4a42-8610-2c944e453de7/20241120_115613/events-7a3125fb.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7a3125fb-cb7d-4a42-8610-2c944e453de7/20241120_115613/events-7a3125fb.log.tar.gz)
- **normal-7a3125fb.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7a3125fb-cb7d-4a42-8610-2c944e453de7/20241120_115613/normal-7a3125fb.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7a3125fb-cb7d-4a42-8610-2c944e453de7/20241120_115613/normal-7a3125fb.log.tar.gz)
- **2024_11_18__09_32_05_049.sct-7a3125fb.log.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7a3125fb-cb7d-4a42-8610-2c944e453de7/20241120_115613/2024_11_18__09_32_05_049.sct-7a3125fb.log.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7a3125fb-cb7d-4a42-8610-2c944e453de7/20241120_115613/2024_11_18__09_32_05_049.sct-7a3125fb.log.gz)
- **2024_11_19__17_05_50_904.sct-7a3125fb.log.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7a3125fb-cb7d-4a42-8610-2c944e453de7/20241120_115613/2024_11_19__17_05_50_904.sct-7a3125fb.log.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7a3125fb-cb7d-4a42-8610-2c944e453de7/20241120_115613/2024_11_19__17_05_50_904.sct-7a3125fb.log.gz)
- **loader-set-7a3125fb.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7a3125fb-cb7d-4a42-8610-2c944e453de7/20241120_115613/loader-set-7a3125fb.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7a3125fb-cb7d-4a42-8610-2c944e453de7/20241120_115613/loader-set-7a3125fb.tar.gz)
- **monitor-set-7a3125fb.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7a3125fb-cb7d-4a42-8610-2c944e453de7/20241120_115613/monitor-set-7a3125fb.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7a3125fb-cb7d-4a42-8610-2c944e453de7/20241120_115613/monitor-set-7a3125fb.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2024.2/job/alternator_tablets/job/longevity-alternator-1h-scan-12h-ttl-no-lwt-2h-grace-4loaders-sisyphus-test/4/)
[Argus](https://argus.scylladb.com/test/cc3a6940-a949-4765-b703-d1e31fa5b208/runs?additionalRuns[]=7a3125fb-cb7d-4a42-8610-2c944e453de7)
</details>

**Comment by fruch** [comment]
What's unique in this case ? 

What does the elasticsearch nemesis results say for this nemesis?

 if usually it was taking much less then 2h and now in this case it exceeds it, it's or a scylla regression or this test is overloading the cluster.

**Comment by yarongilor** [comment]
well, i can rerun the same test with 2023 for comparison

**Comment by yarongilor** [comment]
In the previous run of this Longevity the issue is reproduced with even much longer duration (8260.339139223099s), during add-remove-dc nemesis:
```
2024-11-20 11:35:11.876: (SoftTimeoutEvent Severity.ERROR) period_type=one-time event_id=7862d3ae-2a94-4dc6-9d43-8c6b140ad754 during_nemesis=AddRemoveDc, source=SoftTimeout message=operation 'DECOMMISSION' took 8260.339139223099s and soft-timeout was set to 7200s
Traceback (most recent call last):
File "/usr/local/lib/python3.10/threading.py", line 973, in _bootstrap
self._bootstrap_inner()
File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.10/threading.py", line 953, in run
self._target(*self._args, **self._kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/sct_events/decorators.py", line 26, in wrapper
return func(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 436, in run
self.disrupt()
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 6390, in disrupt
self.call_next_nemesis()
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1973, in call_next_nemesis
self.execute_disrupt_method(disrupt_method=next(self.disruptions_cycle))
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1899, in execute_disrupt_method
disrupt_method()
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 5230, in wrapper
result = method(*args[1:], **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4660, in disrupt_add_remove_dc
self.cluster.decommission(new_node)
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 4974, in decommission
with adaptive_timeout(operation=Operations.DECOMMISSION, node=node):
File "/usr/local/lib/python3.10/contextlib.py", line 142, in __exit__
next(self.gen)
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/adaptive_timeouts/__init__.py", line 113, in adaptive_timeout
SoftTimeoutEvent(operation=operation.name, soft_timeout=timeout, duration=duration).publish_or_dump()
```

**Comment by yarongilor** [comment]
> [@yarongilor](https://github.com/yarongilor) you are pointing to the same exact scylla version, with and without tablets.
> 
> why would expect it to behave any differently ?

the point is it even worst.

**Comment by fruch** [comment]
> > [@yarongilor](https://github.com/yarongilor) you are pointing to the same exact scylla version, with and without tablets.
> > 
> > why would expect it to behave any differently ?
> 
> the point is it even worst.

One more reason to take it to scylla core

**Comment by fruch** [comment]
@yarongilor 

please take this one to scylla core, not SCT issue from the information shared so far

**Comment by yarongilor** [comment]
> well, i can rerun the same test with 2023 for comparison https://argus.scylladb.com/tests/scylla-cluster-tests/b2fe0c9a-1f8d-42b4-ada1-3d65889fd345

unfortunately logs weren't collected in this run. rerunning it.
Argus does show a notable perf regression of the grow-shrink nemesis duration for 2024.
So this issue can move to core once results of perf regression are available and confirmed.

**Comment by pehala** [comment]
@yarongilor did you encounter it in 2025.1 or recent master builds?

**Comment by yarongilor** [comment]
> [@yarongilor](https://github.com/yarongilor) did you encounter it in 2025.1 or recent master builds?
no recent reproductions.
i think the test of `longevity-alternator-1h-scan-12h-ttl-no-lwt-2h-grace-4loaders-sisyphus` didn't run in 2025.1 or master.

**Comment by fruch** [comment]
> > [@yarongilor](https://github.com/yarongilor) did you encounter it in 2025.1 or recent master builds?
> no recent reproductions.
> i think the test of `longevity-alternator-1h-scan-12h-ttl-no-lwt-2h-grace-4loaders-sisyphus` didn't run in 2025.1 or master.
> 

Please update the title to mention it's specific to some alternator ttl case
