### ISSUE TITLE
disrupt_add_remove_dc nemesis reported failure but all operations within it were successful

### ISSUE THREAD

**Issue by timtimb0t** [scylladb/scylla-cluster-tests#9470]
## Packages

Scylla version: `6.3.0~dev-20241129.65949ce60780` with build-id `d0921e78443678667ebaf5d8cdfda19428d03e6c`

Kernel Version: `6.8.0-1019-aws`

## Issue description

**disrupt_add_remove_dc** nemesis implies adding and removing new DC. DC been added and successfully removed but during the exit from **temporary_replication_strategy_setter** the following error returned:

```
Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 5430, in wrapper
    result = method(*args[1:], **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4787, in disrupt_add_remove_dc
    with temporary_replication_strategy_setter(node) as replication_strategy_setter:
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/replication_strategy_utils.py", line 114, in __exit__
    self(**self.preserved)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/replication_strategy_utils.py", line 125, in __call__
    strategy.apply(self.node, keyspace)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/replication_strategy_utils.py", line 47, in apply
    session.execute(cql)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 1318, in execute_verbose
    return execute_orig(*args, **kwargs)
  File "cassandra/cluster.py", line 2729, in cassandra.cluster.Session.execute
  File "cassandra/cluster.py", line 5120, in cassandra.cluster.ResponseFuture.result
cassandra.OperationTimedOut: errors={<Host: 10.4.10.165:9042 eu-west>: ConnectionException('Host has been marked down or removed')}, last_host=10.4.9.78:9042
```
target node (ie new DC) been removed successfully 

## Impact

No scylla impact

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Cluster size: 4 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
- longevity-50gb-12h-master-db-node-899fa2dc-7 (34.246.171.132 | 10.4.11.139) (shards: 8)
- longevity-50gb-12h-master-db-node-899fa2dc-6 (18.201.126.28 | 10.4.10.177) (shards: 8)
- longevity-50gb-12h-master-db-node-899fa2dc-5 (52.209.17.188 | 10.4.11.7) (shards: 8)
- longevity-50gb-12h-master-db-node-899fa2dc-4 (34.247.85.22 | 10.4.10.165) (shards: 11)
- longevity-50gb-12h-master-db-node-899fa2dc-3 (3.253.80.20 | 10.4.9.78) (shards: 14)
- longevity-50gb-12h-master-db-node-899fa2dc-2 (52.209.150.157 | 10.4.10.62) (shards: 9)
- longevity-50gb-12h-master-db-node-899fa2dc-1 (18.201.192.26 | 10.4.8.24) (shards: 11)

OS / Image: `ami-09d8c22a0006e46a8` (aws: undefined_region)

Test: `longevity-150gb-asymmetric-cluster-12h-test`
Test id: `899fa2dc-a66d-4948-bb82-ede7d1fba930`
Test name: `scylla-master/tier1/longevity-150gb-asymmetric-cluster-12h-test`
Test method: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):

- [longevity-150GB-12h-autorization-LimitedMonkey.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/63b10fb84ca390399aeee6195e8051ebd5411ffe/test-cases/longevity/longevity-150GB-12h-autorization-LimitedMonkey.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 899fa2dc-a66d-4948-bb82-ede7d1fba930`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=899fa2dc-a66d-4948-bb82-ede7d1fba930)
- Show all stored logs command: `$ hydra investigate show-logs 899fa2dc-a66d-4948-bb82-ede7d1fba930`

## Logs:
- **longevity-50gb-12h-master-db-node-899fa2dc-5** - [https://cloudius-jenkins-test.s3.amazonaws.com/899fa2dc-a66d-4948-bb82-ede7d1fba930/20241130_041118/longevity-50gb-12h-master-db-node-899fa2dc-5-899fa2dc.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/899fa2dc-a66d-4948-bb82-ede7d1fba930/20241130_041118/longevity-50gb-12h-master-db-node-899fa2dc-5-899fa2dc.tar.gz)
- **longevity-50gb-12h-master-db-node-899fa2dc-6** - [https://cloudius-jenkins-test.s3.amazonaws.com/899fa2dc-a66d-4948-bb82-ede7d1fba930/20241130_041118/longevity-50gb-12h-master-db-node-899fa2dc-6-899fa2dc.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/899fa2dc-a66d-4948-bb82-ede7d1fba930/20241130_041118/longevity-50gb-12h-master-db-node-899fa2dc-6-899fa2dc.tar.gz)
- **longevity-50gb-12h-master-db-node-899fa2dc-1** - [https://cloudius-jenkins-test.s3.amazonaws.com/899fa2dc-a66d-4948-bb82-ede7d1fba930/20241130_041118/longevity-50gb-12h-master-db-node-899fa2dc-1-899fa2dc.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/899fa2dc-a66d-4948-bb82-ede7d1fba930/20241130_041118/longevity-50gb-12h-master-db-node-899fa2dc-1-899fa2dc.tar.gz)
- **db-cluster-899fa2dc.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/899fa2dc-a66d-4948-bb82-ede7d1fba930/20241201_043026/db-cluster-899fa2dc.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/899fa2dc-a66d-4948-bb82-ede7d1fba930/20241201_043026/db-cluster-899fa2dc.tar.gz)
- **sct-runner-events-899fa2dc.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/899fa2dc-a66d-4948-bb82-ede7d1fba930/20241201_043026/sct-runner-events-899fa2dc.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/899fa2dc-a66d-4948-bb82-ede7d1fba930/20241201_043026/sct-runner-events-899fa2dc.tar.gz)
- **sct-899fa2dc.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/899fa2dc-a66d-4948-bb82-ede7d1fba930/20241201_043026/sct-899fa2dc.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/899fa2dc-a66d-4948-bb82-ede7d1fba930/20241201_043026/sct-899fa2dc.log.tar.gz)
- **loader-set-899fa2dc.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/899fa2dc-a66d-4948-bb82-ede7d1fba930/20241201_043026/loader-set-899fa2dc.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/899fa2dc-a66d-4948-bb82-ede7d1fba930/20241201_043026/loader-set-899fa2dc.tar.gz)
- **monitor-set-899fa2dc.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/899fa2dc-a66d-4948-bb82-ede7d1fba930/20241201_043026/monitor-set-899fa2dc.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/899fa2dc-a66d-4948-bb82-ede7d1fba930/20241201_043026/monitor-set-899fa2dc.tar.gz)
- **core.scylla-longevity-50gb-12h-master-db-node-899fa2dc-2-2024-12-01_02-09-24.gz** - [https://storage.cloud.google.com/upload.scylladb.com/core.scylla.106.d8962df97b334de1bd953bd6ce2e405b.24168.1733015713000000./core.scylla.106.d8962df97b334de1bd953bd6ce2e405b.24168.1733015713000000.zst](https://storage.cloud.google.com/upload.scylladb.com/core.scylla.106.d8962df97b334de1bd953bd6ce2e405b.24168.1733015713000000./core.scylla.106.d8962df97b334de1bd953bd6ce2e405b.24168.1733015713000000.zst)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/tier1/job/longevity-150gb-asymmetric-cluster-12h-test/48/)
[Argus](https://argus.scylladb.com/test/7f604213-5cad-4418-921e-1ca98918071c/runs?additionalRuns[]=899fa2dc-a66d-4948-bb82-ede7d1fba930)
</details>

**Comment by soyacz** [comment]
should be fixed when https://github.com/scylladb/scylla-cluster-tests/issues/9430 is fixed.

**Comment by temichus** [comment]
blocked by https://github.com/scylladb/scylla-cluster-tests/issues/9430

**Comment by timtimb0t** [comment]
## Packages

Scylla version: `6.3.0~dev-20250108.e51b2075dacc` with build-id `1ffc83e51d7f78126ce77667ff1140f5f4913518`


Kernel Version: `6.8.0-1021-aws`


## Installation details

Cluster size: 4 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
- longevity-50gb-12h-master-db-node-bf0c7579-7 (63.34.7.22 | 10.4.8.238) (shards: 13)
- longevity-50gb-12h-master-db-node-bf0c7579-6 (34.245.207.49 | 10.4.11.63) (shards: 12)
- longevity-50gb-12h-master-db-node-bf0c7579-5 (18.201.25.47 | 10.4.10.152) (shards: 12)
- longevity-50gb-12h-master-db-node-bf0c7579-4 (3.255.173.221 | 10.4.11.204) (shards: 13)
- longevity-50gb-12h-master-db-node-bf0c7579-3 (54.76.108.105 | 10.4.11.166) (shards: 12)
- longevity-50gb-12h-master-db-node-bf0c7579-2 (3.250.88.220 | 10.4.11.229) (shards: 12)
- longevity-50gb-12h-master-db-node-bf0c7579-1 (54.217.164.238 | 10.4.10.126) (shards: 8)


OS / Image: `ami-0419ef0a7ad763693` (NO RUNNER: NO RUNNER)

Test: `longevity-150gb-asymmetric-cluster-12h-test`
Test id: `bf0c7579-e48d-4814-9625-8a3f1193c8d7`
Test name: `scylla-master/tier1/longevity-150gb-asymmetric-cluster-12h-test`
Test method: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):

- [longevity-150GB-12h-autorization-LimitedMonkey.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/63550823bce5b0518bd72b91f3d4dc139b7ca937/test-cases/longevity/longevity-150GB-12h-autorization-LimitedMonkey.yaml)


<details>
<summary>
Logs and commands
</summary>


- Restore Monitor Stack command: `$ hydra investigate show-monitor bf0c7579-e48d-4814-9625-8a3f1193c8d7`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=bf0c7579-e48d-4814-9625-8a3f1193c8d7)
- Show all stored logs command: `$ hydra investigate show-logs bf0c7579-e48d-4814-9625-8a3f1193c8d7`


## Logs:
- **longevity-50gb-12h-master-db-node-bf0c7579-5** - [https://cloudius-jenkins-test.s3.amazonaws.com/bf0c7579-e48d-4814-9625-8a3f1193c8d7/20250111_041403/longevity-50gb-12h-master-db-node-bf0c7579-5-bf0c7579.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/bf0c7579-e48d-4814-9625-8a3f1193c8d7/20250111_041403/longevity-50gb-12h-master-db-node-bf0c7579-5-bf0c7579.tar.gz)
- **longevity-50gb-12h-master-db-node-bf0c7579-6** - [https://cloudius-jenkins-test.s3.amazonaws.com/bf0c7579-e48d-4814-9625-8a3f1193c8d7/20250111_041403/longevity-50gb-12h-master-db-node-bf0c7579-6-bf0c7579.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/bf0c7579-e48d-4814-9625-8a3f1193c8d7/20250111_041403/longevity-50gb-12h-master-db-node-bf0c7579-6-bf0c7579.tar.gz)
- **longevity-50gb-12h-master-db-node-bf0c7579-2** - [https://cloudius-jenkins-test.s3.amazonaws.com/bf0c7579-e48d-4814-9625-8a3f1193c8d7/20250111_041403/longevity-50gb-12h-master-db-node-bf0c7579-2-bf0c7579.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/bf0c7579-e48d-4814-9625-8a3f1193c8d7/20250111_041403/longevity-50gb-12h-master-db-node-bf0c7579-2-bf0c7579.tar.gz)
- **core.scylla-longevity-50gb-12h-master-db-node-bf0c7579-3-2025-01-11_21-01-53.gz** - [https://storage.cloud.google.com/upload.scylladb.com/core.scylla.106.e413da9d671c48d682abad5758f58d45.9780.1736626496000000./core.scylla.106.e413da9d671c48d682abad5758f58d45.9780.1736626496000000.zst](https://storage.cloud.google.com/upload.scylladb.com/core.scylla.106.e413da9d671c48d682abad5758f58d45.9780.1736626496000000./core.scylla.106.e413da9d671c48d682abad5758f58d45.9780.1736626496000000.zst)
- **db-cluster-bf0c7579.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/bf0c7579-e48d-4814-9625-8a3f1193c8d7/20250111_211355/db-cluster-bf0c7579.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/bf0c7579-e48d-4814-9625-8a3f1193c8d7/20250111_211355/db-cluster-bf0c7579.tar.gz)
- **sct-runner-events-bf0c7579.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/bf0c7579-e48d-4814-9625-8a3f1193c8d7/20250111_211355/sct-runner-events-bf0c7579.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/bf0c7579-e48d-4814-9625-8a3f1193c8d7/20250111_211355/sct-runner-events-bf0c7579.tar.gz)
- **sct-bf0c7579.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/bf0c7579-e48d-4814-9625-8a3f1193c8d7/20250111_211355/sct-bf0c7579.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/bf0c7579-e48d-4814-9625-8a3f1193c8d7/20250111_211355/sct-bf0c7579.log.tar.gz)
- **loader-set-bf0c7579.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/bf0c7579-e48d-4814-9625-8a3f1193c8d7/20250111_211355/loader-set-bf0c7579.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/bf0c7579-e48d-4814-9625-8a3f1193c8d7/20250111_211355/loader-set-bf0c7579.tar.gz)
- **monitor-set-bf0c7579.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/bf0c7579-e48d-4814-9625-8a3f1193c8d7/20250111_211355/monitor-set-bf0c7579.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/bf0c7579-e48d-4814-9625-8a3f1193c8d7/20250111_211355/monitor-set-bf0c7579.tar.gz)
- **ssl-conf-bf0c7579.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/bf0c7579-e48d-4814-9625-8a3f1193c8d7/20250111_211355/ssl-conf-bf0c7579.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/bf0c7579-e48d-4814-9625-8a3f1193c8d7/20250111_211355/ssl-conf-bf0c7579.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/tier1/job/longevity-150gb-asymmetric-cluster-12h-test/54/)
[Argus](https://argus.scylladb.com/test/7f604213-5cad-4418-921e-1ca98918071c/runs?additionalRuns[]=bf0c7579-e48d-4814-9625-8a3f1193c8d7)
</details>

**Comment by timtimb0t** [comment]
## Packages

Scylla version: `2025.2.0~dev-20250207.d50738fecab4` with build-id `f1c4907fdf6f61926febd063df9a87ca493d8281`



Kernel Version: `6.8.0-1021-aws`



## Installation details

Cluster size: 4 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
- longevity-50gb-12h-master-db-node-b476a611-7 (54.78.196.33 | 10.4.8.120) (shards: 13)
- longevity-50gb-12h-master-db-node-b476a611-6 (34.245.169.56 | 10.4.9.209) (shards: 8)
- longevity-50gb-12h-master-db-node-b476a611-5 (18.201.128.168 | 10.4.10.206) (shards: 9)
- longevity-50gb-12h-master-db-node-b476a611-4 (34.252.194.115 | 10.4.8.141) (shards: 14)
- longevity-50gb-12h-master-db-node-b476a611-3 (52.211.238.83 | 10.4.10.56) (shards: 11)
- longevity-50gb-12h-master-db-node-b476a611-2 (3.250.57.19 | 10.4.11.162) (shards: 10)
- longevity-50gb-12h-master-db-node-b476a611-1 (3.253.112.204 | 10.4.8.107) (shards: 14)


OS / Image: `ami-099b445904ffa1978` (aws: undefined_region)

Test: `longevity-150gb-asymmetric-cluster-12h-test`
Test id: `b476a611-2b99-4b4e-af76-0a1de69d38b1`
Test name: `scylla-master/tier1/longevity-150gb-asymmetric-cluster-12h-test`
Test method: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):

- [longevity-150GB-12h-autorization-LimitedMonkey.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/80eb803292e752e70f4a86855ac3a24732ba09ea/test-cases/longevity/longevity-150GB-12h-autorization-LimitedMonkey.yaml)


<details>
<summary>
Logs and commands
</summary>


- Restore Monitor Stack command: `$ hydra investigate show-monitor b476a611-2b99-4b4e-af76-0a1de69d38b1`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=b476a611-2b99-4b4e-af76-0a1de69d38b1)
- Show all stored logs command: `$ hydra investigate show-logs b476a611-2b99-4b4e-af76-0a1de69d38b1`


## Logs:
- **longevity-50gb-12h-master-db-node-b476a611-5** - [https://cloudius-jenkins-test.s3.amazonaws.com/b476a611-2b99-4b4e-af76-0a1de69d38b1/20250208_041158/longevity-50gb-12h-master-db-node-b476a611-5-b476a611.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/b476a611-2b99-4b4e-af76-0a1de69d38b1/20250208_041158/longevity-50gb-12h-master-db-node-b476a611-5-b476a611.tar.zst)
- **longevity-50gb-12h-master-db-node-b476a611-6** - [https://cloudius-jenkins-test.s3.amazonaws.com/b476a611-2b99-4b4e-af76-0a1de69d38b1/20250208_041158/longevity-50gb-12h-master-db-node-b476a611-6-b476a611.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/b476a611-2b99-4b4e-af76-0a1de69d38b1/20250208_041158/longevity-50gb-12h-master-db-node-b476a611-6-b476a611.tar.zst)
- **longevity-50gb-12h-master-db-node-b476a611-2** - [https://cloudius-jenkins-test.s3.amazonaws.com/b476a611-2b99-4b4e-af76-0a1de69d38b1/20250208_041158/longevity-50gb-12h-master-db-node-b476a611-2-b476a611.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/b476a611-2b99-4b4e-af76-0a1de69d38b1/20250208_041158/longevity-50gb-12h-master-db-node-b476a611-2-b476a611.tar.zst)
- **core.scylla-longevity-50gb-12h-master-db-node-b476a611-3-2025-02-09_00-52-24.gz** - [https://storage.cloud.google.com/upload.scylladb.com/core.scylla.106.7b4bfe3663ab4b7a8e732be766d1503e.14589.1739059262000000./core.scylla.106.7b4bfe3663ab4b7a8e732be766d1503e.14589.1739059262000000.zst](https://storage.cloud.google.com/upload.scylladb.com/core.scylla.106.7b4bfe3663ab4b7a8e732be766d1503e.14589.1739059262000000./core.scylla.106.7b4bfe3663ab4b7a8e732be766d1503e.14589.1739059262000000.zst)
- **db-cluster-b476a611.tar.zst** - [https://cloudius-jenkins-test.s3.amazonaws.com/b476a611-2b99-4b4e-af76-0a1de69d38b1/20250209_043048/db-cluster-b476a611.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/b476a611-2b99-4b4e-af76-0a1de69d38b1/20250209_043048/db-cluster-b476a611.tar.zst)
- **sct-runner-events-b476a611.tar.zst** - [https://cloudius-jenkins-test.s3.amazonaws.com/b476a611-2b99-4b4e-af76-0a1de69d38b1/20250209_043048/sct-runner-events-b476a611.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/b476a611-2b99-4b4e-af76-0a1de69d38b1/20250209_043048/sct-runner-events-b476a611.tar.zst)
- **sct-b476a611.log.tar.zst** - [https://cloudius-jenkins-test.s3.amazonaws.com/b476a611-2b99-4b4e-af76-0a1de69d38b1/20250209_043048/sct-b476a611.log.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/b476a611-2b99-4b4e-af76-0a1de69d38b1/20250209_043048/sct-b476a611.log.tar.zst)
- **loader-set-b476a611.tar.zst** - [https://cloudius-jenkins-test.s3.amazonaws.com/b476a611-2b99-4b4e-af76-0a1de69d38b1/20250209_043048/loader-set-b476a611.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/b476a611-2b99-4b4e-af76-0a1de69d38b1/20250209_043048/loader-set-b476a611.tar.zst)
- **monitor-set-b476a611.tar.zst** - [https://cloudius-jenkins-test.s3.amazonaws.com/b476a611-2b99-4b4e-af76-0a1de69d38b1/20250209_043048/monitor-set-b476a611.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/b476a611-2b99-4b4e-af76-0a1de69d38b1/20250209_043048/monitor-set-b476a611.tar.zst)
- **ssl-conf-b476a611.tar.zst** - [https://cloudius-jenkins-test.s3.amazonaws.com/b476a611-2b99-4b4e-af76-0a1de69d38b1/20250209_043048/ssl-conf-b476a611.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/b476a611-2b99-4b4e-af76-0a1de69d38b1/20250209_043048/ssl-conf-b476a611.tar.zst)
- **builder-b476a611.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b476a611-2b99-4b4e-af76-0a1de69d38b1/upload_20250209_043247/builder-b476a611.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b476a611-2b99-4b4e-af76-0a1de69d38b1/upload_20250209_043247/builder-b476a611.log.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/tier1/job/longevity-150gb-asymmetric-cluster-12h-test/58/)
[Argus](https://argus.scylladb.com/test/7f604213-5cad-4418-921e-1ca98918071c/runs?additionalRuns[]=b476a611-2b99-4b4e-af76-0a1de69d38b1)
</details>
