### ISSUE TITLE
Incorrect object used during events handling

### ISSUE THREAD

**Issue by xtrey** [scylladb/scylla-cluster-tests#9482]
## Packages

Scylla version: `6.2.2-20241128.c6ef055e9c3b` with build-id `d4c2d158132fbb16ba24f21c443cbfb9f67401ea`

Kernel Version: `4.14.355-271.569.amzn2.x86_64`

## Issue description

```
2024-12-01 15:00:58.269: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=ea9d61f4-cf60-48a1-85cb-5c40b52b7537, source=ArtifactsTest.test_scylla_service (artifacts_test.ArtifactsTest) [Check the output of perftune.py]() message=Traceback (most recent call last):
File "/tmp/jenkins/workspace/scylla-6.2/artifacts/artifacts-amazon2-test/scylla-cluster-tests/sdcm/utils/perftune_validator.py", line 230, in compare_perftune_results
option_file_dict = self.executor.get_default_perftune_config()
File "/tmp/jenkins/workspace/scylla-6.2/artifacts/artifacts-amazon2-test/scylla-cluster-tests/sdcm/utils/perftune_validator.py", line 90, in get_default_perftune_config
return yaml.safe_load(self.node.get_perftune_yaml())
File "/usr/local/lib/python3.10/site-packages/yaml/__init__.py", line 125, in safe_load
return load(stream, SafeLoader)
File "/usr/local/lib/python3.10/site-packages/yaml/__init__.py", line 81, in load
return loader.get_single_data()
File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 49, in get_single_data
node = self.get_single_node()
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 36, in get_single_node
document = self.compose_document()
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 55, in compose_document
node = self.compose_node(None, None)
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
node = self.compose_mapping_node(anchor)
File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 127, in compose_mapping_node
while not self.check_event(MappingEndEvent):
File "/usr/local/lib/python3.10/site-packages/yaml/parser.py", line 98, in check_event
self.current_event = self.state()
File "/usr/local/lib/python3.10/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
if self.check_token(KeyToken):
File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 116, in check_token
self.fetch_more_tokens()
File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
return self.fetch_value()
File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 577, in fetch_value
raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
in "<unicode string>", line 1, column 33:
cat: /etc/scylla.d/perftune.yaml: No such file or directory
^
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/tmp/jenkins/workspace/scylla-6.2/artifacts/artifacts-amazon2-test/scylla-cluster-tests/artifacts_test.py", line 454, in test_scylla_service
perftune_checker.compare_perftune_results()
File "/tmp/jenkins/workspace/scylla-6.2/artifacts/artifacts-amazon2-test/scylla-cluster-tests/sdcm/utils/perftune_validator.py", line 236, in compare_perftune_results
PerftuneResultEvent(
File "/tmp/jenkins/workspace/scylla-6.2/artifacts/artifacts-amazon2-test/scylla-cluster-tests/sdcm/sct_events/system.py", line 180, in __init__
self.trace = "".join(format_stack(trace)) if trace else None
File "/usr/local/lib/python3.10/traceback.py", line 213, in format_stack
return format_list(extract_stack(f, limit=limit))
File "/usr/local/lib/python3.10/traceback.py", line 227, in extract_stack
stack = StackSummary.extract(walk_stack(f), limit=limit)
File "/usr/local/lib/python3.10/traceback.py", line 364, in extract
for f, lineno in frame_gen:
File "/usr/local/lib/python3.10/traceback.py", line 318, in walk_stack
yield f, f.f_lineno
AttributeError: 'str' object has no attribute 'f_lineno'
```

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Cluster size: 1 nodes (i4i.large)

Scylla Nodes used in this run:
- artifacts-amazon2-jenkins-db-node-3b1056df-1 (54.78.187.125 | 10.4.11.48) (shards: 2)

OS / Image: `ami-0a09a25a3d0574b76` (aws: undefined_region)

Test: `artifacts-amazon2-test`
Test id: `3b1056df-ad2c-41d6-82a5-303f3451ae07`
Test name: `scylla-6.2/artifacts/artifacts-amazon2-test`
Test method: `artifacts_test`
Test config file(s):

- [amazon2.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/1882aedc0089972334eac61ddd4dfa380eca54c3/test-cases/artifacts/amazon2.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 3b1056df-ad2c-41d6-82a5-303f3451ae07`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=3b1056df-ad2c-41d6-82a5-303f3451ae07)
- Show all stored logs command: `$ hydra investigate show-logs 3b1056df-ad2c-41d6-82a5-303f3451ae07`

## Logs:
- **db-cluster-3b1056df.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/3b1056df-ad2c-41d6-82a5-303f3451ae07/20241201_150121/db-cluster-3b1056df.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/3b1056df-ad2c-41d6-82a5-303f3451ae07/20241201_150121/db-cluster-3b1056df.tar.gz)
- **sct-runner-events-3b1056df.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/3b1056df-ad2c-41d6-82a5-303f3451ae07/20241201_150121/sct-runner-events-3b1056df.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/3b1056df-ad2c-41d6-82a5-303f3451ae07/20241201_150121/sct-runner-events-3b1056df.tar.gz)
- **sct-3b1056df.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/3b1056df-ad2c-41d6-82a5-303f3451ae07/20241201_150121/sct-3b1056df.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/3b1056df-ad2c-41d6-82a5-303f3451ae07/20241201_150121/sct-3b1056df.log.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-6.2/job/artifacts/job/artifacts-amazon2-test/7/)
[Argus](https://argus.scylladb.com/test/dbf09d85-8b07-409e-ab78-b9f86affa8eb/runs?additionalRuns[]=3b1056df-ad2c-41d6-82a5-303f3451ae07)
</details>

**Comment by fruch** [comment]
prepare didn't run, hence perftune file is missing
```
2024-12-01T14:58:20.434 artifacts-amazon2-jenkins-db-node-3b1056df-1 !ERROR | systemd[1]: [/usr/lib/systemd/system/scylla-server.service:18] Executable path is not absolute, ignoring: +/opt/scylladb/scripts/scylla_prepare
```

we don't support amazon 2 anymore, partly cause of that.

@yaronkaikov @roydahan, can the trigger for those be remove in 6.2 ?

**Comment by yaronkaikov** [comment]
> prepare didn't run, hence perftune file is missing
> 
> ```
> 2024-12-01T14:58:20.434 artifacts-amazon2-jenkins-db-node-3b1056df-1 !ERROR | systemd[1]: [/usr/lib/systemd/system/scylla-server.service:18] Executable path is not absolute, ignoring: +/opt/scylladb/scripts/scylla_prepare
> ```
> 
> we don't support amazon 2 anymore, partly cause of that.
> 
> [@yaronkaikov](https://github.com/yaronkaikov) [@roydahan](https://github.com/roydahan), can the trigger for those be remove in 6.2 ?

Removed with https://github.com/scylladb/scylla-pkg/pull/4769
