### ISSUE TITLE
disrupt_remove_node_then_add_node: AssertionError: retry is not supported for long running commands, always use it with retry=0

### ISSUE THREAD

**Issue by pehala** [scylladb/scylla-cluster-tests#9534]
Seen here (https://argus.scylladb.com/tests/scylla-cluster-tests/0bc52ea0-4703-4855-8ba2-51bead782590), but also in other runs. Seems like a nemesis bug

```
2024-12-11 01:58:58.053: (DisruptionEvent Severity.ERROR) period_type=end event_id=eca41cbf-cd85-41fb-ad92-feefae7994f6 duration=2m2s: nemesis_name=RemoveNodeThenAddNode target_node=Node longevity-10gb-3h-master-db-node-0bc52ea0-0-8 [34.139.132.146 | 10.142.0.61] errors=retry is not supported for long running commands, always use it with retry=0
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 5443, in wrapper
result = method(*args[1:], **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3712, in disrupt_remove_node_then_add_node
exit_status = remove_node()
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 72, in inner
return func(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3689, in remove_node
res = rnd_node.run_nodetool("removenode {}".format(
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2676, in run_nodetool
runner(cmd, timeout=timeout, ignore_status=ignore_status, verbose=verbose, retry=retry)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_long_running.py", line 31, in run_long_running_cmd
assert retry == 0, "retry is not supported for long running commands, always use it with retry=0"
AssertionError: retry is not supported for long running commands, always use it with retry=0
```

**Comment by pehala** [comment]
I found this error in both Azure & GCE runs, no AWS run where this happened in the last week
