### ISSUE TITLE
logs collection and clean resources fails after aborting a longevity job in Jenkins

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#9623]
## Packages

Scylla version: `2024.3.0~dev-20241223.b8fe6e17c6a3` with build-id `0ac66e4fdafa71257cafa4345cffeb2909d388bc`

Kernel Version: `6.8.0-1021-aws`

## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

*Describe your issue in detail and steps it took to produce it.*
got:
```
13:05:57  [Pipeline] { (Collect log data)
13:05:57  [Pipeline] catchError
13:05:57  [Pipeline] {
13:05:57  [Pipeline] script
13:05:58  [Pipeline] {
13:05:58  [Pipeline] withBuildUser
13:05:58  [Pipeline] {
13:05:58  [Pipeline] dir
13:05:58  Running in /tmp/jenkins/workspace/scylla-staging/yarongilor/longevity-mv-sync/scylla-cluster-tests
13:05:58  [Pipeline] {
13:05:58  [Pipeline] timeout
13:05:58  Timeout set to expire in 1 hr 30 min
13:05:58  [Pipeline] {
13:05:58  [Pipeline] sh
13:06:00  [Click here to forcibly terminate running steps](https://jenkins.scylladb.com/job/scylla-staging/job/yarongilor/job/longevity-mv-sync/22/consoleFull#)
13:06:01  [Pipeline] }
13:06:01  [Pipeline] // timeout
13:06:01  [Pipeline] }
13:06:01  [Pipeline] // dir
13:06:01  [Pipeline] }
13:06:02  [Pipeline] // withBuildUser
13:06:02  [Pipeline] }
13:06:02  [Pipeline] // script
13:06:02  [Pipeline] }
13:06:02  java.io.StreamCorruptedException: invalid stream header: 636F7272
13:06:02  	at java.base/java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:989)
13:06:02  	at java.base/java.io.ObjectInputStream.<init>(ObjectInputStream.java:416)
13:06:02  	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:50)
13:06:02  	at hudson.remoting.Command.readFrom(Command.java:141)
13:06:02  	at hudson.remoting.Command.readFrom(Command.java:127)
13:06:02  	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:35)
13:06:02  	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:62)
13:06:02  Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to i-037b6ddbcdbc27425
13:06:02  		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1923)
13:06:02  		at hudson.remoting.Request.call(Request.java:204)
13:06:02  		at hudson.remoting.Channel.call(Channel.java:1111)
13:06:02  		at hudson.Launcher$RemoteLauncher.launch(Launcher.java:1121)
13:06:02  		at hudson.Launcher$ProcStarter.start(Launcher.java:507)
13:06:02  		at PluginClassLoader for durable-task//org.jenkinsci.plugins.durabletask.BourneShellScript.launchWithCookie(BourneShellScript.java:180)
13:06:02  		at PluginClassLoader for durable-task//org.jenkinsci.plugins.durabletask.FileMonitoringTask.launch(FileMonitoringTask.java:134)
13:06:02  		at PluginClassLoader for workflow-durable-task-step//org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.start(DurableTaskStep.java:330)
13:06:02  		at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:323)
13:06:02  		at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:196)
13:06:02  		at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:124)
13:06:02  		at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
13:06:02  		at java.base/java.lang.reflect.Method.invoke(Method.java:580)
13:06:02  		at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
13:06:02  		at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
13:06:02  		at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
13:06:02  		at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
13:06:02  		at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:41)
13:06:02  		at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
13:06:02  		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
13:06:02  		at PluginClassLoader for script-security//org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:180)
13:06:02  		at PluginClassLoader for script-security//org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:23)
13:06:02  		at PluginClassLoader for script-security//org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:163)
13:06:02  		at PluginClassLoader for script-security//org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:148)
13:06:02  		at PluginClassLoader for script-security//org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:178)
13:06:02  		at PluginClassLoader for script-security//org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:182)
13:06:02  		at PluginClassLoader for workflow-cps//com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:17)
13:06:02  		at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.LoggingInvoker.methodCall(LoggingInvoker.java:117)
13:06:02  		at PluginClassLoader for workflow-cps//com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:90)
13:06:02  		at PluginClassLoader for workflow-cps//com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:116)
13:06:02  		at PluginClassLoader for workflow-cps//com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:85)
13:06:02  		at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
13:06:02  		at java.base/java.lang.reflect.Method.invoke(Method.java:580)
13:06:02  		at PluginClassLoader for workflow-cps//com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
13:06:02  		at PluginClassLoader for workflow-cps//com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:110)
13:06:02  		at PluginClassLoader for workflow-cps//com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:85)
13:06:02  		at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
13:06:02  		at java.base/java.lang.reflect.Method.invoke(Method.java:580)
13:06:02  		at PluginClassLoader for workflow-cps//com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
13:06:02  		at PluginClassLoader for workflow-cps//com.cloudbees.groovy.cps.impl.CastBlock$ContinuationImpl.cast(CastBlock.java:47)
13:06:02  		at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
13:06:02  		at java.base/java.lang.reflect.Method.invoke(Method.java:580)
13:06:02  		at PluginClassLoader for workflow-cps//com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
13:06:02  		at PluginClassLoader for workflow-cps//com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.dispatch(CollectionLiteralBlock.java:55)
13:06:02  		at PluginClassLoader for workflow-cps//com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.item(CollectionLiteralBlock.java:45)
13:06:02  		at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
13:06:02  		at java.base/java.lang.reflect.Method.invoke(Method.java:580)
13:06:02  		at PluginClassLoader for workflow-cps//com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
13:06:02  		at PluginClassLoader for workflow-cps//com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
13:06:02  		at PluginClassLoader for workflow-cps//com.cloudbees.groovy.cps.Next.step(Next.java:83)
13:06:02  		at PluginClassLoader for workflow-cps//com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:147)
13:06:02  		at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:17)
13:06:02  		at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:49)
13:06:02  		at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:180)
13:06:02  		at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:422)
13:06:02  		at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:330)
13:06:02  		at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:294)
13:06:02  		at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService.lambda$wrap$4(CpsVmExecutorService.java:140)
13:06:02  		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
13:06:02  		at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)
13:06:02  		at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
13:06:02  		at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
13:06:02  		at jenkins.util.ErrorLoggingExecutorService.lambda$wrap$0(ErrorLoggingExecutorService.java:51)
13:06:02  		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
13:06:02  		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
13:06:02  		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
13:06:02  		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
13:06:02  		at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$1.call(CpsVmExecutorService.java:53)
13:06:02  		at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$1.call(CpsVmExecutorService.java:50)
13:06:02  		at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:136)
13:06:02  		at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:275)
13:06:02  		at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService.lambda$categoryThreadFactory$0(CpsVmExecutorService.java:50)
13:06:02  		at java.base/java.lang.Thread.run(Thread.java:1583)
13:06:02  Also:   org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: 95033fa3-cd22-4e50-ae6b-8dbe88992179
13:06:02  Caused: hudson.remoting.RequestAbortedException
13:06:02  	at hudson.remoting.Request.abort(Request.java:358)
13:06:02  	at hudson.remoting.Channel.terminate(Channel.java:1196)
13:06:02  	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:95)
13:06:02  [Pipeline] // catchError
13:06:02  [Pipeline] }
13:06:02  [Pipeline] // stage
13:06:02  [Pipeline] stage
13:06:02  [Pipeline] { (Clean resources)
13:06:02  [Pipeline] catchError
13:06:02  [Pipeline] {
13:06:02  [Pipeline] script
13:06:02  [Pipeline] {
13:06:02  [Pipeline] withBuildUser
13:06:02  [Pipeline] // withBuildUser
13:06:02  [Pipeline] }
13:06:03  [Pipeline] // script
13:06:03  [Pipeline] }
13:06:03  Also:   org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: 5f7d3a8f-aa59-4b78-9760-ba4541dbdabd
13:06:03 
 org.jenkinsci.plugins.workflow.support.steps.AgentOfflineException: Unable to create live FilePath for i-037b6ddbcdbc27425; aws-us-east-1-qa-builder-v3-1 i-037b6ddbcdbc27425 Builds left: 10  was marked offline: Connection was broken
13:06:03  	at PluginClassLoader for workflow-durable-task-step//org.jenkinsci.plugins.workflow.support.steps.ExecutorStepDynamicContext$FilePathTranslator.get(ExecutorStepDynamicContext.java:188)
13:06:03  	at PluginClassLoader for workflow-durable-task-step//org.jenkinsci.plugins.workflow.support.steps.ExecutorStepDynamicContext$FilePathTranslator.get(ExecutorStepDynamicContext.java:160)
13:06:03  	at PluginClassLoader for workflow-durable-task-step//org.jenkinsci.plugins.workflow.support.steps.ExecutorStepDynamicContext$Translator.get(ExecutorStepDynamicContext.java:153)
13:06:03  	at PluginClassLoader for workflow-durable-task-step//org.jenkinsci.plugins.workflow.support.steps.ExecutorStepDynamicContext$FilePathTranslator.get(ExecutorStepDynamicContext.java:170)
13:06:03  	at PluginClassLoader for workflow-durable-task-step//org.jenkinsci.plugins.workflow.support.steps.ExecutorStepDynamicContext$FilePathTranslator.get(ExecutorStepDynamicContext.java:160)
13:06:03  	at PluginClassLoader for workflow-step-api//org.jenkinsci.plugins.workflow.steps.DynamicContext$Typed.get(DynamicContext.java:95)
13:06:03  	at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.ContextVariableSet.get(ContextVariableSet.java:139)
13:06:03  	at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.CpsThread.getContextVariable(CpsThread.java:135)
13:06:03  	at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.CpsStepContext.doGet(CpsStepContext.java:297)
13:06:03  	at PluginClassLoader for workflow-support//org.jenkinsci.plugins.workflow.support.DefaultStepContext.get(DefaultStepContext.java:90)
13:06:03  	at PluginClassLoader for workflow-basic-steps//org.jenkinsci.plugins.workflow.steps.CoreWrapperStep$Execution2.doStart(CoreWrapperStep.java:109)
13:06:03  	at PluginClassLoader for workflow-step-api//org.jenkinsci.plugins.workflow.steps.GeneralNonBlockingStepExecution.lambda$run$0(GeneralNonBlockingStepExecution.java:77)
13:06:03  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
13:06:03  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
13:06:03  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
13:06:03  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
13:06:03  	at java.base/java.lang.Thread.run(Thread.java:1583)
```
## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Cluster size: 6 nodes (i3.large)

Scylla Nodes used in this run:
- longevity-10gb-3h-mv-sync-compare--db-node-67ab07ef-6 (3.237.75.97 | 10.12.2.240) (shards: 2)
- longevity-10gb-3h-mv-sync-compare--db-node-67ab07ef-5 (44.200.37.196 | 10.12.3.196) (shards: 2)
- longevity-10gb-3h-mv-sync-compare--db-node-67ab07ef-4 (3.226.252.8 | 10.12.2.113) (shards: 2)
- longevity-10gb-3h-mv-sync-compare--db-node-67ab07ef-3 (3.221.163.226 | 10.12.2.234) (shards: 2)
- longevity-10gb-3h-mv-sync-compare--db-node-67ab07ef-2 (44.192.3.85 | 10.12.3.37) (shards: 2)
- longevity-10gb-3h-mv-sync-compare--db-node-67ab07ef-1 (18.209.230.13 | 10.12.2.185) (shards: 2)

OS / Image: `ami-08a111409026d1e10` (aws: undefined_region)

Test: `longevity-mv-sync`
Test id: `67ab07ef-587e-4573-bd7b-df1ef99b8750`
Test name: `scylla-staging/yarongilor/longevity-mv-sync`
Test method: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):

- [longevity-10gb-3h-mv-sync.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/d2c7c16b05ee22a8c6641ee7526f5215a726228b/test-cases/longevity/longevity-10gb-3h-mv-sync.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 67ab07ef-587e-4573-bd7b-df1ef99b8750`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=67ab07ef-587e-4573-bd7b-df1ef99b8750)
- Show all stored logs command: `$ hydra investigate show-logs 67ab07ef-587e-4573-bd7b-df1ef99b8750`

## Logs:
*No logs captured during this run.*

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/yarongilor/job/longevity-mv-sync/22/)
[Argus](https://argus.scylladb.com/test/21fd824f-2cea-493e-bcfc-c5bab2f8740d/runs?additionalRuns[]=67ab07ef-587e-4573-bd7b-df1ef99b8750)
</details>

**Comment by yarongilor** [comment]
[consoleFull.zip](https://github.com/user-attachments/files/18274264/consoleFull.zip)

**Comment by soyacz** [comment]
Likely it's jenkins issue we recently face: https://github.com/scylladb/scylla-cluster-tests/issues/9444
